Repository umbraco/Umbraco-CMS, pull requests merged in 2018-12, with the labels that each got.

#3757 Fix the changing source name when copying a node
  src/Umbraco.Web.UI.Client/src/views/content/content.copy.controller.js
  src/Umbraco.Web.UI.Client/src/views/content/copy.html
Labels: community/pr, type/bug

#3820 Reload the recycle bin when deleting an item
  src/Umbraco.Web.UI.Client/src/views/content/content.delete.controller.js
  src/Umbraco.Web.UI.Client/src/views/media/media.delete.controller.js
Labels: community/pr, release/7.13.0, type/feature

#3600 Optimized CombinedGuidsMediaPathScheme
  src/Umbraco.Core/ByteArrayExtensions.cs
  src/Umbraco.Core/GuidUtils.cs
  src/Umbraco.Core/HexEncoder.cs
  src/Umbraco.Core/IO/MediaPathSchemes/CombinedGuidsMediaPathScheme.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests.Benchmarks/CombineGuidBenchmarks.cs
  src/Umbraco.Tests.Benchmarks/HexStringBenchmarks.cs
  src/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
  src/Umbraco.Tests/CoreThings/GuidUtilsTests.cs
  src/Umbraco.Tests/CoreThings/HexEncoderTests.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
Labels: community/pr, state/hq-reply, type/feature

#3692 Honour 'Order Direction' passed into GetPagedResultsByQuery
  src/Umbraco.Core/Persistence/Repositories/EntityRepository.cs
Labels: state/hq-discussion-cms

#3827 Fix the disappearing action button by using a promise
  src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js
Labels: community/pr, release/7.13.0, type/bug

#3806 Show only the success message upon successful update of notifications
  src/Umbraco.Web.UI.Client/src/views/content/notify.html
Labels: community/pr, release/7.13.0, type/feature

#3773 Don't show "Create" and "Sort" for deleted items in the media tree
  src/Umbraco.Web/Trees/MediaTreeController.cs
Labels: community/pr, type/bug

#3762 V8: Make Nested Content support content variants
  src/Umbraco.Web/PropertyEditors/NestedContentPropertyEditor.cs
Labels: community/pr, release/8.0.0

#3781 V8: Fix and clean up the restore media dialog
  src/Umbraco.Web.UI.Client/src/views/media/media.restore.controller.js
  src/Umbraco.Web.UI.Client/src/views/media/restore.html
Labels: community/pr, type/bug

#3803 Add search to "move media" dialog
  src/Umbraco.Web.UI.Client/src/views/media/media.move.controller.js
  src/Umbraco.Web.UI.Client/src/views/media/move.html
Labels: community/pr, release/7.13.0, type/feature
