Repository umbraco/Umbraco-CMS, pull requests merged in 2018-11, with the labels that each got.

#3516 Fix expression visitor for WHERE IN
  src/Umbraco.Core/Persistence/Querying/ExpressionVisitorBase.cs
  src/Umbraco.Tests/Persistence/Querying/ExpressionTests.cs
Labels: state/review

#3715 Huntsman case - AuditLog was not returning NodeId from DB
  src/Umbraco.Core/Persistence/PetaPoco.cs
  src/Umbraco.Core/Persistence/Repositories/AuditRepository.cs
Labels: state/review, type/bug

#3782 U4-11088 - XML Data Integrity "Fix Button" not Visible
  src/Umbraco.Web/HealthCheck/Checks/DataIntegrity/XmlDataIntegrityHealthCheck.cs
Labels: community/pr, type/bug

#3736 Fix listview buttons alignment
  src/Umbraco.Web.UI.Client/src/views/components/umb-list-view-settings.html
Labels: community/pr, release/7.13.0, type/feature

#3582 Update ContentFinderByRedirectUrl.cs: only set headers for redirect IF redirect happens
  src/Umbraco.Web/Routing/ContentFinderByRedirectUrl.cs
Labels: community/pr, release/7.13.0, type/bug

#3761 V8: Fix YSODs when moving and copying things in the Settings section
  src/Umbraco.Core/Services/MoveOperationStatusType.cs
Labels: community/pr, release/8.0.0, type/bug
