Repository umbraco/Umbraco-CMS, pull requests merged in 2019-03, with the labels that each got.

#3464 3463 - Suggestion: Make checkboxes look prettier in checkbox lists
  src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbcheckbox.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbradiobutton.directive.js
  src/Umbraco.Web.UI.Client/src/less/belle.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-checkbox-list.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-form-check.less
  src/Umbraco.Web.UI.Client/src/less/property-editors.less
  src/Umbraco.Web.UI.Client/src/views/components/forms/umb-checkbox.html
  src/Umbraco.Web.UI.Client/src/views/components/forms/umb-radiobutton.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/checkboxlist/checkboxlist.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/radiobuttons/radiobuttons.html
Labels: community/pr, state/hq-discussion-ux, state/review, type/feature

#3851 Fixes binding of FormDataCollection for GET requests which fixes the …
  src/Umbraco.Web/Trees/ApplicationTreeController.cs
  src/Umbraco.Web/Trees/ContentTreeControllerBase.cs
  src/Umbraco.Web/Trees/MemberTreeController.cs
  src/Umbraco.Web/Trees/TreeControllerBase.cs
  src/Umbraco.Web/Umbraco.Web.csproj
  src/Umbraco.Web/WebApi/Filters/HttpQueryStringFilterAttribute.cs
  src/Umbraco.Web/WebApi/Filters/HttpQueryStringModelBinder.cs
Labels: release/7.14.0

#4803 Solution for not using scope() in grid redordering
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.getScopeHack.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.html
Labels: state/review

#4848 Modernize NuGet install
  build/NuSpecs/UmbracoCms.Core.nuspec
  build/NuSpecs/UmbracoCms.Web.nuspec
  build/NuSpecs/UmbracoCms.nuspec
  build/NuSpecs/tools/install.core.ps1
  build/NuSpecs/tools/install.ps1
Labels: release/8.0.1, type/feature

#4858 Fixes LogViewer if JSON log contains malformed JSON lines
  src/Umbraco.Core/Logging/Viewer/JsonLogViewer.cs
  src/Umbraco.Core/Logging/Viewer/LogViewerComposer.cs
  src/Umbraco.Tests/Logging/LogviewerTests.cs
Labels: state/review

#4735 Updated CONTRIBUTING_DETAILED to fit new npm setup
  .github/CONTRIBUTING_DETAILED.md
Labels: state/review

#4809 V8: makes document-details go on to two lines when necessary
  src/Umbraco.Web.UI.Client/src/less/components/umb-packages.less
Labels: state/review

#4754 V8: UI — updated login screen
  src/Umbraco.Web.UI.Client/src/less/pages/login.less
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-login.html
  src/Umbraco.Web.UI/Umbraco/assets/img/login.jpg
  src/Umbraco.Web.UI/config/umbracoSettings.Release.config
  src/Umbraco.Web.UI/config/umbracoSettings.config
Labels: state/review

#4853 Fixes javascript error when trying to unpublish an invariant item
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js
  src/Umbraco.Web.UI.Client/src/views/content/overlays/publish.controller.js
  src/Umbraco.Web.UI.Client/src/views/content/overlays/save.controller.js
  src/Umbraco.Web.UI.Client/src/views/content/overlays/schedule.controller.js
  src/Umbraco.Web.UI.Client/src/views/content/overlays/sendtopublish.controller.js
  src/Umbraco.Web.UI.Client/src/views/content/overlays/unpublish.controller.js
Labels: release/8.1.0, state/review, type/bug

#4906 changed umb-checkbox model to be the boolean property, not a object c…
  src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbcheckbox.directive.js
  src/Umbraco.Web.UI.Client/src/views/components/forms/umb-checkbox.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/checkboxlist/checkboxlist.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/checkboxlist/checkboxlist.html
Labels: state/review

#4956 V8: Fixed issue when creating variant content templates,
  src/Umbraco.Core/Services/Implement/ContentService.cs
Labels: state/review

#4908 Use umb-checkbox for all content variant dialogs
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
  src/Umbraco.Web.UI.Client/src/less/components/umb-list.less
  src/Umbraco.Web.UI.Client/src/views/content/overlays/publish.controller.js
  src/Umbraco.Web.UI.Client/src/views/content/overlays/publish.html
  src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.html
  src/Umbraco.Web.UI.Client/src/views/content/overlays/save.html
  src/Umbraco.Web.UI.Client/src/views/content/overlays/schedule.html
  src/Umbraco.Web.UI.Client/src/views/content/overlays/sendtopublish.html
  src/Umbraco.Web.UI.Client/src/views/content/overlays/unpublish.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/checkboxlist/checkboxlist.controller.js
  src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: category/ui, state/review

#4364 V8: fixed type of dashboards in EditorModelEventManager
  src/Umbraco.Web/Editors/DashboardController.cs
  src/Umbraco.Web/Editors/EditorModelEventManager.cs
Labels: release/8.1.0, state/review

#4994 Fixes the authorization for certain endpoints on the UsersController
  src/Umbraco.Web/Editors/UsersController.cs
  src/Umbraco.Web/Umbraco.Web.csproj
  src/Umbraco.Web/WebApi/Filters/AdminUsersAuthorizeAttribute.cs
  src/Umbraco.Web/WebApi/Filters/UmbracoApplicationAuthorizeAttribute.cs
Labels: state/review

#5002 Avoid removing a public method (used by forms 8.0.0)
  src/Umbraco.Web/Editors/EditorModelEventManager.cs
Labels: release/8.0.2, state/review

#4948 V8: Provide url in content lists for ability to open item in a new tab
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbcontentgrid.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbtable.directive.js
  src/Umbraco.Web.UI.Client/src/less/belle.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-content-grid.less
  src/Umbraco.Web.UI.Client/src/less/components/users/umb-user-cards.less
  src/Umbraco.Web.UI.Client/src/less/components/users/umb-user-table.less
  src/Umbraco.Web.UI.Client/src/less/listview.less
  src/Umbraco.Web.UI.Client/src/views/components/umb-content-grid.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-table.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/grid/grid.listviewlayout.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/list/list.listviewlayout.controller.js
  src/Umbraco.Web.UI.Client/src/views/users/views/users/users.controller.js
  src/Umbraco.Web.UI.Client/src/views/users/views/users/users.html
Labels: category/ux, state/review

#4822 V8: Hide empty sticky bar in Grid
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.html
Labels: state/review

#4454 V8: Improve plugin language handling
  src/Umbraco.Core/Composing/CompositionExtensions/Services.cs
  src/Umbraco.Core/Services/Implement/LocalizedTextServiceFileSources.cs
Labels: community/pr, release/8.1.0, state/backlog, type/feature

#5023 Make unpublished items in list view show with grey text-color on name
  src/Umbraco.Web.UI.Client/src/less/components/umb-table.less
  src/Umbraco.Web.UI.Client/src/less/components/users/umb-user-table.less
  src/Umbraco.Web.UI.Client/src/less/variables.less
  src/Umbraco.Web.UI.Client/src/views/components/umb-table.html
Labels: category/ui, state/review

#4974 Fixing code in sync functionality of checkbox-list
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/checkboxlist/checkboxlist.controller.js
Labels: state/review

#4961 Renamed LESS variables with disgrete to discreet
  src/Umbraco.Web.UI.Client/src/less/components/editor.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-file-dropzone.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-media-grid.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-node-preview.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-packages.less
  src/Umbraco.Web.UI.Client/src/less/listview.less
  src/Umbraco.Web.UI.Client/src/less/panel.less
  src/Umbraco.Web.UI.Client/src/less/property-editors.less
  src/Umbraco.Web.UI.Client/src/less/variables.less
Labels: state/review

#2441 U4 10147 - Bypass User Security option in pickers
  src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtreesearchbox.directive.js
  src/Umbraco.Web.UI.Client/src/common/resources/content.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/media.resource.js
  src/Umbraco.Web.UI.Client/src/common/services/search.service.js
  src/Umbraco.Web.UI.Client/src/views/common/overlays/contentpicker/contentpicker.html
  src/Umbraco.Web.UI.Client/src/views/common/overlays/linkpicker/linkpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/overlays/linkpicker/linkpicker.html
  src/Umbraco.Web.UI.Client/src/views/common/overlays/mediaPicker/mediapicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/overlays/treepicker/treepicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/overlays/treepicker/treepicker.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/media.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/rte.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/relatedlinks/relatedlinks.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.html
  src/Umbraco.Web/Editors/ContentController.cs
  src/Umbraco.Web/Editors/EntityController.cs
  src/Umbraco.Web/Editors/MediaController.cs
  src/Umbraco.Web/PropertyEditors/ContentPicker2PropertyEditor.cs
  src/Umbraco.Web/PropertyEditors/GridPropertyEditor.cs
  src/Umbraco.Web/PropertyEditors/MediaPicker2PropertyEditor.cs
  src/Umbraco.Web/PropertyEditors/MultiNodeTreePicker2PropertyEditor.cs
  src/Umbraco.Web/PropertyEditors/MultiUrlPickerPropertyEditor.cs
  src/Umbraco.Web/PropertyEditors/RelatedLinks2PropertyEditor.cs
  src/Umbraco.Web/PropertyEditors/RichTextPreValueEditor.cs
  src/Umbraco.Web/Search/UmbracoTreeSearcher.cs
  src/Umbraco.Web/Trees/ContentTreeControllerBase.cs
  src/Umbraco.Web/Trees/TreeControllerBase.cs
  src/Umbraco.Web/Trees/TreeQueryStringParameters.cs
  src/Umbraco.Web/WebApi/Filters/EnsureUserPermissionForContentAttribute.cs
  src/Umbraco.Web/WebApi/Filters/FilterAllowedOutgoingMediaAttribute.cs
Labels: state/hq-discussion-cms

#4978 Fixes front-end validation (4627)
  src/Umbraco.Web.UI.Client/src/common/directives/validation/valpropertymsg.directive.js
Labels: category/ux

#5063 V8: changed button styles for a better low hanging-fruit solution
  src/Umbraco.Web.UI.Client/src/views/dashboard/content/redirecturls.html
Labels: state/review

#5065 V8: UI changed notification style
  src/Umbraco.Web.UI.Client/src/common/services/notifications.service.js
  src/Umbraco.Web.UI.Client/src/less/components/notifications/umb-notifications.less
Labels: state/review

#5091 UI changes for Schedule Publishing
  src/Umbraco.Web.UI.Client/src/less/modals.less
  src/Umbraco.Web.UI.Client/src/less/properties.less
  src/Umbraco.Web.UI.Client/src/views/content/overlays/schedule.html
Labels: category/ui
