Repository umbraco/Umbraco-CMS, pull requests merged in 2019-02, with the labels that each got.

#4361 V8: Add descriptions to properties on default media items
  src/Umbraco.Core/Migrations/Install/DatabaseDataCreator.cs
Labels: state/sprint-backlog, type/feature

#4337 Web.Config AppSetting key conventions & move to constants class
  build/NuSpecs/tools/install.ps1
  src/Umbraco.Core/Composing/RegisterFactory.cs
  src/Umbraco.Core/Composing/TypeFinder.cs
  src/Umbraco.Core/Configuration/CoreDebug.cs
  src/Umbraco.Core/Configuration/GlobalSettings.cs
  src/Umbraco.Core/Configuration/UmbracoVersion.cs
  src/Umbraco.Core/Constants-AppSettings.cs
  src/Umbraco.Core/IO/SystemFiles.cs
  src/Umbraco.Core/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Core/Migrations/Upgrade/UmbracoUpgrader.cs
  src/Umbraco.Core/Models/Language.cs
  src/Umbraco.Core/Persistence/UmbracoDatabaseFactory.cs
  src/Umbraco.Core/Runtime/CoreRuntimeComposer.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests/App.config
  src/Umbraco.Tests/LegacyXmlPublishedCache/PublishedMediaCache.cs
  src/Umbraco.Tests/Runtimes/StandaloneTests.cs
  src/Umbraco.Tests/Security/BackOfficeCookieManagerTests.cs
  src/Umbraco.Web.UI/web.Template.config
  src/Umbraco.Web/Runtime/WebRuntimeComponent.cs
  src/Umbraco.Web/Security/ActiveDirectoryBackOfficeUserPasswordChecker.cs
Labels: state/review

#3485 V8 - #3434 - change checkboxes on property type settings to toggle
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/propertysettings/propertysettings.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/propertysettings/propertysettings.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-groups-builder.html
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: state/sprint-backlog, type/feature

#4357 V8: Media picker upload button does nothing
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
Labels: community/pr, state/sprint-backlog, type/bug

#4336 V8: Fix disappearing thumbnails in the media grid
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbmediagrid.directive.js
Labels: community/pr, state/review, type/bug

#4345 V8: Relation type editor crashes for root relations and is using excessive XHR
  src/Umbraco.Web.UI.Client/src/views/relationtypes/edit.controller.js
Labels: community/pr, state/review, type/bug

#4346 V8: Make Nested Content resilient towards culture variance in elements
  src/Umbraco.Web/PropertyEditors/NestedContentPropertyEditor.cs
Labels: community/pr, state/review, type/bug

#4422 V8: UI refactoring infinity editing to css animation
  src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditors.directive.js
  src/Umbraco.Web.UI.Client/src/less/components/editor/umb-editor.less
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-navigation.html
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editors.html
Labels: category/v8-alpha, state/review, type/bug

#4432 V8: Rename umbracoDomains table to umbracoDomain (singular)
  src/Umbraco.Core/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/RenameUmbracoDomainsTable.cs
  src/Umbraco.Core/Persistence/Constants-DatabaseSchema.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/DomainRepository.cs
  src/Umbraco.Core/Umbraco.Core.csproj
Labels: state/sprint-backlog, type/bug

#4465 V8: Bugfix for loading paths Ids into TreeEntityPath
  src/Umbraco.Core/Models/Entities/TreeEntityPath.cs
Labels: state/review

#4469 #4359 + #4360 umb editor navigation content apps anchor-dropdown
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbtabbedcontent.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbvariantcontent.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbvariantcontenteditors.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorcontentheader.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditornavigation.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditornavigationitem.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/util/getDomElement.directive.js
  src/Umbraco.Web.UI.Client/src/less/belle.less
  src/Umbraco.Web.UI.Client/src/less/canvas-designer.less
  src/Umbraco.Web.UI.Client/src/less/components/html/umb-group-panel.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-editor-navigation-item.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-editor-navigation.less
  src/Umbraco.Web.UI.Client/src/less/navs.less
  src/Umbraco.Web.UI.Client/src/views/components/content/edit.html
  src/Umbraco.Web.UI.Client/src/views/components/content/umb-tabbed-content.html
  src/Umbraco.Web.UI.Client/src/views/components/content/umb-variant-content-editors.html
  src/Umbraco.Web.UI.Client/src/views/components/content/umb-variant-content.html
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-content-header.html
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-navigation-item.html
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-navigation.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-dropdown.html
Labels: state/review

#4522 Reintroduced the forms section
  src/Umbraco.Core/Constants-Applications.cs
  src/Umbraco.Tests/Testing/UmbracoTestBase.cs
  src/Umbraco.Web.UI.Client/src/views/dashboard/dashboard.tabs.controller.js
  src/Umbraco.Web.UI.Client/src/views/dashboard/forms/formsdashboardintro.html
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
  src/Umbraco.Web/Dashboards/FormsDashboard.cs
  src/Umbraco.Web/Editors/SectionController.cs
  src/Umbraco.Web/Runtime/WebRuntimeComposer.cs
  src/Umbraco.Web/Trees/ApplicationTreeController.cs
  src/Umbraco.Web/Trees/FormsBackOfficeSection.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: state/review

#4514 #4430 change grid-editor settings to use editorService
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/editconfig.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/editconfig.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/layoutconfig.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/layoutconfig.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/rowconfig.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/rowconfig.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/rowdeleteconfirm.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/rowdeleteconfirm.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.prevalues.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.prevalues.html
Labels: state/review

#4535 Updated the tours to match v8
  src/Umbraco.Web.UI/config/BackOfficeTours/getting-started.json
  src/Umbraco.Web/PropertyEditors/TextAreaConfiguration.cs
  src/Umbraco.Web/PropertyEditors/TextAreaConfigurationEditor.cs
Labels: state/review

#4543 Temp8 ui clear distinguish property groups
  src/Umbraco.Web.UI.Client/src/less/components/html/umb-group-panel.less
Labels: state/review

#4539 V8 - Default logging set to JSON
  src/Umbraco.Core/Logging/Serilog/LoggerConfigExtensions.cs
  src/Umbraco.Core/Logging/Serilog/SerilogLogger.cs
  src/Umbraco.Web.UI/config/serilog.config
Labels: state/review

#4484 V8 Installer Steps for starter kit re-enabled
  src/Umbraco.Web/Composing/Composers/InstallerComposer.cs
  src/Umbraco.Web/Install/InstallStepCollection.cs
  src/Umbraco.Web/Install/InstallSteps/StarterKitCleanupStep.cs
  src/Umbraco.Web/Install/InstallSteps/StarterKitDownloadStep.cs
  src/Umbraco.Web/Install/InstallSteps/StarterKitInstallStep.cs
Labels: state/review

#4553 Refactor post-migrations
  src/Umbraco.Core/Components/CompositionExtensions.cs
  src/Umbraco.Core/Migrations/IMigrationContext.cs
  src/Umbraco.Core/Migrations/IPostMigration.cs
  src/Umbraco.Core/Migrations/Install/DatabaseBuilder.cs
  src/Umbraco.Core/Migrations/Install/DatabaseDataCreator.cs
  src/Umbraco.Core/Migrations/MigrationContext.cs
  src/Umbraco.Core/Migrations/MigrationPlan.cs
  src/Umbraco.Core/Migrations/PostMigrationCollection.cs
  src/Umbraco.Core/Migrations/PostMigrationCollectionBuilder.cs
  src/Umbraco.Core/Migrations/PostMigrations/IPublishedSnapshotRebuilder.cs
  src/Umbraco.Core/Migrations/PostMigrations/PublishedSnapshotRebuilder.cs
  src/Umbraco.Core/Migrations/PostMigrations/RebuildPublishedSnapshot.cs
  src/Umbraco.Core/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Core/Migrations/Upgrade/UmbracoUpgrader.cs
  src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/RadioAndCheckboxAndDropdownPropertyEditorsMigration.cs
  src/Umbraco.Core/Runtime/CoreRuntimeComposer.cs
  src/Umbraco.Core/RuntimeState.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests/Migrations/MigrationTests.cs
  src/Umbraco.Tests/Migrations/PostMigrationTests.cs
  src/Umbraco.Web/Editors/NuCacheStatusController.cs
  src/Umbraco.Web/Install/InstallSteps/DatabaseUpgradeStep.cs
  src/Umbraco.Web/Install/InstallSteps/SetUmbracoVersionStep.cs
  src/Umbraco.Web/Migrations/PostMigrations/ClearCsrfCookies.cs
  src/Umbraco.Web/Migrations/PostMigrations/PublishedSnapshotRebuilder.cs
  src/Umbraco.Web/PublishedCache/IPublishedSnapshotService.cs
  src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs
  src/Umbraco.Web/PublishedCache/PublishedSnapshotServiceBase.cs
  src/Umbraco.Web/Runtime/WebRuntimeComposer.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: state/review

#4552 UI datepicker style updated
  src/Umbraco.Web.UI.Client/src/less/forms.less
  src/Umbraco.Web.UI.Client/src/less/property-editors.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/datepicker/datepicker.html
Labels: state/review

#4534 Removing ClientDependency setup for non-web runtimes
  src/Umbraco.Web/Runtime/WebRuntimeComponent.cs
Labels: release/8.0.0

#4558 v8 - the GetByContentType methods for the content cache were not implemented
  src/Umbraco.Tests/LegacyXmlPublishedCache/PublishedContentCache.cs
  src/Umbraco.Web/PublishedCache/IPublishedCache.cs
  src/Umbraco.Web/PublishedCache/NuCache/ContentCache.cs
Labels: state/review

#4551 grey out icons in umb-tree when not published or allowed
  src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less
Labels: state/review

#4344 V8: Align dialogs in the Settings section
  src/Umbraco.Web.UI.Client/src/views/macros/delete.html
  src/Umbraco.Web.UI.Client/src/views/partialviewmacros/create.html
  src/Umbraco.Web.UI.Client/src/views/partialviews/create.html
  src/Umbraco.Web.UI.Client/src/views/relationtypes/create.html
  src/Umbraco.Web.UI.Client/src/views/stylesheets/create.html
Labels: community/pr, state/backlog, type/bug

#4462 v8: Fix closing infinite editors through Escape key
  src/Umbraco.Web.UI.Client/src/less/panel.less
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macropicker/macropicker.html
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.html
  src/Umbraco.Web.UI.Client/src/views/documenttypes/edit.html
  src/Umbraco.Web.UI.Client/src/views/media/edit.html
  src/Umbraco.Web.UI.Client/src/views/mediatypes/edit.html
  src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: community/pr, type/feature

#4557 Use ChangesMonitor to prevent unwanted restarts during install/upgrade
  src/Umbraco.Web/Install/ChangesMonitor.cs
  src/Umbraco.Web/Install/FilePermissionHelper.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: state/review

#4626 v8 - removal of "Created" events that shouldn't exist
  src/Umbraco.Core/Services/Implement/ContentService.cs
  src/Umbraco.Core/Services/Implement/MediaService.cs
  src/Umbraco.Core/Services/Implement/MemberService.cs
  src/Umbraco.Tests/Services/MemberServiceTests.cs
  src/Umbraco.Web/PropertyEditors/PropertyEditorsComponent.cs
Labels: category/breaking, release/8.0.0, state/review

#4639 v8 - reverts the list view changes that opened sub items in infinite editors
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/grid/grid.listviewlayout.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/list/list.listviewlayout.controller.js
Labels: state/review

#4640 v8 - fix publishing new content when there are validation problems
  src/Umbraco.Web/Editors/ContentController.cs
Labels: release/8.0.0, state/review, type/bug

#4650 V8 - Typo FilderedControllerFactory in CompositionExtensions
  src/Umbraco.Web/CompositionExtensions.cs
Labels: release/8.1.0, state/backlog, type/bug
