Repository umbraco/Umbraco-CMS, pull requests merged in 2019-05, with the labels that each got.

#5387 Added margin-left: 5px; to achieve the needed whitespace, couldn't figu…
  src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-button.less
Labels: state/review

#5371 Removing a no longer relevant section
  src/Umbraco.Web.UI.Client/docs/src/api/index.ngdoc
Labels: release/8.1.0, state/review, type/bug

#5390 Add back the ability to use a custom 2-factor auth screen
  src/Umbraco.Web.UI.Client/src/common/directives/components/application/umblogin.directive.js
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-login.html
  src/Umbraco.Web/Editors/AuthenticationController.cs
  src/Umbraco.Web/Security/BackOfficeSignInManager.cs
Labels: release/8.1.0, type/bug

#5375 V8: Make async file logging possible with serilog
  build/NuSpecs/UmbracoCms.nuspec
  build/NuSpecs/tools/serilog.config.install.xdt
  src/Umbraco.Core/Logging/Serilog/LoggerConfigExtensions.cs
  src/Umbraco.Core/Logging/Serilog/SerilogLogger.cs
  src/Umbraco.Core/Logging/Viewer/JsonLogViewer.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Web.UI/config/serilog.Release.config
  src/Umbraco.Web/UmbracoApplicationBase.cs
  src/umbraco.sln
Labels: state/review

#5226 Accessibility and UI update of umb-tags
  src/Umbraco.Web.UI.Client/src/common/directives/components/tags/umbtagseditor.directive.js
  src/Umbraco.Web.UI.Client/src/less/main.less
  src/Umbraco.Web.UI.Client/src/less/property-editors.less
  src/Umbraco.Web.UI.Client/src/less/typeahead.less
  src/Umbraco.Web.UI.Client/src/views/components/tags/umb-tags-editor.html
Labels: category/accessibility, category/ui, release/8.1.0, state/review

#5389 V8 improved focus state of umb-form-check inputs
  src/Umbraco.Web.UI.Client/src/controllers/main.controller.js
  src/Umbraco.Web.UI.Client/src/less/components/umb-form-check.less
Labels: release/8.1.0, state/review

#5353 V8: ClipboardService + implementation for nested content
  src/Umbraco.Web.UI.Client/src/common/directives/components/overlays/umboverlay.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbnestedcontent.directive.js
  src/Umbraco.Web.UI.Client/src/common/filters/truncate.filter.js
  src/Umbraco.Web.UI.Client/src/common/services/clipboard.service.js
  src/Umbraco.Web.UI.Client/src/common/services/overlay.service.js
  src/Umbraco.Web.UI.Client/src/less/belle.less
  src/Umbraco.Web.UI.Client/src/less/components/card.less
  src/Umbraco.Web.UI.Client/src/less/components/overlays.less
  src/Umbraco.Web.UI.Client/src/less/components/overlays/umb-itempicker.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-nested-content.less
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypepicker/datatypepicker.html
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/itempicker/itempicker.html
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macropicker/macropicker.html
  src/Umbraco.Web.UI.Client/src/views/common/overlays/itempicker/itempicker.html
  src/Umbraco.Web.UI.Client/src/views/common/overlays/mediatypepicker/mediatypepicker.html
  src/Umbraco.Web.UI.Client/src/views/components/overlays/umb-overlay.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.html
  src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: category/front-end, category/ux, release/8.1.0, state/review

#5448 V8: Hide "Create new" header in Nested Content create item dialog if all items are filtered out
  src/Umbraco.Web.UI.Client/src/views/common/overlays/itempicker/itempicker.html
Labels: release/8.1.0

#5450 Login errors are not identified for screen reader users
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-login.html
Labels: category/accessibility

#5458 Issue#5277 13
  src/Umbraco.Web.UI.Client/src/less/sections.less
Labels: category/accessibility
