Repository umbraco/Umbraco-CMS, pull requests merged in 2019-12, with the labels that each got.

#7253 8.4RC: MediaIndexPopulator should use IUmbracoContentIndex instead of Umbrac…
  src/Umbraco.Examine/MediaIndexPopulator.cs
Labels: state/estimation

#7282 Basic setup for differentiating compile modes in gulp
  build/build.ps1
  src/Umbraco.Web.UI.Client/gulp/config.js
  src/Umbraco.Web.UI.Client/gulp/modes.js
  src/Umbraco.Web.UI.Client/gulp/util/processLess.js
  src/Umbraco.Web.UI.Client/gulpfile.js
Labels: state/backlog

#7075 Wrong media path stored in database
  src/Umbraco.Core/ContentExtensions.cs
  src/Umbraco.Core/Models/MediaExtensions.cs
  src/Umbraco.Core/Persistence/Factories/ContentBaseFactory.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/MediaRepository.cs
  src/Umbraco.Core/PropertyEditors/IDataEditorWithMediaPath.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests/Routing/MediaUrlProviderTests.cs
  src/Umbraco.Tests/Services/MediaServiceTests.cs
  src/Umbraco.Tests/TestHelpers/Entities/MockedContentTypes.cs
  src/Umbraco.Web/PropertyEditors/FileUploadPropertyEditor.cs
  src/Umbraco.Web/PropertyEditors/ImageCropperPropertyEditor.cs
  src/Umbraco.Web/Routing/DefaultMediaUrlProvider.cs
Labels: state/estimation

#7349 PreviewBadge with option to open in PreviewMode in BackOffice…
  src/Umbraco.Web.UI/config/umbracoSettings.Release.config
  src/Umbraco.Web.UI/config/umbracoSettings.config
  src/Umbraco.Web/HtmlHelperRenderExtensions.cs
  src/Umbraco.Web/Mvc/UmbracoViewPageOfTModel.cs
Labels: category/ui, category/ux

#7105 Added Ids to inputs so the label in umb-control-group gets linked
  src/Umbraco.Web.UI.Client/src/views/components/users/change-password.html
Labels: category/accessibility

#7283 Update noUiSlider to v14.1 for accessibility
  src/Umbraco.Web.UI.Client/package.json
Labels: category/accessibility

#6898 Log Viewer - Fix search toggle accessibility
  src/Umbraco.Web.UI.Client/src/views/logviewer/search.html
Labels: category/accessibility, release/8.6.0, release/no-notes

#7001 Accessibility fix to umb-user-group-preview
  src/Umbraco.Web.UI.Client/src/views/components/users/umb-user-group-preview.html
Labels: category/accessibility

#7376 Property Actions for Property Editor with Controllers
  src/Umbraco.Web.UI.Client/src/common/directives/components/property/umbproperty.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/property/umbpropertyeditor.directive.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.controller.js
Labels: category/front-end

#7315 Adding extra validation for anti forgery tokens
  src/Umbraco.Web/Mvc/ValidateMvcAngularAntiForgeryTokenAttribute.cs
  src/Umbraco.Web/Security/BackOfficeCookieAuthenticationProvider.cs
  src/Umbraco.Web/WebApi/Filters/ValidateAngularAntiForgeryTokenAttribute.cs
Labels: release/8.6.0, type/bug

#7011 Accessibility improvements to Multivalues view
  src/Umbraco.Web.UI.Client/src/views/prevalueeditors/multivalues.html
Labels: category/accessibility
