Repository umbraco/Umbraco-CMS, pull requests merged in 2019-01, with the labels that each got.

#4009 Add null checking for translation details
  src/Umbraco.Web/umbraco.presentation/umbraco/translation/details.aspx.cs
Labels: community/pr, type/bug

#4164 Fixes for broken views..
  src/Umbraco.Tests/Cache/PublishedCache/PublishedMediaCacheTests.cs
  src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/ListChildPagesOrderedByProperty.cshtml
  src/Umbraco.Web.UI/Views/Partials/Grid/Editors/TextString.cshtml
Labels: state/review

#2926 V8 LogViewer
  src/Umbraco.Core/Constants-Applications.cs
  src/Umbraco.Core/EnumerableExtensions.cs
  src/Umbraco.Core/Logging/Viewer/CountingFilter.cs
  src/Umbraco.Core/Logging/Viewer/ErrorCounterFilter.cs
  src/Umbraco.Core/Logging/Viewer/ExpressionFilter.cs
  src/Umbraco.Core/Logging/Viewer/ILogFilter.cs
  src/Umbraco.Core/Logging/Viewer/ILogViewer.cs
  src/Umbraco.Core/Logging/Viewer/JsonLogViewer.cs
  src/Umbraco.Core/Logging/Viewer/LogLevelCounts.cs
  src/Umbraco.Core/Logging/Viewer/LogMessage.cs
  src/Umbraco.Core/Logging/Viewer/LogTemplate.cs
  src/Umbraco.Core/Logging/Viewer/LogViewerComposer.cs
  src/Umbraco.Core/Logging/Viewer/LogViewerSourceBase.cs
  src/Umbraco.Core/Logging/Viewer/MessageTemplateFilter.cs
  src/Umbraco.Core/Logging/Viewer/SavedLogSearch.cs
  src/Umbraco.Core/Migrations/Install/DatabaseSchemaCreator.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests/Composing/TypeFinderTests.cs
  src/Umbraco.Tests/Logging/LogviewerTests.cs
  src/Umbraco.Tests/Logging/UmbracoTraceLog.UNITTEST.20181112.json
  src/Umbraco.Tests/Logging/logviewer.searches.config.js
  src/Umbraco.Tests/Umbraco.Tests.csproj
  src/Umbraco.Web.UI.Client/gulpfile.js
  src/Umbraco.Web.UI.Client/src/common/resources/logviewer.resource.js
  src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js
  src/Umbraco.Web.UI.Client/src/views/common/overlays/logviewersearch/logviewersearch.html
  src/Umbraco.Web.UI.Client/src/views/logviewer/overview.controller.js
  src/Umbraco.Web.UI.Client/src/views/logviewer/overview.html
  src/Umbraco.Web.UI.Client/src/views/logviewer/search.controller.js
  src/Umbraco.Web.UI.Client/src/views/logviewer/search.html
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
  src/Umbraco.Web.UI/config/logviewer.searches.config.js
  src/Umbraco.Web/Editors/BackOfficeServerVariables.cs
  src/Umbraco.Web/Editors/LogViewerController.cs
  src/Umbraco.Web/Trees/LogViewerTreeController.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: state/review

#4136 V8: Clean up trashed content options
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/components/content/edit.html
  src/Umbraco.Web/Editors/ContentController.cs
Labels: community/pr

#4114 Temp8 ui expansion panel hover
  src/Umbraco.Web.UI.Client/src/less/components/html/umb-expansion-panel.less
Labels: state/review

#4211 Fixme - Handled "Method with optional parameter is hidden by overload" issues
  src/Umbraco.Web/PublishedContentExtensions.cs
Labels: state/review

#4212 Fixme - Only allow local KeepAlive Pings requests
  src/Umbraco.Web/Editors/KeepAliveController.cs
  src/Umbraco.Web/Mvc/OnlyLocalRequestsAttribute.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: state/review

#4240 Changed Fixme/task to TODO [Link]
  src/Umbraco.Core/Cache/HttpRequestAppCache.cs
  src/Umbraco.Core/Configuration/UmbracoVersion.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/DataTypeRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/DocumentRepository.cs
  src/Umbraco.Web/PublishedContentExtensions.cs
Labels: state/review

#4259 Remove related links and migrate existing data to Multi URL Picker
  src/Umbraco.Core/Constants-PropertyEditors.cs
  src/Umbraco.Core/Migrations/Install/DatabaseDataCreator.cs
  src/Umbraco.Core/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/ConvertRelatedLinksToMultiUrlPicker.cs
  src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/PropertyEditorsMigration.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests/Composing/TypeLoaderTests.cs
  src/Umbraco.Tests/Services/ContentServiceTests.cs
  src/Umbraco.Tests/TestHelpers/Entities/MockedContent.cs
  src/Umbraco.Tests/TestHelpers/Entities/MockedContentTypes.cs
  src/Umbraco.Tests/Web/Mvc/HtmlHelperExtensionMethodsTests.cs
  src/Umbraco.Web/HtmlHelperRenderExtensions.cs
  src/Umbraco.Web/Models/RelatedLink.cs
  src/Umbraco.Web/Models/RelatedLinkBase.cs
  src/Umbraco.Web/Models/RelatedLinkType.cs
  src/Umbraco.Web/Models/RelatedLinks.cs
  src/Umbraco.Web/PropertyEditors/MultiUrlPickerPropertyEditor.cs
  src/Umbraco.Web/PropertyEditors/RelatedLinksConfiguration.cs
  src/Umbraco.Web/PropertyEditors/RelatedLinksConfigurationEditor.cs
  src/Umbraco.Web/PropertyEditors/RelatedLinksPropertyEditor.cs
  src/Umbraco.Web/PropertyEditors/ValueConverters/RelatedLinksLegacyValueConverter.cs
  src/Umbraco.Web/PropertyEditors/ValueConverters/RelatedLinksValueConverter.cs
  src/Umbraco.Web/RelatedLinksTypeConverter.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: state/review

#4277 V8: Removing legacy webservices
  src/Umbraco.Core/IO/SystemDirectories.cs
  src/Umbraco.Core/Sync/ServerSyncWebServiceClient.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Core/UriExtensions.cs
  src/Umbraco.Tests/Composing/TypeFinderTests.cs
  src/Umbraco.Tests/CoreThings/UriExtensionsTests.cs
  src/Umbraco.Tests/IO/IoHelperTests.cs
  src/Umbraco.Web/Mvc/BackOfficeArea.cs
  src/Umbraco.Web/Routing/WebServicesRouteConstraint.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: state/sprint-backlog

#4286 V8: Don't fail the install if the user opts out of a custom machine key
  src/Umbraco.Web/Install/InstallSteps/ConfigureMachineKey.cs
Labels: state/sprint-backlog

#4276 V8: Validate file system folder names
  src/Umbraco.Web.UI.Client/src/views/partialviewmacros/create.html
  src/Umbraco.Web.UI.Client/src/views/partialviews/create.html
  src/Umbraco.Web.UI.Client/src/views/scripts/create.html
  src/Umbraco.Web.UI.Client/src/views/stylesheets/create.html
  src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
  src/Umbraco.Web/Editors/CodeFileController.cs
Labels: state/sprint-backlog, type/bug

#4249 V8 Remove unused filesystemproviders.config
  build/NuSpecs/tools/Web.config.install.xdt
  src/Umbraco.Core/Configuration/FileSystemProviderElement.cs
  src/Umbraco.Core/Configuration/FileSystemProviderElementCollection.cs
  src/Umbraco.Core/Configuration/FileSystemProvidersSection.cs
  src/Umbraco.Core/Configuration/IFileSystemProviderElement.cs
  src/Umbraco.Core/Configuration/IFileSystemProvidersSection.cs
  src/Umbraco.Core/Sync/DatabaseServerRegistrar.cs
  src/Umbraco.Core/Sync/SingleServerRegistrar.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests/App.config
  src/Umbraco.Tests/Configurations/FileSystemProviderTests.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  src/Umbraco.Web.UI/config/FileSystemProviders.Release.config
  src/Umbraco.Web.UI/config/FileSystemProviders.config
  src/Umbraco.Web.UI/web.Template.config
  src/Umbraco.Web/PublishedCache/NuCache/ContentNode.cs
Labels: state/review

#4298 PartialView & PartialViewMacros template generation fix
  src/Umbraco.Core/Services/Implement/FileService.cs
Labels: state/review

#4300 V8: Respect the name casing when creating a new template
  src/Umbraco.Core/Services/IFileService.cs
  src/Umbraco.Core/Services/Implement/FileService.cs
  src/Umbraco.Tests/Services/FileServiceTests.cs
  src/Umbraco.Web/Editors/TemplateController.cs
Labels: state/review, type/bug

#4278 V8: Removing legacy content tree menu items
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  src/Umbraco.Web/Models/Trees/MenuItem.cs
  src/Umbraco.Web/Trees/ContentTreeController.cs
  src/Umbraco.Web/Trees/LegacyTreeDataConverter.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: state/sprint-backlog

#4288 V8: Align delete dialogs with the other dialogs (take two)
  src/Umbraco.Web.UI.Client/src/views/components/umb-confirm.html
  src/Umbraco.Web.UI.Client/src/views/content/delete.html
  src/Umbraco.Web.UI.Client/src/views/content/emptyrecyclebin.html
  src/Umbraco.Web.UI.Client/src/views/contentblueprints/delete.html
  src/Umbraco.Web.UI.Client/src/views/datatypes/delete.html
  src/Umbraco.Web.UI.Client/src/views/dictionary/delete.html
  src/Umbraco.Web.UI.Client/src/views/documenttypes/delete.html
  src/Umbraco.Web.UI.Client/src/views/macros/delete.html
  src/Umbraco.Web.UI.Client/src/views/media/delete.html
  src/Umbraco.Web.UI.Client/src/views/media/emptyrecyclebin.html
  src/Umbraco.Web.UI.Client/src/views/mediatypes/delete.html
  src/Umbraco.Web.UI.Client/src/views/member/delete.html
  src/Umbraco.Web.UI.Client/src/views/membergroups/delete.html
  src/Umbraco.Web.UI.Client/src/views/membertypes/delete.html
  src/Umbraco.Web.UI.Client/src/views/partialviewmacros/delete.html
  src/Umbraco.Web.UI.Client/src/views/partialviews/delete.html
  src/Umbraco.Web.UI.Client/src/views/relationtypes/delete.html
  src/Umbraco.Web.UI.Client/src/views/scripts/delete.html
  src/Umbraco.Web.UI.Client/src/views/stylesheets/delete.html
  src/Umbraco.Web.UI.Client/src/views/templates/delete.html
Labels: state/sprint-backlog

#4210 Fixme - Handle not implemented exception on pick of macro
  src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js
  src/Umbraco.Web.UI.Client/src/common/services/macro.service.js
  src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macropicker/macropicker.html
  src/Umbraco.Web/Editors/EntityController.cs
  src/Umbraco.Web/Editors/TemplateQueryController.cs
  src/Umbraco.Web/Models/TemplateQuery/OperatorFactory.cs
  src/Umbraco.Web/Models/TemplateQuery/QueryCondition.cs
  src/Umbraco.Web/Models/TemplateQuery/QueryConditionExtensions.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: state/review
