Repository umbraco/Umbraco-CMS, pull requests merged in 2019-08, with the labels that each got.

#6038 Fixes how examine starts up to make it easier for custom index developers
  src/Umbraco.Examine/ContentValueSetBuilder.cs
  src/Umbraco.Examine/ExamineExtensions.cs
  src/Umbraco.Examine/IndexRebuilder.cs
  src/Umbraco.Examine/LuceneIndexDiagnostics.cs
  src/Umbraco.Examine/Umbraco.Examine.csproj
  src/Umbraco.Examine/UmbracoExamineIndexDiagnostics.cs
  src/Umbraco.Web/Search/BackgroundIndexRebuilder.cs
  src/Umbraco.Web/Search/ExamineComponent.cs
  src/Umbraco.Web/Search/ExamineComposer.cs
  src/Umbraco.Web/Search/ExamineFinalComponent.cs
  src/Umbraco.Web/Search/ExamineFinalComposer.cs
  src/Umbraco.Web/Search/ExamineUserComponent.cs
  src/Umbraco.Web/Search/GenericIndexDiagnostics.cs
  src/Umbraco.Web/Suspendable.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: release/8.1.2, type/bug

#6019 v8 Changing a property type from invariant to variant and back again causes issues with reporting that a document is edited or not
  src/Umbraco.Core/Models/IContentTypeBase.cs
  src/Umbraco.Core/Persistence/Factories/PropertyFactory.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/DocumentRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/MediaTypeRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/MemberTypeRepository.cs
  src/Umbraco.Tests/Persistence/Repositories/ContentTypeRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/DocumentRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/DomainRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/MediaRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/MediaTypeRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/MemberRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/MemberTypeRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/PublicAccessRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/TagRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/TemplateRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/UserRepositoryTest.cs
  src/Umbraco.Tests/Services/ContentServicePerformanceTest.cs
  src/Umbraco.Tests/Services/ContentServiceTests.cs
  src/Umbraco.Tests/Services/ContentTypeServiceTests.cs
  src/Umbraco.Tests/Services/ContentTypeServiceVariantsTests.cs
Labels: release/8.1.2, state/estimation, type/bug

#5760 V8: Accessibility improvements for page name entry
  src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorcontentheader.directive.js
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-content-header.html
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: category/accessibility

#5940 Remove unused .visuallyhidden class from main.less
  src/Umbraco.Web.UI.Client/src/less/main.less
Labels: category/accessibility

#5942 Accessibility: Ensure "cancel" is clickable from move/restore dialogs
  src/Umbraco.Web.UI.Client/src/views/content/move.html
  src/Umbraco.Web.UI.Client/src/views/content/restore.html
  src/Umbraco.Web.UI.Client/src/views/datatypes/move.html
  src/Umbraco.Web.UI.Client/src/views/documenttypes/copy.html
  src/Umbraco.Web.UI.Client/src/views/documenttypes/move.html
  src/Umbraco.Web.UI.Client/src/views/media/move.html
  src/Umbraco.Web.UI.Client/src/views/media/restore.html
  src/Umbraco.Web.UI.Client/src/views/mediatypes/copy.html
  src/Umbraco.Web.UI.Client/src/views/mediatypes/move.html
Labels: category/accessibility

#5970 Accessibility: Open User Details - Back icon arrow is identified as "Umbraco link"
  src/Umbraco.Web.UI.Client/src/less/components/editor.less
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-content-header.html
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-header.html
  src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: category/accessibility, community/pr, release/8.2.0, type/feature

#5964 Accessibility: Unable to navigate to close 'X' icon with keyboard
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-tour.html
  src/Umbraco.Web.UI.Client/src/views/components/application/umbtour/umb-tour-step.html
Labels: category/accessibility

#5944 Accessibility: Media uploader widget can't be accessed via keyboard
  src/Umbraco.Web.UI.Client/src/less/components/umb-file-dropzone.less
  src/Umbraco.Web.UI.Client/src/views/components/upload/umb-file-dropzone.html
  src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: category/accessibility, community/pr, release/8.2.0, type/feature

#5930 Accessibility: Open Package - Identifies back button as "Left hand arrow back button"
  src/Umbraco.Web.UI.Client/src/less/components/umb-packages.less
  src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.html
  src/Umbraco.Web.UI.Client/src/views/packages/views/install-local.html
  src/Umbraco.Web.UI.Client/src/views/packages/views/installed.html
  src/Umbraco.Web.UI.Client/src/views/packages/views/repo.html
  src/Umbraco.Web.UI.Client/src/views/users/views/users/users.html
Labels: category/accessibility, community/pr, release/8.2.0, type/feature

#6073 Make it possible to select styles on selected text in distraction free mode.
  src/Umbraco.Web.UI/config/tinyMceConfig.Release.config
  src/Umbraco.Web.UI/config/tinyMceConfig.config
Labels: community/pr, type/feature

#6114 Disable Mini Profiler
  src/Umbraco.Web/Profiling/WebProfilerProvider.cs
Labels: release/7.15.3, type/bug

#6125 Removing legacyAjaxCalls.ValidateUser method
  src/Umbraco.Web/umbraco.presentation/umbraco/webservices/legacyAjaxCalls.asmx.cs
Labels: category/breaking, release/7.15.3

#6137 Secure svg media files preview
  src/Umbraco.Web.UI.Client/src/common/directives/components/media/umbmedianodeinfo.directive.js
  src/Umbraco.Web.UI.Client/src/views/components/media/umb-media-node-info.html
Labels: type/bug

#6092 Ability to distinguish document types with same name in Nested Content config
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.doctypepicker.html
Labels: community/pr, type/feature

#6182 Secure svg media files preview - v8
  src/Umbraco.Web.UI.Client/src/common/directives/components/media/umbmedianodeinfo.directive.js
  src/Umbraco.Web.UI.Client/src/views/components/media/umb-media-node-info.html
Labels: type/bug

#6142 V8: Prevent double click errors when editing compositions
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js
  src/Umbraco.Web.UI.Client/src/views/components/umb-groups-builder.html
Labels: community/pr, type/feature
