Repository umbraco/Umbraco-CMS, pull requests merged in 2019-10, with the labels that each got.

#6568 Allow pasted & dragged images that are not yet saved to allow ALT text to be edited
  src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
Labels: release/8.2.0, type/bug

#6556 Only allow one media folder to be picked for RTE paste/drag image upload location
  src/Umbraco.Web.UI.Client/src/views/prevalueeditors/mediafolderpicker.controller.js
Labels: release/8.2.0, type/bug

#6493 Fixes null reference caused in GridPropertyValueEditor when the value is empty
  src/Umbraco.Web/PropertyEditors/GridPropertyEditor.cs
Labels: release/8.2.1, state/estimation, type/bug

#6582 V8: Split IndexCreator and Index config methods
  src/Umbraco.Examine/IUmbracoIndexConfig.cs
  src/Umbraco.Examine/Umbraco.Examine.csproj
  src/Umbraco.Examine/UmbracoIndexConfig.cs
  src/Umbraco.Web/Search/ExamineComposer.cs
  src/Umbraco.Web/Search/UmbracoIndexesCreator.cs
Labels: release/8.3.0

#6501 Removed Microsoft.Net.Compilers dependency
  build/NuSpecs/UmbracoCms.nuspec
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
Labels: hacktoberfest/contrib-2019

#6530 Fixes Search an element from its GUID with the backoffice #6185
  src/Umbraco.Web/Search/UmbracoTreeSearcher.cs
  src/Umbraco.Web/Trees/ContentTreeController.cs
  src/Umbraco.Web/Trees/ContentTreeControllerBase.cs
  src/Umbraco.Web/Trees/ContentTypeTreeController.cs
  src/Umbraco.Web/Trees/DataTypeTreeController.cs
  src/Umbraco.Web/Trees/MediaTreeController.cs
  src/Umbraco.Web/Trees/MediaTypeTreeController.cs
  src/Umbraco.Web/Trees/TemplatesTreeController.cs
Labels: hacktoberfest/contrib-2019

#6537 Makes it possible to change the icon for list view content apps
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/icon.prevalues.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/icon.prevalues.html
  src/Umbraco.Web/ContentApps/ListViewContentAppFactory.cs
  src/Umbraco.Web/PropertyEditors/ListViewConfiguration.cs
Labels: hacktoberfest/contrib-2019

#6586 Pick macro parameters in an infinite editor like content type properties
  src/Umbraco.Web.UI.Client/src/common/resources/macro.resource.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypepicker/datatypepicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypepicker/datatypepicker.html
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macroparameterpicker/macroparameterpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macroparameterpicker/macroparameterpicker.html
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macropicker/macropicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macropicker/macropicker.html
  src/Umbraco.Web.UI.Client/src/views/macros/infiniteeditors/parameter.controller.js
  src/Umbraco.Web.UI.Client/src/views/macros/infiniteeditors/parameter.html
  src/Umbraco.Web.UI.Client/src/views/macros/macros.edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/macros/views/macro.parameters.controller.js
  src/Umbraco.Web.UI.Client/src/views/macros/views/parameters.html
  src/Umbraco.Web.UI.Client/src/views/macros/views/settings.html
  src/Umbraco.Web/Editors/MacrosController.cs
Labels: state/hq-discussion-cms

#6592 Correct URL decoding of macro partial view names
  src/Umbraco.Web.UI.Client/src/views/macros/views/macro.settings.controller.js
  src/Umbraco.Web.UI.Client/src/views/packages/edit.controller.js
Labels: hacktoberfest/contrib-2019

#6596 Hide icons and use buttons instead of empty anchors in Examine dashboard
  src/Umbraco.Web.UI.Client/src/less/tables.less
  src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.html
  src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: category/accessibility, community/pr, hacktoberfest/contrib-2019, release/8.3.0, type/feature

#6628 install ngAria
  src/Umbraco.Web.UI.Client/gulp/tasks/dependencies.js
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/app.js
  src/Umbraco.Web.UI.Client/src/install.loader.js
  src/Umbraco.Web.UI.Client/test/config/karma.conf.js
  src/Umbraco.Web/JavaScript/JsInitialize.js
Labels: category/accessibility, community/pr, hacktoberfest/contrib-2019, release/8.3.0, type/feature

#6755 V8: Make the color class prefix configurable for <umb-color-swatches/>
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbcolorswatches.directive.js
  src/Umbraco.Web.UI.Client/src/views/components/umb-color-swatches.html
Labels: community/pr, hacktoberfest/contrib-2019, release/8.3.0, type/feature

#6689 V8 - umb-box-header shows values for non-localized and localized title and description
  src/Umbraco.Web.UI.Client/src/common/directives/components/html/umbbox/umbboxheader.directive.js
  src/Umbraco.Web.UI.Client/src/views/components/html/umb-box/umb-box-header.html
Labels: community/pr, hacktoberfest/contrib-2019, release/8.3.0, type/feature

#6208 Support for Segments in ContentTypeRepositoryBase
  src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs
  src/Umbraco.Tests/Services/ContentTypeServiceVariantsTests.cs
Labels: category/segments

#6688 Long running operations causes SQL timeout
  src/Umbraco.Core/Persistence/DatabasenodeLockExtensions.cs
  src/Umbraco.Core/Persistence/SqlSyntax/ISqlSyntaxProvider.cs
  src/Umbraco.Core/Persistence/SqlSyntax/SqlCeSyntaxProvider.cs
  src/Umbraco.Core/Persistence/SqlSyntax/SqlServerSyntaxProvider.cs
  src/Umbraco.Core/Persistence/SqlSyntax/SqlSyntaxProviderBase.cs
  src/Umbraco.Core/Persistence/UmbracoDatabase.cs
  src/Umbraco.Core/Scoping/Scope.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests/Models/UserExtensionsTests.cs
  src/Umbraco.Tests/Persistence/LocksTests.cs
  src/Umbraco.Tests/Persistence/UnitOfWorkTests.cs
Labels: type/bug

#6625 Data type usage reporting and deletion warning
  src/Umbraco.Core/Persistence/Repositories/IDataTypeRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/DataTypeRepository.cs
  src/Umbraco.Core/Services/IContentTypeServiceBase.cs
  src/Umbraco.Core/Services/IDataTypeService.cs
  src/Umbraco.Core/Services/Implement/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
  src/Umbraco.Core/Services/Implement/DataTypeService.cs
  src/Umbraco.Tests/Persistence/Repositories/DataTypeDefinitionRepositoryTest.cs
  src/Umbraco.Tests/TestHelpers/TestObjects-Mocks.cs
  src/Umbraco.Web.UI.Client/lib/bootstrap/less/tables.less
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbconfirm.directive.js
  src/Umbraco.Web.UI.Client/src/common/filters/umbCmsJoinArray.filter.js
  src/Umbraco.Web.UI.Client/src/common/resources/datatype.resource.js
  src/Umbraco.Web.UI.Client/src/init.js
  src/Umbraco.Web.UI.Client/src/less/components/umb-table.less
  src/Umbraco.Web.UI.Client/src/less/tables.less
  src/Umbraco.Web.UI.Client/src/views/components/umb-confirm.html
  src/Umbraco.Web.UI.Client/src/views/datatypes/datatype.delete.controller.js
  src/Umbraco.Web.UI.Client/src/views/datatypes/datatype.edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/datatypes/delete.html
  src/Umbraco.Web.UI.Client/src/views/datatypes/edit.html
  src/Umbraco.Web.UI.Client/src/views/datatypes/views/datatype.references.controller.js
  src/Umbraco.Web.UI.Client/src/views/datatypes/views/datatype.references.html
  src/Umbraco.Web.UI.Client/src/views/datatypes/views/datatype.settings.html
  src/Umbraco.Web.UI.Client/src/views/macros/macros.edit.controller.js
  src/Umbraco.Web.UI.Client/test/unit/common/filters/umbCmsJoinArray.filter.spec.js
  src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
  src/Umbraco.Web/Editors/DataTypeController.cs
  src/Umbraco.Web/Models/ContentEditing/DataTypeReferences.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: release/8.3.0, type/feature

#6751 Add additional null conditionals to the FromEditor method of RichTextPropertyValueEditor
  src/Umbraco.Web/PropertyEditors/GridPropertyEditor.cs
  src/Umbraco.Web/PropertyEditors/RichTextPropertyEditor.cs
Labels: category/regression, release/8.2.1, type/bug

#6783 V8: Make the active state clearly visible for property "edit" and "delete" icons
  src/Umbraco.Web.UI.Client/src/less/components/umb-group-builder.less
Labels: category/accessibility, community/pr, hacktoberfest/contrib-2019, release/8.3.0, type/feature

#6585 V8 style preview badge
  src/Umbraco.Core/Configuration/UmbracoSettings/ContentElement.cs
  src/Umbraco.Tests/Configurations/UmbracoSettings/ContentElementTests.cs
  src/Umbraco.Tests/Configurations/UmbracoSettings/umbracoSettings.config
  src/Umbraco.Web.UI.Client/src/assets/img/preview-mode-badge.png
  src/Umbraco.Web.UI/config/umbracoSettings.Release.config
  src/Umbraco.Web.UI/config/umbracoSettings.config
Labels: community/pr, hacktoberfest/contrib-2019, release/8.3.0, type/feature

#6838 Document type collection: Refactor labels to reference the proper input fields
  src/Umbraco.Web.UI.Client/src/views/documenttypes/create.html
Labels: community/pr, hacktoberfest/contrib-2019, release/8.3.0, type/feature

#6850 V8: Do not allow copying items in the recycle bin
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
Labels: community/pr, hacktoberfest/contrib-2019, release/8.3.0, type/bug

#6636 Add SecurityCodeScan static code analyzer
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Examine/Umbraco.Examine.csproj
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: community/pr, hacktoberfest/contrib-2019

#6315 V8: Accessibility Changes For umbEditorHeader Directive
  src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorheader.directive.js
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-header.html
  src/Umbraco.Web.UI.Client/src/views/dictionary/dictionary.edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/dictionary/edit.html
  src/Umbraco.Web.UI.Client/src/views/documenttypes/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/documenttypes/edit.html
  src/Umbraco.Web.UI.Client/src/views/media/edit.html
  src/Umbraco.Web.UI.Client/src/views/media/media.edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/mediatypes/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/mediatypes/edit.html
  src/Umbraco.Web.UI.Client/src/views/member/edit.html
  src/Umbraco.Web.UI.Client/src/views/member/member.edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/membergroups/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/membergroups/edit.html
  src/Umbraco.Web.UI.Client/src/views/membertypes/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/membertypes/edit.html
  src/Umbraco.Web.UI.Client/src/views/partialviewmacros/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/partialviewmacros/edit.html
  src/Umbraco.Web.UI.Client/src/views/partialviews/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/partialviews/edit.html
  src/Umbraco.Web.UI.Client/src/views/relationtypes/create.controller.js
  src/Umbraco.Web.UI.Client/src/views/scripts/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/scripts/edit.html
  src/Umbraco.Web.UI.Client/src/views/stylesheets/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/stylesheets/edit.html
  src/Umbraco.Web.UI.Client/src/views/templates/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/templates/edit.html
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: category/accessibility

#6878 Opens templates from umb-grid-selector in infinite editor
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbgridselector.directive.js
Labels: community/pr, hacktoberfest/contrib-2019, release/8.3.0, type/bug

#6882 Remove outdated media dashboards
  src/Umbraco.Web.UI.Client/src/views/dashboard/media/desktopmediauploader.html
  src/Umbraco.Web.UI.Client/src/views/dashboard/media/mediadashboardintro.html
Labels: hacktoberfest/contrib-2019

#6885 Remove unused dashboards
  src/Umbraco.Web.UI.Client/src/views/dashboard/default/StartupDashboardKits.html
  src/Umbraco.Web.UI.Client/src/views/dashboard/default/StartupDashboardLastEdits.html
Labels: hacktoberfest/contrib-2019

#7002 Fixes a race condition with nucache
  src/Umbraco.Web/PublishedCache/NuCache/ContentStore.cs
  src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs
  src/Umbraco.Web/Scheduling/HealthCheckNotifier.cs
  src/Umbraco.Web/Scheduling/SchedulerComponent.cs
Labels: type/bug

#6948 Styling for the DataType Delete Dialog
  src/Umbraco.Web.UI.Client/src/less/belle.less
  src/Umbraco.Web.UI.Client/src/less/components/contextdialogs/umb-dialog-datatype-delete.less
  src/Umbraco.Web.UI.Client/src/views/datatypes/delete.html
Labels: category/ui

#6823 PropertyActions + Copy all entries for Nested Content
  src/Umbraco.Web.UI.Client/gulp/tasks/watchTask.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/property/umbproperty.directive.js
  src/Umbraco.Web.UI.Client/src/common/services/clipboard.service.js
  src/Umbraco.Web.UI.Client/src/common/services/propertyeditor.service.js
  src/Umbraco.Web.UI.Client/src/less/belle.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-contextmenu.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-nested-content.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-property-actions.less
  src/Umbraco.Web.UI.Client/src/less/main.less
  src/Umbraco.Web.UI.Client/src/less/variables.less
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/compositions/compositions.html
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.html
  src/Umbraco.Web.UI.Client/src/views/components/property/property-actions/umb-property-actions.html
  src/Umbraco.Web.UI.Client/src/views/components/property/property-actions/umbpropertyactions.component.js
  src/Umbraco.Web.UI.Client/src/views/components/property/umb-property.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.html
  src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: category/ui, category/ux
