Repository umbraco/Umbraco-CMS, pull requests merged in 2019-04, with the labels that each got.

#5107 Replace dynamic ViewBag with ViewData
  src/Umbraco.Web.UI/Umbraco/Install/Views/Index.cshtml
  src/Umbraco.Web.UI/Umbraco/Views/AuthorizeUpgrade.cshtml
  src/Umbraco.Web.UI/Umbraco/Views/Default.cshtml
  src/Umbraco.Web/Editors/BackOfficeController.cs
  src/Umbraco.Web/Install/Controllers/InstallController.cs
  src/Umbraco.Web/Umbraco.Web.csproj
  src/Umbraco.Web/ViewDataExtensions.cs
Labels: release/8.1.0, state/review

#5109 V8: Updated Constant.System.Root references (to use correct constant, and others)
  src/Umbraco.Core/Compose/RelateOnTrashComponent.cs
  src/Umbraco.Core/Constants-AppSettings.cs
  src/Umbraco.Core/Constants-Applications.cs
  src/Umbraco.Core/Constants-Conventions.cs
  src/Umbraco.Core/Constants-Icons.cs
  src/Umbraco.Core/Constants-Indexes.cs
  src/Umbraco.Core/Constants-ObjectTypes.cs
  src/Umbraco.Core/Constants-PackageRepository.cs
  src/Umbraco.Core/Constants-PropertyEditors.cs
  src/Umbraco.Core/Constants-Web.cs
  src/Umbraco.Core/Models/UserExtensions.cs
  src/Umbraco.Core/Persistence/Constants-DatabaseSchema.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs
  src/Umbraco.Core/Services/Implement/ContentService.cs
  src/Umbraco.Core/Services/Implement/MediaService.cs
  src/Umbraco.Core/UdiEntityType.cs
  src/Umbraco.Web/Editors/CodeFileController.cs
  src/Umbraco.Web/Models/Trees/TreeRootNode.cs
  src/Umbraco.Web/Trees/ApplicationTreeController.cs
  src/Umbraco.Web/Trees/ContentBlueprintTreeController.cs
  src/Umbraco.Web/Trees/ContentTreeController.cs
  src/Umbraco.Web/Trees/ContentTreeControllerBase.cs
  src/Umbraco.Web/Trees/ContentTypeTreeController.cs
  src/Umbraco.Web/Trees/DataTypeTreeController.cs
  src/Umbraco.Web/Trees/DictionaryTreeController.cs
  src/Umbraco.Web/Trees/FileSystemTreeController.cs
  src/Umbraco.Web/Trees/MacrosTreeController.cs
  src/Umbraco.Web/Trees/MediaTreeController.cs
  src/Umbraco.Web/Trees/MediaTypeTreeController.cs
  src/Umbraco.Web/Trees/MemberTreeController.cs
  src/Umbraco.Web/Trees/MemberTypeAndGroupTreeControllerBase.cs
  src/Umbraco.Web/Trees/RelationTypeTreeController.cs
  src/Umbraco.Web/Trees/TemplatesTreeController.cs
  src/Umbraco.Web/Trees/TreeControllerBase.cs
Labels: type/feature

#5135 Fix case of query parameter
  src/Umbraco.Core/Persistence/Repositories/Implement/ExternalLoginRepository.cs
Labels: release/8.0.2, state/in-progress, type/bug

#5106 Simplify our Poco mappers
  src/Umbraco.Core/Composing/SetCollectionBuilderBase.cs
  src/Umbraco.Core/Persistence/Mappers/AccessMapper.cs
  src/Umbraco.Core/Persistence/Mappers/AuditEntryMapper.cs
  src/Umbraco.Core/Persistence/Mappers/AuditItemMapper.cs
  src/Umbraco.Core/Persistence/Mappers/BaseMapper.cs
  src/Umbraco.Core/Persistence/Mappers/ConsentMapper.cs
  src/Umbraco.Core/Persistence/Mappers/ContentMapper.cs
  src/Umbraco.Core/Persistence/Mappers/ContentTypeMapper.cs
  src/Umbraco.Core/Persistence/Mappers/DataTypeMapper.cs
  src/Umbraco.Core/Persistence/Mappers/DictionaryMapper.cs
  src/Umbraco.Core/Persistence/Mappers/DictionaryTranslationMapper.cs
  src/Umbraco.Core/Persistence/Mappers/DomainMapper.cs
  src/Umbraco.Core/Persistence/Mappers/DtoMapModel.cs
  src/Umbraco.Core/Persistence/Mappers/ExternalLoginMapper.cs
  src/Umbraco.Core/Persistence/Mappers/LanguageMapper.cs
  src/Umbraco.Core/Persistence/Mappers/MacroMapper.cs
  src/Umbraco.Core/Persistence/Mappers/MapperCollectionBuilder.cs
  src/Umbraco.Core/Persistence/Mappers/MediaMapper.cs
  src/Umbraco.Core/Persistence/Mappers/MediaTypeMapper.cs
  src/Umbraco.Core/Persistence/Mappers/MemberGroupMapper.cs
  src/Umbraco.Core/Persistence/Mappers/MemberMapper.cs
  src/Umbraco.Core/Persistence/Mappers/MemberTypeMapper.cs
  src/Umbraco.Core/Persistence/Mappers/PropertyGroupMapper.cs
  src/Umbraco.Core/Persistence/Mappers/PropertyMapper.cs
  src/Umbraco.Core/Persistence/Mappers/PropertyTypeMapper.cs
  src/Umbraco.Core/Persistence/Mappers/RelationMapper.cs
  src/Umbraco.Core/Persistence/Mappers/RelationTypeMapper.cs
  src/Umbraco.Core/Persistence/Mappers/ServerRegistrationMapper.cs
  src/Umbraco.Core/Persistence/Mappers/SimpleContentTypeMapper.cs
  src/Umbraco.Core/Persistence/Mappers/TagMapper.cs
  src/Umbraco.Core/Persistence/Mappers/TemplateMapper.cs
  src/Umbraco.Core/Persistence/Mappers/UmbracoEntityMapper.cs
  src/Umbraco.Core/Persistence/Mappers/UserGroupMapper.cs
  src/Umbraco.Core/Persistence/Mappers/UserMapper.cs
  src/Umbraco.Core/Persistence/Querying/ModelToSqlExpressionVisitor.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/UserRepository.cs
  src/Umbraco.Core/TypeLoaderExtensions.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests.Benchmarks/ModelToSqlExpressionHelperBenchmarks.cs
  src/Umbraco.Tests/Composing/TypeLoaderTests.cs
  src/Umbraco.Tests/Persistence/Mappers/ContentMapperTest.cs
  src/Umbraco.Tests/Persistence/Mappers/ContentTypeMapperTest.cs
  src/Umbraco.Tests/Persistence/Mappers/DataTypeMapperTest.cs
  src/Umbraco.Tests/Persistence/Mappers/DictionaryMapperTest.cs
  src/Umbraco.Tests/Persistence/Mappers/DictionaryTranslationMapperTest.cs
  src/Umbraco.Tests/Persistence/Mappers/LanguageMapperTest.cs
  src/Umbraco.Tests/Persistence/Mappers/MapperTestBase.cs
  src/Umbraco.Tests/Persistence/Mappers/MediaMapperTest.cs
  src/Umbraco.Tests/Persistence/Mappers/PropertyGroupMapperTest.cs
  src/Umbraco.Tests/Persistence/Mappers/PropertyTypeMapperTest.cs
  src/Umbraco.Tests/Persistence/Mappers/RelationMapperTest.cs
  src/Umbraco.Tests/Persistence/Mappers/RelationTypeMapperTest.cs
  src/Umbraco.Tests/TestHelpers/BaseUsingSqlCeSyntax.cs
  src/Umbraco.Tests/TestHelpers/TestObjects-Mocks.cs
  src/Umbraco.Tests/TestHelpers/TestWithDatabaseBase.cs
  src/Umbraco.Tests/Testing/UmbracoTestBase.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
  src/Umbraco.Tests/Web/Controllers/UsersControllerTests.cs
Labels: category/breaking, release/8.1.0, state/review

#5138 Make XmlHelper class public again
  src/Umbraco.Core/Xml/XmlHelper.cs
Labels: release/8.1.0, type/feature

#5128 V8: Replace listview bulk action permission checkboxes with umb-toggle
  src/Umbraco.Web.UI.Client/src/less/property-editors.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/bulkActionPermissions.prevalues.html
Labels: category/ui, release/8.1.0

#5114 Enable configuration of NuCache BTree block size
  src/Umbraco.Web/PublishedCache/NuCache/DataSource/BTree.cs
Labels: release/8.0.2, type/feature

#5011 Content/Media/MemberTypeRepository refactoring
  src/Umbraco.Core/Cache/NoCacheRepositoryCachePolicy.cs
  src/Umbraco.Core/Composing/CompositionExtensions/Repositories.cs
  src/Umbraco.Core/Migrations/Install/DatabaseSchemaCreator.cs
  src/Umbraco.Core/Migrations/Upgrade/V_7_9_0/AddIsSensitiveMemberTypeColumn.cs
  src/Umbraco.Core/Models/ContentTypeBase.cs
  src/Umbraco.Core/Models/ContentTypeCompositionBase.cs
  src/Umbraco.Core/Models/IContentTypeBase.cs
  src/Umbraco.Core/Persistence/Constants-DatabaseSchema.cs
  src/Umbraco.Core/Persistence/Dtos/ContentTypeDto.cs
  src/Umbraco.Core/Persistence/Dtos/DataTypeDto.cs
  src/Umbraco.Core/Persistence/Dtos/MemberPropertyTypeDto.cs
  src/Umbraco.Core/Persistence/Dtos/MemberTypeReadOnlyDto.cs
  src/Umbraco.Core/Persistence/Dtos/PropertyTypeCommonDto.cs
  src/Umbraco.Core/Persistence/Factories/ContentTypeFactory.cs
  src/Umbraco.Core/Persistence/Factories/MemberTypeReadOnlyFactory.cs
  src/Umbraco.Core/Persistence/Repositories/IContentTypeCommonRepository.cs
  src/Umbraco.Core/Persistence/Repositories/IMediaTypeRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeCommonRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/MediaTypeRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/MemberTypeRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/RepositoryBaseOfTIdTEntity.cs
  src/Umbraco.Core/Services/Implement/DataTypeService.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests/Persistence/Querying/ContentTypeSqlMappingTests.cs
  src/Umbraco.Tests/Persistence/Repositories/ContentTypeRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/DocumentRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/DomainRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/MediaRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/MediaTypeRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/MemberRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/MemberTypeRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/PublicAccessRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/TagRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/TemplateRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/UserRepositoryTest.cs
  src/Umbraco.Tests/Persistence/SqlCeTableByTableTest.cs
  src/Umbraco.Tests/Services/ContentServicePerformanceTest.cs
  src/Umbraco.Tests/Services/ContentServiceTests.cs
  src/Umbraco.Tests/Services/ContentTypeServiceTests.cs
  src/Umbraco.Web/Cache/ContentTypeCacheRefresher.cs
Labels: release/8.1.0, state/review

#5165 V8: Can't save templates (missing mapping profile)
  src/Umbraco.Web/Models/Mapping/TemplateMapDefinition.cs
Labels: state/sprint-backlog, type/bug

#5166 Changed umb-toggle look to fit with v8
  src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-toggle.less
  src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-toggle.html
Labels: state/review

#5140 Use umb-checkbox for select all in listview
  src/Umbraco.Web.UI.Client/src/common/services/listviewhelper.service.js
  src/Umbraco.Web.UI.Client/src/views/components/umb-table.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/list/list.listviewlayout.controller.js
Labels: release/8.1.0, state/review

#5173 V8: YSOD when creating the same content type twice (mapping issue)
  src/Umbraco.Web/Models/Mapping/ContentTypeMapDefinition.cs
Labels: release/8.0.2, state/in-progress, type/bug

#5176 V8: Fix node permissions YSOD (mapping issue)
  src/Umbraco.Web/Models/Mapping/UserMapDefinition.cs
Labels: release/8.0.2, type/bug

#5180 V8: YSOD when saving variant content (mapping issue)
  src/Umbraco.Web/Models/Mapping/ContentMapDefinition.cs
Labels: release/8.1.0, type/bug

#5177 V8: Missing "metadata" breaks media picker (mapping issue)
  src/Umbraco.Web/Models/Mapping/EntityMapDefinition.cs
Labels: release/8.1.0, state/in-progress, type/bug

#5188 V8: Relation type alias is "generating" when editing an existing relation type
  src/Umbraco.Web/Models/Mapping/RelationMapDefinition.cs
Labels: release/8.1.0, state/in-progress, type/bug

#5167 Fixing property editor "checkboxlist" to work in v8
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/checkboxlist/checkboxlist.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/checkboxlist/checkboxlist.html
Labels: state/review

#5221 Making Umb-Toggle round
  src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-toggle.less
Labels: category/ui, release/8.1.0, state/review

#5219 bigger area for add-property + only hover-state if you can edit property
  src/Umbraco.Web.UI.Client/src/less/components/editor.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-group-builder.less
  src/Umbraco.Web.UI.Client/src/views/components/umb-groups-builder.html
Labels: release/8.1.0, state/review

#5159 Fix the colour of the error message in the domains overlay
  src/Umbraco.Web.UI.Client/src/less/forms.less
Labels: category/ui, state/review

#5076 4521 umb-property-editor css width-limitation
  src/Umbraco.Web.UI.Client/src/common/directives/components/editor/subheader/umbeditorsubheader.directive.js
  src/Umbraco.Web.UI.Client/src/less/belle.less
  src/Umbraco.Web.UI.Client/src/less/components/editor/subheader/umb-editor-sub-header.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-dropdown.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-node-preview.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-textarea.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-textstring.less
  src/Umbraco.Web.UI.Client/src/less/listview.less
  src/Umbraco.Web.UI.Client/src/less/mixins.less
  src/Umbraco.Web.UI.Client/src/less/property-editors.less
  src/Umbraco.Web.UI.Client/src/less/rte.less
  src/Umbraco.Web.UI.Client/src/views/components/editor/subheader/umb-editor-sub-header.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.html
Labels: category/front-end, category/ui, community/up-for-grabs

#5216 Fixed not using preview in GetById and added UDI support
  src/Umbraco.Web/PublishedCache/ContextualPublishedCache.cs
Labels: community/pr, state/in-progress

#5247 Fix bad local temp path
  src/Umbraco.Core/Configuration/GlobalSettings.cs
Labels: release/8.1.0, state/review, type/bug

#5246 Add GetById(Udi) to published caches
  src/Umbraco.Tests/LegacyXmlPublishedCache/PublishedContentCache.cs
  src/Umbraco.Tests/LegacyXmlPublishedCache/PublishedMediaCache.cs
  src/Umbraco.Tests/PublishedContent/SolidPublishedSnapshot.cs
  src/Umbraco.Web/PublishedCache/IPublishedCache.cs
  src/Umbraco.Web/PublishedCache/NuCache/ContentCache.cs
  src/Umbraco.Web/PublishedCache/NuCache/MediaCache.cs
  src/Umbraco.Web/PublishedCache/PublishedCacheBase.cs
Labels: release/8.1.0, state/review, type/bug

#5262 V8: Tree node annotation "pending changes" should take precendence over "is listview"
  src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less
Labels: category/ui, community/pr, release/8.1.0

#5116 V8: Add back button to listviews in media
  src/Umbraco.Web.UI.Client/src/views/media/edit.html
  src/Umbraco.Web.UI.Client/src/views/media/media.edit.controller.js
Labels: category/ux, state/backlog, type/feature

#5158 V8: Add back button to listviews for members
  src/Umbraco.Web.UI.Client/src/views/member/edit.html
  src/Umbraco.Web.UI.Client/src/views/member/member.edit.controller.js
Labels: category/ux, state/backlog, type/bug

#5149 V8: Fix broken listview pagination when using the back link
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbpagination.directive.js
  src/Umbraco.Web.UI.Client/src/common/services/listviewhelper.service.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/grid/grid.listviewlayout.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/list/list.listviewlayout.controller.js
Labels: category/ux, state/backlog, type/bug

#5213 V8: Make sure Nested Content item blueprints are listed in defined sort order
  src/Umbraco.Web.UI.Client/src/views/common/overlays/itempicker/itempicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/overlays/itempicker/itempicker.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
Labels: category/ux, state/backlog

#4776 V8: Datatype configs are not validated in infinite editing
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypesettings/datatypesettings.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypesettings/datatypesettings.html
Labels: category/front-end, release/8.1.0

#4777 V8: Allow nested content without blueprints
  src/Umbraco.Web.UI.Client/src/less/components/umb-nested-content.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.doctypepicker.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.html
  src/Umbraco.Web/PropertyEditors/ValueConverters/NestedContentManyValueConverter.cs
Labels: state/hq-discussion-ux, type/feature

#5210 Backoffice session timeout on custom-URL backoffices leads to high browser CPU and self-inflicted backend DDoS
  src/Umbraco.Web.UI.Client/src/common/security/securityinterceptor.js
Labels: type/bug

#5287 V8: Send notifications for changes in permissions
  src/Umbraco.Web/Compose/NotificationsComponent.cs
Labels: community/pr, release/8.1.0, type/feature

#5320 Re-adding outline to the umb-button__button for focus states
  src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-button.less
Labels: category/accessibility, release/8.1.0, state/review

#5304 V8: Login form accessibility improvements and form input tabbed focus styles
  src/Umbraco.Web.UI.Client/src/common/directives/components/application/umblogin.directive.js
  src/Umbraco.Web.UI.Client/src/controllers/main.controller.js
  src/Umbraco.Web.UI.Client/src/less/forms.less
  src/Umbraco.Web.UI.Client/src/less/variables.less
  src/Umbraco.Web.UI/Umbraco/Views/Default.cshtml
Labels: category/accessibility, release/8.1.0, state/review

#5331 Update jQuery to latest 3.4.0
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
Labels: release/8.1.0, state/review

#5336 Create new Nuget Symbol packags - snupkg
  build/NuSpecs/UmbracoCms.Core.nuspec
  build/NuSpecs/UmbracoCms.Web.nuspec
  build/build.ps1
Labels: state/review

#5332 V8: prettier outline on media picker
  src/Umbraco.Web.UI.Client/src/less/property-editors.less
Labels: category/accessibility, category/ui, release/8.1.0, state/review

#5329 V8: nested content consistent "add content"-button, and other adjustments.
  src/Umbraco.Web.UI.Client/src/less/components/umb-nested-content.less
  src/Umbraco.Web.UI.Client/src/less/variables.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.html
Labels: release/8.1.0, state/review

#5330 V8: prettier outline for buttons, and only shown when tabbing is active.
  src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-button.less
Labels: category/accessibility, category/front-end, release/8.1.0, state/review

#5339 focus outline + hover states for umb-checkbox and umb-radio
  src/Umbraco.Web.UI.Client/src/less/components/umb-form-check.less
Labels: category/accessibility, category/ui, release/8.1.0, state/review

#5340 Disable tabbing state if user clicks
  src/Umbraco.Web.UI.Client/src/controllers/main.controller.js
Labels: category/accessibility, release/8.1.0, state/review

#5338 V8: app header action focus outline
  src/Umbraco.Web.UI.Client/src/less/components/application/umb-app-header.less
  src/Umbraco.Web.UI.Client/src/less/sections.less
Labels: category/accessibility, category/ui, release/8.1.0, state/review

#5337 Created umb-outline to make it easy to apply pretty focus outline for elements.
  src/Umbraco.Web.UI.Client/src/less/application/umb-outline.less
  src/Umbraco.Web.UI.Client/src/less/belle.less
  src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less
  src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-item.html
  src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree.html
Labels: category/accessibility, category/front-end, category/ui, release/8.1.0, state/review

#4724 V8: Make header name input look OK when disabled
  src/Umbraco.Web.UI.Client/src/less/components/editor.less
Labels: category/ux, community/pr, state/sprint-backlog

#5333 #5277 Adding correct button element,styling to remove default styles
  src/Umbraco.Web.UI.Client/src/less/components/application/umb-tour.less
  src/Umbraco.Web.UI.Client/src/views/components/application/umbtour/umb-tour-step.html
Labels: category/accessibility, community/pr, release/8.1.0, type/feature
