Repository umbraco/Umbraco-CMS, pull requests merged in 2019-07, with the labels that each got.

#5748 Prepare MB future
  src/Umbraco.Core/CompositionExtensions.cs
  src/Umbraco.Core/ConfigsExtensions.cs
  src/Umbraco.Core/Configuration/Grid/GridConfig.cs
  src/Umbraco.Core/Configuration/Grid/GridEditorsConfig.cs
  src/Umbraco.Core/Manifest/IManifestFilter.cs
  src/Umbraco.Core/Manifest/ManifestFilterCollection.cs
  src/Umbraco.Core/Manifest/ManifestFilterCollectionBuilder.cs
  src/Umbraco.Core/Manifest/ManifestParser.cs
  src/Umbraco.Core/Manifest/PackageManifest.cs
  src/Umbraco.Core/Runtime/CoreInitialComposer.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests/Manifest/ManifestParserTests.cs
  src/Umbraco.Tests/Testing/UmbracoTestBase.cs
  src/Umbraco.Web/Editors/IEditorValidator.cs
  src/Umbraco.Web/Properties/AssemblyInfo.cs
Labels: release/8.1.0, state/estimation, state/review, type/feature

#5751 #5750 - make actions like create folder work again
  src/Umbraco.Web.UI.Client/src/common/directives/components/events/events.directive.js
Labels: community/pr, type/bug

#5801 Remove last casting to LuceneIndex
  src/Umbraco.Web/Editors/ExamineManagementController.cs
Labels: community/pr, release/8.1.1, type/bug

#5869 V8: Fixes LogViewer Error Count search result click
  src/Umbraco.Web.UI.Client/src/views/logviewer/overview.controller.js
  src/Umbraco.Web.UI.Client/src/views/logviewer/overview.html
Labels: release/8.1.1, state/backlog

#5784 V8: Make log naming and colors consistent between Log Search and Log Overview
  src/Umbraco.Web.UI.Client/src/views/logviewer/overview.controller.js
  src/Umbraco.Web.UI.Client/src/views/logviewer/overview.html
  src/Umbraco.Web.UI.Client/src/views/logviewer/search.controller.js
  src/Umbraco.Web.UI/config/logviewer.searches.config.js
  src/Umbraco.Web/Editors/LogViewerController.cs
Labels: release/8.2.0, state/in-progress

#5861 Fixes issue during upgrade where umbraco can't clear cdf log files
  src/Umbraco.Web/JavaScript/ClientDependencyConfiguration.cs
Labels: release/8.1.1, state/estimation, type/bug

#5887 PR fixes 7 -> 8 migration bugs for #5852 and #5864
  src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/DataTypes/DropDownFlexiblePreValueMigrator.cs
  src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/DataTypes/PreValueMigratorComposer.cs
  src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/TablesForScheduledPublishing.cs
  src/Umbraco.Core/Umbraco.Core.csproj
Labels: state/estimation

#5972 Content migration - Include CheckBoxList in ValueListPreValueMigrator
  src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/DataTypes/ValueListPreValueMigrator.cs
Labels: category/content-migration, state/estimation, type/bug

#6009 V8: Value Set builder shouldn't stop indexing when one field is empty in …
  src/Umbraco.Examine/BaseValueSetBuilder.cs
Labels: release/8.1.2, type/bug

#6020 Adds PanicException with details instead of throwing "panic" strings
  src/Umbraco.Core/Exceptions/PanicException.cs
  src/Umbraco.Core/Mapping/UmbracoMapper.cs
  src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/DataTypes/RenamingPreValueMigrator.cs
  src/Umbraco.Core/Models/PublishedContent/ModelType.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeCommonRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/MediaTypeRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/MemberTypeRepository.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests/Testing/TestOptionAttributeBase.cs
  src/Umbraco.Web/Models/Mapping/ContentTypeMapDefinition.cs
  src/Umbraco.Web/PropertyEditors/MultipleTextStringPropertyEditor.cs
  src/Umbraco.Web/PublishedCache/NuCache/ContentStore.cs
  src/Umbraco.Web/PublishedCache/NuCache/SnapDictionary.cs
Labels: release/8.1.2
