Repository umbraco/Umbraco-CMS, pull requests merged in 2020-12, with the labels that each got.

#9459 NetCore: Set up CI with Azure Pipelines
  build/azure-pipelines.yml
  src/Umbraco.Tests.Common/TestHelperBase.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Components/ComponentTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Composing/ComposingTestBase.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Composing/TypeLoaderTests.cs
  src/umbraco.sln
Labels: project/net-core

#9483 NetCore: Prepare pipeline for nightly builds
  build/azure-pipelines.yml
Labels: project/net-core

#9027 Contextmenu: Add focus lock
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-contextmenu.html
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-navigation.html
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: category/accessibility, category/ux, hacktoberfest-accepted, release/8.11.0, type/bug

#9035 Search overlay: Improve accessibility
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-search.html
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: category/accessibility, category/ux, hacktoberfest-accepted, release/8.11.0, type/bug

#9051 Grid editors: Accessibility improvements
  src/Umbraco.Web.UI.Client/src/less/components/umb-grid.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/embed.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/macro.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/media.html
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: hacktoberfest-accepted

#9338 Add Stylecop and .EditorConfig Linting.
  Directory.Build.props
  Directory.Build.targets
  linting/.editorconfig
  linting/codeanalysis.ruleset
  linting/codeanalysis.tests.ruleset
  linting/stylecop.json
  src/.editorconfig
  src/Umbraco.Core/Configuration/ICronTabParser.cs
  src/Umbraco.Core/Properties/AssemblyInfo.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Web/Properties/AssemblyInfo.cs
  src/Umbraco.Web/Umbraco.Web.csproj
  src/umbraco-netcore-only.sln
  src/umbraco.sln
Labels: project/net-core

#9486 Converted OutgoingEditorModelEventAttribute to a type filter
  src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
  src/Umbraco.Web.BackOffice/Controllers/DashboardController.cs
  src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
  src/Umbraco.Web.BackOffice/Controllers/MemberController.cs
  src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
  src/Umbraco.Web.BackOffice/Filters/OutgoingEditorModelEventAttribute.cs
Labels: project/net-core

#9495 Fix typo in Upgrade message
  build/NuSpecs/tools/ReadmeUpgrade.txt
Labels: category/ui, release/8.11.0, release/no-notes, type/bug

#9492 Update version umbColorPicker was introduced
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbcolorpicker.directive.js
Labels: release/8.11.0, type/bug

#9488 #9476 danish translations for addUpTo
  src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
Labels: category/ui, release/8.11.0, release/no-notes, type/bug

#9106 Add "Remove all entries" property action to MNTP
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js
Labels: category/ux, hacktoberfest-accepted, release/8.11.0, type/bug

#9490 NetCore: Adds unit tests for authorization policy handlers
  src/Umbraco.Core/Security/ContentPermissions.cs
  src/Umbraco.Tests.Common/Builders/ContentBuilder.cs
  src/Umbraco.Tests.Common/Builders/MediaBuilder.cs
  src/Umbraco.Tests.Common/Builders/TreeBuilder.cs
  src/Umbraco.Tests.Common/Builders/UserBuilder.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Authorization/AdminUsersHandlerTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Authorization/BackOfficeHandlerTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Authorization/ContentPermissionsPublishBranchHandlerTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Authorization/ContentPermissionsQueryStringHandlerTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Authorization/ContentPermissionsResourceHandlerTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Authorization/DenyLocalLoginHandlerTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Authorization/MediaPermissionsQueryStringHandlerTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Authorization/MediaPermissionsResourceHandlerTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Authorization/SectionHandlerTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Authorization/TreeHandlerTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Authorization/UserGroupHandlerTests.cs
  src/Umbraco.Web.BackOffice/Authorization/AdminUsersHandler.cs
  src/Umbraco.Web.BackOffice/Authorization/AdminUsersRequirement.cs
  src/Umbraco.Web.BackOffice/Authorization/BackOfficeHandler.cs
  src/Umbraco.Web.BackOffice/Authorization/ContentPermissionsPublishBranchHandler.cs
  src/Umbraco.Web.BackOffice/Authorization/ContentPermissionsQueryStringHandler.cs
  src/Umbraco.Web.BackOffice/Authorization/ContentPermissionsResourceHandler.cs
  src/Umbraco.Web.BackOffice/Authorization/MediaPermissionsQueryStringHandler.cs
  src/Umbraco.Web.BackOffice/Authorization/PermissionsQueryStringHandler.cs
  src/Umbraco.Web.BackOffice/Authorization/UserGroupHandler.cs
Labels: project/net-core

#9049 NestedContent DoctyperPicker view: Various a11y fixes
  src/Umbraco.Web.UI.Client/src/less/components/umb-nested-content.less
  src/Umbraco.Web.UI.Client/src/less/navs.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.doctypepicker.html
Labels: hacktoberfest-accepted

#9054 Package section: Edit view
  src/Umbraco.Web.UI.Client/src/less/components/html/umb-expansion-panel.less
  src/Umbraco.Web.UI.Client/src/views/packages/edit.html
  src/Umbraco.Web.UI.Client/src/views/packages/views/created.html
Labels: hacktoberfest-accepted

#9056 Use color picker component in block list editor configuration
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.html
Labels: category/ux, hacktoberfest-accepted, release/8.11.0, type/bug

#9057 Make sure external links are not attempted to be opened inside preview iframe
  src/Umbraco.Web.UI.Client/src/preview/preview.controller.js
Labels: hacktoberfest-accepted

#9197 Update Language keys for 'Public Access' to become 'Restrict Public Access' …
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: hacktoberfest-accepted

#9203 When a user switches their own language the menu doesn't update to reflect the language change
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/fr.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/nl.xml
  src/Umbraco.Web/Editors/UsersController.cs
Labels: hacktoberfest-accepted

#9502 NetCore: Fix wrong version of Smidge in nuspec + Updated to official 3.2.0
  build/NuSpecs/UmbracoCms.Web.nuspec
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
Labels: project/net-core

#9220 Get default culture comparable to the variant culture
  src/Umbraco.Web/Editors/ContentController.cs
Labels: hacktoberfest-accepted

#9028 v8 - use ng-hide in validation directive
  src/Umbraco.Web.UI.Client/src/common/directives/validation/showvalidationonsubmit.directive.js
Labels: hacktoberfest-accepted

#9507 NetCore: further code clean-up (small)
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Configuration/Models/Extensions/HealthCheckSettingsExtensionsTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Configuration/Models/Validation/ContentSettingsValidatorTests.cs
Labels: project/net-core

#9059 Don't log query result to avoid confusion
  src/Umbraco.Core/Migrations/Install/DatabaseSchemaCreator.cs
Labels: hacktoberfest-accepted

#9494 NetCore: Migrate more tests
  src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
  src/Umbraco.Tests.Common/TestHelpers/TestDatabase.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Migrations/AdvancedMigrationTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/RedirectUrlServiceTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Cache/DefaultCachePolicyTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Cache/FullDataSetCachePolicyTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Cache/RefresherTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Cache/SingleItemsOnlyCachePolicyTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/ConvertersTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/AlterMigrationTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/MigrationPlanTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/MigrationTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/PostMigrationTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/Stubs/AlterUserTableMigrationStub.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/Stubs/DropForeignKeyMigrationStub.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/Stubs/Dummy.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/Stubs/FiveZeroMigration.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/Stubs/FourElevenMigration.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/Stubs/SixZeroMigration1.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/Stubs/SixZeroMigration2.cs
  src/Umbraco.Tests.UnitTests/Umbraco.PublishedCache.NuCache/SnapDictionaryTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
  src/Umbraco.Tests/Migrations/SqlScripts/SqlCe-SchemaAndData-4110.sql
  src/Umbraco.Tests/Migrations/SqlScripts/SqlCeTotal-480.sql
  src/Umbraco.Tests/Migrations/SqlScripts/SqlResources.Designer.cs
  src/Umbraco.Tests/Migrations/SqlScripts/SqlResources.resx
  src/Umbraco.Tests/Migrations/SqlScripts/SqlServerTotal-480.sql
  src/Umbraco.Tests/Umbraco.Tests.csproj
  src/Umbraco.Web/Macros/PartialViewMacroPage.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: project/net-core

#9083 9078: Allow changing the login logo through umbracoSettings
  src/Umbraco.Core/Configuration/UmbracoSettings/ContentElement.cs
  src/Umbraco.Core/Configuration/UmbracoSettings/IContentSection.cs
  src/Umbraco.Web.UI.Client/src/common/directives/components/application/umblogin.directive.js
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-login.html
  src/Umbraco.Web.UI/config/umbracoSettings.Release.config
  src/Umbraco.Web.UI/config/umbracoSettings.config
  src/Umbraco.Web/Editors/BackOfficeServerVariables.cs
Labels: hacktoberfest-accepted

#9512 Netcore: Read static files from app_plugins folder
  src/Umbraco.Core/Configuration/Models/UmbracoPluginSettings.cs
  src/Umbraco.Core/Constants-Configuration.cs
  src/Umbraco.Web.BackOffice/Extensions/BackOfficeApplicationBuilderExtensions.cs
  src/Umbraco.Web.BackOffice/Plugins/UmbracoPluginPhysicalFileProvider.cs
  src/Umbraco.Web.Common/Builder/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.UI.NetCore/Startup.cs
Labels: project/net-core

#9527 Little tweak
  src/Umbraco.Web.UI/Umbraco/config/lang/tr.xml
Labels: category/ux, release/8.11.0, type/bug

#9183 9153: Only show the cultures of the node in preview
  src/Umbraco.Web/Editors/PreviewController.cs
Labels: category/ux, hacktoberfest-accepted, release/8.11.0, type/bug

#9234 Change to MemberHasAccess to return true for unprotected paths.
  src/Umbraco.Web/Security/MembershipHelper.cs
Labels: community/pr, hacktoberfest-accepted, hacktoberfest/contrib-2020, type/bug

#9194 Added char counter for dictionary items
  src/Umbraco.Web.UI.Client/src/views/dictionary/dictionary.edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/dictionary/edit.html
Labels: hacktoberfest-accepted

#9255 Removed icon font classes from umb-icon implementations
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbicon.directive.js
  src/Umbraco.Web.UI.Client/src/less/forms.less
  src/Umbraco.Web.UI.Client/src/less/panel.less
  src/Umbraco.Web.UI.Client/src/less/properties.less
  src/Umbraco.Web.UI.Client/src/views/common/drawers/help/help.html
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/iconpicker/iconpicker.html
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/treepicker/treepicker.html
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-app-header.html
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-navigation.html
  src/Umbraco.Web.UI.Client/src/views/components/application/umbtour/umb-tour-step.html
  src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-button.html
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-content-header.html
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-header.html
  src/Umbraco.Web.UI.Client/src/views/components/forms/umb-search-filter.html
  src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-item.html
  src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-search-box.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-groups-builder.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-layout-selector.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-list-view-settings.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-mini-list-view.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-node-preview.html
  src/Umbraco.Web.UI.Client/src/views/content/overlays/schedule.html
  src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.html
  src/Umbraco.Web.UI.Client/src/views/logviewer/search.html
  src/Umbraco.Web.UI.Client/src/views/packages/views/installed.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.html
  src/Umbraco.Web.UI.Client/src/views/templates/edit.html
Labels: hacktoberfest-accepted

#7856 V8: Angular Divorce: isUndefined
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbaceeditor.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbcolorswatches.directive.js
  src/Umbraco.Web.UI.Client/src/common/filters/umbCmsJoinArray.filter.js
  src/Umbraco.Web.UI.Client/src/common/filters/umbwordlimit.filter.js
  src/Umbraco.Web.UI.Client/src/install.loader.js
  src/Umbraco.Web.UI.Client/src/installer/steps/database.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/linkpicker/linkpicker.controller.js
  src/Umbraco.Web.UI.Client/test/lib/angular/angular-mocks.js
  src/Umbraco.Web/JavaScript/JsInitialize.js
  src/Umbraco.Web/JavaScript/PreviewInitialize.js
Labels: community/review

#9098 remove unnecessary classnames/markup
  src/Umbraco.Web.UI.Client/src/views/components/umb-confirm.html
Labels: hacktoberfest-accepted

#9464 Netcore: Enable running integrations tests on Linux
  .gitattributes
  build/azure-pipelines.yml
  src/Umbraco.Infrastructure/Persistence/LocalDb.cs
  src/Umbraco.Infrastructure/Persistence/UmbracoDatabaseFactory.cs
  src/Umbraco.Tests.Integration/GlobalSetupTeardown.cs
  src/Umbraco.Tests.Integration/TestServerTest/UmbracoTestServerTestBase.cs
  src/Umbraco.Tests.Integration/Testing/BaseTestDatabase.cs
  src/Umbraco.Tests.Integration/Testing/ITestDatabase.cs
  src/Umbraco.Tests.Integration/Testing/IntegrationTestComposer.cs
  src/Umbraco.Tests.Integration/Testing/LocalDbTestDatabase.cs
  src/Umbraco.Tests.Integration/Testing/SqlDeveloperTestDatabase.cs
  src/Umbraco.Tests.Integration/Testing/TestDatabaseFactory.cs
  src/Umbraco.Tests.Integration/Testing/TestDbMeta.cs
  src/Umbraco.Tests.Integration/Testing/TestUmbracoDatabaseFactoryProvider.cs
  src/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/PartialViewRepositoryTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/ScriptRepositoryTest.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/StylesheetRepositoryTest.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/ImportResources.resx
  src/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  src/Umbraco.Tests/TestHelpers/TestWithDatabaseBase.cs
Labels: project/net-core

#9300 Fix save buttons not working when using non-live models builder
  src/Umbraco.Web.UI.Client/src/views/documenttypes/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/mediatypes/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/membertypes/edit.controller.js
Labels: hacktoberfest-accepted

#9092 Ensure content wrapper is positioned to left in section without tree
  src/Umbraco.Web.UI.Client/src/less/application/grid.less
Labels: hacktoberfest-accepted

#9263 Add overloaded method for RecurringTaskBase
  src/Umbraco.Web/Scheduling/RecurringTaskBase.cs
Labels: hacktoberfest-accepted

#9547 Netcore: Package support for media + media types
  build/templates/UmbracoSolution/.template.config/template.json
  src/Umbraco.Core/Constants-SystemDirectories.cs
  src/Umbraco.Core/Models/Packaging/CompiledPackage.cs
  src/Umbraco.Core/Models/Packaging/CompiledPackageContentBase.cs
  src/Umbraco.Core/Packaging/CompiledPackageXmlParser.cs
  src/Umbraco.Core/Packaging/InstallationSummary.cs
  src/Umbraco.Core/Packaging/PackageDefinition.cs
  src/Umbraco.Core/Packaging/PackageDefinitionXmlParser.cs
  src/Umbraco.Core/Packaging/PackagesRepository.cs
  src/Umbraco.Core/Services/IContentService.cs
  src/Umbraco.Core/Services/IContentServiceBase.cs
  src/Umbraco.Core/Services/IContentTypeServiceBase.cs
  src/Umbraco.Core/Services/IMediaService.cs
  src/Umbraco.Infrastructure/Composing/CompositionExtensions/Services.cs
  src/Umbraco.Infrastructure/Packaging/PackageDataInstallation.cs
  src/Umbraco.Infrastructure/Runtime/CoreInitialComposer.cs
  src/Umbraco.Infrastructure/Services/Implement/ContentService.cs
  src/Umbraco.Infrastructure/Services/Implement/EntityXmlSerializer.cs
  src/Umbraco.Infrastructure/Services/Implement/MediaService.cs
  src/Umbraco.Tests.Integration/TestData/Packages/Document_Type_Picker_1.1.umb
  src/Umbraco.Tests.Integration/TestData/Packages/Document_Type_Picker_1.1.zip
  src/Umbraco.Tests.Integration/TestData/Packages/Hello_1.0.0.zip
  src/Umbraco.Tests.Integration/Umbraco.Core/Packaging/CreatedPackagesRepositoryTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Core/Packaging/PackageDataInstallationTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Core/Packaging/PackageInstallationTest.cs
  src/Umbraco.Tests.Integration/Umbraco.Core/Packaging/Packages/Document_Type_Picker_1.1.umb
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/EntityXmlSerializerTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/CheckboxList-Content-Package.xml
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/CompositionsTestPackage-Random.xml
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/CompositionsTestPackage.xml
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/Fanoe-Package.xml
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/ImportResources.Designer.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/ImportResources.resx
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/InheritedDocTypes-Package.xml
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/MediaTypesAndMedia-Package.xml
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/SingleDocType.xml
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/StandardMvc-Package.xml
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/TemplateOnly-Package.xml
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/TemplateOnly-Updated-Package.xml
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/XsltSearch-Package.xml
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/uBlogsy-Package.xml
  src/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  src/Umbraco.Tests.UnitTests/Umbraco.PublishedCache.NuCache/SnapDictionaryTests.cs
  src/Umbraco.Tests/LegacyXmlPublishedCache/XmlStore.cs
  src/Umbraco.Tests/Services/Importing/ImportResources.Designer.cs
  src/Umbraco.Tests/Services/Importing/ImportResources.resx
  src/Umbraco.Tests/Umbraco.Tests.csproj
  src/Umbraco.Web.BackOffice/Controllers/ContentTypeController.cs
  src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
  src/Umbraco.Web.BackOffice/Controllers/PackageController.cs
  src/Umbraco.Web.Common/AspNetCore/AspNetCoreUmbracoApplicationLifetime.cs
  src/Umbraco.Web.UI.Client/src/views/packages/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/packages/edit.html
  src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
  src/Umbraco.Web.UI.NetCore/umbraco/config/lang/en_us.xml
Labels: project/net-core

#9066 Use ace xml mode for package actions
  src/Umbraco.Web.UI.Client/gulp/tasks/dependencies.js
  src/Umbraco.Web.UI.Client/src/views/packages/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/packages/edit.html
Labels: hacktoberfest-accepted

#9193 Mediapicker: Use <umb-search-filter>
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.html
Labels: hacktoberfest-accepted

#9556 Netcore: composer / component cleanup low hanging fruit
  .gitignore
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Events.cs
  src/Umbraco.Core/Events/UmbracoApplicationStarting.cs
  src/Umbraco.Core/Events/UmbracoApplicationStopping.cs
  src/Umbraco.Core/Services/IRuntime.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Infrastructure/Compose/ManifestWatcherComponent.cs
  src/Umbraco.Infrastructure/Compose/ManifestWatcherComposer.cs
  src/Umbraco.Infrastructure/Composing/HostBuilderExtensions.cs
  src/Umbraco.Infrastructure/Runtime/CoreInitialServices.cs
  src/Umbraco.Infrastructure/Runtime/CoreRuntime.cs
  src/Umbraco.Infrastructure/Runtime/EssentialDirectoryCreator.cs
  src/Umbraco.Infrastructure/Runtime/ManifestWatcher.cs
  src/Umbraco.PublishedCache.NuCache/PublishedSnapshotService.cs
  src/Umbraco.Tests.Integration/RuntimeTests.cs
  src/Umbraco.Tests.Integration/TestServerTest/UmbracoTestServerTestBase.cs
  src/Umbraco.Tests.Integration/TestServerTest/UmbracoWebApplicationFactory.cs
  src/Umbraco.Tests.Integration/Testing/BaseTestDatabase.cs
  src/Umbraco.Tests.Integration/Testing/LocalDbTestDatabase.cs
  src/Umbraco.Tests.Integration/Testing/SqlDeveloperTestDatabase.cs
  src/Umbraco.Tests.Integration/Testing/TestDatabaseFactory.cs
  src/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentTypeServiceVariantsTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ThreadSafetyServiceTest.cs
  src/Umbraco.Web.Common/Builder/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Extensions/ApplicationBuilderExtensions.cs
  src/Umbraco.Web.Common/Runtime/AspNetCoreComposer.cs
  src/Umbraco.Web.UI.NetCore/Program.cs
  src/Umbraco.Web/Runtime/WebInitialComposer.cs
  src/Umbraco.Web/UmbracoApplicationBase.cs
Labels: project/net-core

#9032 Fix, update and extend Range model
  src/Umbraco.Core/Models/Range.cs
  src/Umbraco.Tests/Models/RangeTests.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
Labels: hacktoberfest-accepted
