Repository umbraco/Umbraco-CMS, pull requests merged in 2020-07, with the labels that each got.

#8358 BlockEditor Fix - Parse on contentType key
  src/Umbraco.Web.UI.Client/src/views/documenttypes/edit.controller.js
Labels: project/block-editor, state/sprint-candidate

#8398 Adjustments for SqlMainDomLock and others to make azure operations more resilient
  src/Umbraco.Core/Persistence/FaultHandling/Strategies/SqlAzureTransientErrorDetectionStrategy.cs
  src/Umbraco.Core/Persistence/Repositories/IDocumentRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/DocumentRepository.cs
  src/Umbraco.Core/Runtime/SqlMainDomLock.cs
  src/Umbraco.Core/Services/Implement/ContentService.cs
  src/Umbraco.Examine/IndexRebuilder.cs
  src/Umbraco.TestData/LoadTestController.cs
  src/Umbraco.TestData/Umbraco.TestData.csproj
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  src/Umbraco.Web/Compose/DatabaseServerRegistrarAndMessengerComponent.cs
  src/Umbraco.Web/Scheduling/HealthCheckNotifier.cs
  src/Umbraco.Web/Scheduling/LogScrubber.cs
  src/Umbraco.Web/Scheduling/ScheduledPublishing.cs
  src/Umbraco.Web/Scheduling/SchedulerComponent.cs
Labels: release/8.6.4, type/bug

#8047 Use overlayService for user overlay
  src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbappheader.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/overlays/umboverlay.directive.js
  src/Umbraco.Web.UI.Client/src/common/services/overlay.service.js
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-app-header.html
  src/Umbraco.Web.UI.Client/src/views/components/overlays/umb-overlay.html
  src/Umbraco.Web.UI/Umbraco/Views/Default.cshtml
Labels: category/refactor, community/pr, release/8.8.0, type/feature

#8364 NetCore: Create new NuGet packages basis
  build/NuSpecs/UmbracoCms.Core.nuspec
  build/NuSpecs/UmbracoCms.Web.nuspec
  build/NuSpecs/UmbracoCms.nuspec
  build/NuSpecs/build/UmbracoCms.props
  build/NuSpecs/build/UmbracoCms.targets
  build/build-bootstrap.ps1
  build/build.ps1
  src/Umbraco.Configuration/Models/ContentSettings.cs
  src/Umbraco.Configuration/Umbraco.Configuration.csproj
  src/Umbraco.Core/Composing/ReferenceResolver.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Infrastructure/HealthCheck/NotificationMethods/NotificationMethodBase.cs
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.Persistance.SqlCe/Umbraco.Persistance.SqlCe.csproj
  src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
  src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
  src/Umbraco.Web.Common/Install/InstallController.cs
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  src/Umbraco.Web.UI.NetCore/Config/lang/cs-CZ.user.xml
  src/Umbraco.Web.UI.NetCore/Config/lang/da-DK.user.xml
  src/Umbraco.Web.UI.NetCore/Config/lang/de-DE.user.xml
  src/Umbraco.Web.UI.NetCore/Config/lang/en-GB.user.xml
  src/Umbraco.Web.UI.NetCore/Config/lang/en-US.user.xml
  src/Umbraco.Web.UI.NetCore/Config/lang/es-ES.user.xml
  src/Umbraco.Web.UI.NetCore/Config/lang/fr-FR.user.xml
  src/Umbraco.Web.UI.NetCore/Config/lang/he-IL.user.xml
  src/Umbraco.Web.UI.NetCore/Config/lang/it-IT.user.xml
  src/Umbraco.Web.UI.NetCore/Config/lang/ja-JP.user.xml
  src/Umbraco.Web.UI.NetCore/Config/lang/ko-KR.user.xml
  src/Umbraco.Web.UI.NetCore/Config/lang/nb-NO.user.xml
  src/Umbraco.Web.UI.NetCore/Config/lang/nl-NL.user.xml
  src/Umbraco.Web.UI.NetCore/Config/lang/pl-PL.user.xml
  src/Umbraco.Web.UI.NetCore/Config/lang/pt-BR.user.xml
  src/Umbraco.Web.UI.NetCore/Config/lang/ru-RU.user.xml
  src/Umbraco.Web.UI.NetCore/Config/lang/sv-SE.user.xml
  src/Umbraco.Web.UI.NetCore/Config/lang/zh-CN.user.xml
  src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
  src/Umbraco.Web.UI.NetCore/Umbraco/UmbracoBackOffice/Default.cshtml
  src/Umbraco.Web.UI.NetCore/Umbraco/UmbracoInstall/Index.cshtml
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  src/Umbraco.Web.Website/Umbraco.Web.Website.csproj
Labels: project/net-core

#8396 NuGet package specifications for SQL CE
  build/NuSpecs/UmbracoCms.SqlCe.nuspec
  build/build.ps1
  src/Umbraco.Configuration/Umbraco.Configuration.csproj
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.Persistance.SqlCe/Umbraco.Persistance.SqlCe.csproj
  src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
  src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
  src/Umbraco.Web.Website/Umbraco.Web.Website.csproj
Labels: project/net-core

#8348 Add the current culture to the cache key for the CachedPartial Html Helper
  src/Umbraco.Web/HtmlHelperRenderExtensions.cs
Labels: community/pr, project/content-variants, release/8.8.0, type/feature

#8390 Register dragover state of file upload
  src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbfileupload.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbpropertyfileupload.directive.js
  src/Umbraco.Web.UI.Client/src/less/components/umb-property-file-upload.less
  src/Umbraco.Web.UI.Client/src/views/components/upload/umb-property-file-upload.html
Labels: category/ui, community/pr, release/8.8.0, type/feature

#8445 Adjust toggle styling when checked and disabled
  src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbtoggle.directive.js
  src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-toggle.less
  src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-toggle.html
Labels: category/refactor, community/pr, release/8.8.0, type/feature

#8179 Add umb-search-filter component
  src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbsearchfilter.directive.js
  src/Umbraco.Web.UI.Client/src/less/forms.less
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypepicker/datatypepicker.html
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macroparameterpicker/macroparameterpicker.html
  src/Umbraco.Web.UI.Client/src/views/components/forms/umb-search-filter.html
  src/Umbraco.Web.UI.Client/src/views/dashboard/content/redirecturls.html
Labels: category/refactor, community/pr, release/8.8.0, type/feature

#8198 umb-confirmation directive: move trashcan into directive and address accessibility issues
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbconfirmaction.directive.js
  src/Umbraco.Web.UI.Client/src/less/components/umb-confirm-action.less
  src/Umbraco.Web.UI.Client/src/views/components/tags/umb-tags-editor.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-confirm-action.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-groups-builder.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts.prevalues.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/multipletextbox/multipletextbox.html
Labels: category/accessibility, category/refactor, community/pr, release/8.8.0, type/feature

#8480 Richtext rules adjustments
  src/Umbraco.Web.UI.Client/src/less/components/umb-stylesheet.less
  src/Umbraco.Web.UI.Client/src/less/property-editors.less
  src/Umbraco.Web.UI.Client/src/views/prevalueeditors/multivalues.html
  src/Umbraco.Web.UI.Client/src/views/stylesheets/infiniteeditors/richtextrule/richtextrule.html
  src/Umbraco.Web.UI.Client/src/views/stylesheets/views/rules/rules.controller.js
  src/Umbraco.Web.UI.Client/src/views/stylesheets/views/rules/rules.html
Labels: category/refactor, community/pr, release/8.8.0, type/feature

#8382 V8/feature/block list data structure v3
  src/Umbraco.Core/Models/Blocks/BlockEditorData.cs
  src/Umbraco.Core/Models/Blocks/BlockEditorDataConverter.cs
  src/Umbraco.Core/Models/Blocks/BlockEditorModel.cs
  src/Umbraco.Core/Models/Blocks/BlockItemData.cs
  src/Umbraco.Core/Models/Blocks/BlockListEditorDataConverter.cs
  src/Umbraco.Core/Models/Blocks/BlockListLayoutItem.cs
  src/Umbraco.Core/Models/Blocks/BlockListLayoutReference.cs
  src/Umbraco.Core/Models/Blocks/BlockListModel.cs
  src/Umbraco.Core/Models/Blocks/BlockValue.cs
  src/Umbraco.Core/Models/Blocks/ContentAndSettingsReference.cs
  src/Umbraco.Core/Models/Blocks/IBlockElement.cs
  src/Umbraco.Core/Models/Blocks/IBlockReference.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests/PropertyEditors/BlockListPropertyValueConverterTests.cs
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
  src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
  src/Umbraco.Web.UI.Client/test/unit/common/services/block-editor-service.spec.js
  src/Umbraco.Web/PropertyEditors/BlockEditorPropertyEditor.cs
  src/Umbraco.Web/PropertyEditors/BlockListConfiguration.cs
  src/Umbraco.Web/PropertyEditors/NestedContentPropertyEditor.cs
  src/Umbraco.Web/PropertyEditors/ValueConverters/BlockEditorConverter.cs
  src/Umbraco.Web/PropertyEditors/ValueConverters/BlockListPropertyValueConverter.cs
Labels: project/block-editor

#8493 Block list editor - settings validation
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/common/directives/validation/valservermatch.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/validation/valsubview.directive.js
  src/Umbraco.Web.UI.Client/src/common/mocks/resources/_utils.js
  src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
  src/Umbraco.Web.UI.Client/src/common/services/localization.service.js
  src/Umbraco.Web.UI.Client/src/common/services/servervalidationmgr.service.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockeditor/blockeditor.controller.js
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-sub-view.html
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-sub-views.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-row.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbblocklistrow.component.js
  src/Umbraco.Web.UI.Client/test/config/karma.conf.js
  src/Umbraco.Web.UI.Client/test/unit/common/services/block-editor-service.spec.js
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  src/Umbraco.Web/PropertyEditors/BlockEditorPropertyEditor.cs
  src/Umbraco.Web/PropertyEditors/NestedContentPropertyEditor.cs
  src/Umbraco.Web/PropertyEditors/Validation/ComplexEditorElementTypeValidationResult.cs
  src/Umbraco.Web/PropertyEditors/Validation/ComplexEditorPropertyTypeValidationResult.cs
  src/Umbraco.Web/PropertyEditors/Validation/ComplexEditorValidationResult.cs
  src/Umbraco.Web/PropertyEditors/Validation/ContentPropertyValidationResult.cs
  src/Umbraco.Web/PropertyEditors/Validation/ValidationResultConverter.cs
Labels: project/block-editor

#8507 Fix panel header spacing when a description is present
  src/Umbraco.Web.UI.Client/src/less/panel.less
Labels: category/ui, community/pr, release/8.8.0, type/bug

#8195 Improve dictionary dashboard performance significantly
  src/Umbraco.Web/Editors/DictionaryController.cs
Labels: category/performance
