Repository umbraco/Umbraco-CMS, pull requests merged in 2020-01, with the labels that each got.

#6617 Log exceptions thrown while terminating components
  src/Umbraco.Core/Composing/ComponentCollection.cs
Labels: state/needs-investigation

#6919 Feature/media provide screen reader context remove files
  src/Umbraco.Web.UI.Client/src/views/components/upload/umb-property-file-upload.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.html
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: category/accessibility, community/pr, type/feature

#7260 Listview styling adjustments
  src/Umbraco.Web.UI.Client/src/less/belle.less
  src/Umbraco.Web.UI.Client/src/less/buttons.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-layout-selector.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-mini-search.less
  src/Umbraco.Web.UI.Client/src/less/listview.less
  src/Umbraco.Web.UI.Client/src/views/components/umb-content-grid.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-layout-selector.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-mini-list-view.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-mini-search/umb-mini-search.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-mini-search/umbminisearch.component.js
  src/Umbraco.Web.UI.Client/src/views/components/umb-table.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.html
Labels: category/ui

#5241 Review: Media picker UX updates
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbmediagrid.directive.js
  src/Umbraco.Web.UI.Client/src/less/components/umb-breadcrumbs.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-media-grid.less
  src/Umbraco.Web.UI.Client/src/less/property-editors.less
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-media-grid.html
  src/Umbraco.Web.UI.Client/src/views/prevalueeditors/mediafolderpicker.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/grid/grid.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.html
Labels: state/sprint-candidate

#7189 Make sure the configured url provider mode is used when getting a url
  src/Umbraco.Web/PublishedContentExtensions.cs
Labels: category/regression

#7031 V8: Make it possible to hide anchor/querystring input in the linkpicker
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/linkpicker/linkpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/linkpicker/linkpicker.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.controller.js
  src/Umbraco.Web/PropertyEditors/MultiUrlPickerConfiguration.cs
Labels: community/pr, release/no-notes, type/feature

#7212 Segments in Backoffice: Server code
  src/Umbraco.Core/ContentVariationExtensions.cs
  src/Umbraco.Web/Editors/Binders/ContentItemBinder.cs
  src/Umbraco.Web/Editors/ContentController.cs
  src/Umbraco.Web/Models/ContentEditing/ContentPropertyBasic.cs
  src/Umbraco.Web/Models/ContentEditing/ContentVariantSave.cs
  src/Umbraco.Web/Models/Mapping/ContentPropertyBasicMapper.cs
  src/Umbraco.Web/Models/Mapping/ContentVariantMapper.cs
  src/Umbraco.Web/Models/Mapping/MapperContextExtensions.cs
Labels: category/segments

#7432 Netcore: Handle IRegisteredObject and remove Umbraco.Core project
  src/Umbraco.Abstractions/Hosting/IHostingEnvironment.cs
  src/Umbraco.Abstractions/IRegisteredObject.cs
  src/Umbraco.Core/Properties/AssemblyInfo.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Examine/Umbraco.Examine.csproj
  src/Umbraco.Infrastructure/MainDom.cs
  src/Umbraco.ModelsBuilder.Embedded/PureLiveModelFactory.cs
  src/Umbraco.ModelsBuilder.Embedded/Umbraco.ModelsBuilder.Embedded.csproj
  src/Umbraco.Tests/LegacyXmlPublishedCache/XmlStore.cs
  src/Umbraco.Tests/Runtimes/CoreRuntimeTests.cs
  src/Umbraco.Tests/Scheduling/BackgroundTaskRunnerTests.cs
  src/Umbraco.Tests/Scheduling/BackgroundTaskRunnerTests2.cs
  src/Umbraco.Tests/Testing/UmbracoTestBase.cs
  src/Umbraco.Web.UI/config/serilog.Release.config
  src/Umbraco.Web/Compose/DatabaseServerRegistrarAndMessengerComponent.cs
  src/Umbraco.Web/Hosting/AspNetHostingEnvironment.cs
  src/Umbraco.Web/Scheduling/BackgroundTaskRunner.cs
  src/Umbraco.Web/Scheduling/IBackgroundTaskRunner.cs
  src/Umbraco.Web/Scheduling/SchedulerComponent.cs
  src/Umbraco.Web/Search/BackgroundIndexRebuilder.cs
  src/umbraco.sln
Labels: project/net-core

#6804 Improvements to grid accessibility
  src/Umbraco.Web.UI.Client/src/common/directives/components/overlays/umboverlay.directive.js
  src/Umbraco.Web.UI.Client/src/less/components/umb-grid.less
  src/Umbraco.Web.UI.Client/src/views/common/overlays/itempicker/itempicker.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-confirm-action.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.html
Labels: category/accessibility, community/pr, release/8.6.0, release/no-notes, type/feature

#7366 V8: Email Marketing Opt In
  .gitattributes
  src/Umbraco.Web.UI.Client/src/common/resources/emailmarketing.resource.js
  src/Umbraco.Web.UI.Client/src/common/services/tour.service.js
  src/Umbraco.Web.UI.Client/src/common/services/user.service.js
  src/Umbraco.Web.UI.Client/src/init.js
  src/Umbraco.Web.UI.Client/src/less/belle.less
  src/Umbraco.Web.UI.Client/src/less/components/application/umb-tour.less
  src/Umbraco.Web.UI.Client/src/less/components/umbemailmarketing.less
  src/Umbraco.Web.UI.Client/src/main.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/tours/umbEmailMarketing/emails/emails.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/tours/umbEmailMarketing/emails/emails.html
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-tour.html
  src/Umbraco.Web.UI/Umbraco/js/main.controller.js
  src/Umbraco.Web.UI/config/BackOfficeTours/getting-started.json
  src/Umbraco.Web/Models/BackOfficeTour.cs
Labels: release/8.6.0, type/feature

#7438 Netcore: Move content apps to abstractions
  src/Umbraco.Abstractions/ContentApps/ContentAppFactoryCollection.cs
  src/Umbraco.Abstractions/ContentApps/ContentAppFactoryCollectionBuilder.cs
  src/Umbraco.Abstractions/ContentApps/ContentEditorContentAppFactory.cs
  src/Umbraco.Abstractions/ContentApps/ContentInfoContentAppFactory.cs
  src/Umbraco.Abstractions/ContentApps/ListViewContentAppFactory.cs
  src/Umbraco.Abstractions/Models/ContentEditing/ContentPropertyDisplay.cs
  src/Umbraco.Abstractions/Models/Identity/ICurrentUserAccessor.cs
  src/Umbraco.Tests/Testing/UmbracoTestBase.cs
  src/Umbraco.Web/Runtime/WebInitialComposer.cs
  src/Umbraco.Web/Security/CurrentUserAccessor.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: project/net-core

#7306 Introduce a new IMainDomLock and both default and sql implementations
  src/Umbraco.Core/Constants-AppSettings.cs
  src/Umbraco.Core/Migrations/Install/DatabaseDataCreator.cs
  src/Umbraco.Core/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Core/Migrations/Upgrade/V_8_6_0/AddMainDomLock.cs
  src/Umbraco.Core/Migrations/Upgrade/V_8_6_0/AddPropertyTypeValidationMessageColumns.cs
  src/Umbraco.Core/Persistence/Constants-Locks.cs
  src/Umbraco.Core/Persistence/SqlSyntax/SqlServerSyntaxProvider.cs
  src/Umbraco.Core/Runtime/CoreRuntime.cs
  src/Umbraco.Core/Runtime/IMainDom.cs
  src/Umbraco.Core/Runtime/IMainDomLock.cs
  src/Umbraco.Core/Runtime/MainDom.cs
  src/Umbraco.Core/Runtime/MainDomSemaphoreLock.cs
  src/Umbraco.Core/Runtime/SqlMainDomLock.cs
  src/Umbraco.Core/Scoping/IScopeProvider.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests/Cache/SnapDictionaryTests.cs
  src/Umbraco.Tests/LegacyXmlPublishedCache/XmlPublishedSnapshotService.cs
  src/Umbraco.Tests/LegacyXmlPublishedCache/XmlStore.cs
  src/Umbraco.Web/PublishedCache/NuCache/ContentStore.cs
  src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs
  src/Umbraco.Web/PublishedCache/NuCache/SnapDictionary.cs
  src/Umbraco.Web/PublishedCache/NuCache/readme.md
  src/Umbraco.Web/Umbraco.Web.csproj
  src/Umbraco.Web/UmbracoApplication.cs
Labels: release/8.6.0, type/feature

#7497 Netcore: Moves services and dependencies from Web to Abstractions
  src/Umbraco.Abstractions/Dashboards/DashboardCollection.cs
  src/Umbraco.Abstractions/Models/Trees/ActionMenuItem.cs
  src/Umbraco.Abstractions/Models/Trees/MenuItem.cs
  src/Umbraco.Abstractions/Models/Trees/RefreshNode.cs
  src/Umbraco.Abstractions/Services/IDashboardService.cs
  src/Umbraco.Abstractions/Services/ISectionService.cs
  src/Umbraco.Abstractions/Services/ITreeService.cs
  src/Umbraco.Abstractions/Services/SectionService.cs
  src/Umbraco.Abstractions/Services/TreeService.cs
  src/Umbraco.Abstractions/Trees/ActionUrlMethod.cs
  src/Umbraco.Abstractions/Trees/CoreTreeAttribute.cs
  src/Umbraco.Abstractions/Trees/ITree.cs
  src/Umbraco.Abstractions/Trees/Tree.cs
  src/Umbraco.Abstractions/Trees/TreeCollection.cs
  src/Umbraco.Abstractions/Trees/TreeUse.cs
  src/Umbraco.Infrastructure/Services/Implement/DashboardService.cs
  src/Umbraco.Infrastructure/Trees/ISearchableTree.cs
  src/Umbraco.Web/Compose/DatabaseServerRegistrarAndMessengerComponent.cs
  src/Umbraco.Web/Models/Trees/MenuItemCollection.cs
  src/Umbraco.Web/Models/Trees/MenuItemList.cs
  src/Umbraco.Web/Trees/ContentTreeController.cs
  src/Umbraco.Web/Trees/RelationTypeTreeController.cs
  src/Umbraco.Web/Trees/TreeNode.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: project/net-core

#7310 V7: Discard MiniProfiler results when not in debug mode
  src/Umbraco.Web/Profiling/WebProfiler.cs
  src/Umbraco.Web/Profiling/WebProfilerProvider.cs
Labels: state/in-sprint

#7532 Don't downcast `IPublishedSnapshot` unnecessarily in `PublishedContent`
  src/Umbraco.Web/PublishedCache/NuCache/PublishedContent.cs
Labels: release/8.7.0, type/bug

#7522 Netcore: Move scheduling to Abstractions and Infrastructure
  src/Umbraco.Abstractions/Scheduling/BackgroundTaskRunnerOptions.cs
  src/Umbraco.Abstractions/Scheduling/IBackgroundTask.cs
  src/Umbraco.Abstractions/Scheduling/IBackgroundTaskRunner.cs
  src/Umbraco.Abstractions/Scheduling/ILatchedBackgroundTask.cs
  src/Umbraco.Abstractions/Scheduling/KeepAlive.cs
  src/Umbraco.Abstractions/Scheduling/LatchedBackgroundTaskBase.cs
  src/Umbraco.Abstractions/Scheduling/RecurringTaskBase.cs
  src/Umbraco.Abstractions/Scheduling/TaskAndFactoryExtensions.cs
  src/Umbraco.Abstractions/Scheduling/TaskEventArgs.cs
  src/Umbraco.Abstractions/Scheduling/TempFileCleanup.cs
  src/Umbraco.Abstractions/Scheduling/ThreadingTaskImmutable.cs
  src/Umbraco.Infrastructure/Scheduling/LogScrubber.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: project/net-core

#7468 Add missing documentation for web.routing in umbracoSettings.config
  src/Umbraco.Web.UI/config/umbracoSettings.config
Labels: community/pr, release/8.7.0, release/no-notes, type/feature

#7000 Added dialog aria labelling
  src/Umbraco.Web.UI.Client/src/views/content/rights.html
Labels: category/accessibility

#7003 V8: Fix button style when opening doctype in infinite editing with unsaved changes
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js
Labels: community/pr, hacktoberfest/contrib-2019, release/8.7.0, release/no-notes, type/feature
