Repository umbraco/Umbraco-CMS, pull requests merged in 2020-06, with the labels that each got.

#8218 Fix up typo for clipboardService.registrerClearPropertyResolver & mark incorrect as deprecated
  src/Umbraco.Web.UI.Client/src/common/services/clipboard.service.js
Labels: release/8.7.0

#8220 Netcore: Migration of more controllers
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeAssetsController.cs
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeNotificationsController.cs
  src/Umbraco.Web.BackOffice/Controllers/DictionaryController.cs
  src/Umbraco.Web.BackOffice/Controllers/ExamineManagementController.cs
  src/Umbraco.Web.BackOffice/Controllers/ImageUrlGeneratorController.cs
  src/Umbraco.Web.BackOffice/Controllers/ImagesController.cs
  src/Umbraco.Web.BackOffice/Controllers/TemplateController.cs
  src/Umbraco.Web.BackOffice/Controllers/TinyMceController.cs
  src/Umbraco.Web.BackOffice/Controllers/TourController.cs
  src/Umbraco.Web.BackOffice/Controllers/UmbracoAuthorizedJsonController.cs
  src/Umbraco.Web.BackOffice/Controllers/UpdateCheckController.cs
  src/Umbraco.Web.BackOffice/HealthCheck/HealthCheckController.cs
  src/Umbraco.Web.BackOffice/Profiling/WebProfilingController.cs
  src/Umbraco.Web.BackOffice/PropertyEditors/NestedContentController.cs
  src/Umbraco.Web.BackOffice/PropertyEditors/RichTextPreValueController.cs
  src/Umbraco.Web.BackOffice/PropertyEditors/RteEmbedController.cs
  src/Umbraco.Web.Common/AspNetCore/AspNetCoreCookieManager.cs
  src/Umbraco.Web.Common/Runtime/AspNetCoreComposer.cs
  src/Umbraco.Web/Editors/BackOfficeServerVariables.cs
  src/Umbraco.Web/Editors/TinyMceController.cs
  src/Umbraco.Web/Editors/UpdateCheckController.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: project/net-core

#8230 Netcore: Removing UmbracoContext.Security usages
  src/Umbraco.Infrastructure/Install/InstallSteps/StarterKitDownloadStep.cs
  src/Umbraco.Infrastructure/Install/InstallSteps/StarterKitInstallStep.cs
  src/Umbraco.Infrastructure/Models/Mapping/MemberTabsAndPropertiesMapper.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Filters/AppendUserModifiedHeaderAttributeTests.cs
  src/Umbraco.Tests/Testing/UmbracoTestBase.cs
  src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
  src/Umbraco.Web.BackOffice/Controllers/LogController.cs
  src/Umbraco.Web.BackOffice/Controllers/PackageController.cs
  src/Umbraco.Web.BackOffice/Controllers/PackageInstallController.cs
  src/Umbraco.Web.BackOffice/Controllers/PreviewController.cs
  src/Umbraco.Web.BackOffice/Controllers/RedirectUrlManagementController.cs
  src/Umbraco.Web.BackOffice/Controllers/TourController.cs
  src/Umbraco.Web.BackOffice/Filters/AppendUserModifiedHeaderAttribute.cs
  src/Umbraco.Web.BackOffice/Filters/OutgoingEditorModelEventAttribute.cs
  src/Umbraco.Web.BackOffice/Filters/UmbracoApplicationAuthorizeAttribute.cs
  src/Umbraco.Web.BackOffice/Filters/UmbracoTreeAuthorizeAttribute.cs
  src/Umbraco.Web.Common/Install/InstallController.cs
  src/Umbraco.Web/Editors/AuthenticationController.cs
  src/Umbraco.Web/Editors/Filters/ContentModelValidator.cs
  src/Umbraco.Web/Editors/Filters/ContentSaveModelValidator.cs
  src/Umbraco.Web/Editors/Filters/ContentSaveValidationAttribute.cs
  src/Umbraco.Web/Editors/Filters/MediaItemSaveValidationAttribute.cs
  src/Umbraco.Web/Editors/Filters/MediaSaveModelValidator.cs
  src/Umbraco.Web/Editors/Filters/MemberSaveModelValidator.cs
  src/Umbraco.Web/Editors/Filters/MemberSaveValidationAttribute.cs
  src/Umbraco.Web/Editors/MemberTypeController.cs
  src/Umbraco.Web/Editors/UsersController.cs
  src/Umbraco.Web/Mvc/UmbracoAuthorizeAttribute.cs
  src/Umbraco.Web/WebApi/UmbracoAuthorizeAttribute.cs
Labels: project/net-core

#8105 Fix "Edit: undefined" in content editor title
  src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorcontentheader.directive.js
Labels: status/regression

#5466 Api documentation functions update
  build/build.ps1
Labels: state/sprint-candidate

#8235 Adds skipStepIfVisible property to JSON Tour Steps to allow skipping if DOM item is present
  src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbtour.directive.js
  src/Umbraco.Web.UI/config/BackOfficeTours/getting-started.json
  src/Umbraco.Web/Models/BackOfficeTourStep.cs
Labels: status/needs-docs

#8226 Fix nested content clipboard
  src/Umbraco.Web.UI.Client/src/common/services/clipboard.service.js
Labels: release/8.6.3

#8175 Fix glitch in umb-checkbox background
  src/Umbraco.Web.UI.Client/src/less/components/umb-form-check.less
Labels: status/regression

#8234 Netcore: Migreate macro related controllers
  src/Umbraco.Core/IO/FileSystems.cs
  src/Umbraco.Core/IO/PhysicalFileSystem.cs
  src/Umbraco.Core/IO/ShadowWrapper.cs
  src/Umbraco.Core/Routing/DomainUtilities.cs
  src/Umbraco.Core/Routing/PublishedRequest.cs
  src/Umbraco.Core/Templates/IUmbracoComponentRenderer.cs
  src/Umbraco.Core/Templates/UmbracoComponentRenderer.cs
  src/Umbraco.Infrastructure/Composing/CompositionExtensions/FileSystems.cs
  src/Umbraco.Infrastructure/Runtime/CoreInitialComposer.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
  src/Umbraco.Tests/Components/ComponentTests.cs
  src/Umbraco.Tests/IO/FileSystemsTests.cs
  src/Umbraco.Tests/IO/PhysicalFileSystemTests.cs
  src/Umbraco.Tests/IO/ShadowFileSystemTests.cs
  src/Umbraco.Tests/Persistence/Repositories/PartialViewRepositoryTests.cs
  src/Umbraco.Tests/Persistence/Repositories/ScriptRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/StylesheetRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/TemplateRepositoryTest.cs
  src/Umbraco.Tests/Scoping/ScopeEventDispatcherTests.cs
  src/Umbraco.Tests/Scoping/ScopeFileSystemsTests.cs
  src/Umbraco.Tests/TestHelpers/TestObjects.cs
  src/Umbraco.Tests/Testing/TestingTests/MockTests.cs
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeAssetsController.cs
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeServerVariables.cs
  src/Umbraco.Web.BackOffice/Controllers/MacroRenderingController.cs
  src/Umbraco.Web.BackOffice/Controllers/MacrosController.cs
  src/Umbraco.Web.BackOffice/Extensions/UmbracoBackOfficeServiceCollectionExtensions.cs
  src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
  src/Umbraco.Web.Common/AspNetCore/UmbracoViewPage.cs
  src/Umbraco.Web.Common/Macros/PartialViewMacroEngine.cs
  src/Umbraco.Web.Common/Macros/PartialViewMacroViewComponent.cs
  src/Umbraco.Web.Common/Routing/PublicAccessChecker.cs
  src/Umbraco.Web.Common/Runtime/AspNetCoreComposer.cs
  src/Umbraco.Web.Common/Templates/TemplateRenderer.cs
  src/Umbraco.Web.UI.NetCore/Startup.cs
  src/Umbraco.Web.UI.NetCore/appsettings.json
  src/Umbraco.Web/Composing/Current.cs
  src/Umbraco.Web/Editors/BackOfficeServerVariables.cs
  src/Umbraco.Web/Runtime/WebInitialComposer.cs
  src/Umbraco.Web/Trees/FilesTreeController.cs
  src/Umbraco.Web/Umbraco.Web.csproj
  src/Umbraco.Web/UmbracoHelper.cs
Labels: project/net-core

#8290 Importing a doctype leaves behind temp files
  src/Umbraco.Web/Editors/ContentTypeController.cs
  src/Umbraco.Web/Models/ContentTypeImportModel.cs
Labels: release/8.7.0, type/bug

#8078 Add id attribute so click on property label focus in input
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/decimal/decimal.html
Labels: category/ux

#8286 NetCore: Updated various type filters to attributes with nested filters.
  src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeNotificationsController.cs
  src/Umbraco.Web.BackOffice/Controllers/DashboardController.cs
  src/Umbraco.Web.BackOffice/Controllers/DataTypeController.cs
  src/Umbraco.Web.BackOffice/Controllers/UmbracoAuthorizedJsonController.cs
  src/Umbraco.Web.BackOffice/Filters/AppendCurrentEventMessagesAttribute.cs
  src/Umbraco.Web.BackOffice/Filters/DataTypeValidateAttribute.cs
  src/Umbraco.Web.BackOffice/Filters/SetAngularAntiForgeryTokens.cs
  src/Umbraco.Web.BackOffice/Filters/SetAngularAntiForgeryTokensAttribute.cs
  src/Umbraco.Web.BackOffice/Filters/ValidateAngularAntiForgeryTokenAttribute.cs
  src/Umbraco.Web.Common/Controllers/UmbracoApiControllerBase.cs
  src/Umbraco.Web.Common/Filters/AngularJsonOnlyConfigurationAttribute.cs
  src/Umbraco.Web.Common/Install/InstallApiController.cs
Labels: project/net-core

#6545 Properly HTML encode text in helper methods
  src/Umbraco.Core/Models/PublishedContent/IndexedArrayItem.cs
  src/Umbraco.Web/HtmlHelperRenderExtensions.cs
  src/Umbraco.Web/HtmlStringUtilities.cs
  src/Umbraco.Web/Mvc/HtmlTagWrapperTextNode.cs
  src/Umbraco.Web/PublishedContentExtensions.cs
Labels: state/needs-investigation

#8187 Added content apps for document types
  src/Umbraco.Core/Manifest/ManifestContentAppFactory.cs
  src/Umbraco.Web.UI.Client/src/views/documenttypes/edit.controller.js
  src/Umbraco.Web/ContentApps/ContentEditorContentAppFactory.cs
  src/Umbraco.Web/ContentApps/ContentInfoContentAppFactory.cs
  src/Umbraco.Web/ContentApps/ContentTypeDesignContentAppFactory.cs
  src/Umbraco.Web/ContentApps/ContentTypeListViewContentAppFactory.cs
  src/Umbraco.Web/ContentApps/ContentTypePermissionsContentAppFactory.cs
  src/Umbraco.Web/ContentApps/ContentTypeTemplatesContentAppFactory.cs
  src/Umbraco.Web/ContentApps/ListViewContentAppFactory.cs
  src/Umbraco.Web/Models/ContentEditing/DocumentTypeDisplay.cs
  src/Umbraco.Web/Models/Mapping/CommonMapper.cs
  src/Umbraco.Web/Models/Mapping/ContentTypeMapDefinition.cs
  src/Umbraco.Web/Runtime/WebInitialComposer.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: community/pr, type/feature

#8074 Update slider to handle merging of overlapping tooltips
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbrangeslider.directive.js
Labels: category/ui

#8155 Accessibility improvement: umb-context-menu
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-contextmenu.html
Labels: category/accessibility, community/pr, release/8.7.0, type/feature

#8134 Use sql main dom lock as default if linux
  src/Umbraco.Web.Common/Extensions/UmbracoCoreServiceCollectionExtensions.cs
  src/Umbraco.Web/UmbracoApplication.cs
Labels: project/net-core
