Repository umbraco/Umbraco-CMS, pull requests merged in 2020-05, with the labels that each got.

#8057 Don't re-create indexes twice when rebuilding in the back office
  src/Umbraco.Web/Editors/ExamineManagementController.cs
Labels: community/review, type/bug

#8008 Netcore: #7898 Migrate Misc tests to new test project
  src/Umbraco.Tests.Common/Builders/XmlDocumentBuilder.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/DateTimeExtensionsTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/HashCodeCombinerTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/HashGeneratorTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/UriUtilityTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Xml/XmlHelperTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/Builders/XmlDocumentBuilderTests.cs
  src/Umbraco.Tests/Misc/XmlHelperTests.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
Labels: project/net-core

#8025 Migrated back office to ASP.NET Core Identity
  build/NuSpecs/UmbracoCms.Web.nuspec
  src/Umbraco.Core/ClaimsIdentityExtensions.cs
  src/Umbraco.Core/Constants-Web.cs
  src/Umbraco.Tests/CoreThings/ClaimsIdentityExtensionsTests.cs
  src/Umbraco.Tests/Security/AuthenticationExtensionsTests.cs
  src/Umbraco.Tests/Security/BackOfficeClaimsPrincipalFactoryTests.cs
  src/Umbraco.Tests/Security/BackOfficeUserManagerTests.cs
  src/Umbraco.Tests/Security/NopLookupNormalizerTests.cs
  src/Umbraco.Tests/Security/OwinDataProtectorTokenProviderTests.cs
  src/Umbraco.Tests/Security/UmbracoBackOfficeIdentityTests.cs
  src/Umbraco.Tests/Security/UmbracoSecurityStampValidatorTests.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
  src/Umbraco.Tests/Web/Controllers/UsersControllerTests.cs
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  src/Umbraco.Web/Editors/AuthenticationController.cs
  src/Umbraco.Web/Editors/BackOfficeController.cs
  src/Umbraco.Web/Editors/BackOfficeServerVariables.cs
  src/Umbraco.Web/Editors/CurrentUserController.cs
  src/Umbraco.Web/Editors/PasswordChanger.cs
  src/Umbraco.Web/Editors/UsersController.cs
  src/Umbraco.Web/HtmlHelperBackOfficeExtensions.cs
  src/Umbraco.Web/Install/InstallSteps/NewInstallStep.cs
  src/Umbraco.Web/Models/Identity/IdentityUser.cs
  src/Umbraco.Web/Models/Identity/UserLoginInfoWrapper.cs
  src/Umbraco.Web/OwinExtensions.cs
  src/Umbraco.Web/Security/AppBuilderExtensions.cs
  src/Umbraco.Web/Security/AuthenticationExtensions.cs
  src/Umbraco.Web/Security/AuthenticationManagerExtensions.cs
  src/Umbraco.Web/Security/BackOfficeClaimsIdentityFactory.cs
  src/Umbraco.Web/Security/BackOfficeClaimsPrincipalFactory.cs
  src/Umbraco.Web/Security/BackOfficeCookieAuthenticationProvider.cs
  src/Umbraco.Web/Security/BackOfficeSignInManager.cs
  src/Umbraco.Web/Security/BackOfficeUserManager.cs
  src/Umbraco.Web/Security/BackOfficeUserManagerMarker.cs
  src/Umbraco.Web/Security/BackOfficeUserStore.cs
  src/Umbraco.Web/Security/BackOfficeUserValidator.cs
  src/Umbraco.Web/Security/EmailService.cs
  src/Umbraco.Web/Security/ExternalSignInAutoLinkOptions.cs
  src/Umbraco.Web/Security/IBackOfficeUserManagerMarker.cs
  src/Umbraco.Web/Security/IUserAwarePasswordHasher.cs
  src/Umbraco.Web/Security/IUserSessionStore.cs
  src/Umbraco.Web/Security/IdentityFactoryMiddleware.cs
  src/Umbraco.Web/Security/NopLookupNormalizer.cs
  src/Umbraco.Web/Security/OwinDataProtectorTokenProvider.cs
  src/Umbraco.Web/Security/SessionIdValidator.cs
  src/Umbraco.Web/Security/UmbracoBackOfficeIdentity.cs
  src/Umbraco.Web/Security/UmbracoEmailMessage.cs
  src/Umbraco.Web/Security/UmbracoSecurityStampValidator.cs
  src/Umbraco.Web/Security/UserAwarePasswordHasher.cs
  src/Umbraco.Web/Security/WebSecurity.cs
  src/Umbraco.Web/Umbraco.Web.csproj
  src/Umbraco.Web/UmbracoDefaultOwinStartup.cs
  src/Umbraco.Web/WebApi/UmbracoAuthorizedApiController.cs
Labels: project/net-core

#8064 UI: Corrected validation indication in variant-picker
  src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorcontentheader.directive.js
  src/Umbraco.Web.UI.Client/src/common/services/servervalidationmgr.service.js
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-content-header.html
Labels: category/front-end, state/sprint-candidate

#5677 New user journey for the DataType Picker in the DocumentType Editor
  src/Umbraco.Web.UI.Client/src/common/filters/umbCmsJoinArray.filter.js
  src/Umbraco.Web.UI.Client/src/common/filters/umbCmsTitleCase.filter.js
  src/Umbraco.Web.UI.Client/src/less/components/card.less
  src/Umbraco.Web.UI.Client/src/less/components/overlays.less
  src/Umbraco.Web.UI.Client/src/less/components/overlays/umb-itempicker.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-group-builder.less
  src/Umbraco.Web.UI.Client/src/less/forms/umb-validation-label.less
  src/Umbraco.Web.UI.Client/src/less/variables.less
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypeconfigurationpicker/datatypeconfigurationpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypeconfigurationpicker/datatypeconfigurationpicker.html
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypepicker/datatypepicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypepicker/datatypepicker.html
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/propertysettings/propertysettings.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/propertysettings/propertysettings.html
  src/Umbraco.Web.UI.Client/src/views/components/overlays/umb-overlay.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-groups-builder.html
  src/Umbraco.Web.UI.Client/src/views/documenttypes/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/macros/infiniteeditors/parameter.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
  src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: category/ux, release/8.7.0, state/sprint-candidate

#8014 Add utility function equivalent to angular.fromJson
  src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbrawmodel.directive.js
  src/Umbraco.Web.UI.Client/src/common/mocks/resources/_utils.js
  src/Umbraco.Web.UI.Client/src/common/services/util.service.js
  src/Umbraco.Web.UI.Client/src/utilities.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macropicker/macropicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/treepicker/treepicker.controller.js
  src/Umbraco.Web.UI.Client/test/unit/utilities.spec.js
Labels: release/8.7.0

#2980 Update old string format for a language area alias and a language key…
  src/Umbraco.Web/Trees/ContentTypeTreeController.cs
  src/Umbraco.Web/Trees/DataTypeTreeController.cs
  src/Umbraco.Web/Trees/MediaTypeTreeController.cs
Labels: state/sprint-candidate

#8065 Validation errors reworked to incorporate segment errors
  src/Umbraco.Tests/Web/Controllers/ContentControllerTests.cs
  src/Umbraco.Tests/Web/ModelStateExtensionsTests.cs
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
  src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js
  src/Umbraco.Web/Editors/ContentController.cs
  src/Umbraco.Web/ModelStateExtensions.cs
Labels: state/sprint-candidate

#8070 Added support for segments to File Uploads
  src/Umbraco.Core/Models/Editors/ContentPropertyFile.cs
  src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbpropertyfileupload.directive.js
  src/Umbraco.Web.UI.Client/src/common/services/filemanager.service.js
  src/Umbraco.Web.UI.Client/src/common/services/umbrequesthelper.service.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/fileupload/fileupload.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/fileupload/fileupload.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.html
  src/Umbraco.Web/Editors/Binders/ContentModelBinderHelper.cs
  src/Umbraco.Web/Editors/ContentControllerBase.cs
Labels: state/sprint-candidate

#8142 Netcore: Re-implementing Email Service
  src/Umbraco.Configuration/Legacy/SmtpSettings.cs
  src/Umbraco.Configuration/Models/GlobalSettings.cs
  src/Umbraco.Core/Configuration/ISmtpSettings.cs
  src/Umbraco.Infrastructure/Runtime/CoreInitialComposer.cs
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.Infrastructure/Users/EmailSender.cs
  src/Umbraco.Tests.Common/Builders/SmtpSettingsBuilder.cs
  src/Umbraco.Tests/Testing/UmbracoTestBase.cs
  src/Umbraco.Tests/Web/Controllers/AuthenticationControllerTests.cs
  src/Umbraco.Tests/Web/Controllers/UsersControllerTests.cs
  src/Umbraco.Web.UI.NetCore/appsettings.json
  src/Umbraco.Web/Editors/AuthenticationController.cs
  src/Umbraco.Web/Editors/UsersController.cs
Labels: project/net-core

#8135 Netcore: Migrate Controllers
  src/Umbraco.Core/Models/ImageUrlGenerationOptions.cs
  src/Umbraco.Infrastructure/Media/ImageSharpImageUrlGenerator.cs
  src/Umbraco.Infrastructure/Models/UserExtensions.cs
  src/Umbraco.Infrastructure/PropertyEditors/RichTextEditorPastedImages.cs
  src/Umbraco.Tests/Models/ImageProcessorImageUrlGeneratorTest.cs
  src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeAssetsController.cs
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
  src/Umbraco.Web.BackOffice/Controllers/DashboardController.cs
  src/Umbraco.Web.BackOffice/Controllers/ExamineManagementController.cs
  src/Umbraco.Web.BackOffice/Controllers/HelpController.cs
  src/Umbraco.Web.BackOffice/Controllers/ImageUrlGeneratorController.cs
  src/Umbraco.Web.BackOffice/Controllers/ImagesController.cs
  src/Umbraco.Web.BackOffice/Controllers/TourController.cs
  src/Umbraco.Web.BackOffice/Controllers/UmbracoAuthorizedApiController.cs
  src/Umbraco.Web.BackOffice/Controllers/UmbracoAuthorizedJsonController.cs
  src/Umbraco.Web.BackOffice/Filters/EditorModelEventManager.cs
  src/Umbraco.Web.BackOffice/Filters/OutgoingEditorModelEventAttribute.cs
  src/Umbraco.Web.BackOffice/Filters/UmbracoAuthorizeFilter.cs
  src/Umbraco.Web.BackOffice/Filters/UmbracoWebApiRequireHttpsAttribute.cs
  src/Umbraco.Web.BackOffice/Filters/ValidateAngularAntiForgeryTokenAttribute.cs
  src/Umbraco.Web.Common/Exceptions/HttpResponseException.cs
  src/Umbraco.Web.Common/Extensions/ActionResultExtensions.cs
  src/Umbraco.Web.Common/Extensions/LinkGeneratorExtensions.cs
  src/Umbraco.Web.Common/Security/WebSecurity.cs
  src/Umbraco.Web.Common/UmbracoContext/UmbracoContextFactory.cs
  src/Umbraco.Web.UI.NetCore/Config/BackOfficeTours/getting-started.json
  src/Umbraco.Web/Editors/BackOfficeController.cs
  src/Umbraco.Web/Editors/BackOfficeServerVariables.cs
  src/Umbraco.Web/Editors/ContentController.cs
  src/Umbraco.Web/Editors/MediaController.cs
  src/Umbraco.Web/Editors/MemberController.cs
  src/Umbraco.Web/Editors/UsersController.cs
  src/Umbraco.Web/ImageCropperTemplateCoreExtensions.cs
  src/Umbraco.Web/Umbraco.Web.csproj
  src/Umbraco.Web/WebApi/Filters/OutgoingEditorModelEventAttribute.cs
  src/Umbraco.Web/WebApi/Filters/UmbracoWebApiRequireHttpsAttribute.cs
  src/Umbraco.Web/WebApi/UmbracoAuthorizedApiController.cs
Labels: project/net-core

#7102 V8: Accessibility Changes For umbEditorHeader Directive (edit user)
  src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorheader.directive.js
  src/Umbraco.Web.UI.Client/src/views/users/user.controller.js
Labels: category/accessibility

#7104 v8: Accessibility Create User Page Title
  src/Umbraco.Web.UI.Client/src/views/users/views/users/users.controller.js
Labels: category/accessibility

#5800 V8: Accessibility changes for login screen
  src/Umbraco.Web.UI.Client/src/common/directives/components/application/umblogin.directive.js
  src/Umbraco.Web.UI.Client/src/less/pages/login.less
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-login.html
Labels: category/accessibility

#8011 Convert date/time picker span to button, add missing label, hide icons for screen readers
  src/Umbraco.Web.UI.Client/src/less/property-editors.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/datepicker/datepicker.html
Labels: category/accessibility, community/pr, release/8.7.0, type/feature

#8091 Bugfix: Adds new confirmation email marketing step
  src/Umbraco.Web.UI.Client/src/views/common/tours/umbEmailMarketing/confirm/confirm.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/tours/umbEmailMarketing/confirm/confirm.html
  src/Umbraco.Web.UI.Client/src/views/common/tours/umbEmailMarketing/emails/emails.controller.js
  src/Umbraco.Web.UI/config/BackOfficeTours/getting-started.json
Labels: release/8.7.0

#8200 V8/bugfix/gulp update inline views on watch
  src/Umbraco.Web.UI.Client/gulp/config.js
  src/Umbraco.Web.UI.Client/gulp/modes.js
  src/Umbraco.Web.UI.Client/gulp/tasks/test.js
  src/Umbraco.Web.UI.Client/gulp/tasks/watchTask.js
  src/Umbraco.Web.UI.Client/gulp/util/processJs.js
  src/Umbraco.Web.UI.Client/gulpfile.js
Labels: community/review

#8189 Fix HTML markup of umb-list-view-settings.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-list-view-settings.html
Labels: community/pr, release/8.7.0, release/no-notes, type/bug

#7166 NC keys: Do not copy keys for Nested Content (Fix for #7133)
  src/Umbraco.Web.UI.Client/src/common/services/clipboard.service.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
  src/Umbraco.Web.UI.Client/test/config/app.unit.js
  src/Umbraco.Web/Compose/NestedContentPropertyComponent.cs
  src/Umbraco.Web/Compose/NestedContentPropertyComposer.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: release/8.6.2
