Repository umbraco/Umbraco-CMS, pull requests merged in 2020-08, with the labels that each got.

#8588 better null checking for config validation limits
  src/Umbraco.Web/PropertyEditors/BlockEditorPropertyEditor.cs
Labels: project/block-editor

#8589 Ensure that we validate all properties for a block based on it's element type properties, not just the property values that are POSTed
  src/Umbraco.Core/Models/Blocks/BlockItemData.cs
  src/Umbraco.Web/PropertyEditors/BlockEditorPropertyEditor.cs
  src/Umbraco.Web/PropertyEditors/NestedContentPropertyEditor.cs
Labels: project/block-editor

#7596 Adds new methods to MembershipHelper for dealing with checking bulk paths for access
  src/Umbraco.Web/Security/MembershipHelper.cs
Labels: category/breaking, community/review, release/8.8.0, type/feature

#8601 Fixing publish descendants dialog
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.controller.js
  src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.html
  src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: state/sprint-candidate

#8584 Netcore: Added request localization from the current user.
  src/Umbraco.Core/Security/AuthenticationExtensions.cs
  src/Umbraco.Web.Common/ApplicationModels/BackOfficeApplicationModelProvider.cs
  src/Umbraco.Web.Common/ApplicationModels/BackOfficeIdentityCultureConvention.cs
  src/Umbraco.Web.Common/ApplicationModels/UmbracoApiBehaviorApplicationModelProvider.cs
  src/Umbraco.Web.Common/Extensions/UmbracoBackOfficeIdentityCultureProvider.cs
  src/Umbraco.Web.Common/Extensions/UmbracoCoreServiceCollectionExtensions.cs
  src/Umbraco.Web.Common/Extensions/UmbracoWebServiceCollectionExtensions.cs
  src/Umbraco.Web.Common/Filters/BackOfficeCultureFilter.cs
  src/Umbraco.Web.UI.NetCore/Startup.cs
Labels: project/net-core

#8591 Netcore: Let build.ps1 create the dotnet new templates
  build/NuSpecs/UmbracoCms.SqlCe.nuspec
  build/NuSpecs/UmbracoCms.Web.nuspec
  build/build.ps1
  build/templates/Umbraco.Templates.nuspec
  build/templates/UmbracoSolution/.template.config/template.json
  build/templates/UmbracoSolution/UmbracoSolution.csproj
  src/Umbraco.Tests.Integration/TestServerTest/UmbracoWebApplicationFactory.cs
  src/Umbraco.Web.UI.NetCore/Program.cs
  src/Umbraco.Web.UI.NetCore/Startup.cs
  src/umbraco.sln
Labels: project/net-core

#8613 UI for highlighting validation issues
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/inlineblock/inlineblock.editor.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/inlineblock/inlineblock.editor.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/labelblock/labelblock.editor.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-row.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
Labels: category/ui

#8572 Migrates remaining non-oauth actions on back office controller to netcore
  src/Umbraco.Infrastructure/Migrations/Install/DatabaseBuilder.cs
  src/Umbraco.Infrastructure/Services/Implement/KeyValueService.cs
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
  src/Umbraco.Web.UI.NetCore/Umbraco/UmbracoBackOffice/AuthorizeUpgrade.cshtml
  src/Umbraco.Web/Editors/BackOfficeController.cs
Labels: project/net-core

#8634 Support SQL Server 2012 syntax on SQL Server 2019
  src/Umbraco.Core/Persistence/SqlSyntax/SqlServerSyntaxProvider.cs
  src/Umbraco.Core/Persistence/UmbracoDatabaseFactory.cs
Labels: release/8.8.0, type/bug

#8641 Fixed log viewer level filter by correcting binding for provided array of selected values to filter by.
  src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
  src/Umbraco.Web.BackOffice/Controllers/LogViewerController.cs
Labels: project/net-core

#7876 property group header adjustment
  src/Umbraco.Web.UI.Client/src/less/components/html/umb-group-panel.less
  src/Umbraco.Web.UI.Client/src/views/components/property/umb-property.html
Labels: category/ui, community/review

#8672 NetCore: Migrate GetCurrentUserLinkedLogins api
  src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
  src/Umbraco.Web.BackOffice/Controllers/CurrentUserController.cs
  src/Umbraco.Web.UI.Client/src/common/resources/auth.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/currentuser.resource.js
  src/Umbraco.Web.UI.Client/src/views/common/overlays/user/user.controller.js
  src/Umbraco.Web/Editors/AuthenticationController.cs
Labels: project/net-core

#8674 Netcore: Update user on successful login
  src/Umbraco.Web.Common/Security/BackOfficeSignInManager.cs
Labels: project/net-core

#8630 Support include in sql server indexes
  src/Umbraco.Core/Persistence/DatabaseAnnotations/IndexAttribute.cs
  src/Umbraco.Core/Persistence/DatabaseModelDefinitions/DefinitionFactory.cs
  src/Umbraco.Core/Persistence/DatabaseModelDefinitions/IndexDefinition.cs
  src/Umbraco.Core/Persistence/SqlSyntax/SqlCeSyntaxProvider.cs
  src/Umbraco.Core/Persistence/SqlSyntax/SqlServerSyntaxProvider.cs
Labels: release/8.8.0, type/feature

#8427 Rerunning first tour resets tour data
  src/Umbraco.Tests.AcceptanceTest/README.md
  src/Umbraco.Tests.AcceptanceTest/cypress/integration/Tour/backofficeTour.ts
Labels: category/test-automation, community/pr, type/feature

#8715 8.7RC umb-block-card absolute path and dont scale SVGs
  src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.html
  src/Umbraco.Web.UI.Client/src/views/components/blockcard/umbBlockCard.component.js
Labels: project/block-editor, state/sprint-candidate

#8669 V8.7RC Sort paste entries by date
  src/Umbraco.Web.UI.Client/src/common/services/clipboard.service.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
Labels: state/sprint-candidate

#8583 Fix: v7 Base64 image performance in rich text editor
  src/Umbraco.Web/Templates/TemplateUtilities.cs
Labels: category/preview, release/7.15.7, type/bug

#8556 Update styling of listview layout icons
  src/Umbraco.Web.UI.Client/src/less/listview.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts.prevalues.html
Labels: category/ui, community/pr, release/8.8.0, type/feature

#8645 NetCore: Migrating some Repository tests
  src/Umbraco.Tests.Common/TestHelpers/Entities/MockedMedia.cs
  src/Umbraco.Tests.Common/TestHelpers/Entities/MockedMember.cs
  src/Umbraco.Tests.Common/TestHelpers/Entities/MockedUserGroup.cs
  src/Umbraco.Tests.Integration/Extensions/ApplicationBuilderExtensions.cs
  src/Umbraco.Tests.Integration/Persistence/Repositories/DictionaryRepositoryTest.cs
  src/Umbraco.Tests.Integration/Persistence/Repositories/EntityRepositoryTest.cs
  src/Umbraco.Tests.Integration/Persistence/Repositories/KeyValueRepositoryTests.cs
  src/Umbraco.Tests.Integration/Persistence/Repositories/LanguageRepositoryTest.cs
  src/Umbraco.Tests.Integration/Persistence/Repositories/MacroRepositoryTest.cs
  src/Umbraco.Tests.Integration/Persistence/Repositories/NotificationsRepositoryTest.cs
  src/Umbraco.Tests.Integration/Persistence/Repositories/RedirectUrlRepositoryTests.cs
  src/Umbraco.Tests.Integration/Persistence/Repositories/RelationTypeRepositoryTest.cs
  src/Umbraco.Tests.Integration/Persistence/Repositories/ServerRegistrationRepositoryTest.cs
  src/Umbraco.Tests.Integration/Persistence/Repositories/SimilarNodeNameTests.cs
  src/Umbraco.Tests.Integration/Persistence/Repositories/TemplateRepositoryTest.cs
  src/Umbraco.Tests.Integration/Persistence/Repositories/UserGroupRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/UserRepositoryTest.cs
  src/Umbraco.Tests/Services/ContentServiceTests.cs
  src/Umbraco.Tests/Services/UserServiceTests.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
Labels: project/net-core

#8731 NetCore: Add file name tests
  src/Umbraco.Tests.UnitTests/AutoFixture/AutoMoqDataAttribute.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/FileNameTests.cs
  src/Umbraco.Web.Common/Extensions/LinkGeneratorExtensions.cs
  src/Umbraco.Web.Common/Extensions/UrlHelperExtensions.cs
  src/Umbraco.Web.Common/Install/InstallController.cs
Labels: project/net-core

#8748 Fix: v7 BeginTransaction null reference after custom migrations
  src/Umbraco.Core/Persistence/PetaPoco.cs
  src/Umbraco.Core/Scoping/Scope.cs
Labels: community/pr, release/7.15.7, type/bug

#8738 Userpicker view: Change anchor element to button
  src/Umbraco.Web.UI.Client/src/less/components/users/umb-user-picker-list.less
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/userpicker/userpicker.html
Labels: category/accessibility
