Repository umbraco/Umbraco-CMS, pull requests merged in 2020-11, with the labels that each got.

#9318 Netcore : Fixed issue in ScopedRepositoryTests
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Scoping/ScopedRepositoryTests.cs
Labels: hacktoberfest-accepted, project/net-core

#9323 NetCore: Fixes registration issue
  src/Umbraco.Core/ServiceCollectionExtensions.cs
  src/Umbraco.Web.Common/Runtime/AspNetCoreComposer.cs
Labels: hacktoberfest-accepted, project/net-core

#9241 Make blockConfigModel optional
  src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.html
  src/Umbraco.Web.UI.Client/src/views/components/blockcard/umbBlockCard.component.js
Labels: hacktoberfest-accepted, state/sprint-candidate

#9243 use umb-outline for umb-block-card
  src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.less
Labels: category/accessibility, category/ui, hacktoberfest-accepted, release/8.10.0, state/sprint-candidate

#9324 Netcore: Migrates further background tasks to hosted services
  src/Umbraco.Core/Configuration/Models/KeepAliveSettings.cs
  src/Umbraco.Core/Configuration/Models/LoggingSettings.cs
  src/Umbraco.Core/IO/CleanFolderResult.cs
  src/Umbraco.Core/IO/CleanFolderResultStatus.cs
  src/Umbraco.Core/IO/IIOHelper.cs
  src/Umbraco.Core/IO/IOHelper.cs
  src/Umbraco.Core/Scheduling/TempFileCleanup.cs
  src/Umbraco.Infrastructure/HostedServices/HealthCheckNotifier.cs
  src/Umbraco.Infrastructure/HostedServices/KeepAlive.cs
  src/Umbraco.Infrastructure/HostedServices/LogScrubber.cs
  src/Umbraco.Infrastructure/HostedServices/RecurringHostedServiceBase.cs
  src/Umbraco.Infrastructure/HostedServices/TempFileCleanup.cs
  src/Umbraco.Infrastructure/Scheduling/LogScrubber.cs
  src/Umbraco.Infrastructure/Scheduling/SchedulerComponent.cs
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/HealthCheckNotifierTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/KeepAliveTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/LogScrubberTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/TempFileCleanupTests.cs
  src/Umbraco.Web.BackOffice/Extensions/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Builder/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Extensions/UmbracoCoreServiceCollectionExtensions.cs
Labels: hacktoberfest-accepted, project/net-core

#9330 NetCore: Fixes registration issue (continued)
  src/Umbraco.Core/ServiceCollectionExtensions.cs
  src/Umbraco.Web.Common/Runtime/AspNetCoreComposer.cs
Labels: project/net-core

#9332 NetCore: Migrated scheduled publishing task to a hosted service.
  src/Umbraco.Infrastructure/HostedServices/ScheduledPublishing.cs
  src/Umbraco.Infrastructure/Scheduling/SchedulerComponent.cs
  src/Umbraco.Infrastructure/Scheduling/SchedulerComposer.cs
  src/Umbraco.Tests.Integration/Testing/IntegrationTestComposer.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/ScheduledPublishingTests.cs
  src/Umbraco.Web.Common/Extensions/UmbracoCoreServiceCollectionExtensions.cs
Labels: project/net-core

#9336 Netcore: Migrate our custom view engines
  src/Umbraco.Core/Constants-SystemDirectories.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.Website/ViewEngines/ProfilingViewEngineWrapperMvcViewOptionsSetupTests.cs
  src/Umbraco.Tests/Runtimes/WebRuntimeComponentTests.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
  src/Umbraco.Web.Website/Extensions/UmbracoWebstiteServiceCollectionExtensions.cs
  src/Umbraco.Web.Website/ViewEngines/IPluginViewEngine.cs
  src/Umbraco.Web.Website/ViewEngines/IRenderViewEngine.cs
  src/Umbraco.Web.Website/ViewEngines/PluginMvcViewOptionsSetup.cs
  src/Umbraco.Web.Website/ViewEngines/PluginViewEngine.cs
  src/Umbraco.Web.Website/ViewEngines/ProfilingViewEngine.cs
  src/Umbraco.Web.Website/ViewEngines/ProfilingViewEngineWrapperMvcViewOptionsSetup.cs
  src/Umbraco.Web.Website/ViewEngines/RenderMvcViewOptionsSetup.cs
  src/Umbraco.Web.Website/ViewEngines/RenderViewEngine.cs
  src/Umbraco.Web/Mvc/PluginViewEngine.cs
  src/Umbraco.Web/Mvc/ProfilingViewEngine.cs
  src/Umbraco.Web/Mvc/RenderViewEngine.cs
  src/Umbraco.Web/Runtime/WebInitialComponent.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: project/net-core

#9272 Returning response from downloadFile promise
  src/Umbraco.Web.UI.Client/src/common/services/umbrequesthelper.service.js
Labels: hacktoberfest-accepted

#8747 Resolves issue with rendering back-office media selections when synchronous IO is not allowed.
  src/Umbraco.Web.BackOffice/Controllers/DetermineAmbiguousActionByPassingParameters.cs
  src/Umbraco.Web.BackOffice/Extensions/BackOfficeServiceCollectionExtensions.cs
  src/Umbraco.Web.Common/Extensions/HttpRequestExtensions.cs
Labels: project/net-core

#9361 Limit access to logviewer endpoints to people with access to the settings section
  src/Umbraco.Web/Editors/LogViewerController.cs
Labels: release/8.10.0, type/bug

#9356 NetCore: MSDI refactor split CoreRuntime & Remove Current
  src/Umbraco.Core/Composing/Current.cs
  src/Umbraco.Core/Models/ContentEditing/UserInvite.cs
  src/Umbraco.Core/Models/Member.cs
  src/Umbraco.Core/PublishedContentExtensions.cs
  src/Umbraco.Core/Services/IRuntime.cs
  src/Umbraco.Core/StaticApplicationLogging.cs
  src/Umbraco.Core/UriExtensions.cs
  src/Umbraco.Infrastructure/CompositionExtensions_Essentials.cs
  src/Umbraco.Infrastructure/Events/QueuingEventDispatcher.cs
  src/Umbraco.Infrastructure/HealthCheck/HealthCheckResults.cs
  src/Umbraco.Infrastructure/Models/PropertyTagsExtensions.cs
  src/Umbraco.Infrastructure/Persistence/DbConnectionExtensions.cs
  src/Umbraco.Infrastructure/Persistence/UmbracoDatabaseExtensions.cs
  src/Umbraco.Infrastructure/PropertyEditors/DataEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/DataValueEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/GridValueConverter.cs
  src/Umbraco.Infrastructure/Routing/NotFoundHandlerHelper.cs
  src/Umbraco.Infrastructure/Runtime/CoreRuntime.cs
  src/Umbraco.Infrastructure/Runtime/CoreRuntimeBootstrapper.cs
  src/Umbraco.Infrastructure/Services/Implement/ContentService.cs
  src/Umbraco.Infrastructure/Services/Implement/EntityXmlSerializer.cs
  src/Umbraco.Infrastructure/Services/Implement/LocalizedTextServiceFileSources.cs
  src/Umbraco.Infrastructure/Suspendable.cs
  src/Umbraco.Infrastructure/Sync/ServerMessengerBase.cs
  src/Umbraco.Infrastructure/Trees/TreeNode.cs
  src/Umbraco.Tests.Integration/RuntimeTests.cs
  src/Umbraco.Tests.Integration/TestServerTest/UmbracoBuilderExtensions.cs
  src/Umbraco.Tests.Integration/TestServerTest/UmbracoTestServerTestBase.cs
  src/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEventsTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServicePerformanceTest.cs
  src/Umbraco.Tests/Routing/RenderRouteHandlerTests.cs
  src/Umbraco.Tests/Runtimes/CoreRuntimeTests.cs
  src/Umbraco.Tests/Web/Mvc/ValidateUmbracoFormRouteStringAttributeTests.cs
  src/Umbraco.Web.BackOffice/Controllers/ContentControllerBase.cs
  src/Umbraco.Web.BackOffice/Controllers/UpdateCheckController.cs
  src/Umbraco.Web.BackOffice/Extensions/BackOfficeApplicationBuilderExtensions.cs
  src/Umbraco.Web.BackOffice/Trees/PartialViewMacrosTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/PartialViewsTreeController.cs
  src/Umbraco.Web.Common/Controllers/UmbracoController.cs
  src/Umbraco.Web.Common/Extensions/ApplicationBuilderExtensions.cs
  src/Umbraco.Web.Common/Extensions/ImageCropperTemplateExtensions.cs
  src/Umbraco.Web.Common/Extensions/UmbracoCoreServiceCollectionExtensions.cs
  src/Umbraco.Web.Common/UmbracoContext/UmbracoContext.cs
  src/Umbraco.Web.UI.NetCore/umbraco/UmbracoInstall/Index.cshtml
  src/Umbraco.Web/Composing/Current.cs
  src/Umbraco.Web/Logging/OwinLoggerFactory.cs
  src/Umbraco.Web/UmbracoApplication.cs
  src/Umbraco.Web/UmbracoApplicationBase.cs
  src/Umbraco.Web/UmbracoHelper.cs
Labels: project/net-core

#9353 NetCore: Migrated database server registrar and messenger tasks into hosted services
  src/Umbraco.Core/Configuration/Models/DatabaseServerMessengerSettings.cs
  src/Umbraco.Core/Configuration/Models/DatabaseServerRegistrarSettings.cs
  src/Umbraco.Core/Configuration/Models/GlobalSettings.cs
  src/Umbraco.Core/Sync/DatabaseServerMessengerCallbacks.cs
  src/Umbraco.Core/Sync/DatabaseServerMessengerOptions.cs
  src/Umbraco.Core/Sync/DatabaseServerRegistrar.cs
  src/Umbraco.Core/Sync/DatabaseServerRegistrarOptions.cs
  src/Umbraco.Core/Sync/IBatchedDatabaseServerMessenger.cs
  src/Umbraco.Infrastructure/BatchedDatabaseServerMessenger.cs
  src/Umbraco.Infrastructure/Compose/DatabaseServerRegistrarAndMessengerComponent.cs
  src/Umbraco.Infrastructure/CompositionExtensions.cs
  src/Umbraco.Infrastructure/HostedServices/ServerRegistration/InstructionProcessTask.cs
  src/Umbraco.Infrastructure/HostedServices/ServerRegistration/TouchServerTask.cs
  src/Umbraco.Infrastructure/Runtime/CoreInitialComposer.cs
  src/Umbraco.Infrastructure/Sync/DatabaseServerMessenger.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/HealthCheckNotifierTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/ScheduledPublishingTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/ServerRegistration/InstructionProcessTaskTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/ServerRegistration/TouchServerTaskTests.cs
  src/Umbraco.Web.Common/AspNetCore/AspNetCoreRequestAccessor.cs
  src/Umbraco.Web.Common/Extensions/UmbracoCoreServiceCollectionExtensions.cs
Labels: project/net-core

#9372 Netcore: Misc Remove BuildServiceProvider call
  src/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
  src/Umbraco.Web.Common/Builder/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Extensions/UmbracoWebServiceCollectionExtensions.cs
Labels: project/net-core

#9388 NetCore: Install page db checks
  src/Umbraco.Infrastructure/Install/InstallSteps/DatabaseConfigureStep.cs
  src/Umbraco.Web.UI.Client/src/installer/steps/database.html
Labels: project/net-core

#9302 Updated editor.service.js for consistency
  src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
Labels: hacktoberfest-accepted

#9210 Conditionally show check icon if umb-tree-item is selected
  src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-item.html
Labels: hacktoberfest-accepted

#9069 umb-control-group directive: Fix styling issue
  src/Umbraco.Web.UI.Client/src/views/components/html/umb-control-group.html
Labels: hacktoberfest-accepted

#9312 This PR sets the page title when editing and maintaining languages
  src/Umbraco.Web.UI.Client/src/views/languages/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/languages/overview.controller.js
Labels: category/accessibility, hacktoberfest-accepted

#9380 Netcore: Use DefaultControllerActivator
  src/Umbraco.Web.BackOffice/Extensions/BackOfficeServiceCollectionExtensions.cs
  src/Umbraco.Web.BackOffice/Extensions/CompositionExtensions.cs
  src/Umbraco.Web.BackOffice/Runtime/BackOfficeComposer.cs
  src/Umbraco.Web.Common/Extensions/CompositionExtensions.cs
  src/Umbraco.Web.Common/Runtime/AspNetCoreComposer.cs
  src/Umbraco.Web.UI.NetCore/Program.cs
  src/Umbraco.Web.Website/Extensions/CompositionExtensions.cs
  src/Umbraco.Web.Website/Extensions/UmbracoWebstiteServiceCollectionExtensions.cs
  src/Umbraco.Web.Website/Runtime/WebsiteComposer.cs
Labels: project/net-core

#9400 Turkish language has been arranged according to v8
  src/Umbraco.Web.UI/Umbraco/config/lang/tr.xml
Labels: release/8.10.0

#9213 Documentation link updated - umbdrawer
  src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbdrawer/umbdrawer.directive.js
Labels: hacktoberfest-accepted

#9161 Styling all code elements in backoffice UI docs
  src/Umbraco.Web.UI.Docs/umb-docs.css
Labels: category/api-documentation, category/ui, hacktoberfest-accepted, release/8.10.0

#9206 Change comments to use allowed and disallowed
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/grid/grid.listviewlayout.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/list/list.listviewlayout.controller.js
Labels: community/pr, hacktoberfest-accepted, hacktoberfest/contrib-2020, release/8.10.0, release/no-notes

#9204 Fix mis-spelt "occurred"
  src/Umbraco.Web.UI.Client/src/common/services/umbrequesthelper.service.js
  src/Umbraco.Web/Editors/UsersController.cs
Labels: hacktoberfest-accepted, hacktoberfest/contrib-2020, release/no-notes, type/bug

#9201 Added documentation for umbContextMenu
  src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbcontextmenu.directive.js
Labels: hacktoberfest-accepted

#9111 Allow to close list view settings overlay via esc shortcut
  src/Umbraco.Web.UI.Client/src/views/components/umb-list-view-settings-overlay.html
Labels: hacktoberfest-accepted

#9048 Do not show cryptic confirm dialog when editing group
  src/Umbraco.Web.UI.Client/src/views/users/group.controller.js
  src/Umbraco.Web.UI.Client/src/views/users/group.html
Labels: hacktoberfest-accepted

#9401 Netcore: Turn container validation back on
  src/Umbraco.Core/Composing/Composers.cs
  src/Umbraco.Core/Composing/RuntimeLevelAttribute.cs
  src/Umbraco.Examine.Lucene/ExamineLuceneComposer.cs
  src/Umbraco.Examine.Lucene/ExamineLuceneFinalComposer.cs
  src/Umbraco.Infrastructure/Cache/DistributedCacheBinderComposer.cs
  src/Umbraco.Infrastructure/Compose/BlockEditorComposer.cs
  src/Umbraco.Infrastructure/Compose/DatabaseServerRegistrarAndMessengerComponent.cs
  src/Umbraco.Infrastructure/Compose/ManifestWatcherComposer.cs
  src/Umbraco.Infrastructure/Compose/NestedContentPropertyComposer.cs
  src/Umbraco.Infrastructure/Compose/NotificationsComposer.cs
  src/Umbraco.Infrastructure/Compose/PublicAccessComposer.cs
  src/Umbraco.Infrastructure/Compose/RelateOnCopyComposer.cs
  src/Umbraco.Infrastructure/Compose/RelateOnTrashComposer.cs
  src/Umbraco.Infrastructure/Logging/Viewer/LogViewerComposer.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_8_0_0/DataTypes/PreValueMigratorComposer.cs
  src/Umbraco.Infrastructure/PropertyEditors/PropertyEditorsComposer.cs
  src/Umbraco.Infrastructure/Routing/RedirectTrackingComposer.cs
  src/Umbraco.Infrastructure/Search/ExamineComposer.cs
  src/Umbraco.Infrastructure/Search/ExamineFinalComposer.cs
  src/Umbraco.ModelsBuilder.Embedded/Compose/ModelsBuilderComposer.cs
  src/Umbraco.Tests.Integration/RuntimeTests.cs
  src/Umbraco.Tests.Integration/Testing/IntegrationTestComposer.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Components/ComponentTests.cs
  src/Umbraco.Web.BackOffice/Extensions/BackOfficeServiceCollectionExtensions.cs
  src/Umbraco.Web.BackOffice/Security/ConfigureBackOfficeCookieOptions.cs
  src/Umbraco.Web.BackOffice/SignalR/PreviewHubComposer.cs
  src/Umbraco.Web.Common/Runtime/AspNetCoreBootFailedComposer.cs
  src/Umbraco.Web.Common/Runtime/AspNetCoreComposer.cs
  src/Umbraco.Web.UI.NetCore/Program.cs
Labels: project/net-core

#9301 Remove double editorService.close()
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/membergrouppicker/membergrouppicker.controller.js
Labels: hacktoberfest-accepted

#9242 Remove CSS: bottom offset in umb-grid.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-grid.less
Labels: hacktoberfest-accepted

#9024 Make Nested Content icons centered and same size as Block Editor
  src/Umbraco.Web.UI.Client/src/less/components/umb-nested-content.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.propertyeditor.html
Labels: hacktoberfest-accepted

#9325 Accessibility (keyboard navigation): The 'Content' drop down menu opens automatically when tabbing
  src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditornavigationitem.directive.js
  src/Umbraco.Web.UI.Client/src/less/components/umb-editor-navigation-item.less
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-navigation-item.html
Labels: hacktoberfest-accepted

#9411 Added netcore-only solution file
  src/umbraco-netcore-only.sln
Labels: project/net-core

#9105 Add confirmation dialog to media picker "remove all entries" action
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.controller.js
Labels: hacktoberfest-accepted

#9025 umb-tree-search-results directive view fixes
  src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less
  src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree-search-results.html
Labels: hacktoberfest-accepted

#9021 8838: Node Actions menu should be disabled on listview
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbvariantcontent.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorcontentheader.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditormenu.directive.js
  src/Umbraco.Web.UI.Client/src/common/services/listviewhelper.service.js
  src/Umbraco.Web.UI.Client/src/views/components/content/umb-variant-content.html
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-content-header.html
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-menu.html
Labels: hacktoberfest-accepted

#9045 ContextDialog: Accessibility improvements
  src/Umbraco.Web.UI.Client/src/views/components/tree/umbcontextdialog/umb-context-dialog.html
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: hacktoberfest-accepted

#9047 Issue 8353 - Fix of issue that caused small screens labels alignment
  src/Umbraco.Web.UI.Client/src/less/forms.less
  src/Umbraco.Web.UI.Client/src/less/installer.less
Labels: hacktoberfest-accepted

#9090 Help drawer adjustments
  src/Umbraco.Web.UI.Client/src/views/common/drawers/help/help.html
Labels: hacktoberfest-accepted

#9230 Update umb-button directive parameter usage to reflect accurate imple…
  src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbbutton.directive.js
Labels: hacktoberfest-accepted

#9053 Grid: Layoutconfig improvements
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/layoutconfig.html
Labels: hacktoberfest-accepted

#9421 Netcore: Migration of Property Editor classes from Umbraco.Infrastructure to Core
  src/Umbraco.Core/PropertyEditors/ConfigurationEditor.cs
  src/Umbraco.Core/PropertyEditors/DataValueReferenceFactoryCollection.cs
  src/Umbraco.Core/PropertyEditors/DataValueReferenceFactoryCollectionBuilder.cs
  src/Umbraco.Core/PropertyEditors/DecimalConfigurationEditor.cs
  src/Umbraco.Core/PropertyEditors/IDataValueReference.cs
  src/Umbraco.Core/PropertyEditors/IDataValueReferenceFactory.cs
  src/Umbraco.Core/PropertyEditors/IntegerConfigurationEditor.cs
  src/Umbraco.Core/PropertyEditors/ListViewConfiguration.cs
  src/Umbraco.Core/PropertyEditors/MemberPickerConfiguration.cs
  src/Umbraco.Core/PropertyEditors/MissingPropertyEditor.cs
  src/Umbraco.Core/PropertyEditors/MultiNodePickerConfiguration.cs
  src/Umbraco.Core/PropertyEditors/MultiNodePickerConfigurationTreeSource.cs
  src/Umbraco.Core/PropertyEditors/NestedContentConfiguration.cs
  src/Umbraco.Core/PropertyEditors/UserPickerConfiguration.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/ContentPickerValueConverter.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/LabelValueConverter.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/MediaPickerValueConverter.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/MultiNodeTreePickerValueConverter.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/TinyMceValueConverter.cs
  src/Umbraco.Infrastructure/PropertyEditors/MultiNodePickerConfigurationTreeSource.cs
  src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
  src/Umbraco.Web.BackOffice/Controllers/MacroRenderingController.cs
Labels: project/net-core

#9398 Speed up publish content query and reduce memory use by reducing array allocations for PublishedContent properties
  src/Umbraco.Web/PublishedCache/NuCache/PublishedContent.cs
Labels: category/performance, release/8.10.0, type/feature

#9340 Track ng-repeat with id instead of label
  src/Umbraco.Web.UI.Client/src/views/components/content/umb-tabbed-content.html
  src/Umbraco.Web.UI.Client/src/views/components/elementeditor/umb-element-editor-content.component.html
  src/Umbraco.Web.UI.Client/src/views/components/member/umb-member-node-info.html
  src/Umbraco.Web.UI.Client/src/views/media/apps/content/content.html
  src/Umbraco.Web.UI.Client/src/views/member/apps/content/content.html
Labels: release/8.7.2

#9030 Replace obsolete usages with injected services in UmbracoHelper
  src/Umbraco.Web/UmbracoHelper.cs
Labels: category/refactor, community/pr, hacktoberfest-accepted, hacktoberfest/contrib-2020, release/8.10.0, type/bug

#9275 Make index, settings and layout props available for labels
  src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbblocklistblock.component.js
Labels: hacktoberfest-accepted, state/sprint-candidate

#9322 V8/feature/ab9079 use tree for element type pickers
  src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/treepicker/treepicker.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.controller.js
  src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: category/ux, hacktoberfest-accepted

#9279 When creating a new dictionary item clears out the page title
  src/Umbraco.Web.UI.Client/src/views/dictionary/dictionary.create.controller.js
Labels: category/accessibility, hacktoberfest-accepted

#9103 Hide property actions for culture invariant properties
  src/Umbraco.Web.UI.Client/src/views/components/property/umb-property.html
Labels: hacktoberfest-accepted

#9052 Grid prevalues: Improve accessibility and semantics
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.prevalues.html
Labels: hacktoberfest-accepted

#9072 Use umb-icon in umb-node-preview
  src/Umbraco.Web.UI.Client/src/less/components/umb-node-preview.less
  src/Umbraco.Web.UI.Client/src/views/components/umb-node-preview.html
Labels: hacktoberfest-accepted

#9050 Listview: Fix icon-picker a11y
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/icon.prevalues.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/icon.prevalues.html
Labels: hacktoberfest-accepted

#9392 Remove Security from UmbracoContext
  src/Umbraco.Core/ContentApps/ContentAppFactoryCollection.cs
  src/Umbraco.Core/ContentApps/ContentAppFactoryCollectionBuilder.cs
  src/Umbraco.Core/IUmbracoContext.cs
  src/Umbraco.Examine.Lucene/BackOfficeExamineSearcher.cs
  src/Umbraco.Infrastructure/Compose/NotificationsComponent.cs
  src/Umbraco.Infrastructure/PropertyEditors/GridPropertyEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs
  src/Umbraco.Tests/PublishedContent/PublishedContentTestBase.cs
  src/Umbraco.Tests/PublishedContent/PublishedContentTests.cs
  src/Umbraco.Tests/Testing/TestingTests/MockTests.cs
  src/Umbraco.Tests/Testing/UmbracoTestBase.cs
  src/Umbraco.Web.BackOffice/Controllers/CodeFileController.cs
  src/Umbraco.Web.BackOffice/Controllers/DashboardController.cs
  src/Umbraco.Web.BackOffice/Controllers/DataTypeController.cs
  src/Umbraco.Web.BackOffice/Mapping/ContentMapDefinition.cs
  src/Umbraco.Web.Common/Controllers/IRenderController.cs
  src/Umbraco.Web.Common/Extensions/GridTemplateExtensions.cs
  src/Umbraco.Web.Common/Filters/UmbracoBackOfficeAuthorizeFilter.cs
  src/Umbraco.Web.Common/Install/InstallAuthorizeAttribute.cs
  src/Umbraco.Web.Common/Macros/MacroRenderer.cs
  src/Umbraco.Web.Common/UmbracoContext/UmbracoContext.cs
  src/Umbraco.Web/Composing/Current.cs
  src/Umbraco.Web/Mvc/UmbracoAuthorizeAttribute.cs
  src/Umbraco.Web/Umbraco.Web.csproj
  src/Umbraco.Web/UmbracoHttpHandler.cs
  src/Umbraco.Web/UmbracoWebService.cs
  src/Umbraco.Web/WebApi/UmbracoApiController.cs
  src/Umbraco.Web/WebApi/UmbracoApiControllerBase.cs
  src/Umbraco.Web/WebApi/UmbracoAuthorizeAttribute.cs
  src/Umbraco.Web/WebApi/UmbracoAuthorizedApiController.cs
Labels: project/net-core

#9451 Netcore: Misc resolve naming issues
  src/Umbraco.Web/Umbraco.Web.csproj
  src/Umbraco.Web/UmbracoBuilderExtensions.cs
Labels: project/net-core

#9452 Netcore: Fix unit tests, so they pass on linux too
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/TempFileCleanupTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Logging/LogviewerTests.cs
Labels: project/net-core

#9304 Bugfix: Add null check for null converted treenode icon so .startsWith does not throw
  src/Umbraco.Web.UI.Client/src/common/services/tree.service.js
Labels: hacktoberfest-accepted

#9448 NetCore: Migrated member related partial views
  src/Umbraco.Core/Models/Security/LoginStatusModel.cs
  src/Umbraco.Core/Security/IUmbracoWebsiteSecurity.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.Website/Security/UmbracoWebsiteSecurityTests.cs
  src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
  src/Umbraco.Web.UI.NetCore/umbraco/PartialViewMacros/Templates/EditProfile.cshtml
  src/Umbraco.Web.UI.NetCore/umbraco/PartialViewMacros/Templates/Login.cshtml
  src/Umbraco.Web.UI.NetCore/umbraco/PartialViewMacros/Templates/LoginStatus.cshtml
  src/Umbraco.Web.UI.NetCore/umbraco/PartialViewMacros/Templates/RegisterMember.cshtml
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  src/Umbraco.Web.Website/Extensions/HtmlHelperRenderExtensions.cs
  src/Umbraco.Web.Website/Extensions/TypeLoaderExtensions.cs
  src/Umbraco.Web.Website/Security/UmbracoWebsiteSecurity.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: project/net-core

#7444 added round corners in umb-media-grid for media-picker
  src/Umbraco.Web.UI.Client/src/less/components/umb-media-grid.less
Labels: category/ui, community/review

#7560 keep umb-editor inside viewport width
  src/Umbraco.Web.UI.Client/src/less/components/editor/umb-editor.less
Labels: community/review

#9425 Introduce content app helper
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbvariantcontent.directive.js
  src/Umbraco.Web.UI.Client/src/common/services/contentapphelper.service.js
Labels: category/refactor, community/pr, release/8.10.0, type/feature

#9205 Add Swedish translation for the member section.
  src/Umbraco.Web.UI/Umbraco/config/lang/sv.xml
Labels: hacktoberfest-accepted

#9414 Linux paths
  src/Umbraco.Core/Configuration/XmlConfigManipulator.cs
  src/Umbraco.Core/HealthCheck/Checks/Permissions/FolderAndFilePermissionsCheck.cs
  src/Umbraco.Core/IO/FileSystems.cs
  src/Umbraco.Core/IO/IIOHelper.cs
  src/Umbraco.Core/IO/IOHelper.cs
  src/Umbraco.Core/IO/IOHelperLinux.cs
  src/Umbraco.Core/IO/IOHelperOSX.cs
  src/Umbraco.Core/IO/IOHelperWindows.cs
  src/Umbraco.Core/IO/PhysicalFileSystem.cs
  src/Umbraco.Core/IO/ShadowWrapper.cs
  src/Umbraco.Core/Install/InstallStatusTracker.cs
  src/Umbraco.Core/Install/InstallSteps/StarterKitCleanupStep.cs
  src/Umbraco.Core/Packaging/PackageFileInstallation.cs
  src/Umbraco.Core/Persistence/Repositories/UpgradeCheckRepository.cs
  src/Umbraco.Core/Xml/XmlHelper.cs
  src/Umbraco.Infrastructure/Compose/ManifestWatcherComponent.cs
  src/Umbraco.Infrastructure/Install/FilePermissionHelper.cs
  src/Umbraco.Infrastructure/Manifest/ManifestParser.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/StylesheetRepository.cs
  src/Umbraco.Infrastructure/PropertyEditors/RichTextEditorPastedImages.cs
  src/Umbraco.Infrastructure/Runtime/CoreInitialComponent.cs
  src/Umbraco.Infrastructure/Services/Implement/PackagingService.cs
  src/Umbraco.ModelsBuilder.Embedded/PureLiveModelFactory.cs
  src/Umbraco.Tests.Common/TestHelperBase.cs
  src/Umbraco.Tests.Common/TestHelpers/TestEnvironment.cs
  src/Umbraco.Tests.Integration/Umbraco.Core/IO/FileSystemsTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/PartialViewRepositoryTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/ScriptRepositoryTest.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/StylesheetRepositoryTest.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/TemplateRepositoryTest.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Manifest/ManifestParserTests.cs
  src/Umbraco.Tests/IO/ShadowFileSystemTests.cs
  src/Umbraco.Tests/Packaging/PackageInstallationTest.cs
  src/Umbraco.Tests/PublishedContent/PublishedContentTestBase.cs
  src/Umbraco.Tests/PublishedContent/PublishedContentTests.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeAssetsController.cs
  src/Umbraco.Web.BackOffice/Controllers/CodeFileController.cs
  src/Umbraco.Web.BackOffice/Controllers/ContentTypeController.cs
  src/Umbraco.Web.BackOffice/Runtime/BackOfficeComposer.cs
  src/Umbraco.Web.Common/AspNetCore/AspNetCoreHostingEnvironment.cs
  src/Umbraco.Web.Common/Builder/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Extensions/UmbracoCoreServiceCollectionExtensions.cs
  src/Umbraco.Web.Common/Macros/MacroRenderer.cs
  src/Umbraco.Web.Common/Macros/PartialViewMacroEngine.cs
  src/Umbraco.Web/AspNet/AspNetHostingEnvironment.cs
  src/Umbraco.Web/UmbracoApplicationBase.cs
  src/Umbraco.Web/WebApi/HttpActionContextExtensions.cs
  src/Umbraco.Web/WebAssets/CDF/ClientDependencyConfiguration.cs
  src/Umbraco.Web/WebAssets/CDF/ClientDependencyRuntimeMinifier.cs
Labels: project/net-core

#9469 Review Remove this form-horizontal class from member groups info
  src/Umbraco.Web.UI.Client/src/views/membergroups/edit.html
Labels: state/sprint-candidate

#8849 Feature: Property label on top
  src/Umbraco.Core/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Core/Migrations/Upgrade/V_8_10_0/AddPropertyTypeLabelOnTopColumn.cs
  src/Umbraco.Core/Models/PropertyType.cs
  src/Umbraco.Core/Packaging/PackageDataInstallation.cs
  src/Umbraco.Core/Persistence/Dtos/PropertyTypeDto.cs
  src/Umbraco.Core/Persistence/Dtos/PropertyTypeReadOnlyDto.cs
  src/Umbraco.Core/Persistence/Factories/PropertyGroupFactory.cs
  src/Umbraco.Core/Persistence/Mappers/PropertyTypeMapper.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeCommonRepository.cs
  src/Umbraco.Core/PropertyEditors/DataValueEditor.cs
  src/Umbraco.Core/Services/Implement/EntityXmlSerializer.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests/Models/Mapping/ContentTypeModelMappingTests.cs
  src/Umbraco.Tests/Persistence/Repositories/ContentTypeRepositoryTest.cs
  src/Umbraco.Tests/TestHelpers/Entities/MockedContentTypes.cs
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js
  src/Umbraco.Web.UI.Client/src/common/services/umbdataformatter.service.js
  src/Umbraco.Web.UI.Client/src/less/main.less
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/propertysettings/propertysettings.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/propertysettings/propertysettings.html
  src/Umbraco.Web.UI.Client/src/views/components/property/umb-property.html
  src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
  src/Umbraco.Web/Models/ContentEditing/ContentPropertyDisplay.cs
  src/Umbraco.Web/Models/ContentEditing/ContentPropertyDto.cs
  src/Umbraco.Web/Models/ContentEditing/PropertyTypeBasic.cs
  src/Umbraco.Web/Models/Mapping/ContentPropertyDisplayMapper.cs
  src/Umbraco.Web/Models/Mapping/ContentPropertyDtoMapper.cs
  src/Umbraco.Web/Models/Mapping/ContentPropertyMapDefinition.cs
  src/Umbraco.Web/Models/Mapping/ContentTypeMapDefinition.cs
  src/Umbraco.Web/Models/Mapping/PropertyTypeGroupMapper.cs
  src/Umbraco.Web/PropertyEditors/BlockEditorPropertyEditor.cs
Labels: category/ui, state/sprint-candidate
