Repository umbraco/Umbraco-CMS, pull requests merged in 2020-09, with the labels that each got.

#8779 Macropicker: Fix semantics
  src/Umbraco.Web.UI.Client/src/less/forms.less
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macropicker/macropicker.html
Labels: category/accessibility, community/pr, release/8.8.0, type/feature

#8732 V8.7RC Prevent usage of NestedContent in BlockEditors
  src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
Labels: state/sprint-candidate

#8807 AC7976 dont place runtime vars in model
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/textarea/textarea.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/textarea/textarea.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/textbox/textbox.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/textbox/textbox.html
  src/Umbraco.Web/PropertyEditors/TextboxConfiguration.cs
Labels: release/8.7.0

#8736 V8.7RC: Recreate UDIs for pasted Block Editor entries
  src/Umbraco.Web.UI.Client/src/common/services/blockeditor.service.js
  src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
  src/Umbraco.Web.UI.Client/src/common/services/clipboard.service.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
Labels: category/front-end, state/sprint-candidate

#8701 V8.7RC: Block List property editor api methods available on blockObject
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbblocklistblock.component.js
Labels: category/dx, state/sprint-candidate

#8744 V8.7RC: Moved validation indication one element up.
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-row.html
Labels: state/sprint-candidate

#8809 V8.7RC: Clipboard resolvers should target specific entry types
  src/Umbraco.Web.UI.Client/src/common/services/blockeditor.service.js
  src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
  src/Umbraco.Web.UI.Client/src/common/services/clipboard.service.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
Labels: state/sprint-candidate

#8841 8.7RC Add generic BlockListItem classes
  src/Umbraco.Core/Models/Blocks/BlockListItem.cs
  src/Umbraco.Core/Models/Blocks/BlockListModel.cs
  src/Umbraco.Core/Models/Blocks/ContentAndSettingsReference.cs
  src/Umbraco.Core/Models/Blocks/IBlockReference.cs
  src/Umbraco.Web/PropertyEditors/ValueConverters/BlockListPropertyValueConverter.cs
Labels: category/api, community/pr, release/8.7.0, status/needs-docs, type/feature

#8847 NetCore: Fix for mapping route param
  src/Umbraco.Web.BackOffice/Trees/ContentTreeControllerBase.cs
Labels: project/net-core, release/netcore-alpha002

#8852 NetCore: Fix for disabling/enabling url tracking
  src/Umbraco.Core/Configuration/IConfigManipulator.cs
  src/Umbraco.Core/Configuration/XmlConfigManipulator.cs
  src/Umbraco.Infrastructure/Configuration/JsonConfigManipulator.cs
  src/Umbraco.Infrastructure/Routing/RedirectTrackingComponent.cs
  src/Umbraco.Web.BackOffice/Controllers/RedirectUrlManagementController.cs
Labels: project/net-core

#8622 Acceptance tests for Content
  src/Umbraco.Tests.AcceptanceTest/cypress/integration/Content/content.ts
  src/Umbraco.Tests.AcceptanceTest/package.json
Labels: category/test-automation, release/8.8.0, type/feature

#8851 Netcore/feature/models builder embedded migration roslyn compiler
  build/NuSpecs/UmbracoCms.Web.nuspec
  src/Umbraco.Configuration/Models/ModelsBuilderConfig.cs
  src/Umbraco.Core/Composing/DefaultUmbracoAssemblyProvider.cs
  src/Umbraco.Core/Configuration/ModelsBuilderConfigExtensions.cs
  src/Umbraco.Core/IO/ViewHelper.cs
  src/Umbraco.Infrastructure/Models/PublishedContent/PublishedModelFactory.cs
  src/Umbraco.ModelsBuilder.Embedded/BackOffice/ContentTypeModelValidatorBase.cs
  src/Umbraco.ModelsBuilder.Embedded/BackOffice/ModelsBuilderDashboardController.cs
  src/Umbraco.ModelsBuilder.Embedded/Building/Builder.cs
  src/Umbraco.ModelsBuilder.Embedded/Building/ModelsGenerator.cs
  src/Umbraco.ModelsBuilder.Embedded/Building/TextBuilder.cs
  src/Umbraco.ModelsBuilder.Embedded/Building/TypeModelHasher.cs
  src/Umbraco.ModelsBuilder.Embedded/Compose/DisabledModelsBuilderComponent.cs
  src/Umbraco.ModelsBuilder.Embedded/Compose/ModelsBuilderComponent.cs
  src/Umbraco.ModelsBuilder.Embedded/Compose/ModelsBuilderComposer.cs
  src/Umbraco.ModelsBuilder.Embedded/Compose/ModelsBuilderInitializer.cs
  src/Umbraco.ModelsBuilder.Embedded/HashCombiner.cs
  src/Umbraco.ModelsBuilder.Embedded/ImplementPropertyTypeAttribute.cs
  src/Umbraco.ModelsBuilder.Embedded/LiveModelsProvider.cs
  src/Umbraco.ModelsBuilder.Embedded/LiveModelsProviderModule.cs
  src/Umbraco.ModelsBuilder.Embedded/ModelsBuilderDashboard.cs
  src/Umbraco.ModelsBuilder.Embedded/ModelsGenerationError.cs
  src/Umbraco.ModelsBuilder.Embedded/OutOfDateModelsStatus.cs
  src/Umbraco.ModelsBuilder.Embedded/Properties/AssemblyInfo.cs
  src/Umbraco.ModelsBuilder.Embedded/PublishedElementExtensions.cs
  src/Umbraco.ModelsBuilder.Embedded/PublishedModelUtility.cs
  src/Umbraco.ModelsBuilder.Embedded/PureLiveModelFactory.cs
  src/Umbraco.ModelsBuilder.Embedded/ReferencedAssemblies.cs
  src/Umbraco.ModelsBuilder.Embedded/RoslynCompiler.cs
  src/Umbraco.ModelsBuilder.Embedded/Umbraco.ModelsBuilder.Embedded.csproj
  src/Umbraco.ModelsBuilder.Embedded/UmbracoAssemblyLoadContext.cs
  src/Umbraco.Tests.Integration/Persistence/Repositories/TemplateRepositoryTest.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/ModelsBuilder/BuilderTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/ModelsBuilder/ConfigTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/ModelsBuilder/StringExtensions.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/ModelsBuilder/UmbracoApplicationTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
  src/Umbraco.Tests/Published/ConvertersTests.cs
  src/Umbraco.Tests/Published/PublishedSnapshotTestObjects.cs
  src/Umbraco.Tests/PublishedContent/PublishedContentSnapshotTestBase.cs
  src/Umbraco.Tests/PublishedContent/PublishedContentTests.cs
  src/Umbraco.Tests/PublishedContent/SolidPublishedSnapshot.cs
  src/Umbraco.Tests/Templates/ViewHelperTests.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
  src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
  src/Umbraco.Web.UI.NetCore/appsettings.json
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
Labels: project/net-core

#8703 Show tracked references on a content item
  src/Umbraco.Web.UI.Client/src/common/directives/components/media/umbmedianodeinfo.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/references/umbtrackedreferences.component.js
  src/Umbraco.Web.UI.Client/src/common/resources/media.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/trackedreferences.resource.js
  src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html
  src/Umbraco.Web.UI.Client/src/views/components/media/umb-media-node-info.html
  src/Umbraco.Web.UI.Client/src/views/components/references/umb-tracked-references.html
  src/Umbraco.Web/Editors/BackOfficeServerVariables.cs
  src/Umbraco.Web/Editors/MediaController.cs
  src/Umbraco.Web/Editors/TrackedReferencesController.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: category/item-tracking, community/up-for-grabs, type/feature

#7599 UI: corrected button style to match new style
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.html
Labels: category/ui, community/review, state/sprint-candidate

#8908 Change wrong URL in KeepAlive XML Comments
  src/Umbraco.Web.UI/config/umbracoSettings.config
Labels: release/8.7.1, release/no-notes, type/bug

#8815 Ensure event handlers are unsubscribed in Core Components
  src/Umbraco.Core/Compose/AuditEventsComponent.cs
  src/Umbraco.Core/Compose/RelateOnCopyComponent.cs
  src/Umbraco.Core/Compose/RelateOnTrashComponent.cs
  src/Umbraco.ModelsBuilder.Embedded/Compose/ModelsBuilderComponent.cs
  src/Umbraco.Web/Compose/BackOfficeUserAuditEventsComponent.cs
  src/Umbraco.Web/Compose/NotificationsComponent.cs
  src/Umbraco.Web/Compose/PublicAccessComponent.cs
  src/Umbraco.Web/Logging/WebProfilerComponent.cs
  src/Umbraco.Web/PropertyEditors/PropertyEditorsComponent.cs
  src/Umbraco.Web/Routing/RedirectTrackingComponent.cs
  src/Umbraco.Web/Search/ExamineComponent.cs
Labels: release/8.6.5, state/sprint-candidate, type/bug

#8772 Umbraco to re-index data on background thread and fix potential Scope issue
  src/Umbraco.Examine/ContentValueSetBuilder.cs
  src/Umbraco.Examine/UmbracoContentIndex.cs
  src/Umbraco.Web/Scheduling/SimpleTask.cs
  src/Umbraco.Web/Search/ExamineComponent.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: category/performance, release/8.6.5, release/8.7.1, state/sprint-candidate, type/bug

#8866 Netcore: Handle tree authentication
  src/Umbraco.Infrastructure/Scheduling/ScheduledPublishing.cs
  src/Umbraco.Infrastructure/Scheduling/SchedulerComponent.cs
  src/Umbraco.Web.BackOffice/Controllers/SectionController.cs
  src/Umbraco.Web.BackOffice/Extensions/ControllerContextExtensions.cs
  src/Umbraco.Web.BackOffice/Trees/ApplicationTreeController.cs
  src/Umbraco.Web.Common/UmbracoContext/UmbracoContext.cs
  src/Umbraco.Web/Umbraco.Web.csproj
  src/Umbraco.Web/WebApi/HttpControllerContextExtensions.cs
Labels: project/net-core

#8525 Fixes #8433 ensures there are no write locks when updating members during login
  src/Umbraco.Core/Persistence/Repositories/IMemberRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/MemberRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/SimpleGetRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/UserRepository.cs
  src/Umbraco.Core/Services/IMembershipMemberService.cs
  src/Umbraco.Core/Services/Implement/MemberService.cs
  src/Umbraco.Core/Services/Implement/UserService.cs
  src/Umbraco.Tests/Persistence/Repositories/UserRepositoryTest.cs
  src/Umbraco.Tests/Services/MemberServiceTests.cs
  src/Umbraco.Web/Cache/DistributedCacheExtensions.cs
  src/Umbraco.Web/Cache/MemberCacheRefresher.cs
  src/Umbraco.Web/Security/MembershipHelper.cs
  src/Umbraco.Web/Security/Providers/UmbracoMembershipProvider.cs
Labels: state/sprint-candidate

#8932 NetCore: Update NuGet packages to latest versions
  build/NuSpecs/UmbracoCms.Core.nuspec
  build/NuSpecs/UmbracoCms.Web.nuspec
  build/templates/UmbracoSolution/.template.config/template.json
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
  src/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
  src/Umbraco.Tests/Umbraco.Tests.csproj
  src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
  src/Umbraco.Web.Common/Extensions/UmbracoCoreServiceCollectionExtensions.cs
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
  src/Umbraco.Web.UI.NetCore/appsettings.json
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: project/net-core

#8913 Introduced interface on BackOfficeUserManager
  src/Umbraco.Infrastructure/BackOffice/BackOfficeUserManager.cs
  src/Umbraco.Infrastructure/BackOffice/IBackOfficeUserManager.cs
  src/Umbraco.Infrastructure/Install/InstallSteps/NewInstallStep.cs
  src/Umbraco.Tests.Integration/Umbraco.Web.BackOffice/UmbracoBackOfficeServiceCollectionExtensionsTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Controllers/UsersControllerUnitTests.cs
  src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
  src/Umbraco.Web.BackOffice/Controllers/CurrentUserController.cs
  src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
  src/Umbraco.Web.BackOffice/Extensions/BackOfficeServiceCollectionExtensions.cs
  src/Umbraco.Web.BackOffice/Extensions/IdentityBuilderExtensions.cs
  src/Umbraco.Web.BackOffice/Security/BackOfficeSessionIdValidator.cs
  src/Umbraco.Web.BackOffice/Security/PasswordChanger.cs
  src/Umbraco.Web.Common/Security/BackOfficeSignInManager.cs
  src/Umbraco.Web/Security/BackOfficeSignInManager.cs
Labels: project/net-core

#8928 Update noUiSlider to v14.6.2
  src/Umbraco.Web.UI.Client/package.json
Labels: release/8.8.0, release/no-notes

#8948 Netcore: configuration of supported image file types
  src/Umbraco.Core/Configuration/ContentSettingsExtensions.cs
  src/Umbraco.Core/Media/IImageUrlGenerator.cs
  src/Umbraco.Core/Media/ImageUrlGeneratorExtensions.cs
  src/Umbraco.Infrastructure/Media/ImageSharpImageUrlGenerator.cs
  src/Umbraco.Infrastructure/Media/UploadAutoFillProperties.cs
  src/Umbraco.Infrastructure/PropertyEditors/FileUploadPropertyEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/ImageCropperPropertyEditor.cs
  src/Umbraco.Infrastructure/Runtime/CoreInitialComposer.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/ImageCropperTest.cs
  src/Umbraco.Tests/Models/MediaXmlTest.cs
  src/Umbraco.Tests/Routing/MediaUrlProviderTests.cs
  src/Umbraco.Tests/Testing/UmbracoTestBase.cs
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeServerVariables.cs
  src/Umbraco.Web.BackOffice/Controllers/ImagesController.cs
  src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
  src/Umbraco.Web.BackOffice/Controllers/TinyMceController.cs
  src/Umbraco.Web/Editors/BackOfficeServerVariables.cs
Labels: project/net-core

#8925 Netcore: Use serilog to log all messages and use appsettings as config
  src/Umbraco.Core/Logging/ILoggingConfiguration.cs
  src/Umbraco.Core/Logging/LoggingConfiguration.cs
  src/Umbraco.Infrastructure/Composing/HostBuilderExtensions.cs
  src/Umbraco.Infrastructure/Logging/Serilog/LoggerConfigExtensions.cs
  src/Umbraco.Infrastructure/Logging/Serilog/SerilogLogger.cs
  src/Umbraco.Infrastructure/Logging/Viewer/LogViewerComposer.cs
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.Tests.Common/TestHelperBase.cs
  src/Umbraco.Tests.Integration/RuntimeTests.cs
  src/Umbraco.Tests.Integration/TestServerTest/UmbracoBuilderExtensions.cs
  src/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
  src/Umbraco.Web.Common/Builder/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Extensions/UmbracoCoreServiceCollectionExtensions.cs
  src/Umbraco.Web.UI.NetCore/Program.cs
  src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
  src/Umbraco.Web.UI.NetCore/Views/asda.cshtml
  src/Umbraco.Web.UI.NetCore/appsettings.Development.json
  src/Umbraco.Web.UI.NetCore/appsettings.json
  src/Umbraco.Web.UI.NetCore/config/serilog.Release.config
  src/Umbraco.Web.UI.NetCore/config/serilog.config
  src/Umbraco.Web.UI.NetCore/config/serilog.user.Release.config
  src/Umbraco.Web.UI.NetCore/config/serilog.user.config
  src/Umbraco.Web/UmbracoApplicationBase.cs
Labels: project/net-core

#8771 Fixed reset password for functionality
  src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
  src/Umbraco.Web.BackOffice/Extensions/HtmlHelperBackOfficeExtensions.cs
  src/Umbraco.Web.UI.NetCore/umbraco/UmbracoBackOffice/AuthorizeUpgrade.cshtml
  src/Umbraco.Web.UI.NetCore/umbraco/UmbracoBackOffice/Default.cshtml
Labels: project/net-core, release/netcore-alpha002

#8960 create enviroment configuration through install script
  src/Umbraco.Tests.AcceptanceTest/README.md
  src/Umbraco.Tests.AcceptanceTest/config.js
  src/Umbraco.Tests.AcceptanceTest/cypress/plugins/index.js
  src/Umbraco.Tests.AcceptanceTest/package.json
  src/Umbraco.Tests.AcceptanceTest/postinstall.js
Labels: category/dx

#8850 Review Feature: umb-property-info-button
  src/Umbraco.Web.UI.Client/src/less/belle.less
  src/Umbraco.Web.UI.Client/src/views/components/umb-property-info-button/umb-property-info-button.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-property-info-button/umb-property-info-button.less
  src/Umbraco.Web.UI.Client/src/views/components/umb-property-info-button/umbpropertyinfobutton.component.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.html
  src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: category/ui, state/sprint-candidate

#8941 8.8 Revert icon styling, to ensure backwards compatibility
  src/Umbraco.Web.UI.Client/src/common/services/iconhelper.service.js
  src/Umbraco.Web.UI.Client/src/less/components/umb-icon.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-iconpicker.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-media-grid.less
  src/Umbraco.Web.UI.Client/src/less/helveticons.less
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/iconpicker/iconpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/iconpicker/iconpicker.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-media-grid.html
Labels: state/sprint-candidate

#8975 adjust default size of umb-button-ellipsis and its apperance in umb-tree
  src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-button-ellipsis.less
  src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree-root.less
  src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less
Labels: state/sprint-candidate

#8981 Cleanup NC specific data before sending it to the clipboard
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
Labels: state/sprint-candidate

#8979 Review: Check for null since null is an object as well.
  src/Umbraco.Web.UI.Client/src/common/services/blockeditor.service.js
Labels: state/sprint-candidate

#8982 Review: Break text in item-picker cards
  src/Umbraco.Web.UI.Client/src/less/components/card.less
Labels: state/sprint-candidate

#8983 Review: Always show if limit are exceeded
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.html
Labels: category/ux, state/sprint-candidate

#8986 Review: Fixing blocklist labelblock css
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/labelblock/labelblock.editor.less
Labels: state/sprint-candidate

#8985 Review: Fix one pixel in dialog
  src/Umbraco.Web.UI.Client/src/less/components/umb-form-check.less
Labels: state/sprint-candidate

#8984 Review: Always show action buttons in delete dialogs & enable once checked
  src/Umbraco.Web.UI.Client/src/views/datatypes/delete.html
  src/Umbraco.Web.UI.Client/src/views/documenttypes/delete.html
  src/Umbraco.Web.UI.Client/src/views/mediatypes/delete.html
  src/Umbraco.Web.UI.Client/src/views/membertypes/delete.html
Labels: category/ux, state/sprint-candidate

#8980 Review: Check that scaffold exists
  src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
  src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.html
  src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.controller.js
  src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: state/sprint-candidate

#8818 Fix JS error preventing newly created dictionary items from opening automatically
  src/Umbraco.Web.UI.Client/src/views/dictionary/dictionary.create.controller.js
Labels: community/pr, release/8.7.1, type/bug

#8812 Add color picker component
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbcolorpicker.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbrangeslider.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbtable.directive.js
  src/Umbraco.Web.UI.Client/src/less/belle.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-color-picker.less
  src/Umbraco.Web.UI.Client/src/less/property-editors.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/colorpicker/colorpicker.prevalues.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/colorpicker/multicolorpicker.controller.js
Labels: category/api, community/pr, release/8.10.0, type/feature

#8883 Remove unused legacy mediatypepicker overlay
  src/Umbraco.Web.UI.Client/src/views/common/overlays/mediatypepicker/mediapicktypepicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/overlays/mediatypepicker/mediatypepicker.html
Labels: category/breaking, community/pr, release/8.10.0, type/feature
