Repository umbraco/Umbraco-CMS, pull requests merged in 2020-03, with the labels that each got.

#7722 NetCore: Moved install steps + dashboards
  src/Umbraco.Configuration/ConfigsFactory.cs
  src/Umbraco.Configuration/MachineKeyConfig.cs
  src/Umbraco.Core/Configuration/IMachineKeyConfig.cs
  src/Umbraco.Core/Dashboards/ContentDashboard.cs
  src/Umbraco.Core/Dashboards/ExamineDashboard.cs
  src/Umbraco.Core/Dashboards/FormsDashboard.cs
  src/Umbraco.Core/Dashboards/HealthCheckDashboard.cs
  src/Umbraco.Core/Dashboards/MediaDashboard.cs
  src/Umbraco.Core/Dashboards/MembersDashboard.cs
  src/Umbraco.Core/Dashboards/ProfilerDashboard.cs
  src/Umbraco.Core/Dashboards/PublishedStatusDashboard.cs
  src/Umbraco.Core/Dashboards/RedirectUrlDashboard.cs
  src/Umbraco.Core/Dashboards/SettingsDashboards.cs
  src/Umbraco.Core/Hosting/IHostingEnvironment.cs
  src/Umbraco.Core/Manifest/ManifestWatcher.cs
  src/Umbraco.Core/Net/IUmbracoApplicationLifetime.cs
  src/Umbraco.Core/Net/IUserAgentProvider.cs
  src/Umbraco.Core/Packaging/PackageDefinition.cs
  src/Umbraco.Core/UmbracoContextAccessorExtensions.cs
  src/Umbraco.Infrastructure/Compose/ManifestWatcherComponent.cs
  src/Umbraco.Infrastructure/Intall/InstallHelper.cs
  src/Umbraco.Infrastructure/Intall/InstallSteps/ConfigureMachineKey.cs
  src/Umbraco.Infrastructure/Intall/InstallSteps/SetUmbracoVersionStep.cs
  src/Umbraco.Infrastructure/Intall/InstallSteps/StarterKitDownloadStep.cs
  src/Umbraco.Infrastructure/Intall/InstallSteps/StarterKitInstallStep.cs
  src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs
  src/Umbraco.Infrastructure/Persistence/SqlSyntax/SqlServerSyntaxProvider.cs
  src/Umbraco.Infrastructure/Persistence/SqlSyntax/SqlSyntaxProviderBase.cs
  src/Umbraco.Persistance.SqlCe/SqlCeSyntaxProvider.cs
  src/Umbraco.Web/AspNet/AspNetHostingEnvironment.cs
  src/Umbraco.Web/AspNet/AspNetUmbracoApplicationLifetime.cs
  src/Umbraco.Web/AspNet/AspNetUserAgentProvider.cs
  src/Umbraco.Web/Composing/Current.cs
  src/Umbraco.Web/Editors/PackageInstallController.cs
  src/Umbraco.Web/HttpContextAccessorExtensions.cs
  src/Umbraco.Web/Macros/MacroRenderer.cs
  src/Umbraco.Web/Macros/PartialViewMacroEngine.cs
  src/Umbraco.Web/Mvc/ContentModelBinder.cs
  src/Umbraco.Web/Runtime/WebInitialComposer.cs
  src/Umbraco.Web/Umbraco.Web.csproj
  src/Umbraco.Web/UmbracoApplication.cs
  src/Umbraco.Web/UmbracoContextFactory.cs
  src/Umbraco.Web/UmbracoHelper.cs
Labels: project/net-core

#7742 V8: Show image thumbnails for media picker search results (regression)
  src/Umbraco.Core/Persistence/Repositories/Implement/EntityRepository.cs
Labels: community/pr, release/8.6.0, release/no-notes, status/regression

#7535 Adding more fine colors for UI
  src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-editor-navigation-item.less
  src/Umbraco.Web.UI.Client/src/less/sections.less
  src/Umbraco.Web.UI.Client/src/less/variables.less
Labels: category/ui, community/review

#7740 NetCore: Replaced nonodes.aspx with MVC controller and view, with configurable view location
  src/Umbraco.Configuration/GlobalSettings.cs
  src/Umbraco.Core/Configuration/IGlobalSettings.cs
  src/Umbraco.Core/Constants-AppSettings.cs
  src/Umbraco.Core/Constants-Web.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
  src/Umbraco.Tests/Web/Mvc/RenderNoContentControllerTests.cs
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  src/Umbraco.Web.UI/config/splashes/NoNodes.aspx.cs
  src/Umbraco.Web.UI/config/splashes/NoNodes.aspx.designer.cs
  src/Umbraco.Web.UI/config/splashes/NoNodes.cshtml
  src/Umbraco.Web.UI/config/splashes/noNodes.aspx
  src/Umbraco.Web/Models/NoNodesViewModel.cs
  src/Umbraco.Web/Mvc/RenderNoContentController.cs
  src/Umbraco.Web/Runtime/WebInitialComponent.cs
  src/Umbraco.Web/Umbraco.Web.csproj
  src/Umbraco.Web/UmbracoInjectedModule.cs
Labels: project/net-core

#7752 Obsoleting UmbracoHelper properties
  src/Umbraco.Web/Composing/Current.cs
  src/Umbraco.Web/Models/RegisterModel.cs
  src/Umbraco.Web/UmbracoHelper.cs
Labels: community/review, release/8.7.0

#7788 7434 do not use umb outline for select
  src/Umbraco.Web.UI.Client/src/less/forms.less
Labels: category/accessibility, category/front-end, category/ui

#7795 Fixes issue with deep cloning property values
  src/Umbraco.Core/Models/Property.cs
  src/Umbraco.Tests/Services/ContentServiceTests.cs
Labels: community/review

#7822 NetCore: Make WebRuntime netstandard compatible
  src/Umbraco.Core/Cache/DeepCloneAppCache.cs
  src/Umbraco.Core/Cache/DictionaryAppCache.cs
  src/Umbraco.Core/Cache/FastDictionaryAppCache.cs
  src/Umbraco.Core/Cache/FastDictionaryAppCacheBase.cs
  src/Umbraco.Core/Cache/HttpRequestAppCache.cs
  src/Umbraco.Core/Cache/IAppCache.cs
  src/Umbraco.Core/Cache/NoAppCache.cs
  src/Umbraco.Core/Cache/ObjectCacheAppCache.cs
  src/Umbraco.Infrastructure/Runtime/CoreRuntime.cs
  src/Umbraco.Infrastructure/Runtime/WebRuntime.cs
  src/Umbraco.Infrastructure/Scoping/Scope.cs
  src/Umbraco.PublishedCache.NuCache/PublishedSnapshotService.cs
  src/Umbraco.Tests/Cache/AppCacheTests.cs
  src/Umbraco.Tests/Cache/DeepCloneAppCacheTests.cs
  src/Umbraco.Tests/Cache/HttpRequestAppCacheTests.cs
  src/Umbraco.Tests/Cache/ObjectAppCacheTests.cs
  src/Umbraco.Tests/Macros/MacroTests.cs
  src/Umbraco.Tests/Models/ContentTests.cs
  src/Umbraco.Tests/Persistence/Repositories/DocumentRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/MediaRepositoryTest.cs
  src/Umbraco.Tests/Published/PropertyCacheLevelTests.cs
  src/Umbraco.Tests/PublishedContent/NuCacheChildrenTests.cs
  src/Umbraco.Tests/PublishedContent/NuCacheTests.cs
  src/Umbraco.Tests/Routing/RenderRouteHandlerTests.cs
  src/Umbraco.Tests/Scoping/ScopedNuCacheTests.cs
  src/Umbraco.Tests/Scoping/ScopedRepositoryTests.cs
  src/Umbraco.Tests/Services/ContentTypeServiceVariantsTests.cs
  src/Umbraco.Web/Umbraco.Web.csproj
  src/Umbraco.Web/UmbracoApplication.cs
  src/Umbraco.Web/UmbracoApplicationBase.cs
Labels: project/net-core

#7782 Added GetSegment() method to VariationContext and uses it when conten…
  src/Umbraco.Core/Models/PublishedContent/VariationContext.cs
  src/Umbraco.Core/Models/PublishedContent/VariationContextAccessorExtensions.cs
  src/Umbraco.Web/Models/PublishedContent/PublishedValueFallback.cs
  src/Umbraco.Web/PublishedCache/NuCache/Property.cs
Labels: release/8.7.0, type/feature

#7641 Grant access to Packages section for any user groups with access to the Developer section
  src/Umbraco.Core/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Core/Migrations/Upgrade/V_8_0_0/AddPackagesSectionAccess.cs
  src/Umbraco.Core/Umbraco.Core.csproj
Labels: category/content-migration

#7820 NetCore: Introduces a seperate UnitTest project
  src/Umbraco.Configuration/Models/ConnectionStrings.cs
  src/Umbraco.Tests.Common/Builders/BuilderBase.cs
  src/Umbraco.Tests.Common/Builders/ChildBuilderBase.cs
  src/Umbraco.Tests.Common/Builders/ConfigurationEditorBuilder.cs
  src/Umbraco.Tests.Common/Builders/DataEditorBuilder.cs
  src/Umbraco.Tests.Common/Builders/DataTypeBuilder.cs
  src/Umbraco.Tests.Common/Builders/DataValueEditorBuilder.cs
  src/Umbraco.Tests.Common/Builders/DictionaryItemBuilder.cs
  src/Umbraco.Tests.Common/Builders/DictionaryTranslationBuilder.cs
  src/Umbraco.Tests.Common/Builders/Extensions/BuilderExtensions.cs
  src/Umbraco.Tests.Common/Builders/GlobalSettingsBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithAliasBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithCreateDateBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithCultureInfoBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithDeleteDateBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithIdBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithKeyBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithNameBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithUpdateDateBuilder.cs
  src/Umbraco.Tests.Common/Builders/LanguageBuilder.cs
  src/Umbraco.Tests.Common/Builders/RelationTypeBuilder.cs
  src/Umbraco.Tests.Common/Builders/SmtpSettingsBuilder.cs
  src/Umbraco.Tests.Shared/Umbraco.Tests.Shared.csproj
  src/Umbraco.Tests.UnitTests/Umbraco.Configuration/Models/ConnectionStringsTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/DataTypeTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/DictionaryItemTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/LanguageTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/RelationTypeTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
  src/Umbraco.Tests/Models/DataTypeTests.cs
  src/Umbraco.Tests/Models/DictionaryItemTests.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
  src/Umbraco.Web.UI.Client/package-lock.json
  src/umbraco.sln
Labels: project/net-core

#7837 Netcore: Use API to get Image URLs in BackOffice instead of hardcoded querystrings
  src/Umbraco.Core/Media/IImageUrlGenerator.cs
  src/Umbraco.Infrastructure/Media/ImageProcessorImageUrlGenerator.cs
  src/Umbraco.Infrastructure/Models/Mapping/UserMapDefinition.cs
  src/Umbraco.Infrastructure/Models/UserExtensions.cs
  src/Umbraco.Infrastructure/PropertyEditors/GridPropertyEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/RichTextEditorPastedImages.cs
  src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/ImageCropperValue.cs
  src/Umbraco.Tests/Models/ImageProcessorImageUrlGeneratorTest.cs
  src/Umbraco.Tests/PropertyEditors/ImageCropperTest.cs
  src/Umbraco.Tests/PublishedContent/PublishedContentTestBase.cs
  src/Umbraco.Tests/PublishedContent/PublishedContentTests.cs
  src/Umbraco.Tests/Runtimes/StandaloneTests.cs
  src/Umbraco.Tests/Testing/UmbracoTestBase.cs
  src/Umbraco.Tests/Web/Controllers/UsersControllerTests.cs
  src/Umbraco.Web.UI.Client/src/common/services/mediahelper.service.js
  src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/fileupload/fileupload.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/media.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.controller.js
  src/Umbraco.Web/Editors/CurrentUserController.cs
  src/Umbraco.Web/Editors/ImageUrlGeneratorController.cs
  src/Umbraco.Web/Editors/ImagesController.cs
  src/Umbraco.Web/Editors/LogController.cs
  src/Umbraco.Web/Editors/UsersController.cs
  src/Umbraco.Web/ImageCropperTemplateCoreExtensions.cs
  src/Umbraco.Web/Runtime/WebInitialComposer.cs
  src/Umbraco.Web/UrlHelperRenderExtensions.cs
Labels: project/net-core

#7669 .NetCore: Remove direct database queries from services
  src/Umbraco.Core/Models/IKeyValue.cs
  src/Umbraco.Core/Models/KeyValue.cs
  src/Umbraco.Core/Persistence/Repositories/IKeyValueRepository.cs
  src/Umbraco.Core/Persistence/Repositories/IUserRepository.cs
  src/Umbraco.Core/Services/ServiceContext.cs
  src/Umbraco.Infrastructure/Composing/CompositionExtensions/Repositories.cs
  src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs
  src/Umbraco.Infrastructure/Persistence/Dtos/KeyValueDto.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/KeyValueRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/RepositoryBaseOfTIdTEntity.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/UserRepository.cs
  src/Umbraco.Infrastructure/Persistence/UmbracoDatabaseExtensions.cs
  src/Umbraco.Infrastructure/Runtime/CoreInitialComposer.cs
  src/Umbraco.Infrastructure/Runtime/SqlMainDomLock.cs
  src/Umbraco.Infrastructure/RuntimeState.cs
  src/Umbraco.Infrastructure/Services/Implement/KeyValueService.cs
  src/Umbraco.Infrastructure/Services/Implement/MemberService.cs
  src/Umbraco.Infrastructure/Services/Implement/PublicAccessService.cs
  src/Umbraco.Infrastructure/Services/Implement/ServerRegistrationService.cs
  src/Umbraco.Infrastructure/Services/Implement/UserService.cs
  src/Umbraco.Tests/Persistence/Repositories/KeyValueRepositoryTests.cs
  src/Umbraco.Tests/Services/KeyValueServiceTests.cs
  src/Umbraco.Tests/TestHelpers/TestObjects.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
Labels: project/net-core
