Repository umbraco/Umbraco-CMS, pull requests merged in 2020-04, with the labels that each got.

#7855 Netcore: Migrated member unit tests into new project/builder pattern
  src/Umbraco.Tests.Common/Builders/ChildBuilderBase.cs
  src/Umbraco.Tests.Common/Builders/ConfigurationEditorBuilder.cs
  src/Umbraco.Tests.Common/Builders/DataTypeBuilder.cs
  src/Umbraco.Tests.Common/Builders/DictionaryTranslationBuilder.cs
  src/Umbraco.Tests.Common/Builders/Extensions/BuilderExtensions.cs
  src/Umbraco.Tests.Common/Builders/Extensions/StringExtensions.cs
  src/Umbraco.Tests.Common/Builders/GenericCollectionBuilder.cs
  src/Umbraco.Tests.Common/Builders/GenericDictionaryBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithCreatorIdBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithDescriptionBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithIconBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithLevelBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithParentIdBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithPathBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithSortOrderBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithThumbnailBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithTrashedBuilder.cs
  src/Umbraco.Tests.Common/Builders/MemberBuilder.cs
  src/Umbraco.Tests.Common/Builders/MemberGroupBuilder.cs
  src/Umbraco.Tests.Common/Builders/MemberTypeBuilder.cs
  src/Umbraco.Tests.Common/Builders/PropertyGroupBuilder.cs
  src/Umbraco.Tests.Common/Builders/PropertyTypeBuilder.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/DataTypeTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/MemberGroupTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/MemberTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/Builders/DataTypeBuilderTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/Builders/MemberBuilderTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/Builders/MemberGroupBuilderTests.cs
  src/Umbraco.Tests/Models/MemberTests.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
Labels: project/net-core

#7872 NetCore: Aligned User and UserGroup builders to the other builders
  src/Umbraco.Configuration/Models/GlobalSettings.cs
  src/Umbraco.Core/Constants-Configuration.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithApprovedBuilder.cs
  src/Umbraco.Tests.Common/Builders/UserBuilder.cs
  src/Umbraco.Tests.Common/Builders/UserGroupBuilder.cs
  src/Umbraco.Tests.Integration/Extensions/ApplicationBuilderExtensions.cs
  src/Umbraco.Web.Common/Extensions/UmbracoCoreServiceCollectionExtensions.cs
  src/Umbraco.Web.UI/Umbraco/PartialViewMacros/Templates/Gallery.cshtml
  src/Umbraco.Web.UI/Views/Partials/Grid/Editors/Media.cshtml
Labels: project/net-core

#7895 Netcore: Further model unit test migrations into new project and builder pattern
  src/Umbraco.Core/Models/RelationType.cs
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.Tests.Common/Builders/Extensions/BuilderExtensions.cs
  src/Umbraco.Tests.Common/Builders/MemberTypeBuilder.cs
  src/Umbraco.Tests.Common/Builders/RelationBuilder.cs
  src/Umbraco.Tests.Common/Builders/RelationTypeBuilder.cs
  src/Umbraco.Tests.Common/Builders/StylesheetBuilder.cs
  src/Umbraco.Tests.Common/Builders/TemplateBuilder.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/RelationTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/RelationTypeTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/StylesheetTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/TemplateTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/Builders/RelationBuilderTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/Builders/RelationTypeBuilderTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/Builders/StylesheetBuilderTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/Builders/TemplateBuilderTests.cs
  src/Umbraco.Tests/Models/RelationTests.cs
  src/Umbraco.Tests/Models/TemplateTests.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
Labels: project/net-core

#7925 Moved from angular.IsNumber to Utilities.IsNumber
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbaceeditor.directive.js
  src/Umbraco.Web.UI.Client/src/common/resources/content.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/media.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/member.resource.js
  src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js
  src/Umbraco.Web.UI.Client/src/common/services/umbdataformatter.service.js
  src/Umbraco.Web.UI.Client/src/common/services/user.service.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.prevalues.controller.js
Labels: community/pr, release/8.7.0, type/feature

#7896 Netcore: Further model unit test migrations into new project and builder pattern (2)
  src/Umbraco.Tests.Common/Builders/Interfaces/IBuildPropertyGroups.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IBuildPropertyTypes.cs
  src/Umbraco.Tests.Common/Builders/MemberBuilder.cs
  src/Umbraco.Tests.Common/Builders/MemberTypeBuilder.cs
  src/Umbraco.Tests.Common/Builders/PropertyBuilder.cs
  src/Umbraco.Tests.Common/Builders/PropertyGroupBuilder.cs
  src/Umbraco.Tests.Common/Builders/PropertyTypeBuilder.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/PropertyGroupTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/PropertyTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/PropertyTypeTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/Builders/MemberBuilderTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/Builders/PropertyBuilderTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/Builders/PropertyGroupBuilderTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/Builders/PropertyTypeBuilderTests.cs
  src/Umbraco.Tests/Models/PropertyGroupTests.cs
  src/Umbraco.Tests/Models/PropertyTests.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
Labels: project/net-core

#7953 Remove unused "umb-password-toggle" directive
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbpasswordtoggle.directive.js
Labels: category/breaking, community/pr, release/8.7.0, type/feature

#7946 Append "active" to currently selected section for screen readers
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-sections.html
Labels: category/accessibility, community/pr, type/feature

#7910 Add migrations for new block editor
  src/Umbraco.Core/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Core/Migrations/Upgrade/V_8_7_0/ColorPickerPreValues.cs
  src/Umbraco.Core/Migrations/Upgrade/V_8_7_0/ConvertToElements.cs
  src/Umbraco.Core/Umbraco.Core.csproj
Labels: state/sprint-candidate

#7890 NetCore: Initialize more services for .net core
  src/Umbraco.Core/Actions/ActionCollectionBuilder.cs
  src/Umbraco.Core/CompositionExtensions.cs
  src/Umbraco.Core/CompositionExtensions_Uniques.cs
  src/Umbraco.Core/ContentApps/ContentEditorContentAppFactory.cs
  src/Umbraco.Core/ContentApps/ListViewContentAppFactory.cs
  src/Umbraco.Core/DefaultEventMessagesFactory.cs
  src/Umbraco.Core/HybridEventMessagesAccessor.cs
  src/Umbraco.Core/Services/SectionService.cs
  src/Umbraco.Core/Services/TreeService.cs
  src/Umbraco.Core/Web/ISessionManager.cs
  src/Umbraco.Infrastructure/CompositionExtensions.cs
  src/Umbraco.Infrastructure/Runtime/CoreInitialComposer.cs
  src/Umbraco.Tests/Web/Mvc/RenderNoContentControllerTests.cs
  src/Umbraco.Web.Common/AspNetCore/AspNetCoreCookieManager.cs
  src/Umbraco.Web.Common/AspNetCore/AspNetCoreSessionIdResolver.cs
  src/Umbraco.Web.Common/AspNetCore/AspNetCoreSessionManager.cs
  src/Umbraco.Web.Common/Extensions/UmbracoCoreServiceCollectionExtensions.cs
  src/Umbraco.Web.Common/Runtime/AspNetCoreComposer.cs
  src/Umbraco.Web/AspNet/AspNetSessionManager.cs
  src/Umbraco.Web/Composing/CompositionExtensions/WebMappingProfiles.cs
  src/Umbraco.Web/CompositionExtensions.cs
  src/Umbraco.Web/Macros/MacroRenderer.cs
  src/Umbraco.Web/Mvc/RenderNoContentController.cs
  src/Umbraco.Web/Runtime/WebInitialComposer.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: project/net-core

#7961 Nucache NullReferenceException when copying
  src/Umbraco.Tests/PublishedContent/NuCacheChildrenTests.cs
  src/Umbraco.Web/PublishedCache/NuCache/ContentStore.cs
Labels: community/review, release/8.6.1, type/bug

#7948 Netcore: Further model unit test migrations into new project and builder pattern
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.Tests.Common/Builders/ConfigurationEditorBuilder.cs
  src/Umbraco.Tests.Common/Builders/DataEditorBuilder.cs
  src/Umbraco.Tests.Common/Builders/DataTypeBuilder.cs
  src/Umbraco.Tests.Common/Builders/DataValueEditorBuilder.cs
  src/Umbraco.Tests.Common/Builders/DictionaryTranslationBuilder.cs
  src/Umbraco.Tests.Common/Builders/EntitySlimBuilder.cs
  src/Umbraco.Tests.Common/Builders/Extensions/BuilderExtensions.cs
  src/Umbraco.Tests.Common/Builders/GenericCollectionBuilder.cs
  src/Umbraco.Tests.Common/Builders/GenericDictionaryBuilder.cs
  src/Umbraco.Tests.Common/Builders/GlobalSettingsBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IAccountBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithApprovedBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithEmailBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithFailedPasswordAttemptsBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithIsApprovedBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithIsLockedOutBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithLastLoginDateBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithLastPasswordChangeDateBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithLoginBuilder.cs
  src/Umbraco.Tests.Common/Builders/LanguageBuilder.cs
  src/Umbraco.Tests.Common/Builders/MacroBuilder.cs
  src/Umbraco.Tests.Common/Builders/MacroPropertyBuilder.cs
  src/Umbraco.Tests.Common/Builders/MemberBuilder.cs
  src/Umbraco.Tests.Common/Builders/PropertyTypeBuilder.cs
  src/Umbraco.Tests.Common/Builders/RelationTypeBuilder.cs
  src/Umbraco.Tests.Common/Builders/SmtpSettingsBuilder.cs
  src/Umbraco.Tests.Common/Builders/TemplateBuilder.cs
  src/Umbraco.Tests.Common/Builders/UserBuilder.cs
  src/Umbraco.Tests.Common/Builders/UserGroupBuilder.cs
  src/Umbraco.Tests.Integration/Persistence/Repositories/UserRepositoryTest.cs
  src/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/DataTypeTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/DictionaryItemTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/LanguageTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/MacroTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/MemberGroupTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/MemberTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/PathValidationTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/PropertyGroupTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/PropertyTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/PropertyTypeTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/RelationTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/RelationTypeTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/StylesheetTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/TemplateTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/UserExtensionsTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Models/UserTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/Builders/MacroBuilderTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/Builders/MemberBuilderTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/Builders/UserBuilderTests.cs
  src/Umbraco.Tests/Models/UserTests.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
Labels: project/net-core

#7907 Fix moving large amounts of content/media
  src/Umbraco.Core/Constants-SqlTemplates.cs
  src/Umbraco.Core/ContentExtensions.cs
  src/Umbraco.Core/Models/ContentDataIntegrityReport.cs
  src/Umbraco.Core/Models/ContentDataIntegrityReportEntry.cs
  src/Umbraco.Core/Models/ContentDataIntegrityReportOptions.cs
  src/Umbraco.Core/Persistence/Repositories/IContentRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/ContentRepositoryBase.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/DocumentRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/MediaRepository.cs
  src/Umbraco.Core/Services/IContentService.cs
  src/Umbraco.Core/Services/IContentServiceBase.cs
  src/Umbraco.Core/Services/Implement/ContentService.cs
  src/Umbraco.Core/Services/Implement/MediaService.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Web/HealthCheck/Checks/Data/DatabaseIntegrityCheck.cs
  src/Umbraco.Web/PublishedCache/NuCache/ContentStore.cs
  src/Umbraco.Web/PublishedCache/NuCache/Snap/LinkedNode.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: category/performance, release/8.7.0, type/bug, type/feature

#7970 In Nucache when we are loading in all data that we page over the data as to not cause an SQL timeout
  src/Umbraco.Core/Persistence/NPocoDatabaseExtensions.cs
  src/Umbraco.Web/PublishedCache/NuCache/DataSource/DatabaseDataSource.cs
  src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs
Labels: release/8.7.0, type/bug

#7963 Netcore: Migrate UmbracoSettings tests from UnitTests to Integration Tests
  src/Umbraco.Tests.Common/TestHelperBase.cs
  src/Umbraco.Tests.Integration/Extensions/ApplicationBuilderExtensions.cs
  src/Umbraco.Tests.Integration/Extensions/ServiceCollectionExtensions.cs
  src/Umbraco.Tests.Integration/Implementations/TestHelper.cs
  src/Umbraco.Tests.Integration/Implementations/TestHostingEnvironment.cs
  src/Umbraco.Tests.Integration/Testing/LocalDbTestDatabase.cs
  src/Umbraco.Tests.Integration/Umbraco.Configuration/Configurations/umbracoSettings.config
  src/Umbraco.Tests.Integration/Umbraco.Configuration/Configurations/umbracoSettings.minimal.config
  src/Umbraco.Tests.Integration/Umbraco.Configuration/Configurations/web.config
  src/Umbraco.Tests.Integration/Umbraco.Configuration/UmbracoSettings/ContentElementDefaultTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Configuration/UmbracoSettings/ContentElementTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Configuration/UmbracoSettings/LoggingElementDefaultTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Configuration/UmbracoSettings/LoggingElementTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Configuration/UmbracoSettings/RequestHandlerElementDefaultTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Configuration/UmbracoSettings/RequestHandlerElementTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Configuration/UmbracoSettings/SecurityElementDefaultTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Configuration/UmbracoSettings/SecurityElementTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Configuration/UmbracoSettings/UmbracoSettingsTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Configuration/UmbracoSettings/WebRoutingElementDefaultTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Configuration/UmbracoSettings/WebRoutingElementTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  src/Umbraco.Tests/Configurations/UmbracoSettings/ContentElementDefaultTests.cs
  src/Umbraco.Tests/Configurations/UmbracoSettings/RequestHandlerElementDefaultTests.cs
  src/Umbraco.Tests/Configurations/UmbracoSettings/SecurityElementDefaultTests.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
Labels: project/net-core

#7983 ModelsBuilder enabled flag not respected
  src/Umbraco.Core/Models/PublishedContent/ILivePublishedModelFactory.cs
  src/Umbraco.Core/PublishedModelFactoryExtensions.cs
  src/Umbraco.ModelsBuilder.Embedded/PureLiveModelFactory.cs
  src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs
  src/Umbraco.Web/PublishedCache/PublishedSnapshotServiceBase.cs
Labels: category/performance, release/8.7.0, type/bug

#7998 Add GetMainDom method to UmbracoApplication
  src/Umbraco.Web/UmbracoApplication.cs
Labels: state/sprint-candidate
