Repository umbraco/Umbraco-CMS, pull requests merged in 2021-07, with the labels that each got.

#10560 V9: Route plugin controllers by area
  src/Umbraco.Tests.Integration/Umbraco.Web.Website/Routing/FrontEndRouteTests.cs
  src/Umbraco.Web.Common/Extensions/EndpointRouteBuilderExtensions.cs
  src/Umbraco.Web.Website/Routing/FrontEndRoutes.cs
Labels: category/breaking, project/v9, release/9.0.0-beta005, type/bug

#10396 Add missing UrlHelper GetCropUrl methods
  src/Umbraco.Web.Common/Extensions/UrlHelperExtensions.cs
Labels: project/v9

#10534 Streamlines response handling in controllers
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Extensions/ModelStateExtensionsTests.cs
  src/Umbraco.Web.BackOffice/ActionResults/UmbracoNotificationSuccessResponse.cs
  src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeNotificationsController.cs
  src/Umbraco.Web.BackOffice/Controllers/CodeFileController.cs
  src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
  src/Umbraco.Web.BackOffice/Controllers/ContentTypeController.cs
  src/Umbraco.Web.BackOffice/Controllers/ContentTypeControllerBase.cs
  src/Umbraco.Web.BackOffice/Controllers/CurrentUserController.cs
  src/Umbraco.Web.BackOffice/Controllers/DataTypeController.cs
  src/Umbraco.Web.BackOffice/Controllers/DictionaryController.cs
  src/Umbraco.Web.BackOffice/Controllers/LanguageController.cs
  src/Umbraco.Web.BackOffice/Controllers/LogViewerController.cs
  src/Umbraco.Web.BackOffice/Controllers/MacrosController.cs
  src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
  src/Umbraco.Web.BackOffice/Controllers/MediaTypeController.cs
  src/Umbraco.Web.BackOffice/Controllers/MemberController.cs
  src/Umbraco.Web.BackOffice/Controllers/PackageController.cs
  src/Umbraco.Web.BackOffice/Controllers/PackageInstallController.cs
  src/Umbraco.Web.BackOffice/Controllers/RelationTypeController.cs
  src/Umbraco.Web.BackOffice/Controllers/UmbracoAuthorizedApiController.cs
  src/Umbraco.Web.BackOffice/Controllers/UserGroupsController.cs
  src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
  src/Umbraco.Web.BackOffice/Extensions/ModelStateExtensions.cs
  src/Umbraco.Web.Common/ActionsResults/UmbracoProblemResult.cs
  src/Umbraco.Web.Common/ActionsResults/ValidationErrorResult.cs
  src/Umbraco.Web.Common/Extensions/ModelStateExtensions.cs
Labels: project/v9

#10547 V9: Show cultures in dropdown with english names
  src/Umbraco.Web.BackOffice/Controllers/LanguageController.cs
Labels: project/v9

#10594 V9: Add RazorCompileOnPublish property to UmbracoProject for template
  build/templates/UmbracoProject/UmbracoProject.csproj
Labels: project/v9

#10575 V9: Add UmbracoAuthorizedController
  src/Umbraco.Web.Common/Controllers/UmbracoAuthorizedController.cs
Labels: project/v9

#10531 V9: Autogeneration of AppSettings JSON schema and Merge the official + Umbraco
  .gitignore
  NuGet.Config
  build/azure-pipelines.yml
  build/build.ps1
  build/templates/UmbracoProject/appsettings.Development.json
  build/templates/UmbracoProject/appsettings.json
  src/JsonSchema/AppSettings.cs
  src/JsonSchema/JsonSchema.csproj
  src/JsonSchema/NamespacePrefixedSchemaNameGenerator.cs
  src/JsonSchema/Program.cs
  src/JsonSchema/UmbracoJsonSchemaGenerator.cs
  src/JsonSchema/UmbracoJsonSchemaGeneratorSettings.cs
  src/Umbraco.Core/Configuration/Models/ActiveDirectorySettings.cs
  src/Umbraco.Core/Configuration/Models/Attributes/UmbracoOptionsAttribute.cs
  src/Umbraco.Core/Configuration/Models/ConnectionStrings.cs
  src/Umbraco.Core/Configuration/Models/ContentImagingSettings.cs
  src/Umbraco.Core/Configuration/Models/ContentNotificationSettings.cs
  src/Umbraco.Core/Configuration/Models/ContentSettings.cs
  src/Umbraco.Core/Configuration/Models/CoreDebugSettings.cs
  src/Umbraco.Core/Configuration/Models/DatabaseServerMessengerSettings.cs
  src/Umbraco.Core/Configuration/Models/DatabaseServerRegistrarSettings.cs
  src/Umbraco.Core/Configuration/Models/ExceptionFilterSettings.cs
  src/Umbraco.Core/Configuration/Models/GlobalSettings.cs
  src/Umbraco.Core/Configuration/Models/HealthChecksNotificationMethodSettings.cs
  src/Umbraco.Core/Configuration/Models/HealthChecksNotificationSettings.cs
  src/Umbraco.Core/Configuration/Models/HealthChecksSettings.cs
  src/Umbraco.Core/Configuration/Models/HostingSettings.cs
  src/Umbraco.Core/Configuration/Models/ImagingCacheSettings.cs
  src/Umbraco.Core/Configuration/Models/ImagingResizeSettings.cs
  src/Umbraco.Core/Configuration/Models/ImagingSettings.cs
  src/Umbraco.Core/Configuration/Models/IndexCreatorSettings.cs
  src/Umbraco.Core/Configuration/Models/KeepAliveSettings.cs
  src/Umbraco.Core/Configuration/Models/LoggingSettings.cs
  src/Umbraco.Core/Configuration/Models/MemberPasswordConfigurationSettings.cs
  src/Umbraco.Core/Configuration/Models/ModelsBuilderSettings.cs
  src/Umbraco.Core/Configuration/Models/NuCacheSettings.cs
  src/Umbraco.Core/Configuration/Models/RequestHandlerSettings.cs
  src/Umbraco.Core/Configuration/Models/RichTextEditorSettings.cs
  src/Umbraco.Core/Configuration/Models/RuntimeMinificationSettings.cs
  src/Umbraco.Core/Configuration/Models/RuntimeSettings.cs
  src/Umbraco.Core/Configuration/Models/SecuritySettings.cs
  src/Umbraco.Core/Configuration/Models/SmtpSettings.cs
  src/Umbraco.Core/Configuration/Models/TourSettings.cs
  src/Umbraco.Core/Configuration/Models/TypeFinderSettings.cs
  src/Umbraco.Core/Configuration/Models/UmbracoPluginSettings.cs
  src/Umbraco.Core/Configuration/Models/UnattendedSettings.cs
  src/Umbraco.Core/Configuration/Models/UserPasswordConfigurationSettings.cs
  src/Umbraco.Core/Configuration/Models/WebRoutingSettings.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
  src/Umbraco.Web.UI.NetCore/appsettings.Development.json
  src/Umbraco.Web.UI.NetCore/appsettings.json
  src/umbraco.sln
Labels: project/v9

#9576 Accessibility improvements for Extensions in Razor Markup
  src/Umbraco.Core/Models/PublishedContent/Fallback.cs
  src/Umbraco.Tests/PublishedContent/PublishedContentLanguageVariantTests.cs
  src/Umbraco.Web/Models/PublishedContent/PublishedValueFallback.cs
Labels: state/needs-investigation

#10592 V9: SqlCeImageMapper only applied for SqlCe
  src/Umbraco.Infrastructure/Persistence/DbProviderFactoryCreator.cs
  src/Umbraco.Infrastructure/Persistence/IDbProviderFactoryCreator.cs
  src/Umbraco.Infrastructure/Persistence/IProviderSpecificMapperFactory.cs
  src/Umbraco.Infrastructure/Persistence/SqlServerDbProviderFactoryCreator.cs
  src/Umbraco.Infrastructure/Persistence/UmbracoDatabase.cs
  src/Umbraco.Infrastructure/Persistence/UmbracoDatabaseFactory.cs
  src/Umbraco.Persistence.SqlCe/SqlCeSpecificMapperFactory.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web/UmbracoDbProviderFactoryCreator.cs
Labels: project/v9, release/9.0.0-rc001, type/bug

#10612 V9: Remove manifest watcher
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Core/Manifest/ManifestWatcher.cs
  src/Umbraco.Core/Runtime/AppPluginsManifestWatcherNotificationHandler.cs
Labels: project/v9

#10614 RenderController as .NETCore IOptions pattern
  src/Umbraco.Tests.UnitTests/Umbraco.Web.Website/Routing/UmbracoRouteValuesFactoryTests.cs
  src/Umbraco.Web.Website/Controllers/UmbracoRenderingDefaults.cs
  src/Umbraco.Web.Website/Controllers/UmbracoRenderingDefaultsOptions.cs
  src/Umbraco.Web.Website/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Website/Routing/UmbracoRouteValuesFactory.cs
Labels: release/9.0.0-rc001

#10618 V9: Migrated surfaceaction extension methods
  src/Umbraco.Web.Common/Extensions/FriendlyUrlHelperExtensions.cs
  src/Umbraco.Web.Common/Extensions/UrlHelperExtensions.cs
  src/Umbraco.Web/UrlHelperRenderExtensions.cs
Labels: release/9.0.0-rc001

#10619 Changes the RoslynCompiler to use assemblies resolved from the DependencyContext
  src/Umbraco.Infrastructure/ModelsBuilder/Building/Builder.cs
  src/Umbraco.Infrastructure/ModelsBuilder/RoslynCompiler.cs
  src/Umbraco.Web.Common/ModelsBuilder/InMemoryModelFactory.cs
Labels: release/9.0.0-rc001, type/bug

#10628 Fix for #10627 - UmbracoDictionaryTranslate checks.
  src/Umbraco.Core/Services/LocalizedTextServiceExtensions.cs
Labels: project/v9, release/9.0.0-rc002, type/bug

#10636 Change path to log files in error.html (installation)
  src/Umbraco.Web.UI.Client/src/installer/steps/error.html
Labels: project/v9, release/9.0.0-rc002

#10629 V9/task/package partial views
  src/Umbraco.Core/IO/FileSystemExtensions.cs
  src/Umbraco.Core/Models/ContentEditing/UmbracoEntityTypes.cs
  src/Umbraco.Core/Models/Mapping/CodeFileMapDefinition.cs
  src/Umbraco.Core/Models/Packaging/CompiledPackage.cs
  src/Umbraco.Core/Packaging/CompiledPackageXmlParser.cs
  src/Umbraco.Core/Packaging/ConflictingPackageData.cs
  src/Umbraco.Core/Packaging/InstallationSummary.cs
  src/Umbraco.Core/Packaging/PackageDefinition.cs
  src/Umbraco.Core/Packaging/PackageDefinitionXmlParser.cs
  src/Umbraco.Core/Packaging/PackageMigrationResource.cs
  src/Umbraco.Core/Packaging/PackagesRepository.cs
  src/Umbraco.Core/Services/IEntityXmlSerializer.cs
  src/Umbraco.Core/Services/IFileService.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Services.cs
  src/Umbraco.Infrastructure/Packaging/PackageDataInstallation.cs
  src/Umbraco.Infrastructure/Services/Implement/EntityXmlSerializer.cs
  src/Umbraco.Infrastructure/Services/Implement/FileService.cs
  src/Umbraco.Tests.Integration/Umbraco.Core/Packaging/CreatedPackagesRepositoryTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Packaging/PackageDataInstallationTests.cs
  src/Umbraco.Web.BackOffice/Controllers/CodeFileController.cs
  src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
  src/Umbraco.Web.BackOffice/Controllers/MacrosController.cs
  src/Umbraco.Web.BackOffice/Controllers/PackageController.cs
  src/Umbraco.Web.BackOffice/Controllers/StylesheetController.cs
  src/Umbraco.Web.UI.Client/src/views/packages/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/packages/edit.html
Labels: category/breaking, project/v9, release/9.0.0-rc002

#10669 V9: Fix recursive localize when resetting password
  src/Umbraco.Core/Services/LocalizedTextServiceExtensions.cs
Labels: project/v9, release/9.0.0-rc002, type/bug

#10659 Fixes issue that the update culture dates were not synced with the version date like they are for the published culture dates
  src/Umbraco.Core/Models/ContentRepositoryExtensions.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentRepository.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServiceTests.cs
Labels: project/v9, type/bug

#10680 V9: Fix validation messages
  src/Umbraco.Web.BackOffice/Controllers/UmbracoAuthorizedApiController.cs
Labels: project/v9, release/9.0.0-rc002, type/bug

#10652 Typo in DataTypeList Media Picke (legacy)
  src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs
Labels: category/ui, community/pr, project/v9, release/9.0.0-rc002, type/bug

#10691 Adds bundle options to the package manifest
  src/Umbraco.Core/Configuration/Grid/GridEditorsConfig.cs
  src/Umbraco.Core/ContentApps/ContentAppFactoryCollectionBuilder.cs
  src/Umbraco.Core/Dashboards/DashboardCollectionBuilder.cs
  src/Umbraco.Core/Manifest/BundleOptions.cs
  src/Umbraco.Core/Manifest/CompositePackageManifest.cs
  src/Umbraco.Core/Manifest/IManifestParser.cs
  src/Umbraco.Core/Manifest/ManifestAssets.cs
  src/Umbraco.Core/Manifest/PackageManifest.cs
  src/Umbraco.Core/PropertyEditors/ParameterEditorCollection.cs
  src/Umbraco.Core/PropertyEditors/PropertyEditorCollection.cs
  src/Umbraco.Core/Sections/SectionCollectionBuilder.cs
  src/Umbraco.Core/WebAssets/BundlingOptions.cs
  src/Umbraco.Core/WebAssets/IRuntimeMinifier.cs
  src/Umbraco.Infrastructure/Manifest/ManifestParser.cs
  src/Umbraco.Infrastructure/WebAssets/BackOfficeWebAssets.cs
  src/Umbraco.Infrastructure/WebAssets/RuntimeMinifierExtensions.cs
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
  src/Umbraco.Web.BackOffice/Extensions/RuntimeMinifierExtensions.cs
  src/Umbraco.Web.Common/RuntimeMinification/SmidgeRuntimeMinifier.cs
Labels: project/v9, type/feature

#10150 Ensure that any ReaderWriterLockSlim is disposed, or replaced with a more suitable lock
  src/Umbraco.Core/Cache/AppCaches.cs
  src/Umbraco.Core/Cache/AppPolicedCacheDictionary.cs
  src/Umbraco.Core/Cache/DeepCloneAppCache.cs
  src/Umbraco.Core/Cache/ObjectCacheAppCache.cs
  src/Umbraco.Core/Cache/WebCachingAppCache.cs
  src/Umbraco.Core/Collections/ConcurrentHashSet.cs
  src/Umbraco.Core/Models/PropertyGroupCollection.cs
  src/Umbraco.Core/Models/PropertyTypeCollection.cs
  src/Umbraco.Core/ReadLock.cs
  src/Umbraco.Core/Services/IdkMap.cs
  src/Umbraco.Core/UpgradeableReadLock.cs
  src/Umbraco.Core/WriteLock.cs
  src/Umbraco.ModelsBuilder.Embedded/PureLiveModelFactory.cs
  src/Umbraco.Web/Logging/WebProfilerProvider.cs
  src/Umbraco.Web/PublishedCache/NuCache/MemberCache.cs
  src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshot.cs
  src/Umbraco.Web/PublishedCache/PublishedContentTypeCache.cs
  src/Umbraco.Web/Routing/SiteDomainHelper.cs
Labels: category/performance, state/sprint-candidate

#10603 Fix duplicate ID when creating document types with SQL CE
  src/Umbraco.Core/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Core/Migrations/Upgrade/V_8_15_0/UpdateCmsPropertyGroupIdSeed.cs
  src/Umbraco.Core/Persistence/Dtos/PropertyTypeGroupDto.cs
  src/Umbraco.Core/Umbraco.Core.csproj
Labels: type/bug

#10621 File upload checkered background
  src/Umbraco.Web.UI.Client/src/less/components/umb-property-file-upload.less
  src/Umbraco.Web.UI.Client/src/less/property-editors.less
  src/Umbraco.Web.UI.Client/src/views/components/upload/umb-property-file-upload.html
Labels: category/ux, release/8.16.0

#10717 Update umbeditorview.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorview.directive.js
Labels: community/pr, release/8.16.0, release/no-notes

#9181 9157: Use the sorting event instead of the saving
  src/Umbraco.Core/Services/Implement/ContentService.cs
Labels: hacktoberfest-accepted

#10675 Change the property accessed on the external provider from SocialIcon to Icon.
  src/Umbraco.Web.UI.Client/src/views/common/overlays/user/user.html
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-login.html
Labels: community/pr, project/v9

#10745 Inject windowResizeListener in Image Crop directive
  src/Umbraco.Web.UI.Client/src/common/directives/components/imaging/umbimagecrop.directive.js
  src/Umbraco.Web.UI.Client/src/common/services/windowresizelistener.service.js
Labels: community/pr, release/8.14.3, release/8.15.1, type/bug

#10763 Don't squeeze avatar when help panel is open
  src/Umbraco.Web.UI.Client/src/less/components/application/umb-app-header.less
Labels: category/ui, community/pr, release/8.16.0, type/bug
