Repository umbraco/Umbraco-CMS, pull requests merged in 2021-08, with the labels that each got.

#10319 Update noUiSlider to v15.2.0
  src/Umbraco.Web.UI.Client/gulp/tasks/dependencies.js
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbrangeslider.directive.js
Labels: community/pr, release/8.16.0

#10676 V9: Fix drag and drop image upload
  src/Umbraco.Core/PropertyEditors/MediaUrlGeneratorCollection.cs
Labels: project/v9, release/9.0.0-rc002, type/bug

#10742 Migrated Umbraco.TestData to .NET 5.
  src/Umbraco.TestData/Configuration/TestDataSettings.cs
  src/Umbraco.TestData/Extensions/UmbracoBuilderExtensions.cs
  src/Umbraco.TestData/LoadTestComponent.cs
  src/Umbraco.TestData/LoadTestComposer.cs
  src/Umbraco.TestData/LoadTestController.cs
  src/Umbraco.TestData/Properties/AssemblyInfo.cs
  src/Umbraco.TestData/SegmentTestController.cs
  src/Umbraco.TestData/Umbraco.TestData.csproj
  src/Umbraco.TestData/UmbracoTestDataController.cs
  src/Umbraco.TestData/readme.md
  src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
Labels: project/v9

#10687 V9: Fix translations not shown everywhere
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
Labels: project/v9, type/bug

#10688 Support member names using Down-Level Logon Name format
  src/Umbraco.Core/Configuration/Models/SecuritySettings.cs
  src/Umbraco.Web.Common/Security/ConfigureMemberIdentityOptions.cs
  src/Umbraco.Web.UI.NetCore/appsettings.json
Labels: project/v9

#10615 V9: Fix GetLocalCropUrl
  src/Umbraco.Web.Common/Extensions/FriendlyImageCropperTemplateExtensions.cs
Labels: project/v9, type/bug

#10781 V9: Merge v8/dev 03082021
  src/Umbraco.Core/Configuration/ContentDashboardSettings.cs
  src/Umbraco.Core/Configuration/Models/NuCacheSettings.cs
  src/Umbraco.Core/Models/ContentEditing/ContentTypesByKeys.cs
  src/Umbraco.Core/PropertyEditors/IPropertyCacheCompression.cs
  src/Umbraco.Core/PropertyEditors/IPropertyCacheCompressionOptions.cs
  src/Umbraco.Core/PropertyEditors/NoopPropertyCacheCompressionOptions.cs
  src/Umbraco.Core/PropertyEditors/PropertyCacheCompression.cs
  src/Umbraco.Core/PropertyEditors/UnPublishedContentPropertyCacheCompressionOptions.cs
  src/Umbraco.Core/Services/LocalizedTextServiceExtensions.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Infrastructure/Migrations/Expressions/Create/Table/CreateTableOfDtoBuilder.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_8_15_0/AddCmsContentNuByteColumn.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_8_15_0/UpdateCmsPropertyGroupIdSeed.cs
  src/Umbraco.Infrastructure/Models/MediaWithCrops.cs
  src/Umbraco.Infrastructure/Persistence/BasicBulkSqlInsertProvider.cs
  src/Umbraco.Infrastructure/Persistence/Dtos/PropertyTypeGroupDto.cs
  src/Umbraco.Infrastructure/Persistence/PocoDataDataReader.cs
  src/Umbraco.Infrastructure/Persistence/SqlServerBulkSqlInsertProvider.cs
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/MediaPickerWithCropsValueConverter.cs
  src/Umbraco.Persistence.SqlCe/SqlCeBulkSqlInsertProvider.cs
  src/Umbraco.PublishedCache.NuCache/DataSource/IContentCacheDataSerializer.cs
  src/Umbraco.PublishedCache.NuCache/DataSource/JsonContentNestedDataSerializer.cs
  src/Umbraco.PublishedCache.NuCache/DataSource/MsgPackContentNestedDataSerializer.cs
  src/Umbraco.PublishedCache.NuCache/DataSource/MsgPackContentNestedDataSerializerFactory.cs
  src/Umbraco.PublishedCache.NuCache/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.PublishedCache.NuCache/Persistence/NuCacheContentRepository.cs
  src/Umbraco.Tests/PublishedContent/ContentSerializationTests.cs
  src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
  src/Umbraco.Web.BackOffice/Controllers/DashboardController.cs
  src/Umbraco.Web.Common/Extensions/FriendlyImageCropperTemplateExtensions.cs
  src/Umbraco.Web.Common/Extensions/ImageCropperTemplateCoreExtensions.cs
  src/Umbraco.Web.Common/Extensions/UrlHelperExtensions.cs
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditors.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/imaging/umbimagecrop.directive.js
  src/Umbraco.Web.UI.Client/src/common/resources/content.resource.js
  src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
  src/Umbraco.Web.UI.Client/src/common/services/localization.service.js
  src/Umbraco.Web.UI.Client/src/common/services/windowresizelistener.service.js
  src/Umbraco.Web.UI.Client/src/views/content/content.rights.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker3/umbMediaPicker3PropertyEditor.component.js
  src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
Labels: project/v9

#10661 Updated public IUmbracoBuilder extension methods to allow chaining
  src/Umbraco.Core/Composing/CompositionExtensions.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.DistributedCache.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Uniques.cs
  src/Umbraco.Web.Website/Extensions/WebsiteUmbracoBuilderExtensions.cs
Labels: project/v9

#10716 Testable BTree to ContentCache in V9 / Separate SqlCe from integration tests
  .gitignore
  build/azure-pipelines.yml
  build/templates/UmbracoPackage/.template.config/template.json
  build/templates/UmbracoProject/.template.config/template.json
  src/Directory.Build.props
  src/Umbraco.Infrastructure/Routing/RedirectTrackingHandler.cs
  src/Umbraco.PublishedCache.NuCache/DataSource/BTree.ContentDataSerializer.cs
  src/Umbraco.PublishedCache.NuCache/DataSource/BTree.cs
  src/Umbraco.PublishedCache.NuCache/DataSource/IDictionaryOfPropertyDataSerializer.cs
  src/Umbraco.Tests.Integration.SqlCe/Umbraco.Infrastructure/Persistence/DatabaseBuilderTests.cs
  src/Umbraco.Tests.Integration.SqlCe/Umbraco.Tests.Integration.SqlCe.csproj
  src/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  src/Umbraco.Web.UI.NetCore/umbraco/config/lang/en.xml
  src/Umbraco.Web.UI.NetCore/umbraco/config/lang/en_us.xml
  src/umbraco-netcore-only.sln
  src/umbraco.sln
Labels: project/v9

#10660 Added MaybeNullAttribute to ModelsBuilder generated files
  src/Umbraco.Infrastructure/ModelsBuilder/Building/TextBuilder.cs
  src/Umbraco.Tests.UnitTests/Umbraco.ModelsBuilder.Embedded/BuilderTests.cs
Labels: project/v9

#10722 V9: Fix multi url picker
  src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
  src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js
Labels: project/v9, type/bug

#10795 Update Serilog dependencies
  build/NuSpecs/UmbracoCms.Core.nuspec
  src/Umbraco.Core/Umbraco.Core.csproj
Labels: category/performance, community/pr, release/8.16.0, status/dependency-update, type/bug

#10762 Tour backdrop missing
  src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtree.directive.js
  src/Umbraco.Web.UI.Client/src/common/services/backdrop.service.js
  src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js
  src/Umbraco.Web.UI.Client/src/common/services/overlay.service.js
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-backdrop.html
Labels: category/ux, community/pr, release/8.16.0, type/bug

#10756 Only make umb-button-ellipsis visible when above backdrop
  src/Umbraco.Web.UI.Client/src/less/components/buttons/umb-button-ellipsis.less
Labels: category/ui, community/pr, release/8.16.0, type/bug

#10797 Fixes: Unable to unlock locked-out member #10678
  src/Umbraco.Core/Models/Identity/BackOfficeIdentityUser.cs
  src/Umbraco.Web/Security/BackOfficeUserManager.cs
Labels: community/pr, release/8.16.0, type/bug

#10654 Refactor NPoco queries to use constants and dtos
  src/Umbraco.Core/Persistence/Dtos/DictionaryDto.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/DictionaryRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/DomainRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/ExternalLoginRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/LanguageRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/MacroRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/MediaTypeRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/MemberGroupRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/MemberRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/MemberTypeRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/PublicAccessRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/RelationRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/RelationTypeRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/TemplateRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/UserGroupRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/UserRepository.cs
Labels: community/pr, category/refactor, type/feature, release/8.16.0

#10600 Fix localization of title attribute in umb-property-info-button
  src/Umbraco.Web.UI.Client/src/views/components/umb-property-info-button/umb-property-info-button.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-property-info-button/umbpropertyinfobutton.component.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.html
Labels: community/pr, project/block-editor, category/localization, type/feature, release/8.16.0

#10523 Use color picker plugin when plugins includes table plugin
  src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
Labels: community/pr, type/feature, release/8.16.0

#9305 Match neutral cultures as Examine culture fields
  src/Umbraco.Examine/ExamineExtensions.cs
  src/Umbraco.Examine/UmbracoFieldDefinitionCollection.cs
Labels: hacktoberfest-accepted

#10681 UserService.SavedUserGroup event returns wrong list of AddedUsers
  src/Umbraco.Core/Services/Implement/UserService.cs
Labels: community/pr, type/bug, release/8.16.0

#10672 Fix examine overview not working as expected
  src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.controller.js
  src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.html
Labels: community/pr, type/bug, release/8.16.0

#10663 8.15RC Compress Umbraco.TrueFalse properties from int32 to bool.
  src/Umbraco.Core/PropertyEditors/UnPublishedContentPropertyCacheCompressionOptions.cs
  src/Umbraco.Web/PublishedCache/NuCache/DataSource/MsgPackContentNestedDataSerializer.cs
Labels: community/pr, category/performance, type/feature, release/8.16.0

#10664 Automatically intern Alias properties for SQL queries
  src/Umbraco.Core/Persistence/Dtos/ContentTypeDto.cs
  src/Umbraco.Core/Persistence/Dtos/PropertyTypeDto.cs
Labels: community/pr, category/performance, type/feature, release/8.16.0

#10803 V9: Add basic auth middleware
  src/JsonSchema/AppSettings.cs
  src/Umbraco.Core/Configuration/Models/BasicAuthSettings.cs
  src/Umbraco.Core/Constants-Configuration.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
  src/Umbraco.Core/Services/IBasicAuthService.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Services.cs
  src/Umbraco.Infrastructure/Services/Implement/BasicAuthService.cs
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Services/BasicAuthServiceTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Security/BackOfficeCookieManagerTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Extensions/HttpContextExtensionTests.cs
  src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilder.BackOfficeAuth.cs
  src/Umbraco.Web.BackOffice/Extensions/HttpContextExtensions.cs
  src/Umbraco.Web.BackOffice/Extensions/UmbracoApplicationBuilder.BackOffice.cs
  src/Umbraco.Web.BackOffice/Security/BackOfficeCookieManager.cs
  src/Umbraco.Web.BackOffice/Security/ConfigureBackOfficeCookieOptions.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Extensions/ApplicationBuilderExtensions.cs
  src/Umbraco.Web.Common/Extensions/ControllerExtensions.cs
  src/Umbraco.Web.Common/Extensions/HttpContextExtensions.cs
  src/Umbraco.Web.Common/Security/IBackOfficeSignInManager.cs
  src/Umbraco.Web.Website/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Website/Extensions/UmbracoApplicationBuilder.Website.cs
  src/Umbraco.Web.Website/Middleware/BasicAuthenticationMiddleware.cs
Labels: project/v9

#10804 Update Nuget Package Dependencies
  src/JsonSchema/JsonSchema.csproj
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
  src/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
  src/Umbraco.Tests.Integration.SqlCe/Umbraco.Tests.Integration.SqlCe.csproj
  src/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
Labels: project/v9

#10589 Adding extension for MapDefinitions collection builder
  src/Umbraco.Core/CompositionExtensions.cs
Labels: community/pr, category/dx, type/feature, release/8.16.0

#10518 Changed umb-notifications z-index
  src/Umbraco.Web.UI.Client/src/less/components/notifications/umb-notifications.less
Labels: community/pr, category/ui, category/ux, type/bug, release/8.16.0

#10356 #10354 - added domain content id as node context for the content find…
  src/Umbraco.Web/Routing/ContentFinderByConfigured404.cs
  src/Umbraco.Web/Routing/NotFoundHandlerHelper.cs
Labels: community/pr, status/needs-docs, type/feature, release/8.16.0

#10808 v9: Added "JetBrains.Annotations" to assembly exclusion list to fix #10801
  src/Umbraco.Core/Composing/TypeFinder.cs
Labels: project/v9

#10794 V9: Limit the BlockList thumbnail picker to only the directories serving static files
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Composing/TypeFinderTests.cs
  src/Umbraco.Web.BackOffice/Trees/StaticFilesTreeController.cs
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.controller.js
Labels: project/v9

#10796 V9: Umbraco Templates - remove unwanted folders on publish
  build/templates/UmbracoProject/UmbracoProject.csproj
Labels: project/v9

#10811 Needs a null check so it doesn't explode when saving content during a migration.
  src/Umbraco.Infrastructure/Routing/RedirectTrackingHandler.cs
Labels: project/v9

#10819 v9: Remove duplicate project entry for examine in netcore-only sln
  src/umbraco-netcore-only.sln
Labels: project/v9

#10721 external login changes/enhancements
  src/Umbraco.Core/Install/InstallSteps/UpgradeStep.cs
  src/Umbraco.Core/Notifications/SendEmailNotification.cs
  src/Umbraco.Infrastructure/EmailSender.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_9_0_0/ExternalLoginTableIndexes.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_9_0_0/ExternalLoginTableIndexesFixup.cs
  src/Umbraco.Infrastructure/Persistence/DatabaseAnnotations/SpecialDbType.cs
  src/Umbraco.Infrastructure/Persistence/DatabaseAnnotations/SpecialDbTypeAttribute.cs
  src/Umbraco.Infrastructure/Persistence/DatabaseAnnotations/SpecialDbTypes.cs
  src/Umbraco.Infrastructure/Persistence/DatabaseModelDefinitions/ColumnDefinition.cs
  src/Umbraco.Infrastructure/Persistence/DatabaseModelDefinitions/DefinitionFactory.cs
  src/Umbraco.Infrastructure/Persistence/DbProviderFactoryCreator.cs
  src/Umbraco.Infrastructure/Persistence/Dtos/ExternalLoginDto.cs
  src/Umbraco.Infrastructure/Persistence/PocoDataDataReader.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/UserRepository.cs
  src/Umbraco.Infrastructure/Persistence/SqlSyntax/DbTypes.cs
  src/Umbraco.Infrastructure/Persistence/SqlSyntax/DbTypesFactory.cs
  src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs
  src/Umbraco.Infrastructure/Persistence/SqlSyntax/MicrosoftSqlSyntaxProviderBase.cs
  src/Umbraco.Infrastructure/Persistence/SqlSyntax/SqlSyntaxProviderBase.cs
  src/Umbraco.Infrastructure/Security/BackOfficeIdentityUser.cs
  src/Umbraco.Infrastructure/Security/BackOfficeUserStore.cs
  src/Umbraco.Infrastructure/Security/IdentityMapDefinition.cs
  src/Umbraco.Infrastructure/WebAssets/BackOfficeWebAssets.cs
  src/Umbraco.Persistence.SqlCe/SqlCeSyntaxProvider.cs
  src/Umbraco.Tests.UnitTests/TestHelpers/TestHelper.cs
  src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeServerVariables.cs
  src/Umbraco.Web.BackOffice/Extensions/HtmlHelperBackOfficeExtensions.cs
  src/Umbraco.Web.BackOffice/Security/AutoLinkSignInResult.cs
  src/Umbraco.Web.BackOffice/Security/BackOfficeAuthenticationBuilder.cs
  src/Umbraco.Web.BackOffice/Security/BackOfficeExternaLoginProviderScheme.cs
  src/Umbraco.Web.BackOffice/Security/BackOfficeExternalLoginProvider.cs
  src/Umbraco.Web.BackOffice/Security/BackOfficeExternalLoginProviderOptions.cs
  src/Umbraco.Web.BackOffice/Security/BackOfficeExternalLoginProviders.cs
  src/Umbraco.Web.BackOffice/Security/BackOfficeExternalLoginsBuilder.cs
  src/Umbraco.Web.BackOffice/Security/BackOfficeSignInManager.cs
  src/Umbraco.Web.BackOffice/Security/IBackOfficeExternalLoginProviders.cs
  src/Umbraco.Web.Common/Security/UmbracoSignInManager.cs
  src/Umbraco.Web.UI.Client/src/common/services/externallogininfo.service.js
Labels: project/v9

#10823 V9: Package export and import both xml and zip
  src/Umbraco.Core/Packaging/PackageMigrationResource.cs
  src/Umbraco.Core/Packaging/PackagesRepository.cs
  src/Umbraco.Infrastructure/Packaging/ImportPackageBuilderExpression.cs
  src/Umbraco.Infrastructure/Packaging/PackageDataInstallation.cs
  src/Umbraco.Tests.Integration/Umbraco.Core/Packaging/CreatedPackagesRepositoryTests.cs
Labels: project/v9, release/9.0.0-rc002

#10832 Fixed issue with CachedPartial that cached an unmaterialized value
  src/Umbraco.Web.Common/Extensions/CacheHelperExtensions.cs
  src/Umbraco.Web.Common/Extensions/HtmlContentExtensions.cs
  src/Umbraco.Web.Website/Extensions/HtmlHelperRenderExtensions.cs
Labels: project/v9, type/bug, release/9.0.0-rc002

#10684 Set isMainPage to true on TemplateRenderer.ExecuteTemplateRendering
  src/Umbraco.Web.Common/Templates/TemplateRenderer.cs
Labels: project/v9

#10849 Build sln before running tests.
  build/azure-pipelines.yml
Labels: project/v9

#10850 v9: If you didnt have a member group, restricting acces to the public would always lead to error page
  src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Security/PublicAccessCheckerTests.cs
  src/Umbraco.Web.Common/Security/PublicAccessChecker.cs
Labels: project/v9, type/bug, release/9.0.0-rc002

#10787 v9: Fixed a bug where validation didnt update properly
  src/Umbraco.Web.BackOffice/Controllers/MemberController.cs
Labels: project/v9

#10856 Implement drag start and drag stop events
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbcolorpicker.directive.js
Labels: community/pr, category/ux, release/8.17.0

#10623 V9: Fix ImageSharp integration and add support for custom crops
  src/Umbraco.Core/Media/IImageUrlGenerator.cs
  src/Umbraco.Core/Models/ImageCropRatioMode.cs
  src/Umbraco.Core/Models/ImageUrlGenerationOptions.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/Media/ImageDimensionExtractor.cs
  src/Umbraco.Infrastructure/Media/ImageSharpImageUrlGenerator.cs
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/ImageCropperValue.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Media/ImageSharpImageUrlGeneratorTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Extensions/ImageCropperTemplateCoreExtensionsTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/ImageCropperTest.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/ImageProcessors/CropWebProcessorTests.cs
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeServerVariables.cs
  src/Umbraco.Web.BackOffice/Controllers/ImageUrlGeneratorController.cs
  src/Umbraco.Web.BackOffice/Controllers/ImagesController.cs
  src/Umbraco.Web.Common/DependencyInjection/ImageSharpConfigurationOptions.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilder.ImageSharp.cs
  src/Umbraco.Web.Common/Extensions/FriendlyImageCropperTemplateExtensions.cs
  src/Umbraco.Web.Common/Extensions/ImageCropperTemplateCoreExtensions.cs
  src/Umbraco.Web.Common/Extensions/UrlHelperExtensions.cs
  src/Umbraco.Web.Common/ImageProcessors/CropWebProcessor.cs
  src/Umbraco.Web.UI.Client/src/common/resources/imageurlgenerator.resource.js
  src/Umbraco.Web.UI.Client/src/common/services/mediahelper.service.js
  src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
  src/Umbraco.Web.UI.Client/src/views/components/blockcard/umbBlockCard.component.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/fileupload/fileupload.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/media.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.controller.js
Labels: category/breaking, project/v9, type/bug, release/9.0.0-rc002

#10857 SystemLock - Update link to msdn blog
  src/Umbraco.Core/SystemLock.cs
Labels: project/v9

#10859 Process requires disposal
  src/Umbraco.Core/Diagnostics/MiniDump.cs
  src/Umbraco.Infrastructure/Persistence/LocalDb.cs
  src/Umbraco.Infrastructure/Sync/DatabaseServerMessenger.cs
Labels: project/v9

#10862 Cleanup _inMemoryModelFactory.ModelsChanged event on dispose in RefreshingRazorViewEngine
  src/Umbraco.Web.Common/ModelsBuilder/RefreshingRazorViewEngine.cs
Labels: project/v9

#10861 Reduce allocations by using existing CharArrays for TrimStart()
  src/Umbraco.Core/Constants-CharArrays.cs
  src/Umbraco.Core/Routing/ContentFinderByUrlAlias.cs
  src/Umbraco.Core/Routing/UmbracoRequestPaths.cs
  src/Umbraco.Web.Common/AspNetCore/AspNetCoreHostingEnvironment.cs
Labels: project/v9

#10855 V9: Fix packages overflow
  src/Umbraco.Web.UI.Client/src/less/components/html/umb-expansion-panel.less
Labels: project/v9

#10860 Avoid mixing using of string interpolation and string formatting in log messages
  src/Umbraco.Infrastructure/Examine/ExamineIndexRebuilder.cs
  src/Umbraco.PublishedCache.NuCache/ContentStore.cs
  src/Umbraco.PublishedCache.NuCache/PublishedSnapshotService.cs
Labels: project/v9, release/9.0.0-rc002

#10826 V9: Add unique constraints to cmsDictionary and cmsLanguageText tables
  src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_9_0_0/DictionaryTablesIndexes.cs
  src/Umbraco.Infrastructure/Persistence/Dtos/DictionaryDto.cs
  src/Umbraco.Infrastructure/Persistence/Dtos/LanguageTextDto.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Packaging/PackageDataInstallationTests.cs
Labels: project/v9, type/bug, release/9.0.0-rc002

#10873 v9: Making backoffice path absolute
  src/Umbraco.Tests.Integration/Implementations/TestHelper.cs
  src/Umbraco.Web.Common/AspNetCore/AspNetCoreBackOfficeInfo.cs
Labels: project/v9, release/9.0.0-rc002

#10868 v9: appsettings.json now generate from template if missing
  .gitignore
  src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
  src/Umbraco.Web.UI.NetCore/appsettings.Development.template.json
  src/Umbraco.Web.UI.NetCore/appsettings.template.json
Labels: project/v9

#10877 V9: Help improve using Smidge in FrontEnd views
  build/templates/UmbracoProject/Views/_ViewImports.cshtml
  src/Umbraco.Web.UI.NetCore/Views/_ViewImports.cshtml
Labels: project/v9

#10789 v9: Resolving UmbracoHelper in custom middleware was null
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
Labels: project/v9, type/bug, release/9.0.0-rc002

#10846 Resolve issues adding content on startup for #10774
  src/Umbraco.PublishedCache.NuCache/PublishedSnapshotService.cs
Labels: project/v9

#10869 Raise SendingContentModel event for each element type in blocklist
  src/Umbraco.Web/WebApi/Filters/OutgoingEditorModelEventAttribute.cs
Labels: type/bug

#10878 V9: Keep the old indexes in case the DictionaryTablesIndexes migration fails
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_9_0_0/DictionaryTablesIndexes.cs
Labels: project/v9, release/9.0.0-rc002

#10829 V9: Infinite editor file picker
  src/Umbraco.Web.BackOffice/Trees/StaticFilesTreeController.cs
  src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
  src/Umbraco.Web.UI.Client/src/views/packages/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.controller.js
Labels: project/v9

#10853 V9: Eye Dropper property value converter
  src/Umbraco.Core/Constants-PropertyEditors.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/EyeDropperValueConverter.cs
  src/Umbraco.Infrastructure/PropertyEditors/EyeDropperColorPickerConfigurationEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/EyeDropperColorPickerPropertyEditor.cs
Labels: project/v9

#10885 V8: Improve nested content optimization in the backoffice
  src/Umbraco.Web.UI.Client/src/common/resources/content.resource.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
  src/Umbraco.Web/Editors/ContentController.cs
  src/Umbraco.Web/Models/ContentEditing/ContentTypesByAliases.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: category/performance

#10894 Inherit text color from parent element
  src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.html
  src/Umbraco.Web.UI.Client/src/views/components/blockcard/umbBlockCard.component.js
Labels: community/pr, category/ui, type/bug, release/8.17.0

#10887 Ensure Nuget dependencies are upto date except NPoco as breaking changes in major
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
  src/Umbraco.Tests.Integration.SqlCe/Umbraco.Tests.Integration.SqlCe.csproj
  src/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
Labels: project/v9, release/9.0.0-rc003

#10905 V9/bugfix/email sender ambiguous constructor
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/Mail/EmailSender.cs
  src/Umbraco.Tests.UnitTests/TestHelpers/TestHelper.cs
Labels: project/v9, release/9.0.0-rc003

#10720 Update LocalizedTextServiceExtensions.cs - use the culture parameter, instead of Thread.CurrentThread.CurrentUICulture
  src/Umbraco.Core/Services/LocalizedTextServiceExtensions.cs
Labels: project/v9, release/9.0.0-rc003

#10884 V9: Move default ImageSharp cache folder to TEMP and map configured value to content root
  .gitignore
  src/Umbraco.Core/Configuration/Models/ImagingCacheSettings.cs
  src/Umbraco.Tests.Integration/TestServerTest/UmbracoTestServerTestBase.cs
  src/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilder.ImageSharp.cs
Labels: project/v9, release/9.0.0-rc003

#10898 v9: removed obsolete property from User and IUser
  src/Umbraco.Core/Models/Membership/IUser.cs
  src/Umbraco.Core/Models/Membership/User.cs
  src/Umbraco.Infrastructure/Persistence/Factories/UserFactory.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/UserRepository.cs
Labels: category/breaking, project/v9, release/9.0.0-rc003

#10880 Suppress scope notifications during migrations
  src/Umbraco.Core/Notifications/RuntimeUnattendedUpgradeNotification.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Installer.cs
  src/Umbraco.Infrastructure/Install/InstallSteps/DatabaseUpgradeStep.cs
  src/Umbraco.Infrastructure/Install/InstallSteps/NewInstallStep.cs
  src/Umbraco.Infrastructure/Install/PackageMigrationRunner.cs
  src/Umbraco.Infrastructure/Install/UnattendedUpgrader.cs
  src/Umbraco.Infrastructure/Migrations/ExecutedMigrationPlan.cs
  src/Umbraco.Infrastructure/Migrations/IMigrationExpression.cs
  src/Umbraco.Infrastructure/Migrations/IMigrationPlanExecutor.cs
  src/Umbraco.Infrastructure/Migrations/Install/DatabaseBuilder.cs
  src/Umbraco.Infrastructure/Migrations/MigrationPlan.cs
  src/Umbraco.Infrastructure/Migrations/MigrationPlanExecutor.cs
  src/Umbraco.Infrastructure/Migrations/Notifications/MigrationPlansExecutedNotification.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/Upgrader.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Migrations/AdvancedMigrationTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/MigrationPlanTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/PostMigrationTests.cs
  src/Umbraco.Web.BackOffice/Controllers/PackageController.cs
Labels: project/v9, state/sprint-candidate

#10919 Update Serilog.Enrichers.Process to 2.0.2 as it fixes a leak
  build/NuSpecs/UmbracoCms.Core.nuspec
  src/Umbraco.Core/Umbraco.Core.csproj
Labels: category/performance, type/bug, release/8.16.0

#10948 Fixed potential null reference exception in KeepAlive
  src/Umbraco.Infrastructure/HostedServices/KeepAlive.cs
Labels: project/v9, type/bug, release/9.0.0-rc003

#10934 Avoid creating a new string for the log level every log message
  src/Umbraco.Core/Logging/Serilog/Enrichers/Log4NetLevelMapperEnricher.cs
Labels: community/pr, category/performance, type/feature, release/8.17.0

#10935 Avoid generating the maindom hash twice to get the Id.
  src/Umbraco.Core/Runtime/MainDomSemaphoreLock.cs
Labels: community/pr, category/performance, type/feature, release/8.17.0

#8638 Allow to pass in boolean to noDirtyCheck directive
  src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbcheckbox.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbradiobutton.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/validation/nodirtycheck.directive.js
  src/Umbraco.Web.UI.Client/src/views/components/forms/umb-checkbox.html
  src/Umbraco.Web.UI.Client/src/views/components/forms/umb-radiobutton.html
Labels: state/needs-investigation

#10957 emit formSubmitting when submitting change in multi url picker dialog
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.controller.js
Labels: community/pr, type/bug, release/8.17.0

#10973 Fix self-closing tags which should have a end-closing tag
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/propertysettings/propertysettings.html
  src/Umbraco.Web.UI.Client/src/views/common/overlays/user/user.html
  src/Umbraco.Web.UI.Client/src/views/content/assigndomain.html
  src/Umbraco.Web.UI.Client/src/views/content/create.html
  src/Umbraco.Web.UI.Client/src/views/content/createblueprint.html
  src/Umbraco.Web.UI.Client/src/views/documenttypes/views/listview/listview.html
  src/Umbraco.Web.UI.Client/src/views/documenttypes/views/permissions/permissions.html
  src/Umbraco.Web.UI.Client/src/views/documenttypes/views/templates/templates.html
  src/Umbraco.Web.UI.Client/src/views/media/create.html
  src/Umbraco.Web.UI.Client/src/views/mediatypes/views/listview/listview.html
  src/Umbraco.Web.UI.Client/src/views/mediatypes/views/permissions/permissions.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/rowconfig.html
Labels: community/pr, type/bug, release/8.17.0

#10942 Added url mode parameter to the GetCropUrl extension methods
  src/Umbraco.Web.Common/Extensions/FriendlyImageCropperTemplateExtensions.cs
  src/Umbraco.Web.Common/Extensions/ImageCropperTemplateCoreExtensions.cs
  src/Umbraco.Web.Common/Extensions/UrlHelperExtensions.cs
Labels: project/v9

#10941 New project - simplify includes/excludes
  build/templates/UmbracoProject/UmbracoProject.csproj
Labels: project/v9

#10959 V8: Fix IsPublished only working with lowercase.
  src/Umbraco.Core/Serialization/AutoInterningStringKeyCaseInsensitiveDictionaryConverter.cs
  src/Umbraco.Web/PublishedCache/NuCache/DataSource/ContentCacheDataModel.cs
  src/Umbraco.Web/PublishedCache/NuCache/DataSource/MessagePackAutoInterningStringKeyCaseInsensitiveDictionaryFormatter.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: type/bug

#10946 V9: Reuse value editors for validation
  src/Umbraco.Core/Cache/IValueEditorCache.cs
  src/Umbraco.Core/Cache/ValueEditorCache.cs
  src/Umbraco.Core/Cache/ValueEditorCacheRefresher.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Infrastructure/Cache/DistributedCacheBinder_Handlers.cs
  src/Umbraco.Infrastructure/Cache/DistributedCacheExtensions.cs
  src/Umbraco.Infrastructure/Services/Implement/PropertyValidationService.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServiceTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Cache/ValueEditorCacheTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Models/VariationTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Services/PropertyValidationServiceTests.cs
Labels: project/v9, category/performance

#10913 Fix PhysicalFileSystem.GetRelaitvePath for *nix
  src/Umbraco.Core/IO/PhysicalFileSystem.cs
Labels: project/v9
