Repository umbraco/Umbraco-CMS, pull requests merged in 2021-12, with the labels that each got.

#11714 V9: Fix backoffice javascript loading slowly
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/RuntimeMinification/SmidgeRequestHelper.cs
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
Labels: type/bug

#11684 V9: Fix for migration of non-default configurated users/members
  src/JsonSchema/AppSettings.cs
  src/Umbraco.Core/Configuration/Models/LegacyPasswordMigrationSettings.cs
  src/Umbraco.Core/Constants-Configuration.cs
  src/Umbraco.Core/Constants-Security.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
  src/Umbraco.Core/Security/LegacyPasswordSecurity.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberRepository.cs
  src/Umbraco.Infrastructure/Security/MemberPasswordHasher.cs
  src/Umbraco.Infrastructure/Security/MemberUserStore.cs
  src/Umbraco.Infrastructure/Security/UmbracoPasswordHasher.cs
  src/Umbraco.Infrastructure/Security/UmbracoUserManager.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberPasswordHasherTests.cs
Labels: type/bug, release/9.1.2

#11715 V9: Display configured log levels
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/Logging/Serilog/LoggerConfigExtensions.cs
  src/Umbraco.Infrastructure/Logging/Serilog/SerilogLogger.cs
  src/Umbraco.Infrastructure/Logging/Viewer/ILogLevelLoader.cs
  src/Umbraco.Infrastructure/Logging/Viewer/ILogViewer.cs
  src/Umbraco.Infrastructure/Logging/Viewer/LogLevelLoader.cs
  src/Umbraco.Infrastructure/Logging/Viewer/SerilogJsonLogViewer.cs
  src/Umbraco.Infrastructure/Logging/Viewer/SerilogLogViewerSourceBase.cs
  src/Umbraco.Web.BackOffice/Controllers/LogViewerController.cs
  src/Umbraco.Web.Common/Extensions/ServiceCollectionExtensions.cs
  src/Umbraco.Web.UI.Client/src/common/resources/logviewer.resource.js
  src/Umbraco.Web.UI.Client/src/views/logViewer/overview.controller.js
  src/Umbraco.Web.UI.Client/src/views/logViewer/overview.html
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Logging/LogviewerTests.cs
Labels: project/v9

#11548 Remove the need of Smtp.Host config when using PickupDirectoryLocation
  src/Umbraco.Core/Configuration/Models/GlobalSettings.cs
  src/Umbraco.Infrastructure/Mail/EmailSender.cs
Labels: community/pr, type/feature, hacktoberfest-accepted, release/9.2.0

#11768 Move member properties to Member Content App (V9 merge regression)
  src/Umbraco.Core/Models/Mapping/MemberTabsAndPropertiesMapper.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Controllers/MemberControllerUnitTests.cs
Labels: state/sprint-candidate, release/9.2.0

#11769 Adds migration back for v9 for #10450
  src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_9_2_0/AddDefaultForNotificationsToggle.cs
Labels: state/sprint-candidate, release/9.2.0

#11776 Add a health check for umbraco application url
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
  src/Umbraco.Web/HealthCheck/Checks/Security/UmbracoApplicationUrlCheck.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: type/feature, release/8.18.0

#11779 V9: Add a health check for umbraco application url
  src/Umbraco.Core/Constants-HealthChecks.cs
  src/Umbraco.Core/HealthChecks/Checks/Security/UmbracoApplicationUrlCheck.cs
  src/Umbraco.Web.UI/umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
Labels: project/v9, type/feature, release/9.3.0

#11778 V9: Use current request for emails
  src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
  src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
  src/Umbraco.Web.Common/Extensions/HttpRequestExtensions.cs
Labels: release/9.2.0
