Repository umbraco/Umbraco-CMS, pull requests merged in 2021-03, with the labels that each got.

#9881 Replace static events in TreeControllerBase with IEventAggregator notifications
  src/Umbraco.Web.BackOffice/Trees/ApplicationTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/ContentBlueprintTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/ContentTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/ContentTreeControllerBase.cs
  src/Umbraco.Web.BackOffice/Trees/ContentTypeTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/DataTypeTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/DictionaryTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/FileSystemTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/FilesTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/LanguageTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/LogViewerTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/MacrosTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/MediaTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/MediaTypeTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/MemberGroupTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/MemberTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/MemberTypeAndGroupTreeControllerBase.cs
  src/Umbraco.Web.BackOffice/Trees/MemberTypeTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/MenuRenderingEventArgs.cs
  src/Umbraco.Web.BackOffice/Trees/MenuRenderingNotification.cs
  src/Umbraco.Web.BackOffice/Trees/PackagesTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/PartialViewMacrosTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/PartialViewsTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/RelationTypeTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/RootNodeRenderingNotification.cs
  src/Umbraco.Web.BackOffice/Trees/ScriptsTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/StylesheetsTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/TemplatesTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/TreeController.cs
  src/Umbraco.Web.BackOffice/Trees/TreeControllerBase.cs
  src/Umbraco.Web.BackOffice/Trees/TreeNodeRenderingEventArgs.cs
  src/Umbraco.Web.BackOffice/Trees/TreeNodesRenderingEventArgs.cs
  src/Umbraco.Web.BackOffice/Trees/TreeNodesRenderingNotification.cs
  src/Umbraco.Web.BackOffice/Trees/TreeRenderingEventArgs.cs
  src/Umbraco.Web.BackOffice/Trees/UserTreeController.cs
Labels: project/net-core

#9870 Keep custom claims that are flowed during security stamp validation
  src/Umbraco.Web/Security/AppBuilderExtensions.cs
  src/Umbraco.Web/Security/BackOfficeClaimsIdentityFactory.cs
  src/Umbraco.Web/Security/ClaimsIdentityExtensions.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: type/bug

#9900 Remove static methods and events from EmailSender
  src/Umbraco.Core/Mail/IEmailSender.cs
  src/Umbraco.Core/Mail/NotImplementedEmailSender.cs
  src/Umbraco.Infrastructure/EmailSender.cs
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeServerVariables.cs
  src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
  src/Umbraco.Web.BackOffice/Trees/ContentTreeController.cs
Labels: project/net-core

#9892 Replace static editor model events events with IEventAggregator notifications
  src/Umbraco.Core/Editors/EditorModelEventArgs.cs
  src/Umbraco.Web.BackOffice/Filters/EditorModelEventManager.cs
  src/Umbraco.Web.BackOffice/Filters/OutgoingEditorModelEventAttribute.cs
  src/Umbraco.Web.BackOffice/Filters/SendingContentNotification.cs
  src/Umbraco.Web.BackOffice/Filters/SendingDashboardsNotification.cs
  src/Umbraco.Web.BackOffice/Filters/SendingMediaNotification.cs
  src/Umbraco.Web.BackOffice/Filters/SendingMemberNotification.cs
  src/Umbraco.Web.BackOffice/Filters/SendingUserNotification.cs
Labels: project/net-core

#9888 The Value() method for IPublishedContent was not working with the defaultValue parameter
  src/Umbraco.Web/PublishedContentExtensions.cs
  src/Umbraco.Web/PublishedPropertyExtension.cs
Labels: community/review, type/bug

#9934 Unattended Install - Automated User Creation
  src/Umbraco.Core/Configuration/Models/GlobalSettings.cs
  src/Umbraco.Core/Configuration/Models/UnattendedSettings.cs
  src/Umbraco.Core/Configuration/Models/Validation/UnattendedSettingsValidator.cs
  src/Umbraco.Core/Constants-Configuration.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
  src/Umbraco.Core/Events/UnattendedInstallNotification.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Infrastructure/RuntimeState.cs
  src/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
  src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Install/CreateUnattendedUserNotificationHandler.cs
Labels: project/net-core

#9916 Netcore: Fix coupling between IBackOfficeSecurity and IUmbracoContext
  src/Umbraco.Tests.UnitTests/TestHelpers/Objects/TestUmbracoContextFactory.cs
  src/Umbraco.Web.Common/Extensions/HttpContextExtensions.cs
  src/Umbraco.Web.Common/UmbracoContext/UmbracoContext.cs
  src/Umbraco.Web.Common/UmbracoContext/UmbracoContextFactory.cs
Labels: project/net-core

#9200 Cache the SVG icons serverside to boost performance
  src/Umbraco.Core/IO/SystemDirectories.cs
  src/Umbraco.Core/Services/IIconService.cs
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbicon.directive.js
  src/Umbraco.Web.UI.Client/src/common/services/iconhelper.service.js
  src/Umbraco.Web.UI/Umbraco/Views/Default.cshtml
  src/Umbraco.Web/Editors/BackOfficeController.cs
  src/Umbraco.Web/Editors/BackOfficeModel.cs
  src/Umbraco.Web/Editors/BackOfficePreviewModel.cs
  src/Umbraco.Web/Editors/BackOfficeServerVariables.cs
  src/Umbraco.Web/Editors/IconController.cs
  src/Umbraco.Web/Editors/PreviewController.cs
  src/Umbraco.Web/Services/IconService.cs
Labels: category/performance, hacktoberfest/contrib-2020, release/8.10.3, release/8.11.2, release/8.12.1, release/8.8.4, release/8.9.3, state/in-sprint, type/feature

#9965 NetCore: Fix authorization policies bound to Translation section
  src/Umbraco.Web.BackOffice/DependencyInjection/ServiceCollectionExtensions.cs
  src/Umbraco.Web.UI.NetCore/appsettings.json
Labels: project/net-core

#9924 Change scope to only acquire distributed locks once in a scope chain.
  src/Umbraco.Core/Scoping/Scope.cs
  src/Umbraco.Tests/Persistence/LocksTests.cs
  src/Umbraco.Tests/Scoping/ScopeUnitTests.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
Labels: release/8.13.0

#9849 Preview does display draft versions
  src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.BackOffice/Extensions/BackOfficeApplicationBuilderExtensions.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Extensions/ApplicationBuilderExtensions.cs
  src/Umbraco.Web.Common/Middleware/PreviewAuthenticationMiddleware.cs
Labels: project/net-core

#9966 Netcore: Get rid of default files in config folder
  build/NuSpecs/UmbracoCms.nuspec
  build/build.ps1
  src/Umbraco.Core/Configuration/Grid/GridEditorsConfig.cs
  src/Umbraco.Core/Configuration/Models/RichTextEditorSettings.cs
  src/Umbraco.Core/Constants-Configuration.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
  src/Umbraco.Core/EmbeddedResources/Grid/grid.editors.config.js
  src/Umbraco.Core/Models/ILogViewerQuery.cs
  src/Umbraco.Core/Models/LogViewerQuery.cs
  src/Umbraco.Core/Persistence/Constants-DatabaseSchema.cs
  src/Umbraco.Core/Persistence/Repositories/ILogViewerQueryRepository.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Repositories.cs
  src/Umbraco.Infrastructure/Logging/Viewer/LogViewerConfig.cs
  src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs
  src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs
  src/Umbraco.Infrastructure/Migrations/PostMigrations/DeleteLogViewerQueryFile.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_9_0_0/MigrateLogViewerQueriesFromFileToDb.cs
  src/Umbraco.Infrastructure/Persistence/Dtos/LogViewerQueryDto.cs
  src/Umbraco.Infrastructure/Persistence/Mappers/LogViewerQueryMapper.cs
  src/Umbraco.Infrastructure/Persistence/Mappers/MapperCollectionBuilder.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/LogViewerQueryRepository.cs
  src/Umbraco.Infrastructure/PropertyEditors/GridPropertyEditor.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/SqlServerTableByTableTest.cs
  src/Umbraco.Tests.UnitTests/TestHelpers/Assets/logviewer.searches.config.js
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Logging/LogviewerTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
  src/Umbraco.Web.BackOffice/Controllers/TourController.cs
  src/Umbraco.Web.BackOffice/DependencyInjection/ServiceCollectionExtensions.cs
  src/Umbraco.Web.BackOffice/EmbeddedResources/Tours/getting-started.json
  src/Umbraco.Web.BackOffice/PropertyEditors/RichTextPreValueController.cs
  src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
  src/Umbraco.Web.UI.NetCore/appsettings.Development.json
  src/Umbraco.Web.UI.NetCore/config/lang/cs-CZ.user.xml
  src/Umbraco.Web.UI.NetCore/config/lang/da-DK.user.xml
  src/Umbraco.Web.UI.NetCore/config/lang/de-DE.user.xml
  src/Umbraco.Web.UI.NetCore/config/lang/en-GB.user.xml
  src/Umbraco.Web.UI.NetCore/config/lang/en-US.user.xml
  src/Umbraco.Web.UI.NetCore/config/lang/es-ES.user.xml
  src/Umbraco.Web.UI.NetCore/config/lang/fr-FR.user.xml
  src/Umbraco.Web.UI.NetCore/config/lang/he-IL.user.xml
  src/Umbraco.Web.UI.NetCore/config/lang/it-IT.user.xml
  src/Umbraco.Web.UI.NetCore/config/lang/ja-JP.user.xml
  src/Umbraco.Web.UI.NetCore/config/lang/ko-KR.user.xml
  src/Umbraco.Web.UI.NetCore/config/lang/nb-NO.user.xml
  src/Umbraco.Web.UI.NetCore/config/lang/nl-NL.user.xml
  src/Umbraco.Web.UI.NetCore/config/lang/pl-PL.user.xml
  src/Umbraco.Web.UI.NetCore/config/lang/pt-BR.user.xml
  src/Umbraco.Web.UI.NetCore/config/lang/ru-RU.user.xml
  src/Umbraco.Web.UI.NetCore/config/lang/sv-SE.user.xml
  src/Umbraco.Web.UI.NetCore/config/lang/zh-CN.user.xml
  src/Umbraco.Web.UI.NetCore/config/logviewer.searches.config.js
  src/Umbraco.Web.UI.NetCore/config/tinyMceConfig.Release.config
  src/Umbraco.Web.UI.NetCore/config/tinyMceConfig.config
Labels: project/net-core

#9264 [Issue 5277-146] accessibility - Close 'X' icon next to language drop…
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-content-header.html
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/fr.xml
Labels: hacktoberfest-accepted

#9973 Fix issue with SqlMainDomLock that cannot use implicit lock timeouts …
  src/Umbraco.Core/Configuration/GlobalSettings.cs
  src/Umbraco.Core/Runtime/SqlMainDomLock.cs
Labels: release/8.12.1, status/regression, type/bug

#9970 Netcore: Reintroduce friendly bun untestable published content extensions
  src/Umbraco.Web.Common/DependencyInjection/StaticServiceProvider.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoStartupFilter.cs
  src/Umbraco.Web.Common/Extensions/FriendlyPublishedContentExtensions.cs
  src/Umbraco.Web.Common/Extensions/FriendlyPublishedElementExtensions.cs
  src/Umbraco.Web.Common/Extensions/PublishedContentExtensions.cs
  src/Umbraco.Web.UI.Client/src/common/services/templatehelper.service.js
  src/Umbraco.Web.UI.Client/test/unit/common/services/template-helper.spec.js
Labels: project/net-core

#9273 Including ModelsBuilder.Umbraco in list of external Models Builders
  src/Umbraco.ModelsBuilder.Embedded/Compose/ModelsBuilderComposer.cs
Labels: hacktoberfest-accepted

#9960 Fix dead lock with TypeLoader
  src/Umbraco.Core/Composing/TypeLoader.cs
Labels: type/bug

#9839 Do not apply runtime optimization to core scripts and script libraries
  src/Umbraco.Core/Configuration/Models/ContentSettings.cs
  src/Umbraco.Core/WebAssets/IRuntimeMinifier.cs
  src/Umbraco.Infrastructure/WebAssets/BackOfficeWebAssets.cs
  src/Umbraco.Infrastructure/WebAssets/JsInitialize.js
  src/Umbraco.Infrastructure/WebAssets/PreviewInitialize.js
  src/Umbraco.Infrastructure/WebAssets/RuntimeMinifierExtensions.cs
  src/Umbraco.Web.Common/RuntimeMinification/SmidgeRuntimeMinifier.cs
  src/Umbraco.Web.UI.Client/gulp/config.js
  src/Umbraco.Web.UI.Client/gulp/tasks/dependencies.js
  src/Umbraco.Web.UI.Client/gulp/tasks/js.js
  src/Umbraco.Web.UI.Client/gulp/util/processJs.js
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/install.loader.js
  src/Umbraco.Web.UI.Client/test/config/karma.conf.js
Labels: project/net-core

#9953 Fixes and Updates for DB Scope and Ambient Context leaks
  src/Umbraco.Core/Runtime/SqlMainDomLock.cs
  src/Umbraco.Core/Scoping/Scope.cs
  src/Umbraco.Core/Scoping/ScopeProvider.cs
  src/Umbraco.Examine/UmbracoExamineIndex.cs
  src/Umbraco.Tests/Scoping/ScopeTests.cs
  src/Umbraco.Tests/Services/ThreadSafetyServiceTest.cs
  src/Umbraco.Web/Scheduling/BackgroundTaskRunner.cs
Labels: category/performance, release/8.13.0, type/bug

#9954 Adds additional error checking and reporting to MainDom/SqlMainDomLock
  src/Umbraco.Core/Runtime/MainDom.cs
  src/Umbraco.Core/Runtime/SqlMainDomLock.cs
Labels: category/refactor, release/8.12.2, status/regression, type/feature

#9922 Replace static backoffice user manager events with IEventAggregator notifications
  src/Umbraco.Infrastructure/Configuration/JsonConfigManipulator.cs
  src/Umbraco.Infrastructure/Security/IBackOfficeUserManager.cs
  src/Umbraco.Infrastructure/Security/IUmbracoUserManager.cs
  src/Umbraco.Infrastructure/Security/SignOutAuditEventArgs.cs
  src/Umbraco.Infrastructure/Security/SignOutSuccessResult.cs
  src/Umbraco.Infrastructure/Security/UserInviteEventArgs.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberIdentityUserManagerTests.cs
  src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
  src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
  src/Umbraco.Web.BackOffice/DependencyInjection/ServiceCollectionExtensions.cs
  src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.BackOffice/Extensions/BackOfficeApplicationBuilderExtensions.cs
  src/Umbraco.Web.BackOffice/Security/BackOfficeSignInManager.cs
  src/Umbraco.Web.BackOffice/Security/BackOfficeUserManagerAuditer.cs
  src/Umbraco.Web.Common/Security/BackOfficeUserManager.cs
  src/Umbraco.Web.Common/Security/MemberManager.cs
  src/Umbraco.Web.Common/Security/UserForgotPasswordChangedNotification.cs
  src/Umbraco.Web.Common/Security/UserForgotPasswordRequestedNotification.cs
  src/Umbraco.Web.Common/Security/UserLockedNotification.cs
  src/Umbraco.Web.Common/Security/UserLoginFailedNotification.cs
  src/Umbraco.Web.Common/Security/UserLoginRequiresVerificationNotification.cs
  src/Umbraco.Web.Common/Security/UserLoginSuccessNotification.cs
  src/Umbraco.Web.Common/Security/UserLogoutSuccessNotification.cs
  src/Umbraco.Web.Common/Security/UserNotification.cs
  src/Umbraco.Web.Common/Security/UserPasswordChangedNotification.cs
  src/Umbraco.Web.Common/Security/UserPasswordResetNotification.cs
  src/Umbraco.Web.Common/Security/UserResetAccessFailedCountNotification.cs
  src/Umbraco.Web.Common/Security/UserUnlockedNotification.cs
Labels: project/net-core

#9957 Add copy logic to Media Picker
  src/Umbraco.Web.UI.Client/src/common/services/clipboard.service.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.html
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: category/ux, community/pr, release/8.13.0, type/feature

#9974 Netcore: Migrate cache refresher events to IEventAggregator pattern
  src/Umbraco.Core/Cache/ApplicationCacheRefresher.cs
  src/Umbraco.Core/Cache/ApplicationCacheRefresherNotification.cs
  src/Umbraco.Core/Cache/CacheRefresherBase.cs
  src/Umbraco.Core/Cache/CacheRefresherEventArgs.cs
  src/Umbraco.Core/Cache/CacheRefresherNotification.cs
  src/Umbraco.Core/Cache/CacheRefresherNotificationFactory.cs
  src/Umbraco.Core/Cache/ContentCacheRefresher.cs
  src/Umbraco.Core/Cache/ContentCacheRefresherNotification.cs
  src/Umbraco.Core/Cache/ContentTypeCacheRefresher.cs
  src/Umbraco.Core/Cache/ContentTypeCacheRefresherNotification.cs
  src/Umbraco.Core/Cache/DataTypeCacheRefresher.cs
  src/Umbraco.Core/Cache/DataTypeCacheRefresherNotification.cs
  src/Umbraco.Core/Cache/DictionaryCacheRefresher.cs
  src/Umbraco.Core/Cache/DictionaryCacheRefresherNotification.cs
  src/Umbraco.Core/Cache/DomainCacheRefresher.cs
  src/Umbraco.Core/Cache/DomainCacheRefresherNotification.cs
  src/Umbraco.Core/Cache/ICacheRefresherNotificationFactory.cs
  src/Umbraco.Core/Cache/JsonCacheRefresherBase.cs
  src/Umbraco.Core/Cache/LanguageCacheRefresher.cs
  src/Umbraco.Core/Cache/LanguageCacheRefresherNotification.cs
  src/Umbraco.Core/Cache/MacroCacheRefresher.cs
  src/Umbraco.Core/Cache/MacroCacheRefresherNotification.cs
  src/Umbraco.Core/Cache/MediaCacheRefresher.cs
  src/Umbraco.Core/Cache/MediaCacheRefresherNotification.cs
  src/Umbraco.Core/Cache/MemberCacheRefresher.cs
  src/Umbraco.Core/Cache/MemberCacheRefresherNotification.cs
  src/Umbraco.Core/Cache/MemberGroupCacheRefresher.cs
  src/Umbraco.Core/Cache/MemberGroupCacheRefresherNotification.cs
  src/Umbraco.Core/Cache/PayloadCacheRefresherBase.cs
  src/Umbraco.Core/Cache/PublicAccessCacheRefresher.cs
  src/Umbraco.Core/Cache/PublicAccessCacheRefresherNotification.cs
  src/Umbraco.Core/Cache/RelationTypeCacheRefresher.cs
  src/Umbraco.Core/Cache/RelationTypeCacheRefresherNotification.cs
  src/Umbraco.Core/Cache/TemplateCacheRefresher.cs
  src/Umbraco.Core/Cache/TemplateCacheRefresherNotification.cs
  src/Umbraco.Core/Cache/UserCacheRefresher.cs
  src/Umbraco.Core/Cache/UserCacheRefresherNotification.cs
  src/Umbraco.Core/Cache/UserGroupCacheRefresher.cs
  src/Umbraco.Core/Cache/UserGroupCacheRefresherNotification.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Core/Extensions/ClaimsIdentityExtensions.cs
  src/Umbraco.Core/Security/ClaimsPrincipalExtensions.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Examine.cs
  src/Umbraco.Infrastructure/ModelsBuilder/LiveModelsProvider.cs
  src/Umbraco.Infrastructure/ModelsBuilder/OutOfDateModelsStatus.cs
  src/Umbraco.Infrastructure/Search/ExamineNotificationHandler.cs
  src/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEventsTests.cs
  src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.BackOffice/SignalR/PreviewHubComposer.cs
  src/Umbraco.Web.BackOffice/SignalR/PreviewHubUpdater.cs
  src/Umbraco.Web.Common/ModelsBuilder/DependencyInjection/UmbracoBuilderDependencyInjectionExtensions.cs
  src/Umbraco.Web.Common/Views/UmbracoViewPage.cs
Labels: project/net-core

#9840 Allow serving App_Plugins files to Smidge for minification
  src/Umbraco.Tests.Integration/TestServerTest/UmbracoTestServerTestBase.cs
  src/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
  src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.UI.NetCore/Startup.cs
Labels: project/net-core

#9968 New table and service to store auth tokens
  src/Umbraco.Core/Models/Identity/ExternalLogin.cs
  src/Umbraco.Core/Models/Identity/ExternalLoginToken.cs
  src/Umbraco.Core/Models/Identity/IExternalLoginToken.cs
  src/Umbraco.Core/Models/Identity/IIdentityUserLogin.cs
  src/Umbraco.Core/Models/Identity/IIdentityUserToken.cs
  src/Umbraco.Core/Models/Identity/IdentityUserToken.cs
  src/Umbraco.Core/Persistence/Constants-DatabaseSchema.cs
  src/Umbraco.Core/Persistence/Repositories/IExternalLoginRepository.cs
  src/Umbraco.Core/Services/IExternalLoginService.cs
  src/Umbraco.Infrastructure/Configuration/JsonConfigManipulator.cs
  src/Umbraco.Infrastructure/Migrations/Install/DatabaseBuilder.cs
  src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_9_0_0/ExternalLoginTableIndexes.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_9_0_0/ExternalLoginTokenTable.cs
  src/Umbraco.Infrastructure/Persistence/Dtos/ExternalLoginDto.cs
  src/Umbraco.Infrastructure/Persistence/Dtos/ExternalLoginTokenDto.cs
  src/Umbraco.Infrastructure/Persistence/Factories/ExternalLoginFactory.cs
  src/Umbraco.Infrastructure/Persistence/Mappers/ExternalLoginMapper.cs
  src/Umbraco.Infrastructure/Persistence/Mappers/ExternalLoginTokenMapper.cs
  src/Umbraco.Infrastructure/Persistence/Mappers/MapperCollectionBuilder.cs
  src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/AuditEntryRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/AuditRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ConsentRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentRepositoryBase.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DataTypeRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DictionaryRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DomainRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/EntityContainerRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/EntityRepositoryBase.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ExternalLoginRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/KeyValueRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/LanguageRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/LogViewerQueryRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MacroRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MediaRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberGroupRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/PermissionRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/PublicAccessRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/RedirectUrlRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/RelationRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/RelationTypeRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ServerRegistrationRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/SimpleGetRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/TagRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/TemplateRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/UserGroupRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/UserRepository.cs
  src/Umbraco.Infrastructure/Security/BackOfficeUserStore.cs
  src/Umbraco.Infrastructure/Security/UmbracoIdentityUser.cs
  src/Umbraco.Infrastructure/Services/Implement/ExternalLoginService.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ExternalLoginServiceTests.cs
  src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
  src/Umbraco.Web.BackOffice/Security/IBackOfficeSignInManager.cs
  src/Umbraco.Web.UI.NetCore/appsettings.json
Labels: project/net-core

#9987 Add images in grid - fixes 9982
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/media.controller.js
Labels: release/8.12.2, type/bug

#9902 Update to enable members to use the same password change as users
  src/Umbraco.Core/Models/ChangingPasswordModel.cs
  src/Umbraco.Core/Models/ContentEditing/UserSave.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberRepository.cs
  src/Umbraco.Infrastructure/Security/IUmbracoUserManager.cs
  src/Umbraco.Infrastructure/Security/MembersUserStore.cs
  src/Umbraco.Infrastructure/Security/UmbracoUserManager.cs
  src/Umbraco.Infrastructure/WebAssets/Resources.Designer.cs
  src/Umbraco.Tests.Integration/Umbraco.Core/Packaging/PackageDataInstallationTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/EntityXmlSerializerTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/ImportResources.Designer.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Controllers/MemberControllerUnitTests.cs
  src/Umbraco.Web.BackOffice/Controllers/CurrentUserController.cs
  src/Umbraco.Web.BackOffice/Controllers/MemberController.cs
  src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
  src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.BackOffice/Security/IPasswordChanger.cs
  src/Umbraco.Web.BackOffice/Security/PasswordChanger.cs
  src/Umbraco.Web.UI.NetCore/umbraco/UmbracoInstall/Index.cshtml
  src/Umbraco.Web/AspNet/AspNetPasswordHasher.cs
Labels: project/net-core

#9951 Netcore: create service/repo and remove SQL calls from DatabaseServerMessenger
  src/Umbraco.Core/Models/CacheInstruction.cs
  src/Umbraco.Core/Persistence/Repositories/ICacheInstructionRepository.cs
  src/Umbraco.Core/Services/CacheInstructionServiceProcessInstructionsResult.cs
  src/Umbraco.Core/Services/ICacheInstructionService.cs
  src/Umbraco.Core/Sync/RefreshInstruction.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Repositories.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Services.cs
  src/Umbraco.Infrastructure/Persistence/Factories/CacheInstructionFactory.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/CacheInstructionRepository.cs
  src/Umbraco.Infrastructure/Services/Implement/AuditService.cs
  src/Umbraco.Infrastructure/Services/Implement/CacheInstructionService.cs
  src/Umbraco.Infrastructure/Services/Implement/ConsentService.cs
  src/Umbraco.Infrastructure/Services/Implement/ContentTypeServiceBase.cs
  src/Umbraco.Infrastructure/Services/Implement/DataTypeService.cs
  src/Umbraco.Infrastructure/Services/Implement/DomainService.cs
  src/Umbraco.Infrastructure/Services/Implement/EntityService.cs
  src/Umbraco.Infrastructure/Services/Implement/ExternalLoginService.cs
  src/Umbraco.Infrastructure/Services/Implement/FileService.cs
  src/Umbraco.Infrastructure/Services/Implement/LocalizationService.cs
  src/Umbraco.Infrastructure/Services/Implement/MacroService.cs
  src/Umbraco.Infrastructure/Services/Implement/MediaService.cs
  src/Umbraco.Infrastructure/Services/Implement/MemberService.cs
  src/Umbraco.Infrastructure/Services/Implement/PublicAccessService.cs
  src/Umbraco.Infrastructure/Services/Implement/RedirectUrlService.cs
  src/Umbraco.Infrastructure/Services/Implement/RelationService.cs
  src/Umbraco.Infrastructure/Services/Implement/ScopeRepositoryService.cs
  src/Umbraco.Infrastructure/Services/Implement/ServerRegistrationService.cs
  src/Umbraco.Infrastructure/Services/Implement/TagService.cs
  src/Umbraco.Infrastructure/Services/Implement/UserService.cs
  src/Umbraco.Infrastructure/Sync/BatchedDatabaseServerMessenger.cs
  src/Umbraco.Infrastructure/Sync/DatabaseServerMessenger.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/CacheInstructionRepositoryTest.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/CacheInstructionServiceTests.cs
Labels: project/net-core

#9996 Events to Notifications Migration: Packaging Service
  src/Umbraco.Core/Events/CancelableEnumerableObjectNotification.cs
  src/Umbraco.Core/Events/CancelableObjectNotification.cs
  src/Umbraco.Core/Events/CopiedNotification.cs
  src/Umbraco.Core/Events/CopyingNotification.cs
  src/Umbraco.Core/Events/DeletedNotification.cs
  src/Umbraco.Core/Events/EnumerableObjectNotification.cs
  src/Umbraco.Core/Events/EventAggregator.cs
  src/Umbraco.Core/Events/IEventAggregator.cs
  src/Umbraco.Core/Events/ImportPackageEventArgs.cs
  src/Umbraco.Core/Events/ImportedPackageNotification.cs
  src/Umbraco.Core/Events/ImportingPackageNotification.cs
  src/Umbraco.Core/Events/MovedNotification.cs
  src/Umbraco.Core/Events/MovingNotification.cs
  src/Umbraco.Core/Events/ObjectNotification.cs
  src/Umbraco.Core/Events/RolledBackNotification.cs
  src/Umbraco.Core/Events/RollingBackNotification.cs
  src/Umbraco.Core/Events/SavedNotification.cs
  src/Umbraco.Core/Events/SavingNotification.cs
  src/Umbraco.Core/Events/SortedNotification.cs
  src/Umbraco.Core/Events/SortingNotification.cs
  src/Umbraco.Core/Events/StatefulNotification.cs
  src/Umbraco.Core/Events/UnattendedInstallNotification.cs
  src/Umbraco.Core/Events/UninstallPackageEventArgs.cs
  src/Umbraco.Core/Events/UninstallPackageNotification.cs
  src/Umbraco.Infrastructure/RuntimeState.cs
  src/Umbraco.Infrastructure/Services/Implement/PackagingService.cs
  src/Umbraco.Infrastructure/Services/Notifications/ContentNotificationExtensions.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Install/CreateUnattendedUserNotificationHandler.cs
Labels: project/net-core

#9990 Ability to have an in-memory runtime minifier cache and configurable cache busters
  src/Umbraco.Core/Configuration/Models/RuntimeMinificationCacheBuster.cs
  src/Umbraco.Core/Configuration/Models/RuntimeMinificationSettings.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
  src/Umbraco.Core/WebAssets/IRuntimeMinifier.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.WebAssets.cs
  src/Umbraco.Infrastructure/WebAssets/BackOfficeWebAssets.cs
  src/Umbraco.Infrastructure/WebAssets/WebAssetsComponent.cs
  src/Umbraco.Infrastructure/WebAssets/WebAssetsComposer.cs
  src/Umbraco.Tests.Integration/TestServerTest/UmbracoTestServerTestBase.cs
  src/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
  src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Middleware/UmbracoRequestMiddleware.cs
  src/Umbraco.Web.Common/RuntimeMinification/SmidgeComposer.cs
  src/Umbraco.Web.Common/RuntimeMinification/SmidgeNuglifyJs.cs
  src/Umbraco.Web.Common/RuntimeMinification/SmidgeOptionsSetup.cs
  src/Umbraco.Web.Common/RuntimeMinification/SmidgeRuntimeMinifier.cs
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.NetCore/Startup.cs
  src/Umbraco.Web.UI.NetCore/Views/_ViewImports.cshtml
  src/Umbraco.Web.UI.NetCore/appsettings.Development.json
Labels: project/net-core

#9885 Netcore: Update code docs generation
  build/azure-pipelines.yml
  src/ApiDocs/docfx.filter.yml
  src/ApiDocs/docfx.json
  src/ApiDocs/index.md
  src/ApiDocs/toc.yml
  src/ApiDocs/umbracotemplate/partials/navbar.tmpl.partial
  src/Umbraco.Core/Models/Membership/EntityPermissionSet.cs
  src/Umbraco.Infrastructure/Logging/Serilog/Enrichers/HttpRequestIdEnricher.cs
  src/Umbraco.Infrastructure/Logging/Serilog/Enrichers/HttpRequestNumberEnricher.cs
  src/Umbraco.Infrastructure/Logging/Serilog/Enrichers/HttpSessionIdEnricher.cs
  src/Umbraco.Infrastructure/Logging/Serilog/SerilogLogger.cs
  src/Umbraco.Infrastructure/Logging/Viewer/ILogViewer.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/IDocumentRepository.cs
  src/Umbraco.Web.Common/ApplicationModels/VirtualPageApplicationModelProvider.cs
  src/Umbraco.Web.Common/Controllers/IVirtualPageController.cs
  src/Umbraco.Web.Common/Filters/UmbracoVirtualPageFilterAttribute.cs
Labels: project/net-core

#9266 8539: Allow underscore in alias of image cropper property
  src/Umbraco.Core/StringExtensions.cs
  src/Umbraco.Web.UI.Client/src/common/services/umbrequesthelper.service.js
  src/Umbraco.Web/Editors/Binders/ContentModelBinderHelper.cs
Labels: hacktoberfest-accepted

#9977 Made recurring hosted service base class PerformExecuteAsync method public.
  src/Umbraco.Infrastructure/HostedServices/HealthCheckNotifier.cs
  src/Umbraco.Infrastructure/HostedServices/KeepAlive.cs
  src/Umbraco.Infrastructure/HostedServices/LogScrubber.cs
  src/Umbraco.Infrastructure/HostedServices/RecurringHostedServiceBase.cs
  src/Umbraco.Infrastructure/HostedServices/ReportSiteTask.cs
  src/Umbraco.Infrastructure/HostedServices/ScheduledPublishing.cs
  src/Umbraco.Infrastructure/HostedServices/ServerRegistration/InstructionProcessTask.cs
  src/Umbraco.Infrastructure/HostedServices/ServerRegistration/TouchServerTask.cs
  src/Umbraco.Infrastructure/HostedServices/TempFileCleanup.cs
Labels: project/net-core

#9980 Add gulp comments and sourcemap dependencies
  src/Umbraco.Web.UI.Client/gulp/tasks/dependencies.js
  src/Umbraco.Web.UI.Client/gulp/tasks/js.js
  src/Umbraco.Web.UI.Client/gulp/util/processJs.js
Labels: project/net-core

#10001 #9843 - Allow install with DB string pre-configured
  src/Umbraco.Infrastructure/Cache/DatabaseServerMessengerNotificationHandler.cs
Labels: project/net-core

#10012 Netcore: Separate NuGet package for the static assets
  build/NuSpecs/UmbracoCms.StaticAssets.nuspec
  build/NuSpecs/UmbracoCms.nuspec
  build/NuSpecs/build/Umbraco.Cms.StaticAssets.props
  build/NuSpecs/build/Umbraco.Cms.StaticAssets.targets
  build/build.ps1
  src/Umbraco.Infrastructure/Search/ExamineFinalComponent.cs
  src/Umbraco.Infrastructure/Search/ExamineFinalComposer.cs
  src/Umbraco.Infrastructure/Search/ExamineNotificationHandler.cs
  src/umbraco.sln
Labels: project/net-core

#9979 Scope locking rework
  src/Umbraco.Core/Scoping/Scope.cs
  src/Umbraco.Tests/Scoping/ScopeUnitTests.cs
Labels: category/performance

#10024 Netcore: Added TreeAlias to TreeNodesRenderingNotification
  src/Umbraco.Web.BackOffice/Trees/TreeControllerBase.cs
  src/Umbraco.Web.BackOffice/Trees/TreeNodesRenderingNotification.cs
Labels: community/review, project/net-core

#9889 Improve performance, readability and handling of FollowInternalRedirects
  src/Umbraco.Web/Routing/PublishedRouter.cs
Labels: category/performance, community/review

#9256 9097 add contextual password helper
  src/Umbraco.Web.UI.Client/src/common/directives/components/application/umblogin.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbpasswordtip.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/users/changepassword.directive.js
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-login.html
  src/Umbraco.Web.UI.Client/src/views/components/users/change-password.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/changepassword/changepassword.controller.js
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/fr.xml
  src/Umbraco.Web/Editors/BackOfficeServerVariables.cs
Labels: hacktoberfest-accepted

#10042 Netcore: Fix no authentication schema was specified bugs
  src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
  src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
Labels: project/net-core

#10028 Do not apply runtime optimization to core CSS and CSS libraries
  src/Umbraco.Infrastructure/WebAssets/BackOfficeWebAssets.cs
  src/Umbraco.Web.UI.Client/gulp/config.js
  src/Umbraco.Web.UI.Client/gulp/tasks/dependencies.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbcolorpicker.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbdatetimepicker.directive.js
  src/Umbraco.Web.UI.Client/src/index.html
  src/Umbraco.Web.UI.Client/src/views/content/umbpreview.html
  src/Umbraco.Web.UI.NetCore/umbraco/UmbracoInstall/Index.cshtml
Labels: project/net-core

#10044 Netcore: Run acceptance tests on azure pipelines
  build/azure-pipelines.yml
  src/Umbraco.Tests.AcceptanceTest/cypress.json
  src/Umbraco.Tests.AcceptanceTest/cypress/integration/Settings/languages.ts
  src/Umbraco.Tests.AcceptanceTest/cypress/integration/Settings/templates.ts
  src/Umbraco.Tests.AcceptanceTest/cypress/plugins/index.js
  src/Umbraco.Tests.AcceptanceTest/package.json
  src/Umbraco.Web.UI.NetCore/Properties/launchSettings.json
Labels: project/net-core

#10059 Added `TreeAlias` to tree notifications
  src/Umbraco.Web.BackOffice/Trees/MenuRenderingNotification.cs
  src/Umbraco.Web.BackOffice/Trees/RootNodeRenderingNotification.cs
  src/Umbraco.Web.BackOffice/Trees/TreeControllerBase.cs
Labels: project/net-core, release/netcore-beta001

#9999 Granting access to the content dashboard for all user groups
  src/Umbraco.Core/ConfigsExtensions.cs
  src/Umbraco.Core/Configuration/GlobalSettings.cs
  src/Umbraco.Core/Constants-AppSettings.cs
  src/Umbraco.Core/Dashboards/ContentDashboardSettings.cs
  src/Umbraco.Core/Dashboards/IContentDashboardSettings.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Web.UI/web.Template.config
  src/Umbraco.Web/Dashboards/ContentDashboard.cs
  src/Umbraco.Web/Editors/DashboardController.cs
Labels: release/8.13.0, type/feature

#9033 Add Root<T> and Breadcrumbs extension methods for IPublishedContent
  src/Umbraco.Web/PublishedContentExtensions.cs
Labels: hacktoberfest-accepted

#9946 Member group (identity role) and store
  .gitignore
  src/Umbraco.Core/Models/Mapping/MemberTabsAndPropertiesMapper.cs
  src/Umbraco.Core/Services/IMemberGroupService.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberRepository.cs
  src/Umbraco.Infrastructure/Security/IMemberManager.cs
  src/Umbraco.Infrastructure/Security/IdentityMapDefinition.cs
  src/Umbraco.Infrastructure/Security/MemberIdentityBuilder.cs
  src/Umbraco.Infrastructure/Security/MemberIdentityOptions.cs
  src/Umbraco.Infrastructure/Security/MemberIdentityUser.cs
  src/Umbraco.Infrastructure/Security/MemberRoleStore.cs
  src/Umbraco.Infrastructure/Security/MemberRolesUserStore.cs
  src/Umbraco.Infrastructure/Security/MemberUserStore.cs
  src/Umbraco.Infrastructure/Security/UmbracoIdentityRole.cs
  src/Umbraco.Infrastructure/Security/UmbracoIdentityUser.cs
  src/Umbraco.Infrastructure/Services/Implement/MemberGroupService.cs
  src/Umbraco.Tests.Common/Builders/Extensions/BuilderExtensions.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithIdBuilder.cs
  src/Umbraco.Tests.Common/Builders/UmbracoIdentityRoleBuilder.cs
  src/Umbraco.Tests.Common/Builders/UserBuilder.cs
  src/Umbraco.Tests.Integration/Umbraco.Web.Common/MembersServiceCollectionExtensionsTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberIdentityUserManagerTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberIdentityUserStoreTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberRoleStoreTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberUserStoreTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Controllers/MemberControllerUnitTests.cs
  src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
  src/Umbraco.Web.BackOffice/Controllers/MemberController.cs
  src/Umbraco.Web.BackOffice/Controllers/MemberGroupController.cs
  src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.BackOffice/Mapping/MemberMapDefinition.cs
  src/Umbraco.Web.BackOffice/Trees/MemberGroupTreeController.cs
  src/Umbraco.Web.Common/DependencyInjection/ServiceCollectionExtensions.cs
  src/Umbraco.Web.Common/Extensions/IdentityBuilderExtensions.cs
  src/Umbraco.Web.Common/Security/MemberManager.cs
  src/Umbraco.Web/Security/Providers/MembersRoleProvider.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: project/net-core

#10070 Remove static events from MemberGroupService
  src/Umbraco.Infrastructure/Cache/DistributedCacheBinder_Handlers.cs
  src/Umbraco.Infrastructure/Compose/PublicAccessComposer.cs
  src/Umbraco.Infrastructure/Compose/PublicAccessHandler.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberGroupRepository.cs
  src/Umbraco.Infrastructure/Services/Implement/MemberGroupService.cs
  src/Umbraco.Infrastructure/Services/Notifications/MemberGroupDeletedNotification.cs
  src/Umbraco.Infrastructure/Services/Notifications/MemberGroupDeletingNotification.cs
  src/Umbraco.Infrastructure/Services/Notifications/MemberGroupSavedNotification.cs
  src/Umbraco.Infrastructure/Services/Notifications/MemberGroupSavingNotification.cs
  src/Umbraco.Tests.Integration/Cache/DistributedCacheBinderTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Scoping/ScopedRepositoryTests.cs
Labels: project/net-core

#8639 Allow to pass in boolean to preventEnterSubmit directive
  src/Umbraco.Web.UI.Client/src/common/directives/components/forms/prevententersubmit.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbsearchfilter.directive.js
  src/Umbraco.Web.UI.Client/src/less/components/umb-search-filter.less
  src/Umbraco.Web.UI.Client/src/views/components/forms/umb-search-filter.html
Labels: state/needs-investigation
