Repository umbraco/Umbraco-CMS, pull requests merged in 2021-11, with the labels that each got.

#11544 Making UmbracoTreeSearcherFields virtual for easier overriding
  src/Umbraco.Web/Search/UmbracoTreeSearcherFields.cs
Labels: hacktoberfest-accepted

#10653 Additional optional sanitization of scripting in TinyMCE
  src/Umbraco.Core/Configuration/GlobalSettings.cs
  src/Umbraco.Core/Configuration/IGlobalSettings.cs
  src/Umbraco.Core/Constants-AppSettings.cs
  src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
  src/Umbraco.Web.UI/web.Template.config
  src/Umbraco.Web/Editors/BackOfficeServerVariables.cs
Labels: type/feature, release/8.18.0, release/9.1.0

#11378 Published Content Query has "skip" applied twice
  src/Umbraco.Examine.Lucene/BackOfficeExamineSearcher.cs
  src/Umbraco.Infrastructure/Examine/ExamineUmbracoIndexingHandler.cs
  src/Umbraco.Infrastructure/PublishedContentQuery.cs
  src/Umbraco.Web.BackOffice/Controllers/ExamineManagementController.cs
Labels: hacktoberfest-accepted

#11524 v9: don't reload page when navigating to edit user
  src/Umbraco.Web.UI.Client/src/views/common/overlays/user/user.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/overlays/user/user.html
Labels: type/bug, release/9.1.0

#11466 Add missing fallback texts in various views
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.html
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-login.html
  src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html
  src/Umbraco.Web.UI.Client/src/views/components/content/umb-tabbed-content.html
  src/Umbraco.Web.UI.Client/src/views/components/content/umb-variant-content.html
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-content-header.html
  src/Umbraco.Web.UI.Client/src/views/components/elementeditor/umb-element-editor-content.component.html
  src/Umbraco.Web.UI.Client/src/views/components/media/umb-media-node-info.html
  src/Umbraco.Web.UI.Client/src/views/components/mediacard/umb-media-card.html
  src/Umbraco.Web.UI.Client/src/views/components/property/umb-property.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-child-selector.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-table.html
  src/Umbraco.Web.UI.Client/src/views/components/upload/umb-file-dropzone.html
  src/Umbraco.Web.UI.Client/src/views/content/notify.html
  src/Umbraco.Web.UI.Client/src/views/content/rights.html
  src/Umbraco.Web.UI.Client/src/views/dashboard/content/redirecturls.html
  src/Umbraco.Web.UI.Client/src/views/documenttypes/views/templates/templates.html
  src/Umbraco.Web.UI.Client/src/views/languages/edit.html
  src/Umbraco.Web.UI.Client/src/views/languages/overlays/delete.html
  src/Umbraco.Web.UI.Client/src/views/macros/infiniteeditors/parameter.html
  src/Umbraco.Web.UI.Client/src/views/mediatypes/create.html
  src/Umbraco.Web.UI.Client/src/views/mediatypes/views/listview/listview.html
  src/Umbraco.Web.UI.Client/src/views/membertypes/create.html
  src/Umbraco.Web.UI.Client/src/views/partialviewmacros/create.html
  src/Umbraco.Web.UI.Client/src/views/partialviews/create.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/list/list.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/overlays/delete.html
  src/Umbraco.Web.UI.Client/src/views/relationtypes/create.html
  src/Umbraco.Web.UI.Client/src/views/stylesheets/create.html
  src/Umbraco.Web.UI.Client/src/views/users/views/groups/groups.html
Labels: hacktoberfest-accepted

#11527 Move language tests
  src/Umbraco.Tests.AcceptanceTest/cypress/integration/Languages/languages.ts
Labels: hacktoberfest-accepted

#11495 Version history cleanup
  src/Umbraco.Core/Composing/CompositionExtensions/Repositories.cs
  src/Umbraco.Core/Composing/CompositionExtensions/Services.cs
  src/Umbraco.Core/Configuration/UmbracoSettings/ContentElement.cs
  src/Umbraco.Core/Configuration/UmbracoSettings/ContentVersionCleanupPolicyGlobalSettingsElement.cs
  src/Umbraco.Core/Configuration/UmbracoSettings/IContentSection.cs
  src/Umbraco.Core/Configuration/UmbracoSettings/IContentVersionCleanupPolicyGlobalSettings.cs
  src/Umbraco.Core/Migrations/Install/DatabaseSchemaCreator.cs
  src/Umbraco.Core/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Core/Migrations/Upgrade/V_8_18_0/AddContentVersionCleanupFeature.cs
  src/Umbraco.Core/Models/ContentEditing/HistoryCleanup.cs
  src/Umbraco.Core/Models/ContentType.cs
  src/Umbraco.Core/Models/ContentVersionCleanupPolicySettings.cs
  src/Umbraco.Core/Models/HistoricContentVersionMeta.cs
  src/Umbraco.Core/Models/IContentType.cs
  src/Umbraco.Core/Persistence/Constants-DatabaseSchema.cs
  src/Umbraco.Core/Persistence/Dtos/ContentVersionCleanupPolicyDto.cs
  src/Umbraco.Core/Persistence/Dtos/ContentVersionDto.cs
  src/Umbraco.Core/Persistence/Repositories/IDocumentVersionRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeCommonRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/DocumentRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/DocumentVersionRepository.cs
  src/Umbraco.Core/Services/IContentVersionCleanupPolicy.cs
  src/Umbraco.Core/Services/IContentVersionService.cs
  src/Umbraco.Core/Services/Implement/ContentService.cs
  src/Umbraco.Core/Services/Implement/DefaultContentVersionCleanupPolicy.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests/Configurations/UmbracoSettings/umbracoSettings.config
  src/Umbraco.Tests/Persistence/Repositories/ContentTypeRepositoryTest.cs
  src/Umbraco.Tests/Persistence/Repositories/DocumentVersionRepository_Tests_Integration.cs
  src/Umbraco.Tests/Scheduling/ContentVersionCleanup_Tests_UnitTests.cs
  src/Umbraco.Tests/Services/ContentTypeServiceVariantsTests.cs
  src/Umbraco.Tests/Services/ContentVersionCleanupService_Tests_Integration.cs
  src/Umbraco.Tests/Services/ContentVersionCleanupService_Tests_UnitTests.cs
  src/Umbraco.Tests/Services/DefaultContentVersionCleanupPolicy_Tests_UnitTests.cs
  src/Umbraco.Tests/TestHelpers/Entities/MockedContent.cs
  src/Umbraco.Tests/TestHelpers/Entities/MockedContentTypes.cs
  src/Umbraco.Tests/Testing/AutoMoqDataAttribute.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/src/common/services/umbdataformatter.service.js
  src/Umbraco.Web.UI.Client/src/views/documenttypes/views/permissions/permissions.controller.js
  src/Umbraco.Web.UI.Client/src/views/documenttypes/views/permissions/permissions.html
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
  src/Umbraco.Web.UI/config/umbracoSettings.Release.config
  src/Umbraco.Web/Models/ContentEditing/ContentTypeSave.cs
  src/Umbraco.Web/Models/ContentEditing/DocumentTypeDisplay.cs
  src/Umbraco.Web/Models/ContentEditing/HistoryCleanup.cs
  src/Umbraco.Web/Models/Mapping/ContentTypeMapDefinition.cs
  src/Umbraco.Web/Scheduling/ContentVersionCleanup.cs
  src/Umbraco.Web/Scheduling/SchedulerComponent.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: type/feature, release/8.18.0, release/9.1.0

#11528 v9: Create new 'delete stylesheet' cypress test
  tests/Umbraco.Tests.AcceptanceTest/cypress/integration/Settings/stylesheets.ts
Labels: hacktoberfest-accepted

#11406 v9: Use localization keys instead of hardcoded string
  src/Umbraco.Web.UI.Client/src/views/common/drawers/help/help.controller.js
  src/Umbraco.Web.UI/umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
Labels: project/v9, type/bug, hacktoberfest-accepted

#11571 v9: Implemented new routing tests
  tests/Umbraco.Tests.AcceptanceTest/cypress/integration/Content/routing.ts
  tests/Umbraco.Tests.AcceptanceTest/package-lock.json
  tests/Umbraco.Tests.AcceptanceTest/package.json
Labels: category/acceptance-tests

#11579 Allow .map files as default browsable file extensions from the App_Pl…
  src/Umbraco.Core/Configuration/Models/UmbracoPluginSettings.cs
Labels: type/bug

#11556 Hide localization key while loading
  src/Umbraco.Web.UI.Client/src/common/directives/components/localization/localize.directive.js
Labels: community/pr, category/ux, type/feature, hacktoberfest-accepted, release/8.18.0, hacktoberfest/contrib-2021

#11304 Add support for media saving messages in dropzone
  src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbfiledropzone.directive.js
  src/Umbraco.Web.UI.Client/src/less/components/umb-file-dropzone.less
  src/Umbraco.Web.UI.Client/src/views/components/upload/umb-file-dropzone.html
Labels: community/pr, type/feature, hacktoberfest-accepted, hacktoberfest/contrib-2021, release/9.2.0

#11529 v9: Update 'User' Cypress tests
  tests/Umbraco.Tests.AcceptanceTest/cypress/integration/Users/users.ts
Labels: hacktoberfest-accepted

#6890 Update styling of log viewer
  src/Umbraco.Web.UI.Client/src/views/logviewer/search.html
Labels: community/pr, category/ui, type/feature, release/8.18.0

#11462 Update docs for localize.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/localization/localize.directive.js
Labels: hacktoberfest-accepted

#11341 Replace .first() with localize in acceptance-tests
  tests/Umbraco.Tests.AcceptanceTest/cypress/integration/Settings/mediaTypes.ts
  tests/Umbraco.Tests.AcceptanceTest/cypress/integration/Settings/partialsViewMacroFiles.ts
  tests/Umbraco.Tests.AcceptanceTest/cypress/integration/Settings/partialsViews.ts
  tests/Umbraco.Tests.AcceptanceTest/cypress/integration/Settings/scripts.ts
Labels: community/pr, category/acceptance-tests, hacktoberfest-accepted, hacktoberfest/contrib-2021, release/9.2.0

#11555 Updates to Media Selection list view to better match Grid View
  src/Umbraco.Web.UI.Client/src/less/components/umb-media-grid.less
  src/Umbraco.Web.UI.Client/src/views/components/umb-media-grid.html
Labels: community/pr, category/ux, hacktoberfest-accepted, release/8.18.0, hacktoberfest/contrib-2021

#11616 List: Add missing fallback texts
  src/Umbraco.Web.UI.Client/src/views/dictionary/list.html
Labels: community/pr, category/ux, type/bug, release/8.18.0

#11545 Updating fr.xml translation file
  src/Umbraco.Web.UI/Umbraco/config/lang/fr.xml
Labels: community/pr, category/ux, hacktoberfest-accepted, release/8.18.0, hacktoberfest/contrib-2021

#11577 V9: Fix granular permissions for user groups
  src/Umbraco.Core/Handlers/AuditNotificationsHandler.cs
  src/Umbraco.Core/Models/ContentEditing/UserGroupPermissionsSave.cs
  src/Umbraco.Core/Persistence/Constants-DatabaseSchema.cs
  src/Umbraco.Core/Services/UserServiceExtensions.cs
  src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_9_2_0/AddUserGroup2NodeTable.cs
  src/Umbraco.Infrastructure/Persistence/Dtos/UserGroup2NodeDto.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MediaRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberGroupRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/PermissionRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/TemplateRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/UserGroupRepository.cs
  src/Umbraco.Infrastructure/Services/Implement/UserService.cs
  src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
  src/Umbraco.Web.UI.Client/src/views/content/content.rights.controller.js
  src/Umbraco.Web.UI.Client/src/views/users/group.controller.js
Labels: project/v9, type/bug

#11636 Migrated / Rewritten ScopedNuCacheTests
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Scoping/ScopedNuCacheTests.cs
  tests/Umbraco.Tests/Scoping/ScopedNuCacheTests.cs
Labels: project/v9, type/feature

#11557 Fix optional id route param inferred as FromQuery
  src/Umbraco.Web.Common/ApplicationModels/UmbracoApiBehaviorApplicationModelProvider.cs
  src/Umbraco.Web.Common/ApplicationModels/UmbracoJsonModelBinderConvention.cs
Labels: hacktoberfest-accepted

#11652 Update to .NET6 and ASP.NET Core 6
  build/NuSpecs/UmbracoCms.nuspec
  build/azure-pipelines.yml
  build/templates/UmbracoPackage/.template.config/template.json
  build/templates/UmbracoPackage/UmbracoPackage.csproj
  build/templates/UmbracoProject/.template.config/template.json
  build/templates/UmbracoProject/UmbracoProject.csproj
  src/JsonSchema/JsonSchema.csproj
  src/Umbraco.Core/Extensions/EnumerableExtensions.cs
  src/Umbraco.Core/Packaging/PackagesRepository.cs
  src/Umbraco.Core/Routing/UrlProviderExtensions.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
  src/Umbraco.Infrastructure/Manifest/ManifestParser.cs
  src/Umbraco.Infrastructure/Migrations/Expressions/Delete/KeysAndIndexes/DeleteKeysAndIndexesBuilder.cs
  src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ExternalLoginRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberGroupRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/UserRepository.cs
  src/Umbraco.Infrastructure/Services/Implement/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.Persistence.SqlCe/Umbraco.Persistence.SqlCe.csproj
  src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
  src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  src/Umbraco.Web.Website/Umbraco.Web.Website.csproj
  tests/Umbraco.TestData/Umbraco.TestData.csproj
  tests/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
  tests/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
  tests/Umbraco.Tests.Integration.SqlCe/Umbraco.Tests.Integration.SqlCe.csproj
  tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Published/ModelTypeTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
  tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Routing/TestRouteBuilder.cs
Labels: project/v10

#11481 Ensure crop size in shown for slim thumbnails
  src/Umbraco.Web.UI.Client/src/less/property-editors.less
  src/Umbraco.Web.UI.Client/src/views/components/imaging/umb-image-crop.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.prevalues.html
Labels: hacktoberfest-accepted

#7943 #7902 displaying messages on cancelled item creation
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
Labels: community/pr, category/ux, type/bug, release/8.18.0

#10303 fixes #9894 . Truncate block editor model title to 100 chars.
  src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorheader.directive.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockeditor/blockeditor.html
Labels: community/pr, category/ux, type/bug, release/8.18.0

#11027 Fix typo
  src/Umbraco.Web.UI.Client/src/common/directives/util/getDomElement.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/util/retrieveDomElement.directive.js
  src/Umbraco.Web.UI.Client/src/common/resources/auth.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/contenttype.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/datatype.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/log.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/logviewer.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/mediatype.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/redirecturls.resource.js
  src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
  src/Umbraco.Web.UI.Client/src/common/services/clipboard.service.js
  src/Umbraco.Web.UI.Client/src/common/services/tree.service.js
  src/Umbraco.Web.UI.Client/src/views/prevalueeditors/mediafolderpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker3/umbMediaPicker3PropertyEditor.component.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
Labels: community/pr, type/bug, release/8.18.0

#10597 Fix the introduction tour getting lost if dashboard is not shown
  src/Umbraco.Web.UI/config/BackOfficeTours/getting-started.json
Labels: type/bug, release/8.18.0

#11681 V9/feature/merge v8 22/11/2021
  src/Umbraco.Web.UI.Client/src/common/directives/components/localization/localize.directive.js
Labels: release/9.2.0

#11435 Focus lock improvements
  src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbfocuslock.directive.js
Labels: hacktoberfest-accepted

#11660 Support import/export for doc type history cleanup policy
  src/Umbraco.Core/Models/ContentEditing/HistoryCleanup.cs
  src/Umbraco.Core/Models/IContentType.cs
  src/Umbraco.Core/Packaging/PackageDataInstallation.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepository.cs
  src/Umbraco.Core/Services/Implement/EntityXmlSerializer.cs
  src/Umbraco.Tests/Packaging/PackageDataInstallationTests.cs
  src/Umbraco.Tests/Services/Importing/ImportResources.Designer.cs
  src/Umbraco.Tests/Services/Importing/ImportResources.resx
  src/Umbraco.Tests/Services/Importing/SingleDocType-WithCleanupPolicy.xml
  src/Umbraco.Tests/Umbraco.Tests.csproj
  src/Umbraco.Web.UI.Client/src/views/documenttypes/views/permissions/permissions.html
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
  src/Umbraco.Web/Models/Mapping/ContentTypeMapDefinition.cs
Labels: release/8.18.0

#11632 Apply pickDate-config setting to hide calendar in datepicker
  src/Umbraco.Web.UI.Client/src/views/logviewer/search.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/datepicker/datepicker.controller.js
Labels: community/pr, category/ui, type/feature, release/8.18.0

#11349 Update to SixLabors.ImageSharp.Web 1.0.4 and remove processing order workarounds
  src/Umbraco.Infrastructure/Media/ImageSharpImageUrlGenerator.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilder.ImageSharp.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/ImageCropperTest.cs
Labels: project/v9, type/feature, release/9.2.0

#11587 Move member properties to Member Content App
  src/Umbraco.Core/Constants-Conventions.cs
  src/Umbraco.Core/Migrations/Install/DatabaseDataCreator.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeCommonRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/MemberTypeRepository.cs
  src/Umbraco.Core/Services/Implement/MemberService.cs
  src/Umbraco.Tests/Persistence/Repositories/MemberTypeRepositoryTest.cs
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js
  src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js
  src/Umbraco.Web.UI.Client/src/common/services/umbdataformatter.service.js
  src/Umbraco.Web.UI.Client/src/views/components/member/umb-member-node-info.html
  src/Umbraco.Web.UI.Client/src/views/components/member/umb-membergroup-node-info.html
  src/Umbraco.Web.UI.Client/src/views/member/apps/content/content.controller.js
  src/Umbraco.Web.UI.Client/src/views/member/apps/content/content.html
  src/Umbraco.Web.UI.Client/src/views/member/apps/membership/membership.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/boolean/boolean.html
  src/Umbraco.Web/ContentApps/MemberEditorContentAppFactory.cs
  src/Umbraco.Web/Models/ContentEditing/MemberDisplay.cs
  src/Umbraco.Web/Models/Mapping/MemberMapDefinition.cs
  src/Umbraco.Web/Models/Mapping/MemberTabsAndPropertiesMapper.cs
  src/Umbraco.Web/Models/Mapping/TabsAndPropertiesMapper.cs
  src/Umbraco.Web/Runtime/WebInitialComposer.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: project/members, type/bug

#11685 Bugfixes for MNTP / EntityController
  src/Umbraco.Core/Constants-HttpContextItemsKeys.cs
  src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
  src/Umbraco.Web.BackOffice/Controllers/ParameterSwapControllerActionSelectorAttribute.cs
  src/Umbraco.Web.BackOffice/ModelBinders/FromJsonPathAttribute.cs
  src/Umbraco.Web.UI.Client/src/common/mocks/resources/entity.mocks.js
  src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js
  tests/Umbraco.Tests.Integration/Umbraco.Web.BackOffice/Controllers/EntityControllerTests.cs
Labels: release/9.1.2
