Repository umbraco/Umbraco-CMS, pull requests merged in 2021-01, with the labels that each got.

#9604 Reverts button type change in media edit
  src/Umbraco.Web.UI.Client/src/views/media/edit.html
Labels: category/ux, type/bug

#9482 Add support for unattended installs
  src/Umbraco.Core/Exceptions/UnattendedInstallException.cs
  src/Umbraco.Core/Migrations/Install/DatabaseBuilder.cs
  src/Umbraco.Core/Migrations/Install/DatabaseSchemaCreator.cs
  src/Umbraco.Core/Migrations/Install/DatabaseSchemaResult.cs
  src/Umbraco.Core/Persistence/UmbracoDatabaseExtensions.cs
  src/Umbraco.Core/Runtime/CoreRuntime.cs
  src/Umbraco.Core/Runtime/SqlMainDomLock.cs
  src/Umbraco.Core/RuntimeOptions.cs
  src/Umbraco.Core/RuntimeState.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests/Runtimes/CoreRuntimeTests.cs
  src/Umbraco.Tests/Runtimes/StandaloneTests.cs
  src/Umbraco.Web/Install/InstallHelper.cs
  src/Umbraco.Web/Install/InstallSteps/NewInstallStep.cs
  src/Umbraco.Web/UmbracoApplication.cs
Labels: category/breaking, release/8.11.0, state/sprint-candidate

#9061 Updated NPoco from 3.9.4 -> 4.0.2
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Examine/Umbraco.Examine.csproj
  src/Umbraco.Tests/Testing/TestDatabase.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: hacktoberfest/contrib-2020

#9621 Netcore: Migrate more tests
  src/Umbraco.Core/IO/PhysicalFileSystem.cs
  src/Umbraco.Core/IO/ShadowWrapper.cs
  src/Umbraco.Infrastructure/Persistence/IEmbeddedDatabaseCreator.cs
  src/Umbraco.Infrastructure/Persistence/NoopEmbeddedDatabaseCreator.cs
  src/Umbraco.Persistance.SqlCe/SqlCeEmbeddedDatabaseCreator.cs
  src/Umbraco.Tests.Integration/Cache/DistributedCacheBinderTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Core/IO/ShadowFileSystemTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/DatabaseBuilderTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/LocksTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/SchemaValidationTest.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/SqlServerTableByTableTest.cs
  src/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Scoping/ScopeEventDispatcherTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Persistence/DatabaseContextTests.cs
  src/Umbraco.Tests/Cache/DistributedCacheBinderTests.cs
  src/Umbraco.Tests/Persistence/DatabaseContextTests.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  src/umbraco-netcore-only.sln
Labels: project/net-core

#9026 Allow use of infinite editor in list views
  src/Umbraco.Web.UI.Client/src/common/services/listviewhelper.service.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/grid/grid.listviewlayout.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/list/list.listviewlayout.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
  src/Umbraco.Web/PropertyEditors/ListViewConfiguration.cs
Labels: category/ux, hacktoberfest-accepted, release/8.12.0, type/feature

#9640 Fixes a memory leak caused by deep cloning
  src/Umbraco.Core/Collections/EventClearingObservableCollection.cs
  src/Umbraco.Core/Collections/ObservableDictionary.cs
  src/Umbraco.Core/Models/Content.cs
  src/Umbraco.Core/Models/ContentBase.cs
  src/Umbraco.Core/Models/ContentCultureInfosCollection.cs
  src/Umbraco.Core/Models/ContentScheduleCollection.cs
  src/Umbraco.Core/Models/ContentTypeBase.cs
  src/Umbraco.Core/Models/Identity/BackOfficeIdentityUser.cs
  src/Umbraco.Core/Models/Media.cs
  src/Umbraco.Core/Models/PropertyCollection.cs
  src/Umbraco.Core/Models/PropertyGroup.cs
  src/Umbraco.Core/Models/PropertyGroupCollection.cs
  src/Umbraco.Core/Models/PropertyTypeCollection.cs
  src/Umbraco.Core/Models/PublicAccessEntry.cs
  src/Umbraco.Core/Umbraco.Core.csproj
Labels: category/performance, type/bug

#9616 Netcore: Fixes issues with user invites
  src/Umbraco.Core/Models/SimpleValidationModel.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Filters/AppendUserModifiedHeaderAttributeTests.cs
  src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
  src/Umbraco.Web.BackOffice/Controllers/CurrentUserController.cs
  src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
  src/Umbraco.Web.BackOffice/Filters/AppendUserModifiedHeaderAttribute.cs
  src/Umbraco.Web.Common/Security/BackofficeSecurity.cs
  src/Umbraco.Web.Common/Security/BackofficeSecurityFactory.cs
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/src/views/users/user.controller.js
  src/Umbraco.Web.UI.Client/src/views/users/views/users/users.controller.js
  src/Umbraco.Web.UI.NetCore/appsettings.Development.json
Labels: project/net-core

#9207 Check if urls is null
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js
Labels: category/ux, hacktoberfest-accepted, release/8.12.0, type/bug

#9384 Nested content UI fixes
  src/Umbraco.Web.UI.Client/src/less/components/umb-nested-content.less
Labels: category/ux, community/pr, release/8.10.2, release/8.11.0, release/8.7.2, release/8.8.3, release/8.9.2, status/regression, type/bug

#9601 NetCore: Getting rid of HttpResponseException
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Controllers/UsersControllerTests.cs
  src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
  src/Umbraco.Web.BackOffice/Controllers/CodeFileController.cs
  src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
  src/Umbraco.Web.BackOffice/Controllers/ContentControllerBase.cs
  src/Umbraco.Web.BackOffice/Controllers/ContentTypeController.cs
  src/Umbraco.Web.BackOffice/Controllers/ContentTypeControllerBase.cs
  src/Umbraco.Web.BackOffice/Controllers/CurrentUserController.cs
  src/Umbraco.Web.BackOffice/Controllers/DataTypeController.cs
  src/Umbraco.Web.BackOffice/Controllers/DictionaryController.cs
  src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
  src/Umbraco.Web.BackOffice/Controllers/ExamineManagementController.cs
  src/Umbraco.Web.BackOffice/Controllers/LanguageController.cs
  src/Umbraco.Web.BackOffice/Controllers/LogViewerController.cs
  src/Umbraco.Web.BackOffice/Controllers/MacroRenderingController.cs
  src/Umbraco.Web.BackOffice/Controllers/MacrosController.cs
  src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
  src/Umbraco.Web.BackOffice/Controllers/MediaTypeController.cs
  src/Umbraco.Web.BackOffice/Controllers/MemberController.cs
  src/Umbraco.Web.BackOffice/Controllers/MemberGroupController.cs
  src/Umbraco.Web.BackOffice/Controllers/MemberTypeController.cs
  src/Umbraco.Web.BackOffice/Controllers/PackageController.cs
  src/Umbraco.Web.BackOffice/Controllers/PackageInstallController.cs
  src/Umbraco.Web.BackOffice/Controllers/RelationTypeController.cs
  src/Umbraco.Web.BackOffice/Controllers/SectionController.cs
  src/Umbraco.Web.BackOffice/Controllers/TemplateController.cs
  src/Umbraco.Web.BackOffice/Controllers/UserGroupsController.cs
  src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
  src/Umbraco.Web.BackOffice/Filters/DataTypeValidateAttribute.cs
  src/Umbraco.Web.BackOffice/Filters/UserGroupValidateAttribute.cs
  src/Umbraco.Web.BackOffice/ModelBinders/ContentModelBinderHelper.cs
  src/Umbraco.Web.BackOffice/Trees/ApplicationTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/ContentBlueprintTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/ContentTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/ContentTreeControllerBase.cs
  src/Umbraco.Web.BackOffice/Trees/ContentTypeTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/DataTypeTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/DictionaryTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/FileSystemTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/LanguageTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/LogViewerTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/MacrosTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/MediaTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/MediaTypeTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/MemberGroupTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/MemberTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/MemberTypeAndGroupTreeControllerBase.cs
  src/Umbraco.Web.BackOffice/Trees/MemberTypeTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/PackagesTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/RelationTypeTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/TemplatesTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/TreeControllerBase.cs
  src/Umbraco.Web.BackOffice/Trees/UserTreeController.cs
  src/Umbraco.Web.Common/Controllers/UmbracoApiControllerBase.cs
  src/Umbraco.Web.Common/Exceptions/HttpResponseException.cs
  src/Umbraco.Web.Common/Filters/HttpResponseExceptionFilter.cs
  src/Umbraco.Web.Common/Install/InstallApiController.cs
  src/Umbraco.Web/WebApi/HttpActionContextExtensions.cs
Labels: project/net-core

#9531 Add support for unattended upgrades (and custom boot failed error page)
  src/Umbraco.Core/Runtime/CoreRuntime.cs
  src/Umbraco.Core/RuntimeOptions.cs
  src/Umbraco.Core/RuntimeState.cs
  src/Umbraco.Web.UI.Client/src/views/errors/BootFailed.html
  src/Umbraco.Web/Composing/ModuleInjector.cs
  src/Umbraco.Web/UmbracoApplication.cs
  src/Umbraco.Web/UmbracoApplicationBase.cs
  src/Umbraco.Web/UmbracoInjectedModule.cs
Labels: state/sprint-candidate

#9584 NetCore: Code clean-up (Umbraco.Tests.Common)
  src/Umbraco.Tests.Common/Builders/ConfigurationEditorBuilder.cs
  src/Umbraco.Tests.Common/Builders/ContentBuilder.cs
  src/Umbraco.Tests.Common/Builders/ContentPropertyBasicBuilder.cs
  src/Umbraco.Tests.Common/Builders/ContentTypeSortBuilder.cs
  src/Umbraco.Tests.Common/Builders/DataEditorBuilder.cs
  src/Umbraco.Tests.Common/Builders/DataValueEditorBuilder.cs
  src/Umbraco.Tests.Common/Builders/Interfaces/IWithLoginBuilder.cs
  src/Umbraco.Tests.Common/Extensions/ContentBaseExtensions.cs
  src/Umbraco.Tests.Common/Published/PublishedSnapshotTestObjects.cs
  src/Umbraco.Tests.Common/TestClone.cs
  src/Umbraco.Tests.Common/TestDefaultCultureAccessor.cs
  src/Umbraco.Tests.Common/TestHelperBase.cs
  src/Umbraco.Tests.Common/TestHelpers/MockedValueEditors.cs
  src/Umbraco.Tests.Common/TestHelpers/SolidPublishedSnapshot.cs
  src/Umbraco.Tests.Common/TestHelpers/StringNewlineExtensions.cs
  src/Umbraco.Tests.Common/TestHelpers/Stubs/TestProfiler.cs
  src/Umbraco.Tests.Common/TestHelpers/TestDatabase.cs
  src/Umbraco.Tests.Common/TestHelpers/TestEnvironment.cs
  src/Umbraco.Tests.Common/TestPublishedSnapshotAccessor.cs
  src/Umbraco.Tests.Common/TestUmbracoContextAccessor.cs
  src/Umbraco.Tests.Common/TestVariationContextAccessor.cs
  src/Umbraco.Tests.Common/Testing/TestOptionAttributeBase.cs
  src/Umbraco.Tests.Common/Testing/UmbracoTestAttribute.cs
  src/Umbraco.Tests.Common/Testing/UmbracoTestOptions.cs
Labels: project/net-core

#7860 V8: Angular Divorce: equals
  src/Umbraco.Web.UI.Client/src/common/directives/components/forms/checklistmodel.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/imaging/umbimagegravity.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/validation/valserver.directive.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/media.controller.js
  src/Umbraco.Web.UI.Client/test/lib/angular/angular-mocks.js
Labels: community/review

#7861 V8: Angular Divorce: isFunction
  src/Umbraco.Web.UI.Client/src/app.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/tree/umbtree.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbaceeditor.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbminilistview.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/validation/valpropertyvalidator.directive.js
  src/Umbraco.Web.UI.Client/src/common/services/angularhelper.service.js
  src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js
  src/Umbraco.Web.UI.Client/src/common/services/events.service.js
  src/Umbraco.Web.UI.Client/src/common/services/tree.service.js
  src/Umbraco.Web.UI.Client/src/installer/installer.service.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/treepicker/treepicker.controller.js
  src/Umbraco.Web.UI.Client/test/lib/angular/angular-mocks.js
Labels: community/review

#9154 Improvements to validation and accessibility of relationship create view
  src/Umbraco.Web.UI.Client/src/views/relationtypes/create.html
Labels: category/accessibility, category/ux, hacktoberfest-accepted, release/8.12.0

#9583 Netcore: test duration on CI pipeline with more databases
  src/Umbraco.Tests.Integration/Testing/BaseTestDatabase.cs
  src/Umbraco.Tests.Integration/Testing/LocalDbTestDatabase.cs
  src/Umbraco.Tests.Integration/Testing/SqlDeveloperTestDatabase.cs
  src/Umbraco.Tests.Integration/Testing/TestDatabaseFactory.cs
  src/Umbraco.Tests.Integration/Testing/TestDatabaseSettings.cs
  src/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
Labels: project/net-core

#9677 Fixes: 9360: Nested validation freezes browser
  src/Umbraco.Web.UI.Client/src/common/services/angularhelper.service.js
Labels: state/sprint-candidate

#9672 Get MB with PureLive working for netcore
  .gitignore
  src/Umbraco.Core/Configuration/Models/ModelsBuilderSettings.cs
  src/Umbraco.Core/Configuration/ModelsMode.cs
  src/Umbraco.Core/Configuration/ModelsModeExtensions.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Events.cs
  src/Umbraco.Core/Models/PublishedContent/ILivePublishedModelFactory.cs
  src/Umbraco.Core/PublishedModelFactoryExtensions.cs
  src/Umbraco.Core/Runtime/IMainDom.cs
  src/Umbraco.Core/Runtime/MainDom.cs
  src/Umbraco.Core/SimpleMainDom.cs
  src/Umbraco.Infrastructure/Scheduling/BackgroundTaskRunner.cs
  src/Umbraco.Infrastructure/Search/ExamineComponent.cs
  src/Umbraco.Infrastructure/Sync/DatabaseServerMessenger.cs
  src/Umbraco.Infrastructure/WebAssets/ServerVariablesParser.cs
  src/Umbraco.Infrastructure/WebAssets/ServerVariablesParsing.cs
  src/Umbraco.ModelsBuilder.Embedded/BackOffice/ContentTypeModelValidatorBase.cs
  src/Umbraco.ModelsBuilder.Embedded/BackOffice/DashboardReport.cs
  src/Umbraco.ModelsBuilder.Embedded/BackOffice/ModelsBuilderDashboardController.cs
  src/Umbraco.ModelsBuilder.Embedded/Building/ModelsGenerator.cs
  src/Umbraco.ModelsBuilder.Embedded/Compose/DisabledModelsBuilderComponent.cs
  src/Umbraco.ModelsBuilder.Embedded/Compose/ModelsBuilderComposer.cs
  src/Umbraco.ModelsBuilder.Embedded/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.ModelsBuilder.Embedded/DisableModelsBuilderNotificationHandler.cs
  src/Umbraco.ModelsBuilder.Embedded/LiveModelsProvider.cs
  src/Umbraco.ModelsBuilder.Embedded/ModelsBuilderNotificationHandler.cs
  src/Umbraco.ModelsBuilder.Embedded/OutOfDateModelsStatus.cs
  src/Umbraco.ModelsBuilder.Embedded/PureLiveModelFactory.cs
  src/Umbraco.ModelsBuilder.Embedded/RefreshingRazorViewEngine.cs
  src/Umbraco.ModelsBuilder.Embedded/RoslynCompiler.cs
  src/Umbraco.ModelsBuilder.Embedded/Umbraco.ModelsBuilder.Embedded.csproj
  src/Umbraco.ModelsBuilder.Embedded/UmbracoAssemblyLoadContext.cs
  src/Umbraco.ModelsBuilder.Embedded/UmbracoServices.cs
  src/Umbraco.PublishedCache.NuCache/PublishedSnapshotService.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/LocksTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Composing/TypeLoaderTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/AngularIntegration/ServerVariablesParserTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Views/UmbracoViewPageTests.cs
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
  src/Umbraco.Web.BackOffice/Controllers/PreviewController.cs
  src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/AspNetCore/UmbracoViewPage.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Filters/ModelBindingExceptionAttribute.cs
  src/Umbraco.Web.Common/Lifetime/IUmbracoRequestLifetime.cs
  src/Umbraco.Web.Common/Localization/UmbracoBackOfficeIdentityCultureProvider.cs
  src/Umbraco.Web.Common/ModelBinders/ContentModelBinder.cs
  src/Umbraco.Web.UI.Client/src/common/services/contenttypehelper.service.js
  src/Umbraco.Web.UI.NetCore/Startup.cs
  src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
  src/Umbraco.Web.UI.NetCore/appsettings.json
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  src/Umbraco.Web.Website/DependencyInjection/UmbracoBuilderExtensions.cs
Labels: project/net-core

#9669 Minor optimisation by passing int instead of int? to Umbraco.Content()
  src/Umbraco.Web/Mvc/EnsurePublishedContentRequestAttribute.cs
Labels: category/performance, community/pr

#9268 Optimize content and media count queries when paging
  src/Umbraco.Web/PublishedCache/NuCache/DataSource/DatabaseDataSource.cs
Labels: category/performance, community/pr, hacktoberfest-accepted

#9682 Netcore: Add support for sync notification handlers in event aggregator
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Events.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Core/Events/EventAggregator.Notifications.cs
  src/Umbraco.Core/Events/EventAggregator.cs
  src/Umbraco.Core/Events/IEventAggregator.cs
  src/Umbraco.Core/Events/INotificationHandler.cs
  src/Umbraco.Core/Runtime/AppPluginsManifestWatcherNotificationHandler.cs
  src/Umbraco.Core/Runtime/EssentialDirectoryCreator.cs
  src/Umbraco.Infrastructure/Cache/DatabaseServerMessengerNotificationHandler.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Events/EventAggregatorTests.cs
  src/Umbraco.Web.Common/Profiler/InitializeWebProfiling.cs
Labels: project/net-core

#9700 Netcore: Use hosted services instead of umbraco background task
  src/Umbraco.Core/Scheduling/RecurringTaskBase.cs
  src/Umbraco.Core/Scheduling/TaskAndFactoryExtensions.cs
  src/Umbraco.Core/TaskHelper.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.DistributedCache.cs
  src/Umbraco.Infrastructure/HostedServices/BackgroundTaskQueue.cs
  src/Umbraco.Infrastructure/HostedServices/IBackgroundTaskQueue.cs
  src/Umbraco.Infrastructure/HostedServices/QueuedHostedService.cs
  src/Umbraco.Infrastructure/Scheduling/SimpleTask.cs
  src/Umbraco.Infrastructure/Search/BackgroundIndexRebuilder.cs
  src/Umbraco.Infrastructure/Search/ExamineComponent.cs
  src/Umbraco.Infrastructure/Search/ExamineFinalComponent.cs
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.Tests.Common/TestHelpers/LogTestHelper.cs
  src/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
  src/Umbraco.Tests.Integration/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/TaskHelperTests.cs
  src/Umbraco.Tests/LegacyXmlPublishedCache/LegacyBackgroundTask/BackgroundTaskRunner.cs
  src/Umbraco.Tests/LegacyXmlPublishedCache/LegacyBackgroundTask/BackgroundTaskRunnerOptions.cs
  src/Umbraco.Tests/LegacyXmlPublishedCache/LegacyBackgroundTask/IBackgroundTask.cs
  src/Umbraco.Tests/LegacyXmlPublishedCache/LegacyBackgroundTask/IBackgroundTaskRunner.cs
  src/Umbraco.Tests/LegacyXmlPublishedCache/LegacyBackgroundTask/ILatchedBackgroundTask.cs
  src/Umbraco.Tests/LegacyXmlPublishedCache/LegacyBackgroundTask/LatchedBackgroundTaskBase.cs
  src/Umbraco.Tests/LegacyXmlPublishedCache/LegacyBackgroundTask/TaskEventArgs.cs
  src/Umbraco.Tests/LegacyXmlPublishedCache/LegacyBackgroundTask/ThreadingTaskImmutable.cs
  src/Umbraco.Tests/Scheduling/BackgroundTaskRunnerTests.cs
  src/Umbraco.Tests/Scheduling/BackgroundTaskRunnerTests2.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
Labels: project/net-core

#9711 Netcore: Replace IUmbracoRequestLifetime with EventAggregator nofitications
  src/Umbraco.Infrastructure/Persistence/SqlSyntax/SqlServerSyntaxProvider.cs
  src/Umbraco.ModelsBuilder.Embedded/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.ModelsBuilder.Embedded/LiveModelsProvider.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/LocksTests.cs
  src/Umbraco.Web.Common/AspNetCore/AspNetCoreRequestAccessor.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Events/UmbracoRequestBegin.cs
  src/Umbraco.Web.Common/Events/UmbracoRequestEnd.cs
  src/Umbraco.Web.Common/Lifetime/IUmbracoRequestLifetime.cs
  src/Umbraco.Web.Common/Lifetime/IUmbracoRequestLifetimeManager.cs
  src/Umbraco.Web.Common/Lifetime/UmbracoRequestLifetime.cs
  src/Umbraco.Web.Common/Middleware/UmbracoRequestMiddleware.cs
  src/Umbraco.Web.Common/Profiler/InitializeWebProfiling.cs
  src/Umbraco.Web.Common/Profiler/WebProfiler.cs
Labels: project/net-core

#9717 Netcore: Migrate more tests
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/SyntaxProvider/SqlServerSyntaxProviderTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Models/RangeTests.cs
  src/Umbraco.Tests/Testing/TestingTests/MockTests.cs
  src/Umbraco.Tests/Testing/TestingTests/NUnitTests.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
Labels: project/net-core

#9327 Add ellipsis to the Sort action in Content and Media
  src/Umbraco.Web/Trees/ContentTreeController.cs
  src/Umbraco.Web/Trees/MediaTreeController.cs
Labels: hacktoberfest/contrib-2020

#9694 Netcore: Updated to .NET 5
  build/NuSpecs/UmbracoCms.Core.nuspec
  build/NuSpecs/UmbracoCms.SqlCe.nuspec
  build/NuSpecs/UmbracoCms.Web.nuspec
  build/NuSpecs/UmbracoCms.nuspec
  build/azure-pipelines.yml
  build/build.ps1
  build/templates/Umbraco.Templates.nuspec
  build/templates/UmbracoSolution/.template.config/template.json
  build/templates/UmbracoSolution/UmbracoSolution.csproj
  src/Umbraco.Configuration/Properties/AssemblyInfo.cs
  src/Umbraco.Configuration/Umbraco.Configuration.csproj
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Infrastructure/Install/InstallSteps/DatabaseConfigureStep.cs
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.ModelsBuilder.Embedded/Umbraco.ModelsBuilder.Embedded.csproj
  src/Umbraco.Persistence.SqlCe/SqlCeBulkSqlInsertProvider.cs
  src/Umbraco.Persistence.SqlCe/SqlCeEmbeddedDatabaseCreator.cs
  src/Umbraco.Persistence.SqlCe/SqlCeSyntaxProvider.cs
  src/Umbraco.Persistence.SqlCe/Umbraco.Persistence.SqlCe.csproj
  src/Umbraco.TestData/Umbraco.TestData.csproj
  src/Umbraco.Tests.Benchmarks/ModelToSqlExpressionHelperBenchmarks.cs
  src/Umbraco.Tests.Benchmarks/SqlTemplatesBenchmark.cs
  src/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
  src/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/DatabaseBuilderTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/LocksTests.cs
  src/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Published/ModelTypeTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.PublishedCache.NuCache/SnapDictionaryTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
  src/Umbraco.Tests/Persistence/Mappers/MapperTestBase.cs
  src/Umbraco.Tests/TestHelpers/BaseUsingSqlCeSyntax.cs
  src/Umbraco.Tests/TestHelpers/TestHelper.cs
  src/Umbraco.Tests/TestHelpers/TestObjects-Mocks.cs
  src/Umbraco.Tests/TestHelpers/TestObjects.cs
  src/Umbraco.Tests/TestHelpers/TestWithDatabaseBase.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
  src/Umbraco.Tests/Web/Controllers/AuthenticationControllerTests.cs
  src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
  src/Umbraco.Web.Common/Authorization/FeatureAuthorizeHandler.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  src/Umbraco.Web.Website/Umbraco.Web.Website.csproj
  src/Umbraco.Web/Umbraco.Web.csproj
  src/Umbraco.Web/UmbracoDbProviderFactoryCreator.cs
  src/umbraco.sln
Labels: project/net-core

#9721 NetCore: Published X Extensions classes migration
  src/Umbraco.Core/PublishedContentExtensions.cs
  src/Umbraco.Tests/PublishedContent/NuCacheChildrenTests.cs
  src/Umbraco.Tests/PublishedContent/NuCacheTests.cs
  src/Umbraco.Tests/PublishedContent/PublishedContentDataTableTests.cs
  src/Umbraco.Tests/PublishedContent/PublishedContentLanguageVariantTests.cs
  src/Umbraco.Tests/PublishedContent/PublishedContentMoreTests.cs
  src/Umbraco.Tests/PublishedContent/PublishedContentTests.cs
  src/Umbraco.Tests/PublishedContent/PublishedMediaTests.cs
  src/Umbraco.Web.Website/Extensions/PublishedContentExtensions.cs
  src/Umbraco.Web/PublishedContentExtensions.cs
  src/Umbraco.Web/PublishedElementExtensions.cs
  src/Umbraco.Web/PublishedPropertyExtension.cs
  src/Umbraco.Web/Security/PublicAccessChecker.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: project/net-core
