Repository umbraco/Umbraco-CMS, pull requests merged in 2021-02, with the labels that each got.

#9740 Netcore: Various bugfixes found while building realistic website
  src/Umbraco.Core/TypeExtensions.cs
  src/Umbraco.ModelsBuilder.Embedded/Building/TextBuilder.cs
  src/Umbraco.ModelsBuilder.Embedded/RoslynCompiler.cs
  src/Umbraco.Tests.Integration/TestServerTest/Controllers/EnsureNotAmbiguousActionNameControllerTests.cs
  src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
  src/Umbraco.Web.BackOffice/Controllers/ContentTypeController.cs
  src/Umbraco.Web.BackOffice/Controllers/DataTypeController.cs
  src/Umbraco.Web.BackOffice/Controllers/DetermineAmbiguousActionByPassingParameters.cs
  src/Umbraco.Web.BackOffice/Controllers/DictionaryController.cs
  src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
  src/Umbraco.Web.BackOffice/Controllers/IconController.cs
  src/Umbraco.Web.BackOffice/Controllers/MacrosController.cs
  src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
  src/Umbraco.Web.BackOffice/Controllers/MediaTypeController.cs
  src/Umbraco.Web.BackOffice/Controllers/MemberGroupController.cs
  src/Umbraco.Web.BackOffice/Controllers/MemberTypeController.cs
  src/Umbraco.Web.BackOffice/Controllers/ParameterSwapControllerActionSelectorAttribute.cs
  src/Umbraco.Web.BackOffice/Controllers/RelationTypeController.cs
  src/Umbraco.Web.BackOffice/Controllers/TemplateController.cs
  src/Umbraco.Web.BackOffice/Filters/CheckIfUserTicketDataIsStaleAttribute.cs
  src/Umbraco.Web.Common/AspNetCore/UmbracoViewPage.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Extensions/HttpRequestExtensions.cs
  src/Umbraco.Web.Common/Extensions/UrlHelperExtensions.cs
  src/Umbraco.Web.Common/UmbracoHelper.cs
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/src/common/resources/content.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js
Labels: project/net-core

#9648 fix history box label, destructure localization response
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js
  src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html
Labels: category/ux, release/no-notes, type/bug

#9752 Fix eventService memory leaks
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbvariantcontenteditors.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorheader.directive.js
  src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
  src/Umbraco.Web.UI.Client/src/common/services/localization.service.js
  src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js
  src/Umbraco.Web.UI.Client/src/views/prevalueeditors/treesourcetypepicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/colorpicker/multicolorpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
  src/Umbraco.Web.UI.Client/src/views/relationtypes/edit.controller.js
Labels: community/pr, release/8.12.0, type/bug

#9716 Add Check for ´err´
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
Labels: community/review, release/8.12.0, release/no-notes

#9715 Stop using .length !== 0 when its not jQuery
  src/Umbraco.Web.UI.Client/src/common/services/formhelper.service.js
Labels: community/review, release/8.12.0, release/no-notes, type/bug

#9618 Document onChange in umbPagination
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbpagination.directive.js
Labels: category/api-documentation, community/pr, release/8.12.0

#9739 Prevent overflow of searchresults with long urls
  src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-icon.less
Labels: category/ui, community/pr, release/8.12.0, type/bug

#9729 Add more constants for tree icons
  src/Umbraco.Core/Constants-Icons.cs
  src/Umbraco.Web/Trees/DataTypeTreeController.cs
  src/Umbraco.Web/Trees/DictionaryTreeController.cs
  src/Umbraco.Web/Trees/LanguageTreeController.cs
  src/Umbraco.Web/Trees/LogViewerTreeController.cs
  src/Umbraco.Web/Trees/PackagesTreeController.cs
Labels: community/pr, release/8.12.0, release/no-notes

#9770 Netcore: Fix missing application url
  src/Umbraco.Core/HealthChecks/Checks/Security/BaseHttpHeaderCheck.cs
  src/Umbraco.Core/HealthChecks/Checks/Security/ClickJackingCheck.cs
  src/Umbraco.Core/HealthChecks/Checks/Security/ExcessiveHeadersCheck.cs
  src/Umbraco.Core/HealthChecks/Checks/Security/HstsCheck.cs
  src/Umbraco.Core/HealthChecks/Checks/Security/HttpsCheck.cs
  src/Umbraco.Core/HealthChecks/Checks/Security/NoSniffCheck.cs
  src/Umbraco.Core/HealthChecks/Checks/Security/XssProtectionCheck.cs
  src/Umbraco.Core/HealthChecks/NotificationMethods/EmailNotificationMethod.cs
  src/Umbraco.Core/Hosting/IHostingEnvironment.cs
  src/Umbraco.Core/Web/IRequestAccessor.cs
  src/Umbraco.Infrastructure/Compose/NotificationsComponent.cs
  src/Umbraco.Infrastructure/HostedServices/KeepAlive.cs
  src/Umbraco.Infrastructure/HostedServices/ServerRegistration/TouchServerTask.cs
  src/Umbraco.Tests.Integration/Implementations/TestHelper.cs
  src/Umbraco.Tests.Integration/Implementations/TestHostingEnvironment.cs
  src/Umbraco.Tests.UnitTests/TestHelpers/TestHelper.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Extensions/UriExtensionsTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/UmbracoRequestPathsTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/KeepAliveTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/ServerRegistration/TouchServerTaskTests.cs
  src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
  src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
  src/Umbraco.Web.Common/AspNetCore/AspNetCoreHostingEnvironment.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Middleware/UmbracoRequestMiddleware.cs
  src/Umbraco.Web/AspNet/AspNetHostingEnvironment.cs
Labels: project/net-core

#9075 V8/bugfix/9074 current urls segments
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js
Labels: hacktoberfest-accepted

#9780 Fix mini profiler so that it actually profiles the Content APIs in the back office
  src/Umbraco.Web/Logging/WebProfiler.cs
  src/Umbraco.Web/Logging/WebProfilerProvider.cs
Labels: category/performance, type/bug

#9174 V8/feature/super doctype create menu
  src/Umbraco.Web.UI.Client/src/common/resources/contenttype.resource.js
  src/Umbraco.Web.UI.Client/src/views/documenttypes/create.controller.js
  src/Umbraco.Web.UI.Client/src/views/documenttypes/create.html
  src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
  src/Umbraco.Web/Editors/ContentTypeController.cs
Labels: hacktoberfest-accepted

#9822 Netcore: Copy static files to publish directory in dotnet template
  build/templates/UmbracoSolution/UmbracoSolution.csproj
Labels: project/net-core

#9778 Fixes issue with broken caches used for user permissions
  src/Umbraco.Core/Cache/CacheKeys.cs
  src/Umbraco.Core/Models/Identity/IdentityMapDefinition.cs
  src/Umbraco.Core/Models/Membership/User.cs
  src/Umbraco.Core/Models/UserExtensions.cs
  src/Umbraco.Core/Security/BackOfficeUserStore.cs
  src/Umbraco.Core/Security/ContentPermissionsHelper.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests/Models/UserExtensionsTests.cs
  src/Umbraco.Tests/Web/Controllers/ContentControllerUnitTests.cs
  src/Umbraco.Tests/Web/Controllers/FilterAllowedOutgoingContentAttributeTests.cs
  src/Umbraco.Tests/Web/Controllers/MediaControllerUnitTests.cs
  src/Umbraco.Tests/Web/Controllers/UserEditorAuthorizationHelperTests.cs
  src/Umbraco.Web/Cache/UserCacheRefresher.cs
  src/Umbraco.Web/Editors/ContentController.cs
  src/Umbraco.Web/Editors/EntityController.cs
  src/Umbraco.Web/Editors/Filters/ContentSaveValidationAttribute.cs
  src/Umbraco.Web/Editors/Filters/MediaItemSaveValidationAttribute.cs
  src/Umbraco.Web/Editors/Filters/UserGroupAuthorizationAttribute.cs
  src/Umbraco.Web/Editors/Filters/UserGroupEditorAuthorizationHelper.cs
  src/Umbraco.Web/Editors/MediaController.cs
  src/Umbraco.Web/Editors/UserEditorAuthorizationHelper.cs
  src/Umbraco.Web/Editors/UserGroupsController.cs
  src/Umbraco.Web/Editors/UsersController.cs
  src/Umbraco.Web/Models/Mapping/ContentMapDefinition.cs
  src/Umbraco.Web/Models/Mapping/UserMapDefinition.cs
  src/Umbraco.Web/Search/UmbracoTreeSearcher.cs
  src/Umbraco.Web/Trees/ContentTreeController.cs
  src/Umbraco.Web/Trees/ContentTreeControllerBase.cs
  src/Umbraco.Web/Trees/MediaTreeController.cs
  src/Umbraco.Web/WebApi/Filters/AdminUsersAuthorizeAttribute.cs
  src/Umbraco.Web/WebApi/Filters/CheckIfUserTicketDataIsStaleAttribute.cs
  src/Umbraco.Web/WebApi/Filters/EnsureUserPermissionForContentAttribute.cs
  src/Umbraco.Web/WebApi/Filters/EnsureUserPermissionForMediaAttribute.cs
  src/Umbraco.Web/WebApi/Filters/FilterAllowedOutgoingContentAttribute.cs
  src/Umbraco.Web/WebApi/Filters/FilterAllowedOutgoingMediaAttribute.cs
Labels: category/performance, state/sprint-candidate, type/bug

#9827 Netcore: Fixed buildscripts to work with latest Umbraco.Build and Directory.Build.props
  build/build-bootstrap.ps1
  build/build.ps1
  src/Directory.Build.props
  src/SolutionInfo.cs
  src/Umbraco.Web.UI.NetCore/Properties/launchSettings.json
Labels: project/net-core

#9834 Fixes error trying to load Cosmos.CRTCompat.dll (System.BadImageForma…
  src/Umbraco.Core/Composing/DefaultUmbracoAssemblyProvider.cs
  src/Umbraco.Core/Composing/FindAssembliesWithReferencesTo.cs
  src/Umbraco.Core/Composing/ReferenceResolver.cs
  src/Umbraco.Tests.Benchmarks/TypeFinderBenchmarks.cs
  src/Umbraco.Tests.Common/TestHelperBase.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Composing/TypeFinderTests.cs
  src/Umbraco.Tests/Testing/UmbracoTestBase.cs
  src/Umbraco.Web.Common/Extensions/UmbracoCoreServiceCollectionExtensions.cs
  src/Umbraco.Web/UmbracoApplicationBase.cs
Labels: project/net-core

#9803 Remove HtmlSanitizer
  build/NuSpecs/UmbracoCms.Web.nuspec
  src/Umbraco.Core/Constants-SvgSanitizer.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Web/Services/IconService.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: category/breaking, release/8.12.0, type/feature

#9846 Fix 'Do something else' button position in create dialog
  src/Umbraco.Web.UI.Client/src/views/documenttypes/create.html
  src/Umbraco.Web.UI.Client/src/views/mediatypes/create.html
  src/Umbraco.Web.UI.Client/src/views/membertypes/create.html
Labels: category/ui, community/pr

#9632 Align datatype sidebar box properties
  src/Umbraco.Web.UI.Client/src/less/forms.less
Labels: release/8.13.0, status/regression, type/bug

#9633 Ensure sub-view components are not self-closed elements
  src/Umbraco.Web.UI.Client/src/views/components/content/umb-variant-content.html
  src/Umbraco.Web.UI.Client/src/views/content/recyclebin.html
  src/Umbraco.Web.UI.Client/src/views/media/edit.html
  src/Umbraco.Web.UI.Client/src/views/media/recyclebin.html
  src/Umbraco.Web.UI.Client/src/views/member/edit.html
  src/Umbraco.Web.UI.Client/src/views/member/list.html
Labels: category/ui, community/pr, release/8.13.0, type/bug

#9657 Move relation type id and macro id to sidebar box
  src/Umbraco.Web.UI.Client/src/views/macros/views/settings.html
  src/Umbraco.Web.UI.Client/src/views/relationtypes/views/relationType.html
Labels: category/ui, community/pr, release/8.13.0, type/feature

#9670 Speed up boot times and Improve Json (De)Serialization performance and reduce memory usage by reusing JsonSerializerSettings
  src/Umbraco.Core/PropertyEditors/ValueConverters/ImageCropperValueConverter.cs
  src/Umbraco.Core/Serialization/NoTypeConverterJsonConverter.cs
  src/Umbraco.Tests.Benchmarks/JsonSerializerSettingsBenchmarks.cs
  src/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
  src/Umbraco.Web/Editors/BackOfficeController.cs
  src/Umbraco.Web/ImageCropperTemplateExtensions.cs
  src/Umbraco.Web/Mvc/JsonNetResult.cs
  src/Umbraco.Web/PropertyEditors/MultiUrlPickerValueEditor.cs
  src/Umbraco.Web/PublishedCache/NuCache/DataSource/DatabaseDataSource.cs
Labels: category/performance, community/pr, release/8.12.0, type/feature

#9693 Fix some exceptions being logged the wrong way
  src/Umbraco.ModelsBuilder.Embedded/LiveModelsProvider.cs
  src/Umbraco.ModelsBuilder.Embedded/PureLiveModelFactory.cs
  src/Umbraco.Web/PropertyEditors/MultiUrlPickerValueEditor.cs
  src/Umbraco.Web/UmbracoInjectedModule.cs
Labels: category/refactor, community/pr, release/8.13.0, type/bug

#9848 Fixes #9625 - Searching icons for "box" returns all icons
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/iconpicker/iconpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/iconpicker/iconpicker.html
Labels: category/ux, community/pr, release/8.13.0, type/bug

#9810 Performance and accessibility improvements on the embed screen
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/embed/embed.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/embed/embed.html
Labels: category/accessibility, community/pr, release/8.13.0, type/feature

#9487 Change access level for TreeChanged event in Media and ContentService
  src/Umbraco.Core/Services/Changes/TreeChange.cs
  src/Umbraco.Core/Services/Implement/ContentService.cs
  src/Umbraco.Core/Services/Implement/MediaService.cs
Labels: category/api, community/pr, release/8.13.0, type/feature

#9528 Make abstract FileSystemWrapper class methods virtual
  src/Umbraco.Core/IO/FileSystemWrapper.cs
Labels: category/api, community/pr, release/8.13.0, type/feature

#9335 Make models builder properties virtual to allow mocking
  src/Umbraco.ModelsBuilder.Embedded/Building/TextBuilder.cs
  src/Umbraco.Tests/ModelsBuilder/BuilderTests.cs
Labels: category/api, community/pr, release/8.13.0, type/feature

#9856 Fixes #9615 - Upgrade to Htmlsanitizer v5
  build/NuSpecs/UmbracoCms.Web.nuspec
  src/Umbraco.Core/Constants-SvgSanitizer.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Web/Runtime/WebInitialComposer.cs
  src/Umbraco.Web/Services/IconService.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: community/pr, dependencies, release/8.12.0, type/feature

#9850 Remove legacy member cache refresher and unused base class
  src/Umbraco.Core/Cache/MemberCacheRefresher.cs
  src/Umbraco.Core/Cache/TypedCacheRefresherBase.cs
Labels: project/net-core

#9851 Remove obsolete configuration references
  src/Umbraco.Core/Configuration/Models/GlobalSettings.cs
  src/Umbraco.Core/Constants-AppSettings.cs
  src/Umbraco.Tests/LegacyXmlPublishedCache/PublishedMediaCache.cs
Labels: project/net-core

#9853 Clean up the IO Helper interface
  src/Umbraco.Core/Extensions/StringExtensions.cs
  src/Umbraco.Core/IO/IIOHelper.cs
  src/Umbraco.Core/IO/IOHelper.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/ShortStringHelper/StringExtensionsTests.cs
Labels: project/net-core

#9854 Removed unused method from migration expression interface
  src/Umbraco.Infrastructure/Migrations/Expressions/Rename/Expressions/RenameColumnExpression.cs
  src/Umbraco.Infrastructure/Migrations/IMigrationExpression.cs
  src/Umbraco.Infrastructure/Migrations/MigrationExpressionBase.cs
Labels: project/net-core

#9852 Rename UmbracoVersion.Current to UmbracoVersion.Version
  src/Umbraco.Core/Configuration/IUmbracoVersion.cs
  src/Umbraco.Core/Configuration/UmbracoVersion.cs
  src/Umbraco.Core/Models/UpgradeCheckResponse.cs
  src/Umbraco.Core/Packaging/PackageDefinitionXmlParser.cs
  src/Umbraco.Infrastructure/Install/InstallHelper.cs
  src/Umbraco.Infrastructure/Install/InstallSteps/StarterKitDownloadStep.cs
  src/Umbraco.Infrastructure/RuntimeState.cs
  src/Umbraco.Web.BackOffice/Controllers/PackageInstallController.cs
  src/Umbraco.Web.BackOffice/Controllers/UpdateCheckController.cs
  src/Umbraco.Web/Security/Providers/UmbracoMembershipProvider.cs
Labels: project/net-core

#9855 Remove obsolete method in UmbracoBuilderExtensions
  src/Umbraco.Tests/TestHelpers/BaseUsingSqlCeSyntax.cs
  src/Umbraco.Tests/TestHelpers/TestHelper.cs
  src/Umbraco.Tests/Testing/UmbracoTestBase.cs
  src/Umbraco.Web/UmbracoBuilderExtensions.cs
Labels: project/net-core

#9833 Netcore: Remove UmbracoBackOfficeIdentity
  src/Umbraco.Core/Extensions/ClaimsIdentityExtensions.cs
  src/Umbraco.Core/Security/AuthenticationExtensions.cs
  src/Umbraco.Core/Security/ClaimsPrincipalExtensions.cs
  src/Umbraco.Core/Security/UmbracoBackOfficeIdentity.cs
  src/Umbraco.Infrastructure/Compose/AuditEventsComponent.cs
  src/Umbraco.Infrastructure/Security/BackOfficeClaimsPrincipalFactory.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/BackOffice/UmbracoBackOfficeIdentityTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Extensions/ClaimsPrincipalExtensionsTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/BackOffice/BackOfficeClaimsPrincipalFactoryTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Security/BackOfficeAntiforgeryTests.cs
  src/Umbraco.Tests/PublishedContent/PublishedContentTests.cs
  src/Umbraco.Tests/TestHelpers/ControllerTesting/AuthenticateEverythingMiddleware.cs
  src/Umbraco.Tests/TestHelpers/ControllerTesting/TestControllerActivatorBase.cs
  src/Umbraco.Web.BackOffice/Filters/CheckIfUserTicketDataIsStaleAttribute.cs
  src/Umbraco.Web.BackOffice/Security/BackOfficeSecureDataFormat.cs
  src/Umbraco.Web.BackOffice/Security/ConfigureBackOfficeCookieOptions.cs
  src/Umbraco.Web.Common/Extensions/HttpContextExtensions.cs
  src/Umbraco.Web.Common/Security/BackOfficeUserManager.cs
  src/Umbraco.Web.Common/Security/BackofficeSecurity.cs
  src/Umbraco.Web.Common/Security/MemberManager.cs
Labels: project/net-core

#9441 Ensure there's explicit scopes used for all service access in the Examine indexing logic
  src/Umbraco.Core/Services/Implement/PublicAccessService.cs
  src/Umbraco.Examine/ContentValueSetValidator.cs
  src/Umbraco.Tests/UmbracoExamine/UmbracoContentValueSetValidatorTests.cs
  src/Umbraco.Web/Search/ExamineComponent.cs
Labels: community/review, type/bug

#9741 NetCore: Fix CreateMember and CreateContent methods
  src/Umbraco.Core/Models/Content.cs
  src/Umbraco.Core/Models/Member.cs
  src/Umbraco.Infrastructure/Services/Implement/ContentService.cs
  src/Umbraco.Infrastructure/Services/Implement/MemberService.cs
Labels: project/net-core

#9899 Netcore: Fix packages with actions
  src/Umbraco.Infrastructure/Packaging/PackageInstallation.cs
  src/Umbraco.Web.UI.Client/src/views/packages/edit.html
Labels: project/net-core
