Repository umbraco/Umbraco-CMS, pull requests merged in 2021-06, with the labels that each got.

#10352 Enable email sender to publish an event if smtp is not configured
  src/Umbraco.Core/Mail/IEmailSender.cs
  src/Umbraco.Core/Mail/NotImplementedEmailSender.cs
  src/Umbraco.Core/Notifications/SendEmailNotification.cs
  src/Umbraco.Infrastructure/EmailSender.cs
  src/Umbraco.Tests.UnitTests/TestHelpers/TestHelper.cs
  src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
Labels: project/v9

#10365 Support custom SVG icon in block list editor
  src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/inlineblock/inlineblock.editor.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/inlineblock/inlineblock.editor.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/labelblock/labelblock.editor.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/labelblock/labelblock.editor.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/unsupportedblock/unsupportedblock.editor.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/unsupportedblock/unsupportedblock.editor.less
Labels: category/ui, community/pr, release/8.15.0, type/bug

#10310 Add a collection to allow adding CSS and JS to the back office via C#
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Collections.cs
  src/Umbraco.Core/WebAssets/CustomBackOfficeAssetsCollection.cs
  src/Umbraco.Core/WebAssets/CustomBackOfficeAssetsCollectionBuilder.cs
  src/Umbraco.Infrastructure/WebAssets/BackOfficeWebAssets.cs
  src/Umbraco.Infrastructure/WebAssets/PropertyEditorAssetAttribute.cs
Labels: project/v9

#10370 V9: Fixed serialization issue Amount (min and max) isn't stored and working with Media picker 3
  src/Umbraco.Core/PropertyEditors/MediaPicker3Configuration.cs
Labels: project/v9

#10182 Fix startup issues and timing with Examine and Nucache
  src/Umbraco.Core/Sync/DatabaseServerMessenger.cs
  src/Umbraco.Core/Sync/DatabaseServerMessengerOptions.cs
  src/Umbraco.Core/Sync/ISyncBootStateAccessor.cs
  src/Umbraco.Core/Sync/NonRuntimeLevelBootStateAccessor.cs
  src/Umbraco.Core/Sync/SyncBootState.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests/PublishedContent/NuCacheChildrenTests.cs
  src/Umbraco.Tests/PublishedContent/NuCacheTests.cs
  src/Umbraco.Tests/Scoping/ScopedNuCacheTests.cs
  src/Umbraco.Tests/Services/ContentTypeServiceVariantsTests.cs
  src/Umbraco.Tests/TestHelpers/TestSyncBootStateAccessor.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
  src/Umbraco.Web/BatchedDatabaseServerMessenger.cs
  src/Umbraco.Web/Compose/DatabaseServerRegistrarAndMessengerComponent.cs
  src/Umbraco.Web/Compose/DatabaseServerRegistrarAndMessengerComposer.cs
  src/Umbraco.Web/PublishedCache/NuCache/NuCacheComposer.cs
  src/Umbraco.Web/PublishedCache/NuCache/PublishedSnapshotService.cs
  src/Umbraco.Web/Search/ExamineFinalComponent.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: type/bug

#10344 Support custom SVG icon in umb-child-selector component
  src/Umbraco.Web.UI.Client/src/less/components/card.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-group-builder.less
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypepicker/datatypepicker.html
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/macroparameterpicker/macroparameterpicker.html
  src/Umbraco.Web.UI.Client/src/views/common/overlays/itempicker/itempicker.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-child-selector.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-grid-selector.html
  src/Umbraco.Web.UI.Client/src/views/macros/infiniteeditors/parameter.html
Labels: release/8.13.2, release/8.14.1, state/sprint-candidate

#10345 Support custom SVG icon in listview
  src/Umbraco.Web.UI.Client/src/views/components/umb-content-grid.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-folder-grid.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-media-grid.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-table.html
  src/Umbraco.Web.UI.Client/src/views/content/create.html
  src/Umbraco.Web.UI.Client/src/views/media/create.html
  src/Umbraco.Web.UI.Client/src/views/member/create.html
Labels: release/8.13.2, release/8.14.1, state/sprint-candidate, type/bug

#10361 Support custom SVG icon in grid editor row configuration
  src/Umbraco.Web.UI.Client/src/less/components/umb-form-check.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-grid.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/dialogs/rowconfig.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/embed.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/embed.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/macro.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/macro.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/media.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/media.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/textstring.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js
Labels: category/ux, community/pr, release/8.13.1, release/8.14.1, type/bug

#10367 Support custom SVG icon in user group filter
  src/Umbraco.Web.UI.Client/src/views/users/views/users/users.html
Labels: category/ux, community/pr, release/8.13.1, release/8.14.1, type/bug

#9835 .NETCore & SQL Docker Image for Container Isolated Development & GitHub CodeSpaces
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/library-scripts/azcli-debian.sh
  .devcontainer/mssql/BlankDb.sql
  .devcontainer/mssql/installSQLtools.sh
  .devcontainer/mssql/postCreateCommand.sh
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByUrlAliasTests.cs
Labels: project/v9

#10407 Convert date to datetime in SQL queries for sorting on date
  src/Umbraco.Core/Persistence/SqlSyntax/SqlSyntaxProviderBase.cs
Labels: community/pr, release/8.15.0, type/bug

#10313 Link picker: Make link input full width if anchor option is disabled
  src/Umbraco.Web.UI.Client/src/less/property-editors.less
Labels: category/ui, community/pr, release/8.15.0, type/bug

#10425 V9: add missing overload is allowed template
  src/Umbraco.Web.Common/Extensions/FriendlyPublishedContentExtensions.cs
Labels: project/v9, type/bug

#10455 HTML Symantic error UL > LI >LI changes to UL > LI > UL > LI
  src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree.html
Labels: category/accessibility, category/ui, community/pr, release/8.15.0, type/bug

#10440 10430: Fix typo
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker3/umb-media-picker3-property-editor.html
Labels: category/ux, community/pr, type/bug

#10470 Fix interface inheritance
  src/Umbraco.Web.Common/ApplicationBuilder/IUmbracoApplicationBuilder.cs
  src/Umbraco.Web.Common/ApplicationBuilder/UmbracoApplicationBuilder.cs
Labels: project/v9, release/9.0.0-beta004

#10467 dotnet new template - Escape JSON special characters for password & connection string
  build/build.ps1
  build/templates/UmbracoProject/.template.config/template.json
  src/Directory.Build.props
  src/Umbraco.Web.UI.Client/package.json
Labels: project/v9

#10472 Adds dotnetRunMessages flag to launch settings for Kestrel
  build/templates/UmbracoProject/Properties/launchSettings.json
Labels: project/v9

#10473 V9: Fix issue with recurring services that executes too often
  src/Umbraco.Infrastructure/HostedServices/RecurringHostedServiceBase.cs
  src/Umbraco.Infrastructure/HostedServices/ReportSiteTask.cs
Labels: project/v9, release/9.0.0-beta004, type/bug

#10471 Added two further notifications to the boot process.
  src/Umbraco.Core/Notifications/UmbracoApplicationComponentsInstallingNotification.cs
  src/Umbraco.Core/Notifications/UmbracoApplicationMainDomAcquiredNotification.cs
  src/Umbraco.Infrastructure/Runtime/CoreRuntime.cs
Labels: project/v9

#10475 V9 - Adds missing DataContract to FileExtensionConfigItem
  src/Umbraco.Core/PropertyEditors/FileExtensionConfigItem.cs
Labels: project/v9

#10422 Bugfix Allow you to change your own password if using user section
  src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
Labels: project/v9, type/bug

#10360 Avoid repeated reloads of content and media cache following Deploy operations.
  src/Umbraco.Tests/Cache/DistributedCacheBinderTests.cs
  src/Umbraco.Web/Cache/DistributedCacheBinder.cs
Labels: category/performance, release/8.15.0, type/feature

#10185 Get rid of ICoreComposer
  src/Umbraco.Core/Collections/TopoGraph.cs
  src/Umbraco.Core/Composing/ICoreComposer.cs
  src/Umbraco.Core/Composing/IUserComposer.cs
  src/Umbraco.Infrastructure/Compose/NotificationsComposer.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/Logging/Viewer/LogViewerComposer.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_8_0_0/DataTypes/PreValueMigratorComposer.cs
  src/Umbraco.PublishedCache.NuCache/Compose/NotificationsComposer.cs
  src/Umbraco.PublishedCache.NuCache/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
  src/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentTypeServiceVariantsTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Components/ComponentTests.cs
  src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.UI.NetCore/Startup.cs
  src/Umbraco.Web.UI.NetCore/appsettings.json
  src/Umbraco.Web/Runtime/WebFinalComposer.cs
Labels: project/v9

#10489 Moves extension methods from HtmlHelper to IHtmlHelper
  src/Umbraco.Web.Website/Extensions/HtmlHelperRenderExtensions.cs
Labels: project/v9, release/9.0.0-beta004, type/bug

#10393 V9: Add new email Model for notifications
  src/Umbraco.Core/Events/SendEmailEventArgs.cs
  src/Umbraco.Core/HealthChecks/NotificationMethods/EmailNotificationMethod.cs
  src/Umbraco.Core/Mail/IEmailSender.cs
  src/Umbraco.Core/Mail/NotImplementedEmailSender.cs
  src/Umbraco.Core/Models/Email/EmailMessage.cs
  src/Umbraco.Core/Models/Email/EmailMessageAttachment.cs
  src/Umbraco.Core/Models/Email/NotificationEmailAddress.cs
  src/Umbraco.Core/Models/Email/NotificationEmailModel.cs
  src/Umbraco.Core/Notifications/SendEmailNotification.cs
  src/Umbraco.Infrastructure/EmailSender.cs
  src/Umbraco.Infrastructure/Extensions/EmailMessageExtensions.cs
  src/Umbraco.Infrastructure/Services/Implement/NotificationService.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Extensions/EmailMessageExtensionsTests.cs
  src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
  src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
Labels: project/v9

#10451 Fix: Searching in mediapicker doesn't filter according to allowedtypes #10429
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js
Labels: project/media-picker, release/8.14.1, type/bug

#10509 V9: Updated nuget dependencies
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
  src/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
  src/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
Labels: project/v9

#10513 Add lang to extended valid elements for span
  src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
Labels: community/pr, release/8.15.0, type/bug

#10517 Add the ability to convert Media Picker v2 to v3 progressively
  src/Umbraco.Web.UI.Client/src/views/prevalueeditors/obsoletemediapickernotice.html
  src/Umbraco.Web/PropertyEditors/MediaPicker3PropertyEditor.cs
  src/Umbraco.Web/PropertyEditors/MediaPickerConfiguration.cs
  src/Umbraco.Web/PropertyEditors/ValueConverters/MediaPickerWithCropsValueConverter.cs
Labels: project/media-picker, release/8.15.0, type/feature

#9823 Reduce memory use and speed up queries by only fetching required properties from examine
  src/Umbraco.Examine/UmbracoContentIndex.cs
  src/Umbraco.Web/IPublishedContentQuery.cs
  src/Umbraco.Web/PublishedContentQuery.cs
  src/Umbraco.Web/Search/ExamineComponent.cs
  src/Umbraco.Web/Search/GenericIndexDiagnostics.cs
  src/Umbraco.Web/Search/IUmbracoTreeSearcherFields2.cs
  src/Umbraco.Web/Search/UmbracoTreeSearcher.cs
  src/Umbraco.Web/Search/UmbracoTreeSearcherFields.cs
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: category/performance, state/sprint-candidate

#9671 Reduce memory allocations and speed up text localization
  src/Umbraco.Core/Compose/RelateOnTrashComponent.cs
  src/Umbraco.Core/Services/ILocalizedTextService.cs
  src/Umbraco.Core/Services/Implement/LocalizedTextService.cs
  src/Umbraco.Core/Services/LocalizedTextServiceExtensions.cs
  src/Umbraco.Tests.Benchmarks/LocalizedTextServiceGetAllStoredValuesBenchmarks.cs
  src/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
  src/Umbraco.Tests/Models/Mapping/ContentWebModelMappingTests.cs
  src/Umbraco.Web/Compose/NotificationsComponent.cs
  src/Umbraco.Web/Editors/AuthenticationController.cs
  src/Umbraco.Web/Editors/BackOfficeController.cs
  src/Umbraco.Web/Editors/CodeFileController.cs
  src/Umbraco.Web/Editors/ContentController.cs
  src/Umbraco.Web/Editors/ContentTypeController.cs
  src/Umbraco.Web/Editors/ContentTypeControllerBase.cs
  src/Umbraco.Web/Editors/CurrentUserController.cs
  src/Umbraco.Web/Editors/DataTypeController.cs
  src/Umbraco.Web/Editors/DictionaryController.cs
  src/Umbraco.Web/Editors/MediaController.cs
  src/Umbraco.Web/Editors/MediaTypeController.cs
  src/Umbraco.Web/Editors/MemberController.cs
  src/Umbraco.Web/Editors/MemberGroupController.cs
  src/Umbraco.Web/Editors/MemberTypeController.cs
  src/Umbraco.Web/Editors/PackageInstallController.cs
  src/Umbraco.Web/Editors/TemplateQueryController.cs
  src/Umbraco.Web/Editors/UserGroupsController.cs
  src/Umbraco.Web/Editors/UsersController.cs
  src/Umbraco.Web/HealthCheck/Checks/Config/AbstractConfigCheck.cs
  src/Umbraco.Web/HealthCheck/Checks/Config/CompilationDebugCheck.cs
  src/Umbraco.Web/HealthCheck/Checks/Config/ConfigurationService.cs
  src/Umbraco.Web/HealthCheck/Checks/Config/CustomErrorsCheck.cs
  src/Umbraco.Web/HealthCheck/Checks/Config/MacroErrorsCheck.cs
  src/Umbraco.Web/HealthCheck/Checks/Config/NotificationEmailCheck.cs
  src/Umbraco.Web/HealthCheck/Checks/Config/TraceCheck.cs
  src/Umbraco.Web/HealthCheck/Checks/Config/TrySkipIisCustomErrorsCheck.cs
  src/Umbraco.Web/HealthCheck/Checks/Permissions/FolderAndFilePermissionsCheck.cs
  src/Umbraco.Web/HealthCheck/Checks/Security/BaseHttpHeaderCheck.cs
  src/Umbraco.Web/HealthCheck/Checks/Security/ExcessiveHeadersCheck.cs
  src/Umbraco.Web/HealthCheck/Checks/Security/HttpsCheck.cs
  src/Umbraco.Web/HealthCheck/Checks/Services/SmtpCheck.cs
  src/Umbraco.Web/HealthCheck/NotificationMethods/EmailNotificationMethod.cs
  src/Umbraco.Web/Macros/MacroRenderer.cs
  src/Umbraco.Web/Models/Mapping/CommonMapper.cs
  src/Umbraco.Web/Models/Mapping/ContentVariantMapper.cs
  src/Umbraco.Web/Models/Mapping/MemberTabsAndPropertiesMapper.cs
  src/Umbraco.Web/Models/Mapping/SectionMapDefinition.cs
  src/Umbraco.Web/Models/Mapping/TabsAndPropertiesMapper.cs
  src/Umbraco.Web/Models/Mapping/UserMapDefinition.cs
  src/Umbraco.Web/Models/Trees/MenuItem.cs
  src/Umbraco.Web/Models/Trees/MenuItemList.cs
  src/Umbraco.Web/PropertyEditors/BlockEditorPropertyEditor.cs
  src/Umbraco.Web/PropertyEditors/DropDownFlexibleConfigurationEditor.cs
  src/Umbraco.Web/PropertyEditors/UploadFileTypeValidator.cs
  src/Umbraco.Web/PropertyEditors/ValueListConfigurationEditor.cs
  src/Umbraco.Web/Routing/UrlProviderExtensions.cs
  src/Umbraco.Web/Trees/ApplicationTreeController.cs
  src/Umbraco.Web/Trees/ContentTreeControllerBase.cs
  src/Umbraco.Web/Trees/DataTypeTreeController.cs
  src/Umbraco.Web/Trees/MediaTypeTreeController.cs
  src/Umbraco.Web/Trees/MemberTreeController.cs
  src/Umbraco.Web/Trees/Tree.cs
Labels: category/performance, community/pr, community/review, release/8.15.0, state/sprint-candidate

#10235 Optimizations related to BlockEditorPropertyEditor.ToEditor()
  src/Umbraco.Core/PropertyEditors/DataEditor.cs
  src/Umbraco.Tests/Web/Controllers/ContentControllerTests.cs
  src/Umbraco.Web.UI.Client/src/common/resources/content.resource.js
  src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
  src/Umbraco.Web.UI.Client/test/unit/common/services/block-editor-service.spec.js
  src/Umbraco.Web/Editors/ContentController.cs
  src/Umbraco.Web/PropertyEditors/BlockEditorPropertyEditor.cs
Labels: category/performance, release/8.15.0

#10376 Fix Rollback feature not creating diffs when properties are moved between tabs in EditorModel events
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/rollback/rollback.controller.js
Labels: category/ux, community/pr, release/8.15.0, type/bug

#10529 Improvements to media pickers/crop handling and URL generation
  src/Umbraco.Core/Models/MediaWithCrops.cs
  src/Umbraco.Core/PropertyEditors/ImageCropperConfiguration.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/ImageCropperValue.cs
  src/Umbraco.Tests/PropertyEditors/ImageCropperTest.cs
  src/Umbraco.Web/ImageCropperTemplateCoreExtensions.cs
  src/Umbraco.Web/ImageCropperTemplateExtensions.cs
  src/Umbraco.Web/PropertyEditors/MediaPicker3Configuration.cs
  src/Umbraco.Web/PropertyEditors/ValueConverters/BlockListPropertyValueConverter.cs
  src/Umbraco.Web/PropertyEditors/ValueConverters/MediaPickerWithCropsValueConverter.cs
  src/Umbraco.Web/UrlHelperRenderExtensions.cs
Labels: category/breaking, category/front-end, project/media-picker, release/8.15.0, status/needs-docs, type/feature

#10521 Reduce sql queries when rendering blocklists in the content panel
  src/Umbraco.Core/Services/IContentService.cs
  src/Umbraco.Core/Services/Implement/ContentService.cs
  src/Umbraco.Web/Editors/ContentController.cs
  src/Umbraco.Web/Models/Mapping/ContentMapDefinition.cs
Labels: category/performance, release/8.15.0, type/feature

#10453 Textstring prevalue editor view: Set id attribute
  src/Umbraco.Web.UI.Client/src/views/prevalueeditors/textstring.html
Labels: category/ux, community/pr, release/8.15.0, type/bug

#10236 Nested content optimizations
  src/Umbraco.Web/PropertyEditors/NestedContentPropertyEditor.cs
Labels: category/performance, release/8.15.0, type/feature

#10257 Ability to configure a remote URL for displaying different content on the content dashboard
  src/Umbraco.Core/Constants-AppSettings.cs
  src/Umbraco.Core/Dashboards/ContentDashboardSettings.cs
  src/Umbraco.Core/Dashboards/IContentDashboardSettings.cs
  src/Umbraco.Web.UI/web.Template.config
  src/Umbraco.Web/Editors/DashboardController.cs
Labels: release/8.15.0, type/feature

#10562 #10520 ensure property culture in Nested Content
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
Labels: state/sprint-candidate
