Repository umbraco/Umbraco-CMS, pull requests merged in 2021-05, with the labels that each got.

#10199 Backport cache key fix and optimizations
  src/Umbraco.Core/Cache/DefaultRepositoryCachePolicy.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/ConsentRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/DictionaryRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/DocumentRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/MediaRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/MemberRepository.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/RepositoryCacheKeys.cs
  src/Umbraco.Core/Persistence/Repositories/Implement/UserRepository.cs
  src/Umbraco.Web/Cache/ContentCacheRefresher.cs
  src/Umbraco.Web/Cache/MacroCacheRefresher.cs
  src/Umbraco.Web/Cache/MediaCacheRefresher.cs
  src/Umbraco.Web/Cache/MemberCacheRefresher.cs
  src/Umbraco.Web/Cache/RelationTypeCacheRefresher.cs
  src/Umbraco.Web/Cache/UserCacheRefresher.cs
  src/Umbraco.Web/Cache/UserGroupCacheRefresher.cs
Labels: category/performance, release/8.14.0, type/feature

#10216 V9: Implementing Error Describers for translated error messages
  src/Umbraco.Infrastructure/Security/BackOfficeErrorDescriber.cs
  src/Umbraco.Infrastructure/Security/UmbracoErrorDescriberBase.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberManagerTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Security/MemberSignInManagerTests.cs
  src/Umbraco.Web.UI.NetCore/umbraco/config/lang/en_us.xml
Labels: project/net-core, release/netcore-beta002

#10134 Block List and Nested Content browser performance problem - don't run heavy count method on `$watch`
  src/Umbraco.Web.UI.Client/src/common/directives/validation/valformmanager.directive.js
Labels: release/8.14.0, state/sprint-candidate

#10222 Netcore: dotnet new template updates and change HideTopLevelNodeFromPath default value to `true`
  build/templates/UmbracoProject/.template.config/dotnetcli.host.json
  build/templates/UmbracoProject/appsettings.Development.json
  build/templates/UmbracoProject/appsettings.json
  src/Umbraco.Core/Configuration/Models/GlobalSettings.cs
Labels: project/net-core, release/netcore-beta002

#10157 Review AB11194 — Improve media selector UX
  src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbfiledropzone.directive.js
  src/Umbraco.Web.UI.Client/src/common/services/mediatypehelper.service.js
  src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
Labels: category/ux, state/sprint-candidate

#10208 Casing in appsettings:umbraco:cms:contentMacroErrors and using MacroErrorBehaviour Enum
  src/Umbraco.Core/HealthChecks/Checks/Configuration/MacroErrorsCheck.cs
  src/Umbraco.Infrastructure/Configuration/JsonConfigManipulator.cs
  src/Umbraco.Web.UI.NetCore/appsettings.json
Labels: project/net-core

#10209 Fix issue with hardcoded '\' as directory separator char.
  src/Umbraco.Core/Packaging/CompiledPackageXmlParser.cs
Labels: project/net-core, release/netcore-beta002

#10224 Netcore: V9 Enable Microsoft SouceLink Debugging Feature
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.Persistence.SqlCe/Umbraco.Persistence.SqlCe.csproj
  src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
  src/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
  src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
  src/Umbraco.Web.Website/Umbraco.Web.Website.csproj
Labels: project/net-core, release/netcore-beta002

#9691 Dont let validation issues prevent saving
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
  src/Umbraco.Web.UI.Client/src/common/directives/validation/valformmanager.directive.js
  src/Umbraco.Web.UI.Client/src/common/services/contenteditinghelper.service.js
  src/Umbraco.Web.UI.Client/src/less/alerts.less
  src/Umbraco.Web.UI.Client/src/less/components/editor/umb-variant-switcher.less
  src/Umbraco.Web.UI.Client/src/less/components/overlays.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-editor-navigation-item.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-list.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-nested-content.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-tabs.less
  src/Umbraco.Web.UI.Client/src/less/forms.less
  src/Umbraco.Web.UI.Client/src/less/variables.less
  src/Umbraco.Web.UI.Client/src/views/content/overlays/save.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/inlineblock/inlineblock.editor.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/blocklistentryeditors/labelblock/labelblock.editor.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.less
Labels: category/ux, state/sprint-candidate

#10230 Fixes FileUploadCleanupFilterAttribute when incomimg model is not provided.
  src/Umbraco.Web.BackOffice/Filters/FileUploadCleanupFilterAttribute.cs
Labels: project/net-core

#10205 Replaces System.Drawing with ImageSharp, and thereby fix TODO.
  src/Umbraco.Infrastructure/Media/ImageDimensionExtractor.cs
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
Labels: project/net-core, release/netcore-beta002

#10234 V9: Bugfix for modelsbuilder when having inherited doctypes
  src/Umbraco.Core/Models/PublishedContent/PublishedContentModel.cs
  src/Umbraco.Core/Models/PublishedContent/PublishedContentWrapped.cs
  src/Umbraco.Core/Models/PublishedContent/PublishedElementModel.cs
  src/Umbraco.Core/Models/PublishedContent/PublishedElementWrapped.cs
  src/Umbraco.Infrastructure/ModelsBuilder/Building/TextBuilder.cs
  src/Umbraco.Tests.Common/Published/PublishedSnapshotTestObjects.cs
  src/Umbraco.Tests.Common/TestHelpers/SolidPublishedSnapshot.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Published/NestedContentTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.ModelsBuilder.Embedded/BuilderTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/ModelBinders/ContentModelBinderTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Views/UmbracoViewPageTests.cs
  src/Umbraco.Tests/PublishedContent/PublishedContentTests.cs
  src/Umbraco.Tests/PublishedContent/SolidPublishedSnapshot.cs
Labels: project/net-core, release/netcore-beta002

#10238 V9 Netcore: Fix missing launch browser param for dotnet run from template
  build/templates/UmbracoProject/Properties/launchSettings.json
  src/Umbraco.Web.UI.NetCore/Properties/launchSettings.json
Labels: project/net-core

#10237 Deterministic Builds for Sourcelink
  src/Directory.Build.props
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.Persistence.SqlCe/Umbraco.Persistence.SqlCe.csproj
  src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
  src/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
  src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
  src/Umbraco.Web.Website/Umbraco.Web.Website.csproj
Labels: project/net-core

#10244 V9: Do not save runtime level in ctors
  src/Umbraco.Core/PublishedCache/DefaultCultureAccessor.cs
  src/Umbraco.Infrastructure/Services/Implement/UserService.cs
Labels: project/net-core, release/netcore-beta002

#10158 Fix copy button being inactive when selecting a valid item
  src/Umbraco.Web.UI.Client/src/views/content/content.copy.controller.js
Labels: category/ux, community/pr, release/8.14.0, type/bug

#10146 Updates to Examine 1.2.0
  build/NuSpecs/UmbracoCms.Web.nuspec
  src/Umbraco.Examine/Umbraco.Examine.csproj
  src/Umbraco.Examine/UmbracoExamineIndex.cs
  src/Umbraco.Tests/Umbraco.Tests.csproj
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: release/8.14.0, type/feature

#9771 Move the SetWeight logic to WeightedCollectionBuilderBase
  src/Umbraco.Core/Composing/WeightedCollectionBuilderBase.cs
  src/Umbraco.Tests/Composing/CollectionBuildersTests.cs
  src/Umbraco.Web/Dashboards/DashboardCollectionBuilder.cs
Labels: community/pr, release/8.14.0

#10202 #10193 The listview search within a dialog (eg. minilistview) shows the loading indicator forever for zero results
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbminilistview.directive.js
  src/Umbraco.Web.UI.Client/src/views/components/umb-mini-list-view.html
Labels: category/ui, community/pr, release/8.14.0, type/bug

#10277 Update version and artifact name generated by azure pipeline
  build/azure-pipelines.yml
  src/Umbraco.Web.UI.Client/package-lock.json
Labels: project/v9

#10291 Bugfix: Acquire the maindom before we do unattended installs
  src/Umbraco.Infrastructure/Runtime/CoreRuntime.cs
Labels: project/v9

#10294 Update nuget packages
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
  src/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
  src/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  src/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
  src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilder.ImageSharp.cs
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  src/Umbraco.Web.UI.NetCore/Umbraco.Web.UI.NetCore.csproj
  src/Umbraco.Web/Umbraco.Web.csproj
Labels: project/v9, release/9.0.0-beta003

#10286 V9: Do not restart doing simple installs without package installation
  src/Umbraco.Core/Services/IRuntime.cs
  src/Umbraco.Infrastructure/Cache/DatabaseServerMessengerNotificationHandler.cs
  src/Umbraco.Infrastructure/Examine/RebuildOnStartupHandler.cs
  src/Umbraco.Infrastructure/Persistence/UmbracoDatabaseFactory.cs
  src/Umbraco.Infrastructure/Runtime/CoreRuntime.cs
  src/Umbraco.Tests.UnitTests/AutoFixture/AutoMoqDataAttribute.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/FileNameTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Routing/BackOfficeAreaRoutesTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Routing/InstallAreaRoutesTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Routing/PreviewRoutesTests.cs
  src/Umbraco.Web.BackOffice/Controllers/PackageInstallController.cs
  src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.BackOffice/Extensions/LinkGeneratorExtensions.cs
  src/Umbraco.Web.BackOffice/Extensions/UmbracoApplicationBuilder.Installer.cs
  src/Umbraco.Web.BackOffice/Install/CreateUnattendedUserNotificationHandler.cs
  src/Umbraco.Web.BackOffice/Install/InstallApiController.cs
  src/Umbraco.Web.BackOffice/Install/InstallAreaRoutes.cs
  src/Umbraco.Web.BackOffice/Install/InstallAuthorizeAttribute.cs
  src/Umbraco.Web.BackOffice/Install/InstallController.cs
  src/Umbraco.Web.BackOffice/Routing/BackOfficeAreaRoutes.cs
  src/Umbraco.Web.BackOffice/Routing/PreviewRoutes.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Extensions/LinkGeneratorExtensions.cs
  src/Umbraco.Web.Common/Middleware/UmbracoRequestMiddleware.cs
  src/Umbraco.Web.Common/Profiler/InitializeWebProfiling.cs
  src/Umbraco.Web.Common/Profiler/WebProfiler.cs
  src/Umbraco.Web.UI.Client/src/installer/installer.service.js
Labels: project/v9, release/9.0.0-beta003

#10299 V9: Allow custom notification publisher in scope
  src/Umbraco.Infrastructure/Scoping/IScopeProvider.cs
  src/Umbraco.Infrastructure/Scoping/Scope.cs
  src/Umbraco.Infrastructure/Scoping/ScopeProvider.cs
  src/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/ExamineBaseTest.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Core/Scoping/ScopedNotificationPublisherTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/LogScrubberTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Mapping/MappingTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/MigrationTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberUserStoreTests.cs
  src/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Controllers/MemberControllerUnitTests.cs
Labels: category/breaking, project/v9, release/9.0.0-beta003

#10314 NETCore: Fix dotnet new template for safe namespaces
  build/templates/UmbracoProject/.template.config/template.json
  build/templates/UmbracoProject/UmbracoProject.csproj
Labels: category/dx, project/v9

#10320 V9: Fix issue with determining the uploaded media type
  src/Umbraco.Infrastructure/PropertyEditors/FileUploadPropertyEditor.cs
Labels: project/v9, release/9.0.0-beta003

#10272 Rename models builder modes
  src/Umbraco.Core/Configuration/Models/ModelsBuilderSettings.cs
  src/Umbraco.Core/Configuration/ModelsMode.cs
  src/Umbraco.Core/Configuration/ModelsModeExtensions.cs
  src/Umbraco.Core/Extensions/PublishedModelFactoryExtensions.cs
  src/Umbraco.Core/Models/PublishedContent/IAutoPublishedModelFactory.cs
  src/Umbraco.Infrastructure/ModelsBuilder/AutoModelsNotificationHandler.cs
  src/Umbraco.Infrastructure/ModelsBuilder/Building/Builder.cs
  src/Umbraco.Infrastructure/ModelsBuilder/Building/PropertyModel.cs
  src/Umbraco.Infrastructure/ModelsBuilder/ModelsBuilderAssemblyAttribute.cs
  src/Umbraco.Infrastructure/ModelsBuilder/UmbracoServices.cs
  src/Umbraco.PublishedCache.NuCache/PublishedSnapshotService.cs
  src/Umbraco.Web.BackOffice/ModelsBuilder/DashboardReport.cs
  src/Umbraco.Web.BackOffice/ModelsBuilder/ModelsBuilderDashboardController.cs
  src/Umbraco.Web.Common/Filters/ModelBindingExceptionAttribute.cs
  src/Umbraco.Web.Common/ModelsBuilder/DependencyInjection/UmbracoBuilderDependencyInjectionExtensions.cs
  src/Umbraco.Web.Common/ModelsBuilder/InMemoryModelFactory.cs
  src/Umbraco.Web.Common/ModelsBuilder/ModelsBuilderNotificationHandler.cs
  src/Umbraco.Web.Common/ModelsBuilder/RefreshingRazorViewEngine.cs
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.NetCore/appsettings.json
  src/Umbraco.Web.UI/web.Template.config
Labels: project/v9

#10311 added cdata on sectionMandatoryDesc for other languages
  src/Umbraco.Web.UI/Umbraco/config/lang/cy.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/de.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/es.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/fr.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/pl.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/ru.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/tr.xml
Labels: category/ux, community/pr, release/8.15.0, type/bug

#10163 Fixed 10144: Prevalue alias not set
  src/Umbraco.Web.UI.Client/src/common/services/datatypehelper.service.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/datatypesettings/datatypesettings.controller.js
  src/Umbraco.Web.UI.Client/src/views/datatypes/datatype.edit.controller.js
Labels: category/ui, community/pr, release/8.15.0, type/bug

#10023 Replaced angular.extend with Utilities.extend
  src/Umbraco.Web.UI.Client/.babelrc
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/common/directives/components/grid/grid.rte.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbaceeditor.directive.js
  src/Umbraco.Web.UI.Client/src/common/resources/content.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/log.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/logviewer.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/media.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/member.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/relationtype.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/users.resource.js
  src/Umbraco.Web.UI.Client/src/common/services/keyboard.service.js
  src/Umbraco.Web.UI.Client/src/common/services/searchresultformatter.service.js
  src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
  src/Umbraco.Web.UI.Client/src/utilities.js
  src/Umbraco.Web.UI.Client/src/views/prevalueeditors/colorpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/prevalueeditors/mediapicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/prevalueeditors/treepicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/datepicker/datepicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/dropdownFlexible/dropdownFlexible.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/imagecropper/imagecropper.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/memberpicker/memberpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.controller.js
Labels: community/pr, release/8.15.0, type/feature

#10338 Updates benchmark proj to net5, adds TypeLoader benchmarks
  src/Umbraco.Core/Composing/TypeFinder.cs
  src/Umbraco.Core/Composing/TypeLoader.cs
  src/Umbraco.Tests.Benchmarks/CtorInvokeBenchmarks.cs.bak
  src/Umbraco.Tests.Benchmarks/ReflectionUtilities-Unused.cs.bak
  src/Umbraco.Tests.Benchmarks/TypeFinderBenchmarks.cs
  src/Umbraco.Tests.Benchmarks/TypeLoaderBenchmarks.cs
  src/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
Labels: project/v9
