Repository umbraco/Umbraco-CMS, pull requests merged in 2022-09, with the labels that each got.

#12939 Fix breaking change in DictionaryMapDefinition
  src/Umbraco.Core/Models/Mapping/DictionaryMapDefinition.cs
Labels: release/10.2.0

#12922 Use SVG logo in installer/upgrader
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoInstall/Index.cshtml
  src/Umbraco.Web.UI.Client/src/less/components/application/umb-app-header.less
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-app-header.html
  src/Umbraco.Web.UI.Client/src/views/errors/BootFailed.html
Labels: community/pr, category/ui

#12920 V9: upgrade backoffice dependencies
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
Labels: status/dependency-update, type/bug, release/9.5.4

#12930 New backoffice: language controller
  src/Umbraco.Cms.ManagementApi/Controllers/Culture/CultureControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Culture/GetAllCultureController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Language/CreateLanguageController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Language/CultureLanguageController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Language/DeleteLanguageController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Language/GetAllLanguageController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Language/GetLanguageController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Language/LanguageControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Language/UpdateLanguageController.cs
  src/Umbraco.Cms.ManagementApi/DependencyInjection/InstallerBuilderExtensions.cs
  src/Umbraco.Cms.ManagementApi/DependencyInjection/MappingBuilderExtensions.cs
  src/Umbraco.Cms.ManagementApi/DependencyInjection/ServicesBuilderExtensions.cs
  src/Umbraco.Cms.ManagementApi/ManagementApiComposer.cs
  src/Umbraco.Cms.ManagementApi/Mapping/Culture/CultureViewModelMapDefinition.cs
  src/Umbraco.Cms.ManagementApi/Mapping/Languages/LanguageViewModelsMapDefinition.cs
  src/Umbraco.Cms.ManagementApi/ViewModels/Culture/CultureViewModel.cs
  src/Umbraco.Cms.ManagementApi/ViewModels/Language/LanguageViewModel.cs
  src/Umbraco.Core/Models/Mapping/LanguageMapDefinition.cs
  src/Umbraco.Core/Models/PagedModel.cs
  src/Umbraco.Core/Services/ILocalizationService.cs
  src/Umbraco.New.Cms.Core/Services/Installer/ILanguageService.cs
  src/Umbraco.New.Cms.Core/Services/Languages/LanguageService.cs
Labels: project/new-backoffice

#12931 New backoffice: Problem details builder
  src/Umbraco.Cms.ManagementApi/Builders/ProblemDetailsBuilder.cs
  src/Umbraco.Cms.ManagementApi/Controllers/NewInstallController.cs
Labels: project/new-backoffice

#12956 New backoffice: Dictionary controller
  src/Umbraco.Cms.ManagementApi/Controllers/Dictionary/CreateDictionaryController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Dictionary/DeleteDictionaryController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Dictionary/DictionaryControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Dictionary/ExportDictionaryController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Dictionary/GetAllDictionaryController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Dictionary/GetDictionaryController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Dictionary/ImportDictionaryController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Dictionary/MoveDictionaryController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Dictionary/UpdateDictionaryController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Dictionary/UploadDictionaryController.cs
  src/Umbraco.Cms.ManagementApi/DependencyInjection/FactoriesBuilderExtensions.cs
  src/Umbraco.Cms.ManagementApi/DependencyInjection/InstallerBuilderExtensions.cs
  src/Umbraco.Cms.ManagementApi/DependencyInjection/ServicesBuilderExtensions.cs
  src/Umbraco.Cms.ManagementApi/Factories/DictionaryFactory.cs
  src/Umbraco.Cms.ManagementApi/Factories/IDictionaryFactory.cs
  src/Umbraco.Cms.ManagementApi/ManagementApiComposer.cs
  src/Umbraco.Cms.ManagementApi/Mapping/Dictionary/DictionaryViewModelMapDefinition.cs
  src/Umbraco.Cms.ManagementApi/Services/IJsonPatchService.cs
  src/Umbraco.Cms.ManagementApi/Services/JsonPatchService.cs
  src/Umbraco.Cms.ManagementApi/Umbraco.Cms.ManagementApi.csproj
  src/Umbraco.Cms.ManagementApi/ViewModels/Dictionary/DictionaryImportViewModel.cs
  src/Umbraco.Cms.ManagementApi/ViewModels/Dictionary/DictionaryItemViewModel.cs
  src/Umbraco.Cms.ManagementApi/ViewModels/Dictionary/DictionaryItemsImportViewModel.cs
  src/Umbraco.Cms.ManagementApi/ViewModels/Dictionary/DictionaryOverviewViewModel.cs
  src/Umbraco.Cms.ManagementApi/ViewModels/Dictionary/DictionaryTranslationOverviewViewModel.cs
  src/Umbraco.Cms.ManagementApi/ViewModels/Dictionary/DictionaryTranslationViewModel.cs
  src/Umbraco.Cms.ManagementApi/ViewModels/Dictionary/DictionaryViewModel.cs
  src/Umbraco.Cms.ManagementApi/ViewModels/JsonPatch/JsonPatchViewModel.cs
  src/Umbraco.Cms.ManagementApi/ViewModels/Move/MoveViewModel.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Core/Models/ContentEditing/DictionaryTranslationDisplay.cs
  src/Umbraco.Core/Models/Mapping/DictionaryMapDefinition.cs
  src/Umbraco.Core/Services/DictionaryService.cs
  src/Umbraco.Core/Services/IDictionaryService.cs
Labels: project/new-backoffice

#12957 New backoffice: Analytics controller
  src/Umbraco.Cms.ManagementApi/Controllers/Analytics/AnalyticsControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Analytics/GetAllAnalyticsController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Analytics/GetAnalyticsController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Analytics/SetAnalyticsController.cs
  src/Umbraco.Cms.ManagementApi/DependencyInjection/FactoryBuilderExtensions.cs
  src/Umbraco.Cms.ManagementApi/Factories/IPagedViewModelFactory.cs
  src/Umbraco.Cms.ManagementApi/Factories/PagedViewModelFactory.cs
  src/Umbraco.Cms.ManagementApi/ViewModels/Analytics/AnalyticsLevelViewModel.cs
Labels: project/new-backoffice

#12958 New backoffice: Help controller
  src/Umbraco.Cms.ManagementApi/Controllers/Help/GetHelpController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Help/HelpControllerBase.cs
  src/Umbraco.Cms.ManagementApi/ViewModels/Help/HelpPageViewModel.cs
Labels: project/new-backoffice

#12961 New backoffice: Relation controller
  src/Umbraco.Cms.ManagementApi/Controllers/Relation/GetByChildRelationController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Relation/GetRelationController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Relation/RelationControllerBase.cs
  src/Umbraco.Cms.ManagementApi/DependencyInjection/FactoryBuilderExtensions.cs
  src/Umbraco.Cms.ManagementApi/DependencyInjection/InstallerBuilderExtensions.cs
  src/Umbraco.Cms.ManagementApi/DependencyInjection/MappingBuilderExtensions.cs
  src/Umbraco.Cms.ManagementApi/Factories/IRelationViewModelFactory.cs
  src/Umbraco.Cms.ManagementApi/Factories/RelationViewModelFactory.cs
  src/Umbraco.Cms.ManagementApi/Mapping/Relation/RelationViewModelsMapDefinition.cs
  src/Umbraco.Cms.ManagementApi/ViewModels/Relation/RelationViewModel.cs
Labels: project/new-backoffice

#12934 Backoffice api: Refactor controllers
  src/Umbraco.Cms.ManagementApi/Controllers/Install/InstallControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Install/SettingsInstallController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Install/SetupInstallController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Install/ValidateDatabaseInstallController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/NewInstallController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Upgrade/AuthorizeUpgradeController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Upgrade/SettingsUpgradeController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Upgrade/UpgradeControllerBase.cs
  src/Umbraco.New.Cms.Web.Common/Installer/SignInUserStep.cs
Labels: project/new-backoffice

#13014 v10: Update JS dependencies
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
Labels: dependencies, release/10.3.0

#13020 pass in parameters needed to member service
  src/Umbraco.Core/Services/MemberService.cs
Labels: type/bug, release/10.3.0

#13022 Missing methods from IMemberService
  src/Umbraco.Core/Services/IMemberService.cs
  src/Umbraco.Core/Services/MemberService.cs
Labels: type/bug

#13016 V10: Fix to allow dragged images in the rich text editor to be correctly uploaded
  src/Umbraco.Core/Extensions/StringExtensions.cs
  src/Umbraco.Core/IO/IOHelper.cs
  src/Umbraco.Core/IO/IOHelperLinux.cs
  src/Umbraco.Core/IO/IOHelperOSX.cs
  src/Umbraco.Core/IO/IOHelperWindows.cs
  src/Umbraco.Web.BackOffice/Controllers/TinyMceController.cs
  src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/ShortStringHelper/StringExtensionsTests.cs
Labels: category/front-end, type/bug, release/10.3.0

#13031 v10: add Umbraco UI Library to the backoffice
  src/Umbraco.Infrastructure/WebAssets/BackOfficeWebAssets.cs
  src/Umbraco.Infrastructure/WebAssets/JsInitialize.js
  src/Umbraco.Web.UI.Client/gulp/tasks/dependencies.js
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
Labels: category/ui, category/notable, release/10.3.0

#12998 New backoffice/add system text json configuration attribute
  src/Umbraco.Cms.ManagementApi/Controllers/ManagementApiControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Filters/ManagementApiJsonConfigurationAttribute.cs
  src/Umbraco.Cms.ManagementApi/Filters/ManagementApiJsonOutputFormatter.cs
Labels: project/new-backoffice

#13033 Only contain style instead of full layout
  src/Umbraco.Web.UI.Client/src/less/components/umb-property-editor.less
Labels: type/bug

#13013 V11: Update the rich text editor TinyMCE to v6
  src/Umbraco.Core/Configuration/Models/RichTextEditorSettings.cs
  src/Umbraco.Core/Extensions/StringExtensions.cs
  src/Umbraco.Infrastructure/WebAssets/Resources.Designer.cs
  src/Umbraco.Infrastructure/WebAssets/TinyMceInitialize.js
  src/Umbraco.Web.UI.Client/gulp/tasks/dependencies.js
  src/Umbraco.Web.UI.Client/gulpfile.js
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/common/directives/components/grid/grid.rte.directive.js
  src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
  src/Umbraco.Web.UI.Client/src/less/rte.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.html
  src/Umbraco.Web.UI/appsettings.Development.template.json
  tests/Umbraco.Tests.AcceptanceTest/cypress/integration/Content/content.ts
  tests/Umbraco.Tests.AcceptanceTest/package-lock.json
  tests/Umbraco.Tests.AcceptanceTest/package.json
  tests/Umbraco.Tests.AcceptanceTest/tsconfig.json
Labels: category/breaking, category/ui, dependencies, category/notable, project/v11, release/11.0.0

#12992 Ensure consistent margin on headings in tree root
  src/Umbraco.Web.UI.Client/src/less/components/tree/umb-tree-root.less
Labels: community/pr, category/ui, type/bug, release/10.2.1

#13044 Fix regression of active pips handling with noUiSlider
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbrangeslider.directive.js
  src/Umbraco.Web.UI.Client/src/installer/steps/user.controller.js
Labels: type/bug, release/10.2.1

#13038 New endpoint for web profiling dashboard
  src/Umbraco.Cms.ManagementApi/Controllers/Profiling/ProfilingControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Profiling/StatusProfilingController.cs
  src/Umbraco.Cms.ManagementApi/OpenApi.json
  src/Umbraco.Cms.ManagementApi/ViewModels/Profiling/ProfilingStatusViewModel.cs
Labels: project/new-backoffice

#13034 New Backoffice: Published cache controller
  src/Umbraco.Cms.ManagementApi/Controllers/PublishedCache/CollectPublishedCacheController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/PublishedCache/PublishedCacheControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/PublishedCache/RebuildPublishedCacheController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/PublishedCache/ReloadPublishedCacheController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/PublishedCache/StatusPublishedCacheController.cs
  src/Umbraco.Cms.ManagementApi/OpenApi.json
  tests/Umbraco.Tests.Integration/NewBackoffice/OpenAPIContractTest.cs
Labels: project/new-backoffice

#13055 Make sure swagger tags and operations are sorted alphabetically
  src/Umbraco.Cms.ManagementApi/ManagementApiComposer.cs
  src/Umbraco.Cms.ManagementApi/OpenApi.json
Labels: project/new-backoffice

#12981 New backoffice: examine management controller
  src/Umbraco.Cms.ManagementApi/Controllers/ExamineManagement/ExamineManagementControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/ExamineManagement/IndexExamineManagementController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/ExamineManagement/IndexesExamineManagementController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/ExamineManagement/RebuildExamineManagementController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/ExamineManagement/SearchExamineManagementController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/ExamineManagement/SearchersExamineManagementController.cs
  src/Umbraco.Cms.ManagementApi/DependencyInjection/ExamineManagementBuilderExtensions.cs
  src/Umbraco.Cms.ManagementApi/Factories/ExamineIndexViewModelFactory.cs
  src/Umbraco.Cms.ManagementApi/Factories/IExamineIndexViewModelFactory.cs
  src/Umbraco.Cms.ManagementApi/ManagementApiComposer.cs
  src/Umbraco.Cms.ManagementApi/OpenApi.json
  src/Umbraco.Cms.ManagementApi/Services/ExamineManagerService.cs
  src/Umbraco.Cms.ManagementApi/Services/IExamineManagerService.cs
  src/Umbraco.Cms.ManagementApi/ViewModels/ExamineManagement/ExamineIndexViewModel.cs
  src/Umbraco.Cms.ManagementApi/ViewModels/ExamineManagement/FieldViewModel.cs
  src/Umbraco.Cms.ManagementApi/ViewModels/ExamineManagement/SearchResultViewModel.cs
  src/Umbraco.Cms.ManagementApi/ViewModels/ExamineManagement/SearcherViewModel.cs
  src/Umbraco.New.Cms.Infrastructure/Services/IIndexingRebuilderService.cs
  src/Umbraco.New.Cms.Infrastructure/Services/IndexingRebuilderService.cs
Labels: project/new-backoffice

#13068 Searchers endpoint should return ActionResult
  src/Umbraco.Cms.ManagementApi/Controllers/ExamineManagement/SearchersExamineManagementController.cs
Labels: project/new-backoffice
