Repository umbraco/Umbraco-CMS, pull requests merged in 2022-04, with the labels that each got.

#12220 busfy => busy
  src/Umbraco.Web.UI.Client/src/views/users/user.controller.js
Labels: community/pr, type/bug

#12224 Fix KeepAlive Config so that value from appsettings.json is used
  src/Umbraco.Core/Configuration/Models/KeepAliveSettings.cs
Labels: community/pr, type/bug, release/9.5.0

#12045 Clean up and improve project templates
  build/NuSpecs/buildTransitive/Umbraco.Cms.StaticAssets.props
  build/NuSpecs/buildTransitive/Umbraco.Cms.StaticAssets.targets
  build/azure-pipelines.yml
  build/build.ps1
  src/JsonSchema/JsonSchema.csproj
  src/Umbraco.Web.UI/Program.cs
  src/Umbraco.Web.UI/Startup.cs
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  templates/Umbraco.Templates.nuspec
  templates/UmbracoPackage/.template.config/dotnetcli.host.json
  templates/UmbracoPackage/.template.config/ide.host.json
  templates/UmbracoPackage/.template.config/template.json
  templates/UmbracoPackage/App_Plugins/UmbracoPackage/package.manifest
  templates/UmbracoPackage/UmbracoPackage.csproj
  templates/UmbracoPackage/build/UmbracoPackage.targets
  templates/UmbracoProject/.gitignore
  templates/UmbracoProject/.template.config/dotnetcli.host.json
  templates/UmbracoProject/.template.config/ide.host.json
  templates/UmbracoProject/.template.config/template.json
  templates/UmbracoProject/UmbracoProject.csproj
  templates/UmbracoProject/appsettings.Development.json
  templates/UmbracoProject/appsettings.json
  tests/Umbraco.TestData/Umbraco.TestData.csproj
  tests/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
  tests/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
  tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
Labels: state/sprint-candidate

#12142 Simplified setup of 2FA for users
  .gitignore
  src/Umbraco.Core/Models/UserTwoFactorProviderModel.cs
  src/Umbraco.Core/Services/ITwoFactorLoginService.cs
  src/Umbraco.Infrastructure/Security/BackOfficeUserStore.cs
  src/Umbraco.Infrastructure/Security/UmbracoUserManager.cs
  src/Umbraco.Infrastructure/Services/Implement/TwoFactorLoginService.cs
  src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeServerVariables.cs
  src/Umbraco.Web.BackOffice/Controllers/TwoFactorLoginController.cs
  src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilder.BackOfficeAuth.cs
  src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilder.BackOfficeIdentity.cs
  src/Umbraco.Web.BackOffice/Security/DefaultBackOfficeTwoFactorOptions.cs
  src/Umbraco.Web.BackOffice/Security/NoopBackOfficeTwoFactorOptions.cs
  src/Umbraco.Web.BackOffice/Security/TwoFactorLoginViewOptions.cs
  src/Umbraco.Web.Common/Security/BackOfficeUserManager.cs
  src/Umbraco.Web.Common/Security/MemberManager.cs
  src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbappheader.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/application/umblogin.directive.js
  src/Umbraco.Web.UI.Client/src/common/resources/twofactorlogin.resource.js
  src/Umbraco.Web.UI.Client/src/common/services/notifications.service.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/twofactor/configuretwofactor.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/twofactor/configuretwofactor.html
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/twofactor/disabletwofactor.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/twofactor/disabletwofactor.html
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/user/user.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/user/user.html
  src/Umbraco.Web.UI.Client/src/views/common/login-2fa.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/login-2fa.html
  src/Umbraco.Web.UI.Client/src/views/common/overlays/user/user.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/overlays/user/user.html
  src/Umbraco.Web.UI.Client/src/views/users/user.controller.js
  src/Umbraco.Web.UI.Client/src/views/users/views/user/details.controller.js
  src/Umbraco.Web.UI.Client/src/views/users/views/user/details.html
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  src/Umbraco.Web.UI/umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
  tests/Umbraco.Tests.AcceptanceTest/cypress/integration/Tours/backofficeTour.ts
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Security/BackOfficeUserStoreTests.cs
Labels: category/notable, type/feature, release/9.5.0

#12207 Fix member last login date not being set
  src/Umbraco.Infrastructure/Security/MemberUserStore.cs
Labels: type/bug

#12149 V9/tmp nucache lock
  src/Umbraco.Core/Configuration/Models/NuCacheSettings.cs
  src/Umbraco.PublishedCache.NuCache/ContentStore.cs
  src/Umbraco.PublishedCache.NuCache/PublishedSnapshotService.cs
Labels: status/needs-docs

#12216 V8: Fix member last login date not being set
  src/Umbraco.Web/Security/Providers/UmbracoMembershipProvider.cs
Labels: type/bug

#12233 Ported over the fixes in #11858 "Check media Parent for permissions when setting correct MediaType" to target v8
  src/Umbraco.Web.UI/Umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml
  src/Umbraco.Web/Editors/MediaController.cs
Labels: community/pr, type/bug, release/8.18.4

#12282 V9: Fix member properties always being sensitive
  src/Umbraco.Core/Models/MemberType.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/ContentTypeTests.cs
Labels: type/bug

#12283 Dependency updates
  src/JsonSchema/JsonSchema.csproj
  src/Umbraco.Cms.Persistence.Sqlite/Umbraco.Cms.Persistence.Sqlite.csproj
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
  src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  tests/Umbraco.TestData/Umbraco.TestData.csproj
  tests/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
  tests/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
  tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
Labels: release/10.0.0

#12291 Update installer background image
  src/Umbraco.Web.UI.Client/src/assets/img/installer.jpg
  src/Umbraco.Web.UI.Client/src/assets/img/installer.svg
  src/Umbraco.Web.UI.Client/src/less/installer.less
Labels: release/10.0.0

#12270 V10 - Reduce usage of temp AspNetCoreHostingEnvironment
  src/Umbraco.Core/Composing/TypeLoader.cs
  src/Umbraco.Core/DependencyInjection/IUmbracoBuilder.cs
  src/Umbraco.Core/Extensions/HostEnvironmentExtensions.cs
  src/Umbraco.Core/Hosting/IHostingEnvironment.cs
  src/Umbraco.Infrastructure/Logging/Serilog/LoggerConfigExtensions.cs
  src/Umbraco.Infrastructure/Logging/Serilog/SerilogLogger.cs
  src/Umbraco.Infrastructure/Runtime/CoreRuntime.cs
  src/Umbraco.Web.Common/AspNetCore/AspNetCoreHostingEnvironment.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilder.ImageSharp.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Extensions/ApplicationDiscriminatorExtensions.cs
  src/Umbraco.Web.Common/Extensions/ServiceCollectionExtensions.cs
  src/Umbraco.Web.Common/Extensions/WebHostEnvironmentExtensions.cs
  src/Umbraco.Web.Common/Hosting/HostBuilderExtensions.cs
  src/Umbraco.Web.Common/Hosting/UmbracoHostBuilderDecorator.cs
  src/Umbraco.Web.Common/Logging/Enrichers/ApplicationIdEnricher.cs
  src/Umbraco.Web.Common/Logging/Enrichers/NoopEnricher.cs
  src/Umbraco.Web.Common/Logging/RegisteredReloadableLogger.cs
  src/Umbraco.Web.UI/Program.cs
  tests/Umbraco.Tests.Benchmarks/TypeLoaderBenchmarks.cs
  tests/Umbraco.Tests.Common/Testing/TestHostingEnvironment.cs
  tests/Umbraco.Tests.Integration/TestServerTest/UmbracoTestServerTestBase.cs
  tests/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Composing/TypeLoaderTests.cs
Labels: release/10.0.0, project/v10

#12299 V9/feature/log telemetry level changing
  src/Umbraco.Core/Services/MetricsConsentService.cs
Labels: release/9.5.0
