Repository umbraco/Umbraco-CMS, pull requests merged in 2022-11, with the labels that each got.

#13318 OpenId Connect authentication for new management API
  src/Umbraco.Cms.ManagementApi/Controllers/Security/BackOfficeController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Security/Paths.cs
  src/Umbraco.Cms.ManagementApi/DependencyInjection/BackOfficeAuthBuilderExtensions.cs
  src/Umbraco.Cms.ManagementApi/DependencyInjection/ServicesBuilderExtensions.cs
  src/Umbraco.Cms.ManagementApi/ManagementApiComposer.cs
  src/Umbraco.Cms.ManagementApi/Middleware/BackOfficeAuthorizationInitializationMiddleware.cs
  src/Umbraco.Cms.ManagementApi/OpenApi.json
  src/Umbraco.Cms.ManagementApi/Security/BackOfficeApplicationManager.cs
  src/Umbraco.Cms.ManagementApi/Security/ClientSecretManager.cs
  src/Umbraco.Cms.ManagementApi/Security/IClientSecretManager.cs
  src/Umbraco.Cms.ManagementApi/Umbraco.Cms.ManagementApi.csproj
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
  src/Umbraco.Core/Routing/UmbracoRequestPaths.cs
  src/Umbraco.Core/Routing/UmbracoRequestPathsOptions.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.New.Cms.Core/Constants-OauthClientIds.cs
  src/Umbraco.New.Cms.Core/Models/Configuration/NewBackOfficeSettings.cs
  src/Umbraco.New.Cms.Core/Models/Configuration/NewBackOfficeSettingsValidator.cs
  src/Umbraco.New.Cms.Infrastructure/HostedServices/OpenIddictCleanup.cs
  src/Umbraco.New.Cms.Infrastructure/Security/IBackOfficeApplicationManager.cs
  src/Umbraco.New.Cms.Infrastructure/Umbraco.New.Cms.Infrastructure.csproj
  src/Umbraco.Web.UI.Client/src/views/common/login.controller.js
  tests/Umbraco.Tests.UnitTests/TestHelpers/Objects/TestUmbracoContextFactory.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/UmbracoRequestPathsTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Security/BackOfficeCookieManagerTests.cs
Labels: project/new-backoffice

#13350 Use Swashbuckle instead of NSwag
  src/Umbraco.Cms.ManagementApi/Controllers/Culture/CultureControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/DataType/Tree/DataTypeTreeControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Dictionary/DictionaryControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Dictionary/ExportDictionaryController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Dictionary/Tree/DictionaryTreeControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Document/RecycleBin/DocumentRecycleBinControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Document/Tree/DocumentTreeControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/DocumentBlueprint/Tree/DocumentBlueprintTreeControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/DocumentType/Tree/DocumentTypeTreeControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Help/HelpControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Install/InstallControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Language/LanguageControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Media/RecycleBin/MediaRecycleBinControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Media/Tree/MediaTreeControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/MediaType/Tree/MediaTypeTreeControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/MemberGroup/Tree/MemberGroupTreeControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/MemberType/Tree/MemberTypeTreeControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/ModelsBuilder/GetModelsBuilderController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/ModelsBuilder/ModelsBuilderControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/PartialView/Tree/PartialViewTreeControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Profiling/ProfilingControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/PublishedCache/PublishedCacheControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Relation/RelationControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/RelationType/Tree/RelationTypeTreeControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Script/Tree/ScriptTreeControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Search/SearchControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Security/BackOfficeController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Server/ServerControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/StaticFile/Tree/StaticFileTreeControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Stylesheet/Tree/StylesheetTreeControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Telemetry/AllTelemetryController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Telemetry/GetTelemetryController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Telemetry/SetTelemetryController.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Telemetry/TelemetryControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Template/Tree/TemplateTreeControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/TrackedReference/TrackedReferencesControllerBase.cs
  src/Umbraco.Cms.ManagementApi/Controllers/Upgrade/UpgradeControllerBase.cs
  src/Umbraco.Cms.ManagementApi/DependencyInjection/BackOfficeAuthBuilderExtensions.cs
  src/Umbraco.Cms.ManagementApi/ManagementApiComposer.cs
  src/Umbraco.Cms.ManagementApi/OpenApi.json
  src/Umbraco.Cms.ManagementApi/OpenApi/EnumSchemaFilter.cs
  src/Umbraco.Cms.ManagementApi/OpenApi/MimeTypeDocumentFilter.cs
  src/Umbraco.Cms.ManagementApi/OpenApi/SchemaIdGenerator.cs
  src/Umbraco.Cms.ManagementApi/Security/BackOfficeApplicationManager.cs
  src/Umbraco.Cms.ManagementApi/Security/ClientSecretManager.cs
  src/Umbraco.Cms.ManagementApi/Security/IClientSecretManager.cs
  src/Umbraco.Cms.ManagementApi/Umbraco.Cms.ManagementApi.csproj
  src/Umbraco.Cms.ManagementApi/ViewModels/Telemetry/TelemetryViewModel.cs
  src/Umbraco.Core/Routing/UmbracoRequestPaths.cs
  tests/Umbraco.Tests.Integration/NewBackoffice/OpenAPIContractTest.cs
Labels: project/new-backoffice

#13372 Updated to aspnetcore 7.0.0
  src/Umbraco.Cms.ManagementApi/Controllers/Search/IndexListExamineController.cs
  src/Umbraco.Cms.ManagementApi/Umbraco.Cms.ManagementApi.csproj
  src/Umbraco.Cms.Persistence.Sqlite/Umbraco.Cms.Persistence.Sqlite.csproj
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  tests/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
  tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
Labels: dependencies, release/11.0.0

#13380 Remove nullability from AdditionalData on ContentItemDisplay
  src/Umbraco.Core/Models/ContentEditing/ContentItemDisplay.cs
Labels: category/breaking, release/11.0.0

#13394 v11: Rich text editor - remove distraction-free mode and optimise inline mode
  src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.html
Labels: category/ui, type/feature, release/11.0.0, javascript

#13216 Enable single block mode
  src/Umbraco.Core/PropertyEditors/BlockListConfiguration.cs
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockListPropertyValueConverter.cs
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockpicker/blockpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-row.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/BlockListPropertyValueConverterTests.cs
Labels: state/sprint-candidate, hacktoberfest-accepted

#13415 V10: merge v8 blobstorage file deletion fix
  src/Umbraco.Web.BackOffice/Controllers/CodeFileController.cs
Labels: release/10.4.0

#13325 rename block grid allowance to permissions
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/blockgrid.blockconfiguration.overlay.html
Labels: category/ui, category/accessibility, hacktoberfest-accepted, release/11.0.0, release/10.4.0

#13371 v11: Umbraco Marketplace replaces packages repo
  src/JsonSchema/AppSettings.cs
  src/Umbraco.Core/Configuration/Models/ActiveDirectorySettings.cs
  src/Umbraco.Core/Configuration/Models/MarketplaceSettings.cs
  src/Umbraco.Core/Constants-Configuration.cs
  src/Umbraco.Core/Constants-Marketplace.cs
  src/Umbraco.Core/Constants-PackageRepository.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
  src/Umbraco.Core/EmbeddedResources/Lang/da.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeServerVariables.cs
  src/Umbraco.Web.UI.Client/src/common/resources/ourpackagerrepository.resource.js
  src/Umbraco.Web.UI.Client/src/less/components/umb-packages.less
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-container.html
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-sub-views.html
  src/Umbraco.Web.UI.Client/src/views/packages/overview.controller.js
  src/Umbraco.Web.UI.Client/src/views/packages/views/marketplace.controller.js
  src/Umbraco.Web.UI.Client/src/views/packages/views/marketplace.html
  src/Umbraco.Web.UI.Client/src/views/packages/views/repo.controller.js
  src/Umbraco.Web.UI.Client/src/views/packages/views/repo.html
Labels: category/dx, release/11.0.0, release/10.4.0

#13225 Adjust sorting of block grid editor groups to y-axis only
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/blockgrid.blockconfiguration.controller.js
Labels: hacktoberfest-accepted

#13427 Simplify JSON schema, generation, copying and updating
  .gitignore
  Directory.Build.props
  src/JsonSchema/AppSettings.cs
  src/JsonSchema/NamespacePrefixedSchemaNameGenerator.cs
  src/JsonSchema/Options.cs
  src/JsonSchema/Program.cs
  src/JsonSchema/UmbracoJsonSchemaGenerator.cs
  src/JsonSchema/UmbracoJsonSchemaGeneratorSettings.cs
  src/JsonSchema/appsettings-schema.json
  src/Umbraco.Cms.Targets/Umbraco.Cms.Targets.csproj
  src/Umbraco.Cms.Targets/buildTransitive/Umbraco.Cms.Targets.props
  src/Umbraco.Cms.Targets/buildTransitive/Umbraco.Cms.Targets.targets
  src/Umbraco.Core/Configuration/Models/GlobalSettings.cs
  src/Umbraco.Core/Configuration/Models/LicensesSettings.cs
  src/Umbraco.Core/Configuration/Models/MarketplaceSettings.cs
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  src/Umbraco.Web.UI/appsettings.Development.template.json
  src/Umbraco.Web.UI/appsettings.template.json
  templates/UmbracoProject/.gitignore
  templates/UmbracoProject/UmbracoProject.csproj
  templates/UmbracoProject/appsettings.Development.json
  templates/UmbracoProject/appsettings.json
  tools/Umbraco.JsonSchema/Options.cs
  tools/Umbraco.JsonSchema/Program.cs
  tools/Umbraco.JsonSchema/Umbraco.JsonSchema.csproj
  tools/Umbraco.JsonSchema/UmbracoCmsSchema.cs
  tools/Umbraco.JsonSchema/UmbracoJsonSchemaGenerator.cs
  umbraco.sln
Labels: status/needs-docs, category/dx, type/feature, release/11.0.0

#13457 Add sensible eslint rules with newest eslint version
  src/Umbraco.Web.UI.Client/.eslintrc
  src/Umbraco.Web.UI.Client/gulp/util/processJs.js
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/common/directives/components/imaging/umbimagethumbnail.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/overlays/umboverlay.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/umblightbox.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbmediagrid.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/util/disabletabindex.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/validation/valformmanager.directive.js
  src/Umbraco.Web.UI.Client/src/common/directives/validation/valpropertymsg.directive.js
  src/Umbraco.Web.UI.Client/src/common/mocks/resources/_utils.js
  src/Umbraco.Web.UI.Client/src/common/mocks/umbraco.servervariables.js
  src/Umbraco.Web.UI.Client/src/common/resources/datatype.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/dictionary.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js
  src/Umbraco.Web.UI.Client/src/common/services/assets.service.js
  src/Umbraco.Web.UI.Client/src/common/services/help.service.js
  src/Umbraco.Web.UI.Client/src/common/services/macro.service.js
  src/Umbraco.Web.UI.Client/src/common/services/menuactions.service.js
  src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js
  src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
  src/Umbraco.Web.UI.Client/src/common/services/umbrequesthelper.service.js
  src/Umbraco.Web.UI.Client/src/common/services/urlhelper.service.js
  src/Umbraco.Web.UI.Client/src/init.js
  src/Umbraco.Web.UI.Client/src/installer/steps/database.controller.js
  src/Umbraco.Web.UI.Client/src/routes.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/treepicker/treepicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/prevalueeditors/colorpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbBlockGridPropertyEditor.component.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/colorpicker/colorpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/colorpicker/multicolorpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/datepicker/datepicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/config/grid.default.config.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.controller.js
  src/Umbraco.Web.UI.Client/src/views/relationTypes/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/templates/edit.controller.js
Labels: dependencies, category/dx, type/feature, javascript, area/frontend

#13470 Ensure that all automatic relation types are updated
  src/Umbraco.Core/Constants-Conventions.cs
  src/Umbraco.Core/PropertyEditors/IDataValueReference.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentRepositoryBase.cs
Labels: type/bug

#13369 Enabling an Umbraco admin user to disable 2FA for a member
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Core/Models/ContentEditing/MemberSave.cs
  src/Umbraco.Core/Models/Mapping/MemberTabsAndPropertiesMapper.cs
  src/Umbraco.Web.BackOffice/Controllers/MemberController.cs
  src/Umbraco.Web.UI.Client/src/common/services/umbdataformatter.service.js
  src/Umbraco.Web.Website/Controllers/UmbTwoFactorLoginController.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Controllers/MemberControllerUnitTests.cs
Labels: type/feature, release/11.1.0

#13085 add setDirty() logic to remove actions on mediaPicker3 property editor
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker3/umbMediaPicker3PropertyEditor.component.js
Labels: community/pr, category/ux, type/bug, release/11.1.0

#13489 Revert breaking changes adding IContextCache to deploy connectors
  src/Umbraco.Core/Deploy/DataTypeConfigurationConnectorExtensions.cs
  src/Umbraco.Core/Deploy/IDataTypeConfigurationConnector.cs
  src/Umbraco.Core/Deploy/IDataTypeConfigurationConnector2.cs
  src/Umbraco.Core/Deploy/IServiceConnector.cs
  src/Umbraco.Core/Deploy/IServiceConnector2.cs
  src/Umbraco.Core/Deploy/IValueConnector.cs
  src/Umbraco.Core/Deploy/IValueConnector2.cs
  src/Umbraco.Core/Deploy/ServiceConnectorExtensions.cs
  src/Umbraco.Core/Deploy/ValueConnectorExtensions.cs
  src/Umbraco.Infrastructure/Deploy/GridCellValueConnectorExtensions.cs
  src/Umbraco.Infrastructure/Deploy/IGridCellValueConnector.cs
  src/Umbraco.Infrastructure/Deploy/IGridCellValueConnector2.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/CoreThings/UdiTests.cs
Labels: release/11.0.0

#13475 Create and pack empty file to add TFM dependency to Umbraco.Cms and Umbraco.Cms.Targets
  src/Umbraco.Cms.Targets/Umbraco.Cms.Targets.csproj
  src/Umbraco.Cms/Umbraco.Cms.csproj
Labels: release/11.0.0

#13493 New login background as SVG
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/assets/img/login.svg
  src/Umbraco.Core/Configuration/Models/ContentSettings.cs
  src/Umbraco.Web.UI.Client/src/less/pages/login.less
  src/Umbraco.Web.UI.Client/src/views/errors/BootFailed.html
Labels: release/11.0.0

#13086 added fix for ncNodeName filter in list view
  src/Umbraco.Web.UI.Client/src/views/components/umb-content-grid.html
  src/Umbraco.Web.UI.Client/src/views/components/umb-table.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
Labels: community/pr, type/bug, hacktoberfest-accepted, release/11.1.0

#13087 Accessibility Fixes for Users and Packages pages
  src/Umbraco.Web.UI.Client/src/views/components/html/umb-control-group.html
  src/Umbraco.Web.UI.Client/src/views/packages/views/installed.html
  src/Umbraco.Web.UI.Client/src/views/users/views/users/users.html
Labels: hacktoberfest-accepted

#13113 Added "loading" parameter to "umbEditorHeader" directive
  src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorheader.directive.js
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-header.html
Labels: community/pr, category/ux, type/feature, hacktoberfest-accepted, release/11.1.0

#13101 Use span in StripFileExtension to speed up and use less memory
  src/Umbraco.Core/Extensions/StringExtensions.cs
  tests/Umbraco.Tests.Benchmarks/StringFileExtensionBenchmark.cs
Labels: community/pr, category/performance, type/feature, hacktoberfest-accepted, release/11.1.0

#13109 Skip populating the PropertyTypeGroup alias column if it is already populated
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_8_17_0/AddPropertyTypeGroupColumns.cs
Labels: community/pr, type/bug, hacktoberfest-accepted, release/11.1.0

#13117 Accessibility: Fix - Missing table description: A data table is present with no description associated to it
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.html
Labels: hacktoberfest-accepted

#13142 Fixes umbraco/Umbraco-CMS.Accessibility.Issues#39
  src/Umbraco.Web.UI.Client/src/views/components/tags/umb-tags-editor.html
Labels: community/pr, category/accessibility, type/bug, hacktoberfest-accepted, release/11.1.0

#13150 Ensure culture is always set in `LocalizeText`
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
Labels: community/pr, type/bug, hacktoberfest-accepted, release/11.1.0

#13161 Add AddManifestFilter extension method to UmbracoBuilder.CollectionBuilders.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.CollectionBuilders.cs
Labels: community/pr, category/dx, type/feature, hacktoberfest-accepted, release/11.1.0

#13178 Use array instead of list when rebuilding mediacache
  src/Umbraco.PublishedCache.NuCache/Persistence/NuCacheContentRepository.cs
  tests/Umbraco.Tests.Benchmarks/CollectionBenchmarks.cs
Labels: community/pr, category/performance, type/feature, hacktoberfest-accepted, release/11.1.0

#13207 Notification documentation
  src/Umbraco.Core/Notifications/ContentMovedNotification.cs
  src/Umbraco.Core/Notifications/ContentMovingNotification.cs
  src/Umbraco.Core/Notifications/ContentPublishedNotification.cs
  src/Umbraco.Core/Notifications/ContentPublishingNotification.cs
  src/Umbraco.Core/Notifications/ContentSortedNotification.cs
  src/Umbraco.Core/Notifications/ContentSortingNotification.cs
  src/Umbraco.Core/Notifications/MovedNotification.cs
  src/Umbraco.Core/Notifications/MovingNotification.cs
Labels: hacktoberfest-accepted

#13469 Use `getLocalDate` from dateHelper
  src/Umbraco.Web.UI.Client/src/views/users/user.controller.js
Labels: javascript, area/frontend

#13478 Nuget updates
  src/Umbraco.Cms.Persistence.SqlServer/Umbraco.Cms.Persistence.SqlServer.csproj
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
  src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
  tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
Labels: category/breaking, release/11.0.0

#13253 Fix Content Tree Node Not Greyed Out
  src/Umbraco.Web.BackOffice/Trees/ContentTreeController.cs
Labels: hacktoberfest-accepted

#13381 Solves #13378
  src/Umbraco.Cms.Imaging.ImageSharp/Media/ImageSharpImageUrlGenerator.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Media/ImageSharpImageUrlGeneratorTests.cs
Labels: community/pr, type/bug, release/11.1.0

#13297 Added missing content-type header to BootFailedMiddleware response
  src/Umbraco.Web.Common/Middleware/BootFailedMiddleware.cs
Labels: hacktoberfest-accepted

#13114 Accessibility - Fix Packages - Modal - Empty buttons
  src/Umbraco.Web.UI.Client/src/views/packages/views/repo.html
Labels: community/pr, category/accessibility, type/bug, hacktoberfest-accepted, release/10.4.0

#13116 Use Spans in UriExtensions
  src/Umbraco.Core/Extensions/UriExtensions.cs
Labels: community/pr, category/performance, type/feature, hacktoberfest-accepted, release/11.1.0

#13327 Fixing some comments errors to reduce CodeQL warnings
  src/Umbraco.Core/Composing/BuilderCollectionBase.cs
  src/Umbraco.Core/Configuration/Models/SmtpSettings.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Collections.cs
  src/Umbraco.Core/Models/Blocks/BlockListItem.cs
  src/Umbraco.Core/Models/Range.cs
Labels: hacktoberfest-accepted

#13330 Remove reference to installing a local package via backoffice
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Web.UI.Client/src/views/packages/views/installed.html
Labels: community/pr, category/ux, type/bug, hacktoberfest-accepted, hacktoberfest/contrib-2022, release/11.1.0

#13346 Update to latest framework version in web site projects
  umbraco.sln
Labels: community/pr, type/feature

#13357 LogViewer: Adding support for viewing destructed properties
  src/Umbraco.Web.UI.Client/src/views/logViewer/search.html
Labels: community/pr, category/ux, category/dx, type/feature, release/11.1.0

#13434 Allow empty valuesets to be indexed so the back-offce does not hang when rebuilding empty indexes
  src/Umbraco.Infrastructure/Examine/ContentIndexPopulator.cs
  src/Umbraco.Infrastructure/Examine/MediaIndexPopulator.cs
  src/Umbraco.Infrastructure/Examine/MemberIndexPopulator.cs
Labels: community/pr, type/bug, release/11.1.0
