Repository umbraco/Umbraco-CMS, pull requests merged in 2022-01, with the labels that each got.

#11784 v9: some url paths are not correct on case sensitive filesystems
  src/Umbraco.Core/Actions/ActionAssignDomain.cs
  src/Umbraco.Web.UI/umbraco/config/lang/cs.xml
  src/Umbraco.Web.UI/umbraco/config/lang/cy.xml
  src/Umbraco.Web.UI/umbraco/config/lang/da.xml
  src/Umbraco.Web.UI/umbraco/config/lang/de.xml
  src/Umbraco.Web.UI/umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
  src/Umbraco.Web.UI/umbraco/config/lang/es.xml
  src/Umbraco.Web.UI/umbraco/config/lang/fr.xml
  src/Umbraco.Web.UI/umbraco/config/lang/he.xml
  src/Umbraco.Web.UI/umbraco/config/lang/it.xml
  src/Umbraco.Web.UI/umbraco/config/lang/ja.xml
  src/Umbraco.Web.UI/umbraco/config/lang/ko.xml
  src/Umbraco.Web.UI/umbraco/config/lang/nb.xml
  src/Umbraco.Web.UI/umbraco/config/lang/nl.xml
  src/Umbraco.Web.UI/umbraco/config/lang/pl.xml
  src/Umbraco.Web.UI/umbraco/config/lang/pt.xml
  src/Umbraco.Web.UI/umbraco/config/lang/ru.xml
  src/Umbraco.Web.UI/umbraco/config/lang/sv.xml
  src/Umbraco.Web.UI/umbraco/config/lang/tr.xml
  src/Umbraco.Web.UI/umbraco/config/lang/zh.xml
  src/Umbraco.Web.UI/umbraco/config/lang/zh_tw.xml
Labels: type/bug

#11785 V8: Merge package telemetry from V9
  src/Umbraco.Core/Composing/CompositionExtensions/Services.cs
  src/Umbraco.Core/Manifest/ManifestParser.cs
  src/Umbraco.Core/Manifest/PackageManifest.cs
  src/Umbraco.Core/Telemetry/ITelemetryService.cs
  src/Umbraco.Core/Telemetry/Models/PackageTelemetry.cs
  src/Umbraco.Core/Telemetry/Models/TelemetryReportData.cs
  src/Umbraco.Core/Telemetry/TelemetryService.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests/Manifest/ManifestParserTests.cs
  src/Umbraco.Web/Telemetry/ReportSiteTask.cs
  src/Umbraco.Web/Telemetry/TelemetryComponent.cs
Labels: type/feature, release/8.18.0

#11805 Prune Image Cropper and Media Picker (v3) values
  src/Umbraco.Core/PropertyEditors/ValueConverters/ImageCropperValue.cs
  src/Umbraco.Tests/PropertyEditors/ImageCropperTest.cs
  src/Umbraco.Web/PropertyEditors/ImageCropperPropertyValueEditor.cs
  src/Umbraco.Web/PropertyEditors/MediaPicker3PropertyEditor.cs
Labels: type/feature, release/8.18.0

#11386 Request Handler Settings for character replacement
  src/Umbraco.Core/Configuration/Models/CharItem.cs
  src/Umbraco.Core/Configuration/Models/RequestHandlerSettings.cs
  src/Umbraco.Core/Configuration/UmbracoSettings/CharacterReplacementEqualityComparer.cs
  src/Umbraco.Core/Configuration/UmbracoSettings/IChar.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
  src/Umbraco.Core/Extensions/RequestHandlerSettingsExtension.cs
  src/Umbraco.Core/Strings/DefaultShortStringHelperConfig.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Configuration/Models/RequestHandlerSettingsTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/ShortStringHelper/DefaultShortStringHelperTestsWithoutSetup.cs
Labels: hacktoberfest-accepted

#11824 Add package tests
  tests/Umbraco.Tests.AcceptanceTest/cypress/integration/Packages/packages.ts
  tests/Umbraco.Tests.AcceptanceTest/cypress/plugins/index.js
  tests/Umbraco.Tests.AcceptanceTest/cypress/support/commands.js
  tests/Umbraco.Tests.AcceptanceTest/package-lock.json
  tests/Umbraco.Tests.AcceptanceTest/package.json
  tests/Umbraco.Tests.AcceptanceTest/tsconfig.json
Labels: category/acceptance-tests

#11845 Take `ufprt` from form data if post, fallback to query
  src/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformer.cs
Labels: type/bug, release/9.3.0

#11841 V10 Update AddUnique to support multiple lifetimes.
  src/Umbraco.Core/DependencyInjection/ServiceCollectionExtensions.cs
Labels: project/v10

#11852 V9: Visiting a page without a template returns "Page Not Found"
  src/Umbraco.Web.Common/Controllers/RenderController.cs
  src/Umbraco.Web.Common/Controllers/UmbracoPageController.cs
Labels: type/bug

#11825 V9: Allowlisting remote URLs for displaying content on the content dashboard
  src/JsonSchema/AppSettings.cs
  src/Umbraco.Core/Configuration/Models/ContentDashboardSettings.cs
  src/Umbraco.Core/Constants-Configuration.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
  src/Umbraco.Web.BackOffice/Controllers/DashboardController.cs
Labels: project/v9, type/feature, release/9.3.0

#11822 Allowlisting remote URLs for displaying content on the content dashboard
  src/Umbraco.Core/Constants-AppSettings.cs
  src/Umbraco.Core/Dashboards/ContentDashboardSettings.cs
  src/Umbraco.Core/Dashboards/IContentDashboardSettings.cs
  src/Umbraco.Web.UI/web.Template.config
  src/Umbraco.Web/Editors/DashboardController.cs
Labels: type/feature, release/8.18.0

#11823 Don't show stack trace in production mode
  src/Umbraco.Web/WebApi/EnableDetailedErrorsAttribute.cs
Labels: type/bug, release/8.18.0

#11680 Added EntityController.GetUrlsByIds support for int & guid + update MNTP
  src/Umbraco.Web.UI.Client/src/common/mocks/resources/entity.mocks.js
  src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js
  src/Umbraco.Web/Editors/EntityController.cs
Labels: release/8.18.0

#11821 Bump ImageSharp.Web version to v1.0.5
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
Labels: status/dependency-update, type/bug, release/9.3.0

#11814 Null check in Examine backoffice search
  src/Umbraco.Web.BackOffice/Controllers/ExamineManagementController.cs
Labels: community/pr, type/bug, release/9.3.0

#11833 Added description to entityResource.getSafeAlias
  src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js
Labels: community/pr, category/api-documentation, release/9.3.0

#11883 Add IsRestarting property to Umbraco application notifications
  src/Umbraco.Core/Notifications/IUmbracoApplicationLifetimeNotification.cs
  src/Umbraco.Core/Notifications/UmbracoApplicationStartedNotification.cs
  src/Umbraco.Core/Notifications/UmbracoApplicationStartingNotification.cs
  src/Umbraco.Core/Notifications/UmbracoApplicationStoppedNotification.cs
  src/Umbraco.Core/Notifications/UmbracoApplicationStoppingNotification.cs
  src/Umbraco.Infrastructure/Runtime/CoreRuntime.cs
Labels: type/feature, release/9.3.0

#11897 V8: Add ability to implement your own HtmlSanitizer
  src/Umbraco.Core/Composing/CompositionExtensions/Services.cs
  src/Umbraco.Core/Security/IHtmlSanitizer.cs
  src/Umbraco.Core/Security/NoopHtmlSanitizer.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Tests/PublishedContent/PublishedContentTests.cs
  src/Umbraco.Web/PropertyEditors/GridPropertyEditor.cs
  src/Umbraco.Web/PropertyEditors/RichTextPropertyEditor.cs
Labels: type/feature

#11898 V9: Add ability to implement your own HtmlSanitizer
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Core/Security/IHtmlSanitizer.cs
  src/Umbraco.Core/Security/NoopHtmlSanitizer.cs
  src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs
Labels: type/feature

#11907 V8: Add allowlist for HelpPage
  src/Umbraco.Core/ConfigsExtensions.cs
  src/Umbraco.Core/Constants-AppSettings.cs
  src/Umbraco.Core/Help/HelpPageSettings.cs
  src/Umbraco.Core/Help/IHelpPageSettings.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Web.UI/web.Template.config
  src/Umbraco.Web/Editors/HelpController.cs
Labels: type/feature, release/8.18.0

#11909 V9: Add allowlist for HelpPage
  src/JsonSchema/AppSettings.cs
  src/Umbraco.Core/Configuration/Models/HelpPageSettings.cs
  src/Umbraco.Core/Constants-Configuration.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
  src/Umbraco.Web.BackOffice/Controllers/HelpController.cs
Labels: type/feature, release/9.3.0

#11911 Add check for PluginControllerAttribute and compare area name
  src/Umbraco.Infrastructure/Runtime/RuntimeState.cs
  src/Umbraco.Web.BackOffice/Services/ConflictingRouteService.cs
Labels: type/bug

#11455 Removed if-check to allow empty values from blocks
  src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
Labels: hacktoberfest-accepted
