Repository umbraco/Umbraco-CMS, pull requests merged in 2022-05, with the labels that each got.

#12307 Update examine to version 3
  src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
  src/Umbraco.Examine.Lucene/UmbracoContentIndex.cs
  src/Umbraco.Examine.Lucene/UmbracoExamineIndex.cs
  src/Umbraco.Infrastructure/Examine/ContentValueSetValidator.cs
  src/Umbraco.Infrastructure/Examine/ValueSetValidator.cs
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/ExamineExtensions.cs
  tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/IndexTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Examine/UmbracoContentValueSetValidatorTests.cs
Labels: category/breaking, release/10.0.0

#12243 v10: Make language name editable
  src/Umbraco.Core/Models/ContentEditing/Language.cs
  src/Umbraco.Core/Models/ILanguage.cs
  src/Umbraco.Core/Models/Language.cs
  src/Umbraco.Core/Models/Mapping/DictionaryMapDefinition.cs
  src/Umbraco.Core/Models/Mapping/LanguageMapDefinition.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Services.cs
  src/Umbraco.Infrastructure/Packaging/PackageDataInstallation.cs
  src/Umbraco.Infrastructure/Persistence/Factories/LanguageFactory.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/LanguageRepository.cs
  src/Umbraco.Web.BackOffice/Controllers/LanguageController.cs
  src/Umbraco.Web.Common/Templates/TemplateRenderer.cs
  src/Umbraco.Web.UI.Client/src/views/components/html/umb-control-group.html
  src/Umbraco.Web.UI.Client/src/views/languages/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/languages/edit.html
  src/Umbraco.Web.UI.Client/src/views/languages/overview.controller.js
  src/Umbraco.Web.UI.Client/src/views/languages/overview.html
  src/Umbraco.Web.UI/umbraco/config/lang/en.xml
  src/Umbraco.Web.UI/umbraco/config/lang/en_us.xml
  tests/Umbraco.Tests.AcceptanceTest/cypress/integration/Content/routing.ts
  tests/Umbraco.Tests.Common/Builders/LanguageBuilder.cs
  tests/Umbraco.Tests.Integration/Testing/SqliteTestDatabase.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Packaging/PackageDataInstallationTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/DictionaryRepositoryTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/DocumentRepositoryTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/DomainRepositoryTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/LanguageRepositoryTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/MediaRepositoryTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/TemplateRepositoryTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Scoping/ScopedRepositoryTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServiceNotificationTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServicePublishBranchTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentTypeServiceVariantsTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/EntityServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/EntityXmlSerializerTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/Dictionary-Package.xml
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/GetContentUrlsTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/PublishedCache/PublishedContentLanguageVariantTests.cs
Labels: category/breaking, category/ui, status/dependency-update, type/feature, release/10.0.0

#12324 Move umbraco views to static assets and make that an RCL + Embedded language files
  build/NuSpecs/UmbracoCms.StaticAssets.nuspec
  build/NuSpecs/buildTransitive/Umbraco.Cms.StaticAssets.props
  build/NuSpecs/buildTransitive/Umbraco.Cms.StaticAssets.targets
  build/build.ps1
  src/Umbraco.Cms.StaticAssets/Umbraco.Cms.StaticAssets.csproj
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/AuthorizeUpgrade.cshtml
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Default.cshtml
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Preview.cshtml
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoInstall/Index.cshtml
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoWebsite/NoNodes.cshtml
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoWebsite/NotFound.cshtml
  src/Umbraco.Core/Configuration/Models/GlobalSettings.cs
  src/Umbraco.Core/EmbeddedResources/Lang/cs.xml
  src/Umbraco.Core/EmbeddedResources/Lang/cy.xml
  src/Umbraco.Core/EmbeddedResources/Lang/da.xml
  src/Umbraco.Core/EmbeddedResources/Lang/de.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Core/EmbeddedResources/Lang/es.xml
  src/Umbraco.Core/EmbeddedResources/Lang/fr.xml
  src/Umbraco.Core/EmbeddedResources/Lang/he.xml
  src/Umbraco.Core/EmbeddedResources/Lang/it.xml
  src/Umbraco.Core/EmbeddedResources/Lang/ja.xml
  src/Umbraco.Core/EmbeddedResources/Lang/ko.xml
  src/Umbraco.Core/EmbeddedResources/Lang/nb.xml
  src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
  src/Umbraco.Core/EmbeddedResources/Lang/pl.xml
  src/Umbraco.Core/EmbeddedResources/Lang/pt.xml
  src/Umbraco.Core/EmbeddedResources/Lang/ru.xml
  src/Umbraco.Core/EmbeddedResources/Lang/sv.xml
  src/Umbraco.Core/EmbeddedResources/Lang/tr.xml
  src/Umbraco.Core/EmbeddedResources/Lang/zh.xml
  src/Umbraco.Core/EmbeddedResources/Lang/zh_tw.xml
  src/Umbraco.Core/Services/LocalizedTextServiceFileSources.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.FileSystems.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Services.cs
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.Web.BackOffice/Extensions/UmbracoApplicationBuilder.BackOffice.cs
  src/Umbraco.Web.BackOffice/Services/IconService.cs
  src/Umbraco.Web.Common/AspNetCore/AspNetCoreHostingEnvironment.cs
  src/Umbraco.Web.Common/Extensions/ApplicationDiscriminatorExtensions.cs
  src/Umbraco.Web.Common/Extensions/UmbracoApplicationBuilder.RuntimeMinification.cs
  src/Umbraco.Web.Common/Extensions/WebHostEnvironmentExtensions.cs
  src/Umbraco.Web.Common/Logging/Enrichers/ApplicationIdEnricher.cs
  src/Umbraco.Web.UI.Client/gulp/config.js
  src/Umbraco.Web.UI.Client/test/config/karma.conf.js
  src/Umbraco.Web.UI/Program.cs
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  templates/UmbracoProject/UmbracoProject.csproj
  tests/Umbraco.Tests.Integration/DependencyInjection/UmbracoBuilderExtensions.cs
  tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Configurations/LanguageXmlTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/FileNameTests.cs
  umbraco.sln
Labels: type/feature, release/10.0.0

#12311 Limit link picker to content tree in content section
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/linkpicker/linkpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/linkpicker/linkpicker.html
Labels: community/pr, category/ux, project/v10

#12333 v10: Update locations of npm dependencies
  src/Umbraco.Web.UI.Client/gulp/tasks/dependencies.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/rollback/rollback.controller.js
Labels: status/regression

#12342 v10: Fix Block List settings exception and optimize PVCs
  src/Umbraco.Core/Models/PublishedContent/IPublishedModelFactory.cs
  src/Umbraco.Core/Models/PublishedContent/NoopPublishedModelFactory.cs
  src/Umbraco.Core/Models/PublishedContent/PublishedModelFactory.cs
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockEditorConverter.cs
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockListPropertyValueConverter.cs
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/NestedContentManyValueConverter.cs
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/NestedContentSingleValueConverter.cs
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/NestedContentValueConverterBase.cs
  src/Umbraco.Web.Common/ModelsBuilder/InMemoryModelFactory.cs
Labels: category/breaking, type/bug, release/10.0.0

#12344 v10: Async tree search
  src/Umbraco.Core/Models/ContentEditing/EntitySearchResults.cs
  src/Umbraco.Core/Models/ContentEditing/SearchResultEntity.cs
  src/Umbraco.Core/Trees/ISearchableTree.cs
  src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
  src/Umbraco.Web.BackOffice/Trees/ContentTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/ContentTypeTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/DataTypeTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/MediaTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/MediaTypeTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/MemberTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/MemberTypeTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/TemplatesTreeController.cs
Labels: category/breaking

#12340 v10: Async support for content finders. Improve loging performance.
  src/Umbraco.Core/Routing/ContentFinderByIdPath.cs
  src/Umbraco.Core/Routing/ContentFinderByPageIdQuery.cs
  src/Umbraco.Core/Routing/ContentFinderByRedirectUrl.cs
  src/Umbraco.Core/Routing/ContentFinderByUrl.cs
  src/Umbraco.Core/Routing/ContentFinderByUrlAlias.cs
  src/Umbraco.Core/Routing/ContentFinderByUrlAndTemplate.cs
  src/Umbraco.Core/Routing/IContentFinder.cs
  src/Umbraco.Core/Routing/PublishedRouter.cs
  src/Umbraco.Infrastructure/Routing/ContentFinderByConfigured404.cs
  tests/Umbraco.Tests.Common/TestLastChanceFinder.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByAliasTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByAliasWithDomainsTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByIdTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByPageIdQueryTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByUrlAliasTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByUrlAndTemplateTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByUrlTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByUrlWithDomainsTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/DomainsAndCulturesTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/UrlsWithNestedDomains.cs
Labels: category/breaking

#12346 v10: Fix LESS math
  src/Umbraco.Web.UI.Client/lib/bootstrap/less/button-groups.less
  src/Umbraco.Web.UI.Client/lib/bootstrap/less/code.less
  src/Umbraco.Web.UI.Client/lib/bootstrap/less/forms.less
  src/Umbraco.Web.UI.Client/lib/bootstrap/less/hero-unit.less
  src/Umbraco.Web.UI.Client/lib/bootstrap/less/labels-badges.less
  src/Umbraco.Web.UI.Client/lib/bootstrap/less/mixins.less
  src/Umbraco.Web.UI.Client/lib/bootstrap/less/navbar.less
  src/Umbraco.Web.UI.Client/lib/bootstrap/less/popovers.less
  src/Umbraco.Web.UI.Client/lib/bootstrap/less/responsive-1200px-min.less
  src/Umbraco.Web.UI.Client/lib/bootstrap/less/thumbnails.less
  src/Umbraco.Web.UI.Client/lib/bootstrap/less/tooltip.less
  src/Umbraco.Web.UI.Client/lib/bootstrap/less/type.less
  src/Umbraco.Web.UI.Client/lib/bootstrap/less/variables.less
  src/Umbraco.Web.UI.Client/src/less/button-groups.less
  src/Umbraco.Web.UI.Client/src/less/canvas-designer.less
  src/Umbraco.Web.UI.Client/src/less/components/application/umb-tour.less
  src/Umbraco.Web.UI.Client/src/less/components/card.less
  src/Umbraco.Web.UI.Client/src/less/components/editor/umb-editor.less
  src/Umbraco.Web.UI.Client/src/less/components/umb-box.less
  src/Umbraco.Web.UI.Client/src/less/forms.less
  src/Umbraco.Web.UI.Client/src/less/hacks.less
  src/Umbraco.Web.UI.Client/src/less/mixins.less
  src/Umbraco.Web.UI.Client/src/less/property-editors.less
  src/Umbraco.Web.UI.Client/src/less/variables.less
  src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.less
  src/Umbraco.Web.UI.Client/src/views/components/mediacard/umb-media-card-grid.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/notsupported/notsupported.less
Labels: type/bug, project/v10

#12347 Moved StackQueue to correct namespace
  src/Umbraco.Core/Collections/StackQueue.cs
  src/Umbraco.Infrastructure/Scoping/Scope.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Collections/StackQueueTests.cs
Labels: category/breaking, release/10.0.0

#12353 Update NoUiSlider to 15.6.0
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
Labels: dependencies, release/10.0.0

#12140 Show nicer overlay when clicking block card for deleted element type
  src/Umbraco.Core/EmbeddedResources/Lang/da.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
  src/Umbraco.Web.UI.Client/src/common/services/overlay.service.js
  src/Umbraco.Web.UI.Client/src/less/components/editor.less
  src/Umbraco.Web.UI.Client/src/less/navs.less
  src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card-grid.less
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-container.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.less
Labels: community/pr, category/ux, release/10.0.0

#12408 v10: Support System.Data.SqlClient provider name
  src/Umbraco.Cms.Persistence.SqlServer/UmbracoBuilderExtensions.cs
  src/Umbraco.Cms.Persistence.Sqlite/UmbracoBuilderExtensions.cs
  src/Umbraco.Core/Configuration/ConfigureConnectionStrings.cs
Labels: type/bug, release/10.0.0

#12397 v10: Use ForceCreateDatabase during unattended install and extend GetUmbracoConnectionString extension methods
  src/Umbraco.Core/Configuration/ConfigureConnectionStrings.cs
  src/Umbraco.Core/Configuration/Models/ConnectionStrings.cs
  src/Umbraco.Core/Constants-System.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
  src/Umbraco.Core/Extensions/ConfigurationExtensions.cs
  src/Umbraco.Core/Extensions/ConnectionStringExtensions.cs
  src/Umbraco.Infrastructure/Install/InstallSteps/DatabaseConfigureStep.cs
  src/Umbraco.Infrastructure/Install/InstallSteps/NewInstallStep.cs
  src/Umbraco.Infrastructure/Install/UnattendedUpgrader.cs
  src/Umbraco.Infrastructure/Migrations/Install/DatabaseBuilder.cs
  src/Umbraco.Infrastructure/Persistence/DatabaseProviderMetadataExtensions.cs
  src/Umbraco.Infrastructure/Runtime/RuntimeState.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Configuration/Models/ConnectionStringsTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Configuration/ConfigureConnectionStringsTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Extensions/ConfigurationExtensionsTests.cs
Labels: category/breaking, release/10.0.0

#12404 V9: Fix URL generation when publishing invariant content with domains
  src/Umbraco.PublishedCache.NuCache/ContentCache.cs
  src/Umbraco.PublishedCache.NuCache/DomainCacheExtensions.cs
Labels: type/bug

#12395 V8: Fix changing member password
  src/Umbraco.Web.UI.Client/src/views/member/member.edit.controller.js
Labels: type/bug

#12407 v10: Project template database/connection string improvements
  templates/Umbraco.Templates.nuspec
  templates/UmbracoPackage/.template.config/dotnetcli.host.json
  templates/UmbracoPackage/.template.config/ide.host.json
  templates/UmbracoPackage/.template.config/template.json
  templates/UmbracoPackage/UmbracoPackage.csproj
  templates/UmbracoPackage/build/UmbracoPackage.targets
  templates/UmbracoProject/.gitignore
  templates/UmbracoProject/.template.config/dotnetcli.host.json
  templates/UmbracoProject/.template.config/ide.host.json
  templates/UmbracoProject/.template.config/template.json
  templates/UmbracoProject/UmbracoProject.csproj
  templates/UmbracoProject/appsettings.Development.json
  templates/UmbracoProject/appsettings.json
Labels: category/breaking, type/feature, project/v10

#12413 v10: Change Umbraco.Cms and Umbraco.Templates nuspecs to csproj
  build/NuSpecs/UmbracoCms.nuspec
  build/build.ps1
  src/Umbraco.Cms/Umbraco.Cms.csproj
  src/Umbraco.Cms/buildTransitive/Umbraco.Cms.props
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  templates/Umbraco.Templates.csproj
  templates/Umbraco.Templates.nuspec
  umbraco.sln
Labels: type/feature, project/v10

#12416 V10: Reintroduce appsettings-schema.json
  .gitignore
  src/JsonSchema/Options.cs
  src/Umbraco.Cms.StaticAssets/Umbraco.Cms.StaticAssets.csproj
  src/Umbraco.Cms/Umbraco.Cms.csproj
  src/Umbraco.Cms/buildTransitive/Umbraco.Cms.targets
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  src/Umbraco.Web.UI/appsettings.Development.template.json
  src/Umbraco.Web.UI/appsettings.template.json
  templates/UmbracoProject/appsettings.Development.json
  templates/UmbracoProject/appsettings.json
Labels: category/breaking, type/bug, release/10.0.0

#12451 Translate 'Configure Two Factor' (Dutch)
  src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
Labels: community/pr, category/ux, release/10.1.0

#12462 Move msbuild target to correct location
  src/Umbraco.Cms.StaticAssets/Umbraco.Cms.StaticAssets.csproj
  src/Umbraco.Cms/buildTransitive/Umbraco.Cms.targets
Labels: type/bug

#12474 Fixed null check typo in CacheInstructionService. Fixes #12473.
  src/Umbraco.Infrastructure/Services/CacheInstructionService.cs
Labels: release/10.0.0

#12453 Fixes issue with redirects not being generated when an invariant cont…
  src/Umbraco.Core/Routing/UrlProvider.cs
  src/Umbraco.Infrastructure/Routing/RedirectTrackingHandler.cs
Labels: type/bug

#12463 V9: Send content type notifications on copy
  src/Umbraco.Infrastructure/Services/Implement/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
Labels: type/bug, release/9.5.1
