Repository umbraco/Umbraco-CMS, pull requests merged in 2022-07, with the labels that each got.

#12618 Support localization for content search (backoffice)
  src/Umbraco.Core/Trees/ISearchableTreeWithCulture.cs
  src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
  src/Umbraco.Web.BackOffice/Trees/ContentTreeController.cs
Labels: state/sprint-candidate

#12634 Read BootFailed.html file from WebRootFileProvider
  src/Umbraco.Web.Common/Middleware/BootFailedMiddleware.cs
Labels: state/sprint-candidate

#12379 Inherit from `OEmbedProviderBase` in OEmbed providers
  src/Umbraco.Core/Media/EmbedProviders/DailyMotion.cs
  src/Umbraco.Core/Media/EmbedProviders/Flickr.cs
  src/Umbraco.Core/Media/EmbedProviders/GettyImages.cs
  src/Umbraco.Core/Media/EmbedProviders/Giphy.cs
  src/Umbraco.Core/Media/EmbedProviders/Hulu.cs
  src/Umbraco.Core/Media/EmbedProviders/Issuu.cs
  src/Umbraco.Core/Media/EmbedProviders/Kickstarter.cs
  src/Umbraco.Core/Media/EmbedProviders/Slideshare.cs
  src/Umbraco.Core/Media/EmbedProviders/SoundCloud.cs
  src/Umbraco.Core/Media/EmbedProviders/Ted.cs
  src/Umbraco.Core/Media/EmbedProviders/Twitter.cs
  src/Umbraco.Core/Media/EmbedProviders/Vimeo.cs
  src/Umbraco.Core/Media/EmbedProviders/Youtube.cs
Labels: community/pr, category/refactor, type/feature, release/10.2.0

#12693 Add RuntimeModeValidator collection builder
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Collections.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/Runtime/RuntimeModeValidationService.cs
  src/Umbraco.Infrastructure/Runtime/RuntimeModeValidatorCollection.cs
  src/Umbraco.Infrastructure/Runtime/RuntimeModeValidatorCollectionBuilder.cs
Labels: release/10.1.0

#12710 Don't allocate new object array instances when indexing
  src/Umbraco.Infrastructure/Examine/ContentValueSetBuilder.cs
Labels: community/pr, type/bug, release/10.2.0

#12698 Tweaks the composition dialog in the content type editor
  src/Umbraco.Web.UI.Client/src/less/components/umb-checkbox-list.less
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/compositions/compositions.html
Labels: community/pr, category/ux, type/bug, release/10.2.0

#12595 Fix previous conversion of SearchAll to async ignoring the SortOrder value from SearchableTree
  src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
Labels: community/pr, category/ux, type/feature, release/10.2.0

#12731 v10: restore one-click install
  src/Umbraco.Web.UI.Client/src/installer/steps/user.html
Labels: status/regression

#12719 Fix: Package view - Layout not showing correctly in respect to screen size #12576
  src/Umbraco.Web.UI.Client/src/less/components/umb-packages.less
Labels: community/pr, category/ui, type/bug, release/10.2.0
