Repository umbraco/Umbraco-CMS, pull requests merged in 2022-12, with the labels that each got.

#13159 Improve system information/telemetry
  src/Umbraco.Core/Constants-Telemetry.cs
  src/Umbraco.Infrastructure/Telemetry/Providers/SystemInformationTelemetryProvider.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Telemetry/TelemetryServiceTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Services/UserDataServiceTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Telemetry/SystemInformationTelemetryProviderTests.cs
Labels: hacktoberfest-accepted

#12669 Allow indexing variant nodes when not all variants are published - fixes issues 11383.
  src/Umbraco.Infrastructure/Examine/ContentValueSetValidator.cs
  src/Umbraco.Infrastructure/Examine/ValueSetValidator.cs
  src/Umbraco.Web.Common/Views/UmbracoViewPage.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Examine/UmbracoContentValueSetValidatorTests.cs
Labels: community/pr, release/10.4.0, release/11.1.0

#13103 Fix for issue 13017 - BeginUmbracoForm doesn't work with custom umbraco routes
  src/Umbraco.Web.Common/Extensions/EndpointDataSourceExtensions.cs
  src/Umbraco.Web.Common/Extensions/EndpointExtensions.cs
  src/Umbraco.Web.Common/Extensions/LinkParserExtensions.cs
  src/Umbraco.Web.Common/Filters/UmbracoVirtualPageFilterAttribute.cs
  src/Umbraco.Web.Common/Routing/IUmbracoVirtualPageRoute.cs
  src/Umbraco.Web.Common/Routing/UmbracoVirtualPageRoute.cs
  src/Umbraco.Web.Website/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformer.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformerTests.cs
Labels: hacktoberfest-accepted, release/10.4.0, release/11.1.0

#13511 V10: Umbraco Marketplace
  src/JsonSchema/AppSettings.cs
  src/Umbraco.Core/Configuration/Models/ActiveDirectorySettings.cs
  src/Umbraco.Core/Configuration/Models/MarketplaceSettings.cs
  src/Umbraco.Core/Constants-Configuration.cs
  src/Umbraco.Core/Constants-Marketplace.cs
  src/Umbraco.Core/Constants-PackageRepository.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
  src/Umbraco.Core/EmbeddedResources/Lang/da.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeServerVariables.cs
  src/Umbraco.Web.UI.Client/src/common/resources/ourpackagerrepository.resource.js
  src/Umbraco.Web.UI.Client/src/less/components/umb-packages.less
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-container.html
  src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-sub-views.html
  src/Umbraco.Web.UI.Client/src/views/dataTypes/views/datatype.info.controller.js
  src/Umbraco.Web.UI.Client/src/views/packages/overview.controller.js
  src/Umbraco.Web.UI.Client/src/views/packages/views/marketplace.controller.js
  src/Umbraco.Web.UI.Client/src/views/packages/views/marketplace.html
  src/Umbraco.Web.UI.Client/src/views/packages/views/repo.controller.js
  src/Umbraco.Web.UI.Client/src/views/packages/views/repo.html
  src/Umbraco.Web.UI.Client/src/views/relationTypes/edit.controller.js
Labels: category/dx, type/feature, release/10.4.0, javascript, area/frontend, area/backend

#13507 Tree picker support for selecting containers
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/treepicker/treepicker.controller.js
Labels: type/bug, release/11.1.0

#13217 Show published in tracked references
  src/Umbraco.Core/Models/RelationItem.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/RelationRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/TrackedReferencesRepository.cs
  src/Umbraco.Web.UI.Client/src/common/directives/components/references/umbtrackedreferencestable.component.js
  src/Umbraco.Web.UI.Client/src/views/components/references/umb-tracked-references-table.html
  src/Umbraco.Web.UI.Client/src/views/components/references/umb-tracked-references.html
  src/Umbraco.Web.UI.Client/src/views/media/delete.html
Labels: hacktoberfest-accepted

#13270 standardising ActionLetter and ActionName for IAction
  src/Umbraco.Core/Actions/ActionAssignDomain.cs
  src/Umbraco.Core/Actions/ActionBrowse.cs
  src/Umbraco.Core/Actions/ActionCopy.cs
  src/Umbraco.Core/Actions/ActionCreateBlueprintFromContent.cs
  src/Umbraco.Core/Actions/ActionDelete.cs
  src/Umbraco.Core/Actions/ActionMove.cs
  src/Umbraco.Core/Actions/ActionNew.cs
  src/Umbraco.Core/Actions/ActionNotify.cs
  src/Umbraco.Core/Actions/ActionProtect.cs
  src/Umbraco.Core/Actions/ActionPublish.cs
  src/Umbraco.Core/Actions/ActionRestore.cs
  src/Umbraco.Core/Actions/ActionRights.cs
  src/Umbraco.Core/Actions/ActionRollback.cs
  src/Umbraco.Core/Actions/ActionSort.cs
  src/Umbraco.Core/Actions/ActionToPublish.cs
  src/Umbraco.Core/Actions/ActionUnpublish.cs
  src/Umbraco.Core/Actions/ActionUpdate.cs
  src/Umbraco.Core/Actions/IAction.cs
Labels: hacktoberfest-accepted

#13314 Tree Roots are H1
  src/Umbraco.Web.UI.Client/src/views/components/tree/umb-tree.html
Labels: hacktoberfest-accepted

#13537 V12: Named json options
  src/Umbraco.Cms.Api.Management/Configuration/ConfigureMvcJsonOptions.cs
  src/Umbraco.Cms.Api.Management/Controllers/ManagementApiControllerBase.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/MvcBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/Filters/JsonOptionsNameAttribute.cs
  src/Umbraco.Cms.Api.Management/Filters/ManagementApiJsonConfigurationAttribute.cs
  src/Umbraco.Cms.Api.Management/Filters/ManagementApiJsonOutputFormatter.cs
  src/Umbraco.Cms.Api.Management/Json/HttpContextJsonExtensions.cs
  src/Umbraco.Cms.Api.Management/Json/JsonObjectConverter.cs
  src/Umbraco.Cms.Api.Management/Json/NamedSystemTextJsonInputFormatter.cs
  src/Umbraco.Cms.Api.Management/Json/NamedSystemTextJsonOutputFormatter.cs
  src/Umbraco.Cms.Api.Management/ManagementApiComposer.cs
  src/Umbraco.New.Cms.Core/Constants-JsonOptionsNames.cs
  src/Umbraco.New.Cms.Core/Constants-OauthClientIds.cs
Labels: project/new-backoffice

#13534 BGE: Make Areas use Flexbox for easy customisation and better drag n' drop UX
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbraco-blockgridlayout-flexbox.css
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbraco-blockgridlayout.css
Labels: type/feature, area/frontend

#13551 Maintenance page when in upgrade state
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoWebsite/Maintenance.cshtml
  src/Umbraco.Core/Configuration/Models/GlobalSettings.cs
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
  src/Umbraco.Web.BackOffice/Install/InstallAreaRoutes.cs
  src/Umbraco.Web.Common/ActionsResults/MaintenanceResult.cs
  src/Umbraco.Web.Common/Authorization/FeatureAuthorizeHandler.cs
  src/Umbraco.Web.Common/Controllers/MaintenanceModeActionFilterAttribute.cs
  src/Umbraco.Web.Common/Controllers/RenderController.cs
  src/Umbraco.Web.Common/Middleware/UmbracoRequestMiddleware.cs
  src/Umbraco.Web.Website/Routing/FrontEndRoutes.cs
  src/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformer.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Routing/InstallAreaRoutesTests.cs
Labels: category/notable, type/feature, release/11.0.0, release/10.4.0

#13572 New backoffice: Redirect Url Management controller
  src/Umbraco.Cms.Api.Management/Controllers/RedirectUrlManagement/ByKeyRedirectUrlManagementController.cs
  src/Umbraco.Cms.Api.Management/Controllers/RedirectUrlManagement/DeleteByKeyRedirectUrlManagementController.cs
  src/Umbraco.Cms.Api.Management/Controllers/RedirectUrlManagement/GetAllRedirectUrlManagementController.cs
  src/Umbraco.Cms.Api.Management/Controllers/RedirectUrlManagement/GetStatusRedirectUrlManagementController.cs
  src/Umbraco.Cms.Api.Management/Controllers/RedirectUrlManagement/RedirectUrlManagementBaseController.cs
  src/Umbraco.Cms.Api.Management/Controllers/RedirectUrlManagement/SetStatusRedirectUrlManagementController.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/FactoryBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/Factories/IRedirectUrlStatusViewModelFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/IRedirectUrlViewModelFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/RedirectUrlStatusViewModelFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/RedirectUrlViewModelFactory.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/RedirectUrlManagement/RedirectUrlStatusViewModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/RedirectUrlManagement/RedirectUrlViewModel.cs
  src/Umbraco.Core/Models/ContentEditing/ContentRedirectUrl.cs
  src/Umbraco.Core/Models/Mapping/RedirectUrlMapDefinition.cs
  src/Umbraco.New.Cms.Core/Models/RedirectUrlManagement/RedirectStatus.cs
Labels: project/new-backoffice

#12969 Set redirect URL when building RegisterModel
  src/Umbraco.Web.Website/Models/RegisterModelBuilder.cs
Labels: type/bug, release/11.1.0

#13543 New Backoffice: Health check controller
  src/Umbraco.Cms.Api.Management/Controllers/HealthCheck/ExecuteActionHealthCheckController.cs
  src/Umbraco.Cms.Api.Management/Controllers/HealthCheck/Group/AllHealthCheckGroupController.cs
  src/Umbraco.Cms.Api.Management/Controllers/HealthCheck/Group/ByNameWithResultHealthCheckGroupController.cs
  src/Umbraco.Cms.Api.Management/Controllers/HealthCheck/Group/HealthCheckGroupControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/HealthCheck/HealthCheckControllerBase.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/FactoryBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/MappingBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/Factories/HealthCheckGroupWithResultViewModelFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/IHealthCheckGroupWithResultViewModelFactory.cs
  src/Umbraco.Cms.Api.Management/Mapping/HealthCheck/HealthCheckViewModelsMapDefinition.cs
  src/Umbraco.Cms.Api.Management/Mapping/Languages/LanguageViewModelsMapDefinition.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/HealthCheck/HealthCheckActionViewModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/HealthCheck/HealthCheckGroupViewModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/HealthCheck/HealthCheckGroupWithResultViewModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/HealthCheck/HealthCheckResultViewModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/HealthCheck/HealthCheckViewModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/HealthCheck/HealthCheckWithResultViewModel.cs
  src/Umbraco.Core/Constants-HealthChecks.cs
Labels: project/new-backoffice

#13621 fixes data-element attribute on media section
  src/Umbraco.Web.UI.Client/src/views/member/apps/content/content.html
Labels: release/11.2.0, release/10.5.0

#13625 Rename title marketplace to packages
  src/Umbraco.Web.UI.Client/src/views/packages/overview.controller.js
Labels: release/11.2.0
