Repository umbraco/Umbraco-CMS, pull requests merged in 2023-11, with the labels that each got.

#14937 Fix custom dbcontexts extention methods
  src/Umbraco.Cms.Persistence.EFCore.SqlServer/SqlServerMigrationProvider.cs
  src/Umbraco.Cms.Persistence.EFCore.SqlServer/SqlServerMigrationProviderSetup.cs
  src/Umbraco.Cms.Persistence.EFCore.Sqlite/SqliteMigrationProvider.cs
  src/Umbraco.Cms.Persistence.EFCore.Sqlite/SqliteMigrationProviderSetup.cs
  src/Umbraco.Cms.Persistence.EFCore/Composition/UmbracoEFCoreComposer.cs
  src/Umbraco.Cms.Persistence.EFCore/Constants-ProviderNames.cs
  src/Umbraco.Cms.Persistence.EFCore/Extensions/UmbracoEFCoreServiceCollectionExtensions.cs
  src/Umbraco.Cms.Persistence.EFCore/UmbracoDbContext.cs
  tests/Umbraco.Tests.Integration/Umbraco.Persistence.EFCore/DbContext/CustomDbContextTests.cs
Labels: hacktoberfest-accepted, hacktoberfest/contrib-2023

#15043 Check content permissions before performing action
  src/Umbraco.Core/Security/ContentPermissions.cs
  src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
  src/Umbraco.Web.BackOffice/Controllers/ContentControllerBase.cs
  src/Umbraco.Web.BackOffice/Filters/ContentSaveValidationAttribute.cs
Labels: type/bug, release/10.8.0

#15077 V13: Webhook corrections
  src/Umbraco.Core/Constants-Icons.cs
  src/Umbraco.Core/EmbeddedResources/Lang/da.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Web.BackOffice/Trees/PackagesTreeController.cs
  src/Umbraco.Web.BackOffice/Trees/WebhooksTreeController.cs
  src/Umbraco.Web.UI.Client/src/assets/icons/icon-webhook.svg
  src/Umbraco.Web.UI.Client/src/views/webhooks/logs.controller.js
  src/Umbraco.Web.UI.Client/src/views/webhooks/logs.html
  src/Umbraco.Web.UI.Client/src/views/webhooks/overlays/details.html
  src/Umbraco.Web.UI.Client/src/views/webhooks/overlays/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/webhooks/overlays/edit.html
  src/Umbraco.Web.UI.Client/src/views/webhooks/overlays/header.controller.js
  src/Umbraco.Web.UI.Client/src/views/webhooks/overlays/header.html
  src/Umbraco.Web.UI.Client/src/views/webhooks/overview.controller.js
  src/Umbraco.Web.UI.Client/src/views/webhooks/overview.html
  src/Umbraco.Web.UI.Client/src/views/webhooks/webhooks.controller.js
  src/Umbraco.Web.UI.Client/src/views/webhooks/webhooks.html
Labels: hacktoberfest-accepted

#15081 Ensure that missing access rules do not break the site
  src/Umbraco.Infrastructure/Persistence/Dtos/AccessDto.cs
Labels: type/bug, release/10.8.0

#15076 Fix warning CS0618: 'IHostingEnvironment.MapPathContentRoot(string)' is obsolete in Umbraco.TestData.
  tests/Umbraco.TestData/LoadTestController.cs
Labels: community/pr, hacktoberfest-accepted, release/13.0.0, category/obsolete-methods

#14915 Allow dashboard content to grow and fit height
  src/Umbraco.Web.UI.Client/src/less/components/application/umb-dashboard.less
Labels: hacktoberfest-accepted, hacktoberfest/contrib-2023

#15106 Remove setter from WebhookEvent
  src/Umbraco.Core/Webhooks/IWebhookEvent.cs
Labels: release/13.0.0

#15111 V13 RC: Avoid duplicate id's on the login screen
  src/Umbraco.Web.UI.Login/src/auth.element.ts
  src/Umbraco.Web.UI.Login/src/components/login-input.element.ts
Labels: type/bug

#14840 Don't allow to select folder in create dialog under media type
  src/Umbraco.Web.UI.Client/src/common/resources/contenttype.resource.js
  src/Umbraco.Web.UI.Client/src/common/resources/mediatype.resource.js
  src/Umbraco.Web.UI.Client/src/views/mediaTypes/create.controller.js
  src/Umbraco.Web.UI.Client/src/views/mediaTypes/create.html
  src/Umbraco.Web.UI.Client/src/views/memberTypes/create.controller.js
  src/Umbraco.Web.UI.Client/src/views/memberTypes/create.html
Labels: community/pr

#14941 Fix potential NullReferenceException
  src/Umbraco.Web.Common/AspNetCore/AspNetCoreSessionManager.cs
Labels: type/bug, hacktoberfest-accepted, release/13.0.0, hacktoberfest/contrib-2023

#15113 Fix FurthestAncestorOrSelfDynamicRootQueryStep and FurthestDescendantOrSelfDynamicRootQueryStep
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Collections.cs
  src/Umbraco.Core/DynamicRoot/QuerySteps/FurthestAncestorOrSelfDynamicRootQueryStep.cs
  src/Umbraco.Core/DynamicRoot/QuerySteps/FurthestDescendantOrSelfDynamicRootQueryStep.cs
  src/Umbraco.Core/DynamicRoot/QuerySteps/IDynamicRootRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DynamicRootRepository.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DynamicRootServiceTests.cs
Labels: category/breaking, release/13.0.0

#15142 Update correct action permission for schedule publishing
  src/Umbraco.Web.BackOffice/Filters/ContentSaveValidationAttribute.cs
Labels: type/bug, release/10.8.0, release/12.3.1

#15144 Move IContextCache parameter to base Deploy interfaces and add checksum to artifact dependency
  src/Umbraco.Core/Deploy/ArtifactDependency.cs
  src/Umbraco.Core/Deploy/DataTypeConfigurationConnectorExtensions.cs
  src/Umbraco.Core/Deploy/IDataTypeConfigurationConnector.cs
  src/Umbraco.Core/Deploy/IDataTypeConfigurationConnector2.cs
  src/Umbraco.Core/Deploy/IServiceConnector.cs
  src/Umbraco.Core/Deploy/IServiceConnector2.cs
  src/Umbraco.Core/Deploy/IValueConnector.cs
  src/Umbraco.Core/Deploy/IValueConnector2.cs
  src/Umbraco.Core/Deploy/ServiceConnectorExtensions.cs
  src/Umbraco.Core/Deploy/ValueConnectorExtensions.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/CoreThings/UdiTests.cs
Labels: category/breaking, release/13.0.0

#15140 V13 RC: Fix issue with 2FA login
  src/Umbraco.Web.UI.Login/src/components/pages/mfa.page.element.ts
  src/Umbraco.Web.UI.Login/src/context/auth.repository.ts
Labels: type/bug

#14923 Add strict contextual escaping on the $scope for grid controller
  src/Umbraco.Cms.StaticAssets/wwwroot/App_Plugins/Umbraco.BlockGridEditor.DefaultCustomViews/umbBlockGridDemoRichTextBlock.html
Labels: hacktoberfest-accepted, hacktoberfest/contrib-2023

#14900 Add global.json and cleanup UI project file
  global.json
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
Labels: category/dx, type/improvement

#14872 #14835 Update link on permissionsreport.html
  src/Umbraco.Web.UI.Client/src/installer/steps/permissionsreport.html
Labels: community/pr, project/v10, affected/v10, type/improvement

#15091 Translate webhooks keys to Dutch
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
Labels: release/13.0.0

#15170 V14: make v13 login screen work initially with Management API
  src/Umbraco.Web.UI.Login/src/auth.element.ts
  src/Umbraco.Web.UI.Login/src/context/auth.context.ts
  src/Umbraco.Web.UI.Login/src/context/auth.repository.ts
Labels: type/feature

#15175 Add edit page for webhook
  src/Umbraco.Core/EmbeddedResources/Lang/da.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Web.BackOffice/Controllers/WebhookController.cs
  src/Umbraco.Web.BackOffice/Services/WebhookPresentationFactory.cs
  src/Umbraco.Web.Common/Models/WebhookViewModel.cs
  src/Umbraco.Web.UI.Client/src/less/property-editors.less
  src/Umbraco.Web.UI.Client/src/views/languages/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/languages/overview.controller.js
  src/Umbraco.Web.UI.Client/src/views/webhooks/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/webhooks/edit.html
  src/Umbraco.Web.UI.Client/src/views/webhooks/overlays/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/webhooks/overlays/edit.html
  src/Umbraco.Web.UI.Client/src/views/webhooks/webhooks.controller.js
  src/Umbraco.Web.UI.Client/src/views/webhooks/webhooks.html
Labels: release/13.0.0

#15168 Use header value instead if present to set culture on request
  src/Umbraco.Web.Common/Extensions/HttpRequestExtensions.cs
  src/Umbraco.Web.Common/Middleware/UmbracoRequestMiddleware.cs
Labels: release/13.0.0

#15192 Updated nuget packages for v10
  src/JsonSchema/JsonSchema.csproj
  src/Umbraco.Cms.Persistence.Sqlite/Umbraco.Cms.Persistence.Sqlite.csproj
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Infrastructure/Logging/Serilog/Enrichers/ThreadAbortExceptionEnricher.cs
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
  src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  tests/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
  tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
Labels: dependencies, release/10.8.0

#15180 V13: Refactor webhookservice to attempt pattern
  src/Umbraco.Core/Services/IWebhookService.cs
  src/Umbraco.Core/Services/OperationStatus/WebhookOperationStatus.cs
  src/Umbraco.Core/Services/WebhookService.cs
  src/Umbraco.Web.BackOffice/Controllers/WebhookController.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/WebhookServiceTests.cs
Labels: release/13.0.0

#15184 Performance optimisations related to blocks (and multi url picker)
  src/Umbraco.Core/PropertyEditors/DefaultPropertyIndexValueFactory.cs
  src/Umbraco.Core/PropertyEditors/IPropertyIndexValueFactory.cs
  src/Umbraco.Core/PropertyEditors/JsonPropertyIndexValueFactoryBase.cs
  src/Umbraco.Core/PropertyEditors/NoopPropertyIndexValueFactory.cs
  src/Umbraco.Infrastructure/Examine/BaseValueSetBuilder.cs
  src/Umbraco.Infrastructure/Examine/ContentValueSetBuilder.cs
  src/Umbraco.Infrastructure/Examine/MediaValueSetBuilder.cs
  src/Umbraco.Infrastructure/Examine/MemberValueSetBuilder.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyIndexValueFactory.cs
  src/Umbraco.Infrastructure/PropertyEditors/MultiUrlPickerValueEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/NestedContentPropertyIndexValueFactory.cs
  src/Umbraco.Infrastructure/PropertyEditors/NestedPropertyIndexValueFactoryBase.cs
Labels: category/performance, release/10.8.0

#15196 Fix caching of media
  src/Umbraco.PublishedCache.NuCache/Persistence/NuCacheContentRepository.cs
Labels: type/bug

#15197 V10: Update @umbraco-ui/uui, jQuery, ace-editor, nouislider, spectrum-colorpicker2
  build/azure-pipelines.yml
  src/Umbraco.Web.UI.Client/.nvmrc
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/config/grid.default.config.js
Labels: dependencies, release/10.8.0, type/improvement

#15207 Added missing scope.Complete in some edge cases.
  src/Umbraco.Core/Services/ContentVersionService.cs
  src/Umbraco.Web.Website/Controllers/UmbProfileController.cs
Labels: type/bug, release/12.3.3

#15204 Updated to .NET 8 final
  global.json
  src/Umbraco.Cms.Persistence.EFCore.SqlServer/Umbraco.Cms.Persistence.EFCore.SqlServer.csproj
  src/Umbraco.Cms.Persistence.EFCore.Sqlite/Umbraco.Cms.Persistence.EFCore.Sqlite.csproj
  src/Umbraco.Cms.Persistence.EFCore/Umbraco.Cms.Persistence.EFCore.csproj
  src/Umbraco.Cms.Persistence.Sqlite/Umbraco.Cms.Persistence.Sqlite.csproj
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  tests/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
  tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
Labels: dependencies, release/13.0.0

#15220 Updated rich text parser interfaces to support context cache.
  src/Umbraco.Core/Deploy/IImageSourceParser.cs
  src/Umbraco.Core/Deploy/ILocalLinkParser.cs
  src/Umbraco.Core/Deploy/IMacroParser.cs
Labels: release/13.0.0

#15245 V13 RC: Revert change to user dialog that accidentally removed user dashboards
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/user/user.html
Labels: status/regression, type/bug

#14929 Fix button styling in block list & block grid overlay
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/blockgrid.blockconfiguration.overlay.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.overlay.less
Labels: hacktoberfest-accepted, hacktoberfest/contrib-2023

#15251 V13: Allow external login custom views to see where they are being shown
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Default.cshtml
  src/Umbraco.Web.UI.Client/src/common/services/user.service.js
  src/Umbraco.Web.UI.Client/src/main.controller.js
  src/Umbraco.Web.UI.Client/src/routes.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/user/user.html
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-login.html
  src/Umbraco.Web.UI.Login/src/components/external-login-provider.element.ts
  src/Umbraco.Web.UI.Login/src/components/pages/login.page.element.ts
  src/Umbraco.Web.UI.Login/src/external/custom-view.element.ts
  src/Umbraco.Web.UI.Login/src/mocks/customViews/my-custom-view.js
Labels: category/front-end, type/feature, release/13.0.0

#15267 V13: Implement webook as i entity
  src/Umbraco.Core/Models/IWebhook.cs
  src/Umbraco.Core/Models/Webhook.cs
  src/Umbraco.Core/Notifications/WebhookDeletedNotification .cs
  src/Umbraco.Core/Notifications/WebhookDeletingNotification.cs
  src/Umbraco.Core/Notifications/WebhookSavedNotification.cs
  src/Umbraco.Core/Notifications/WebhookSavingNotification.cs
  src/Umbraco.Core/Persistence/Repositories/IWebhookRepository.cs
  src/Umbraco.Core/Services/IWebhookFiringService.cs
  src/Umbraco.Core/Services/IWebhookLogFactory.cs
  src/Umbraco.Core/Services/IWebhookService.cs
  src/Umbraco.Core/Services/ServiceContext.cs
  src/Umbraco.Core/Services/WebhookLogFactory.cs
  src/Umbraco.Core/Services/WebhookService.cs
  src/Umbraco.Core/Webhooks/WebhookEventBase.cs
  src/Umbraco.Core/Webhooks/WebhookEventContentBase.cs
  src/Umbraco.Infrastructure/BackgroundJobs/Jobs/WebhookFiring.cs
  src/Umbraco.Infrastructure/Persistence/Factories/WebhookFactory.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/WebhookRepository.cs
  src/Umbraco.Infrastructure/Services/Implement/WebhookFiringService.cs
  src/Umbraco.Web.BackOffice/Controllers/WebhookController.cs
  src/Umbraco.Web.BackOffice/Mapping/WebhookMapDefinition.cs
  src/Umbraco.Web.BackOffice/Services/IWebhookPresentationFactory.cs
  src/Umbraco.Web.BackOffice/Services/WebhookPresentationFactory.cs
Labels: category/breaking

#15272 V13 Bugfix. Added backend validation for checking if a webhook has any events
  src/Umbraco.Core/Services/OperationStatus/WebhookOperationStatus.cs
  src/Umbraco.Core/Services/WebhookService.cs
  src/Umbraco.Web.BackOffice/Controllers/WebhookController.cs
Labels: release/13.0.0

#15269 V14: Allowing custom backoffice host with CORS policy
  src/Umbraco.Cms.Api.Management/DependencyInjection/BackOfficeCorsPolicyBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/ManagementApiComposer.cs
Labels: project/bellissima

#15287 Dynamic root with culture and segment
  src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
  src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js
Labels: release/13.0.0

#15261 Redirect is broken with Hebrew chars on Linux
  src/Umbraco.Core/Routing/ContentFinderByRedirectUrl.cs
Labels: community/pr, category/localization, type/bug, release/13.1.0

#15288 Fix `IWebhook.GetUdi()` and `IEntity.GetUdi()` extension methods
  src/Umbraco.Core/Extensions/UdiGetterExtensions.cs
  tests/Umbraco.Tests.Common/Builders/WebhookBuilder.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Extensions/UdiGetterExtensionsTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Tests.Common/Builders/WebhookBuilderTests.cs
Labels: release/13.0.0

#15285 V13: Login page backwards compatibility
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Default.cshtml
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoLogin/Index.cshtml
  src/Umbraco.Core/EmbeddedResources/Lang/bs.xml
  src/Umbraco.Core/EmbeddedResources/Lang/cs.xml
  src/Umbraco.Core/EmbeddedResources/Lang/cy.xml
  src/Umbraco.Core/EmbeddedResources/Lang/da.xml
  src/Umbraco.Core/EmbeddedResources/Lang/de.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Core/EmbeddedResources/Lang/es.xml
  src/Umbraco.Core/EmbeddedResources/Lang/fr.xml
  src/Umbraco.Core/EmbeddedResources/Lang/he.xml
  src/Umbraco.Core/EmbeddedResources/Lang/hr.xml
  src/Umbraco.Core/EmbeddedResources/Lang/it.xml
  src/Umbraco.Core/EmbeddedResources/Lang/ja.xml
  src/Umbraco.Core/EmbeddedResources/Lang/ko.xml
  src/Umbraco.Core/EmbeddedResources/Lang/nb.xml
  src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
  src/Umbraco.Core/EmbeddedResources/Lang/pl.xml
  src/Umbraco.Core/EmbeddedResources/Lang/pt.xml
  src/Umbraco.Core/EmbeddedResources/Lang/ru.xml
  src/Umbraco.Core/EmbeddedResources/Lang/sv.xml
  src/Umbraco.Core/EmbeddedResources/Lang/tr.xml
  src/Umbraco.Core/EmbeddedResources/Lang/ua.xml
  src/Umbraco.Core/EmbeddedResources/Lang/zh.xml
  src/Umbraco.Core/EmbeddedResources/Lang/zh_tw.xml
  src/Umbraco.Web.UI.Login/index.html
  src/Umbraco.Web.UI.Login/src/auth.element.ts
  src/Umbraco.Web.UI.Login/src/components/layouts/auth-layout.element.ts
  src/Umbraco.Web.UI.Login/src/components/pages/login.page.element.ts
  src/Umbraco.Web.UI.Login/src/mocks/data/texts.json
Labels: category/front-end, type/feature

#15293 Centralised NuGet packages
  src/Directory.Packages.props
  src/JsonSchema/JsonSchema.csproj
  src/Umbraco.Cms.ManagementApi/Umbraco.Cms.ManagementApi.csproj
  src/Umbraco.Cms.Persistence.Sqlite/Umbraco.Cms.Persistence.Sqlite.csproj
  src/Umbraco.Cms/Umbraco.Cms.csproj
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
  src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  templates/Umbraco.Templates.csproj
  templates/UmbracoPackage/UmbracoPackage.csproj
  templates/UmbracoProject/UmbracoProject.csproj
  tests/Directory.Packages.props
  tests/Umbraco.TestData/Umbraco.TestData.csproj
  tests/Umbraco.Tests.AcceptanceTest/package-lock.json
  tests/Umbraco.Tests.AcceptanceTest/package.json
  tests/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
  tests/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
  tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
  umbraco.sln
Labels: type/improvement

#15301 V13: Add more css custom properties to style the login screen
  src/Umbraco.Web.UI.Login/src/components/layouts/auth-layout.element.ts
Labels: type/feature

#15305 V13: Delivery API composite id handler
  src/Umbraco.Core/DeliveryApi/DeliveryApiCompositeIdHandler.cs
  src/Umbraco.Core/DeliveryApi/DeliveryApiIndexCompositeIdModel.cs
  src/Umbraco.Core/DeliveryApi/IDeliveryApiCompositeIdHandler.cs
  src/Umbraco.Examine.Lucene/DeliveryApiContentIndex.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Examine.cs
  src/Umbraco.Infrastructure/Examine/Deferred/DeliveryApiContentIndexHandleContentTypeChanges.cs
  src/Umbraco.Infrastructure/Examine/DeliveryApiContentIndexUtilites.cs
  src/Umbraco.Infrastructure/Examine/DeliveryApiContentIndexValueSetBuilder.cs
Labels: release/13.0.0

#15063 Block editors - replaces hardcoded -20 with current node ID
  src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
Labels: community/pr, category/dx, hacktoberfest-accepted, release/13.1.0

#15002 Prevent RTE in fullscreen being partially covered by the left menu column (should fix #14890)
  src/Umbraco.Web.UI.Client/src/less/application/grid.less
Labels: community/pr, category/ui, category/ux, hacktoberfest-accepted, hacktoberfest/contrib-2023, release/13.1.0

#14720 Add and use global.json to configure .NET SDK version
  build/azure-pipelines.yml
  global.json
Labels: category/dx, type/improvement

#15276 Add HealthCheckCompletedNotification
  src/Umbraco.Core/HealthChecks/HealthCheckResults.cs
  src/Umbraco.Core/Notifications/HealthCheckCompletedNotification.cs
  src/Umbraco.Infrastructure/BackgroundJobs/Jobs/HealthCheckNotifierJob.cs
  src/Umbraco.Web.BackOffice/HealthChecks/HealthCheckController.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/BackgroundJobs/Jobs/HealthCheckNotifierJobTests.cs
Labels: community/pr, category/dx, type/feature, release/13.0.0

#14960 Added BlockEditorDataConverter method to BlockListPropertyEditorBase …
  src/Umbraco.Infrastructure/Models/Blocks/BlockListEditorDataConverter.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockListPropertyEditorBase.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/DataValueEditorReuseTests.cs
Labels: community/pr, type/bug, hacktoberfest-accepted, release/13.0.0, hacktoberfest/contrib-2023

#14879 Added `[NotNullWhen(true)]` attribute to `IPublishedSnapshotAccessor` and `UmbracoContextPublishedSnapshotAccessor`
  src/Umbraco.Core/PublishedCache/IPublishedSnapshotAccessor.cs
  src/Umbraco.Core/PublishedCache/UmbracoContextPublishedSnapshotAccessor.cs
Labels: hacktoberfest-accepted, hacktoberfest/contrib-2023

#14906 Added ReSharperTestRunner to KnownAssemblyExclusionFilter
  src/Umbraco.Core/Composing/TypeFinder.cs
Labels: hacktoberfest-accepted, hacktoberfest/contrib-2023

#14939 fixed #14832 user without HasAccessToSensitiveData change sensitive data: IsApproved IsApproved IsTwoFactorEnabled
  src/Umbraco.Web.BackOffice/Controllers/MemberController.cs
Labels: community/pr, hacktoberfest-accepted, type/improvement, hacktoberfest/contrib-2023, release/13.1.0

#14980 Bugfix: #14481 - Landmark roles missing
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Default.cshtml
  src/Umbraco.Core/EmbeddedResources/Lang/da.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Web.UI.Client/src/index.html
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-app-header.html
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-navigation.html
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-search.html
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-sections.html
Labels: community/pr, category/accessibility, hacktoberfest-accepted, type/improvement, hacktoberfest/contrib-2023, release/13.1.0

#15034 Add contentTypeEditor to editorService
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js
  src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
  src/Umbraco.Web.UI.Client/src/views/dataTypes/views/datatype.info.controller.js
Labels: community/pr, category/dx, type/feature, hacktoberfest-accepted, release/13.0.0, hacktoberfest/contrib-2023

#15040 Bugfix: #15036 - Password Is Not Hidden During Installation
  src/Umbraco.Web.UI.Client/src/installer/steps/user.controller.js
  src/Umbraco.Web.UI.Client/src/installer/steps/user.html
  src/Umbraco.Web.UI.Client/src/less/installer.less
Labels: community/pr, hacktoberfest-accepted, project/bellissima, type/improvement, hacktoberfest/contrib-2023, release/13.1.0

#15087 Make Block List configuration consistent with Block Grid
  src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card-grid.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/blockgrid.blockconfiguration.less
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.less
Labels: hacktoberfest-accepted, project/bellissima

#15080 Adjust content type picker to support different content types
  src/Umbraco.Web.UI.Client/src/common/services/editor.service.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/prevalue/blockgrid.blockconfiguration.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/prevalue/blocklist.blockconfiguration.controller.js
Labels: community/pr, hacktoberfest-accepted, type/improvement, release/13.1.0

#15335 Fix log message in `Verify2FACode` method
  src/Umbraco.Web.Website/Controllers/UmbTwoFactorLoginController.cs
Labels: community/pr, release/no-notes, type/improvement, release/13.1.0
