Repository umbraco/Umbraco-CMS, pull requests merged in 2023-06, with the labels that each got.

#14318 v14: login app
  .gitignore
  src/Umbraco.Cms.Api.Management/Controllers/BackOfficeLoginController.cs
  src/Umbraco.Cms.StaticAssets/Umbraco.Cms.StaticAssets.csproj
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoLogin/Index.cshtml
Labels: project/bellissima

#14340 Update OpenIdDict
  src/Umbraco.Cms.Api.Common/Umbraco.Cms.Api.Common.csproj
  src/Umbraco.Cms.Persistence.EFCore/Umbraco.Cms.Persistence.EFCore.csproj
Labels: release/12.0.0

#14326 V14: Update template controllers
  src/Umbraco.Cms.Api.Management/Controllers/Template/ByKeyTemplateController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Template/Item/ItemTemplateItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Template/ScaffoldTemplateController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Template/TemplateControllerBase.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/TemplateBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/Factories/ITemplatePresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/TemplatePresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Mapping/Items/ItemTypeMapDefinition.cs
  src/Umbraco.Cms.Api.Management/Mapping/Template/TemplateViewModelMapDefinition.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Template/Item/TemplateItemResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Template/TemplateResponseModel.cs
  src/Umbraco.Core/Services/ITemplateService.cs
  src/Umbraco.Core/Services/OperationStatus/TemplateOperationStatus.cs
  src/Umbraco.Core/Services/TemplateService.cs
  src/Umbraco.Web.BackOffice/Controllers/TemplateController.cs
  tests/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTestWithContent.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Packaging/PackageDataInstallationTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/DocumentRepositoryTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServicePerformanceTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/EntityServiceTests.cs
Labels: project/bellissima

#14352 Add get ByEditorUiAlias datatype item endpoint
  src/Umbraco.Cms.Api.Management/Controllers/DataType/Items/ByEditorUiAliasController.cs
  src/Umbraco.Core/Services/DataTypeService.cs
  src/Umbraco.Core/Services/IDataTypeService.cs
  src/Umbraco.Infrastructure/Persistence/Mappers/DataTypeMapper.cs
Labels: project/bellissima

#14353 V14: Replace usage of SortedSet with HashSets and ISets
  src/Umbraco.Cms.Api.Management/Controllers/DataType/Items/ItemDatatypeItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Dictionary/Item/ItemDictionaryItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/Item/ItemDocumentItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/DocumentBlueprint/Item/ItemDocumentBlueprintController.cs
  src/Umbraco.Cms.Api.Management/Controllers/DocumentType/Item/ItemDocumentTypeItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Language/Item/ItemsLanguageEntityController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Media/Item/ItemMediaItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/MediaType/Item/ItemMediaTypeItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Member/Item/ItemMemberItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/MemberGroup/Item/ItemMemberGroupItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/MemberType/Items/ItemMemberTypeItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/PartialView/Items/ItemPartialViewItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/RelationType/Item/ItemRelationTypeItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Script/Item/ItemScriptItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/StaticFile/Item/ItemStaticFileItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Stylesheet/Item/ItemStylesheetItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Template/Item/ItemTemplateItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/TrackedReference/ItemsTrackedReferenceController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/FilterUsersController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/Item/ItemUserItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/UserGroup/Item/ItemUserGroupItemController.cs
  src/Umbraco.Cms.Api.Management/Factories/UserPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/ViewModels/User/DisableUserRequestModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/User/EnableUserRequestModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/User/UnlockUsersRequestModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/User/UpdateUserGroupsOnUserRequestModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/User/UpdateUserRequestModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/User/UserPresentationBase.cs
  src/Umbraco.Core/Models/Membership/UserFilter.cs
  src/Umbraco.Core/Models/UserUpdateModel.cs
  src/Umbraco.Core/Services/UserService.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/UserServiceCrudTests.Filter.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/UserServiceCrudTests.Update.cs
Labels: project/bellissima

#12345 Fix for escaping markdown characters in property descriptions
  src/Umbraco.Web.BackOffice/Mapping/ContentMapDefinition.cs
  src/Umbraco.Web.BackOffice/Security/BackOfficeAntiforgery.cs
  src/Umbraco.Web.BackOffice/Umbraco.Web.BackOffice.csproj
  src/Umbraco.Web.UI.Client/src/common/directives/components/property/umbproperty.directive.js
  src/Umbraco.Web.UI.Client/src/common/filters/simpleMarkdown.filter.js
  src/Umbraco.Web.UI.Client/src/common/filters/simpleMarkdown.filter.js.js
  src/Umbraco.Web.UI.Client/src/views/components/property/umb-property.html
Labels: community/pr, category/ux, type/bug, release/12.1.0

#14252 Disable sortable if readonly or max is limited to one item
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Web.UI.Client/src/views/components/mediacard/umb-media-card.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker3/umb-media-picker3-property-editor.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker3/umbMediaPicker3PropertyEditor.component.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/multiurlpicker/multiurlpicker.html
Labels: category/ux, release/12.1.0

#14362 Update security stamps on logout
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilder.MembersIdentity.cs
  src/Umbraco.Web.Common/Security/ConfigureMemberCookieOptions.cs
  src/Umbraco.Web.Common/Security/MemberSecurityStampValidator.cs
  src/Umbraco.Web.Common/Security/MemberSecurityStampValidatorOptions.cs
  src/Umbraco.Web.Common/Security/UmbracoSignInManager.cs
Labels: release/12.0.0, release/10.6.0, release/11.4.1

#14379 Add Croatian backoffice language
  src/Umbraco.Core/EmbeddedResources/Lang/hr.xml
Labels: category/ui, category/ux, category/localization, category/dx, type/feature, release/12.1.0

#14392 #14388 - Change the outdated "no nodes" image
  src/Umbraco.Web.UI.Client/src/assets/img/nonodesbg.jpg
  src/Umbraco.Web.UI.Client/src/assets/img/nonodesbg.webp
  src/Umbraco.Web.UI.Client/src/less/pages/nonodes.less
Labels: category/ui, category/ux, type/feature, category/umbraco-cms

#14396 Fix/delete language error message 14333
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Core/EmbeddedResources/Lang/hr.xml
  src/Umbraco.Web.UI.Client/src/views/languages/overlays/delete.html
Labels: category/ui, category/localization, release/12.1.0

#14395 Makes sure the nucache is not truncated when its null
  src/Umbraco.PublishedCache.NuCache/Persistence/NuCacheContentRepository.cs
Labels: type/bug, category/umbraco-cms, release/12.1.0

#14370 Delivery API: Add query params and headers to Swagger document
  src/Umbraco.Cms.Api.Delivery/Configuration/ConfigureUmbracoDeliveryApiSwaggerGenOptions.cs
  src/Umbraco.Cms.Api.Delivery/Configuration/DeliveryApiConfiguration.cs
  src/Umbraco.Cms.Api.Delivery/Filters/SwaggerDocumentationFilter.cs
Labels: release/12.0.0

#14412 v14: update package templates with new umbraco-package.json format
  templates/UmbracoPackage/App_Plugins/UmbracoPackage/package.manifest
  templates/UmbracoPackage/App_Plugins/UmbracoPackage/umbraco-package.json
  templates/UmbracoPackageRcl/wwwroot/package.manifest
  templates/UmbracoPackageRcl/wwwroot/umbraco-package.json
Labels: project/bellissima

#14406 v10: Backoffice JS updates
  .github/workflows/pr-first-response.yml
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
Labels: dependencies, release/10.6.0

#14407 v11: Backoffice JS Updates
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
Labels: dependencies, area/frontend, release/11.4.1

#14402 Fixed typo "optinal" to "optional" for translation dictionary import dialog
  src/Umbraco.Core/EmbeddedResources/Lang/de.xml
  src/Umbraco.Web.UI.Client/lib/markdown/markdown.editor.js
  src/Umbraco.Web.UI.Client/src/views/dictionary/import.html
Labels: category/ui, type/bug, state/reproduced, area/frontend, release/12.1.0

#14418 V12: Add deliver api information to detailed telemetry
  src/Umbraco.Core/Constants-Telemetry.cs
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.TelemetryProviders.cs
  src/Umbraco.Infrastructure/Telemetry/Providers/DeliveryApiTelemetryProvider.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Telemetry/TelemetryServiceTests.cs
Labels: release/12.0.0

#14419 Updated nuget packages to latest versions
  src/Umbraco.Cms.Api.Common/Umbraco.Cms.Api.Common.csproj
  src/Umbraco.Cms.Persistence.EFCore/Umbraco.Cms.Persistence.EFCore.csproj
  src/Umbraco.Cms.Persistence.Sqlite/Umbraco.Cms.Persistence.Sqlite.csproj
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
  src/Umbraco.Web.Common/Profiler/WebProfiler.cs
  src/Umbraco.Web.Common/Profiler/WebProfilerHtml.cs
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  tests/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
  tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
Labels: dependencies, release/12.0.0

#14421 Add support for property value fallbacks in the delivery API
  src/Umbraco.Cms.Api.Delivery/Rendering/RequestContextOutputExpansionStrategy.cs
  src/Umbraco.Core/DeliveryApi/IApiPropertyRenderer.cs
  src/Umbraco.Core/DeliveryApi/PropertyRenderer.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/DeliveryApiTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/OutputExpansionStrategyTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/PropertyRendererTests.cs
Labels: type/feature, release/12.0.0

#14429 Return raw markdown in the Delivery API
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/MarkdownEditorValueConverter.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/MarkdownEditorValueConverterTests.cs
Labels: type/feature, release/12.0.0

#14428 Delivery API: Ensure the path parameter starts with forward slash
  src/Umbraco.Cms.Api.Delivery/Controllers/ByRouteContentApiController.cs
Labels: release/12.0.0

#14442 Added acceptance tests for testing the API for the Stylesheet section.
  tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/Stylesheet/Stylesheet.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/Stylesheet/StylesheetFolder.spec.ts
Labels: category/acceptance-tests

#14463 Auto-detect custom Image type on drag and drop
  src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
Labels: type/bug

#14469 Handle upload error when file size is bigger than the configured value
  src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
Labels: type/bug, release/10.7.0

#14434 V14: allowed children endpoints
  src/Umbraco.Cms.Api.Management/Content/ContentControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/AllowedChildrenByKeyDocumentController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/AllowedChildrenOfRootDocumentController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/DocumentControllerBase.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Core/Services/ContentCreatingService.cs
  src/Umbraco.Core/Services/ContentTypeService.cs
  src/Umbraco.Core/Services/IContentCreatingService.cs
  src/Umbraco.Core/Services/IContentTypeService.cs
  src/Umbraco.Core/Services/OperationStatus/ContentCreatingOperationStatus.cs
  src/Umbraco.Core/Services/OperationStatus/ContentTypeOperationStatus.cs
Labels: project/bellissima

#14478 V14: Skip and take updates
  src/Umbraco.Cms.Api.Management/Controllers/AuditLog/CurrentUserAuditLogController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Help/GetHelpController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Indexer/AllIndexerController.cs
  src/Umbraco.Cms.Api.Management/Controllers/PropertyType/IsUsedPropertyTypeController.cs
  src/Umbraco.Cms.Api.Management/Controllers/RedirectUrlManagement/ByKeyRedirectUrlManagementController.cs
  src/Umbraco.Cms.Api.Management/Controllers/RedirectUrlManagement/GetAllRedirectUrlManagementController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Relation/ByChildRelationController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Searcher/AllSearcherController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Searcher/QuerySearcherController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Telemetry/AllTelemetryController.cs
  src/Umbraco.Cms.Api.Management/Controllers/TrackedReference/ByIdTrackedReferenceController.cs
  src/Umbraco.Cms.Api.Management/Controllers/TrackedReference/DescendantsTrackedReferenceController.cs
  src/Umbraco.Cms.Api.Management/Controllers/TrackedReference/ItemsTrackedReferenceController.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
Labels: project/bellissima

#14479 Add additional preview URLs option
  src/Umbraco.Core/Models/ContentEditing/ContentVariationDisplay.cs
  src/Umbraco.Core/Models/ContentEditing/NamedUrl.cs
  src/Umbraco.Web.BackOffice/Mapping/ContentMapDefinition.cs
Labels: type/feature, release/12.1.0
