Repository umbraco/Umbraco-CMS, pull requests merged in 2023-02, with the labels that each got.

#13751 Use ISO codes instead of language IDs for fallback languages and translations
  src/Umbraco.Cms.Api.Management/Controllers/Language/AllLanguageController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Language/ByIsoCodeLanguageController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Language/CreateLanguageController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Language/LanguageControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/Language/UpdateLanguageController.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/LanguageBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/Factories/DictionaryFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/ILanguageFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/LanguageFactory.cs
  src/Umbraco.Cms.Api.Management/Mapping/Dictionary/DictionaryMapDefinition.cs
  src/Umbraco.Cms.Api.Management/Mapping/Language/LanguageViewModelsMapDefinition.cs
  src/Umbraco.Core/CompatibilitySuppressions.xml
  src/Umbraco.Core/Dictionary/UmbracoCultureDictionary.cs
  src/Umbraco.Core/Models/ContentEditing/Language.cs
  src/Umbraco.Core/Models/DictionaryItem.cs
  src/Umbraco.Core/Models/DictionaryItemExtensions.cs
  src/Umbraco.Core/Models/DictionaryTranslation.cs
  src/Umbraco.Core/Models/IDictionaryTranslation.cs
  src/Umbraco.Core/Models/ILanguage.cs
  src/Umbraco.Core/Models/Language.cs
  src/Umbraco.Core/Models/Mapping/DictionaryMapDefinition.cs
  src/Umbraco.Core/Models/Mapping/LanguageMapDefinition.cs
  src/Umbraco.Core/Models/PublishedContent/PublishedValueFallback.cs
  src/Umbraco.Core/Services/DictionaryItemService.cs
  src/Umbraco.Core/Services/EntityXmlSerializer.cs
  src/Umbraco.Core/Services/LanguageService.cs
  src/Umbraco.Core/Services/LocalizationService.cs
  src/Umbraco.Core/Services/OperationStatus/LanguageOperationStatus.cs
  src/Umbraco.Infrastructure/Packaging/PackageDataInstallation.cs
  src/Umbraco.Infrastructure/Persistence/Factories/DictionaryItemFactory.cs
  src/Umbraco.Infrastructure/Persistence/Factories/DictionaryTranslationFactory.cs
  src/Umbraco.Infrastructure/Persistence/Factories/LanguageFactory.cs
  src/Umbraco.Infrastructure/Persistence/Mappers/DictionaryTranslationMapper.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DictionaryRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/LanguageRepository.cs
  src/Umbraco.Web.BackOffice/Controllers/LanguageController.cs
  tests/Umbraco.Tests.Common/Builders/LanguageBuilder.cs
  tests/Umbraco.Tests.Common/CompatibilitySuppressions.xml
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/TelemetryProviderTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Packaging/PackageDataInstallationTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/DictionaryRepositoryTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/LanguageRepositoryTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Scoping/ScopedRepositoryTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/DictionaryItemServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/Dictionary-Package.xml
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/Importing/ImportResources.Designer.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/LanguageServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/LocalizationServiceTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/DictionaryItemTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/DictionaryTranslationTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Persistence/Mappers/DictionaryTranslationMapperTest.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/PublishedCache/PublishedContentLanguageVariantTests.cs
Labels: category/breaking, release/13.0.0

#13767 Isolate maintenance page from published content cache
  src/Umbraco.Infrastructure/Persistence/Dtos/KeyValueDto.cs
  src/Umbraco.Web.Common/Controllers/MaintenanceModeActionFilterAttribute.cs
  src/Umbraco.Web.Common/Controllers/PublishedRequestFilterAttribute.cs
  src/Umbraco.Web.Website/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformer.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformerTests.cs
Labels: type/bug, release/11.2.0, release/10.5.0

#13676 New backoffice: Obsolete ReadOnlyUserGroup constructor.
  src/Umbraco.Core/Models/Membership/ReadOnlyUserGroup.cs
  src/Umbraco.Core/Models/Membership/UserGroupExtensions.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Editors/UserEditorAuthorizationHelperTests.cs
Labels: release/11.2.0

#13787 Updated nuget dependencies
  src/Umbraco.Cms.ManagementApi/Umbraco.Cms.ManagementApi.csproj
  src/Umbraco.Cms.Persistence.Sqlite/Umbraco.Cms.Persistence.Sqlite.csproj
  src/Umbraco.Cms.Targets/Umbraco.Cms.Targets.csproj
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  tests/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
  tests/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
  tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
Labels: dependencies, release/11.2.0

#13672 New backoffice: Add GUIDS to user groups
  src/Umbraco.Cms.Persistence.Sqlite/Services/SqliteSyntaxProvider.cs
  src/Umbraco.Core/CompatibilitySuppressions.xml
  src/Umbraco.Core/Models/Membership/IReadOnlyUserGroup.cs
  src/Umbraco.Core/Models/Membership/ReadOnlyUserGroup.cs
  src/Umbraco.Core/Models/Membership/UserGroupExtensions.cs
  src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs
  src/Umbraco.Infrastructure/Migrations/MigrationContext.cs
  src/Umbraco.Infrastructure/Migrations/UnscopedMigrationBase.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_13_0_0/AddGuidsToUserGroups.cs
  src/Umbraco.Infrastructure/Persistence/Dtos/UserGroupDto.cs
  src/Umbraco.Infrastructure/Persistence/Factories/UserFactory.cs
  src/Umbraco.Infrastructure/Persistence/Factories/UserGroupFactory.cs
  src/Umbraco.Infrastructure/Persistence/Mappers/UserGroupMapper.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/UserGroupRepository.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Editors/UserEditorAuthorizationHelperTests.cs
Labels: project/new-backoffice

#13743 Fixes #13732 - IsBackOfficeRequest is extremely inefficient
  src/Umbraco.Core/Routing/UmbracoRequestPaths.cs
Labels: community/pr

#13843 V13: website assets directly from static assets
  .gitignore
  build/azure-pipelines.yml
  src/Umbraco.Cms.StaticAssets/Umbraco.Cms.StaticAssets.csproj
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoWebsite/Maintenance.cshtml
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoWebsite/NoNodes.cshtml
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoWebsite/NotFound.cshtml
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/website/fonts/lato/LatoLatin-Black.woff2
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/website/fonts/lato/LatoLatin-BlackItalic.woff2
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/website/fonts/lato/LatoLatin-Bold.woff2
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/website/fonts/lato/LatoLatin-BoldItalic.woff2
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/website/fonts/lato/LatoLatin-Italic.woff2
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/website/fonts/lato/LatoLatin-Light.woff2
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/website/fonts/lato/LatoLatin-LightItalic.woff2
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/website/fonts/lato/LatoLatin-Regular.woff2
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/website/nonodes.css
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/website/nonodesbg.jpg
Labels: project/new-backoffice

#13846 Removed failing test
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/content.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/recycleBin.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Media/mediaFiles.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Media/mediaSection.spec.ts
Labels: project/new-backoffice

#13853 Document and document type read API
  src/Umbraco.Cms.Api.Management/Controllers/Document/ByKeyDocumentController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/DocumentControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/DocumentType/ByKeyDocumentTypeController.cs
  src/Umbraco.Cms.Api.Management/Controllers/DocumentType/DocumentControllerBase.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/DocumentBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/DocumentTypeBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/Factories/ContentUrlFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/DocumentViewModelFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/IContentUrlFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/IDocumentViewModelFactory.cs
  src/Umbraco.Cms.Api.Management/ManagementApiComposer.cs
  src/Umbraco.Cms.Api.Management/Mapping/Content/ContentMapDefinition.cs
  src/Umbraco.Cms.Api.Management/Mapping/ContentType/ContentTypeMapDefinition.cs
  src/Umbraco.Cms.Api.Management/Mapping/Document/DocumentMapDefinition.cs
  src/Umbraco.Cms.Api.Management/Mapping/DocumentType/DocumentTypeMapDefinition.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/Content/ContentState.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Content/ContentUrlInfo.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Content/ContentViewModelBase.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Content/ValueViewModelBase.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Content/VariantViewModelBase.cs
  src/Umbraco.Cms.Api.Management/ViewModels/ContentType/ContentTypeCleanup.cs
  src/Umbraco.Cms.Api.Management/ViewModels/ContentType/ContentTypeComposition.cs
  src/Umbraco.Cms.Api.Management/ViewModels/ContentType/ContentTypeCompositionType.cs
  src/Umbraco.Cms.Api.Management/ViewModels/ContentType/ContentTypeSort.cs
  src/Umbraco.Cms.Api.Management/ViewModels/ContentType/ContentTypeViewModelBase.cs
  src/Umbraco.Cms.Api.Management/ViewModels/ContentType/PropertyTypeAppearance.cs
  src/Umbraco.Cms.Api.Management/ViewModels/ContentType/PropertyTypeContainerViewModelBase.cs
  src/Umbraco.Cms.Api.Management/ViewModels/ContentType/PropertyTypeValidation.cs
  src/Umbraco.Cms.Api.Management/ViewModels/ContentType/PropertyTypeViewModelBase.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentValueViewModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentVariantViewModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentViewModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/DocumentTypePropertyTypeContainerViewModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/DocumentTypePropertyTypeViewModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/DocumentTypeViewModel.cs
  src/Umbraco.Core/CompatibilitySuppressions.xml
  src/Umbraco.Core/Models/ContentTypeSort.cs
  src/Umbraco.Core/Routing/UrlProviderExtensions.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/Models/Mapping/EntityMapDefinition.cs
  src/Umbraco.Infrastructure/Packaging/PackageDataInstallation.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeCommonRepository.cs
  src/Umbraco.Infrastructure/Serialization/ContextualJsonSerializer.cs
  src/Umbraco.Infrastructure/Serialization/SystemTextConfigurationEditorJsonSerializer.cs
  src/Umbraco.Infrastructure/Serialization/SystemTextJsonSerializer.cs
  tests/Umbraco.TestData/LoadTestController.cs
  tests/Umbraco.Tests.Common/Builders/ContentTypeSortBuilder.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/ContentTypeRepositoryTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServicePerformanceTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServiceTagsTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Web.BackOffice/UrlAndDomains/DomainAndUrlsTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/GetContentUrlsTests.cs
Labels: category/breaking

#13849 Use keys for tracked references
  src/Umbraco.Cms.Api.Management/Controllers/TrackedReference/ByIdTrackedReferenceController.cs
  src/Umbraco.Cms.Api.Management/Controllers/TrackedReference/DescendantsTrackedReferenceController.cs
  src/Umbraco.Cms.Api.Management/Controllers/TrackedReference/ItemsTrackedReferenceController.cs
  src/Umbraco.Cms.Api.Management/Mapping/TrackedReferences/TrackedReferenceViewModelsMapDefinition.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/TrackedReferences/RelationItemViewModel.cs
  src/Umbraco.Core/Models/RelationItemModel.cs
  src/Umbraco.Core/Persistence/Repositories/ITrackedReferencesRepository.cs
  src/Umbraco.Core/Services/ITrackedReferencesService.cs
  src/Umbraco.Core/Services/TrackedReferencesService.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/TrackedReferencesRepository.cs
  src/Umbraco.Infrastructure/Persistence/UmbracoDatabaseExtensions.cs
  src/Umbraco.New.Cms.Infrastructure/Persistence/Mappers/RelationModelMapDefinition.cs
Labels: project/new-backoffice

#13861 Fixed profiling status endpoints and added an update endpoint
  src/Umbraco.Cms.Api.Management/Controllers/Profiling/GetStatusProfilingController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Profiling/ProfilingControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/Profiling/StatusProfilingController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Profiling/UpdateStatusProfilingController.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Default.cshtml
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Core/Persistence/Repositories/IWebProfilerRepository.cs
  src/Umbraco.Core/Services/IWebProfilerService.cs
  src/Umbraco.Core/Services/OperationStatus/WebProfilerOperationStatus.cs
  src/Umbraco.Core/Services/WebProfilerService.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Profiler/WebProfiler.cs
  src/Umbraco.Web.Common/Repositories/WebProfilerRepository.cs
  src/Umbraco.Web.Common/UmbracoContext/UmbracoContext.cs
  src/Umbraco.Web.Common/UmbracoContext/UmbracoContextFactory.cs
  tests/Umbraco.Tests.Integration/TestServerTest/UmbracoTestServerTestBase.cs
  tests/Umbraco.Tests.Integration/Testing/TestWebProfilerRepository.cs
  tests/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
  tests/Umbraco.Tests.UnitTests/TestHelpers/Objects/TestUmbracoContextFactory.cs
Labels: project/new-backoffice

#13866 Reset selected index/searcher
  src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.controller.js
Labels: community/pr, type/bug, release/10.5.0, release/11.3.0

#13842 V13: Audit log controller
  src/Umbraco.Cms.Api.Management/Controllers/AuditLog/AuditLogControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/AuditLog/ByKeyAuditLogController.cs
  src/Umbraco.Cms.Api.Management/Controllers/AuditLog/ByTypeAuditLogController.cs
  src/Umbraco.Cms.Api.Management/Controllers/AuditLog/CurrentUserAuditLogController.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/AuditLogBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/Factories/AuditLogViewModelFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/IAuditLogViewModelFactory.cs
  src/Umbraco.Cms.Api.Management/ManagementApiComposer.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/AuditLogs/AuditLogBaseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/AuditLogs/AuditLogResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/AuditLogs/AuditLogWithUsernameResponseModel.cs
  src/Umbraco.Core/Models/AuditItem.cs
  src/Umbraco.Core/PaginationHelper.cs
  src/Umbraco.Core/Services/AuditService.cs
  src/Umbraco.Core/Services/IAuditService.cs
  src/Umbraco.Core/Services/OperationStatus/AuditLogOperationStatus.cs
  src/Umbraco.Core/Services/UserServiceExtensions.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/AuditRepository.cs
Labels: project/new-backoffice

#13578 New Backoffice: Package controller
  src/Umbraco.Cms.Api.Management/Controllers/Dictionary/DictionaryControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/LogViewer/LogLevelCountLogViewerController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Package/AllMigrationStatusPackageController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Package/Created/AllCreatedPackageController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Package/Created/ByKeyCreatedPackageController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Package/Created/CreateCreatedPackageController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Package/Created/CreatedPackageControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/Package/Created/DeleteCreatedPackageController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Package/Created/DownloadCreatedPackageController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Package/Created/UpdateCreatedPackageController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Package/PackageControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/Package/RunMigrationPackageController.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/PackageBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/Factories/IPackageDefinitionFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/PackageDefinitionFactory.cs
  src/Umbraco.Cms.Api.Management/ManagementApiComposer.cs
  src/Umbraco.Cms.Api.Management/Mapping/Package/PackageViewModelMapDefinition.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/Package/PackageCreateModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Package/PackageDefinitionViewModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Package/PackageMigrationStatusViewModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Package/PackageModelBase.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Package/PackageUpdateModel.cs
  src/Umbraco.Core/CompatibilitySuppressions.xml
  src/Umbraco.Core/Packaging/IPackageDefinitionRepository.cs
  src/Umbraco.Core/Packaging/PackagesRepository.cs
  src/Umbraco.Core/Services/IPackagingService.cs
  src/Umbraco.Core/Services/OperationStatus/PackageMigrationOperationStatus.cs
  src/Umbraco.Core/Services/OperationStatus/PackageOperationStatus.cs
  src/Umbraco.Infrastructure/Install/PackageMigrationRunner.cs
  src/Umbraco.Infrastructure/Migrations/MigrationPlanExecutor.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_13_0_0/UpdateDefaultGuidsOfCreatedPackages.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/CreatedPackageSchemaRepository.cs
  src/Umbraco.Infrastructure/Services/Implement/PackagingService.cs
Labels: category/breaking, project/new-backoffice

#13894 Use latest c# language version instead of csharp 8 in runtime views
  src/Umbraco.Web.Common/ModelsBuilder/InMemoryAuto/CompilationOptionsProvider.cs
Labels: release/11.3.0
