Repository umbraco/Umbraco-CMS, pull requests merged in 2023-12, with the labels that each got.

#15334 V13 RC: Fix regression for external login providers
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
Labels: type/bug

#14940 Fixed potential NuCache file lock causing unusable website
  src/Umbraco.PublishedCache.NuCache/PublishedSnapshotService.cs
Labels: hacktoberfest-accepted, hacktoberfest/contrib-2023

#15150 Expose the Delivery API CLR type
  src/Umbraco.Core/Models/PublishedContent/IPublishedPropertyType.cs
  src/Umbraco.Core/Models/PublishedContent/PublishedPropertyType.cs
Labels: community/pr, type/feature, release/13.0.0

#15351 Change `WebhookEventCollectionBuilder` to set collection
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.CollectionBuilders.cs
  src/Umbraco.Core/Webhooks/WebhookEventCollectionBuilder.cs
  src/Umbraco.Core/Webhooks/WebhookEventCollectionBuilderCmsContentExtensions.cs
  src/Umbraco.Core/Webhooks/WebhookEventCollectionBuilderCmsContentTypeExtensions.cs
  src/Umbraco.Core/Webhooks/WebhookEventCollectionBuilderCmsExtensions.cs
  src/Umbraco.Core/Webhooks/WebhookEventCollectionBuilderCmsFileExtensions.cs
  src/Umbraco.Core/Webhooks/WebhookEventCollectionBuilderCmsMemberExtensions.cs
  src/Umbraco.Core/Webhooks/WebhookEventCollectionBuilderCmsUserExtensions.cs
Labels: category/breaking, release/13.0.0

#15059 Don't overwrite default values in the block list editor
  src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
Labels: hacktoberfest-accepted

#15350 Fix console errors in content type editor with single block mode
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
Labels: community/pr, type/bug, release/13.1.0

#15354 Ensure the toggles return booleans and not integers.
  src/Umbraco.Web.UI.Client/src/common/services/umbdataformatter.service.js
Labels: release/13.0.0

#15390 V13: Log retrycount and properly log request headers
  src/Umbraco.Core/Services/WebhookLogFactory.cs
Labels: release/13.0.0

#15391 V13: Link to error when Webhook request exceptions happen
  src/Umbraco.Web.UI.Client/src/views/webhooks/overlays/details.html
Labels: release/13.0.0

#15393 V13: Log webhook firing exceptions when they happen
  src/Umbraco.Core/Models/WebhookLog.cs
  src/Umbraco.Core/Models/WebhookResponseModel.cs
  src/Umbraco.Core/Services/IWebhookLogFactory.cs
  src/Umbraco.Core/Services/WebhookLogFactory.cs
  src/Umbraco.Infrastructure/BackgroundJobs/Jobs/WebhookFiring.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_13_0_0/AddExceptionOccured.cs
  src/Umbraco.Infrastructure/Persistence/Dtos/WebhookLogDto.cs
  src/Umbraco.Infrastructure/Persistence/Factories/WebhookLogFactory.cs
  src/Umbraco.Web.BackOffice/Mapping/WebhookMapDefinition.cs
  src/Umbraco.Web.Common/Models/WebhookLogViewModel.cs
  src/Umbraco.Web.UI.Client/src/views/webhooks/overlays/details.html
Labels: category/breaking, release/13.0.0

#15407 Remove date header from webhook request and use constants
  src/Umbraco.Core/Constants-WebhookEvents.cs
  src/Umbraco.Infrastructure/BackgroundJobs/Jobs/WebhookFiring.cs
Labels: category/breaking, release/13.0.0

#15425 Ensure thread safety for block editor constructor caches
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockEditorPropertyValueConstructorCacheBase.cs
Labels: release/13.0.0

#15442 V14: Rename user controller files to match class names
  src/Umbraco.Cms.Api.Management/Controllers/User/BulkDeleteUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/ByKeyUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/ChangePasswordUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/ClearAvatarUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/CreateUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/DeleteUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/DisableUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/EnableUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/FilterUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/GetAllUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/InviteUsersController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/ResendInviteUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/SetAvatarUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/UnlockUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/UpdateUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/UpdateUserGroupsUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/UserControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/VerifyInviteUserController.cs
Labels: project/bellissima

#15454 13: Add old databasemodel to ChangeLogStatusCode migration
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_13_0_0/ChangeLogStatusCode.cs
Labels: release/13.0.1

#15457 V14: Tighten permissions for folder controllers
  src/Umbraco.Cms.Api.Management/Controllers/DataType/Folder/DataTypeFolderControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/DocumentType/Folder/DocumentTypeFolderControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/MediaType/Folder/MediaTypeFolderControllerBase.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/BackOfficeAuthPolicyBuilderExtensions.cs
Labels: type/bug, project/bellissima

#15472 V14: add the cors policy as first item on the pipeline filter
  src/Umbraco.Cms.Api.Management/DependencyInjection/BackOfficeCorsPolicyBuilderExtensions.cs
Labels: type/feature

#15484 Add policies for content template handling (backport of #15482)
  src/Umbraco.Web/Actions/ActionCreateBlueprintFromContent.cs
  src/Umbraco.Web/Editors/ContentController.cs
  src/Umbraco.Web/Editors/Filters/ContentSaveValidationAttribute.cs
Labels: release/8.18.12

#15487 Batched more update calls to avoid Sql paramater count error
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs
Labels: affected/v10, affected/v12, affected/v14, affected/v13

#15500 Ensure artifact dependency keeps correct mode, ordering and checksum values
  src/Umbraco.Core/Deploy/ArtifactDependency.cs
  src/Umbraco.Core/Deploy/ArtifactDependencyCollection.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Deploy/ArtifactBaseTests.cs
Labels: status/regression, type/bug, release/13.0.3

#15497 V14: Server information
  src/Umbraco.Cms.Api.Management/Controllers/Server/InformationServerController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Server/TroubleshootingServerController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Server/VersionServerController.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/ServerBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/Mapping/Server/ServerConfigurationMapDefinition.cs
  src/Umbraco.Cms.Api.Management/Mapping/Server/ServerInformationMapDefinition.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/Server/ServerConfigurationBaseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Server/ServerConfigurationItemResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Server/ServerInformationResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Server/ServerTroubleshootingResponseModel.cs
  src/Umbraco.Core/Models/ServerInformation.cs
  src/Umbraco.Core/Services/IServerInformationService.cs
  src/Umbraco.Core/Services/ISystemTroubleshootingInformationService.cs
  src/Umbraco.Core/Services/IUserDataService.cs
  src/Umbraco.Core/Services/UserDataService.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Services.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.TelemetryProviders.cs
  src/Umbraco.Infrastructure/Telemetry/Providers/SystemTroubleshootingInformationTelemetryProvider.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Services/SystemInformationServiceTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Telemetry/SystemTroubleshootingInformationTelemetryProviderTests.cs
Labels: project/bellissima

#15507 V14: Security configuration
  src/Umbraco.Cms.Api.Management/Controllers/Server/ConfigurationServerController.cs
  src/Umbraco.Cms.Api.Management/Mapping/Server/ServerConfigurationMapDefinition.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Server/ServerConfigurationResponseModel.cs
Labels: project/bellissima
