Repository umbraco/Umbraco-CMS, pull requests merged in 2023-05, with the labels that each got.

#14186 v10: update @umbraco-ui/uui to 1.2.1
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
Labels: dependencies

#14179 Backoffice JS dependency updates
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.controller.js
Labels: category/front-end, dependencies, release/12.0.0, release/11.4.0

#14152 Fix: Form elements in thirdparty dashboard views get removed
  src/Umbraco.Web.UI.Client/src/views/common/dashboard.html
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Tabs/tabs.spec.ts
Labels: category/ui, type/bug, area/frontend, affected/v10, affected/v11

#14218 IAppCache implementations should not cache null values
  src/Umbraco.Core/Cache/DictionaryAppCache.cs
  src/Umbraco.Core/Cache/FastDictionaryAppCache.cs
  src/Umbraco.Core/Cache/IAppCache.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Cache/AppCacheTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Cache/FastDictionaryAppCacheTests.cs
Labels: category/breaking

#13692 Make it possible to keep focus on a parent Block
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/blockgridui.less
Labels: category/ui

#12577 V10: Fix "Save and close"/"Publish and close" for infinite editing of language variant content
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
Labels: community/pr, type/bug, release/12.1.0

#14109 Entity Framework Core Support
  src/Umbraco.Cms.Persistence.EFCore/Extensions/DbContextExtensions.cs
  src/Umbraco.Cms.Persistence.EFCore/Extensions/UmbracoEFCoreServiceCollectionExtensions.cs
  src/Umbraco.Cms.Persistence.EFCore/Locking/SqlServerEFCoreDistributedLockingMechanism.cs
  src/Umbraco.Cms.Persistence.EFCore/Locking/SqliteEFCoreDistributedLockingMechanism.cs
  src/Umbraco.Cms.Persistence.EFCore/Scoping/AmbientEFCoreScopeStack.cs
  src/Umbraco.Cms.Persistence.EFCore/Scoping/EFCoreDetachableScope.cs
  src/Umbraco.Cms.Persistence.EFCore/Scoping/EFCoreScope.cs
  src/Umbraco.Cms.Persistence.EFCore/Scoping/EFCoreScopeAccessor.cs
  src/Umbraco.Cms.Persistence.EFCore/Scoping/EFCoreScopeProvider.cs
  src/Umbraco.Cms.Persistence.EFCore/Scoping/IAmbientEfCoreScopeStack.cs
  src/Umbraco.Cms.Persistence.EFCore/Scoping/IEFCoreScope.cs
  src/Umbraco.Cms.Persistence.EFCore/Scoping/IEFCoreScopeAccessor.cs
  src/Umbraco.Cms.Persistence.EFCore/Scoping/IEFCoreScopeProvider.cs
  src/Umbraco.Cms.Persistence.EFCore/Umbraco.Cms.Persistence.EFCore.csproj
  src/Umbraco.Cms/Umbraco.Cms.csproj
  src/Umbraco.Core/CompatibilitySuppressions.xml
  src/Umbraco.Core/Scoping/CoreScope.cs
  src/Umbraco.Core/Scoping/ICoreScope.cs
  src/Umbraco.Core/Scoping/ILockingMechanism.cs
  src/Umbraco.Core/Scoping/LockingMechanism.cs
  src/Umbraco.Infrastructure/Scoping/IAmbientScopeContextStack.cs
  src/Umbraco.Infrastructure/Scoping/Scope.cs
  src/Umbraco.Infrastructure/Scoping/ScopeContext.cs
  src/Umbraco.Infrastructure/Scoping/ScopeProvider.cs
  tests/Umbraco.Tests.Integration/DependencyInjection/UmbracoBuilderExtensions.cs
  tests/Umbraco.Tests.Integration/Umbraco.Persistence.EFCore/DbContext/TestUmbracoDbContext.cs
  tests/Umbraco.Tests.Integration/Umbraco.Persistence.EFCore/DbContext/UmbracoLock.cs
  tests/Umbraco.Tests.Integration/Umbraco.Persistence.EFCore/Scoping/EFCoreLockTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Persistence.EFCore/Scoping/EFCoreScopeInfrastructureScopeLockTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Persistence.EFCore/Scoping/EFCoreScopeInfrastructureScopeTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Persistence.EFCore/Scoping/EFCoreScopeNotificationsTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Persistence.EFCore/Scoping/EFCoreScopeTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Persistence.EFCore/Scoping/EFCoreScopedFileSystemsTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  umbraco.sln
Labels: category/breaking, category/notable, type/feature, release/12.0.0

#14060 Add posibillty to use composition on memberstype
  src/Umbraco.Core/ConventionsHelper.cs
  src/Umbraco.Web.BackOffice/Controllers/MemberTypeController.cs
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js
  src/Umbraco.Web.UI.Client/src/common/resources/membertype.resource.js
  src/Umbraco.Web.UI.Client/src/views/memberTypes/views/design/design.html
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/MemberRepositoryTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/MemberTypeRepositoryTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/MemberServiceTests.cs
Labels: project/bellissima

#14258 Wrap RTE content in a dedicated model for future expansion
  src/Umbraco.Core/Models/DeliveryApi/RichTextModel.cs
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/RteMacroRenderingValueConverter.cs
Labels: release/12.0.0

#14173 Umbraco 8 - SQL Server 2022 NuCache Error Using JSON Serializer
  src/Umbraco.Core/Persistence/IUmbracoDatabase.cs
  src/Umbraco.Core/Persistence/NPocoDatabaseExtensions-Bulk.cs
  src/Umbraco.Core/Persistence/UmbracoDatabase.cs
  src/Umbraco.Tests/Testing/TestDatabase.cs
Labels: community/pr, type/bug, release/8.18.9

#14294 Ensure that blocks always open automatically when added to block list or block grid
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbBlockGridPropertyEditor.component.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
Labels: status/regression, area/frontend, affected/v10, affected/v11, affected/v12

#14295 Empty filter and sort values should not be considered when executing queries
  src/Umbraco.Cms.Api.Delivery/Services/ApiContentQueryService.cs
Labels: release/12.0.0

#14296 Fix the namespace for PagedModel
  src/Umbraco.Cms.Api.Delivery/Controllers/QueryContentApiController.cs
  src/Umbraco.Cms.Api.Delivery/Services/ApiContentQueryProvider.cs
  src/Umbraco.Cms.Api.Delivery/Services/ApiContentQueryService.cs
  src/Umbraco.Core/CompatibilitySuppressions.xml
  src/Umbraco.Core/DeliveryApi/IApiContentQueryProvider.cs
  src/Umbraco.Core/DeliveryApi/IApiContentQueryService.cs
  src/Umbraco.Core/DeliveryApi/NoopApiContentQueryService.cs
  src/Umbraco.Core/Models/PagedModel.cs
  src/Umbraco.Core/Services/ILocalizationService.cs
  src/Umbraco.Core/Services/ITrackedReferencesService.cs
  src/Umbraco.Core/Services/TrackedReferencesService.cs
Labels: category/breaking, release/12.0.0

#14289 Delivery API: Adding support for "Contains" filters
  src/Umbraco.Cms.Api.Delivery/Indexing/Filters/NameFilterIndexer.cs
  src/Umbraco.Cms.Api.Delivery/Indexing/Sorts/NameSortIndexer.cs
  src/Umbraco.Cms.Api.Delivery/Querying/Filters/NameFilter.cs
  src/Umbraco.Cms.Api.Delivery/Services/ApiContentQueryProvider.cs
  src/Umbraco.Infrastructure/Examine/DeliveryApiContentIndexFieldDefinitionBuilder.cs
Labels: release/12.0.0

#14269 Adding logging and make sure PostAddFile always releases the file semaphore
  src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
Labels: community/pr, category/dx, type/feature, release/12.1.0

#14321 Change "Media Picker" in RTE to "Image Picker"
  src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
Labels: community/pr, category/ui, category/ux, type/bug, release/12.1.0

#14308 Fix #14270 - ImageCropperValue.GetCropUrl(alias, imageUrlGenerator) always returns null
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/ImageCropperValue.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/ImageCropperTest.cs
Labels: community/pr, type/bug, release/12.1.0

#14315 Swapped the sortCreateDateAscending and sortCreateDateDescending translation values to match the intended behavior
  src/Umbraco.Core/EmbeddedResources/Lang/bs.xml
  src/Umbraco.Core/EmbeddedResources/Lang/cs.xml
  src/Umbraco.Core/EmbeddedResources/Lang/da.xml
  src/Umbraco.Core/EmbeddedResources/Lang/de.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Core/EmbeddedResources/Lang/fr.xml
  src/Umbraco.Core/EmbeddedResources/Lang/it.xml
  src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
  src/Umbraco.Core/EmbeddedResources/Lang/pt.xml
  src/Umbraco.Core/EmbeddedResources/Lang/sv.xml
  src/Umbraco.Core/EmbeddedResources/Lang/tr.xml
Labels: community/pr, type/feature

#14275 Convert collections for XPath in PropertyValueConverterBase
  src/Umbraco.Core/PropertyEditors/PropertyValueConverterBase.cs
Labels: community/pr, category/dx, type/bug, release/12.1.0

#14319 V14: umbraco-package.json schema
  .gitignore
  src/Umbraco.Cms.Targets/Umbraco.Cms.Targets.csproj
  src/Umbraco.Cms.Targets/buildTransitive/Umbraco.Cms.Targets.props
  src/Umbraco.Cms.Targets/buildTransitive/Umbraco.Cms.Targets.targets
  templates/Umbraco.Templates.csproj
  templates/UmbracoProject/.gitignore
Labels: project/bellissima
