Repository umbraco/Umbraco-CMS, pull requests merged in 2023-10, with the labels that each got.

#14880 Replaced `[MaybeNullWhen(false)]` with `[NotNullWhen(true)]` for `UdiParser.TryParse` method
  src/Umbraco.Core/UdiParser.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/CoreThings/UdiTests.cs
Labels: hacktoberfest/contrib-2023

#14895 Translate 'noItemsFound' to Dutch
  src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
Labels: community/pr, category/localization, type/feature, hacktoberfest-accepted, release/12.3.0, hacktoberfest/contrib-2023

#14928 Default value editors for all (meaningful) value types
  src/Umbraco.Core/Constants-PropertyEditors.cs
  src/Umbraco.Core/Models/PublishedContent/IPublishedPropertyType.cs
  src/Umbraco.Core/Models/PublishedContent/PublishedContentTypeFactory.cs
  src/Umbraco.Core/Models/PublishedContent/PublishedDataType.cs
  src/Umbraco.Core/Models/PublishedContent/PublishedPropertyType.cs
  src/Umbraco.Core/PropertyEditors/DefaultValueTypePropertyValueConverterAttribute.cs
  src/Umbraco.Core/PropertyEditors/PlainDateTimePropertyEditor.cs
  src/Umbraco.Core/PropertyEditors/PlainDecimalPropertyEditor.cs
  src/Umbraco.Core/PropertyEditors/PlainIntegerPropertyEditor.cs
  src/Umbraco.Core/PropertyEditors/PlainJsonPropertyEditor.cs
  src/Umbraco.Core/PropertyEditors/PlainStringPropertyEditor.cs
  src/Umbraco.Core/PropertyEditors/PlainTimePropertyEditor.cs
  src/Umbraco.Core/PropertyEditors/PropertyValueConverterCollection.cs
  src/Umbraco.Core/PropertyEditors/StringPropertyEditor.cs
  src/Umbraco.Core/PropertyEditors/StringValueConverter.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/BigintValueTypeConverter.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/DatePickerValueConverter.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/DateTimeValueTypeConverter.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/DecimalValueConverter.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/DecimalValueTypeConverter.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/IntegerValueTypeConverter.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/TextStringValueTypeConverter.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/TimeValueTypeConverter.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/ValueTypePropertyValueConverterBase.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/XmlValueTypeConverter.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Composing/TypeLoaderTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/PropertyEditorValueConverterTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/PropertyEditorValueTypeConverterTests.cs
Labels: project/bellissima

#13500 Allow to specify format and parsing format in dateHelper functions
  src/Umbraco.Web.UI.Client/src/common/services/util.service.js
Labels: category/dx

#14725 Update umbBlockGridPropertyEditor.component.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbBlockGridPropertyEditor.component.js
Labels: project/bellissima, release/12.3.0

#14881 Fixed URL tracking not working for invariant pages with culture variant ancestors
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/RedirectUrlRepository.cs
Labels: hacktoberfest/contrib-2023

#14942 Corrected mark-up
  src/Umbraco.Web.UI.Client/src/views/logViewer/search.html
Labels: hacktoberfest/contrib-2023

#14904 Add aria label to umbraco property
  src/Umbraco.Web.UI.Client/src/common/directives/components/property/umbproperty.directive.js
  src/Umbraco.Web.UI.Client/src/views/components/property/umb-property.html
Labels: hacktoberfest/contrib-2023

#14963 Refactored from ISystemClock to TimeProvider
  src/Umbraco.Web.BackOffice/Security/BackOfficeSecurityStampValidator.cs
  src/Umbraco.Web.BackOffice/Security/BackOfficeSessionIdValidator.cs
  src/Umbraco.Web.BackOffice/Security/ConfigureBackOfficeCookieOptions.cs
  src/Umbraco.Web.Common/Security/MemberSecurityStampValidator.cs
  tests/Umbraco.Tests.Integration/TestServerTest/TestAuthHandler.cs
Labels: project/bellissima

#14761 Add SetMemberSignInManager builder extension
  src/Umbraco.Web.Common/Extensions/UmbracoApplicationBuilder.Identity.cs
Labels: category/dx, release/12.3.0

#14799 a11y improvement for settingsdashboardintro
  src/Umbraco.Web.UI.Client/src/views/dashboard/settings/settingsdashboardintro.html
Labels: category/accessibility, release/12.3.0

#14905 Add IExceptionHandlerFeature check to dynamic route check
  src/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformer.cs
Labels: hacktoberfest/contrib-2023

#14816 Remove duplicate name attribute in 2FA login form
  src/Umbraco.Web.UI.Client/src/views/common/login-2fa.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/login-2fa.html
Labels: category/ui, release/12.3.0

#14892 Fix for fallback file upload
  src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
Labels: type/bug, area/backend, affected/v12, hacktoberfest/contrib-2023

#14978 Updated Welsh lang file
  src/Umbraco.Core/EmbeddedResources/Lang/cy.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
Labels: hacktoberfest/contrib-2023

#14987 Create matcher policy to pick the correct item endpoint
  src/Umbraco.Cms.Api.Delivery/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Cms.Api.Delivery/Routing/DeliveryApiItemsEndpointsMatcherPolicy.cs
Labels: type/bug, release/12.3.0

#14967 Add config to limit concurrent logins
  src/Umbraco.Core/Configuration/Models/SecuritySettings.cs
  src/Umbraco.Web.BackOffice/Security/BackOfficeSignInManager.cs
  src/Umbraco.Web.BackOffice/Security/ConfigureBackOfficeSecurityStampValidatorOptions.cs
  src/Umbraco.Web.Common/Security/ConfigureSecurityStampOptions.cs
  src/Umbraco.Web.Common/Security/MemberSignInManager.cs
  src/Umbraco.Web.Common/Security/UmbracoSignInManager.cs
  templates/UmbracoProject/appsettings.json
  tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Security/MemberSignInManagerTests.cs
Labels: type/feature, release/12.3.0

#14989 V13: Add config to limit concurrent logins
  src/Umbraco.Core/Configuration/Models/SecuritySettings.cs
  src/Umbraco.Web.BackOffice/Security/BackOfficeSignInManager.cs
  src/Umbraco.Web.BackOffice/Security/ConfigureBackOfficeSecurityStampValidatorOptions.cs
  src/Umbraco.Web.Common/Security/ConfigureSecurityStampOptions.cs
  src/Umbraco.Web.Common/Security/MemberSignInManager.cs
  src/Umbraco.Web.Common/Security/UmbracoSignInManager.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Security/MemberSignInManagerTests.cs
Labels: category/breaking, type/feature, release/13.0.0

#14994 V12: Update Backoffice dependencies: jQuery, TinyMCE, SignalR, Ace Editor, Umbraco UI Library
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
Labels: category/front-end, dependencies, javascript, release/12.3.0

#15003 Link Picker Title UI Quirk
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/linkpicker/linkpicker.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/linkpicker/linkpicker.html
Labels: community/pr, category/ux, type/bug, release/13.0.0, hacktoberfest/contrib-2023

#14991 14523: Return focus to trigger element when close event occurs
  src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js
Labels: community/pr, category/accessibility, release/13.0.0, type/improvement, hacktoberfest/contrib-2023

#14974 our umbraco link works as expected - playwright test.
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/HelpPanel/helpLinks.spec.ts
Labels: community/pr, category/acceptance-tests, release/13.0.0, type/improvement, hacktoberfest/contrib-2023

#14970 New login page playwright test - Ensure Show/hide password button works as expected.
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Login/login.spec.ts
Labels: community/pr, category/acceptance-tests, release/13.0.0, type/improvement, hacktoberfest/contrib-2023

#14896 Fix permissions for assign hostname
  src/Umbraco.Core/Services/UserServiceExtensions.cs
  src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
Labels: hacktoberfest/contrib-2023

#15014 Added word-wrap so block item doesn't extend over the whole line
  src/Umbraco.Web.UI.Client/src/views/components/blockcard/umb-block-card.less
Labels: hacktoberfest/contrib-2023

#14977 Grant all users access to the content recycle bin
  src/Umbraco.Web.BackOffice/Trees/ContentTreeControllerBase.cs
Labels: hacktoberfest/contrib-2023

#14950 Condition on the userState instead of the dates.
  src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
Labels: hacktoberfest/contrib-2023

#14919 Added aria-labelledby so no longer 'empty' on Toggle Group
  src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbtogglegroup.directive.js
  src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-toggle-group.html
Labels: hacktoberfest/contrib-2023

#15017 Bug fix for compistion on member and media give 404
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbgroupsbuilder.directive.js
Labels: hacktoberfest/contrib-2023

#15005 Turkish language support changes
  src/Umbraco.Core/EmbeddedResources/Lang/tr.xml
Labels: hacktoberfest/contrib-2023

#15028 Dont explicitly index nested property by default
  src/Umbraco.Core/Configuration/Models/IndexingSettings.cs
Labels: category/breaking, release/13.0.0

#15032 Bugfix: UI for preview bug related to single language & non variant content
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
  templates/Umbraco.Templates.csproj
Labels: type/bug, release/12.3.0

#15065 V12: Bump @umbraco-ui/uui from 1.4.0 to 1.5.0
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
Labels: dependencies, javascript, release/12.3.0

#15035 Dynamic Root (Alternative to XPath in MNTP)
  src/Umbraco.Cms.Persistence.Sqlite/Services/SqliteSyntaxProvider.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Collections.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Core/DynamicRoot/DynamicRootContext.cs
  src/Umbraco.Core/DynamicRoot/DynamicRootNodeQuery.cs
  src/Umbraco.Core/DynamicRoot/DynamicRootService.cs
  src/Umbraco.Core/DynamicRoot/IDynamicRootService.cs
  src/Umbraco.Core/DynamicRoot/Origin/ByKeyDynamicRootOriginFinder.cs
  src/Umbraco.Core/DynamicRoot/Origin/CurrentDynamicRootOriginFinder.cs
  src/Umbraco.Core/DynamicRoot/Origin/DynamicRootOriginCollectionBuilder.cs
  src/Umbraco.Core/DynamicRoot/Origin/DynamicRootOriginFinderCollection.cs
  src/Umbraco.Core/DynamicRoot/Origin/IDynamicRootOriginFinder.cs
  src/Umbraco.Core/DynamicRoot/Origin/ParentDynamicRootOriginFinder.cs
  src/Umbraco.Core/DynamicRoot/Origin/RootDynamicRootOriginFinder.cs
  src/Umbraco.Core/DynamicRoot/Origin/SiteDynamicRootOriginFinder.cs
  src/Umbraco.Core/DynamicRoot/QuerySteps/DynamicRootQueryStep.cs
  src/Umbraco.Core/DynamicRoot/QuerySteps/DynamicRootQueryStepCollection.cs
  src/Umbraco.Core/DynamicRoot/QuerySteps/DynamicRootQueryStepCollectionBuilder.cs
  src/Umbraco.Core/DynamicRoot/QuerySteps/FarthestAncestorOrSelfDynamicRootQueryStep.cs
  src/Umbraco.Core/DynamicRoot/QuerySteps/FarthestDescendantOrSelfDynamicRootQueryStep.cs
  src/Umbraco.Core/DynamicRoot/QuerySteps/IDynamicRootQueryStep.cs
  src/Umbraco.Core/DynamicRoot/QuerySteps/IDynamicRootRepository.cs
  src/Umbraco.Core/DynamicRoot/QuerySteps/NearestAncestorOrSelfDynamicRootQueryStep.cs
  src/Umbraco.Core/DynamicRoot/QuerySteps/NearestDescendantOrSelfDynamicRootQueryStep.cs
  src/Umbraco.Core/EmbeddedResources/Lang/da.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Core/Extensions/CollectionExtensions.cs
  src/Umbraco.Core/Extensions/EnumerableExtensions.cs
  src/Umbraco.Core/PropertyEditors/MultiNodePickerConfigurationTreeSource.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Repositories.cs
  src/Umbraco.Infrastructure/Logging/Serilog/LoggerConfigExtensions.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DynamicRootRepository.cs
  src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs
  src/Umbraco.Infrastructure/Persistence/SqlSyntax/SqlSyntaxProviderBase.cs
  src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
  src/Umbraco.Web.UI.Client/src/common/filters/nestedcontent.filter.js
  src/Umbraco.Web.UI.Client/src/common/resources/entity.resource.js
  src/Umbraco.Web.UI.Client/src/less/components/umb-node-preview.less
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/pickdynamicrootcustomstep/pickdynamicrootcustomstep.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/pickdynamicrootcustomstep/pickdynamicrootcustomstep.html
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/pickdynamicrootorigin/pickdynamicrootorigin.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/pickdynamicrootorigin/pickdynamicrootorigin.html
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/pickdynamicrootquerystep/pickdynamicrootquerystep.controller.js
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/pickdynamicrootquerystep/pickdynamicrootquerystep.html
  src/Umbraco.Web.UI.Client/src/views/prevalueeditors/treesource.controller.js
  src/Umbraco.Web.UI.Client/src/views/prevalueeditors/treesource.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DynamicRootServiceTests.cs
Labels: category/notable, type/feature, release/13.0.0

#14953 Update NestedContentPropertyEditor.cs - Update obsolete message
  src/Umbraco.Infrastructure/PropertyEditors/NestedContentPropertyEditor.cs
Labels: hacktoberfest/contrib-2023

#14814 Fix `JsonNetSerializer` settings leaking into derived implementations
  src/Umbraco.Infrastructure/Serialization/ConfigurationEditorJsonSerializer.cs
  src/Umbraco.Infrastructure/Serialization/JsonNetSerializer.cs
Labels: category/breaking, type/bug, affected/v9, affected/v10, affected/v11, affected/v12, release/13.0.0

#14990 Updates and support for re-use of CMS logic in Deploy
  src/Umbraco.Core/Deploy/IFileSource.cs
  src/Umbraco.Core/Routing/IRedirectTracker.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/Routing/RedirectTracker.cs
  src/Umbraco.Infrastructure/Routing/RedirectTrackingHandler.cs
Labels: category/breaking, release/13.0.0

#15075 V13/bugfix/login screen autofill
  src/Umbraco.Web.UI.Login/src/auth-styles.css
  src/Umbraco.Web.UI.Login/src/auth.element.ts
  src/Umbraco.Web.UI.Login/src/components/login-input.element.ts
  src/Umbraco.Web.UI.Login/src/components/pages/login.page.element.ts
  src/Umbraco.Web.UI.Login/src/index.ts
Labels: type/bug

#15066 Set max height of media item in grid
  src/Umbraco.Web.UI.Client/src/common/directives/components/umbmediagrid.directive.js
  src/Umbraco.Web.UI.Client/src/views/components/media/umbimagepreview/umb-image-preview.less
Labels: hacktoberfest-accepted, project/bellissima, hacktoberfest/contrib-2023
