Repository umbraco/Umbraco-CMS, pull requests merged in 2023-08, with the labels that each got.

#14618 Allow newlines in invite emails
  src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
Labels: type/bug, release/12.1.0, release/10.7.0

#14629 V12: Remove avatar step from login
  src/Umbraco.Core/EmbeddedResources/Lang/bs.xml
  src/Umbraco.Core/EmbeddedResources/Lang/cs.xml
  src/Umbraco.Core/EmbeddedResources/Lang/cy.xml
  src/Umbraco.Core/EmbeddedResources/Lang/da.xml
  src/Umbraco.Core/EmbeddedResources/Lang/de.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Core/EmbeddedResources/Lang/es.xml
  src/Umbraco.Core/EmbeddedResources/Lang/fr.xml
  src/Umbraco.Core/EmbeddedResources/Lang/hr.xml
  src/Umbraco.Core/EmbeddedResources/Lang/it.xml
  src/Umbraco.Core/EmbeddedResources/Lang/nl.xml
  src/Umbraco.Core/EmbeddedResources/Lang/ru.xml
  src/Umbraco.Core/EmbeddedResources/Lang/tr.xml
  src/Umbraco.Core/EmbeddedResources/Lang/ua.xml
  src/Umbraco.Web.UI.Client/src/common/directives/components/application/umblogin.directive.js
  src/Umbraco.Web.UI.Client/src/views/components/application/umb-login.html
Labels: type/bug

#14648 Add config so it is configurable whether to explicitly index each nested property
  src/JsonSchema/AppSettings.cs
  src/Umbraco.Core/Configuration/Models/IndexingSettings.cs
  src/Umbraco.Core/Constants-Configuration.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
  src/Umbraco.Core/PropertyEditors/JsonPropertyIndexValueFactoryBase.cs
  src/Umbraco.Core/PropertyEditors/TagPropertyIndexValueFactory.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyIndexValueFactory.cs
  src/Umbraco.Infrastructure/PropertyEditors/NestedContentPropertyIndexValueFactory.cs
  src/Umbraco.Infrastructure/PropertyEditors/NestedPropertyIndexValueFactoryBase.cs
Labels: type/feature, release/12.1.0, release/10.7.0, release/11.5.0

#14639 Fix userid zero in integration tests
  src/Umbraco.Core/Services/ContentVersionService.cs
  src/Umbraco.Core/Services/MediaServiceExtensions.cs
  tests/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTestWithContent.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Packaging/PackageDataInstallationTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/DocumentRepositoryTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/MediaRepositoryTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/RelationRepositoryTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServicePerformanceTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentTypeServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/EntityServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/LocalizationServiceTests.cs
Labels: community/pr, category/test-automation, type/feature, release/12.2.0

#14669 fix: Pass correct user id to Audit log
  src/Umbraco.Core/Services/ContentService.cs
Labels: community/pr, category/auditing, type/bug, release/12.2.0

#14688 fix: Translations keys from #12776
  src/Umbraco.Core/EmbeddedResources/Lang/da.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/compositions/compositions.html
Labels: community/pr, category/ui, type/bug, release/12.2.0

#14656 Move to Minimal Hosting Model in a backwards compatible way
  build/azure-pipelines.yml
  src/Umbraco.Infrastructure/Runtime/CoreRuntime.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Extensions/ApplicationBuilderExtensions.cs
  src/Umbraco.Web.Common/Extensions/WebApplicationBuilderExtensions.cs
  src/Umbraco.Web.Common/Extensions/WebApplicationExtensions.cs
  src/Umbraco.Web.Common/Hosting/HostBuilderExtensions.cs
  src/Umbraco.Web.UI/Program.cs
  src/Umbraco.Web.UI/Startup.cs
  src/Umbraco.Web.UI/Views/_ViewImports.cshtml
  templates/Umbraco.Templates.csproj
  tests/Umbraco.Tests.AcceptanceTest/misc/umbraco-linux.docker
Labels: category/notable, type/feature, release/13.0.0

#14702 V12: Get multiple items by ids endpoints
  src/Umbraco.Cms.Api.Delivery/Controllers/ByIdsContentApiController.cs
  src/Umbraco.Cms.Api.Delivery/Controllers/ByIdsMediaApiController.cs
Labels: type/feature

#14498 Add ReSharperTestRunner64 to the assembly exclusion list in TypeFinder
  src/Umbraco.Core/Composing/TypeFinder.cs
Labels: release/12.2.0

#14728 Fixed incorrect BlockListPropertyValueConverter delivery api property value type
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockListPropertyValueConverter.cs
Labels: community/pr, category/dx, type/bug, release/12.2.0

#14729 DeliveryApi: Ensure the ContentType property is serialized first
  src/Umbraco.Core/Models/DeliveryApi/ApiElement.cs
  src/Umbraco.Core/Models/DeliveryApi/IApiElement.cs
Labels: community/pr, category/dx, type/feature, release/12.2.0
