Repository umbraco/Umbraco-CMS, pull requests merged in 2024-09, with the labels that each got.

#16923 Templates can still be editable when using runtime mode Production bug fixed #16622
  src/Umbraco.Web.UI.Client/src/views/templates/edit.html
Labels: community/pr, category/dx, type/bug, release/14.3.0

#17006 Avoid concurrent build of `Umbraco.JsonSchema` tool and add execution timeouts to `Exec` build tasks
  src/Umbraco.Cms.StaticAssets/Umbraco.Cms.StaticAssets.csproj
  src/Umbraco.Cms.Targets/Umbraco.Cms.Targets.csproj
  umbraco.sln
Labels: type/improvement

#15051 No longer shows success message if content moving is cancelled
  src/Umbraco.Core/Services/ContentService.cs
  src/Umbraco.Core/Services/IContentService.cs
  src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
Labels: hacktoberfest-accepted, hacktoberfest/contrib-2023

#16990 Resolved more warnings, and marked more warning types as errors
  src/Umbraco.Cms.Api.Management/Controllers/Indexer/RebuildIndexerController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Security/BackOfficeController.cs
  src/Umbraco.Cms.Api.Management/Factories/MediaTypeEditingPresentationFactory.cs
  src/Umbraco.Cms.Persistence.EFCore/Locking/SqliteEFCoreDistributedLockingMechanism.cs
  src/Umbraco.Cms.Persistence.SqlServer/LocalDb.cs
  src/Umbraco.Core/Logging/DisposableTimer.cs
  src/Umbraco.Core/Models/Membership/UserGroup.cs
  src/Umbraco.Core/Persistence/Repositories/ITrackedReferencesRepository.cs
  src/Umbraco.Core/PropertyEditors/JsonPropertyIndexValueFactoryBase.cs
  src/Umbraco.Core/Routing/ContentFinderByUrlAndTemplate.cs
  src/Umbraco.Core/Routing/DefaultUrlProvider.cs
  src/Umbraco.Core/Services/ContentService.cs
  src/Umbraco.Core/Services/DataTypeService.cs
  src/Umbraco.Core/Services/IAuditService.cs
  src/Umbraco.Core/Services/IContentPublishingService.cs
  src/Umbraco.Core/Services/IRelationService.cs
  src/Umbraco.Core/Services/ITrackedReferencesService.cs
  src/Umbraco.Core/Services/ImportExport/ContentTypeImportService.cs
  src/Umbraco.Core/Services/LocalizationService.cs
  src/Umbraco.Core/Services/Querying/RecycleBin/RecycleBinQueryResultType.cs
  src/Umbraco.Core/Services/RedirectUrlService.cs
  src/Umbraco.Core/Services/UserService.cs
  src/Umbraco.Core/Services/WebProfilerService.cs
  src/Umbraco.Infrastructure/BackgroundJobs/IRecurringBackgroundJob.cs
  src/Umbraco.Infrastructure/BackgroundJobs/Jobs/HealthCheckNotifierJob.cs
  src/Umbraco.Infrastructure/BackgroundJobs/Jobs/LogScrubberJob.cs
  src/Umbraco.Infrastructure/BackgroundJobs/Jobs/ServerRegistration/InstructionProcessJob.cs
  src/Umbraco.Infrastructure/Install/FilePermissionHelper.cs
  src/Umbraco.Infrastructure/Logging/Viewer/LogViewerConfig.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPremigrationPlan.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/UserRepository.cs
  src/Umbraco.Infrastructure/PropertyEditors/ImageCropperPropertyEditor.cs
  src/Umbraco.Infrastructure/Security/BackOfficeClaimsPrincipalFactory.cs
  src/Umbraco.Infrastructure/Security/BackOfficeIdentityUser.cs
  src/Umbraco.Web.Common/ModelsBuilder/DependencyInjection/UmbracoBuilderDependencyInjectionExtensions.cs
  src/Umbraco.Web.Website/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Website/Routing/PublicAccessRequestHandler.cs
  src/Umbraco.Web.Website/Routing/UmbracoRouteValuesFactory.cs
  src/Umbraco.Web.Website/Umbraco.Web.Website.csproj
  src/Umbraco.Web.Website/ViewEngines/ProfilingViewEngine.cs
  tests/Umbraco.Tests.Benchmarks/EnumeratorBenchmarks.cs
  tests/Umbraco.Tests.Benchmarks/HashFromStreams.cs
  tests/Umbraco.Tests.Integration/Implementations/TestHelper.cs
  tests/Umbraco.Tests.Integration/TestServerTest/UmbracoTestServerTestBase.cs
  tests/Umbraco.Tests.Integration/Testing/TestWebProfilerRepository.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/ContentTypeRepositoryTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/LanguageServiceTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Components/ComponentTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/BackgroundJobs/Jobs/ServerRegistration/InstructionProcessJobTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/BackgroundJobs/Jobs/TempFileCleanupJobTests.cs
Labels: community/pr, category/dx

#17053 Updated to dotnet 9 RC.1 - and other nuget packages
  Directory.Packages.props
  global.json
  src/Umbraco.Cms.Api.Management/Mapping/PartialView/PartialViewViewModelsMapDefinition.cs
  src/Umbraco.Cms.Api.Management/Mapping/Script/ScriptViewModelsMapDefinition.cs
  src/Umbraco.Cms.Api.Management/Mapping/Stylesheet/StylesheetviewModelsMapDefinition.cs
  tests/Directory.Packages.props
  tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/PublishedContentQueryTests.cs
Labels: dependencies, release/15.0.0

#17062 Updated nuget packages
  Directory.Packages.props
  tests/Directory.Packages.props
Labels: dependencies, release/14.3.0

#16997 Updated the assembly names to avoid a debug-warning in the log
  src/Umbraco.Core/Constants-Composing.cs
Labels: type/bug, release/14.3.0

#17052 Allow client to send language values, that user cannot persist
  src/Umbraco.Cms.Api.Management/Controllers/Document/CreateDocumentControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/UpdateDocumentControllerBase.cs
  src/Umbraco.Core/Services/ContentEditingService.cs
Labels: release/14.3.0

#16536 Add `IAsyncComponent` to allow async initialize/terminate
  src/Umbraco.Core/Composing/AsyncComponentBase.cs
  src/Umbraco.Core/Composing/ComponentCollection.cs
  src/Umbraco.Core/Composing/ComponentCollectionBuilder.cs
  src/Umbraco.Core/Composing/ComponentComposer.cs
  src/Umbraco.Core/Composing/IAsyncComponent.cs
  src/Umbraco.Core/Composing/IComponent.cs
  src/Umbraco.Core/Composing/RuntimeAsyncComponentBase.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.CollectionBuilders.cs
  src/Umbraco.Core/Extensions/ObjectExtensions.cs
  src/Umbraco.Core/Notifications/UmbracoApplicationStartingNotification.cs
  src/Umbraco.Core/Notifications/UmbracoApplicationStoppingNotification.cs
  src/Umbraco.Infrastructure/Runtime/CoreRuntime.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Components/ComponentTests.cs
Labels: category/breaking, status/needs-docs

#17118 V15: Allows blocks in rich text editor to leave out the "Umbraco-Block" HTML comment
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/RichTextParsingRegexes.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/RichTextPropertyEditorHelperTests.cs
Labels: type/feature, release/15.0.0

#17126 Update ImageSharpMiddlewareOption for fixing invalid width and height
  src/Umbraco.Cms.Imaging.ImageSharp/ConfigureImageSharpMiddlewareOptions.cs
Labels: type/bug, release/13.6.0
