Repository umbraco/Umbraco-CMS, pull requests merged in 2024-08, with the labels that each got.

#16840 Remove favicon from dotnet templates
  templates/Umbraco.Templates.csproj
Labels: affected/v10, affected/v14, affected/v13

#16861 Updated NuGet Packages
  Directory.Packages.props
  src/Umbraco.Cms.Imaging.ImageSharp2/Umbraco.Cms.Imaging.ImageSharp2.csproj
  tests/Directory.Packages.props
  tools/Umbraco.JsonSchema/Umbraco.JsonSchema.csproj
Labels: dependencies, release/14.2.0

#16871 Updated to lastest nuget minor or patch versions
  Directory.Packages.props
Labels: dependencies, release/13.5.0

#16880 Do not allow save of invalid domains
  src/Umbraco.Cms.Api.Management/Controllers/Document/UpdateDomainsController.cs
  src/Umbraco.Core/Services/DomainService.cs
  src/Umbraco.Core/Services/OperationStatus/DomainOperationStatus.cs
  tests/Umbraco.Tests.Integration/Umbraco.Web.BackOffice/UrlAndDomains/DomainAndUrlsTests.cs
Labels: type/bug, release/14.2.0

#16903 V14: Don't duplicate audit loggin for media trashing
  src/Umbraco.Core/Services/MediaService.cs
  src/Umbraco.Infrastructure/Events/RelateOnTrashNotificationHandler.cs
Labels: type/bug

#16832 Fix for MemberDefaultLockoutTimeInMinutes lockout time
  src/Umbraco.Infrastructure/Security/IdentityMapDefinition.cs
Labels: community/pr, type/bug, release/13.5.0

#16921 Stripped username before login
  src/Umbraco.Web.Common/Security/UmbracoSignInManager.cs
Labels: community/pr, category/ux, release/14.3.0

#15908 Cache a dictionary of dictionaries
  src/Umbraco.Web.Common/UmbracoHelper.cs
Labels: community/pr, type/bug, affected/v14, affected/v13

#16912 Fix broken Tours migration for V15
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/MigrateTours.cs
Labels: type/bug

#16935 Update to latest nuget packages 2024-08-20
  Directory.Packages.props
  src/Umbraco.Cms.Api.Common/Umbraco.Cms.Api.Common.csproj
  src/Umbraco.Cms.Persistence.EFCore.SqlServer/Umbraco.Cms.Persistence.EFCore.SqlServer.csproj
  src/Umbraco.Cms.Persistence.SqlServer/Umbraco.Cms.Persistence.SqlServer.csproj
  src/Umbraco.Web.BackOffice/Controllers/AuthenticationController.cs
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  tests/Directory.Packages.props
Labels: dependencies, release/13.5.0

#15929 Update valid reasons to not have a template on a content node to include having umbracoRedirect
  src/Umbraco.Web.Website/Routing/UmbracoRouteValuesFactory.cs
Labels: community/pr, category/dx, release/14.3.0

#16815 Improve dotnet templates
  src/Umbraco.Infrastructure/Install/FilePermissionHelper.cs
  src/Umbraco.Web.UI/Program.cs
  templates/Umbraco.Templates.csproj
  templates/UmbracoDockerCompose/.env
  templates/UmbracoDockerCompose/.template.config/dotnetcli.host.json
  templates/UmbracoDockerCompose/.template.config/ide.host.json
  templates/UmbracoDockerCompose/.template.config/template.json
  templates/UmbracoDockerCompose/Database/Dockerfile
  templates/UmbracoDockerCompose/Database/healthcheck.sh
  templates/UmbracoDockerCompose/Database/setup.sql
  templates/UmbracoDockerCompose/Database/startup.sh
  templates/UmbracoDockerCompose/docker-compose.yml
  templates/UmbracoProject/.dockerignore
  templates/UmbracoProject/.template.config/dotnetcli.host.json
  templates/UmbracoProject/.template.config/ide.host.json
  templates/UmbracoProject/.template.config/starterkits.template.json
  templates/UmbracoProject/.template.config/template.json
  templates/UmbracoProject/Dockerfile
  templates/UmbracoProject/UmbracoProject.csproj
  templates/UmbracoProject/appsettings.Development.json
  templates/UmbracoProject/appsettings.json
Labels: category/notable, type/feature, release/14.3.0

#16962 Fix mandatory RTE validation
  src/Umbraco.Core/PropertyEditors/Validators/RequiredValidator.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/Validators/IRichTextRequiredValidator.cs
  src/Umbraco.Infrastructure/PropertyEditors/Validators/RichTextRequiredValidator.cs
Labels: type/bug, release/13.5.0

#16958 Remove warnings from Umbraco.Web.UI
  src/Umbraco.Web.UI/Program.cs
Labels: community/pr, category/dx, release/14.3.0

#16933 Support parentId in document/media item search endpoints
  src/Umbraco.Cms.Api.Management/Controllers/Document/Item/SearchDocumentItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Media/Item/SearchMediaItemController.cs
  src/Umbraco.Core/Services/IIndexedEntitySearchService.cs
  src/Umbraco.Examine.Lucene/BackOfficeExamineSearcher.cs
  src/Umbraco.Infrastructure/Services/Implement/IndexedEntitySearchService.cs
Labels: release/14.3.0

#16967 V14: Extensions of type `AppEntryPoint` are not being executed on the login screen
  src/Umbraco.Web.UI.Login/src/controllers/slim-backoffice-initializer.ts
Labels: type/bug, release/14.3.0

#15019 Treat warnings as errors for initial projects
  Directory.Build.props
  global.json
  src/Umbraco.Cms.Api.Common/Umbraco.Cms.Api.Common.csproj
  src/Umbraco.Cms.Api.Delivery/Umbraco.Cms.Api.Delivery.csproj
  src/Umbraco.Cms.Api.Management/Umbraco.Cms.Api.Management.csproj
  src/Umbraco.Cms.Imaging.ImageSharp/Umbraco.Cms.Imaging.ImageSharp.csproj
  src/Umbraco.Cms.Imaging.ImageSharp2/Umbraco.Cms.Imaging.ImageSharp2.csproj
  src/Umbraco.Cms.Persistence.EFCore.SqlServer/Umbraco.Cms.Persistence.EFCore.SqlServer.csproj
  src/Umbraco.Cms.Persistence.EFCore.Sqlite/Umbraco.Cms.Persistence.EFCore.Sqlite.csproj
  src/Umbraco.Cms.Persistence.EFCore/Umbraco.Cms.Persistence.EFCore.csproj
  src/Umbraco.Cms.Persistence.SqlServer/Umbraco.Cms.Persistence.SqlServer.csproj
  src/Umbraco.Cms.Persistence.Sqlite/Umbraco.Cms.Persistence.Sqlite.csproj
  src/Umbraco.Cms.StaticAssets/Umbraco.Cms.StaticAssets.csproj
  src/Umbraco.Cms.Targets/Umbraco.Cms.Targets.csproj
  src/Umbraco.Cms/Umbraco.Cms.csproj
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  src/Umbraco.Web.Website/Umbraco.Web.Website.csproj
  tests/Umbraco.TestData/Umbraco.TestData.csproj
  tests/Umbraco.Tests.Benchmarks/Umbraco.Tests.Benchmarks.csproj
  tests/Umbraco.Tests.Common/Umbraco.Tests.Common.csproj
  tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
  tools/Umbraco.JsonSchema/Umbraco.JsonSchema.csproj
Labels: community/pr, category/dx, hacktoberfest-accepted, affected/v14

#16977 V15 Bugfix: Temp remove tag helpers on login screen
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoLogin/Index.cshtml
Labels: type/bug
