Repository umbraco/Umbraco-CMS, pull requests merged in 2024-02, with the labels that each got.

#15370 V14: Don't add published culture infos if not published
  src/Umbraco.Core/Services/ContentService.cs
  src/Umbraco.Infrastructure/Persistence/Factories/ContentBaseFactory.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentRepository.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentPublishingServiceTests.Publish.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentPublishingServiceTests.Unpublish.cs
Labels: category/breaking

#15660 V14: Align item namespaces
  src/Umbraco.Cms.Api.Management/Controllers/DataType/Item/ByEditorUiAliasController.cs
  src/Umbraco.Cms.Api.Management/Controllers/DataType/Item/DatatypeItemControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/DataType/Item/ItemDatatypeItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/MemberType/Item/ItemMemberTypeItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/MemberType/Item/MemberTypeItemControllerBase.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/EntityBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/Mapping/Item/ItemTypeMapDefinition.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/Media/Item/MediaItemResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Media/Item/MediaTreeItemResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/MemberType/Item/MemberTypeItemResponseModel.cs
Labels: project/bellissima

#15661 Move document related operations to DocumentControllerBase
  src/Umbraco.Cms.Api.Management/Controllers/Content/ContentControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/DocumentControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/PublishDocumentController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/PublishDocumentWithDescendantsController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/UnpublishDocumentController.cs
  src/Umbraco.Core/Services/OperationStatus/ContentCreatingOperationStatus.cs
Labels: project/bellissima

#15668 Login assets should be built independently of the Backoffice
  src/Umbraco.Cms.StaticAssets/Umbraco.Cms.StaticAssets.csproj
Labels: type/feature

#15651 V14: Invalidate user tokens
  src/Umbraco.Cms.Api.Delivery/Handlers/RevokeMemberAuthenticationTokensNotificationHandler.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/BackOfficeAuthBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/Handlers/RevokeUserAuthenticationTokensNotificationHandler.cs
Labels: project/bellissima

#15690 Fix certificate health check so that it validates multiple times
  src/Umbraco.Core/HealthChecks/Checks/Security/HttpsCheck.cs
Labels: community/pr, type/bug, release/13.2.0

#14979 Bugfix: #14742 - Tabs not coded according to best practice
  src/Umbraco.Web.UI.Client/src/common/directives/components/tabs/umbtabsnav.directive.js
  src/Umbraco.Web.UI.Client/src/views/components/content/umb-tabbed-content.html
  src/Umbraco.Web.UI.Client/src/views/components/tabs/umb-tabs-nav.html
Labels: community/pr, category/accessibility, type/bug, hacktoberfest-accepted, hacktoberfest/contrib-2023, release/13.2.0

#15713 V13: Update Login UI to Lit 3 and update the UI Library to 1.7.1
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/user/user.html
  src/Umbraco.Web.UI.Login/index.html
  src/Umbraco.Web.UI.Login/package-lock.json
  src/Umbraco.Web.UI.Login/package.json
  src/Umbraco.Web.UI.Login/public/mockServiceWorker.js
  src/Umbraco.Web.UI.Login/src/auth.element.ts
  src/Umbraco.Web.UI.Login/src/components/external-login-provider.element.ts
  src/Umbraco.Web.UI.Login/src/components/pages/mfa.page.element.ts
  src/Umbraco.Web.UI.Login/src/external/custom-view.element.ts
  src/Umbraco.Web.UI.Login/src/external/icon.registry.ts
  src/Umbraco.Web.UI.Login/src/mocks/handlers/backoffice.handlers.ts
  src/Umbraco.Web.UI.Login/src/mocks/handlers/login.handlers.ts
  src/Umbraco.Web.UI.Login/src/mocks/index.ts
  src/Umbraco.Web.UI.Login/src/utils/load-custom-view.function.ts
Labels: dependencies, javascript

#15715 V13: The login screen does not display external login errors
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Default.cshtml
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoLogin/Index.cshtml
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
  src/Umbraco.Web.Common/Extensions/ViewDataExtensions.cs
Labels: status/regression, type/bug, affected/v13, release/13.2.0

#15696 V14: Document and media collection view endpoints
  src/Umbraco.Cms.Api.Management/Controllers/Content/ContentCollectionControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/Collection/ByKeyDocumentCollectionController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/Collection/DocumentCollectionControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/Media/Collection/ByKeyMediaCollectionController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Media/Collection/MediaCollectionControllerBase.cs
  src/Umbraco.Cms.Api.Management/Mapping/Content/ContentMapDefinition.cs
  src/Umbraco.Cms.Api.Management/Mapping/Document/DocumentMapDefinition.cs
  src/Umbraco.Cms.Api.Management/Mapping/DocumentType/DocumentTypeMapDefinition.cs
  src/Umbraco.Cms.Api.Management/Mapping/Media/MediaMapDefinition.cs
  src/Umbraco.Cms.Api.Management/Mapping/MediaType/MediaTypeMapDefinition.cs
  src/Umbraco.Cms.Api.Management/Mapping/Member/MemberMapDefinition.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/Content/ContentCollectionResponseModelBase.cs
  src/Umbraco.Cms.Api.Management/ViewModels/ContentType/ContentTypeCollectionReferenceResponseModelBase.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Document/Collection/DocumentCollectionResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/DocumentTypeCollectionReferenceResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Media/Collection/MediaCollectionResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/MediaType/MediaTypeCollectionReferenceResponseModel.cs
  src/Umbraco.Core/Constants-Web.cs
  src/Umbraco.Core/Models/ListViewPagedModel.cs
  src/Umbraco.Core/Services/AuthorizationStatus/ContentAuthorizationStatus.cs
  src/Umbraco.Core/Services/ContentPermissionService.cs
  src/Umbraco.Core/Services/IContentListViewService.cs
  src/Umbraco.Core/Services/IMediaListViewService.cs
  src/Umbraco.Core/Services/OperationStatus/ContentCollectionOperationStatus.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Services.cs
  src/Umbraco.Infrastructure/Services/ContentListViewServiceBase.cs
  src/Umbraco.Infrastructure/Services/Implement/ContentListViewService.cs
  src/Umbraco.Infrastructure/Services/Implement/MediaListViewService.cs
Labels: project/bellissima

#15710 V14: generate dynamic importmap
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Default.cshtml
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoInstall/Index.cshtml
  src/Umbraco.Core/Constants-SystemDirectories.cs
  src/Umbraco.Core/Constants-Web.cs
  src/Umbraco.Core/Manifest/IPackageManifestService.cs
  src/Umbraco.Core/Manifest/PackageManifest.cs
  src/Umbraco.Core/Manifest/PackageManifestImportmap.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/Manifest/AppPluginsPackageManifestReader.cs
  src/Umbraco.Infrastructure/Manifest/BackOfficePackageManifestReader.cs
  src/Umbraco.Infrastructure/Manifest/PackageManifestReader.cs
  src/Umbraco.Infrastructure/Manifest/PackageManifestService.cs
  src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.BackOffice/Extensions/HtmlHelperBackOfficeExtensions.cs
  src/Umbraco.Web.Common/Extensions/ApplicationBuilderExtensions.cs
  src/Umbraco.Web.Common/Hosting/IBackOfficePathGenerator.cs
  src/Umbraco.Web.Common/Hosting/IStaticFileHostGenerator.cs
  src/Umbraco.Web.Common/Hosting/UmbracoBackOfficePathGenerator.cs
  src/Umbraco.Web.Common/Hosting/UmbracoStaticFilePathGenerator.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Manifest/PackageManifestReaderTests.cs
Labels: project/bellissima

#15727 V14: Member collection view/filter endpoint
  src/Umbraco.Cms.Api.Management/Controllers/Member/FilterMemberController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/FilterUserController.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/BackOfficeAuthPolicyBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/Factories/IMemberPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/MemberPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
Labels: project/bellissima

#15731 Fix excessive datatype load times in propertyValueEditors and backoffice mapping
  Directory.Packages.props
  src/Umbraco.Core/Cache/DataTypeConfigurationCache.cs
  src/Umbraco.Core/Cache/DataTypeConfigurationCacheRefresher.cs
  src/Umbraco.Core/Cache/IDataTypeConfigurationCache.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Core/Models/Mapping/ContentPropertyDisplayMapper.cs
  src/Umbraco.Core/Models/Mapping/ContentPropertyMapDefinition.cs
  src/Umbraco.Core/Services/DataTypeService.cs
  src/Umbraco.Core/Umbraco.Core.csproj
  src/Umbraco.Infrastructure/PropertyEditors/BlockEditorPropertyValueEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockGridPropertyEditorBase.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockListPropertyEditorBase.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyValueEditorBase.cs
  src/Umbraco.Infrastructure/PropertyEditors/ImageCropperPropertyValueEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/MediaPicker3PropertyEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/NestedContentPropertyEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/DataValueEditorReuseTests.cs
Labels: release/13.2.0

#15732 V14: Align routes
  src/Umbraco.Cms.Api.Management/Controllers/Member/Filter/FilterMemberFilterController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Member/Filter/MemberFilterControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/TemporaryFile/TemporaryFileControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/Filter/FilterUserFilterController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/Filter/UserFilterControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/UserControllerBase.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Core/Constants-Web.cs
Labels: project/bellissima

#15571 Add custom Examine FileSystemDirectoryFactory using Umbraco SiteName
  src/Umbraco.Examine.Lucene/ConfigurationEnabledDirectoryFactory.cs
  src/Umbraco.Examine.Lucene/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Examine.Lucene/UmbracoTempEnvFileSystemDirectoryFactory.cs
Labels: community/pr, type/bug, release/13.2.0

#15737 Add CultureInfo.InvariantCulture argument to nodeId.ToString() in Che…
  src/Umbraco.Core/Security/ContentPermissions.cs
Labels: community/pr, category/localization, type/bug, release/13.2.0

#15728 V14: Migrate Newtonsoft to System.Text in value converters
  src/Umbraco.Core/Models/ContentEditing/ContentItemDisplay.cs
  src/Umbraco.Core/Models/ContentEditing/Language.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/ColorPickerValueConverter.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/FlexibleDropdownPropertyValueConverter.cs
  src/Umbraco.Core/Serialization/IJsonSerializer.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/ImageCropperValueConverter.cs
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/JsonValueConverter.cs
  src/Umbraco.Infrastructure/Serialization/ConfigurationEditorJsonSerializer.cs
  src/Umbraco.Infrastructure/Serialization/ContextualConfigurationEditorJsonSerializer.cs
  src/Umbraco.Infrastructure/Serialization/ContextualJsonSerializer.cs
  src/Umbraco.Infrastructure/Serialization/JsonNetSerializer.cs
  src/Umbraco.Infrastructure/Serialization/SystemTextConfigurationEditorJsonSerializer.cs
  src/Umbraco.Infrastructure/Serialization/SystemTextJsonSerializer.cs
  src/Umbraco.Web.Common/Filters/JsonDateTimeFormatAttribute.cs
  tests/Umbraco.TestData/UmbracoTestDataController.cs
  tests/Umbraco.Tests.Common/Builders/DataTypeBuilder.cs
  tests/Umbraco.Tests.Common/Published/PublishedContentXmlAdapter.cs
  tests/Umbraco.Tests.Common/TestHelperBase.cs
  tests/Umbraco.Tests.Common/TestHelpers/MockedValueEditors.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/TemplateRepositoryTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/UserRepositoryTest.cs
  tests/Umbraco.Tests.UnitTests/TestHelpers/PublishedSnapshotServiceTestBase.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ImageCropperValueConverterTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/MediaPickerWithCropsValueConverterTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/MultiUrlPickerValueConverterTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/OutputExpansionStrategyTestBase.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Manifest/LegacyManifestParserTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/VariationTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/BlockGridPropertyValueConverterTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/ConvertersTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/DataValueReferenceFactoryCollectionTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/MultiValuePropertyEditorTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/PropertyEditorValueConverterTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/PropertyEditorValueEditorTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/PropertyEditorValueTypeConverterTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/RichTextPropertyEditorHelperTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Published/ConvertersTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Published/PropertyCacheLevelTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Persistence/Querying/ExpressionTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/PublishedCache/PublishedMediaTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberPasswordHasherTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Serialization/JsonNetSerializerTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Services/PropertyValidationServiceTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Controllers/MemberControllerUnitTests.cs
Labels: category/breaking, project/bellissima

#15764 V13.2 RC: The user panel does not work
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Default.cshtml
Labels: status/regression, release/13.2.0

#15766 Finalized the data type config migration
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/MigrateDataTypeConfigurations.cs
Labels: project/bellissima

#15745 V14: Align cultures & segments casing
  src/Umbraco.Core/Models/ContentCultureInfosCollection.cs
  src/Umbraco.Core/Models/Property.cs
  src/Umbraco.Infrastructure/Examine/DeliveryApiContentIndexValueSetBuilder.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentServiceTests.cs
Labels: project/bellissima

#15771 Allow operation id selector to work for non-CMS API's
  src/Umbraco.Cms.Api.Common/OpenApi/OperationIdSelector.cs
  src/Umbraco.Cms.Api.Common/OpenApi/UmbracoOperationIdSettings.cs
Labels: project/bellissima

#15776 Added the possibility to select all the cultures at once in the save and save&publish dialogs
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Web.UI.Client/src/views/content/overlays/publish.controller.js
  src/Umbraco.Web.UI.Client/src/views/content/overlays/publish.html
  src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.controller.js
  src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.html
  src/Umbraco.Web.UI.Client/src/views/content/overlays/save.controller.js
  src/Umbraco.Web.UI.Client/src/views/content/overlays/save.html
  src/Umbraco.Web.UI.Client/src/views/content/overlays/sendtopublish.controller.js
  src/Umbraco.Web.UI.Client/src/views/content/overlays/sendtopublish.html
Labels: community/pr, project/bellissima

#15789 V14: Unpublish multiple cultures
  src/Umbraco.Cms.Api.Management/Controllers/Document/DocumentControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/UnpublishDocumentController.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/Document/UnpublishDocumentRequestModel.cs
  src/Umbraco.Core/Models/ContentRepositoryExtensions.cs
  src/Umbraco.Core/Services/ContentPublishingService.cs
  src/Umbraco.Core/Services/IContentPublishingService.cs
  src/Umbraco.Core/Services/IContentService.cs
  src/Umbraco.Core/Services/OperationStatus/ContentPublishingOperationStatus.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentPublishingServiceTests.Publish.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentPublishingServiceTests.Unpublish.cs
Labels: project/bellissima
