Repository umbraco/Umbraco-CMS, pull requests merged in 2024-01, with the labels that each got.

#15511 V14: User token revocation and session sign-out
  src/Umbraco.Cms.Api.Common/DependencyInjection/UmbracoBuilderAuthExtensions.cs
  src/Umbraco.Cms.Api.Management/Controllers/Security/BackOfficeController.cs
  src/Umbraco.Cms.Api.Management/Security/BackOfficeApplicationManager.cs
Labels: type/feature, project/bellissima

#15367 V13: Load TinyMCE premium plugins through tiny.cloud
  src/Umbraco.Core/Configuration/Models/RichTextEditorSettings.cs
  src/Umbraco.Core/Models/ContentEditing/RichTextEditorConfiguration.cs
  src/Umbraco.Web.BackOffice/PropertyEditors/RichTextPreValueController.cs
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.component.js
Labels: category/front-end, type/feature, release/13.1.0

#15534 v13: the color on icons for external login providers should match the text
  src/Umbraco.Web.UI.Login/src/components/external-login-provider.element.ts
Labels: category/front-end, type/bug, release/13.1.0

#12788 Pass cache level defined in value converters
  src/Umbraco.Web/PublishedCache/NuCache/PublishedContent.cs
Labels: community/pr, type/bug, release/8.18.13

#14912 Setting SavedDictionaryItem EventState to the one from SavingDictionaryItem
  src/Umbraco.Core/Services/Implement/LocalizationService.cs
Labels: type/bug, hacktoberfest-accepted, hacktoberfest/contrib-2023, release/8.18.13

#15513 Fixes #15512 to allow curly braces in anchors
  src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
Labels: community/pr, type/bug, release/13.1.0

#15541 Run the same cleanup with scaffolding content as when copying.
  src/Umbraco.Core/Notifications/ContentScaffoldedNotification.cs
  src/Umbraco.Core/Notifications/ScaffoldedNotification.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/PropertyEditors/ComplexPropertyEditorContentNotificationHandler.cs
  src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
Labels: release/10.8.4

#15558 V13: TinyMCE does not toggle plugin buttons
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
Labels: type/bug, release/13.1.0

#15563 V10: Pass in variation context to published cache
  src/Umbraco.Core/PublishedCache/PublishedCacheBase.cs
  src/Umbraco.PublishedCache.NuCache/ContentCache.cs
  src/Umbraco.PublishedCache.NuCache/MediaCache.cs
Labels: release/10.8.4, release/13.2.0

#15555 Migrated ReportSite, OpenIddictCleanup and TemporaryFileCleanup to background jobs
  src/Umbraco.Cms.Api.Common/DependencyInjection/UmbracoBuilderAuthExtensions.cs
  src/Umbraco.Infrastructure/BackgroundJobs/Jobs/OpenIddictCleanupJob.cs
  src/Umbraco.Infrastructure/BackgroundJobs/Jobs/ReportSiteJob.cs
  src/Umbraco.Infrastructure/BackgroundJobs/Jobs/TemporaryFileCleanupJob.cs
  src/Umbraco.Infrastructure/HostedServices/ContentVersionCleanup.cs
  src/Umbraco.Infrastructure/HostedServices/HealthCheckNotifier.cs
  src/Umbraco.Infrastructure/HostedServices/KeepAlive.cs
  src/Umbraco.Infrastructure/HostedServices/LogScrubber.cs
  src/Umbraco.Infrastructure/HostedServices/ReportSiteTask.cs
  src/Umbraco.Infrastructure/HostedServices/ScheduledPublishing.cs
  src/Umbraco.Infrastructure/HostedServices/ServerRegistration/InstructionProcessTask.cs
  src/Umbraco.Infrastructure/HostedServices/ServerRegistration/TouchServerTask.cs
  src/Umbraco.Infrastructure/HostedServices/TempFileCleanup.cs
  src/Umbraco.Infrastructure/HostedServices/TemporaryFileCleanup.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Scheduling/ContentVersionCleanupTest.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/BackgroundJobs/Jobs/ServerRegistration/TouchServerJobTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/HealthCheckNotifierTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/KeepAliveTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/LogScrubberTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/ScheduledPublishingTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/ServerRegistration/InstructionProcessTaskTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/ServerRegistration/TouchServerTaskTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HostedServices/TempFileCleanupTests.cs
Labels: project/bellissima

#15553 V14: Copy and move endpoints for content and media types
  src/Umbraco.Cms.Api.Management/Controllers/DataType/MoveDataTypeController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Dictionary/MoveDictionaryController.cs
  src/Umbraco.Cms.Api.Management/Controllers/DocumentType/CopyDocumentTypeController.cs
  src/Umbraco.Cms.Api.Management/Controllers/DocumentType/DocumentTypeControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/DocumentType/MoveDocumentTypeController.cs
  src/Umbraco.Cms.Api.Management/Controllers/MediaType/CopyMediaTypeController.cs
  src/Umbraco.Cms.Api.Management/Controllers/MediaType/MediaTypeControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/MediaType/MoveMediaTypeController.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/CopyDocumentTypeRequestModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/MoveDocumentTypeRequestModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/MediaType/CopyMediaTypeRequestModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/MediaType/MoveMediaTypeRequestModel.cs
  src/Umbraco.Core/Services/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
  src/Umbraco.Core/Services/IContentTypeServiceBase.cs
  src/Umbraco.Core/Services/OperationStatus/ContentTypeStructureOperationStatus.cs
Labels: project/bellissima

#15584 V14: Composition endpoints for Document and Media types
  src/Umbraco.Cms.Api.Management/Controllers/DocumentType/Composition/AvailableCompositionController.cs
  src/Umbraco.Cms.Api.Management/Controllers/DocumentType/Composition/ReferencesCompositionController.cs
  src/Umbraco.Cms.Api.Management/Controllers/MediaType/Composition/AvailableCompositionController.cs
  src/Umbraco.Cms.Api.Management/Controllers/MediaType/Composition/ReferencesCompositionController.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/DocumentTypeBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/MediaTypeBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/Factories/ContentTypeEditingPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/DocumentTypeEditingPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/IDocumentTypeEditingPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/IMediaTypeEditingPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/MediaTypeEditingPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Mapping/DocumentType/DocumentTypeCompositionMapDefinition.cs
  src/Umbraco.Cms.Api.Management/Mapping/MediaType/MediaTypeCompositionMapDefinition.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/ContentType/AvailableContentTypeCompositionResponseModelBase.cs
  src/Umbraco.Cms.Api.Management/ViewModels/ContentType/ContentTypeCompositionRequestModelBase.cs
  src/Umbraco.Cms.Api.Management/ViewModels/ContentType/ContentTypeCompositionResponseModelBase.cs
  src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/Composition/AvailableDocumentTypeCompositionResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/Composition/DocumentTypeCompositionRequestModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/Composition/DocumentTypeCompositionResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/MediaType/Composition/AvailableMediaTypeCompositionResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/MediaType/Composition/MediaTypeCompositionRequestModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/MediaType/Composition/MediaTypeCompositionResponseModel.cs
  src/Umbraco.Core/Models/ContentTypeEditing/MediaTypeCreateModel.cs
  src/Umbraco.Core/Services/ContentTypeEditing/ContentTypeEditingService.cs
  src/Umbraco.Core/Services/ContentTypeEditing/ContentTypeEditingServiceBase.cs
  src/Umbraco.Core/Services/ContentTypeEditing/IContentTypeEditingService.cs
  src/Umbraco.Core/Services/ContentTypeEditing/IMediaTypeEditingService.cs
  src/Umbraco.Core/Services/ContentTypeEditing/MediaTypeEditingService.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentTypeEditingServiceTests.Create.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentTypeEditingServiceTests.GetAvailableCompositions.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentTypeEditingServiceTests.Update.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentTypeEditingServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentTypeEditingServiceTestsBase.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/MediaTypeEditingServiceTests.Create.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/MediaTypeEditingServiceTests.GetAvailableCompositions.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/MediaTypeEditingServiceTests.Update.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/MediaTypeEditingServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
Labels: project/bellissima

#15586 v14: Merge NewBackOfficeSettings into SecuritySettings.
  src/Umbraco.Cms.Api.Management/DependencyInjection/BackOfficeCorsPolicyBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/Security/BackOfficeApplicationManager.cs
  src/Umbraco.Core/Configuration/Models/SecuritySettings.cs
  src/Umbraco.Core/Configuration/Models/Validation/SecuritySettingsValidator.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
  src/Umbraco.Core/Models/Configuration/NewBackOfficeSettings.cs
  src/Umbraco.Core/Models/Configuration/NewBackOfficeSettingsValidator.cs
  src/Umbraco.Core/Umbraco.Core.csproj
Labels: project/bellissima

#15595 V13: Rich text editor does not show its toolbar on grid layout rte's
  src/Umbraco.Web.UI.Client/src/common/directives/components/grid/grid.rte.directive.js
  src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/editors/rte.html
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.component.js
Labels: category/front-end, type/bug, release/13.2.0

#14908 Now properly checks the lockedoutdate
  src/Umbraco.Infrastructure/Security/IdentityMapDefinition.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Security/MemberManagerTests.cs
Labels: hacktoberfest-accepted, hacktoberfest/contrib-2023

#15615 V13 RC: Document types throw an error when inserting a block capable editor
  src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js
Labels: category/front-end, status/regression, type/bug

#15620 V14: Fix composition endpoints namespaces
  src/Umbraco.Cms.Api.Management/Controllers/DocumentType/AvailableCompositionDocumentTypeController.cs
  src/Umbraco.Cms.Api.Management/Controllers/DocumentType/CompositionReferenceDocumentTypeController.cs
  src/Umbraco.Cms.Api.Management/Controllers/MediaType/AvailableCompositionMediaTypeController.cs
  src/Umbraco.Cms.Api.Management/Controllers/MediaType/CompositionReferenceMediaTypeController.cs
  src/Umbraco.Cms.Api.Management/Factories/DocumentTypeEditingPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/IDocumentTypeEditingPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/IMediaTypeEditingPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/MediaTypeEditingPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Mapping/DocumentType/DocumentTypeCompositionMapDefinition.cs
  src/Umbraco.Cms.Api.Management/Mapping/MediaType/MediaTypeCompositionMapDefinition.cs
  src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/AvailableDocumentTypeCompositionResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/DocumentTypeCompositionRequestModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/DocumentTypeCompositionResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/MediaType/AvailableMediaTypeCompositionResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/MediaType/MediaTypeCompositionRequestModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/MediaType/MediaTypeCompositionResponseModel.cs
Labels: project/bellissima

#15607 2FA for users in management API
  src/Umbraco.Cms.Api.Management/Controllers/Security/BackOfficeController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/Current/CurrentUserControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/Current/DisableTwoFactorProviderCurrentUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/Current/EnableTwoFactorProviderCurrentUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/Current/GetTwoFactorSetupForProviderCurrentUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/Current/ListTwoFactorProvidersCurrentUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/DisableTwoFactorProviderUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/ListTwoFactorProvidersUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/UserControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/UserOrCurrentUserControllerBase.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/BackOfficeAuthBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/Security/Authorization/Content/ContentPermissionAuthorizer.cs
  src/Umbraco.Cms.Api.Management/Security/Authorization/Content/ContentPermissionHandler.cs
  src/Umbraco.Cms.Api.Management/Security/Authorization/Content/IContentPermissionAuthorizer.cs
  src/Umbraco.Cms.Api.Management/Security/Authorization/Feature/FeatureAuthorizeHandler.cs
  src/Umbraco.Cms.Api.Management/Security/Authorization/Feature/FeatureAuthorizer.cs
  src/Umbraco.Cms.Api.Management/Security/Authorization/Feature/IFeatureAuthorizer.cs
  src/Umbraco.Cms.Api.Management/Security/Authorization/Media/IMediaPermissionAuthorizer.cs
  src/Umbraco.Cms.Api.Management/Security/Authorization/Media/MediaPermissionAuthorizer.cs
  src/Umbraco.Cms.Api.Management/Security/Authorization/Media/MediaPermissionHandler.cs
  src/Umbraco.Cms.Api.Management/Security/Authorization/User/IUserPermissionAuthorizer.cs
  src/Umbraco.Cms.Api.Management/Security/Authorization/User/UserPermissionAuthorizer.cs
  src/Umbraco.Cms.Api.Management/Security/Authorization/User/UserPermissionHandler.cs
  src/Umbraco.Cms.Api.Management/Security/Authorization/UserGroup/IUserGroupPermissionAuthorizer.cs
  src/Umbraco.Cms.Api.Management/Security/Authorization/UserGroup/UserGroupPermissionAuthorizer.cs
  src/Umbraco.Cms.Api.Management/Security/Authorization/UserGroup/UserGroupPermissionHandler.cs
  src/Umbraco.Cms.Api.Management/ViewModels/User/Current/EnableTwoFactorRequestModel.cs
  src/Umbraco.Core/Constants-Security.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Core/Extensions/ClaimsIdentityExtensions.cs
  src/Umbraco.Core/Models/Verify2FACodeModel.cs
  src/Umbraco.Core/Security/BackOfficeAuthenticationTypeSettings.cs
  src/Umbraco.Core/Security/ClaimsPrincipalExtensions.cs
  src/Umbraco.Core/Security/ISetupTwoFactorModel.cs
  src/Umbraco.Core/Security/ITwoFactorProvider.cs
  src/Umbraco.Core/Security/NoopSetupTwoFactorModel.cs
  src/Umbraco.Core/Services/ITwoFactorLoginService.cs
  src/Umbraco.Core/Services/IUserTwoFactorLoginService.cs
  src/Umbraco.Core/Services/OperationStatus/TwoFactorOperationStatus.cs
  src/Umbraco.Core/Services/TwoFactorLoginService.cs
  src/Umbraco.Core/Services/TwoFactorLoginServiceBase.cs
  src/Umbraco.Core/Services/UserTwoFactorLoginService.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Services.cs
  src/Umbraco.Infrastructure/Security/BackOfficeClaimsPrincipalFactory.cs
  src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilder.BackOfficeIdentity.cs
  src/Umbraco.Web.BackOffice/Security/BackOfficeSignInManager.cs
  src/Umbraco.Web.BackOffice/Security/ConfigureBackOfficeCookieOptions.cs
  src/Umbraco.Web.UI/UseLegacyBackofficeSignInManagerComposer.cs
  tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/BackOfficeExamineSearcherTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/ExamineExternalIndexTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/BackOffice/BackOfficeClaimsPrincipalFactoryTests.cs
Labels: category/breaking, type/feature

#15609 V14: Migrate JsonConfigManipulator to System.Text.Json
  src/Umbraco.Cms.Api.Management/Controllers/RedirectUrlManagement/SetStatusRedirectUrlManagementController.cs
  src/Umbraco.Core/Configuration/IConfigManipulator.cs
  src/Umbraco.Core/Telemetry/SiteIdentifierService.cs
  src/Umbraco.Infrastructure/Configuration/JsonConfigManipulator.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/Migrations/Install/DatabaseBuilder.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Telemetry/SiteIdentifierServiceTests.cs
Labels: project/bellissima

#15603 V14/feature/more configuration endpoints
  src/Umbraco.Cms.Api.Management/Controllers/DataType/ConfigurationDataTypeController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/ConfigurationDocumentController.cs
  src/Umbraco.Cms.Api.Management/Controllers/DocumentType/ConfigurationDocumentTypeController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Media/ConfigurationMediaController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Package/ConfigurationPackageController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Package/Created/CreateCreatedPackageController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Template/ConfigurationTemplateController.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/PackageBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/Factories/IPackagePresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/PackageDefinitionFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/PackagePresentationFactory.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/DataType/DatatypeConfigurationResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentConfigurationResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/DocumentTypeConfigurationResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Media/MediaConfigurationResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Package/PackageConfigurationResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Template/TemplateConfigurationResponseModel.cs
Labels: project/bellissima

#15637 Create shadow file systems in configured LocalTempPath
  src/Umbraco.Core/IO/ShadowWrapper.cs
Labels: category/performance, type/feature

#12569 Fix bulk property variant data updates
  src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs
Labels: type/bug, release/8.18.13

#15638 Made some internal classes public
  src/Umbraco.Web/Editors/Binders/BlueprintItemBinder.cs
  src/Umbraco.Web/Editors/Binders/ContentItemBinder.cs
  src/Umbraco.Web/Editors/Filters/ContentSaveValidationAttribute.cs
  src/Umbraco.Web/WebApi/Filters/FileUploadCleanupFilterAttribute.cs
Labels: type/feature, release/8.18.13

#15650 V13: Obsolete migrations
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_0_0/AddMemberPropertiesAsColumns.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_2_0/AddHasAccessToAllLanguagesColumn.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_2_0/AddUserGroup2LanguageTable.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_3_0/AddBlockGridPartialViews.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_4_0/AddBlockGridPartialViews.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_5_0/AddPrimaryKeyConstrainToContentVersionCleanupDtos.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_7_0/MigrateTagsFromNVarcharToNText.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_11_3_0/AddDomainSortOrder.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_11_4_0/AlterKeyValueDataType.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_12_0_0/ResetCache.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_12_0_0/UseNvarcharInsteadOfNText.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_12_1_0/AddOpenIddict.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_12_1_0/TablesIndexesImprovement.cs
Labels: release/13.2.0

#15641 V14: Update DataTypeControllerBase to use GetAllAsync()
  src/Umbraco.Cms.Api.Management/Controllers/DataType/Tree/DataTypeTreeControllerBase.cs
  src/Umbraco.Core/Services/IDataTypeService.cs
Labels: project/bellissima

#15649 Do not dispose EF Core contexts manually
  src/Umbraco.Cms.Persistence.EFCore/UmbracoDbContext.cs
Labels: type/bug, release/13.1.1
