Repository umbraco/Umbraco-CMS, pull requests merged in 2024-05, with the labels that each got.

#16193 V14: Test new content and media list view service
  src/Umbraco.Cms.Api.Management/Controllers/Content/ContentCollectionControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/Content/ContentControllerBase.cs
  src/Umbraco.Core/Services/OperationStatus/ContentCollectionOperationStatus.cs
  src/Umbraco.Infrastructure/Services/Implement/ContentListViewService.cs
  src/Umbraco.Infrastructure/Services/Implement/MediaListViewService.cs
  tests/Umbraco.Tests.Common/Builders/DataEditorBuilder.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentListViewServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentListViewServiceTestsBase.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/MediaListViewServiceTests.cs
Labels: release/14.0.0-rc3

#16199 V14: Lock out users
  src/Umbraco.Cms.Api.Management/Controllers/Security/BackOfficeController.cs
Labels: type/bug, release/14.0.0-rc3

#16203 [V14] Allow specifying ID on the create package endpoint
  src/Umbraco.Cms.Api.Management/Factories/PackagePresentationFactory.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/Package/CreatePackageRequestModel.cs
Labels: release/14.0.0-rc3

#16194 V14: Unique OAuth callback route
  src/Umbraco.Core/Configuration/Models/SecuritySettings.cs
  src/Umbraco.Web.Common/Helpers/OAuthOptionsHelper.cs
Labels: release/14.0.0-rc3

#16200 Webhook log improvements
  src/Umbraco.Core/Models/WebhookLog.cs
  src/Umbraco.Core/Services/WebhookLogFactory.cs
  src/Umbraco.Infrastructure/Persistence/Factories/WebhookLogFactory.cs
  src/Umbraco.Web.BackOffice/Mapping/WebhookMapDefinition.cs
  src/Umbraco.Web.Common/Models/WebhookLogViewModel.cs
  src/Umbraco.Web.UI.Client/src/views/webhooks/logs.controller.js
  src/Umbraco.Web.UI.Client/src/views/webhooks/logs.html
  src/Umbraco.Web.UI.Client/src/views/webhooks/overlays/details.controller.js
  src/Umbraco.Web.UI.Client/src/views/webhooks/overlays/details.html
  src/Umbraco.Web.UI.Client/src/views/webhooks/overview.controller.js
Labels: release/13.4.0

#16182 V14: Fix sorting by "creator" on collection view
  src/Umbraco.Infrastructure/Services/ContentListViewServiceBase.cs
Labels: type/bug, release/14.0.0-rc3

#16196 Management api should use datetimeoffset
  src/Umbraco.Cms.Api.Management/Controllers/Document/GetAuditLogDocumentController.cs
  src/Umbraco.Cms.Api.Management/Controllers/LogViewer/AllLogViewerController.cs
  src/Umbraco.Cms.Api.Management/Controllers/LogViewer/AllMessageTemplateLogViewerController.cs
  src/Umbraco.Cms.Api.Management/Controllers/LogViewer/LogLevelCountLogViewerController.cs
  src/Umbraco.Cms.Api.Management/Controllers/LogViewer/ValidateLogFileSizeLogViewerController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Media/GetAuditLogMediaController.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Member/MemberResponseModel.cs
  src/Umbraco.Core/Services/AuditService.cs
  src/Umbraco.Core/Services/IAuditService.cs
  src/Umbraco.Core/Services/ILogViewerService.cs
  src/Umbraco.Core/Services/LogViewerService.cs
Labels: type/bug, release/14.0.0-rc3

#16228 V14: Return the unhealthy error message from Examine index
  src/Umbraco.Cms.Api.Management/Factories/IndexPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/Indexer/HealthStatusResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Indexer/IndexResponseModel.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Cms.Api.Management/Factories/IndexPresentationFactoryTests.cs
Labels: type/bug, release/14.0.0-rc4

#16258 Return 401 in case the signin was not successfully
  src/Umbraco.Cms.Api.Management/Controllers/Security/BackOfficeController.cs
Labels: release/14.0.0-rc4

#16263 V14: Reintroduce umbraco api controller as obsolete
  src/Umbraco.Cms.Api.Management/Routing/BackOfficeAreaRoutes.cs
  src/Umbraco.Core/UmbracoApiControllerTypeCollection.cs
  src/Umbraco.Web.Common/Attributes/UmbracoApiControllerAttribute.cs
  src/Umbraco.Web.Common/Controllers/UmbracoApiController.cs
  src/Umbraco.Web.Common/Controllers/UmbracoApiControllerBase.cs
  src/Umbraco.Web.Common/Controllers/UmbracoApiControllerTypeCollectionBuilder.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Web.Common/Extensions/LinkGeneratorExtensions.cs
  src/Umbraco.Web.Common/Extensions/TypeLoaderExtensions.cs
  src/Umbraco.Web.Common/Extensions/UrlHelperExtensions.cs
  src/Umbraco.Web.Common/Security/ConfigureMemberCookieOptions.cs
  src/Umbraco.Web.Website/Extensions/TypeLoaderExtensions.cs
  src/Umbraco.Web.Website/Routing/FrontEndRoutes.cs
  tests/Umbraco.Tests.Integration/TestServerTest/UmbracoTestServerTestBase.cs
  tests/Umbraco.Tests.Integration/Umbraco.Web.Website/Security/MemberAuthorizeTests.cs
  tests/Umbraco.Tests.UnitTests/AutoFixture/Customizations/UmbracoCustomizations.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Routing/BackOfficeAreaRoutesTests.cs
Labels: release/14.0.0-rc4

#16265 Do not expose culture we do not accept for languages
  src/Umbraco.Cms.Api.Management/Controllers/Culture/AllCultureController.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Core/Services/CultureService.cs
  src/Umbraco.Core/Services/ICultureService.cs
  src/Umbraco.Core/Services/IIsoCodeValidator.cs
  src/Umbraco.Core/Services/IsoCodeValidator.cs
Labels: release/14.0.0-rc4

#16214 Allow FileUpload and Imagecropper to upload files in the same way
  src/Umbraco.Infrastructure/PropertyEditors/FileUploadPropertyValueEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/ImageCropperPropertyValueEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/FileUploadValue.cs
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/ImageCropperValue.cs
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/TemporaryFileUploadValueBase.cs
Labels: release/14.0.0-rc4

#16244 V14: The login page does not respect certain error codes
  src/Umbraco.Cms.Api.Management/Security/TwoFactorLoginViewOptions.cs
  src/Umbraco.Web.UI.Login/src/components/pages/login.page.element.ts
  src/Umbraco.Web.UI.Login/src/components/pages/mfa.page.element.ts
  src/Umbraco.Web.UI.Login/src/contexts/auth.repository.ts
  src/Umbraco.Web.UI.Login/src/localization/lang/da-dk.ts
  src/Umbraco.Web.UI.Login/src/localization/lang/de-de.ts
  src/Umbraco.Web.UI.Login/src/localization/lang/en-us.ts
  src/Umbraco.Web.UI.Login/src/localization/lang/en.ts
  src/Umbraco.Web.UI.Login/src/localization/lang/nb-no.ts
  src/Umbraco.Web.UI.Login/src/localization/lang/nl-nl.ts
  src/Umbraco.Web.UI.Login/src/localization/lang/sv-se.ts
Labels: type/bug, release/14.0.0-rc4

#16281 V14: Add JsonDocumentOptions skipping comments in appsettings
  src/Umbraco.Infrastructure/Configuration/JsonConfigManipulator.cs
Labels: project/bellissima, release/14.0.0-rc4

#16285 V14: Fix redirect search
  src/Umbraco.Core/Services/IRedirectUrlService.cs
Labels: release/14.0.0-rc4

#16287 V14: Refactor user and usergroups with referency by id model
  src/Umbraco.Cms.Api.Management/Controllers/User/BulkDeleteUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/DisableUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/EnableUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/UnlockUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/User/UpdateUserGroupsUserController.cs
  src/Umbraco.Cms.Api.Management/Controllers/UserGroup/AddUsersToUserGroupController.cs
  src/Umbraco.Cms.Api.Management/Controllers/UserGroup/BulkDeleteUserGroupsController.cs
  src/Umbraco.Cms.Api.Management/Controllers/UserGroup/RemoveUsersFromUserGroupController.cs
  src/Umbraco.Cms.Api.Management/Factories/UserPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/User/Current/CurrentUserResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/User/DeleteUsersRequestModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/User/DisableUserRequestModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/User/EnableUserRequestModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/User/UnlockUsersRequestModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/User/UpdateUserGroupsOnUserRequestModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/User/UpdateUserRequestModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/User/UserPresentationBase.cs
  src/Umbraco.Cms.Api.Management/ViewModels/User/UserResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/UserGroup/DeleteUserGroupsRequestModel.cs
Labels: category/breaking

#16307 merge user/current/logins and user/current/login-providers
  src/Umbraco.Cms.Api.Management/Controllers/User/Current/GetLinkedLoginsCurrentUserController.cs
  src/Umbraco.Cms.Api.Management/Mapping/Users/UsersViewModelsMapDefinition.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/Services/BackOfficeExternalLoginService.cs
  src/Umbraco.Cms.Api.Management/ViewModels/User/Current/UserExternalLoginProviderResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/User/LinkedLoginViewModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/User/LinkedLoginsRequestModel.cs
  src/Umbraco.Core/Models/UserExternalLoginProviderModel.cs
Labels: category/breaking, release/14.0.0-rc4

#16100 [V14] import/export media/document type endpoints
  src/Umbraco.Cms.Api.Management/Controllers/DocumentType/DocumentTypeControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/DocumentType/ExportDocumentTypeController.cs
  src/Umbraco.Cms.Api.Management/Controllers/DocumentType/ImportExistingDocumentTypeController.cs
  src/Umbraco.Cms.Api.Management/Controllers/DocumentType/ImportNewDocumentTypeController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Import/AnalyzeImportController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Import/ImportControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/MediaType/ExportMediaTypeController.cs
  src/Umbraco.Cms.Api.Management/Controllers/MediaType/ImportExistingMediaTypeController.cs
  src/Umbraco.Cms.Api.Management/Controllers/MediaType/ImportNewMediaTypeController.cs
  src/Umbraco.Cms.Api.Management/Controllers/MediaType/MediaTypeControllerBase.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/ExportBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/ImportBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/Factories/IUdtFileContentFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/UdtFileContentFactory.cs
  src/Umbraco.Cms.Api.Management/Mapping/Import/EntityImportAnalysisViewModelsMapDefinition.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/Services/DictionaryItemImportService.cs
  src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/ImportDocumentTypeRequestModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Import/EntityImportAnalysisResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/MediaType/ImportMediaTypeRequestModel.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Core/Models/ImportExport/EntityXmlAnalysis.cs
  src/Umbraco.Core/Services/EntityXmlSerializer.cs
  src/Umbraco.Core/Services/IEntityXmlSerializer.cs
  src/Umbraco.Core/Services/IPackageDataInstallation.cs
  src/Umbraco.Core/Services/ImportExport/ContentTypeImportService.cs
  src/Umbraco.Core/Services/ImportExport/IContentTypeImportService.cs
  src/Umbraco.Core/Services/ImportExport/IMediaTypeImportService.cs
  src/Umbraco.Core/Services/ImportExport/ITemporaryFileToXmlImportService.cs
  src/Umbraco.Core/Services/ImportExport/MediaTypeImportService.cs
  src/Umbraco.Core/Services/ImportExport/TemporaryFileToXmlImportService.cs
  src/Umbraco.Core/Services/OperationStatus/ContentTypeImportOperationStatus.cs
  src/Umbraco.Core/Services/OperationStatus/MediaTypeImportOperationStatus.cs
  src/Umbraco.Core/Services/OperationStatus/TemporaryFileXmlImportOperationStatus.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Services.cs
  src/Umbraco.Infrastructure/Packaging/PackageDataInstallation.cs
  src/Umbraco.Infrastructure/Packaging/PackageInstallation.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Packaging/PackageDataInstallationTests.cs
Labels: project/bellissima

#16305 V14: Adds `preview.js`
  src/Umbraco.Cms.Api.Management/Routing/BackOfficeAreaRoutes.cs
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Index.cshtml
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoLogin/Index.cshtml
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/website/preview.js
  src/Umbraco.Core/Configuration/Models/ContentSettings.cs
  src/Umbraco.Web.Common/Views/UmbracoViewPage.cs
  src/Umbraco.Web.Website/Extensions/HtmlHelperRenderExtensions.cs
Labels: type/bug, release/14.0.0-rc4

#16344 V13: Fix routing with string parameter
  src/Umbraco.Web.Website/Routing/EagerMatcherPolicy.cs
Labels: type/bug, release/13.3.2

#16346 Update path for basic auth redirect
  src/Umbraco.Web.Website/Middleware/BasicAuthenticationMiddleware.cs
Labels: release/14.0.0-rc4

#16347 Ensure ufprt-token requests are handle in the UmbracoRouteValueTransformer
  src/Umbraco.Web.Website/Routing/EagerMatcherPolicy.cs
Labels: type/bug, release/13.3.2

#16349 Updated nuget packages
  Directory.Packages.props
  tests/Directory.Packages.props
Labels: release/14.0.0, release/14.0.0-rc5

#16350 V14: login should autofocus
  src/Umbraco.Web.UI.Login/src/auth.element.ts
Labels: type/feature, release/14.0.0-rc5

#16359 V14: Login updates
  src/Umbraco.Core/Configuration/Models/ContentSettings.cs
  src/Umbraco.Web.UI.Login/index.html
  src/Umbraco.Web.UI.Login/package-lock.json
  src/Umbraco.Web.UI.Login/package.json
  src/Umbraco.Web.UI.Login/public/login.jpg
  src/Umbraco.Web.UI.Login/public/mockServiceWorker.js
Labels: type/feature, release/14.0.0-rc5

#16284 V14: Fix user cache issue
  src/Umbraco.Core/Cache/DistributedCacheExtensions.cs
Labels: project/bellissima

#16393 Use runtime mode to determine cache TTL for manifest files
  src/Umbraco.Core/Configuration/Models/PackageManifestSettings.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
  src/Umbraco.Infrastructure/Manifest/PackageManifestService.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Manifest/PackageManifestServiceTests.cs
Labels: category/breaking, release/14.0.0-rc5

#16418 Make sure listviews are initialized correctly in a new DB
  src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs
Labels: release/14.0.0-rc5

#16417 Enrich the datatype references output with content type data
  src/Umbraco.Cms.Api.Management/Factories/DataTypeReferencePresentationFactory.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/DataType/DataTypeContentTypeReferenceModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/DataType/DataTypeReferenceResponseModel.cs
Labels: release/14.0.0-rc5

#16429 Fix issue when FileUpload exists on a document, it cannot publish
  src/Umbraco.Infrastructure/PropertyEditors/FileUploadPropertyValueEditor.cs
Labels: type/bug, release/14.1.0

#16430 Include umbraco-package.json manifests in telemetry data
  src/Umbraco.Cms.Api.Management/Mapping/Manifest/ManifestViewModelMapDefinition.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Manifest/ManifestResponseModel.cs
  src/Umbraco.Core/Manifest/PackageManifest.cs
  src/Umbraco.Core/Services/IPackagingService.cs
  src/Umbraco.Core/Telemetry/TelemetryService.cs
  src/Umbraco.Infrastructure/BackgroundJobs/Jobs/ReportSiteJob.cs
  src/Umbraco.Infrastructure/Services/Implement/PackagingService.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Telemetry/TelemetryServiceTests.cs
Labels: release/14.1.0

#16503 V14; Include description in doctype item
  src/Umbraco.Cms.Api.Management/Mapping/Item/ItemTypeMapDefinition.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/DocumentType/Item/DocumentTypeItemResponseModel.cs
Labels: release/14.1.0

#16419 v14: Validate file name to return correct error
  src/Umbraco.Core/Services/FileServiceOperationBase.cs
Labels: release/14.1.0

#16507 Added a Notification warnings when publishing variants without a domain
  src/Umbraco.Core/Events/AddDomainWarningsWhenPublishingNotificationHandler.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
Labels: type/feature, release/14.1.0

#16445 Handle master template not found as bad request
  src/Umbraco.Cms.Api.Management/Controllers/Template/TemplateControllerBase.cs
Labels: type/bug, release/14.1.0
