Repository umbraco/Umbraco-CMS, pull requests merged in 2024-10, with the labels that each got.

#17164 V15: Swap default Richtext Editor data-type from TinyMCE to Tiptap
  src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs
Labels: type/feature, release/15.0.0

#17181 V15: Fix previews
  src/Umbraco.Core/PublishedCache/IPublishedContentCache.cs
  src/Umbraco.Core/Services/IPreviewService.cs
  src/Umbraco.Core/Services/PreviewService.cs
  src/Umbraco.PublishedCache.HybridCache/DocumentCache.cs
  src/Umbraco.PublishedCache.HybridCache/Services/DocumentCacheService.cs
  src/Umbraco.PublishedCache.HybridCache/Services/IDocumentCacheService.cs
  tests/Umbraco.Tests.Integration/Umbraco.PublishedCache.HybridCache/DocumentHybridCacheMockTests.cs
Labels: category/breaking, release/15.0.0-rc2

#17186 V15: Only create route table if table does not exist
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/AddDocumentUrl.cs
Labels: type/bug, release/15.0.0-rc2

#17180 V15: Refresh IPublishedContentTypeFactory when data types change
  src/Umbraco.Core/Cache/Refreshers/Implement/ContentTypeCacheRefresher.cs
  src/Umbraco.Core/Cache/Refreshers/Implement/DataTypeCacheRefresher.cs
  tests/Umbraco.Tests.Common/TestHelpers/ContentTypeUpdateHelper.cs
  tests/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTestWithContentEditing.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Cache/PublishedContentTypeCacheTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/PublishedContent/PublishContentTypeFactoryTest.cs
Labels: type/bug, release/15.0.0-rc2

#17201 Reintroduced a lot of extension methods as obsolete to avoid breaking change
  src/Umbraco.Core/Extensions/PublishedContentExtensions.cs
  src/Umbraco.Web.Common/Extensions/FriendlyPublishedContentExtensions.cs
Labels: release/15.0.0-rc2

#17208 Introduce methods on new service to have alternative to obsoleted methods
  src/Umbraco.Core/Services/EntityTypeContainerService.cs
  src/Umbraco.Core/Services/IEntityTypeContainerService.cs
Labels: release/15.0.0-rc2

#17228 Hotfix: update login photo
  src/Umbraco.Web.UI.Login/public/login.jpg
Labels: type/feature, release/15.0.0

#17227 Fixed issue #17225. Extended RTE valid element configuration
  src/Umbraco.Core/Configuration/Models/RichTextEditorSettings.cs
Labels: type/bug

#17235 Updated to .NET9 RC2 + other nuget packageds
  Directory.Packages.props
  global.json
  src/Umbraco.Cms.Api.Common/DependencyInjection/UmbracoBuilderAuthExtensions.cs
  src/Umbraco.Cms.Api.Delivery/Security/MemberApplicationManager.cs
  src/Umbraco.Cms.Api.Management/Security/BackOfficeApplicationManager.cs
  src/Umbraco.Cms.Persistence.EFCore.SqlServer/Umbraco.Cms.Persistence.EFCore.SqlServer.csproj
  src/Umbraco.Cms.Persistence.EFCore/Umbraco.Cms.Persistence.EFCore.csproj
  src/Umbraco.Cms.Persistence.SqlServer/Umbraco.Cms.Persistence.SqlServer.csproj
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoLogin/Index.cshtml
  src/Umbraco.PublishedCache.HybridCache/DependencyInjection/UmbracoBuilderExtensions.cs
  tests/Directory.Packages.props
Labels: dependencies, release/15.0.0-rc2

#17223 Fixed last remains of `GetAll` vs `GetMany`
  src/Umbraco.Cms.Api.Management/Controllers/DocumentType/Item/ItemDocumentTypeItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/DocumentType/Item/SearchDocumentTypeItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/DocumentType/Tree/DocumentTypeTreeControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/MediaType/Item/ItemMediaTypeItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/MediaType/Item/SearchMediaTypeItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/MediaType/Tree/MediaTypeTreeControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/MemberType/Item/ItemMemberTypeItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/MemberType/Item/SearchMemberTypeItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/MemberType/Tree/MemberTypeTreeControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/Template/Query/ExecuteTemplateQueryController.cs
  src/Umbraco.Cms.Api.Management/Factories/DataTypeReferencePresentationFactory.cs
  src/Umbraco.Core/Handlers/WarnDocumentTypeElementSwitchNotificationHandler.cs
  src/Umbraco.Core/Services/ContentTypeEditing/ElementSwitchValidator.cs
  src/Umbraco.Core/Services/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
  src/Umbraco.Core/Services/IContentTypeServiceBase.cs
  src/Umbraco.Infrastructure/Cache/PropertyEditors/BlockEditorElementTypeCache.cs
  src/Umbraco.Infrastructure/Cache/PropertyEditors/IBlockEditorElementTypeCache.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockEditorValidatorBase.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockEditorValues.cs
  src/Umbraco.Infrastructure/Search/IndexingNotificationHandler.ContentType.cs
Labels: category/breaking, release/15.0.0, release/15.0.0-rc2

#17246 Fix ContentStore locking exceptions in async code
  src/Umbraco.Core/MonitorLock.cs
  src/Umbraco.PublishedCache.NuCache/ContentStore.cs
  src/Umbraco.PublishedCache.NuCache/SnapDictionary.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PublishedCache/ContentCacheTests.cs
Labels: type/bug, affected/v13

#17260 fix(#17220): added a sort to the mapping so the UI reflects the database
  src/Umbraco.Cms.Api.Management/Mapping/DocumentType/DocumentTypeMapDefinition.cs
Labels: community/pr, type/bug, hacktoberfest/contrib-2024, release/15.1.0

#17277 Bugfix: Use published template on load from database
  src/Umbraco.PublishedCache.HybridCache/Persistence/DatabaseCacheRepository.cs
Labels: release/15.0.0-rc2

#17280 V15: Implement sorting for the in-memory navigation structures (document and media)
  src/Umbraco.Core/Cache/Refreshers/Implement/ContentCacheRefresher.cs
  src/Umbraco.Core/Cache/Refreshers/Implement/MediaCacheRefresher.cs
  src/Umbraco.Core/Models/INavigationModel.cs
  src/Umbraco.Core/Models/Navigation/NavigationNode.cs
  src/Umbraco.Core/Services/Navigation/ContentNavigationServiceBase.cs
  src/Umbraco.Core/Services/Navigation/INavigationManagementService.cs
  src/Umbraco.Core/Services/Navigation/INavigationQueryService.cs
  src/Umbraco.Infrastructure/Persistence/Dtos/NavigationDto.cs
  src/Umbraco.Infrastructure/Persistence/Dtos/NodeDto.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentNavigationServiceTests.Copy.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentNavigationServiceTests.Create.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentNavigationServiceTests.Delete.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentNavigationServiceTests.Move.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentNavigationServiceTests.MoveToRecycleBin.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentNavigationServiceTests.Restore.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentNavigationServiceTests.Sort.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/MediaNavigationServiceTests.Create.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/MediaNavigationServiceTests.Delete.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/MediaNavigationServiceTests.Move.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/MediaNavigationServiceTests.MoveToRecycleBin.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/MediaNavigationServiceTests.Restore.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/MediaNavigationServiceTests.Sort.cs
  tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Services/ContentNavigationServiceBaseTests.cs
Labels: type/feature, release/15.0.0, release/15.0.0-rc2

#17287 Added an explicit dependency to Microsoft.Extensions.Caching.Memory
  Directory.Packages.props
  src/Umbraco.Cms.Api.Common/Umbraco.Cms.Api.Common.csproj
  src/Umbraco.Cms.Persistence.EFCore/Umbraco.Cms.Persistence.EFCore.csproj
Labels: dependencies, release/13.5.2

#17290 Updated image sharp to a non vulnerable version
  src/Directory.Packages.props
Labels: dependencies, release/10.8.7

#17285 Fix for #17187, unlock form after unsuccessful save and publish
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
Labels: release/13.5.2

#17288 V15: Rich Text Editor links do not work with query strings and anchors
  src/Umbraco.Core/Templates/HtmlLocalLinkParser.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Templates/HtmlLocalLinkParserTests.cs
Labels: type/bug, release/15.0.0, release/15.0.0-rc2

#17239 Block level variants - search indexing
  src/Umbraco.Core/PropertyEditors/DefaultPropertyIndexValueFactory.cs
  src/Umbraco.Core/PropertyEditors/IPropertyIndexValueFactory.cs
  src/Umbraco.Core/PropertyEditors/IndexValue.cs
  src/Umbraco.Core/PropertyEditors/JsonPropertyIndexValueFactoryBase.cs
  src/Umbraco.Core/PropertyEditors/NoopPropertyIndexValueFactory.cs
  src/Umbraco.Core/PropertyEditors/TagPropertyIndexValueFactory.cs
  src/Umbraco.Infrastructure/Examine/BaseValueSetBuilder.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyIndexValueFactory.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyIndexValueFactoryBase.cs
  src/Umbraco.Infrastructure/PropertyEditors/NestedPropertyIndexValueFactoryBase.cs
  src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyIndexValueFactory.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/BlockListElementLevelVariationTests.Indexing.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/PropertyIndexValueFactoryTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/RichTextElementLevelVariationTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
Labels: category/breaking

#17291 Do not rely on NuCache to do key/id lookups
  build/azure-pipelines.yml
  src/Umbraco.PublishedCache.NuCache/DependencyInjection/UmbracoBuilderExtensions.cs
Labels: release/14.3.1

#17327 Chore: Adds condition to `<TreatWarningsAsErrors>` for not in Debug mode
  Directory.Build.props
Labels: internal

#17379 V15: Adding not null when annotation
  src/Umbraco.Core/Services/Navigation/ContentNavigationServiceBase.cs
  src/Umbraco.Core/Services/Navigation/INavigationQueryService.cs
Labels: internal

#17366 Initialize important services before unattended installs
  build/azure-pipelines.yml
  src/Umbraco.Cms.Persistence.EFCore/Scoping/AmbientEFCoreScopeStack.cs
  src/Umbraco.Core/Constants-Composing.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Core/Notifications/PostRuntimePremigrationsUpgradeNotification.cs
  src/Umbraco.Core/Services/DocumentUrlServiceInitializer.cs
  src/Umbraco.Core/Services/DocumentUrlServiceInitializerNotificationHandler.cs
  src/Umbraco.Core/Services/Navigation/NavigationInitializationNotificationHandler.cs
  src/Umbraco.Core/Services/PublishStatus/PublishStatusInitializationNotificationHandler.cs
  src/Umbraco.Infrastructure/Install/PremigrationUpgrader.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPremigrationPlan.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/ConvertBlockEditorPropertiesBase.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/ConvertBlockGridEditorProperties.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/ConvertBlockListEditorProperties.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/ConvertRichTextEditorProperties.cs
  src/Umbraco.Infrastructure/Runtime/CoreRuntime.cs
  src/Umbraco.Infrastructure/Scoping/AmbientScopeContextStack.cs
  src/Umbraco.Infrastructure/Scoping/AmbientScopeStack.cs
  src/Umbraco.Infrastructure/Scoping/Scope.cs
  src/Umbraco.Infrastructure/Scoping/ScopeProvider.cs
  src/Umbraco.PublishedCache.HybridCache/NotificationHandlers/SeedingNotificationHandler.cs
  src/Umbraco.PublishedCache.HybridCache/Services/DocumentCacheService.cs
  src/Umbraco.PublishedCache.HybridCache/Services/MediaCacheService.cs
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
  tests/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
  tests/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTestWithContent.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentUrlServiceTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentUrlServiceTest_hidetoplevel_false.cs
  tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/BackOfficeExamineSearcherTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/ExamineBaseTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/ExamineExternalIndexTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/IndexTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/SearchTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/MigrationTests.cs
Labels: type/bug, release/15.0.0-rc3

#17380 Added DisableBuildCompression to not make compressed versions of back…
  src/Umbraco.Cms.StaticAssets/Umbraco.Cms.StaticAssets.csproj
  src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
  templates/UmbracoProject/UmbracoProject.csproj
Labels: release/15.0.0-rc3

#17371 Fixes slow legacy routes by using a domain cache
  src/Umbraco.Cms.Api.Delivery/Controllers/Content/ByIdContentApiController.cs
  src/Umbraco.Cms.Api.Delivery/Controllers/Content/ByIdsContentApiController.cs
  src/Umbraco.Core/DeliveryApi/ApiPublishedContentCache.cs
  src/Umbraco.Core/DeliveryApi/IApiPublishedContentCache.cs
  src/Umbraco.Core/Services/DocumentUrlService.cs
Labels: type/bug, release/15.0.0-rc3

#17370 Updated nuget packages 2024-10-25
  Directory.Packages.props
  src/Umbraco.Core/Extensions/ObjectExtensions.cs
Labels: dependencies, release/15.0.0-rc3

#17331 Fix #16659 - Unwanted node modules copying
  src/Umbraco.Cms.Targets/buildTransitive/Umbraco.Cms.Targets.targets
Labels: type/bug, release/15.1.0

#17355 Validation for block level variation
  src/Umbraco.Cms.Api.Management/Controllers/Content/ContentControllerBase.cs
  src/Umbraco.Core/Models/IDataValueEditor.cs
  src/Umbraco.Core/Models/Validation/PropertyValidationContext.cs
  src/Umbraco.Core/PropertyEditors/ConfigurationEditor.cs
  src/Umbraco.Core/PropertyEditors/DataValueEditor.cs
  src/Umbraco.Core/PropertyEditors/IValueValidator.cs
  src/Umbraco.Core/PropertyEditors/Validation/JsonPathExpression.cs
  src/Umbraco.Core/PropertyEditors/Validators/DateTimeValidator.cs
  src/Umbraco.Core/PropertyEditors/Validators/DecimalValidator.cs
  src/Umbraco.Core/PropertyEditors/Validators/EmailValidator.cs
  src/Umbraco.Core/PropertyEditors/Validators/IntegerValidator.cs
  src/Umbraco.Core/PropertyEditors/Validators/RegexValidator.cs
  src/Umbraco.Core/PropertyEditors/Validators/RequiredValidator.cs
  src/Umbraco.Core/Services/ContentPublishingService.cs
  src/Umbraco.Core/Services/ContentValidationServiceBase.cs
  src/Umbraco.Core/Services/IPropertyValidationService.cs
  src/Umbraco.Core/Services/PropertyValidationService.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockEditorMinMaxValidatorBase.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockEditorValidator.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockEditorValidatorBase.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockGridPropertyEditorBase.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockListPropertyEditorBase.cs
  src/Umbraco.Infrastructure/PropertyEditors/ColorPickerConfigurationEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/ComplexEditorValidator.cs
  src/Umbraco.Infrastructure/PropertyEditors/RichTextEditorBlockValidator.cs
  src/Umbraco.Infrastructure/PropertyEditors/TemporaryFileUploadValidator.cs
  src/Umbraco.Infrastructure/PropertyEditors/ValueListUniqueValueValidator.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/BlockListElementLevelVariationTests.Publishing.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/BlockListElementLevelVariationTests.Validation.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/BlockListElementLevelVariationTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentValidationServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/ColorListValidatorTest.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/EnsureUniqueValuesValidatorTest.cs
Labels: category/breaking
