Repository umbraco/Umbraco-CMS, pull requests merged in 2024-12, with the labels that each got.

#17661 Fix copy document with descendants onto self
  src/Umbraco.Core/Services/ContentService.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Copy.cs
Labels: release/14.4.0, release/15.2.0

#17692 Hotfix: unnecessary Discard Changes dialog for RTEs
  src/Umbraco.Web.UI.Client/src/packages/rte/components/rte-base.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiny-mce/property-editors/tiny-mce/property-editor-ui-tiny-mce.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/property-editor-ui-tiptap.element.ts
Labels: type/bug, release/15.1.0

#16058 Refactor settings arrays to `ISet<T>` (to ensure unique values and make them easily mutable)
  Directory.Build.props
  src/Umbraco.Cms.Api.Delivery/Handlers/InitializeMemberApplicationNotificationHandler.cs
  src/Umbraco.Cms.Api.Management/Controllers/Help/GetHelpController.cs
  src/Umbraco.Cms.Api.Management/Factories/TemporaryFileConfigurationPresentationFactory.cs
  src/Umbraco.Core/Configuration/ContentSettingsExtensions.cs
  src/Umbraco.Core/Configuration/Models/BasicAuthSettings.cs
  src/Umbraco.Core/Configuration/Models/ContentDashboardSettings.cs
  src/Umbraco.Core/Configuration/Models/ContentImagingSettings.cs
  src/Umbraco.Core/Configuration/Models/ContentSettings.cs
  src/Umbraco.Core/Configuration/Models/DeliveryApiSettings.cs
  src/Umbraco.Core/Configuration/Models/HealthChecksNotificationSettings.cs
  src/Umbraco.Core/Configuration/Models/HealthChecksSettings.cs
  src/Umbraco.Core/Configuration/Models/HelpPageSettings.cs
  src/Umbraco.Core/Configuration/Models/InstallDefaultDataSettings.cs
  src/Umbraco.Core/Configuration/Models/MarketplaceSettings.cs
  src/Umbraco.Core/Configuration/Models/RequestHandlerSettings.cs
  src/Umbraco.Core/Configuration/Models/TypeFinderSettings.cs
  src/Umbraco.Web.Common/Extensions/ServiceCollectionExtensions.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Configuration/Models/RequestHandlerSettingsTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Configuration/Models/Validation/ContentSettingsValidatorTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/PublishedContentCacheTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Services/BasicAuthServiceTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/ShortStringHelper/DefaultShortStringHelperTestsWithoutSetup.cs
Labels: category/breaking, status/needs-docs, release/16.0.0

#17699 fix: store first rte value
  src/Umbraco.Web.UI.Client/src/packages/tiny-mce/property-editors/tiny-mce/property-editor-ui-tiny-mce.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/property-editor-ui-tiptap.element.ts
Labels: internal

#17704 Updated NuGet Packages for v13
  Directory.Packages.props
  src/Umbraco.Cms.Persistence.EFCore.SqlServer/Umbraco.Cms.Persistence.EFCore.SqlServer.csproj
  src/Umbraco.Cms.Persistence.EFCore/Locking/SqlServerEFCoreDistributedLockingMechanism.cs
  src/Umbraco.Cms.Persistence.EFCore/Umbraco.Cms.Persistence.EFCore.csproj
  src/Umbraco.Cms.Persistence.SqlServer/Umbraco.Cms.Persistence.SqlServer.csproj
  src/Umbraco.Infrastructure/Umbraco.Infrastructure.csproj
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
  tests/Directory.Packages.props
  tests/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
Labels: dependencies, release/13.6.0

#17703 Hotfix: Do not set icon color if item is active
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-base/tree-item-element-base.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/tree/tree-item/document-tree-item.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/tree/tree-item/media-tree-item.element.ts
Labels: type/bug, area/frontend, release/15.1.0, release/15.1.0-rc2

#17711 V15 RC: Blocks do not work in the rich text editors
  src/Umbraco.Web.UI.Client/src/packages/block/block-rte/components/block-rte-entry/block-rte-entry-inline.test.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-rte/components/block-rte-entry/block-rte-entry.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-rte/components/block-rte-entry/block-rte-entry.test.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-rte/components/ref-rte-block/ref-rte-block.test.ts
  src/Umbraco.Web.UI.Client/src/packages/ufm/controllers/ufm-virtual-render.controller.ts
Labels: type/bug, release/15.1.0-rc2

#17679 v14: DecimalConverter - add check for integer
  src/Umbraco.Core/PropertyEditors/ValueConverters/DecimalValueConverter.cs
Labels: type/bug

#17712 V15 RC: Tiptap should only target valid block elements
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/packages/tiptap/plugins/block.extension.ts
Labels: type/bug, release/15.1.0, release/15.1.0-rc2

#17723 Feat: Content Property Datatset Context Token
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/context/block-grid-entries.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/context/block-list-entries.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-rte/context/block-rte-entries.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content/property-dataset-context/content-property-dataset.context-token.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content/property-dataset-context/content-property-dataset.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content/property-dataset-context/index.ts
Labels: category/front-end, type/feature, area/frontend, release/15.2.0

#17696 Explicit endpoints returning the Login and BackOffice logos and background
  src/Umbraco.Cms.Api.Management/Controllers/Security/BackOfficeGraphicsController.cs
  src/Umbraco.Cms.StaticAssets/Umbraco.Cms.StaticAssets.csproj
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Index.cshtml
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoLogin/Index.cshtml
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoWebsite/NoNodes.cshtml
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/assets/README.md
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/assets/login.jpg
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/assets/logo.svg
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/assets/logo_dark.svg
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/assets/logo_light.svg
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/website/logo.png
  src/Umbraco.Core/Configuration/Models/ContentSettings.cs
  src/Umbraco.Web.UI.Client/src/apps/app/app-error.element.ts
  src/Umbraco.Web.UI.Client/src/apps/app/app-logo.element.ts
  src/Umbraco.Web.UI.Client/src/apps/app/index.ts
  src/Umbraco.Web.UI.Client/src/apps/backoffice/components/backoffice-header-logo.element.ts
  src/Umbraco.Web.UI.Client/src/apps/installer/shared/layout/installer-layout.element.ts
  src/Umbraco.Web.UI.Client/src/assets/login.jpg
  src/Umbraco.Web.UI.Client/src/assets/umbraco_logo_blue.svg
  src/Umbraco.Web.UI.Client/src/assets/umbraco_logo_white.svg
  src/Umbraco.Web.UI.Client/src/mocks/browser-handlers.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/document/document.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/backoffice.handlers.ts
  src/Umbraco.Web.UI.Client/src/packages/core/auth/modals/umb-app-auth-modal.element.ts
  src/Umbraco.Web.UI.Login/index.html
  src/Umbraco.Web.UI.Login/package.json
  src/Umbraco.Web.UI.Login/public/mockServiceWorker.js
  src/Umbraco.Web.UI.Login/src/mocks/handlers/backoffice.handlers.ts
  src/Umbraco.Web.UI.Login/src/mocks/handlers/index.ts
Labels: type/feature

#17719 Add "user info" endpoint for the Delivery API
  src/Umbraco.Cms.Api.Common/DependencyInjection/UmbracoBuilderAuthExtensions.cs
  src/Umbraco.Cms.Api.Common/Security/Paths.cs
  src/Umbraco.Cms.Api.Delivery/Controllers/Security/CurrentMemberController.cs
  src/Umbraco.Cms.Api.Delivery/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Cms.Api.Delivery/Services/CurrentMemberClaimsProvider.cs
  src/Umbraco.Cms.Api.Delivery/Services/ICurrentMemberClaimsProvider.cs
Labels: release/13.6.0

#17656 V15: Fix webhook RTE serialization
  src/Umbraco.Cms.Api.Delivery/Json/DeliveryApiJsonTypeResolver.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Core/Serialization/IWebhookJsonSerializer.cs
  src/Umbraco.Core/Services/WebhookRequestService.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/Serialization/ContentJsonTypeResolverBase.cs
  src/Umbraco.Infrastructure/Serialization/SystemTextWebhookJsonSerializer.cs
  src/Umbraco.Infrastructure/Serialization/WebhookJsonTypeResolver.cs
Labels: type/bug

#17763 V14: cherry pick #17656
  src/Umbraco.Cms.Api.Delivery/Json/DeliveryApiJsonTypeResolver.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Core/Serialization/IWebhookJsonSerializer.cs
  src/Umbraco.Core/Services/WebhookRequestService.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/Serialization/ContentJsonTypeResolverBase.cs
  src/Umbraco.Infrastructure/Serialization/SystemTextWebhookJsonSerializer.cs
  src/Umbraco.Infrastructure/Serialization/WebhookJsonTypeResolver.cs
Labels: type/bug

#17774 15.1/hotfix/block editors discard changes on document load
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-areas-config/property-editor-ui-block-grid-areas-config.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-editor/property-editor-ui-block-grid.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
Labels: type/bug, release/15.1.0

#17781 V15: TinyMce triggers navigation when clicking links
  src/Umbraco.Web.UI.Client/src/packages/block/block-rte/components/block-rte-entry/block-rte-entry.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.defaults.ts
Labels: type/bug

#17782 Hotfix: block use push state
  src/Umbraco.Web.UI.Client/src/packages/block/block/context/block-entry.context.ts
Labels: type/bug, release/15.1.1

#17780 hotfix: no need to redirect when removing tab. router handles this fine
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/views/design/content-type-design-editor.element.ts
Labels: type/bug

#17783 Hotfix: Browser navigation between Documents
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/controllers/workspace-is-new-redirect.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace-editor.element.ts
Labels: type/bug, release/15.1.1

#17797 Don't overwrite ancestor configurations for public access
  src/Umbraco.Cms.Api.Management/Controllers/Document/GetPublicAccessDocumentController.cs
  src/Umbraco.Core/Services/IPublicAccessService.cs
  src/Umbraco.Core/Services/PublicAccessService.cs
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/public-access/repository/public-access.server.data.ts
Labels: type/bug

#17804 V15: RTE blocks do not work in an empty RTE editor
  src/Umbraco.Web.UI.Client/src/packages/rte/components/rte-base.element.ts
Labels: type/bug, release/15.1.1

#17809 Chore: Make msw quiet in tests
  src/Umbraco.Web.UI.Client/src/mocks/index.ts
  src/Umbraco.Web.UI.Client/utils/all-umb-consts/index.ts
  src/Umbraco.Web.UI.Client/web-test-runner.index.ts
Labels: internal, ignore-for-release

#17815 V13: Clear username cache
  src/Umbraco.Infrastructure/Cache/MemberRepositoryUsernameCachePolicy.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberRepository.cs
Labels: type/bug, release/13.6.0

#17807 V13: Allow anonymous calls for `UmbLoginStatusController.HandleLogout` action
  src/Umbraco.Web.Website/Controllers/UmbLoginStatusController.cs
Labels: type/bug

#17813 Chore: Remove client tests that doesn't do anything but trouble
  src/Umbraco.Web.UI.Client/src/apps/installer/installer.test.ts
  src/Umbraco.Web.UI.Client/src/apps/preview/preview.test.ts
  src/Umbraco.Web.UI.Client/src/apps/upgrader/upgrader-view.test.ts
  src/Umbraco.Web.UI.Client/src/apps/upgrader/upgrader.test.ts
Labels: internal, ignore-for-release

#16731 V14: Adding the ability to conditionally serialize version bound properties for the Delivery API
  src/Umbraco.Cms.Api.Delivery/Json/DeliveryApiVersionAwareJsonConverterBase.cs
  src/Umbraco.Core/DeliveryApi/IncludeInApiVersionAttribute.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Cms.Api.Delivery/Json/DeliveryApiVersionAwareJsonConverterBaseTests.cs
Labels: type/feature, release/14.4.0

#17822 v14: DictionaryRepository - override PerformGetAll
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DictionaryRepository.cs
Labels: release/14.4.0

#17808 Bugfix: missing links for invariant documents with hostnames
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/views/info/document-workspace-view-info-links.element.ts
Labels: type/bug, area/frontend, release/15.2.0

#17640 Feature: block 'draft' tag
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-block-inline/block-grid-block-inline.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-block/block-grid-block.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/ref-grid-block/ref-grid-block.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/components/block-list-entry/block-list-entry.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/components/inline-list-block/inline-list-block.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/components/ref-list-block/ref-list-block.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-rte/components/block-rte-entry/block-rte-entry.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-rte/components/ref-rte-block/ref-rte-block.element.ts
Labels: category/ux, type/feature, release/15.2.0

#17716 Fix 17326
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/views/design/content-type-design-editor.element.ts
Labels: category/front-end, area/frontend
