Repository umbraco/Umbraco-CMS, pull requests merged in 2024-06, with the labels that each got.

#16049 Respect backoffice login returnPath regression
  src/Umbraco.Web.UI.Login/src/components/external-login-provider.element.ts
Labels: community/pr

#16528 Added "git submodule update --init" command to the documentation
  .github/BUILD.md
Labels: community/pr, type/improvement

#16335 A bunch of minor performance optimizations
  src/Umbraco.Cms.Persistence.EFCore/Locking/SqlServerEFCoreDistributedLockingMechanism.cs
  src/Umbraco.Cms.Persistence.EFCore/Locking/SqliteEFCoreDistributedLockingMechanism.cs
  src/Umbraco.Cms.Persistence.SqlServer/Services/SqlServerDistributedLockingMechanism.cs
  src/Umbraco.Cms.Persistence.Sqlite/Services/SqliteDistributedLockingMechanism.cs
  src/Umbraco.Core/Models/ContentEditing/ContentItemDisplay.cs
  src/Umbraco.Core/Services/UserService.cs
  src/Umbraco.Infrastructure/Cache/PropertyEditors/BlockEditorElementTypeCache.cs
  src/Umbraco.Infrastructure/Cache/PropertyEditors/IBlockEditorElementTypeCache.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/Examine/ContentValueSetBuilder.cs
  src/Umbraco.Infrastructure/Examine/DeliveryApiContentIndexValueSetBuilder.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockEditorValidator.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockEditorValidatorBase.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockEditorValues.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockGridPropertyEditorBase.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockListPropertyEditorBase.cs
  src/Umbraco.Infrastructure/PropertyEditors/RichTextEditorBlockValidator.cs
  src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs
  src/Umbraco.Infrastructure/Templates/HtmlMacroParameterParser.cs
  src/Umbraco.Web.BackOffice/Mapping/ContentMapDefinition.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/DataValueEditorReuseTests.cs
Labels: category/performance, category/notable, release/13.4.0

#16550 RTE and media picker should route medias the same way in the Delivery API
  src/Umbraco.Core/DeliveryApi/ApiMediaUrlProvider.cs
  src/Umbraco.Infrastructure/DeliveryApi/ApiRichTextElementParser.cs
  src/Umbraco.Infrastructure/DeliveryApi/ApiRichTextMarkupParser.cs
  src/Umbraco.Infrastructure/DeliveryApi/ApiRichTextParserBase.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ApiMediaUrlProviderTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/RichTextParserTests.cs
Labels: category/breaking, release/13.4.0

#16549 OpenIddict should only handle `/umbraco/` requests
  src/Umbraco.Cms.Api.Common/DependencyInjection/ProcessRequestContextHandler.cs
  src/Umbraco.Cms.Api.Common/DependencyInjection/UmbracoBuilderAuthExtensions.cs
Labels: release/14.1.0

#16616 V13: Update nuget packages
  Directory.Packages.props
  src/Umbraco.Cms.Imaging.ImageSharp/Umbraco.Cms.Imaging.ImageSharp.csproj
  src/Umbraco.Cms.Imaging.ImageSharp2/Umbraco.Cms.Imaging.ImageSharp2.csproj
  src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
  src/Umbraco.Web.Common/Umbraco.Web.Common.csproj
Labels: dependencies, release/13.4.0

#16614 Allow http for openiddict
  src/Umbraco.Cms.Api.Common/Configuration/PostConfigureOpenIddict.cs
  src/Umbraco.Cms.Api.Common/DependencyInjection/UmbracoBuilderAuthExtensions.cs
Labels: release/14.1.0

#16257 Use parentElement instead of parent
  src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbfocuslock.directive.js
Labels: community/pr, type/bug

#16609 Add endpoint for calculating effective user start nodes
  src/Umbraco.Cms.Api.Management/Controllers/User/CalculateStartNodesUserController.cs
  src/Umbraco.Cms.Api.Management/Factories/IUserPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/UserPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/User/CalculatedUserStartNodesResponseModel.cs
Labels: release/14.1.0

#16653 Nuget update 2024 06 25
  Directory.Packages.props
  src/Umbraco.Cms.Imaging.ImageSharp/Umbraco.Cms.Imaging.ImageSharp.csproj
  src/Umbraco.PublishedCache.NuCache/Umbraco.PublishedCache.NuCache.csproj
  src/Umbraco.Web.Website/Routing/EagerMatcherPolicy.cs
  tests/Directory.Packages.props
  tools/Umbraco.JsonSchema/Umbraco.JsonSchema.csproj
Labels: dependencies, release/14.1.0
