Repository umbraco/Umbraco-CMS, pull requests merged in 2025-04, with the labels that each got.

#18863 Adds webp to mime type map to support preview on upload file property
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/utils.ts
Labels: area/frontend

#18511 Check for NRT directory when populating LuceneIndexFolder for Examine Dashboard
  src/Umbraco.Examine.Lucene/LuceneIndexDiagnostics.cs
Labels: community/pr, category/dx, type/improvement, release/15.4.0

#18899 V15: Upload Field should use a better file preview
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/preview/input-upload-field-file.element.ts
Labels: category/ux, type/feature, area/frontend, release/15.4.0

#18758 Enforce: AllowEditInvariantFromNonDefault configuration
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/structure/content-type-structure-manager.class.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content/workspace/views/edit/content-editor-properties.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/property-read-only-state.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/variant-property-read-only-state.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/variant/index.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/property-dataset-context/document-property-dataset.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace.context.ts
Labels: type/bug, area/frontend, release/15.4.0

#18900 V15: File upload should use better Image & SVG preview
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/input-upload-field.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/preview/input-upload-field-audio.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/preview/input-upload-field-image.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/preview/input-upload-field-svg.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/preview/input-upload-field-video.element.ts
Labels: category/ux, type/bug, area/frontend, release/15.4.0

#18902 V15: Block package should not import from itself
  src/Umbraco.Web.UI.Client/devops/circular/index.js
  src/Umbraco.Web.UI.Client/src/packages/block/block-rte/context/block-rte-entries.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block/modals/block-catalogue/block-catalogue-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block/validation/block-editor-validation-property-path-translator-base.api.ts
Labels: type/bug, area/frontend, release/15.4.0

#18806 Feature: highlight invariant doc with variant blocks is unsupported
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-editor/property-editor-ui-block-grid.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/context/validation-messages.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/bind-server-validation-to-form-control.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/rte/components/rte-base.element.ts
Labels: area/frontend

#18908 V16: Removes RTE Stylesheets (client-side)
  src/Umbraco.Web.UI.Client/src/assets/lang/ar.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/bs.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/cs-cz.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/cy-gb.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/de-de.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/fr-fr.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/hr-hr.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/it-it.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/nl-nl.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/tr-tr.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/stylesheet/stylesheet.data.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/entity-actions/create/options-modal/stylesheet-create-options-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/global-components/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/global-components/index.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/global-components/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/global-components/stylesheet-rule-input/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/global-components/stylesheet-rule-input/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/global-components/stylesheet-rule-input/stylesheet-rule-input.element.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/global-components/stylesheet-rule-input/stylesheet-rule-settings-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/global-components/stylesheet-rule-input/stylesheet-rule-settings-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/global-components/stylesheet-rule-ref/stylesheet-rule-ref.element.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/index.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/types.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/utils/index.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/utils/stylesheet-rule-manager.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/workspace/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/workspace/views/code-editor/stylesheet-code-editor-workspace-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/workspace/views/rich-text-rule/stylesheet-rich-text-rule-workspace-view.element.ts
Labels: area/frontend, release/16.0.0

#18918 Tiptap RTE: Style Menu extension kind
  src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-div.extension.ts
  src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-html-global-attributes.extension.ts
  src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-span.extension.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icon-dictionary.json
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-heading-4.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-paragraph.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/cascading-menu-popover/cascading-menu-popover.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/tiptap-toolbar.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/toolbar/default-tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/toolbar/style-menu.tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/toolbar/tiptap-toolbar-color-picker-button.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/toolbar/tiptap-toolbar-menu.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/style-select/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/style-select/style-select.tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/tiptap-toolbar.extension.ts
Labels: type/feature, area/frontend, release/15.4.0

#18915 V16: Vite development optimizations
  .github/workflows/azure-backoffice.yml
  .github/workflows/azure-storybook.yml
  src/Umbraco.Web.UI.Client/.env
  src/Umbraco.Web.UI.Client/index.html
  src/Umbraco.Web.UI.Client/index.ts
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/mocks/handlers/backoffice/backoffice.handlers.ts
  src/Umbraco.Web.UI.Client/src/mocks/index.ts
  src/Umbraco.Web.UI.Client/src/tsconfig.build.json
  src/Umbraco.Web.UI.Client/src/vite-env.d.ts
  src/Umbraco.Web.UI.Client/staticwebapp.config.json
  src/Umbraco.Web.UI.Client/vite.config.ts
Labels: category/dx, type/feature, release/16.0.0, preview/storybook, preview/backoffice

#18911 V16: Stylesheet Create Options
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/entity-actions/create/create.action.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/entity-actions/create/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/entity-actions/create/options-modal/stylesheet-create-options-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/entity-actions/create/options-modal/stylesheet-create-options.modal-token.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/entity-actions/create/stylesheet-create-option-action.ts
  tests/Umbraco.Tests.AcceptanceTest/package-lock.json
  tests/Umbraco.Tests.AcceptanceTest/package.json
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/Stylesheet/Stylesheet.spec.ts
Labels: type/feature, area/frontend, release/16.0.0

#18843 V16: Migrate TinyMCE data type configuration to Tiptap
  src/Umbraco.Core/Configuration/Models/TinyMceToTiptapMigrationSettings.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_16_0_0/MigrateTinyMceToTiptap.cs
Labels: category/notable, type/feature, area/backend, release/16.0.0

#18790 Ensure has children reflects only items with folder children when folders only are queried.
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/EntityRepository.cs
  tests/Umbraco.Tests.Integration/CompatibilitySuppressions.xml
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/EntityServiceTests.cs
Labels: area/backend, release/15.4.0

#18922 Move database cache rebuild to a background task with polling (13)
  src/Umbraco.Core/PublishedCache/IPublishedSnapshotService.cs
  src/Umbraco.PublishedCache.NuCache/PublishedSnapshotService.cs
  src/Umbraco.PublishedCache.NuCache/PublishedSnapshotStatus.cs
  src/Umbraco.Web.BackOffice/Controllers/PublishedSnapshotCacheStatusController.cs
  src/Umbraco.Web.UI.Client/src/views/dashboard/settings/publishedsnapshotcache.controller.js
  tests/Umbraco.Tests.UnitTests/TestHelpers/PublishedSnapshotServiceTestBase.cs
Labels: area/frontend, area/backend

#18497 Move publish with descendants to a background task with polling
  src/Umbraco.Cms.Api.Management/Controllers/Document/DocumentControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/PublishDocumentWithDescendantsController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/PublishDocumentWithDescendantsResultController.cs
  src/Umbraco.Cms.Api.Management/Controllers/PublishedCache/RebuildPublishedCacheController.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/Document/PublishWithDescendantsResultModel.cs
  src/Umbraco.Core/HostedServices/IBackgroundTaskQueue.cs
  src/Umbraco.Core/Models/ContentPublishing/ContentPublishingBranchResult.cs
  src/Umbraco.Core/Services/ContentPublishingService.cs
  src/Umbraco.Core/Services/ContentService.cs
  src/Umbraco.Core/Services/IContentPublishingService.cs
  src/Umbraco.Core/Services/OperationStatus/ContentPublishingOperationStatus.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/Examine/Deferred/DeliveryApiContentIndexHandleContentChanges.cs
  src/Umbraco.Infrastructure/Examine/Deferred/DeliveryApiContentIndexHandleContentTypeChanges.cs
  src/Umbraco.Infrastructure/Examine/Deferred/DeliveryApiContentIndexHandlePublicAccessChanges.cs
  src/Umbraco.Infrastructure/Examine/DeliveryApiIndexingHandler.cs
  src/Umbraco.Infrastructure/Examine/ExamineUmbracoIndexingHandler.cs
  src/Umbraco.Infrastructure/HostedServices/BackgroundTaskQueue.cs
  src/Umbraco.Infrastructure/HostedServices/IBackgroundTaskQueue.cs
  src/Umbraco.PublishedCache.HybridCache/DatabaseCacheRebuilder.cs
  src/Umbraco.Web.UI.Client/src/external/backend-api/src/sdk.gen.ts
  src/Umbraco.Web.UI.Client/src/external/backend-api/src/types.gen.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/repository/document-publishing.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/repository/document-publishing.server.data-source.ts
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentPublishingServiceTests.Publish.cs
Labels: area/frontend, area/backend, release/15.4.0

#18766 Clear roots before rebuilding navigation dictionary
  src/Umbraco.Core/Services/Navigation/ContentNavigationServiceBase.cs
  tests/Umbraco.Tests.Integration/CompatibilitySuppressions.xml
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentNavigationServiceTests.Rebuild.cs
Labels: area/backend

#18932 Fixes save of empty, invariant block list on variant content
  src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyValueEditorBase.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/BlockListEditorPropertyValueEditorTests.cs
Labels: area/backend

#18931 V15/bugfix/fix route issue from 18859
  src/Umbraco.Web.UI.Client/src/external/router-slot/model.ts
  src/Umbraco.Web.UI.Client/src/external/router-slot/router-slot.ts
  src/Umbraco.Web.UI.Client/src/external/router-slot/util/router.ts
  src/Umbraco.Web.UI.Client/src/packages/core/collection/collection-view.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/modal/component/modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/router/components/router-slot/route.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-editor/workspace-editor.element.ts
Labels: ignore-for-release, release/15.4.0

#18933 V16: Revert removal of RTE Block Type Configuration property-editor
  src/Umbraco.Web.UI.Client/src/packages/block/block-rte/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-rte/property-editors/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-rte/property-editors/property-editor-ui-block-rte-type-configuration.element.ts
Labels: ignore-for-release

#18929 Feature: enable get unpersisted changes (fix #18230)
  src/Umbraco.Web.UI.Client/src/packages/block/block/workspace/block-element-manager.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block/workspace/block-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/entity-detail/entity-detail-workspace-base.ts
Labels: category/dx, type/feature, release/15.4.0

#18882 Added management API endpoint, service and repository for retrieval of references from the recycle bin
  src/Umbraco.Cms.Api.Management/Controllers/Document/RecycleBin/ReferencedByDocumentRecycleBinController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Media/RecycleBin/ReferencedByMediaRecycleBinController.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Core/Persistence/Repositories/ITrackedReferencesRepository.cs
  src/Umbraco.Core/Services/ITrackedReferencesService.cs
  src/Umbraco.Core/Services/TrackedReferencesService.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/TrackedReferencesRepository.cs
  tests/Umbraco.Tests.Integration/CompatibilitySuppressions.xml
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/TrackedReferencesServiceTests.cs
Labels: area/backend

#18952 Fix icon circular import
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icon-picker-modal/icon-picker-modal.element.ts
Labels: ignore-for-release, release/15.4.0

#18951 Fix confirm modal circular import
  src/Umbraco.Web.UI.Client/src/packages/core/modal/common/confirm/confirm-modal.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/modal/controller/open-modal.controller.ts
Labels: release/16.0.0, ignore-for-release

#18949 Remove segment toggle for elements
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/workspace/document-type/views/settings/document-type-workspace-view-settings.element.ts
Labels: ignore-for-release, release/15.4.0

#18953 Fix modal route registration circular import
  src/Umbraco.Web.UI.Client/src/packages/core/router/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/router/modal-registration/modal-route-registration.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/router/route/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/router/route/not-found/route-not-found.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/router/route/route.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/router/route/route.interface.ts
  src/Umbraco.Web.UI.Client/src/packages/core/router/route/router-slot-change.event.ts
  src/Umbraco.Web.UI.Client/src/packages/core/router/route/router-slot-init.event.ts
  src/Umbraco.Web.UI.Client/src/packages/core/router/route/router-slot.element.ts
Labels: ignore-for-release, release/15.4.0

#18890 Avoid unneeded Dictionary operations
  src/Umbraco.Core/Collections/ObservableDictionary.cs
  src/Umbraco.Core/Models/Content.cs
  src/Umbraco.Core/Models/Navigation/NavigationNode.cs
  src/Umbraco.Core/Services/LocalizedTextService.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberTypeRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/PublishStatusRepository.cs
  src/Umbraco.Web.Common/Helpers/OAuthOptionsHelper.cs
Labels: community/pr, category/performance, type/improvement, release/15.4.0

#18888 Avoid some heap allocations
  src/Umbraco.Cms.Api.Delivery/Configuration/ConfigureUmbracoMemberAuthenticationDeliveryApiSwaggerGenOptions.cs
  src/Umbraco.Cms.Api.Management/OpenApi/BackOfficeSecurityRequirementsOperationFilterBase.cs
  src/Umbraco.Core/Composing/TypeFinder.cs
  src/Umbraco.Core/Exceptions/InvalidCompositionException.cs
  src/Umbraco.Core/Extensions/IntExtensions.cs
  src/Umbraco.Core/Extensions/StringExtensions.cs
  src/Umbraco.Core/GuidUtils.cs
  src/Umbraco.Core/HexEncoder.cs
  src/Umbraco.Core/Strings/DefaultShortStringHelper.cs
  src/Umbraco.Core/Strings/Utf8ToAsciiConverter.cs
Labels: community/pr, category/performance, type/improvement, release/15.4.0

#18199 Avoid allocating strings for parsing comma separated int values
  src/Umbraco.Core/Extensions/StringExtensions.cs
  src/Umbraco.Core/Services/PublicAccessService.cs
  src/Umbraco.Core/Services/UserService.cs
  tests/Umbraco.Tests.Benchmarks/StringExtensionsBenchmarks.cs
Labels: community/pr, category/performance, type/improvement, release/15.4.0

#18914 Data type References UI: Workspace + Delete
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Core/Services/DataTypeService.cs
  src/Umbraco.Web.UI.Client/src/external/backend-api/src/sdk.gen.ts
  src/Umbraco.Web.UI.Client/src/external/backend-api/src/types.gen.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/document-blueprint/document-blueprint.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/document-blueprint/document-blueprint.db.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/document/document.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/document/document.db.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/tracked-reference.data.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/info-app/workspace-info-app.extension.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/entity-actions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/reference/info-app/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/reference/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/reference/repository/data-type-reference.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/reference/repository/data-type-reference.server.data.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/workspace/views/info/data-type-workspace-view-info-reference.element.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/workspace/views/info/workspace-view-data-type-info.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/property-type/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/property-type/document-type-property-type-item-ref.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/property-type/document-type-property-type-reference-response.management-api.mapping.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/property-type/entity.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/property-type/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/property-type/types.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/reference/info-app/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/reference/repository/document-reference-response.management-api.mapping.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/reference/types.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/property-type/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/property-type/entity.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/property-type/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/property-type/media-type-property-type-item-ref.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/property-type/media-type-property-type-reference-response.management-api.mapping.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/property-type/types.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/reference/info-app/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/reference/info-app/media-references-workspace-info-app.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/reference/repository/media-reference-response.management-api.mapping.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/reference/repository/types.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/property-type/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/property-type/entity.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/property-type/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/property-type/member-type-property-type-item-ref.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/property-type/member-type-property-type-reference-response.management-api.mapping.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/property-type/types.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/reference/info-app/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/reference/info-app/member-references-workspace-info-app.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/reference/repository/member-reference-response.management-api.mapping.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/reference/repository/types.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/reference/workspace-info-app/entity-references-workspace-view-info.element.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/reference/workspace-info-app/entity-references-workspace-view-info.kind.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/reference/workspace-info-app/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/reference/workspace-info-app/types.ts
Labels: category/ux, type/feature, release/15.4.0

#18956 fix 18367
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-split-view/workspace-split-view-variant-selector.element.ts
Labels: area/frontend

#18963 V16: API error interceptor should return early if it will not execute
  src/Umbraco.Web.UI.Client/src/packages/core/notification/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/notification/isUmbNotifications.function.ts
  src/Umbraco.Web.UI.Client/src/packages/core/resources/api-interceptor.controller.ts
Labels: type/feature, area/frontend, release/16.0.0

#18961 Move "diff" from external to core/utils
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/external/diff/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/package.json
  src/Umbraco.Web.UI.Client/src/packages/core/utils/diff/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/utils/index.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/rollback/modal/rollback-modal.element.ts
  src/Umbraco.Web.UI.Client/tsconfig.json
Labels: category/breaking, category/dx, release/16.0.0

#18955 Internalize uuid package
  src/Umbraco.Web.UI.Client/eslint.config.js
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/external/diff/index.ts
  src/Umbraco.Web.UI.Client/src/external/uuid/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/id/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/package.json
  src/Umbraco.Web.UI.Client/src/packages/core/utils/diff/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/utils/index.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/rollback/modal/rollback-modal.element.ts
  src/Umbraco.Web.UI.Client/tsconfig.json
Labels: category/breaking, category/dx, release/16.0.0

#18967 V16: Adds server context to store information about paths
  src/Umbraco.Web.UI.Client/devops/circular/index.js
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/apps/app/app-context-config.interface.ts
  src/Umbraco.Web.UI.Client/src/apps/app/app-logo.element.ts
  src/Umbraco.Web.UI.Client/src/apps/app/app.element.ts
  src/Umbraco.Web.UI.Client/src/apps/app/index.ts
  src/Umbraco.Web.UI.Client/src/apps/preview/preview.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/block-grid-manager/block-grid-manager.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-type/components/block-type-card/block-type-card.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/auth/modals/umb-app-auth-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/server/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/server/network-connection-status.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/server/server-connection.ts
  src/Umbraco.Web.UI.Client/src/packages/core/server/server.context-token.ts
  src/Umbraco.Web.UI.Client/src/packages/core/server/server.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/server/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/vite.config.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/index.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/image-cropper-field.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/index.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/index.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/input-upload-field.element.ts
  src/Umbraco.Web.UI.Client/src/packages/sysinfo/repository/sysinfo.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/user/current-user/current-user.context.ts
  src/Umbraco.Web.UI.Client/tsconfig.json
Labels: category/breaking, type/feature, area/frontend, preview/backoffice

#18960 `umb-localize` encode HTML arguments
  src/Umbraco.Web.UI.Client/src/libs/localization-api/localization.controller.test.ts
  src/Umbraco.Web.UI.Client/src/libs/localization-api/localization.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/localization/localize.element.test.ts
  src/Umbraco.Web.UI.Client/src/packages/core/localization/localize.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/utils/sanitize/escape-html.function.ts
Labels: status/regression, area/frontend

#18969 Remove external base64-js module
  src/Umbraco.Web.UI.Client/eslint.config.js
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/external/openid/base64-js/index.ts
  src/Umbraco.Web.UI.Client/src/external/openid/crypto_utils.ts
  src/Umbraco.Web.UI.Client/tsconfig.json
Labels: category/breaking, release/16.0.0

#18679 V15: User password resetting notification
  src/Umbraco.Cms.Api.Management/Controllers/Security/SecurityControllerBase.cs
  src/Umbraco.Core/Notifications/UserPasswordResettingNotification.cs
  src/Umbraco.Core/Services/UserService.cs
Labels: status/needs-docs, area/backend

#18721 Aggregate document permissions for current user in API response
  src/Umbraco.Cms.Api.Management/Factories/UserPresentationFactory.cs
  tests/Umbraco.Tests.Common/Builders/UserGroupBuilder.cs
  tests/Umbraco.Tests.Integration/ManagementApi/Factories/UserGroupPresentationFactoryTests.cs
  tests/Umbraco.Tests.Integration/ManagementApi/Factories/UserPresentationFactoryTests.cs
Labels: area/backend

#18935 Document permission inheritance in UI
  src/Umbraco.Web.UI.Client/src/mocks/data/document-blueprint/document-blueprint.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/document-blueprint/document-blueprint.db.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/document/data/permissions-test.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/document/document.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/document/document.db.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/user-group/user-group.data.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/global-components/entity-actions-table-column-view/entity-actions-table-column-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity/contexts/ancestors/ancestors.entity-context-token.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity/contexts/ancestors/ancestors.entity-context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity/contexts/ancestors/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity/contexts/ancestors/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/menu/menu-variant-tree-structure-workspace-context-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/router/route/not-found/route-not-found.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/entity-detail/entity-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/repository/document-collection.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/types.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/views/table/column-layouts/document-entity-actions-table-column-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/views/table/document-table-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish/workspace-action/save-and-publish.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/recycle-bin/tree/types.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/tree/document-tree.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/tree/tree-item/document-tree-item.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/tree/types.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/user-permissions/conditions/document-user-permission.condition.test.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/user-permissions/conditions/document-user-permission.condition.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace.context.ts
Labels: type/bug, area/frontend

#18913 V16: Removes TinyMCE (server-side)
  src/Umbraco.Core/Constants-PropertyEditors.cs
  src/Umbraco.Core/Models/Blocks/RichTextBlockValue.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/SimpleRichtextValueConverter.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/AddEditorUiToDataType.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_14_0_0/MigrateDataTypeConfigurations.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/ConvertRichTextEditorProperties.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_0_0/LocalLinks/LocalLinkRteProcessor.cs
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/RteBlockRenderingValueConverter.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/BlockEditorBackwardsCompatibilityTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/PropertyIndexValueFactoryTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditorTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/RichTextPropertyEditorHelperTests.cs
Labels: category/breaking, category/notable, type/feature, area/backend, release/16.0.0

#18273 Feature: Use uui invalid color
  src/Umbraco.Web.UI.Client/examples/validation-context/validation-context-dashboard.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entries/block-grid-entries.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/components/block-list-entry/block-list-entry.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-rte/components/block-rte-entry/block-rte-entry.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/input-number-range/input-number-range.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/input-with-alias/input-with-alias.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/multiple-color-picker-input/multiple-color-picker-item-input.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/multiple-text-string-input/input-multiple-text-string-item.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/views/design/content-type-design-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content/workspace/content-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/components/property-layout/property-layout.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/components/form-validation-message.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/modals/workspace-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/modals/workspace-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/components/data-type-flow-input/data-type-flow-input.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/workspace-context/document-publishing.workspace-context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/dropdown/property-editor-ui-dropdown.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts
Labels: category/ux, type/feature, area/frontend, release/15.4.0

#18981 V16: Installer does not proceed from last step
  src/Umbraco.Web.UI.Client/src/apps/installer/database/installer-database.element.ts
  src/Umbraco.Web.UI.Client/src/apps/installer/installer.context.ts
Labels: area/frontend, ignore-for-release

#19007 Cleanup redirect to allowed section
  src/Umbraco.Web.UI.Client/src/apps/backoffice/components/backoffice-main.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/section/section-default.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/current-user/current-user.context.ts
Labels: area/frontend, release/16.0.0, ignore-for-release

#18995 set ESLint working directory
  .vscode/settings.json
Labels: ignore-for-release

#18972 Use GetIdsFromPathReversed to avoid allocating the string values of the integers parsed
  src/Umbraco.Core/Services/PublicAccessService.cs
Labels: community/pr, category/performance, type/improvement, release/15.5.0

#19024 Fix dropzone style circular imports
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/components/input-dropzone/input-dropzone.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/components/input-dropzone/input-dropzone.stories.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/input-image-cropper.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/input-upload-field.element.ts
Labels: ignore-for-release

#19026 Dont check for imports in comments
  src/Umbraco.Web.UI.Client/devops/module-dependencies/index.js
Labels: area/frontend, release/16.0.0, ignore-for-release

#19039 Adds some missing mime types to ensure uploaded audio and video displays with preview
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/utils.ts
Labels: area/frontend

#19031 V16: Split media handling from UmbDropzoneManager
  src/Umbraco.Web.UI.Client/devops/circular/index.js
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/entity-actions/import/modal/document-type-import-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/components/input-dropzone/input-dropzone.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/dropzone-manager.class.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/index.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/types.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/entity-actions/import/modal/media-type-import-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/types.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/dropzone-media.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/index.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/media-dropzone.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/modals/dropzone-media-type-picker/dropzone-media-type-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/modals/dropzone-media-type-picker/dropzone-media-type-picker-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/modals/dropzone-media-type-picker/index.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/modals/index.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/modals/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/index.ts
Labels: category/breaking, type/feature, release/16.0.0

#19036 Fix theme module self import
  src/Umbraco.Web.UI.Client/src/packages/core/themes/theme.context.ts
Labels: release/16.0.0, ignore-for-release

#19037 Fix member + member type module self import
  src/Umbraco.Web.UI.Client/devops/module-dependencies/index.js
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/repository/composition/member-type-composition.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/property-editor/member-picker/property-editor-ui-member-picker.element.ts
Labels: release/16.0.0, ignore-for-release

#19041 Move + Rename input-collection-configuration element to input-content-type-collection-configuration
  src/Umbraco.Web.UI.Client/devops/module-dependencies/index.js
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/global-components/index.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/global-components/input-content-type-collection-configuration/index.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/global-components/input-content-type-collection-configuration/input-content-type-collection-configuration.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/input-collection-configuration/index.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/workspace/document-type/views/structure/document-type-workspace-view-structure.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/workspace/views/structure/media-type-workspace-view-structure.element.ts
Labels: category/breaking, area/frontend, release/16.0.0

#19035 Fix document module self import
  src/Umbraco.Web.UI.Client/devops/module-dependencies/index.js
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/action/create-document-collection-action.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/components/input-document/input-document.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/create/document-create-options-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/culture-and-hostnames/culture-and-hostnames.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/modals/document-picker-modal.token.ts
Labels: release/16.0.0, ignore-for-release

#19021 Chore: Temp solution to remove user circular imports
  src/Umbraco.Web.UI.Client/devops/circular/index.js
  src/Umbraco.Web.UI.Client/devops/module-dependencies/index.js
  src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user-group/collection/views/user-group-table-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user-group/components/user-group-ref/user-group-ref.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user-group/modals/user-group-picker/user-group-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user-group/workspace/user-group/user-group-workspace-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/components/user-document-start-node/user-document-start-node.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/components/user-media-start-node/user-media-start-node.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/modals/user-picker/user-picker-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/property-editor/user-picker/property-editor-ui-user-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/workspace/user/components/user-workspace-assign-access/user-workspace-assign-access.element.ts
Labels: area/frontend, release/16.0.0, ignore-for-release

#19046 Content search abstractions to facilitate new search in the backoffice
  src/Umbraco.Core/Services/IContentSearchService.cs
  src/Umbraco.Core/Services/IContentSearchServiceOfTContent.cs
  src/Umbraco.Core/Services/IMediaSearchService.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.Services.cs
  src/Umbraco.Infrastructure/Services/ContentListViewServiceBase.cs
  src/Umbraco.Infrastructure/Services/Implement/ContentListViewService.cs
  src/Umbraco.Infrastructure/Services/Implement/ContentSearchService.cs
  src/Umbraco.Infrastructure/Services/Implement/ContentSearchServiceBase.cs
  src/Umbraco.Infrastructure/Services/Implement/MediaListViewService.cs
  src/Umbraco.Infrastructure/Services/Implement/MediaSearchService.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentSearchServiceTests.cs
Labels: release/16.0.0

#19048 Make the entity search service async
  src/Umbraco.Cms.Api.Management/Controllers/Document/Item/SearchDocumentItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Media/Item/SearchMediaItemController.cs
  src/Umbraco.Core/Services/IIndexedEntitySearchService.cs
  src/Umbraco.Infrastructure/Services/Implement/IndexedEntitySearchService.cs
Labels: release/16.0.0

#19052 V16: Chore: Corrects `UmbLocalizationController` usage in comments/docs
  src/Umbraco.Web.UI.Client/src/libs/element-api/element.interface.ts
  src/Umbraco.Web.UI.Client/src/libs/localization-api/localization.controller.test.ts
  src/Umbraco.Web.UI.Client/src/libs/localization-api/localization.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/localization/stories/localization.mdx
Labels: category/api-documentation, area/frontend, release/16.0.0

#19055 V16: Chore: Client-side markup and style code sweep
  src/Umbraco.Web.UI.Client/src/apps/backoffice/backoffice.element.ts
  src/Umbraco.Web.UI.Client/src/apps/backoffice/components/backoffice-header-apps.element.ts
  src/Umbraco.Web.UI.Client/src/apps/backoffice/components/backoffice-header.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-rte/components/ref-rte-block/ref-rte-block.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/collection/default/collection-default.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/header-app/header-app-button.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icon-picker-modal/icon-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/default/default-tree.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-base/tree-item-element-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-split-view/workspace-split-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/collection/views/grid/media-grid-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/dynamic-root/modals/dynamic-root-origin-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/dynamic-root/modals/dynamic-root-query-step-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/character-map/character-map-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/current-user/current-user-header-app.element.ts
Labels: area/frontend, ignore-for-release

#19056 V16: Chore: Deprecate `getManifest()` methods
  src/Umbraco.Web.UI.Client/src/packages/core/collection/conditions/collection-alias.condition.ts
  src/Umbraco.Web.UI.Client/src/packages/core/collection/default/collection-default.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/recycle-bin/tree/tree-item/recycle-bin-tree-item.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/default/default-tree.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-base/tree-item-context-base.ts
Labels: category/dx, area/frontend, release/16.0.0

#19067 Cleanup last known self imports
  src/Umbraco.Web.UI.Client/devops/module-dependencies/index.js
  src/Umbraco.Web.UI.Client/src/packages/core/property-action/components/property-action-menu/property-action-menu.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property-editor/components/ref-property-editor-ui/ref-property-editor-ui.stories.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property-editor/extensions/property-editor-ui-element.interface.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property-editor/ui-picker-modal/property-editor-ui-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action-menu-item/default/workspace-action-menu-item.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action-menu/workspace-action-menu.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action/common/submit/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-breadcrumb/workspace-menu-breadcrumb/workspace-menu-breadcrumb.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-breadcrumb/workspace-variant-menu-breadcrumb/workspace-variant-menu-breadcrumb.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-footer/workspace-footer.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/contexts/tokens/publishable-workspace.context-token.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/contexts/tokens/submittable-workspace.context-token.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/kinds/default/default-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/modals/workspace-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/workspace-property-dataset/invariant-workspace-property-dataset-context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/workspace.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/repository/composition/media-type-composition.repository.ts
Labels: release/16.0.0, ignore-for-release

#19071 Align server validation with new Fetch Client
  src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/content-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/context/server-model-validator.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/validation.controller.test.ts
Labels: release/16.0.0, ignore-for-release

#19057 Adds trashed/draft state to document search result items
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/search/document-search-result-item.element.ts
Labels: type/feature, area/frontend, release/16.0.0

#19064 Content Picker Search: Option to exclude trashed items
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/components/input-document/input-document.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/components/input-document/input-document.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/search/document-search.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/search/types.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-media/input-media.context.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-media/input-media.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/search/media-search.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/search/types.ts
Labels: type/feature, area/frontend, release/16.0.0

#19047 Transparent Focal Point
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/image-cropper-focus-setter.element.ts
Labels: category/ui, release/16.0.0

#19032 Dynamic Root: Refactored to use `UmbAncestorsEntityContext`
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/dynamic-root/repository/dynamic-root.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/property-editor-ui-content-picker.element.ts
Labels: type/feature, area/frontend, release/16.0.0

#19062 Adds search to Document Type picker
  src/Umbraco.Web.UI.Client/src/packages/core/picker/search/manager/picker-search.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/components/input-document-type/input-document-type.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/components/input-document-type/input-document-type.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/modals/document-type-picker-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/picker/document-type-picker-search-result-item.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/picker/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/search/document-type-search.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/search/document-type-search.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/search/document-type.search-provider.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/search/types.ts
Labels: type/feature, area/frontend, release/16.0.0

#19058 Adds `searchResultItem` element for Media items
  src/Umbraco.Web.UI.Client/src/packages/media/media/search/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/search/media-search-result-item.element.ts
Labels: type/feature, area/frontend, release/16.0.0

#19075 V16: Chore: Refine `umb-localize` rendering
  src/Umbraco.Web.UI.Client/src/packages/core/localization/localize.element.ts
Labels: area/frontend, release/16.0.0, ignore-for-release

#19089 implement readonly mode for umb-property-editor-ui-document-type-picker
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/components/input-document-type/input-document-type.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/property-editors/document-type-picker/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/property-editors/document-type-picker/property-editor-ui-document-type-picker.element.ts
Labels: area/frontend, release/16.0.0

#19060 Feature: Segments
  src/Umbraco.Cms.Api.Management/Controllers/Content/ContentControllerBase.cs
  src/Umbraco.Cms.Api.Management/Factories/ContentEditingPresentationFactory.cs
  src/Umbraco.Core/Services/ContentEditingServiceBase.cs
  src/Umbraco.Core/Services/OperationStatus/ContentEditingOperationStatus.cs
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/workspace/views/design/content-type-design-editor-properties.element.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/workspace/views/design/content-type-design-editor-property.element.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/manager/content-data-manager.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/manager/element-data-manager.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/content-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/content-workspace-context.interface.ts
  src/Umbraco.Web.UI.Client/src/packages/content/property-type/workspace/views/settings/property-workspace-view-settings.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/variant/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-split-view/workspace-split-view-variant-selector.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/contexts/tokens/variant-dataset-workspace-context.interface.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/configuration/configuration.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/configuration/configuration.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/configuration/types.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/workspace/document-type/views/settings/document-type-workspace-view-settings.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish/workspace-action/save-and-publish.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/unpublish/entity-action/unpublish.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/workspace-context/document-publishing.workspace-context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/actions/save.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/segment/collection/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/segment/collection/index.ts
  src/Umbraco.Web.UI.Client/src/packages/segment/collection/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/segment/collection/repository/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/segment/collection/repository/index.ts
  src/Umbraco.Web.UI.Client/src/packages/segment/collection/repository/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/segment/collection/repository/segment-collection.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/segment/collection/repository/segment-collection.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/segment/collection/repository/types.ts
  src/Umbraco.Web.UI.Client/src/packages/segment/collection/types.ts
  src/Umbraco.Web.UI.Client/src/packages/segment/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/segment/entity.ts
  src/Umbraco.Web.UI.Client/src/packages/segment/index.ts
  src/Umbraco.Web.UI.Client/src/packages/segment/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/segment/types.ts
  src/Umbraco.Web.UI.Client/src/packages/segment/umbraco-package.ts
  src/Umbraco.Web.UI.Client/src/packages/segment/vite.config.ts
  src/Umbraco.Web.UI.Client/tsconfig.json
  tests/Umbraco.Tests.AcceptanceTest/package-lock.json
  tests/Umbraco.Tests.AcceptanceTest/package.json
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/DocumentType/DocumentTypeDesignTab.spec.ts
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentBlueprintEditingServiceTests.CreateFromContent.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Create.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Delete.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.DeleteFromRecycleBin.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Get.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.MoveToRecycleBin.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Update.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Validate.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTestsBase.cs
Labels: release/16.0.0

#19103 V16: Import `umb-app-logo` element
  src/Umbraco.Web.UI.Client/src/apps/app/app.element.ts
Labels: area/frontend, release/16.0.0

#19074 Allow for configuration of log file names
  src/Umbraco.Core/Configuration/Models/LoggingSettings.cs
  src/Umbraco.Core/Configuration/Models/Validation/LoggingSettingsValidator.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Configuration.cs
  src/Umbraco.Core/Logging/ILoggingConfiguration.cs
  src/Umbraco.Core/Logging/LoggingConfiguration.cs
  src/Umbraco.Infrastructure/Logging/Serilog/LoggerConfigExtensions.cs
  src/Umbraco.Infrastructure/Logging/Serilog/UmbracoFileConfiguration.cs
  src/Umbraco.Web.Common/Extensions/ServiceCollectionExtensions.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Configuration/Models/Validation/LoggingSettingsValidatorTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Logging/LoggingConfigurationTests.cs
Labels: status/needs-docs, area/backend, release/16.0.0

#19030 Removed population of Urls on document response model and obsoleted property
  src/Umbraco.Cms.Api.Management/Factories/DocumentPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentResponseModel.cs
  src/Umbraco.Web.UI.Client/src/mocks/data/document/document.data.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/content-detail-validation-path-translator.test.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/pending-changes/document-published-pending-changes.manager.test.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/repository/document-publishing.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/repository/detail/document-detail.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/types.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/link-picker-modal/link-picker-modal.element.ts
  tests/Umbraco.Tests.AcceptanceTest/README.md
  tests/Umbraco.Tests.AcceptanceTest/package-lock.json
  tests/Umbraco.Tests.AcceptanceTest/package.json
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithApprovedColor.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithCheckboxList.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithContentPicker.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithDatePicker.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithDropdown.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithImageCropper.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithMemberPicker.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithMultiURLPicker.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithMultipleMediaPicker.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithNumeric.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithRadiobox.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithTags.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithTextarea.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithTextstring.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithTrueFalse.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RenderingContent/RenderingContentWithUploadFile.spec.ts
Labels: area/frontend, area/backend, release/16.0.0

#19112 Add report for bidirectional module imports
  src/Umbraco.Web.UI.Client/devops/module-dependencies/index.js
Labels: release/16.0.0, ignore-for-release

#19114 Service refactoring to "fully" enable segments
  src/Umbraco.Cms.Api.Management/Factories/ContentEditingPresentationFactory.cs
  src/Umbraco.Core/Models/ContentEditing/ContentEditingModelBase.cs
  src/Umbraco.Core/Models/ContentEditing/PropertyValueModel.cs
  src/Umbraco.Core/Models/ContentEditing/VariantModel.cs
  src/Umbraco.Core/Models/Validation/PropertyValidationContext.cs
  src/Umbraco.Core/Services/ContentBlueprintEditingService.cs
  src/Umbraco.Core/Services/ContentEditingServiceBase.cs
  src/Umbraco.Core/Services/ContentPublishingService.cs
  src/Umbraco.Core/Services/ContentValidationServiceBase.cs
  src/Umbraco.Core/Services/MemberContentEditingService.cs
  src/Umbraco.Infrastructure/Services/MemberEditingService.cs
  tests/Umbraco.Tests.Common/Builders/ContentEditingBaseBuilder.cs
  tests/Umbraco.Tests.Common/Builders/ContentEditingPropertyValueBuilder.cs
  tests/Umbraco.Tests.Common/Builders/ContentEditingVariantBuilder.cs
  tests/Umbraco.Tests.Common/TestHelpers/DocumentUpdateHelper.cs
  tests/Umbraco.Tests.Integration/ManagementApi/Policies/UpdateDocumentTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentEditingServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentPublishingServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentNavigationServiceTests.Update.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentNavigationServiceTestsBase.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/MediaEditingServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/MediaNavigationServiceTests.Update.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/MediaNavigationServiceTestsBase.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/BlockListElementLevelVariationTests.Editing.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/BlockListElementLevelVariationTests.Validation.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentBlueprintEditingServiceTests.Create.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentBlueprintEditingServiceTests.CreateFromContent.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentBlueprintEditingServiceTests.GetPagedByContentTypeKey.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentBlueprintEditingServiceTests.Update.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentBlueprintEditingServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Create.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Sort.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Update.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Validate.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTestsBase.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentListViewServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentValidationServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/MediaListViewServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/MemberEditingServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.PublishedCache.HybridCache/DocumentHybridCachePropertyTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.PublishedCache.HybridCache/DocumentHybridCacheTemplateTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.PublishedCache.HybridCache/DocumentHybridCacheTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.PublishedCache.HybridCache/DocumentHybridCacheVariantsTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.PublishedCache.HybridCache/MediaHybridCacheTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.PublishedCache.HybridCache/MemberHybridCacheTests.cs
Labels: category/breaking, area/backend, release/16.0.0

#19034 Content Type inheritance
  src/Umbraco.Cms.Api.Management/Factories/ContentTypeEditingPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/DocumentTypeEditingPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/MediaTypeEditingPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Mapping/ContentType/ContentTypeMapDefinition.cs
  src/Umbraco.Cms.Api.Management/Mapping/DocumentType/DocumentTypeMapDefinition.cs
  src/Umbraco.Cms.Api.Management/Mapping/MediaType/MediaTypeMapDefinition.cs
  src/Umbraco.Cms.Api.Management/Mapping/MemberType/MemberTypeMapDefinition.cs
  src/Umbraco.Core/Services/ContentTypeEditing/ContentTypeEditingServiceBase.cs
  src/Umbraco.Web.UI.Client/src/libs/observable-api/states/array-state.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block/workspace/block-element-manager.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/modals/composition-picker/composition-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/modals/composition-picker/composition-picker-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/structure/content-type-property-structure-helper.class.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/structure/content-type-structure-manager.class.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/workspace/content-type-workspace-context-base.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/workspace/views/design/content-type-design-editor-properties.element.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/workspace/views/design/content-type-design-editor-property.element.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/workspace/views/design/content-type-design-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/content/property-type/workspace/property-type-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/content/property-type/workspace/views/settings/property-workspace-view-settings.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/repository/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/repository/repository-details.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/repository/repository-items.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/entity-detail/entity-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-blueprints/workspace/document-blueprint-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/entity-actions/create/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/entity-actions/create/modal/document-type-create-options-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/workspace/document-type/document-type-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/entity-actions/create/default/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/workspace/media-type-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/workspace/media-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-group/workspace/member-group/views/info/member-type-workspace-view-info.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/workspace/member/member-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/workspace/member/views/member/member-workspace-view-member-info.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/workspace/user/user-workspace.context.ts
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentTypeEditingServiceTests.Create.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentTypeEditingServiceTests.Update.cs
Labels: area/frontend, area/backend, release/16.0.0

#19105 Split "Sort Children"-logic to remove "illegal" import from core to packages
  src/Umbraco.Web.UI.Client/devops/module-dependencies/index.js
  src/Umbraco.Web.UI.Client/src/packages/content/content/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/tree/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/tree/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/tree/sort-children-of-content/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/tree/sort-children-of-content/index.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/tree/sort-children-of-content/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/tree/sort-children-of-content/modal/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/tree/sort-children-of-content/modal/index.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/tree/sort-children-of-content/modal/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/tree/sort-children-of-content/modal/sort-children-of-content-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/tree/sort-children-of-content/modal/sort-children-of-content-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/tree/sort-children-of-content/sort-children-of-content.action.kind.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/tree/sort-children-of-content/sort-children-of-content.action.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/tree/sort-children-of-content/types.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/tree/types.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/table/table.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/entity-actions/sort-children-of/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/entity-actions/sort-children-of/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/entity-actions/sort-children-of/modal/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/entity-actions/sort-children-of/modal/sort-children-of-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/entity-actions/sort-children-of/modal/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/entity-actions/sort-children-of/sort-children-of.action.kind.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/entity-actions/sort-children-of/sort-children-of.action.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/entity-actions/sort-children-of/types.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/sort-children-of/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/entity-actions/sort-children-of/manifests.ts
Labels: category/breaking, release/16.0.0

#19117 Updated server-side dependencies to latest versions for Umbraco 16
  Directory.Packages.props
  src/Umbraco.Infrastructure/PropertyEditors/RichTextEditorPastedImages.cs
  src/Umbraco.Web.Common/Mvc/HtmlStringUtilities.cs
  tests/Directory.Packages.props
  tests/Umbraco.Tests.Integration/Umbraco.Core/DeliveryApi/OpenApiContractTest.cs
Labels: area/backend, release/16.0.0

#19123 Fix UI creation and updating of Document Blueprints
  src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/content-detail-workspace-base.ts
Labels: release/16.0.0

#19122 Image Cropper + Tags style adjustments
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/components/input-dropzone/input-dropzone.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/input-image-cropper.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tags/components/tags-input/tags-input.element.ts
Labels: category/ui, area/frontend, release/16.0.0

#19121 upgrade client dependencies
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/packages/core/backend-api/types.gen.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icon-dictionary.json
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-autofill.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-candy.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-certificate.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-chip-alt.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-chip.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-clipboard-paste.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-colorpicker.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-document-medal.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-filter.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-infinity.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-newspaper-alt.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-newspaper.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-operator.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-palette.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-paste-in.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-piggy-bank.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-planet.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-umb-developer.ts
Labels: release/16.0.0

#19127 V16: Bumps core dependencies openapi-ts and uuid to latest
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/packages/core/openapi-ts.dev.config.js
  src/Umbraco.Web.UI.Client/src/packages/core/package.json
Labels: dependencies, area/frontend, release/16.0.0

#19118 V16: Adds texts for unpublish & publish with descendants
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/data-type/data-type.db.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/document/document-publishing.manager.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/data-type/filter.handlers.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/data-type/index.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/document-type/detail.handlers.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/document/detail.handlers.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/document/publishing.handlers.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish/entity-action/publish.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish/entity-bulk-action/publish.bulk-action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/repository/document-publishing.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/unpublish/entity-action/unpublish.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/unpublish/entity-bulk-action/unpublish.bulk-action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/workspace-context/document-publishing.workspace-context.ts
Labels: category/ux, type/feature, area/frontend, release/16.0.0

#19124 Add Conditions to ManifestHeaderApp
  src/Umbraco.Web.UI.Client/src/packages/core/extension-registry/extensions/header-app.extension.ts
Labels: release/16.0.0

#19129 Retrofit ContentEditingBaseBuilder to match new create/update models
  tests/Umbraco.Tests.Common/Builders/ContentEditingBaseBuilder.cs
  tests/Umbraco.Tests.Common/Builders/ContentEditingBuilder.cs
  tests/Umbraco.Tests.Common/Builders/ContentEditingPropertyValueBuilder.cs
  tests/Umbraco.Tests.Common/Builders/ContentEditingVariantBuilder.cs
  tests/Umbraco.Tests.Common/Builders/Extensions/BuilderExtensions.cs
  tests/Umbraco.Tests.Common/Builders/Interfaces/IWithInvariantNameBuilder.cs
  tests/Umbraco.Tests.Common/Builders/MediaEditingBuilder.cs
Labels: category/breaking, area/backend, release/16.0.0

#19128 V15: Ensure elements cache is cleared on subscribers in load balanced scenarios
  src/Umbraco.Core/Cache/Refreshers/Implement/ContentCacheRefresher.cs
  src/Umbraco.Core/Cache/Refreshers/Implement/MediaCacheRefresher.cs
  src/Umbraco.PublishedCache.HybridCache/NotificationHandlers/CacheRefreshingNotificationHandler.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Cache/DistributedCacheRefresherTests.cs
Labels: type/bug

#19130 Removed population of Urls on media response model and obsoleted property
  src/Umbraco.Cms.Api.Management/Factories/MediaPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/Media/MediaResponseModel.cs
  src/Umbraco.Web.UI.Client/src/mocks/data/media/media.data.ts
  src/Umbraco.Web.UI.Client/src/packages/core/backend-api/types.gen.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-caption-alt-text/media-caption-alt-text-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/repository/detail/media-detail.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/types.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/url/info-app/media-links-workspace-info-app.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/workspace/media-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/link-picker-modal/link-picker-modal.element.ts
Labels: area/frontend, area/backend

#19133 Prevent Culture and Hostnames modal close on error
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/culture-and-hostnames/modal/culture-and-hostnames-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/culture-and-hostnames/repository/culture-and-hostnames.repository.ts
Labels: category/ux, type/bug, area/frontend, release/16.0.0

#19141 Implement a Context Proxy (Fix Provide event handling across proxies)
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/libs/context-api/provide/context-provide.event.ts
  src/Umbraco.Web.UI.Client/src/libs/context-proxy/context-proxy.controller.ts
  src/Umbraco.Web.UI.Client/src/libs/context-proxy/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/modal/component/modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/section/section-sidebar-context-menu/section-sidebar-context-menu.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/default/default-tree.context.ts
  src/Umbraco.Web.UI.Client/tsconfig.json
Labels: release/16.0.0, ignore-for-release

#19158 Hotfix: bring back media collection
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/workspace/views/structure/media-type-workspace-view-structure.element.ts
Labels: release/16.0.0, ignore-for-release

#19152 Hotfix: Do not reset promise on clear
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/structure/content-type-structure-manager.class.ts
Labels: release/16.0.0, ignore-for-release

#19155 Prevent input-document type search from returning element types when not allowed
  src/Umbraco.Web.UI.Client/src/packages/core/picker-input/picker-input.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/components/input-document-type/input-document-type.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/components/input-document-type/input-document-type.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/property-editors/document-type-picker/property-editor-ui-document-type-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/search/document-type-search.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/search/types.ts
Labels: release/16.0.0, ignore-for-release

#19145 Make culture specific update dates work again
  src/Umbraco.Core/Models/ContentBase.cs
  src/Umbraco.Core/Models/Entities/BeingDirtyBase.cs
  src/Umbraco.Core/Models/IProperty.cs
  src/Umbraco.Core/Models/Property.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentPublishingServiceTests.Publish.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Update.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTestsBase.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/ContentTests.cs
Labels: category/breaking, release/16.0.0

#19171 Entity action error handling
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/common/delete/delete.action.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/common/duplicate/duplicate.action.ts
  src/Umbraco.Web.UI.Client/src/packages/core/recycle-bin/entity-action/empty-recycle-bin/empty-recycle-bin.action.ts
  src/Umbraco.Web.UI.Client/src/packages/core/recycle-bin/entity-action/trash/trash.action.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/entity-actions/duplicate-to/duplicate-to.action.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/entity-actions/move/move-to.action.ts
  src/Umbraco.Web.UI.Client/src/packages/dictionary/entity-action/export/export.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-blueprints/entity-actions/create/create.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/entity-actions/export/document-type-export.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/duplicate/duplicate-document.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/permissions.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish/entity-action/publish.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/unpublish/entity-action/unpublish.action.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/entity-actions/export/media-type-export.action.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-public-access/modal/public-access-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-public-access/repository/public-access.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/user/change-password/entity-action/change-user-password.action.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/entity-actions/disable/disable-user.action.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/entity-actions/enable/enable-user.action.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/entity-actions/unlock/unlock-user.action.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/invite/modal/resend-invite/resend-invite-to-user-modal.element.ts
Labels: ignore-for-release

#19166 Remove sort children success notification from repository
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/sort-children-of/repository/sort-children-of.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/entity-actions/sort-children-of/repository/sort-children-of.repository.ts
Labels: area/frontend, release/16.0.0

#19173 Fix so a Preset Value can be falsy
  src/Umbraco.Web.UI.Client/src/packages/core/property/property-value-preset/property-value-preset-builder.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/number/decimal-property-value-preset.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/number/integer-property-value-preset.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/number/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/number/types.ts
Labels: category/ux, area/frontend, release/16.0.0

#19175 Output the correct error status code from the Management API
  src/Umbraco.Cms.Api.Management/DependencyInjection/ApplicationBuilderExtensions.cs
Labels: type/bug, release/16.0.0

#19149 Remove success notification after file rename
  src/Umbraco.Web.UI.Client/src/packages/core/server-file-system/rename/rename-server-file-repository-base.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/PartialView/PartialView.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/Script/Script.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/Stylesheet/Stylesheet.spec.ts
Labels: category/ux, type/feature, area/frontend, release/16.0.0

#19159 V16: Show modal when publishing invariant content
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish/entity-action/publish.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish/modal/document-publish-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish/modal/document-publish-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/unpublish/entity-action/unpublish.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/unpublish/modal/document-unpublish-modal.element.ts
  tests/Umbraco.Tests.AcceptanceTest/package-lock.json
  tests/Umbraco.Tests.AcceptanceTest/package.json
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ChildrenContent.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/Content.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/RedirectManagement.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Users/Permissions/UserGroup/DefaultPermissionsInContent.spec.ts
Labels: category/ux, type/bug, area/frontend, release/16.0.0, preview/backoffice

#19163 Remove workspace split view entity actions for new content
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-split-view/workspace-split-view.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-split-view/workspace-split-view.element.ts
Labels: area/frontend, release/16.0.0

#19178 Add segments support for Publish entity action
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish/entity-action/publish.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/workspace-context/document-publishing.workspace-context.ts
Labels: category/ux, area/frontend, release/16.0.0

#19177 Webhook log authorization and file system path checks
  src/Umbraco.Cms.Api.Management/Controllers/Webhook/Logs/WebhookLogControllerBase.cs
  src/Umbraco.Core/IO/PhysicalFileSystem.cs
Labels: area/backend, release/16.0.0, release/15.4.0

#19179 Add copy to clipboard success notification
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/clipboard/property/actions/copy/copy-to-clipboard.property-action.ts
  src/Umbraco.Web.UI.Client/src/packages/clipboard/property/context/clipboard.property-context.ts
Labels: category/ux, area/frontend

#19189 Build: Avoids rebuilding Backoffice unless it is required
  src/Umbraco.Cms.StaticAssets/Umbraco.Cms.StaticAssets.csproj
Labels: type/feature, ignore-for-release

#19185 Open entity actions menu as pop up instead of modal
  src/Umbraco.Web.UI.Client/src/packages/core/components/entity-actions-bundle/entity-actions-bundle.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/entity-action-list.element.ts
Labels: category/ux, release/16.0.0

#19192 fix: The server path is not appended to stylesheets before load in Backoffice
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts
Labels: area/frontend

#19194 Ensure picker search config query params are always included in the server request
  src/Umbraco.Web.UI.Client/src/packages/core/modal/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/picker/search/manager/picker-search.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/picker/search/manager/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-picker-modal/tree-picker-modal.element.ts
Labels: release/16.0.0, ignore-for-release
