Repository umbraco/Umbraco-CMS, pull requests merged in 2025-09, with the labels that each got.

#20041 V16: Moves icon dependencies to 'core' package.json
  src/Umbraco.Web.UI.Client/devops/icons/index.js
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-azure.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-facebook.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-gitbook.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-github.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-gitlab.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-google.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-mastodon.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-microsoft.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-pictures.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-twitter-x.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-twitter.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-umbrella.ts
  src/Umbraco.Web.UI.Client/src/packages/core/package.json
Labels: type/feature, area/frontend, preview/backoffice, release/16.3.0

#20057 Tiptap RTE: Migration to auto-enable new capabilities
  src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_16_3_0/AddRichTextEditorCapabilities.cs
Labels: type/feature, area/backend, release/16.3.0

#20055 Database creation/migration for UFM Label editor data-types
  src/Umbraco.Core/Constants-DataTypes.cs
  src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_16_3_0/MigrateMediaTypeLabelProperties.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/DataTypeDefinitionRepositoryTest.cs
Labels: type/feature, area/backend, release/16.3.0

#20033 Workspace View Manifest Overrides
  src/Umbraco.Web.UI.Client/src/packages/content/content/collection/content-collection-workspace-context.interface.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/collection/content-collection-workspace-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/collection/content-collection-workspace.context-token.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/collection/index.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/collection/manager/content-collection-manager.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/collection/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/collection/workspace-has-content-collection/workspace-has-content-collection.condition.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/content-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/collection/collection.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/collection/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-editor/workspace-editor.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-editor/workspace-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-editor/workspace-view.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-footer/workspace-footer.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-split-view/workspace-split-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace-split-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/workspace/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/workspace/media-workspace-split-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/workspace/media-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/collection/property-editor-ui-collection.element.ts
Labels: type/feature, area/frontend, release/16.3.0

#20062 Verify that the request cache is available before using it in PublishedContentFactory
  src/Umbraco.PublishedCache.HybridCache/Factories/PublishedContentFactory.cs
  tests/Umbraco.Tests.Integration/Umbraco.PublishedCache.HybridCache/Factories/PublishedContentFactoryTests.cs
Labels: ignore-for-release

#20099 Dropdown: Allow empty option
  src/Umbraco.Web.UI.Client/src/packages/property-editors/dropdown/property-editor-ui-dropdown.element.ts
Labels: type/bug, area/frontend

#20053 V16 - Introducing signs to variants
  src/Umbraco.Cms.Api.Management/Controllers/Content/ContentCollectionControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/Collection/ByKeyDocumentCollectionController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/Item/ItemDocumentItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Media/Collection/ByKeyMediaCollectionController.cs
  src/Umbraco.Cms.Api.Management/Factories/ContentCollectionPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/DocumentPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Services/Signs/HasPendingChangesSignProvider.cs
  src/Umbraco.Cms.Api.Management/Services/Signs/HasScheduleSignProvider.cs
  src/Umbraco.Cms.Api.Management/Services/Signs/ISignProvider.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentVariantItemResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentVariantResponseModel.cs
  src/Umbraco.Core/Persistence/Repositories/IDocumentRepository.cs
  src/Umbraco.Core/Services/ContentService.cs
  src/Umbraco.Core/Services/IContentService.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentRepository.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentServiceTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Cms.Api.Management/Services/Signs/HasPendingChangesSignProviderTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Cms.Api.Management/Services/Signs/HasScheduleSignProviderTests.cs
Labels: release/16.3.0

#20083 Correct the population of the parent for sibling items when retrieved under a folder
  src/Umbraco.Cms.Api.Management/Controllers/Tree/EntityTreeControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/Tree/FolderTreeControllerBase.cs
Labels: release/16.3.0

#20102 Block editors: resolves clipboard UFM label
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/components/block-list-entry/block-list-entry.element.ts
  src/Umbraco.Web.UI.Client/src/packages/clipboard/clipboard-entry/picker/clipboard-entry-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/ufm/controllers/ufm-virtual-render.controller.ts
Labels: type/bug, area/frontend

#19986 Repositories: Introduce and use NPoco and custom extension methods for SQL syntax in ContentTypeRepositoryBase
  src/Umbraco.Infrastructure/Persistence/NPocoSqlExtensions.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs
  src/Umbraco.Infrastructure/Persistence/SqlSyntax/ISqlSyntaxProvider.cs
  src/Umbraco.Infrastructure/Persistence/SqlSyntax/SqlSyntaxProviderBase.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Persistence/Querying/ContentTypeRepositorySqlClausesTest.cs
Labels: community/pr, release/17.0.0

#19955 Repositories: Use NPoco extensions in DatabaseCacheRepository
  src/Umbraco.PublishedCache.HybridCache/Persistence/DatabaseCacheRepository.cs
Labels: community/pr, release/16.3.0

#20084 Feature: Redirect to the last visited path when navigating between sections
  src/Umbraco.Web.UI.Client/src/apps/backoffice/components/backoffice-header-sections.element.ts
Labels: category/ux, release/16.3.0

#20116 V16: Fix member validation endpoints
  src/Umbraco.Infrastructure/Services/MemberEditingService.cs
  src/Umbraco.Web.UI.Client/src/packages/members/member/repository/validation/member-validation.server.data-source.ts
Labels: area/backend, release/16.3.0

#20133 Tiptap RTE: Fixes undo when RTE is emptied
  src/Umbraco.Web.UI.Client/src/packages/block/block-rte/components/ref-rte-block/ref-rte-block.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/heading/heading.tiptap-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap-rte/property-editor-ui-tiptap.element.ts
Labels: type/bug, area/frontend, release/16.3.0

#20148 AppSettings: Improves the templates so they reflect the latest recommended settings
  src/Umbraco.Web.UI/appsettings.Development.template.json
  src/Umbraco.Web.UI/appsettings.template.json
Labels: type/improvement, release/16.3.0

#20151 Generated Partial Views: Improves the generated code slightly for a better developer experience
  src/Umbraco.Core/EmbeddedResources/BlockGrid/default.cshtml
  src/Umbraco.Web.UI/Views/Partials/blockgrid/default.cshtml
  src/Umbraco.Web.UI/Views/Partials/blocklist/default.cshtml
Labels: type/improvement, release/16.3.0

#19737 #19736 adjust drag placeholder for document picker
  src/Umbraco.Web.UI.Client/src/packages/core/entity-item/entity-item-ref/entity-item-ref.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/components/input-document/input-document.element.ts
Labels: category/ui, release/16.3.0

#20104 Property Editors: Improve Missing Property Editor UI and allow save/publish
  src/Umbraco.Core/Services/ContentEditingServiceBase.cs
  src/Umbraco.Core/Services/PropertyValidationService.cs
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/pt.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/missing/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/missing/modal/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/missing/modal/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/missing/modal/missing-editor-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/missing/modal/missing-editor-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/missing/property-editor-ui-missing.element.ts
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Services/PropertyValidationServiceTests.cs
Labels: type/improvement, release/16.3.0

#20183 Dynamic Root: Fix missing dynamicRootQueryStep types (closes #19612)
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/components/index.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/dynamic-root/types.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/types.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/vite.config.ts
  src/Umbraco.Web.UI.Client/tsconfig.json
Labels: category/dx, release/16.3.0

#20159 Interaction Memory: Feature for picker modal state retention (#18305)
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/packages/core/entry-point.ts
  src/Umbraco.Web.UI.Client/src/packages/core/interaction-memory/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/core/interaction-memory/event/interaction-memories-change.event.ts
  src/Umbraco.Web.UI.Client/src/packages/core/interaction-memory/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/interaction-memory/interaction-memory.context.token.ts
  src/Umbraco.Web.UI.Client/src/packages/core/interaction-memory/interaction-memory.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/interaction-memory/interaction-memory.manager.test.ts
  src/Umbraco.Web.UI.Client/src/packages/core/interaction-memory/interaction-memory.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/interaction-memory/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/modal/context/modal.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/modal/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/picker-input/picker-input.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/picker/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/picker/modal/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/picker/modal/picker-modal-base.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/picker/picker.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/picker/search/manager/picker-search.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property-editor/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property-editor/interaction-memory/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property-editor/interaction-memory/property-editor-ui-interaction-memory.manager.test.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property-editor/interaction-memory/property-editor-ui-interaction-memory.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item-picker/tree-item-picker-expansion.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item-picker/tree-item-picker.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-picker-modal/tree-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/vite.config.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/components/input-document/input-document.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/property-editors/document-picker/property-editor-ui-document-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-media/input-media.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/modals/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/media-picker.context.token.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/media-picker.context.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/media-picker/property-editor-ui-media-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/components/input-content/input-content.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/property-editor-ui-content-picker.element.ts
  src/Umbraco.Web.UI.Client/tsconfig.json
Labels: category/ux, type/feature, release/16.3.0

#20145 View Context: Implement browser title
  src/Umbraco.Web.UI.Client/examples/workspace-view-hint/hint-workspace-view.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/workspace/content-type-workspace-context-base.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/workspace/content-type-workspace-context.interface.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/content-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/views/edit/content-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-item/entity-item-ref/entity-item-ref.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/hint/context/hints.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/section/section.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/view/context/view.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/view/context/view.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-editor/workspace-editor.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-editor/workspace-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-editor/workspace-view.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/entity-detail/entity-named-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/components/input-document/input-document.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/workspace/member/member-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user-group/workspace/user-group/user-group-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/workspace/user/user-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/webhook/webhook/collection/repository/webhook-collection.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/webhook/webhook/repository/detail/webhook-detail.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/webhook/webhook/types.ts
  src/Umbraco.Web.UI.Client/src/packages/webhook/webhook/workspace/webhook-workspace.context.ts
Labels: type/feature, area/frontend, release/16.3.0

#20201 Icons: add badge icon
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icon-dictionary.json
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-badge.ts
Labels: area/frontend

#20198 Content/Document Picker: make not existing items appear
  src/Umbraco.Web.UI.Client/src/packages/core/entity-item/entity-item-ref/entity-item-ref.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/picker-input/picker-input.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/repository/repository-items.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/repository/types.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/components/input-document/input-document.element.ts
Labels: category/ux, release/16.3.0

#20040 Management API: Add user data delete endpoint (closes #19793)
  src/Umbraco.Cms.Api.Management/Controllers/UserData/DeleteUserDataController.cs
Labels: community/pr, release/16.3.0

#15289 Allow fetching multiple content and media by `Guid` and `Udi`
  src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
  src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
Labels: community/pr, area/backend, release/13.12.0

#20107 Accessibility changes for the top navbar tabs and settings tabs
  src/Umbraco.Web.UI.Client/src/apps/backoffice/components/backoffice-header-sections.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/section/section-main-views/section-main-views.element.ts
Labels: category/accessibility, release/16.3.0

#20172 Tiptap RTE: Adds hover and focus border input states
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts
Labels: category/accessibility, type/improvement, release/16.3.0

#20209 Caching: Don't remove null values from hybrid cache to avoid broken content references repeatedly requiring a database hit (closes #18892)
  src/Umbraco.PublishedCache.HybridCache/Services/DocumentCacheService.cs
Labels: release/16.3.0

#20235 Collection view: Wrong `Last edited` date displayed in document collection view (closes #19988)
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/repository/document-collection.server.data-source.ts
Labels: type/bug, area/frontend

#20238 Workspace Base: make nonesense getter method to make Lit happy
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-editor/workspace-editor.element.ts
Labels: ignore-for-release

#20134 Upload field Property Editor: Fix resetting value to undefined when empty
  src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/content-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/mixins/form-control.mixin.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action/common/save/save.action.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/input-upload-field.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/upload-field/property-editor-ui-upload-field.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/repository/validation/media-validation.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/collection/repository/member-collection.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/collection/repository/user-collection.repository.ts
Labels: category/front-end, area/frontend, release/16.3.0

#20257 Make remove button consistent with other multi value item remove button
  src/Umbraco.Web.UI.Client/src/packages/core/components/multiple-color-picker-input/multiple-color-picker-item-input.element.ts
Labels: community/pr, release/17.0.0

#20259 Localization/UX: Add a new general translation for "Fields"
  src/Umbraco.Web.UI.Client/src/assets/lang/da.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/nb.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/pt.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/vi.ts
  src/Umbraco.Web.UI.Client/src/packages/search/examine-management-dashboard/modal/fields-settings/examine-fields-settings-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/search/examine-management-dashboard/views/section-view-examine-searchers.ts
Labels: community/pr, release/17.0.0

#20275 Dependencies: Update ImageSharp to latest patch releases (13)
  Directory.Packages.props
  src/Umbraco.Cms.Imaging.ImageSharp2/Umbraco.Cms.Imaging.ImageSharp2.csproj
Labels: dependencies

#20249 Unattended install: Added the ability to set the telemetry level
  src/Umbraco.Cms.Api.Management/DependencyInjection/InstallerBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/Install/PostUnattendedInstallNotificationHandler.cs
  src/Umbraco.Core/Configuration/Models/UnattendedSettings.cs
  templates/UmbracoProject/.template.config/dotnetcli.host.json
  templates/UmbracoProject/.template.config/ide.host.json
  templates/UmbracoProject/.template.config/template.json
  templates/UmbracoProject/appsettings.Development.json
Labels: category/breaking, community/pr, release/17.0.0

#20310 Log Viewer: Fixes continuous polling (closes #20274)
  src/Umbraco.Web.UI.Client/src/packages/log-viewer/workspace/logviewer-workspace.context.ts
Labels: type/bug, area/frontend, release/16.4.0
