Repository umbraco/Umbraco-CMS, pull requests merged in 2025-01, with the labels that each got.

#17172 Fix Umbraco.Tests.Common warnings.
  tests/Umbraco.Tests.Common/Builders/ContentTypeEditingBuilder.cs
  tests/Umbraco.Tests.Common/TestHelperBase.cs
  tests/Umbraco.Tests.Common/TestLastChanceFinder.cs
Labels: hacktoberfest-accepted, hacktoberfest/contrib-2024

#17899 Call change event after update of multiple text string order
  src/Umbraco.Web.UI.Client/src/packages/core/components/multiple-text-string-input/input-multiple-text-string.element.ts
Labels: area/frontend

#17857 Fix #17758: V15 - Race condition breaks navigation between documents
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/structure/content-type-structure-manager.class.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content/workspace/content-detail-workspace-base.ts
Labels: area/frontend

#17853 Fix #14541: hide "Publish with descendants" when not yet created
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/conditions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/conditions/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/conditions/workspace-content-type-alias.condition.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/conditions/workspace-entity-is-new.condition.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/conditions/workspace-entity-type.condition.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/conditions/workspace-has-collection.condition.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish-with-descendants/workspace-action/manifests.ts
Labels: area/frontend

#17887 update property container id when container changed
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/views/design/content-type-design-editor-group.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/views/design/content-type-design-editor-properties.element.ts
Labels: area/frontend

#17669 V15: Document Type Create Options
  src/Umbraco.Web.UI.Client/src/packages/core/components/ref-item/ref-item.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/common/create/modal/entity-create-option-action-list-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/modal/common/item-picker/item-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/picker/search/result-item/default/default-picker-search-result-item.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/entity-actions/create/default/default-document-type-create-option-action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/entity-actions/create/element/element-type-create-option-action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/entity-actions/create/folder/document-type-folder-create-option-action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/entity-actions/create/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/entity-actions/create/modal/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/entity-actions/create/modal/document-type-create-options-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/entity-actions/create/template/document-type-with-template-create-option-action.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/dynamic-root/modals/dynamic-root-origin-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/dynamic-root/modals/dynamic-root-query-step-picker-modal.element.ts
Labels: type/feature, area/frontend, release/15.2.0

#17879 Implemented sorting for media picker crops
  src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/image-crops/property-editor-ui-image-crops.element.ts
Labels: area/frontend

#17880 Add workspace view path const
  src/Umbraco.Web.UI.Client/src/packages/core/router/route.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-editor/workspace-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/paths.ts
Labels: area/frontend

#17837 V15: Warn when content is unroutable
  src/Umbraco.Core/Configuration/Models/ContentSettings.cs
  src/Umbraco.Core/Events/AddUnroutableContentWarningsWhenPublishingNotificationHandler.cs
  src/Umbraco.Core/Routing/NewDefaultUrlProvider.cs
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
Labels: area/backend

#17877 Timing updates for rendering and preparation of user group granular permissions details to resolve intermittent error on race condition
  src/Umbraco.Web.UI.Client/src/packages/core/extension-registry/components/extension-slot/extension-slot.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/extension-registry/components/extension-with-api-slot/extension-with-api-slot.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user-group/workspace/user-group/components/user-group-granular-permission-list.element.ts
Labels: area/frontend

#17900 V15: Change password should not be shown when local login is disabled
  src/Umbraco.Cms.Api.Management/Controllers/Server/ConfigurationServerController.cs
  src/Umbraco.Cms.Api.Management/Factories/UserPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/Server/ServerConfigurationResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/User/UserConfigurationResponseModel.cs
  src/Umbraco.Web.UI.Client/src/apps/app/app-context-config.interface.ts
  src/Umbraco.Web.UI.Client/src/apps/app/app.context.ts
  src/Umbraco.Web.UI.Client/src/apps/app/app.element.ts
  src/Umbraco.Web.UI.Client/src/apps/app/server-connection.ts
  src/Umbraco.Web.UI.Client/src/external/backend-api/src/sdk.gen.ts
  src/Umbraco.Web.UI.Client/src/external/backend-api/src/types.gen.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/server.handlers.ts
  src/Umbraco.Web.UI.Client/src/packages/core/auth/modals/umb-app-auth-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/sysinfo/repository/sysinfo.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/sysinfo/types.ts
  src/Umbraco.Web.UI.Client/src/packages/user/change-password/entity-action/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/user/current-user/external-login/modals/external-login-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/current-user/profile/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/conditions/allow-change-password/user-allow-change-password-action.condition.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/conditions/allow-mfa/user-allow-mfa-action.condition.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/conditions/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/conditions/is-default-kind/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/conditions/is-default-kind/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/conditions/is-default-kind/user-is-default-kind.condition.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/conditions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/repository/config/user-config.repository.ts
  src/Umbraco.Web.UI.Client/utils/all-umb-consts/index.ts
Labels: area/frontend, area/backend

#17884 Fix to GetCultureFromDomains extensions following changes to routing and published content cache
  src/Umbraco.Core/Routing/DomainUtilities.cs
  src/Umbraco.Web.Common/Extensions/FriendlyPublishedContentExtensions.cs
  src/Umbraco.Web.Common/Extensions/PublishedContentExtensions.cs
Labels: area/backend

#17876 Fixed infinite loop triggered when requesting media by ID in a folder via the media delivery API
  src/Umbraco.Infrastructure/DeliveryApi/ApiMediaWithCropsResponseBuilder.cs
Labels: area/backend

#17534 V15: Dont create invalid media
  src/Umbraco.Cms.Api.Management/Controllers/Media/CreateMediaController.cs
  src/Umbraco.Core/Services/MediaEditingService.cs
  tests/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTestWithMediaEditing.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/MediaEditingServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/MediaNavigationServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/MediaListViewServiceTests.cs
Labels: area/backend

#17854 Use data type configuration to determine default value for empty toggle and slider property values
  src/Umbraco.Core/PropertyEditors/SliderConfiguration.cs
  src/Umbraco.Core/PropertyEditors/TrueFalseConfiguration.cs
  src/Umbraco.Core/PropertyEditors/TrueFalseConfigurationEditor.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/SliderValueConverter.cs
  src/Umbraco.Core/PropertyEditors/ValueConverters/YesNoValueConverter.cs
  src/Umbraco.Infrastructure/PropertyEditors/TrueFalsePropertyEditor.cs
  src/Umbraco.Infrastructure/Serialization/SystemTextConfigurationEditorJsonSerializer.cs
  tests/Umbraco.Tests.Common/Builders/DataTypeBuilder.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/PropertyEditorValueConverterTests.cs
Labels: area/backend

#17535 Improve document schedule
  src/Umbraco.Cms.Api.Management/Controllers/Document/ByKeyDocumentController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/DocumentControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/PublishDocumentController.cs
  src/Umbraco.Cms.Api.Management/Factories/DocumentPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/IDocumentPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Mapping/Document/DocumentMapDefinition.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentVariantResponseModel.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Document/PublishDocumentRequestModel.cs
  src/Umbraco.Core/Constants-System.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Core/Extensions/ContentExtensions.cs
  src/Umbraco.Core/Models/ContentPublishing/CultureAndScheduleModel.cs
  src/Umbraco.Core/Models/ContentPublishing/CultureScheduleModel.cs
  src/Umbraco.Core/Models/ContentQuery/ContentScheduleQueryResult.cs
  src/Umbraco.Core/Models/ContentScheduleCollection.cs
  src/Umbraco.Core/Services/ContentPublishingService.cs
  src/Umbraco.Core/Services/ContentService.cs
  src/Umbraco.Core/Services/IContentPublishingService.cs
  src/Umbraco.Core/Services/IContentService.cs
  src/Umbraco.Core/Services/OperationStatus/ContentQueryOperationStatus.cs
  src/Umbraco.Core/Services/Querying/ContentQueryService.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentRepository.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentEditingServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentPublishingServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentServiceTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/ContentScheduleTests.cs
Labels: area/backend

#17904 Allow sort of children by name and create date
  src/Umbraco.Cms.Api.Management/Controllers/Document/Tree/DocumentTreeControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/Media/Tree/MediaTreeControllerBase.cs
  src/Umbraco.Cms.Api.Management/Controllers/RecycleBin/RecycleBinControllerBase.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/RecycleBin/RecycleBinItemResponseModelBase.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Tree/ContentTreeItemResponseModel.cs
  src/Umbraco.Web.UI.Client/src/external/backend-api/src/types.gen.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/document-blueprint/document-blueprint.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/document-blueprint/document-blueprint.db.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/document/document.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/document/document.db.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/media/media.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/media/media.db.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/entity-actions/sort-children-of/modal/sort-children-of-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/entity-actions/sort-children-of/sort-children-of.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/recycle-bin/tree/document-recycle-bin-tree.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/tree/document-tree.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/tree/types.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/recycle-bin/tree/media-recycle-bin-tree.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/tree/media-tree.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/tree/types.ts
Labels: area/frontend, area/backend

#17893 Display variant selection on unpublish only if the document is variant
  src/Umbraco.Core/Services/ContentPublishingService.cs
  src/Umbraco.Web.UI.Client/src/packages/core/modal/common/confirm/confirm-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish/entity-bulk-action/publish.bulk-action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish/modal/document-publish-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/unpublish/entity-bulk-action/unpublish.bulk-action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/unpublish/modal/document-unpublish-modal.element.ts
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentPublishingServiceTests.Publish.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentPublishingServiceTests.Unpublish.cs
Labels: area/frontend, area/backend

#17912 Block list amount valivation message
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
Labels: area/frontend

#17915 Do not allow editing read-only properties
  src/Umbraco.Core/Services/ContentEditingServiceBase.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTests.Update.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEditingServiceTestsBase.cs
Labels: release/15.2.0

#17671 V13: Add rcl files to static files tree
  src/Umbraco.Web.BackOffice/Trees/StaticFilesTreeController.cs
Labels: area/backend

#17878 Reload children of destination after duplicate of content
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/duplicate/duplicate-document.action.ts
Labels: area/frontend, release/15.2.0

#17926 Render all URLs in document workspace info tab and ensure protocol-less links can be used to access the intended URL.
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/views/info/document-workspace-view-info-links.element.ts
Labels: area/frontend

#17349 V14: Reintroduce BackOfficeUserManagerAuditer
  src/Umbraco.Cms.Api.Management/Controllers/Security/BackOfficeController.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/AuditLogBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/Security/BackOfficeUserManagerAuditer.cs
Labels: hacktoberfest-accepted, area/backend, hacktoberfest/contrib-2024

#17928 Fix omitted callback
  src/Umbraco.Web.UI.Client/src/libs/class-api/class.mixin.ts
  src/Umbraco.Web.UI.Client/src/libs/element-api/element.mixin.ts
Labels: area/frontend

#17776 V15: Notification Hub
  Directory.Build.props
  src/Umbraco.Cms.Api.Management/DependencyInjection/ServerEventExtensions.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/UmbracoBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/Factories/DataTypePresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Routing/BackOfficeAreaRoutes.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/DataTypeEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/DictionaryItemEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/DocumentEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/DocumentTypeEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/DomainEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/LanguageEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/MediaEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/MediaTypeEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/MemberEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/MemberGroupEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/MemberTypeEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/PartialViewEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/PublicAccessEntryEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/RelationEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/RelationTypeEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/ScriptEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/StylesheetEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/TemplateEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/UserEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/UserGroupEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/Authorizers/WebhookEventAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/EventSourcePolicyAuthorizer.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/ServerEventAuthorizationService.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/ServerEventHub.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/ServerEventRouter.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/ServerEventSender.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/ServerEventUserManager.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/UserConnectionManager.cs
  src/Umbraco.Cms.Api.Management/ServerEvents/UserConnectionRefresher.cs
  src/Umbraco.Core/Constants-ServerEvents.cs
  src/Umbraco.Core/Constants-Web.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Collections.cs
  src/Umbraco.Core/Models/ServerEvents/ServerEvent.cs
  src/Umbraco.Core/Models/ServerEvents/SeverEventAuthorizationResult.cs
  src/Umbraco.Core/ServerEvents/EventSourceAuthorizerCollection.cs
  src/Umbraco.Core/ServerEvents/EventSourceAuthorizerCollectionBuilder.cs
  src/Umbraco.Core/ServerEvents/IEventSourceAuthorizer.cs
  src/Umbraco.Core/ServerEvents/IServerEventAuthorizationService.cs
  src/Umbraco.Core/ServerEvents/IServerEventHub.cs
  src/Umbraco.Core/ServerEvents/IServerEventRouter.cs
  src/Umbraco.Core/ServerEvents/IServerEventUserManager.cs
  src/Umbraco.Core/ServerEvents/IUserConnectionManager.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Cms.Api.Management/ServerEvents/FakeAuthorizer.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Cms.Api.Management/ServerEvents/ServerEventAuthorizerTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Cms.Api.Management/ServerEvents/ServerEventRouterTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Cms.Api.Management/ServerEvents/ServerEventUserManagerTests.cs
Labels: type/feature, area/backend, release/15.2.0

#17938 Make the Delivery API "ancestors" selector work with preview
  src/Umbraco.Cms.Api.Delivery/Querying/Selectors/AncestorsSelector.cs
Labels: area/backend

#17937 V15: Handle domains in invariant content
  src/Umbraco.Core/Services/DocumentUrlService.cs
Labels: area/backend

#17946 Corrected property names and structure used in JSON schema generation for configuration of default data to install.
  tools/Umbraco.JsonSchema/UmbracoCmsSchema.cs
Labels: area/backend

#17949 Added integration test to verify the Delivery API contract
  tests/Umbraco.Tests.Integration/Umbraco.Core/DeliveryApi/OpenApiContractTest.cs
Labels: area/backend

#17903 Fixing problem on Linux where `dotnet run` fails because we try to set an IIS config
  src/Umbraco.Web.Common/DependencyInjection/UmbracoBuilderExtensions.cs
Labels: area/backend

#17957 Published Content should handle "is previewing"
  src/Umbraco.PublishedCache.HybridCache/PublishedContent.cs
Labels: release/15.2.0

#17972 V13: Update @umbraco-ui/uui to 1.12.2
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Login/package-lock.json
  src/Umbraco.Web.UI.Login/package.json
Labels: dependencies, javascript, area/frontend, release/13.6.0

#17976 Fix: 17428
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block/context/block-entries.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block/context/block-manager.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/context/validation-messages.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/validation.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/utils/extract-json-query-properties.function.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/utils/extract-json-query-properties.test.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/utils/index.ts
Labels: category/front-end, area/frontend

#17962 Add Vary header to all content API operations
  src/Umbraco.Cms.Api.Delivery/Controllers/Content/ContentApiControllerBase.cs
  src/Umbraco.Cms.Api.Delivery/Filters/AddVaryHeaderAttribute.cs
Labels: release/13.6.0

#17956 Resets send to approval dialog on close such that when re-opening the selection and operation can still be triggered.
  src/Umbraco.Web.UI.Client/src/views/content/overlays/sendtopublish.controller.js
Labels: area/frontend, affected/v13

#17943 Feature: no callback then destroy
  src/Umbraco.Web.UI.Client/src/libs/observable-api/observer.ts
Labels: area/frontend

#17973 V13: Update @microsoft/signalr from 7.0.12 to 8.0.7
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
Labels: dependencies, javascript, area/frontend, release/13.6.0

#17980 V15: Adds validation to all entity workspaces
  src/Umbraco.Web.UI.Client/src/mocks/browser-handlers.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/relation-type/relationType.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/relation-type/relationType.db.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/relation/relation.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/relation/relation.db.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/data-type/tree.handlers.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/package.handlers.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/relation-type/detail.handlers.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/relation-type/index.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/relation-type/slug.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/relation/index.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/relation/item.handlers.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/relation/slug.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/input-with-alias/input-with-alias.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/content-type-workspace-context-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content/workspace/content-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property-type/workspace/property-type-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-header-name-editable/workspace-header-name-editable.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/entity-detail/entity-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/tree/folder/workspace/data-type-folder-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/workspace/data-type-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/dictionary/workspace/dictionary-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-blueprints/tree/folder/workspace/document-blueprint-folder-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/tree/folder/workspace/document-type-folder-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/language/workspace/language/language-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/tree/folder/workspace/media-type-folder-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-group/workspace/member-group/member-group-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/packages/package-builder/workspace/workspace-package-builder.element.ts
  src/Umbraco.Web.UI.Client/src/packages/packages/package-repo/workspace/workspace-package.element.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relation-types/workspace/relation-type/relation-type-workspace-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/partial-views/tree/folder/workspace/partial-view-folder-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/partial-views/workspace/partial-view-workspace-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/partial-views/workspace/partial-view-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/scripts/tree/folder/workspace/script-folder-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/scripts/workspace/script-workspace-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/scripts/workspace/script-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/tree/folder/workspace/stylesheet-folder-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/workspace/stylesheet-workspace-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/workspace/stylesheet-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/templates/workspace/template-workspace-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/templates/workspace/template-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/workspace/user/user-workspace.context.ts
Labels: type/feature, area/frontend, release/15.2.0

#17981 add missing new media auditTrail translation
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
Labels: area/frontend

#17985 Enforce the "Save and preview" button after when switching content app
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
Labels: release/13.6.0

#17924 Build: Detect circular dependencies with Madge
  .github/workflows/test-backoffice.yml
  src/Umbraco.Web.UI.Client/devops/circular/index.js
  src/Umbraco.Web.UI.Client/package.json
Labels: area/frontend, internal, ignore-for-release

#17965 Link to content type and/or template from content/media/member info workspace view only if current user has access to settings
  src/Umbraco.Web.UI.Client/src/libs/extension-api/condition/condition-controller-arguments.type.ts
  src/Umbraco.Web.UI.Client/src/packages/core/section/conditions/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/core/section/conditions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/core/section/conditions/section-user-permission.condition.test.ts
  src/Umbraco.Web.UI.Client/src/packages/core/section/conditions/section-user-permission.condition.ts
  src/Umbraco.Web.UI.Client/src/packages/core/section/conditions/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/section/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/public-access/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/section/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/health-check/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-section/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/workspace/views/info/media-workspace-view-info.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/workspace/member/views/member/member-workspace-view-member-info.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/section/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/models-builder/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/packages/package-section/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/performance-profiling/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/publish-cache/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/search/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/settings/section/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/telemetry/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/menu/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/translation/section/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/user/current-user/profile/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/user/section/manifests.ts
  src/Umbraco.Web.UI.Client/utils/all-umb-consts/index.ts
Labels: area/frontend

#17986 Do not show "Save and preview" by default
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
Labels: release/13.6.0

#17988 Close modal for create options with links
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/common/create/modal/entity-create-option-action-list-modal.element.ts
Labels: type/bug, area/frontend, release/15.2.0

#17990 Fix: Do not re-map schedule modal on error as it leads to broken bindings
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
Labels: area/frontend

#16004 Remove __Key field from Backoffice Search if query is not a Guid
  src/Umbraco.Examine.Lucene/BackOfficeExamineSearcher.cs
Labels: community/pr, area/backend

#17982 Added a maxlength setting to the regular expression pattern field
  src/Umbraco.Web.UI.Client/src/less/components/umb-group-builder.less
  src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/propertysettings/propertysettings.html
Labels: area/frontend, release/13.6.0

#17996 Feature: Data Type Folder workspace
  src/Umbraco.Web.UI.Client/src/packages/data-type/collection/index.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/collection/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/collection/repository/index.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/data-type-root/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/data-type-root/index.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/data-type-root/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/paths.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/tree/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/tree/folder/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/tree/folder/workspace/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/tree/folder/workspace/index.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/tree/folder/workspace/paths.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/tree/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/tree/tree-item-children/collection/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/tree/tree-item-children/collection/index.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/tree/tree-item-children/collection/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/tree/tree-item-children/collection/repository/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/tree/tree-item-children/collection/repository/data-type-tree-item-children-collection.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/tree/tree-item-children/collection/repository/index.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/tree/tree-item-children/collection/repository/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/tree/tree-item-children/collection/types.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/tree/tree-item-children/collection/views/data-type-tree-item-table-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/tree/tree-item-children/collection/views/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/tree/tree-item-children/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/tree/tree-item-children/manifests.ts
  src/Umbraco.Web.UI.Client/utils/all-umb-consts/index.ts
Labels: category/ux, type/feature, area/frontend

#18008 Fix: Empty groups appear in block grid editor Add content UI
  src/Umbraco.Web.UI.Client/src/packages/block/block/modals/block-catalogue/block-catalogue-modal.element.ts
Labels: area/frontend

#18010 Feature: Create button in Document Type Folder collection
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/tree/tree-item-children/collection/action/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/tree/tree-item-children/collection/manifests.ts
Labels: category/ux, type/feature, area/frontend, release/15.2.0

#18011 V15: Current User Group Id Condition
  src/Umbraco.Cms.Api.Management/Factories/UserPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/ViewModels/User/Current/CurrentUserResponseModel.cs
  src/Umbraco.Web.UI.Client/src/external/backend-api/src/types.gen.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/user/user.db.ts
  src/Umbraco.Web.UI.Client/src/packages/core/utils/string/string-or-string-array-contains/string-or-string-array-contains.function.ts
  src/Umbraco.Web.UI.Client/src/packages/user/current-user/conditions/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/user/current-user/conditions/group-id/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/user/current-user/conditions/group-id/group-id.condition-config.ts
  src/Umbraco.Web.UI.Client/src/packages/user/current-user/conditions/group-id/group-id.condition.manifest.ts
  src/Umbraco.Web.UI.Client/src/packages/user/current-user/conditions/group-id/group-id.condition.ts
  src/Umbraco.Web.UI.Client/src/packages/user/current-user/conditions/group-id/types.ts
  src/Umbraco.Web.UI.Client/src/packages/user/current-user/conditions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/user/current-user/conditions/types.ts
  src/Umbraco.Web.UI.Client/src/packages/user/current-user/repository/current-user.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/user/current-user/types.ts
  src/Umbraco.Web.UI.Client/utils/all-umb-consts/index.ts
Labels: type/feature, area/frontend, release/15.2.0

#18016 First document at root should not have special meaning when routing
  src/Umbraco.Core/Services/DocumentUrlService.cs
Labels: area/backend

#18021 Fix: Improve sorter placement algorithm
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entries/block-grid-entries.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-type-configuration/property-editor-ui-block-grid-type-configuration.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-type/components/input-block-type/input-block-type.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/common/create/modal/entity-create-option-action-list-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/modal/common/confirm/confirm-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/sorter/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/sorter/replacement-resolver-as-grid.function.ts
  src/Umbraco.Web.UI.Client/src/packages/core/sorter/sorter.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-media/input-media.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
Labels: category/ux, area/frontend, release/15.2.0

#17942 Lucene Package Update to Address CVE-2024-43383
  Directory.Packages.props
  src/Umbraco.Examine.Lucene/Umbraco.Examine.Lucene.csproj
Labels: area/backend

#17818 Allow skipSelect blueprints only when one blueprint exists
  src/Umbraco.Web.UI.Client/src/views/content/content.create.controller.js
Labels: community/pr, type/bug, area/frontend, release/13.6.0

#18013 V15: "New version available" text is not reverified after an upgrade
  src/Umbraco.Web.UI.Client/src/apps/backoffice/backoffice.context.ts
  src/Umbraco.Web.UI.Client/src/apps/backoffice/components/backoffice-header-logo.element.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/server.handlers.ts
  src/Umbraco.Web.UI.Client/src/packages/sysinfo/components/new-version.element.ts
  src/Umbraco.Web.UI.Client/src/packages/sysinfo/modals/new-version-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/sysinfo/repository/sysinfo.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/sysinfo/types.ts
Labels: type/bug, area/frontend

#17778 17760 - improved the Norwegian lang file
  src/Umbraco.Web.UI.Client/src/assets/lang/nb-no.ts
Labels: community/pr, area/frontend, type/improvement, release/15.2.0

#17970 Fixes bug change focal point of Image Cropper can not save image
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/image-cropper-focus-setter.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/input-image-cropper.element.ts
Labels: area/frontend

#18029 Allow for filtering of document type allowed children and allowed at root when creating new content.
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Collections.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Core/Services/ContentTypeService.cs
  src/Umbraco.Core/Services/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
  src/Umbraco.Core/Services/Filters/ContentTypeFilterCollection.cs
  src/Umbraco.Core/Services/Filters/ContentTypeFilterCollectionBuilder.cs
  src/Umbraco.Core/Services/Filters/IContentTypeFilter.cs
  src/Umbraco.Core/Services/MediaTypeService.cs
  src/Umbraco.Core/Services/MemberTypeService.cs
Labels: status/needs-docs, area/backend

#17936 v15: Remove old values from checkboxlist
  src/Umbraco.Core/PropertyEditors/RadioValueEditor.cs
  src/Umbraco.Core/PropertyEditors/Validators/MultipleValueValidator.cs
  src/Umbraco.Core/PropertyEditors/Validators/RadioValueValidator.cs
  src/Umbraco.Infrastructure/PropertyEditors/MultipleValueEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/RadioButtonsPropertyEditor.cs
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/data-type/data-type.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/document-type/document-type.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/document/document.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/utils/entity/entity-detail.manager.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/document/publishing.handlers.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/input-radio-button-list/input-radio-button-list.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/checkbox-list/components/input-checkbox-list/input-checkbox-list.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/checkbox-list/property-editor-ui-checkbox-list.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/dropdown/property-editor-ui-dropdown.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/radio-button-list/property-editor-ui-radio-button-list.element.ts
Labels: type/bug, area/frontend

#17994 V15: Link Picker Modal UX Flow
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/link-picker-modal/link-picker-modal.element.ts
Labels: category/ux, type/feature, area/frontend, release/15.2.0

#18041 V15: Main entity name field lacks placeholder and auto-focus
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-split-view/workspace-split-view-variant-selector.element.ts
Labels: type/bug, area/frontend

#17828 Health Check items "back to overview" link omits backoffice url segment
  src/Umbraco.Web.UI.Client/src/packages/health-check/views/health-check-group.element.ts
Labels: area/frontend

#17637 Fix create child issue in list view with infinite editor (#13355).
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js
Labels: area/frontend, affected/v13

#18033 Updated the dialog label for the Member Group Picker.
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-group/components/member-group-picker-modal/member-group-picker-modal.element.ts
Labels: area/frontend, affected/v15

#18034 Updated the dialog label for the User Picker label
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/modals/user-picker/user-picker-modal.element.ts
Labels: area/frontend, affected/v15

#18050 updated the modal headline
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-picker-modal/tree-picker-modal.element.ts
Labels: area/frontend, affected/v15

#17373 Replaced deprecated navigator.platform with navigator.userAgent for platform detection.
  src/Umbraco.Web.UI.Client/src/views/common/drawers/help/help.controller.js
Labels: hacktoberfest-accepted, area/frontend, hacktoberfest/contrib-2024, release/13.7.0

#18037 Updated the dialog label for the User - Assign Access - Groups
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user-group/modals/user-group-picker/user-group-picker-modal.element.ts
Labels: category/ux, area/frontend, release/15.3.0

#18060 Localize the recycle bin tree root
  src/Umbraco.Web.UI.Client/src/packages/media/media/recycle-bin/tree/media-recycle-bin-tree.repository.ts
Labels: area/frontend

#18051 Sets `max-height` for Workspace Variant Selector scroll container
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-split-view/workspace-split-view-variant-selector.element.ts
Labels: type/bug, area/frontend

#18053 Fixes rendering of the font icons used for buttons in the code editor.
  src/Umbraco.Web.UI.Client/src/css/umb-css.css
  src/Umbraco.Web.UI.Client/src/rollup.config.js
Labels: category/ux, area/frontend, release/15.3.0

#18022 Fix settings value begin indifference (17989)
  src/Umbraco.Web.UI.Client/src/packages/block/block/context/block-entry.context.ts
Labels: area/frontend

#18038 Fix: Block validation (Refactor of context-api proxy from Clipboard Feature)
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/clipboard/block/copy/block-grid-to-block-copy-translator.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/clipboard/grid-block/copy/block-grid-to-grid-block-copy-translator.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-block-inline/block-grid-block-inline.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/context/block-grid-entry.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-value-cloner/property-value-cloner-block-grid.cloner.test.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-value-cloner/property-value-cloner-block-grid.cloner.ts
  src/Umbraco.Web.UI.Client/src/packages/clipboard/property/context/clipboard.property-context-token.ts
  src/Umbraco.Web.UI.Client/src/packages/clipboard/property/context/clipboard.property-context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/context/validation-messages.manager.test.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/submittable/submittable-workspace-context-base.ts
Labels: category/ux, type/bug, area/frontend, release/15.2.0

#17991 Numeric property editor range and misconfiguration validation
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/number/property-editor-ui-number.element.ts
Labels: area/frontend

#18063 Handles migration case where an expected constraint is renamed but the constraint does not exist
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_13_3_0/AlignUpgradedDatabase.cs
Labels: area/backend, release/13.7.0

#18089 Add clientside validation to webhook events
  src/Umbraco.Web.UI.Client/src/views/webhooks/edit.controller.js
  src/Umbraco.Web.UI.Client/src/views/webhooks/edit.html
Labels: release/13.7.0

#18106 V15/bugfix/Reset image crop button fix
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/image-cropper.element.ts
Labels: area/frontend, affected/v15

#18114 Redirect to the published URL when exiting preview
  src/Umbraco.Web.BackOffice/Controllers/PreviewController.cs
Labels: release/13.7.0

#18043 Updated the dialog label for User -> Assign Access -> Media Start nodes
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
Labels: category/ux, area/frontend, release/15.3.0

#18059 updated the link picker modal and the property editors using it.
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/components/input-multi-url/input-multi-url.element.ts
  src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/link-picker-modal/link-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/link-picker-modal/link-picker-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/monaco-markdown-editor-action/url-picker-monaco-markdown-editor-action.ts
  src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/tiny-mce-plugin/tiny-mce-multi-url-picker.plugin.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/link.tiptap-toolbar-api.ts
Labels: category/ux, area/frontend, release/15.3.0

#18123 Feature: Code Editor modal, adds pretty-print support
  src/Umbraco.Web.UI.Client/src/packages/code-editor/code-editor-modal/code-editor-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/code-editor/code-editor-modal/code-editor-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/source-editor.tiptap-toolbar-api.ts
Labels: type/feature, area/frontend

#18118 Bugfix: Align collection item entity actions with menu item entity actions
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/global-components/entity-actions-table-column-view/entity-actions-table-column-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/tree/tree-item-children/collection/views/data-type-tree-item-table-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/tree/tree-item-children/collection/views/document-type-tree-item-table-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/views/table/document-table-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/extension-insights/collection/views/table/extension-table-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/language/collection/views/table/language-table-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/tree/tree-item-children/collection/views/media-type-tree-item-table-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/collection/views/table/media-table-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-group/collection/views/table/member-group-table-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/collection/views/table/member-table-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user-group/collection/views/user-group-table-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/collection/views/table/user-table-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/webhook/collection/views/table/webhook-table-collection-view.element.ts
Labels: category/ux, type/bug, area/frontend, release/15.3.0

#18124 Feature: Tiptap: Generic markup support
  src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-div.extension.ts
  src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-html-global-attributes.extension.ts
  src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-span.extension.ts
  src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-umb-embedded-media.extension.ts
  src/Umbraco.Web.UI.Client/src/external/tiptap/index.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/rich-text-essentials.tiptap-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/tiptap.extension.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/components/property-editor-ui-tiptap-extensions-configuration.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/property-editor-ui-tiptap.element.ts
Labels: type/feature, area/frontend, release/15.3.0

#18131 Refreshed display of check results after all checks are complete
  src/Umbraco.Web.UI.Client/src/packages/health-check/health-check-dashboard.context.ts
  src/Umbraco.Web.UI.Client/src/packages/health-check/views/health-check-group.element.ts
  src/Umbraco.Web.UI.Client/src/packages/health-check/views/health-check-overview.element.ts
Labels: area/frontend

#18113 V15: Media library crashes when uploading large files
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Web.UI.Client/src/mocks/data/media-type/media-type.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/media-type/media-type.db.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/media-type/item.handlers.ts
  src/Umbraco.Web.UI.Client/src/packages/core/repository/data-source-response.interface.ts
  src/Umbraco.Web.UI.Client/src/packages/core/resources/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/resources/resource.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/resources/tryXhrRequest.function.ts
  src/Umbraco.Web.UI.Client/src/packages/core/resources/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/components/temporary-file-badge.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/temporary-file-manager.class.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/temporary-file.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/temporary-file.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/collection/media-collection.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/collection/views/grid/media-grid-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/dropzone-manager.class.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/dropzone-submitted.event.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/dropzone.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/index.ts
  src/Umbraco.Web.UI.Client/src/packages/tiny-mce/plugins/tiny-mce-mediapicker.plugin.ts
Labels: type/bug, area/frontend

#18108 Fix: Mandatory for Image Cropper (17372)
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/input-image-cropper.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/image-cropper/property-editor-ui-image-cropper.element.ts
Labels: area/frontend

#18095 V13: remove unused parameters and documentation
  src/Umbraco.Web.UI.Client/src/common/services/assets.service.js
Labels: category/api-documentation, area/frontend

#18141 V16: Allow `MaxRequestLength` to be specified as a long
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/TemporaryFile/TemporaryFileConfigurationResponseModel.cs
  src/Umbraco.Core/Configuration/Models/RuntimeSettings.cs
Labels: category/breaking, type/feature, area/frontend, release/16.0.0

#18136 Fixes rollback of variant page name
  src/Umbraco.Core/Models/ContentRepositoryExtensions.cs
Labels: area/backend

#18042 Bugfix: Content Picker Search - support allowed content types config
  src/Umbraco.Cms.Api.Management/Controllers/Document/Item/SearchDocumentItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Media/Item/SearchMediaItemController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Member/Item/SearchMemberItemController.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Core/Services/IIndexedEntitySearchService.cs
  src/Umbraco.Examine.Lucene/BackOfficeExamineSearcher.cs
  src/Umbraco.Infrastructure/Examine/IBackOfficeExamineSearcher.cs
  src/Umbraco.Infrastructure/Services/Implement/IndexedEntitySearchService.cs
  src/Umbraco.Web.UI.Client/src/external/backend-api/src/sdk.gen.ts
  src/Umbraco.Web.UI.Client/src/external/backend-api/src/types.gen.ts
  src/Umbraco.Web.UI.Client/src/packages/core/picker/search/manager/picker-search.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-picker-modal/tree-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/components/input-document/input-document.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/components/input-document/input-document.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/search/document-search.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/search/document-search.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/search/document.search-provider.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/search/types.ts
  src/Umbraco.Web.UI.Client/src/packages/markdown-editor/components/input-markdown-editor/input-markdown.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-media/input-media.context.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-media/input-media.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/modals/image-cropper-editor/image-cropper-editor-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/media-picker-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/media-picker/property-editor-ui-media-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/search/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/search/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/search/media-search.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/search/media-search.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/search/media.search-provider.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/search/types.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/components/input-member/input-member.context.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/components/input-member/input-member.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/components/member-picker-modal/member-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/components/member-picker-modal/member-picker-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/search/member-search.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/search/member-search.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/search/member.search-provider.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/search/types.ts
  src/Umbraco.Web.UI.Client/src/packages/search/search-data-source.interface.ts
  src/Umbraco.Web.UI.Client/src/packages/search/search-repository.interface.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/media-picker.tiptap-toolbar-api.ts
  tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/BackOfficeExamineSearcherTests.cs
Labels: category/ux, type/feature, area/frontend, area/backend

#18076 Set document to readonly when a user is not allowed to create / update
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content/workspace/content-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-split-view/workspace-split-view-variant-selector.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish-with-descendants/workspace-action/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/schedule-publish/workspace-action/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/unpublish/workspace-action/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/user-permissions/conditions/document-user-permission.condition.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/actions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/actions/save.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/manifests.ts
Labels: category/ux, type/bug, release/15.3.0

#18120 Pass user Id to audit when saving and deleting members
  src/Umbraco.Core/Services/MemberService.cs
Labels: area/backend

#18145 Added Resharper test assemblies to exclude list on TypeFinder
  src/Umbraco.Core/Composing/TypeFinder.cs
Labels: area/backend

#18080 Elements level property cache should cache by variation
  src/Umbraco.Core/PublishedCache/PublishedElement.cs
  src/Umbraco.Core/PublishedCache/PublishedElementPropertyBase.cs
  src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/BlockEditorConverter.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/BlockListElementLevelVariationTests.Publishing.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/CacheTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ContentBuilderTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ContentPickerValueConverterTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/MultiNodeTreePickerValueConverterTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/OutputExpansionStrategyTestBase.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/PropertyValueConverterTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/RichTextParserTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/ConvertersTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Published/ConvertersTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Published/PropertyCacheLevelTests.cs
Labels: release/15.2.0

#18148 V15: Show upload progress for dropped files in the Media Library
  src/Umbraco.Web.UI.Client/src/mocks/data/data-type/data-type.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/media-type/media-type.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/media-type/media-type.db.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/media/media.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/media/detail.handlers.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/media/imaging.handlers.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/media/index.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/media/tree.handlers.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/temporary-file/temporary-file.handlers.ts
  src/Umbraco.Web.UI.Client/src/packages/core/resources/tryXhrRequest.function.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/components/temporary-file-badge.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/temporary-file-manager.class.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/temporary-file.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/types.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/collection/media-collection.context.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/collection/media-collection.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/collection/types.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/collection/views/grid/media-grid-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/dropzone-manager.class.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/dropzone.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/types.ts
Labels: category/ux, type/feature, area/frontend, release/15.3.0

#18081 Provides an option to remove the inessential version number from the generated models
  src/Umbraco.Core/Configuration/Models/ModelsBuilderSettings.cs
  src/Umbraco.Infrastructure/ModelsBuilder/Building/TextBuilder.cs
Labels: area/backend

#18072 V15: Fix Url Preview
  src/Umbraco.Cms.Api.Management/Factories/DocumentUrlFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/IDocumentUrlFactory.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Core/Routing/IPublishedUrlInfoProvider.cs
  src/Umbraco.Core/Routing/PublishedUrlInfoProvider.cs
  src/Umbraco.Core/Services/DocumentUrlService.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentUrlServiceTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentUrlServiceTest_hidetoplevel_false.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/PublishedUrlInfoProviderTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/PublishedUrlInfoProviderTestsBase.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/PublishedUrlInfoProvider_hidetoplevel_false.cs
  tests/Umbraco.Tests.Integration/Umbraco.Tests.Integration.csproj
Labels: area/backend

#18163 V15: Client should validate maxFileSize and allowed/disallowed file types from server configuration
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/temporary-file/temporary-file.handlers.ts
  src/Umbraco.Web.UI.Client/src/packages/core/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/core/notification/layouts/default/notification-layout-default.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/notification/notification.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/config/config.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/config/config.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/config/config.store.token.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/config/config.store.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/config/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/config/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/config/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/temporary-file-manager.class.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/utils/bytes/bytes.function.ts
  src/Umbraco.Web.UI.Client/src/packages/core/utils/bytes/bytes.test.ts
  src/Umbraco.Web.UI.Client/src/packages/core/utils/index.ts
  src/Umbraco.Web.UI.Client/utils/all-umb-consts/index.ts
Labels: category/ux, type/feature, area/frontend, release/15.3.0

#18094 Bugfix: show notification when offline
  src/Umbraco.Web.UI.Client/src/apps/app/app.context.ts
  src/Umbraco.Web.UI.Client/src/apps/app/network-connection-status.manager.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
Labels: category/ux, area/frontend, release/15.3.0

#18179 Fixed name of True/False property editor schema manifest
  src/Umbraco.Web.UI.Client/src/packages/property-editors/toggle/Umbraco.TrueFalse.ts
Labels: area/frontend

#18149 V15 QA added fixes for flaky/failing acceptance tests
  tests/Umbraco.Tests.AcceptanceTest/package-lock.json
  tests/Umbraco.Tests.AcceptanceTest/package.json
  tests/Umbraco.Tests.AcceptanceTest/tests/ApiTesting/User/User.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ChildrenContent.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ContentInfoTab.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ContentWithDocumentTypeProperties/ContentWithAllowedChildNodes.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ContentWithDocumentTypeProperties/ContentWithCollections.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ContentWithImageCropper.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ContentWithImageMediaPicker.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ContentWithMediaPicker.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ContentWithMultiURLPicker.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ContentWithMultipleImageMediaPicker.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ContentWithMultipleMediaPicker.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ContentWithTiptap.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/CultureAndHostnames.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/BlockGrid/BlockGridEditor.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/BlockListEditor/BlockListEditor.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/DataType.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/DataTypeFolder.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/ListView.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/MediaPicker.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/TinyMCE.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/Tiptap.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/Upload.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Dictionary/Dictionary.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/LogViewer/LogViewer.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Media/ListViewMedia.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Media/Media.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Members/MemberGroups.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Packages/PackagesPackages.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RelationTypes/RelationTypes.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/DocumentType/DocumentTypeDesignTab.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/DocumentType/DocumentTypeSettingsTab.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/MediaType/MediaTypeDesignTab.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/PartialView/PartialView.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/Script/ScriptFolder.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/Stylesheet/StylesheetFolder.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/Template/Templates.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Users/Permissions/UserGroup/ContentWithTinyMCERichTextEditor.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Users/Permissions/UserGroup/DefaultPermissionsInContent.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Users/User.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Users/UserGroups.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/auth.setup.ts
Labels: area/test

#18144 Don't assume HtmlString when inserting default values in templates
  src/Umbraco.Web.UI.Client/src/packages/templating/utils/index.ts
Labels: area/frontend

#18183 Hotfix: Clipboard confirm delete labels
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/libs/localization-api/localization.controller.test.ts
  src/Umbraco.Web.UI.Client/src/libs/localization-api/localization.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/clipboard/clipboard-entry/detail/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/common/delete/delete.action.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/common/delete/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/sorter/sorter.controller.test.ts
  src/Umbraco.Web.UI.Client/utils/all-umb-consts/index.ts
Labels: category/ux, area/frontend

#18176 Use variant context for determining requested culture
  src/Umbraco.Cms.Api.Delivery/Querying/QueryOptionBase.cs
  src/Umbraco.Cms.Api.Delivery/Querying/Selectors/AncestorsSelector.cs
  src/Umbraco.Cms.Api.Delivery/Querying/Selectors/ChildrenSelector.cs
  src/Umbraco.Cms.Api.Delivery/Querying/Selectors/DescendantsSelector.cs
  src/Umbraco.Core/DeliveryApi/ApiPublishedContentCache.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/PublishedContentCacheTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/Selectors/AncestorsSelectorTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/Selectors/ChildrenSelectorTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/Selectors/DescendantsSelectorTests.cs
Labels: area/backend

#18162 Feature: hide icons
  src/Umbraco.Web.UI.Client/devops/icons/index.js
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icon-dictionary.json
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icon-registry.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-clipboard-copy.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-clipboard-entry.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-clipboard-paste.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-clipboard.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-puzzle-piece.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/types.ts
Labels: area/frontend

#18154 Rollback as entity action + Picker data updates
  src/Umbraco.Web.UI.Client/src/packages/core/content/workspace/content-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/entity-action.event.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/entity-updated.event.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/repository/repository-items.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/entity-detail/entity-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/rollback/entity-action/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/rollback/modal/rollback-modal.element.ts
Labels: category/ui, type/bug, area/frontend, release/15.3.0

#18159 User Group picker modal: adds filter input
  src/Umbraco.Web.UI.Client/src/packages/user/user-group/modals/user-group-picker/user-group-picker-modal.element.ts
Labels: area/frontend

#17881 Ensure min/max property editor settings are valid before rendering for content editing
  src/Umbraco.Web.UI.Client/src/packages/core/components/input-slider/input-slider.element.ts
  src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/property-editor/property-editor-ui-multi-url-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/property-editor-ui-content-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/multiple-text-string/property-editor-ui-multiple-text-string.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/number/property-editor-ui-number.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/slider/property-editor-ui-slider.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/textarea/property-editor-ui-textarea.element.ts
Labels: area/frontend

#18075 Tiptap RTE: Add CSS support for extensions
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/base.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/embedded-media.tiptap-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/image.tiptap-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/table.tiptap-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/types.ts
Labels: type/feature, area/frontend, release/15.3.0

#18158 V15/sort by selected icons
  src/Umbraco.Web.UI.Client/src/packages/core/tree/entity-actions/sort-children-of/modal/sort-children-of-modal.element.ts
Labels: category/ux, area/frontend

#18160 More robust resolving of Delivery API redirects
  src/Umbraco.Cms.Api.Delivery/Services/RequestRedirectService.cs
Labels: area/backend

#17421 Fix out of memory file upload of 2gb+ files introduced by #14657 SVG xss
  src/Umbraco.Web.BackOffice/Controllers/MediaController.cs
Labels: area/backend, release/13.7.0

#18192 Update auth.element.ts
  src/Umbraco.Web.UI.Login/src/auth.element.ts
Labels: release/13.7.0

#18048 Less parsing, allocation & LINQ when splitting strings
  src/Umbraco.Core/DynamicRoot/Origin/SiteDynamicRootOriginFinder.cs
  src/Umbraco.Core/Extensions/StringExtensions.cs
  src/Umbraco.Core/Extensions/TreeEntityExtensions.cs
  src/Umbraco.Core/Models/PropertyTagsExtensions.cs
  src/Umbraco.Core/Services/LocalizedTextServiceExtensions.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Extensions/TreeEntityExtensionsTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/ShortStringHelper/StringExtensionsTests.cs
Labels: community/pr, area/backend, release/15.3.0

#17090 v14: Async healthchecks
  src/Umbraco.Cms.Api.Management/Controllers/HealthCheck/ExecuteActionHealthCheckController.cs
  src/Umbraco.Cms.Api.Management/Controllers/HealthCheck/Group/CheckHealthCheckGroupController.cs
  src/Umbraco.Cms.Api.Management/Factories/HealthCheckGroupPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/IHealthCheckGroupPresentationFactory.cs
  src/Umbraco.Core/HealthChecks/Checks/AbstractSettingsCheck.cs
  src/Umbraco.Core/HealthChecks/Checks/Data/DatabaseIntegrityCheck.cs
  src/Umbraco.Core/HealthChecks/Checks/Permissions/FolderAndFilePermissionsCheck.cs
  src/Umbraco.Core/HealthChecks/Checks/Security/BaseHttpHeaderCheck.cs
  src/Umbraco.Core/HealthChecks/Checks/Security/ExcessiveHeadersCheck.cs
  src/Umbraco.Core/HealthChecks/Checks/Security/HstsCheck.cs
  src/Umbraco.Core/HealthChecks/Checks/Security/HttpsCheck.cs
  src/Umbraco.Core/HealthChecks/Checks/Security/UmbracoApplicationUrlCheck.cs
  src/Umbraco.Core/HealthChecks/Checks/Services/SmtpCheck.cs
  src/Umbraco.Core/HealthChecks/HealthCheck.cs
  src/Umbraco.Core/HealthChecks/HealthCheckResults.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/BackgroundJobs/Jobs/HealthCheckNotifierJobTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/HealthChecks/HealthCheckResultsTests.cs
Labels: area/backend

#18190 V15/feature/notification-whitespace
  src/Umbraco.Web.UI.Client/src/packages/core/notification/layouts/default/notification-layout-default.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/notification/notification.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/temporary-file-manager.class.ts
Labels: category/ui, type/feature, area/frontend, release/15.3.0
