Repository umbraco/Umbraco-CMS, pull requests merged in 2025-05, with the labels that each got.

#19199 Reposition workspace entity actions
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/global-components/content-type-workspace-editor-header.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/body-layout/body-layout.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-editor/workspace-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-entity-action-menu/workspace-entity-action-menu.element.ts
  src/Umbraco.Web.UI.Client/src/packages/webhook/webhook/workspace/webhook-workspace-editor.element.ts
  tests/Umbraco.Tests.AcceptanceTest/package-lock.json
  tests/Umbraco.Tests.AcceptanceTest/package.json
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Members/MemberGroups.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Members/Members.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Users/UserGroups.spec.ts
Labels: category/ux, release/16.0.0

#19203 Preview segment
  src/Umbraco.Web.UI.Client/src/apps/preview/apps/manifests.ts
  src/Umbraco.Web.UI.Client/src/apps/preview/apps/preview-segment.element.ts
  src/Umbraco.Web.UI.Client/src/apps/preview/preview.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace.context.ts
Labels: type/feature, area/frontend, release/16.0.0

#19215 Fix filter logic
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/components/input-document-type/input-document-type.element.ts
Labels: release/16.0.0, ignore-for-release

#19204 Changed the Image crop UI component to fit the new Backoffice UI design
  src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/image-cropper/Umbraco.ImageCropper.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/image-crops/property-editor-ui-image-crops.element.ts
Labels: category/ui, type/feature, area/frontend, release/16.1.0

#19216 Fix root path regression for the Delivery API
  src/Umbraco.Core/DeliveryApi/ApiContentPathResolver.cs
  src/Umbraco.Core/DeliveryApi/IApiContentPathResolver.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ApiContentPathResolverTests.cs
Labels: release/13.9.0

#19087 Tiptap cannot set the top position of the toolbar
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/tiptap-toolbar.element.ts
Labels: community/pr, type/bug, area/frontend, release/16.1.0

#17051 Clean up extension methods
  src/Umbraco.Core/Cache/AppCaches.cs
  src/Umbraco.Core/Cache/AppPolicedCacheDictionary.cs
  src/Umbraco.Core/Cache/DeepCloneAppCache.cs
  src/Umbraco.Core/Composing/ComponentCollection.cs
  src/Umbraco.Core/DynamicRoot/QuerySteps/FurthestAncestorOrSelfDynamicRootQueryStep.cs
  src/Umbraco.Core/DynamicRoot/QuerySteps/NearestAncestorOrSelfDynamicRootQueryStep.cs
  src/Umbraco.Core/Extensions/AssemblyExtensions.cs
  src/Umbraco.Core/Extensions/CollectionExtensions.cs
  src/Umbraco.Core/Extensions/DataTableExtensions.cs
  src/Umbraco.Core/Extensions/DelegateExtensions.cs
  src/Umbraco.Core/Extensions/DictionaryExtensions.cs
  src/Umbraco.Core/Extensions/EnumExtensions.cs
  src/Umbraco.Core/Extensions/KeyValuePairExtensions.cs
  src/Umbraco.Core/Extensions/NameValueCollectionExtensions.cs
  src/Umbraco.Core/Extensions/ObjectExtensions.cs
  src/Umbraco.Core/Extensions/PublishedContentExtensions.cs
  src/Umbraco.Core/Extensions/StringExtensions.cs
  src/Umbraco.Core/Extensions/ThreadExtensions.cs
  src/Umbraco.Infrastructure/Logging/Serilog/SerilogLogger.cs
  src/Umbraco.Infrastructure/Persistence/Factories/UserFactory.cs
  src/Umbraco.Web.Common/Extensions/FriendlyPublishedContentExtensions.cs
  src/Umbraco.Web.Common/Security/EncryptionHelper.cs
  tests/Umbraco.Tests.Integration/Testing/UmbracoIntegrationTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/BackOfficeExamineSearcherTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Examine.Lucene/UmbracoExamine/ExamineExternalIndexTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/CoreThings/ObjectExtensionsTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DelegateExtensionsTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/PublishedCache/PublishedContentDataTableTests.cs
Labels: category/breaking, area/backend, release/17.0.0

#19229 Revert #16058 for non-applicable settings
  src/Umbraco.Core/Configuration/Models/DeliveryApiSettings.cs
  src/Umbraco.Core/Configuration/Models/RequestHandlerSettings.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Configuration/Models/RequestHandlerSettingsTests.cs
Labels: status/regression, release/16.0.0

#18427 Fix: #18421 - Added Max Length validation to PropertyTypeBasic Alias
  src/Umbraco.Core/Models/ContentEditing/PropertyTypeBasic.cs
  src/Umbraco.Web.UI.Client/src/views/components/umb-locked-field.html
Labels: community/pr, area/backend

#18412 Create Localization Contributing Documentation
  .github/contributing-localization.md
  .github/img/contributing/ProfileImage.png
  .github/img/contributing/actionAndKeys.png
  .github/img/contributing/changedBackofficeAfterLocalization.png
  .github/img/contributing/editBtn.png
  .github/img/contributing/finishedManifestAfterLocalizatonChanges.png
  .github/img/contributing/localizationCodeSnippetInCode.png
  .github/img/contributing/renderCode.png
  .github/img/contributing/searchInVsCode.png
  .github/img/contributing/searchingThroughLanguageFiles.png
  .github/img/contributing/uiCulture.png
Labels: category/dx

#19217 V16 RC: getOpenApiConfiguration().token does not work
  src/Umbraco.Web.UI.Client/src/packages/core/auth/auth.context.ts
  templates/UmbracoExtension/Client/package.json
  templates/UmbracoExtension/Client/src/dashboards/dashboard.element.ts
  templates/UmbracoExtension/Client/src/entrypoints/entrypoint.ts
Labels: area/frontend, release/16.0.0-rc2

#19237 V16: Main language dropdown does not scroll
  src/Umbraco.Web.UI.Client/src/packages/language/app-language-select/app-language-select.element.ts
Labels: type/bug, area/frontend

#19240 V16: Block selector is limited to 100 blocks
  src/Umbraco.Web.UI.Client/src/packages/data-type/modals/data-type-picker-flow/data-type-picker-flow-data-type-picker-modal.element.ts
Labels: area/frontend, release/16.0.0-rc2

#19259 Log language ISO codes instead of language names
  src/Umbraco.Core/Services/ContentService.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentServiceTests.cs
Labels: category/breaking, type/bug, release/16.0.0

#19260 Handle null for retrieval of content section in unit tests
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Collections.cs
Labels: ignore-for-release

#19258 V16: Localization refinements
  src/Umbraco.Web.UI.Client/src/assets/lang/cs.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/cy.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/da.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/de-ch.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/de.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/es.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/fr-ch.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/fr.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/he.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/hr.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/it-ch.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/it.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/ja.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/ko.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/nb.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/nl.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/pl.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/pt-br.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/pt.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/ro.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/ru.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/sv.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/tr.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/uk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/zh.ts
  src/Umbraco.Web.UI.Client/src/packages/core/localization/components/ui-culture-input/ui-culture-input.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/localization/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/workspace/user/components/user-workspace-profile-settings/user-workspace-profile-settings.element.ts
  tests/Umbraco.Tests.AcceptanceTest/package-lock.json
  tests/Umbraco.Tests.AcceptanceTest/package.json
Labels: category/localization, area/frontend, release/16.0.0, release/16.0.0-rc2

#19256 Chore: Update the list of allowed tags for jsdocs
  src/Umbraco.Web.UI.Client/eslint.config.js
Labels: area/frontend, ignore-for-release, release/16.1.0

#19271 Member Type Root Collection View / Workspace
  src/Umbraco.Web.UI.Client/src/packages/core/collection/action/create/collection-create-action.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/entity-actions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/entity.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/index.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/member-type-root/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/member-type-root/index.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/member-type-root/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/tree/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/tree/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/tree/tree-item-children/collection/action/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/tree/tree-item-children/collection/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/tree/tree-item-children/collection/index.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/tree/tree-item-children/collection/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/tree/tree-item-children/collection/repository/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/tree/tree-item-children/collection/repository/index.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/tree/tree-item-children/collection/repository/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/tree/tree-item-children/collection/repository/member-type-tree-item-children-collection.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/tree/tree-item-children/collection/types.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/tree/tree-item-children/collection/views/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/tree/tree-item-children/collection/views/member-type-tree-item-table-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/tree/tree-item-children/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/tree/tree-item-children/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/tree/tree-item-children/reload-entity-action/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/workspace/index.ts
Labels: type/feature, area/frontend, release/16.1.0

#19233 Batch item rest requests
  src/Umbraco.Web.UI.Client/src/packages/core/entity-item/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-item/item-data-api-get-request-controller/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-item/item-data-api-get-request-controller/item-data-api-get-request.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-item/item-data-api-get-request-controller/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-item/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/repository/item/item-server-data-source-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/resources/data-api/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/resources/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/resources/try-execute/batch-try-execute.function.ts
  src/Umbraco.Web.UI.Client/src/packages/core/resources/try-execute/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/resources/try-execute/try-execute.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/resources/try-execute/tryExecute.function.ts
  src/Umbraco.Web.UI.Client/src/packages/core/resources/try-execute/tryExecuteAndNotify.function.ts
  src/Umbraco.Web.UI.Client/src/packages/core/resources/try-execute/tryXhrRequest.function.ts
  src/Umbraco.Web.UI.Client/src/packages/core/resources/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/utils/array/batch-array.test.ts
  src/Umbraco.Web.UI.Client/src/packages/core/utils/array/batch-array.ts
  src/Umbraco.Web.UI.Client/src/packages/core/utils/array/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/utils/index.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/repository/item/data-type-item.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/dictionary/repository/item/dictionary-item.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-blueprints/repository/item/document-blueprint-item.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/repository/item/document-type-item.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/item/repository/document-item.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/url/repository/document-url.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/language/repository/item/language-item.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/repository/item/media-type-item.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/repository/item/media-item.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/url/repository/media-url.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-group/repository/item/member-group-item.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/repository/item/member-type-item.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/item/repository/member-item.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/static-file/repository/item/static-file-item.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/templates/repository/item/template-item.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user-group/repository/item/user-group-item.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/repository/item/user-item.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/webhook/webhook/repository/item/webhook-item.server.data-source.ts
Labels: area/frontend, release/16.0.0, release/16.0.0-rc2

#19254 Fix #19221
  src/Umbraco.Web.UI.Client/examples/block-custom-view/block-custom-view.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/components/block-list-entry/block-list-entry.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-rte/components/block-rte-entry/block-rte-entry.element.ts
Labels: category/ux, type/bug, area/frontend, release/16.0.0, release/16.0.0-rc2

#19045 Added custom RichTextRegexValidator to validate markup instead of JSON
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/PropertyEditors/RichTextPropertyEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/Validators/IRichTextRegexValidator.cs
  src/Umbraco.Infrastructure/PropertyEditors/Validators/RichTextRegexValidator.cs
Labels: state/sprint-candidate

#19172 hotfix: Correct context tokens for menu structure based workspaces
  src/Umbraco.Web.UI.Client/eslint.config.js
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/workspace/content-type-workspace-context-base.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/content-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/collection/default/collection-default.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity/contexts/parent/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity/contexts/parent/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity/contexts/parent/parent.entity-context-token.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity/contexts/parent/parent.entity-context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/menu/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/menu/menu-structure-workspace-context.context-token.ts
  src/Umbraco.Web.UI.Client/src/packages/core/menu/menu-tree-structure-workspace-context-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/menu/menu-variant-structure-workspace-context.context-token.ts
  src/Umbraco.Web.UI.Client/src/packages/core/menu/menu-variant-structure-workspace-context.interface.ts
  src/Umbraco.Web.UI.Client/src/packages/core/menu/menu-variant-tree-structure-workspace-context-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/menu/section-sidebar-menu-with-entity-actions/section-sidebar-menu-with-entity-actions.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-base/tree-item-context-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-breadcrumb/workspace-menu-breadcrumb/workspace-menu-breadcrumb.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-breadcrumb/workspace-variant-menu-breadcrumb/workspace-variant-menu-breadcrumb.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/contexts/tokens/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/contexts/tokens/submittable-tree-entity-workspace-context.interface.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/contexts/tokens/submittable-tree-entity-workspace.context-token.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/entity-detail/entity-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/language/menu/language-menu-structure.context.ts
Labels: category/breaking, area/frontend, release/16.0.0, release/16.0.0-rc2

#19265 Enforce: allowEditInvariantFromNonDefault configuration in the Backoffice UI
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/property-dataset-context/document-property-dataset.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace.context.ts
Labels: category/ui, area/frontend, release/16.0.0, release/16.0.0-rc2

#19281 Improve active state check for menu and tree item
  src/Umbraco.Web.UI.Client/src/packages/core/menu/components/menu-item-layout/menu-item-layout.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-base/tree-item-context-base.ts
Labels: category/ux, type/bug, area/frontend, release/16.0.0, release/16.0.0-rc2

#19273 Invalidate external login session on removal of provider
  src/Umbraco.Core/Configuration/Models/SecuritySettings.cs
  src/Umbraco.Core/Extensions/IntExtensions.cs
  src/Umbraco.Core/Persistence/Repositories/IExternalLoginWithKeyRepository.cs
  src/Umbraco.Core/Persistence/Repositories/IUserRepository.cs
  src/Umbraco.Core/Services/ExternalLoginService.cs
  src/Umbraco.Core/Services/IExternalLoginWithKeyService.cs
  src/Umbraco.Core/Services/IUserService.cs
  src/Umbraco.Core/Services/UserService.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ExternalLoginRepository.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/UserRepository.cs
  src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilder.BackOfficeAuth.cs
  src/Umbraco.Web.BackOffice/NotificationHandlers/ExternalLoginProviderStartupHandler.cs
  src/Umbraco.Web.BackOffice/Security/BackOfficeExternalLoginProviders.cs
  src/Umbraco.Web.BackOffice/Security/IBackOfficeExternalLoginProviders.cs
  src/Umbraco.Web.Common/Security/ConfigureSecurityStampOptions.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Extensions/IntExtensionsTests.cs
Labels: area/backend

#19210 Align Create Document Blueprint label with other create labels
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/default/entity-action.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-blueprints/entity-actions/create/manifests.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/DocumentBlueprint/DocumentBlueprint.spec.ts
Labels: category/ux, area/frontend, release/16.0.0, release/16.0.0-rc2

#18073 add single blocklist delete
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js
Labels: area/frontend

#19291 Allow segment access to editors with access to documents, not only settings
  src/Umbraco.Cms.Api.Management/Controllers/Segment/AllSegmentController.cs
Labels: area/backend, ignore-for-release

#19305 Close dropdown after executed action workaround
  src/Umbraco.Web.UI.Client/src/packages/core/components/dropdown/dropdown.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/entity-actions-bundle/entity-actions-bundle.element.ts
Labels: type/bug, release/16.0.0, release/16.0.0-rc2

#19315 hotfix: #19299
  src/Umbraco.Web.UI.Client/src/libs/observable-api/states/array-state.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/structure/content-type-container-structure-helper.class.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/structure/content-type-structure-manager.class.ts
  src/Umbraco.Web.UI.Client/src/packages/core/repository/repository-details.manager.ts
Labels: ignore-for-release

#19106 Avoids unnecessary additional domain save notification publishing when sorting an already sorted collection of domains
  src/Umbraco.Core/Services/DomainService.cs
Labels: area/backend

#19277 Include property aliases in compatible composition check
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/modals/composition-picker/composition-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/modals/composition-picker/composition-picker-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/structure/content-type-structure-manager.class.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/workspace/views/design/content-type-design-editor.element.ts
Labels: type/bug, area/frontend, release/16.0.0, release/16.0.0-rc2

#19184 Adds support for retrieval of data type references when data type is routed using a GUID
  src/Umbraco.Web.BackOffice/Controllers/DataTypeController.cs
Labels: area/backend

#17901 User invite email fails if visited more than once without completing
  src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs
Labels: community/pr, category/ux, area/backend, release/13.9.0

#19324 hotfix: remove current user action look and color
  src/Umbraco.Web.UI.Client/src/packages/user/current-user/action/current-user-app-button.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/current-user/current-user-action.extension.ts
  src/Umbraco.Web.UI.Client/src/packages/user/current-user/external-login/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/user/current-user/mfa-login/manifests.ts
Labels: category/breaking, category/ui, category/front-end, area/frontend, release/16.0.0-rc3

#19006 Fix localiztion for buttons in pagination
  src/Umbraco.Web.UI.Client/src/packages/core/collection/components/pagination/collection-pagination.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-redirect-management/dashboard-redirect-management.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/audit-log/info-app/document-history-workspace-info-app.element.ts
  src/Umbraco.Web.UI.Client/src/packages/log-viewer/workspace/views/overview/components/log-viewer-message-templates-overview.element.ts
  src/Umbraco.Web.UI.Client/src/packages/log-viewer/workspace/views/overview/components/log-viewer-saved-searches-overview.element.ts
  src/Umbraco.Web.UI.Client/src/packages/log-viewer/workspace/views/search/components/log-viewer-messages-list.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/audit-log/info-app/media-history-workspace-info-app.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/packages/package-section/views/created/packages-created-overview.element.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relation-types/workspace/relation-type/views/relation-type-detail-workspace-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/reference/workspace-info-app/entity-references-workspace-view-info.element.ts
Labels: area/frontend

#19320 Fix Allow Edit Invariant config in split view
  src/Umbraco.Web.UI.Client/src/packages/block/block/workspace/views/edit/block-workspace-view-edit-properties.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block/workspace/views/edit/block-workspace-view-edit-property.element.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/views/edit/content-editor-properties.element.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/views/edit/content-editor-property.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/property-guard-manager/variant-property-guard.manager.test.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/property-guard-manager/variant-property-guard.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/property-dataset-context/document-property-dataset.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace.context.ts
Labels: ignore-for-release

#19333 Tiptap Media Picker: ImageSharp HMAC support
  src/Umbraco.Web.UI.Client/src/packages/core/utils/media/image-size.function.ts
  src/Umbraco.Web.UI.Client/src/packages/core/utils/media/image-size.test.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/media-upload.tiptap-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/media-picker.tiptap-toolbar-api.ts
Labels: category/front-end, type/bug, area/frontend, release/16.0.0-rc3

#19335 Media Picker Modal File Previews
  src/Umbraco.Web.UI.Client/src/packages/core/extension-registry/components/extension-slot/extension-slot.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/config/config.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/media/imaging/components/imaging-thumbnail.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/collection/media-collection.context.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/image-cropper-field.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/image-cropper-focus-setter.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/input-image-cropper.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/file-upload-preview.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/preview/input-upload-field-audio.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/preview/input-upload-field-file.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/preview/input-upload-field-image.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/preview/input-upload-field-svg.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/preview/input-upload-field-video.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/preview/manifest.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/modals/image-cropper-editor/components/image-cropper-editor-field.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/modals/image-cropper-editor/image-cropper-editor-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/upload-field/property-editor-ui-upload-field.element.ts
Labels: category/front-end, type/feature, area/frontend, release/16.1.0

#19334 Introduce Variant Context
  src/Umbraco.Web.UI.Client/src/packages/content/content/property-dataset-context/element-property-dataset.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/property-dataset/property-dataset-base-context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/variant/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/core/variant/context/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/core/variant/context/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/variant/context/variant.context.token.ts
  src/Umbraco.Web.UI.Client/src/packages/core/variant/context/variant.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/variant/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/workspace-property-dataset/invariant-workspace-property-dataset-context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/item/document-item-data-resolver.ts
  src/Umbraco.Web.UI.Client/src/packages/language/global-contexts/app-language.context.ts
Labels: category/dx, area/frontend, release/16.0.0, release/16.0.0-rc3

#19348 Add explicit Global Search extension point
  src/Umbraco.Web.UI.Client/src/packages/data-type/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/search/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/search/global-search/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/search/global-search/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/search/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/dictionary/search/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/dictionary/search/global-search/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/dictionary/search/global-search/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/dictionary/search/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/search/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/search/global-search/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/search/global-search/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/search/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/search/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/search/global-search/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/search/global-search/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/search/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/search/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/search/global-search/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/search/global-search/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/search/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/search/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/search/global-search/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/search/global-search/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/search/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/search/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/search/global-search/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/search/global-search/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/search/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/search/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/search/global-search/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/search/global-search/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/search/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/search/global-search/global-search.extension.ts
  src/Umbraco.Web.UI.Client/src/packages/search/global-search/types.ts
  src/Umbraco.Web.UI.Client/src/packages/search/search-modal/search-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/templates/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/templates/search/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/templates/search/global-search/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/templates/search/global-search/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/templates/search/manifests.ts
Labels: category/breaking, category/ux, category/dx, area/frontend, release/16.0.0, release/16.0.0-rc3

#18576 Added logging and try/catch around retrieval of references, so we don't block critical operations following an incompatible data type change
  src/Umbraco.Core/PropertyEditors/DataValueReferenceFactoryCollection.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyValueEditorBase.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/DocumentRepositoryTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/MediaRepositoryTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/MemberRepositoryTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/TemplateRepositoryTest.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/BlockListEditorPropertyValueEditorTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/DataValueEditorReuseTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/DataValueReferenceFactoryCollectionTests.cs
Labels: area/backend

#19343 V16 RC: Add more debug info to System Information
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/config/config.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/config/config.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/sysinfo/components/sysinfo.element.ts
  src/Umbraco.Web.UI.Client/src/packages/sysinfo/repository/sysinfo.repository.ts
Labels: type/feature, release/16.0.0

#19344 V16 RC: File upload errors should be shown to the user
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/temporary-file-manager.class.ts
Labels: type/bug, release/16.0.0

#19326 Hotfix: do not validate the invariant-variant entry when we vary by culture
  src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/content-detail-workspace-base.ts
Labels: release/16.0.0-rc3

#19316 Document URLs Data Resolver
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/info-app/global-components/workspace-info-app-layout.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/url/document-urls-data-resolver.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/url/index.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/url/info-app/document-links-workspace-info-app.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/url/repository/types.ts
  src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/components/input-multi-url/input-multi-url.element.ts
  src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/link-picker-modal/link-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/reference/workspace-info-app/entity-references-workspace-view-info.element.ts
Labels: category/ux, type/bug, release/16.0.0, release/16.0.0-rc3

#19331 V16 RC: HtmlImageSourceParser should not care for order of attributes
  src/Umbraco.Core/Templates/HtmlImageSourceParser.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Templates/HtmlImageSourceParserTests.cs
Labels: category/front-end, type/bug, release/16.0.0, release/16.0.0-rc3

#19359 Resolve seen issue regarding destroyed validation context
  src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/bind-server-validation-to-form-control.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/form-control-validator.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/validation.controller.ts
Labels: ignore-for-release, release/16.0.0-rc3

#19363 Fix for invalid state in JsonBlockValueConverter when an unused layout has a nested array
  src/Umbraco.Infrastructure/Serialization/JsonBlockValueConverter.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Serialization/JsonBlockValueConverterTests.cs
Labels: community/pr, release/16.1.0

#19292 Feature: Content Workspace Icon
  src/Umbraco.Web.UI.Client/src/packages/core/repository/detail/detail-data-source.interface.ts
  src/Umbraco.Web.UI.Client/src/packages/core/repository/detail/detail-repository-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-split-view/workspace-split-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/entity-detail/types.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/repository/detail/index.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/repository/detail/document-detail.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace-split-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/repository/detail/index.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/repository/detail/media-type-detail.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/repository/detail/media-type-detail.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/repository/detail/media-detail.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/workspace/media-workspace-split-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/workspace/media-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/repository/detail/index.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/repository/detail/member-type-detail.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/repository/detail/member-type-detail.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/repository/index.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/repository/detail/member-detail.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/workspace/member/member-workspace-split-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/workspace/member/member-workspace.context.ts
Labels: category/ux, type/feature, release/16.1.0

#19358 Set manifests when using createExtensionApi
  src/Umbraco.Web.UI.Client/src/packages/clipboard/property/value-translator/copy/clipboard-copy-translator-value-resolver.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/controller/merge-content-variant-data.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/entity-actions-bundle/entity-actions-bundle.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/common/create/create.action.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/property-value-cloner/property-value-clone.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/property-value-preset/property-value-preset-builder.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/section/section-default.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/validation-path-translation/validation-property-path-translation.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/markdown-editor/components/input-markdown-editor/input-markdown.element.ts
Labels: area/frontend, release/16.0.0

#19369 Fix filter when selecting elements for block types
  src/Umbraco.Web.UI.Client/src/packages/block/block-type/components/input-block-type/input-block-type.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/picker/search/picker-search-result.element.ts
Labels: ignore-for-release

#19361 Handle user id 0 (Unknown/System) when building content version response
  src/Umbraco.Cms.Api.Management/Factories/DocumentVersionPresentationFactory.cs
Labels: type/bug, area/backend, release/16.1.0

#19367 Validation Context destroys self destroy before clean up
  src/Umbraco.Web.UI.Client/examples/validation-context/validation-context-dashboard.ts
  src/Umbraco.Web.UI.Client/src/libs/context-api/consume/context-consumer.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/validation.controller.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ContentWithMultiURLPicker.spec.ts
Labels: area/frontend, release/16.0.0, ignore-for-release

#19350 fix: check for NullRepresentationInCache in AppCacheExtensions
  src/Umbraco.Core/Cache/AppCacheExtensions.cs
  src/Umbraco.Core/Constants-Cache.cs
  src/Umbraco.Infrastructure/Cache/DefaultRepositoryCachePolicy.cs
Labels: community/pr, release/13.9.0, release/16.1.0

#19375 additional context name for 'content property context'
  src/Umbraco.Web.UI.Client/src/packages/content/content/components/property-type-based-property/index.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/components/property-type-based-property/property-type-based-property.context-token.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/components/property-type-based-property/property-type-based-property.context.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/components/property-type-based-property/property-type-based-property.element.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/content-property.context-token.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/index.ts
Labels: area/frontend, release/16.0.0

#19406 hotfix: correct dark theme color for variant selector
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-split-view/workspace-split-view-variant-selector.element.ts
Labels: release/16.0.0, release/16.0.0-rc4

#19412 fix context api test
  src/Umbraco.Web.UI.Client/src/libs/context-api/consume/context-consumer.test.ts
Labels: ignore-for-release, release/16.0.0-rc4

#19411 Fix observe property string name
  src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/views/edit/content-editor-property.element.ts
Labels: ignore-for-release, release/16.0.0-rc4

#19399 <umb-content-workspace-property> DX
  src/Umbraco.Web.UI.Client/src/packages/content/content-type/structure/content-type-property-structure-helper.class.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/global-components/content-workspace-property.element.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/global-components/index.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/index.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/views/edit/content-editor-properties.element.ts
  src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/views/edit/content-editor-property.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item.element.ts
Labels: category/dx, area/frontend, release/16.0.0, release/16.0.0-rc4

#19408 Ensure controller is still present
  src/Umbraco.Web.UI.Client/src/libs/controller-api/controller-host.mixin.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ContentWithMultiURLPicker.spec.ts
Labels: release/16.0.0, release/16.0.0-rc4

#19420 Closing redirecting modals fix
  src/Umbraco.Web.UI.Client/src/packages/content/content/workspace/content-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/repository/item/item-repository-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/repository/item/item-repository.interface.ts
  src/Umbraco.Web.UI.Client/src/packages/core/router/router-slot/router-slot.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/controllers/workspace-is-new-redirect.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/entity-detail/entity-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/submittable/submittable-workspace-context-base.ts
Labels: release/16.0.0-rc4

#19421 V16-RC: Not all types are exported from 'documents'
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/types.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/url/index.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/url/types.ts
Labels: area/frontend, release/16.0.0-rc4

#19423 build(deps): bump @umbraco-ui/uui to 1.14.0-rc.2
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
Labels: dependencies, area/frontend, release/16.0.0-rc4

#19433 V16: Upgrade Login dependencies to Umbraco 16
  src/Umbraco.Web.UI.Login/package-lock.json
  src/Umbraco.Web.UI.Login/package.json
  src/Umbraco.Web.UI.Login/src/components/layouts/new-password-layout.element.ts
  src/Umbraco.Web.UI.Login/src/components/pages/login.page.element.ts
  src/Umbraco.Web.UI.Login/src/components/pages/reset-password.page.element.ts
  src/Umbraco.Web.UI.Login/src/contexts/auth.context.ts
  src/Umbraco.Web.UI.Login/src/contexts/auth.repository.ts
  src/Umbraco.Web.UI.Login/src/controllers/slim-backoffice-initializer.ts
Labels: dependencies, release/16.0.0, release/16.0.0-rc4

#19419 Throw if attempting to use the default unique media path scheme with version 7 GUIDs
  src/Umbraco.Core/IO/MediaPathSchemes/UniqueMediaPathScheme.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/IO/MediaPathSchemes/UniqueMediaPathSchemeTests.cs
Labels: release/16.1.0

#19452 build(deps): bump @umbraco-ui/uui from 1.14.0-rc.3 to 1.14.0-rc.4
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Login/package-lock.json
  src/Umbraco.Web.UI.Login/package.json
  src/Umbraco.Web.UI.Login/vite.config.ts
Labels: dependencies, area/frontend, release/16.0.0-rc5

#19436 Bugfixes/v17/19341 description update models builder generates different types for color picker value
  src/Umbraco.Web.UI.Client/src/assets/lang/da.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
Labels: community/pr, release/17.0.0
