Repository umbraco/Umbraco-CMS, pull requests merged in 2025-03, with the labels that each got.

#16037 Remove `UmbracoPath` setting
  src/Umbraco.Cms.Api.Common/OpenApi/SubTypesSelector.cs
  src/Umbraco.Cms.Api.Common/OpenApi/SwaggerRouteTemplatePipelineFilter.cs
  src/Umbraco.Cms.Api.Management/Controllers/BackOfficeLoginController.cs
  src/Umbraco.Cms.Api.Management/DependencyInjection/ApplicationBuilderExtensions.cs
  src/Umbraco.Cms.Api.Management/Routing/BackOfficeAreaRoutes.cs
  src/Umbraco.Cms.Api.Management/Routing/PreviewRoutes.cs
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoLogin/Index.cshtml
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoWebsite/Maintenance.cshtml
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoWebsite/NoNodes.cshtml
  src/Umbraco.Cms.StaticAssets/umbraco/UmbracoWebsite/NotFound.cshtml
  src/Umbraco.Core/Configuration/GlobalSettingsExtensions.cs
  src/Umbraco.Core/Constants-System.cs
  src/Umbraco.Core/Hosting/HostingEnvironmentExtensions.cs
  src/Umbraco.Core/Routing/UmbracoRequestPaths.cs
  src/Umbraco.Web.Common/AspNetCore/AspNetCoreBackOfficeInfo.cs
  src/Umbraco.Web.Common/Hosting/UmbracoBackOfficePathGenerator.cs
  src/Umbraco.Web.Common/Mvc/UmbracoMvcConfigureOptions.cs
  src/Umbraco.Web.Common/Profiler/ConfigureMiniProfilerOptions.cs
  src/Umbraco.Web.Common/Views/UmbracoViewPage.cs
  src/Umbraco.Web.UI/Composers/ControllersAsServicesComposer.cs
  src/Umbraco.Web.Website/Controllers/RenderNoContentController.cs
  src/Umbraco.Web.Website/Extensions/HtmlHelperRenderExtensions.cs
  src/Umbraco.Web.Website/Middleware/BasicAuthenticationMiddleware.cs
  src/Umbraco.Web.Website/Routing/FrontEndRoutes.cs
  tests/Umbraco.Tests.Integration/DependencyInjection/UmbracoBuilderExtensions.cs
  tests/Umbraco.Tests.Integration/NewBackoffice/OpenAPIContractTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/DeliveryApi/OpenApiContractTest.cs
  tests/Umbraco.Tests.UnitTests/AutoFixture/Customizations/UmbracoCustomizations.cs
  tests/Umbraco.Tests.UnitTests/TestHelpers/Objects/TestUmbracoContextFactory.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Configuration/Models/GlobalSettingsTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/UmbracoRequestPathsTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Routing/BackOfficeAreaRoutesTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Web.Common/Routing/PreviewRoutesTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Web.Website/Controllers/RenderNoContentControllerTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Web.Website/Controllers/SurfaceControllerTests.cs
Labels: category/breaking, area/backend

#17057 Add `AsyncMigrationBase`, update base classes and call async methods
  src/Umbraco.Infrastructure/DependencyInjection/UmbracoBuilder.CoreServices.cs
  src/Umbraco.Infrastructure/Install/PackageMigrationRunner.cs
  src/Umbraco.Infrastructure/Install/PremigrationUpgrader.cs
  src/Umbraco.Infrastructure/Install/UnattendedUpgrader.cs
  src/Umbraco.Infrastructure/Installer/Steps/DatabaseUpgradeStep.cs
  src/Umbraco.Infrastructure/Migrations/AsyncMigrationBase.Database.cs
  src/Umbraco.Infrastructure/Migrations/AsyncMigrationBase.cs
  src/Umbraco.Infrastructure/Migrations/IMigrationBuilder.cs
  src/Umbraco.Infrastructure/Migrations/IMigrationContext.cs
  src/Umbraco.Infrastructure/Migrations/IMigrationPlanExecutor.cs
  src/Umbraco.Infrastructure/Migrations/Install/DatabaseBuilder.cs
  src/Umbraco.Infrastructure/Migrations/MergeBuilder.cs
  src/Umbraco.Infrastructure/Migrations/MigrationBase.cs
  src/Umbraco.Infrastructure/Migrations/MigrationBase_Extra.cs
  src/Umbraco.Infrastructure/Migrations/MigrationBuilder.cs
  src/Umbraco.Infrastructure/Migrations/MigrationContext.cs
  src/Umbraco.Infrastructure/Migrations/MigrationPlan.cs
  src/Umbraco.Infrastructure/Migrations/MigrationPlanExecutor.cs
  src/Umbraco.Infrastructure/Migrations/NoopMigration.cs
  src/Umbraco.Infrastructure/Migrations/PostMigrations/CacheRebuilder.cs
  src/Umbraco.Infrastructure/Migrations/PostMigrations/ICacheRebuilder.cs
  src/Umbraco.Infrastructure/Migrations/UnscopedAsyncMigrationBase.cs
  src/Umbraco.Infrastructure/Migrations/UnscopedMigrationBase.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/Upgrader.cs
  src/Umbraco.Infrastructure/Packaging/AsyncPackageMigrationBase.cs
  src/Umbraco.Infrastructure/Packaging/AutomaticPackageMigrationPlan.cs
  src/Umbraco.Infrastructure/Packaging/IImportPackageBuilder.cs
  src/Umbraco.Infrastructure/Packaging/ImportPackageBuilder.cs
  src/Umbraco.Infrastructure/Packaging/PackageMigrationBase.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/RuntimeStateTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Migrations/AdvancedMigrationTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Migrations/PartialMigrationsTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/AlterMigrationTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/MigrationPlanTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Migrations/MigrationTests.cs
Labels: category/breaking, status/needs-docs, area/backend

#18461 Localize the email property editor validation and add tests
  src/Umbraco.Core/PropertyEditors/Validators/EmailValidator.cs
  src/Umbraco.Infrastructure/PropertyEditors/EmailAddressPropertyEditor.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/Validators/EmailValidatorTests.cs
Labels: area/backend

#18512 Added tests and localization to radio button validation
  src/Umbraco.Core/EmbeddedResources/Lang/da.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Core/PropertyEditors/RadioValueEditor.cs
  src/Umbraco.Core/PropertyEditors/Validators/RadioValueValidator.cs
  src/Umbraco.Infrastructure/PropertyEditors/RadioButtonsPropertyEditor.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/RadioButtonsPropertyValueEditorTests.cs
Labels: area/backend

#18499 V15: Allows certain adjustments of the logo
  src/Umbraco.Cms.Api.Management/Controllers/Security/BackOfficeGraphicsController.cs
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/assets/logo_blue.svg
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/assets/logo_dark.svg
  src/Umbraco.Cms.StaticAssets/wwwroot/umbraco/assets/logo_light.svg
  src/Umbraco.Core/Configuration/Models/ContentSettings.cs
  src/Umbraco.Web.UI.Client/src/apps/app/app-logo.element.ts
  src/Umbraco.Web.UI.Client/src/apps/backoffice/components/backoffice-header-logo.element.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/backoffice/assets/logo_blue.svg
  src/Umbraco.Web.UI.Client/src/mocks/handlers/backoffice/assets/logo_dark.svg
  src/Umbraco.Web.UI.Client/src/mocks/handlers/backoffice/assets/logo_light.svg
  src/Umbraco.Web.UI.Client/src/mocks/handlers/backoffice/backoffice.handlers.ts
  src/Umbraco.Web.UI.Login/src/components/layouts/auth-layout.element.ts
  src/Umbraco.Web.UI.Login/src/mocks/handlers/backoffice.handlers.ts
Labels: category/dx, type/feature, area/frontend, release/15.4.0

#18489 Set additionalOptions on the rollback entity action
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/rollback/entity-action/manifests.ts
Labels: category/ux, area/frontend

#18380 Added option for filtering the content types allowed as children based on the parent node
  src/Umbraco.Cms.Api.Management/Controllers/DocumentType/AllowedChildrenDocumentTypeController.cs
  src/Umbraco.Cms.Api.Management/Controllers/MediaType/AllowedChildrenMediaTypeController.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Core/Services/ContentTypeServiceBaseOfTRepositoryTItemTService.cs
  src/Umbraco.Core/Services/Filters/IContentTypeFilter.cs
  src/Umbraco.Core/Services/IContentTypeServiceBase.cs
  src/Umbraco.Web.UI.Client/src/external/backend-api/src/sdk.gen.ts
  src/Umbraco.Web.UI.Client/src/external/backend-api/src/types.gen.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/repository/structure/content-type-structure-data-source.interface.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/repository/structure/content-type-structure-repository-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/repository/structure/content-type-structure-repository.interface.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/repository/structure/content-type-structure-server-data-source-base.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/repository/structure/document-type-structure.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/action/create-document-collection-action.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/create/document-create-options-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/repository/structure/media-type-structure.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/collection/action/create-media-collection-action.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/dropzone-manager.class.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/entity-actions/create/media-create-options-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/components/media-picker-create-item.element.ts
  src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/link-picker-modal/link-picker-modal.element.ts
Labels: area/backend

#18525 V15: Workspace buttons cannot be overwritten in all cases
  src/Umbraco.Web.UI.Client/public-assets/App_Plugins/custom-bundle-package/index.js
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action-menu/workspace-action-menu.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action/default/workspace-action-default-kind.element.ts
Labels: type/bug, area/frontend

#18520 Feature: Content Type Workspace Editor Header Element
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/global-components/content-type-workspace-editor-header.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/global-components/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/content-type-workspace-context-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/content-type-workspace-context.interface.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/workspace/document-type/document-type-workspace-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/workspace/media-type-workspace-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/workspace/member-type-workspace-editor.element.ts
Labels: category/dx, area/frontend, release/15.4.0

#18501 Remove version from models builder generated code header when configured to do so
  src/Umbraco.Infrastructure/ModelsBuilder/Building/TextBuilder.cs
  src/Umbraco.Infrastructure/ModelsBuilder/Building/TextHeaderWriter.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.ModelsBuilder.Embedded/BuilderTests.cs
Labels: area/backend

#18558 15.3: Hotfix: block grid custom views
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.element.ts
Labels: status/regression, area/frontend, release/15.3.0

#18485 Align folder entity action labels
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/folder/entity-action/delete-folder/delete-folder.action.ts
  tests/Umbraco.Tests.AcceptanceTest/package-lock.json
  tests/Umbraco.Tests.AcceptanceTest/package.json
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/DataTypeFolder.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/DocumentType/DocumentTypeFolder.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/MediaType/MediaTypeFolder.spec.ts
Labels: category/ux, area/frontend

#18508 Fix issue with server validation from dictionary configuration where floating point values can be be accessed as doubles or ints
  src/Umbraco.Core/PropertyEditors/Validators/DictionaryConfigurationValidatorBase.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/DecimalValueEditorTests.cs
Labels: area/backend

#18471 Adds unit tests for RequiredValidator
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/Validators/RequiredValidatorTests.cs
Labels: area/backend, area/test

#18161 Feature: Has Children Condition
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/has-children/condition/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/has-children/condition/entity-has-children.condition-config.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/has-children/condition/entity-has-children.condition.manifest.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/has-children/condition/entity-has-children.condition.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/has-children/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/has-children/context/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/has-children/context/has-children.context-token.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/has-children/context/has-children.entity-context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/has-children/context/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/has-children/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/has-children/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/core/recycle-bin/tree/tree-item/recycle-bin-tree-item.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-base/tree-item-context-base.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/recycle-bin/entity-action/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/recycle-bin/entity-action/manifests.ts
  tests/Umbraco.Tests.AcceptanceTest/package-lock.json
  tests/Umbraco.Tests.AcceptanceTest/package.json
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ChildrenContent.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ContentWithDocumentTypeProperties/ContentWithAllowedChildNodes.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ContentWithDocumentTypeProperties/ContentWithCollections.spec.ts
Labels: category/ux, area/frontend

#18526 V15: Add MNTP serverside validation
  src/Umbraco.Core/EmbeddedResources/Lang/da.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Core/PropertyEditors/MultiNodePickerConfiguration.cs
  src/Umbraco.Core/PropertyEditors/Validation/TypedJsonValidatorRunner.cs
  src/Umbraco.Core/PropertyEditors/Validation/ValidationHelper.cs
  src/Umbraco.Infrastructure/PropertyEditors/MediaPicker3PropertyEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/MultiNodeTreePickerPropertyEditor.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/MultiNodeTreePickerTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/MultiNodeTreePickerValidationTests.cs
Labels: release/15.4.0

#18474 Provide custom required validator for block list and toggle
  src/Umbraco.Core/Services/PropertyValidationService.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockEditorPropertyValueEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockListPropertyEditorBase.cs
  src/Umbraco.Infrastructure/PropertyEditors/BlockValuePropertyValueEditorBase.cs
  src/Umbraco.Infrastructure/PropertyEditors/TrueFalsePropertyEditor.cs
  src/Umbraco.Infrastructure/PropertyEditors/Validators/BlockListValueRequiredValidator.cs
  src/Umbraco.Infrastructure/PropertyEditors/Validators/TrueFalseValueRequiredValidator.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/Validators/BlockListValueRequiredValidatorTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/Validators/TrueFalseValueRequiredValidatorTests.cs
Labels: area/backend

#18478 Handle multiline statements in migrations
  src/Umbraco.Infrastructure/Migrations/MigrationExpressionBase.cs
  src/Umbraco.Infrastructure/Migrations/MigrationPlanExecutor.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/SyntaxProvider/SqlServerSyntaxProviderTests.cs
Labels: area/backend

#18568 V15: Resolves "Save and Preview" backoffice refresh
  src/Umbraco.Web.UI.Client/src/apps/preview/apps/preview-culture.element.ts
  src/Umbraco.Web.UI.Client/src/apps/preview/apps/preview-device.element.ts
  src/Umbraco.Web.UI.Client/src/apps/preview/apps/preview-exit.element.ts
  src/Umbraco.Web.UI.Client/src/apps/preview/apps/preview-open-website.element.ts
  src/Umbraco.Web.UI.Client/src/apps/preview/preview.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace.context.ts
Labels: type/bug, area/frontend, release/15.4.0

#18496 Move database cache rebuild to a background task with polling
  src/Umbraco.Cms.Api.Management/Controllers/PublishedCache/RebuildPublishedCacheController.cs
  src/Umbraco.Cms.Api.Management/Controllers/PublishedCache/RebuildPublishedCacheStatusController.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/PublishedCache/RebuildStatusModel.cs
  src/Umbraco.Core/PublishedCache/IDatabaseCacheRebuilder.cs
  src/Umbraco.Infrastructure/Migrations/MigrationPlanExecutor.cs
  src/Umbraco.Infrastructure/Migrations/PostMigrations/CacheRebuilder.cs
  src/Umbraco.Infrastructure/Services/IndexingRebuilderService.cs
  src/Umbraco.PublishedCache.HybridCache/DatabaseCacheRebuilder.cs
  src/Umbraco.Web.UI.Client/src/external/backend-api/src/sdk.gen.ts
  src/Umbraco.Web.UI.Client/src/external/backend-api/src/types.gen.ts
  src/Umbraco.Web.UI.Client/src/packages/publish-cache/dashboard-published-status.element.ts
Labels: area/frontend, area/backend

#18589 Added server side validation for the Multi Url Picker.
  src/Umbraco.Infrastructure/PropertyEditors/MultiUrlPickerValueEditor.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/Validators/MultiUrlPickerValueEditorValidationTests.cs
Labels: release/15.4.0

#18579 Chore: Tiptap code sweep 2
  src/Umbraco.Web.UI.Client/src/css/rte-content.css
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/toolbar/tiptap-toolbar-menu.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/embedded-media.tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/components/property-editor-ui-tiptap-toolbar-configuration.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/contexts/tiptap-toolbar-configuration.context.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/types.ts
Labels: area/frontend, ignore-for-release

#18569 Tiptap RTE: Block extension enabled/disabled checkbox state
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/components/property-editor-ui-tiptap-extensions-configuration.element.ts
Labels: category/ux, type/bug, area/frontend, release/15.4.0

#18596 V15: Add textbox and text area serverside validation
  src/Umbraco.Core/EmbeddedResources/Lang/da.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Core/PropertyEditors/TextOnlyValueEditor.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Models/VariationTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/DataValueEditorReuseTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/Validators/TextOnlyValueEditorValidatorTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Services/PropertyValidationServiceTests.cs
Labels: release/15.4.0

#18480 Support root/area allowed types when pasting in Block Grid
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/clipboard/block/paste/block-to-block-grid-paste-translator.test.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/clipboard/block/paste/block-to-block-grid-paste-translator.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/clipboard/grid-block/paste/grid-block-to-block-grid-paste-translator.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/clipboard/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/context/block-grid-entries.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-editor/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-editor/property-actions/block-grid-paste-from-clipboard.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-editor/property-actions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-editor/types.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/clipboard/block/paste/block-to-block-list-paste-translator.test.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/clipboard/block/paste/block-to-block-list-paste-translator.ts
  src/Umbraco.Web.UI.Client/src/packages/clipboard/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/clipboard/property/actions/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/clipboard/property/actions/index.ts
  src/Umbraco.Web.UI.Client/src/packages/clipboard/property/actions/paste/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/clipboard/property/actions/paste/index.ts
  src/Umbraco.Web.UI.Client/src/packages/clipboard/property/actions/paste/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/clipboard/property/actions/paste/paste-from-clipboard.property-action.ts
  src/Umbraco.Web.UI.Client/src/packages/clipboard/property/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/clipboard/property/context/clipboard.property-context.ts
  src/Umbraco.Web.UI.Client/src/packages/clipboard/property/index.ts
  src/Umbraco.Web.UI.Client/src/packages/clipboard/property/value-translator/paste/types.ts
Labels: type/feature, area/frontend, release/15.4.0

#18593 Update uui to v.1.13-rc1
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  tests/Umbraco.Tests.AcceptanceTest/package-lock.json
  tests/Umbraco.Tests.AcceptanceTest/package.json
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/ApprovedColor.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/ContentPicker.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/DatePicker.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/Dropdown.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/ListView.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/MediaPicker.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/MultiUrlPicker.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/Numeric.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/TinyMCE.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/Tiptap.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/DataType/TrueFalse.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Members/Members.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/RelationTypes/RelationTypes.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/Dashboard/Profiling.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/DocumentType/DocumentTypeDesignTab.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/MediaType/MediaTypeDesignTab.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Users/User.spec.ts
Labels: ignore-for-release

#18577 Tiptap RTE: Character Map modal + toolbar item
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/data-type/data-type.data.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icon-dictionary.json
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-omega.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/character-map/character-map-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/character-map/character-map-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/character-map/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/character-map/index.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/character-map/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/index.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/character-map.tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/contexts/tiptap-toolbar-configuration.context.ts
Labels: type/feature, area/frontend, release/15.4.0

#18575 Tiptap RTE: Anchor extension + toolbar item
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-anchor.extension.ts
  src/Umbraco.Web.UI.Client/src/external/tiptap/index.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/data-type/data-type.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/document/document.data.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/anchor-modal/anchor-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/anchor-modal/anchor-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/anchor-modal/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/anchor-modal/index.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/anchor-modal/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/index.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/rich-text-essentials.tiptap-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/anchor.tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/contexts/tiptap-toolbar-configuration.context.ts
Labels: type/feature, area/frontend, release/15.4.0

#18632 Adds client-side validation to Dropdown property editor
  src/Umbraco.Web.UI.Client/src/packages/core/components/input-dropdown/input-dropdown-list.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/dropdown/property-editor-ui-dropdown.element.ts
Labels: type/bug, area/frontend

#18629 Adds client-side validation to Radio Button List property editor
  src/Umbraco.Web.UI.Client/src/packages/core/components/input-radio-button-list/input-radio-button-list.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/radio-button-list/property-editor-ui-radio-button-list.element.ts
Labels: type/bug, area/frontend

#18631 Use change event instead of property value change
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-area-type-permission/block-grid-area-type-permission.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-column-span/property-editor-ui-block-grid-column-span.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-group-configuration/property-editor-ui-block-grid-group-configuration.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-layout-stylesheet/property-editor-ui-block-grid-layout-stylesheet.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/property-editors/block-list-type-configuration/property-editor-ui-block-list-type-configuration.element.ts
  src/Umbraco.Web.UI.Client/src/packages/code-editor/property-editor/property-editor-ui-code-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/property-editors/document-type-picker/property-editor-ui-document-type-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/property-editors/document-picker/property-editor-ui-document-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/markdown-editor/property-editors/markdown-editor/property-editor-ui-markdown-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/property-editors/media-type-picker/property-editor-ui-media-type-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/image-cropper/property-editor-ui-image-cropper.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/image-crops/property-editor-ui-image-crops.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/media-entity-picker/property-editor-ui-media-entity-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/media-picker/property-editor-ui-media-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/upload-field/property-editor-ui-upload-field.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-group/property-editor/member-group-picker/property-editor-ui-member-group-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/property-editor/member-picker/property-editor-ui-member-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/property-editor/property-editor-ui-multi-url-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/checkbox-list/property-editor-ui-checkbox-list.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/collection/config/bulk-action-permissions/permissions.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/collection/config/column/column-configuration.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/collection/config/layout/layout-configuration.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/collection/config/order-by/order-by.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/color-picker/property-editor-ui-color-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/color-swatches-editor/property-editor-ui-color-swatches-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/config/source-content/property-editor-ui-content-picker-source.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/config/source-type/property-editor-ui-content-picker-source-type.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/property-editor-ui-content-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/date-picker/property-editor-ui-date-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/dropdown/property-editor-ui-dropdown.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/eye-dropper/property-editor-ui-eye-dropper.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/icon-picker/property-editor-ui-icon-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/multiple-text-string/property-editor-ui-multiple-text-string.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/number-range/property-editor-ui-number-range.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/number/property-editor-ui-number.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/order-direction/property-editor-ui-order-direction.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/overlay-size/property-editor-ui-overlay-size.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/radio-button-list/property-editor-ui-radio-button-list.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/select/property-editor-ui-select.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/slider/property-editor-ui-slider.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/text-box/property-editor-ui-text-box.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/textarea/property-editor-ui-textarea.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/toggle/property-editor-ui-toggle.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/value-type/property-editor-ui-value-type.element.ts
  src/Umbraco.Web.UI.Client/src/packages/rte/components/rte-base.element.ts
  src/Umbraco.Web.UI.Client/src/packages/static-file/property-editors/static-file-picker/property-editor-ui-static-file-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tags/property-editors/tags/property-editor-ui-tags.element.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/property-editors/stylesheet-picker/property-editor-ui-stylesheet-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiny-mce/property-editors/block/property-editor-ui-block-rte-type-configuration.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiny-mce/property-editors/dimensions/property-editor-ui-tiny-mce-dimensions-configuration.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiny-mce/property-editors/max-image-size/property-editor-ui-tiny-mce-maximagesize.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiny-mce/property-editors/stylesheets/property-editor-ui-tiny-mce-stylesheets-configuration.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiny-mce/property-editors/toolbar/property-editor-ui-tiny-mce-toolbar-configuration.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/components/property-editor-ui-tiptap-extensions-configuration.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/property-editor/user-picker/property-editor-ui-user-picker.element.ts
Labels: category/dx, area/frontend, release/15.4.0

#18633 Fix bug RTE code editor modal - pretty print not working
  src/Umbraco.Web.UI.Client/src/external/monaco-editor/index.ts
  src/Umbraco.Web.UI.Client/src/rollup.config.js
  src/Umbraco.Web.UI.Client/vite.config.ts
Labels: type/bug, area/frontend

#18455 Chore: deprecate UmbPropertyValueChangeEvent for v.16
  src/Umbraco.Web.UI.Client/src/packages/core/property-editor/events/property-value-change.event.ts
Labels: category/dx, area/frontend, release/16.0.0

#18636 Adds client-side validation to Checkbox List property editor
  src/Umbraco.Web.UI.Client/src/packages/property-editors/checkbox-list/components/input-checkbox-list/input-checkbox-list.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/checkbox-list/property-editor-ui-checkbox-list.element.ts
Labels: type/bug, area/frontend, release/15.4.0

#18643 V15: Reduce the size of the package json schema
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/external/tinymce/index.ts
  src/Umbraco.Web.UI.Client/src/json-schema/all-packages.ts
  src/Umbraco.Web.UI.Client/src/json-schema/umbraco-package-schema.ts
  src/Umbraco.Web.UI.Client/src/packages/tiny-mce/plugins/tinymce-plugin.extension.ts
Labels: category/dx, type/bug, area/frontend, release/15.4.0

#18644 V15: Support legacy allowPackageTelemetry option
  src/Umbraco.Core/Manifest/PackageManifest.cs
  src/Umbraco.Infrastructure/Services/Implement/PackagingService.cs
  src/Umbraco.Web.UI.Client/src/json-schema/umbraco-package-schema.ts
Labels: type/bug, area/frontend, area/backend, release/15.4.0

#18597 V15: Enable umbraco-extension client to auto-build
  templates/UmbracoExtension/.template.config/template.json
  templates/UmbracoExtension/Client/package.json
  templates/UmbracoExtension/Client/public/umbraco-package.json
  templates/UmbracoExtension/Client/scripts/generate-openapi.js
  templates/UmbracoExtension/Client/src/api/client.gen.ts
  templates/UmbracoExtension/Client/src/api/index.ts
  templates/UmbracoExtension/Client/src/api/schemas.gen.ts
  templates/UmbracoExtension/Client/src/api/sdk.gen.ts
  templates/UmbracoExtension/Client/src/api/services.gen.ts
  templates/UmbracoExtension/Client/src/api/types.gen.ts
  templates/UmbracoExtension/Client/src/bundle.manifests.ts
  templates/UmbracoExtension/Client/src/dashboards/dashboard.element.ts
  templates/UmbracoExtension/Client/src/dashboards/manifest.ts
  templates/UmbracoExtension/Client/src/entrypoints/entrypoint.ts
  templates/UmbracoExtension/Client/src/entrypoints/manifest.ts
  templates/UmbracoExtension/Client/vite.config.ts
  templates/UmbracoExtension/Umbraco.Extension.csproj
Labels: category/dx, type/feature, release/15.4.0

#18650 correct labels
  src/Umbraco.Web.UI.Client/src/packages/tags/property-editors/tags/Umbraco.Tags.ts
Labels: category/ux, release/15.4.0

#18655 15.3: Hotfix: Awaits Open Content Picker
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/components/input-document/input-document.context.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-media/input-media.context.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/components/input-member/input-member.context.ts
Labels: status/regression, area/frontend, release/15.3.0

#18657 Center align search icon
  src/Umbraco.Web.UI.Client/src/packages/core/picker/search/picker-search-field.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/picker/search/picker-search-result.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
Labels: category/ui, area/frontend, release/15.4.0

#18648 v15: clean up unnecesary config options
  src/Umbraco.Web.UI.Client/src/packages/property-editors/textarea/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/textarea/property-editor-ui-textarea.element.ts
Labels: area/frontend

#18463 Remove the hardcoded color for the text in error message
  src/Umbraco.Web.UI.Client/src/packages/log-viewer/workspace/views/search/components/log-viewer-message.element.ts
Labels: category/ux, category/accessibility, type/bug, area/frontend, release/15.4.0

#18653 Fix issue text overflow when user name is too long
  src/Umbraco.Web.UI.Client/src/less/components/users/umb-user-cards.less
  src/Umbraco.Web.UI.Client/src/views/users/views/users/users.html
Labels: category/ux, type/bug, area/frontend, release/13.8.0

#18603 Allow multiple URL segments per document
  src/Umbraco.Core/Models/ContentBaseExtensions.cs
  src/Umbraco.Core/Models/PublishedDocumentUrlSegment.cs
  src/Umbraco.Core/Services/DocumentUrlService.cs
  src/Umbraco.Core/Services/IDocumentUrlService.cs
  src/Umbraco.Core/Strings/IUrlSegmentProvider.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_3_0/AddNameAndDescriptionToWebhooks.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_4_0/UpdateDocumentUrlToPersistMultipleSegmentsPerDocument.cs
  src/Umbraco.Infrastructure/Persistence/Dtos/DocumentUrlDto.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentUrlRepository.cs
  tests/Umbraco.Tests.Integration/CompatibilitySuppressions.xml
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentUrlServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentUrlServiceTests_HideTopLevel_False.cs
Labels: status/needs-docs, type/feature, area/backend, release/15.4.0

#18672 Tiptap RTE: Text Indent extension + toolbar items
  src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-text-indent-extension.ts
  src/Umbraco.Web.UI.Client/src/external/tiptap/index.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/data-type/data-type.data.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/text-indent.tiptap-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/text-indent.tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/text-outdent.tiptap-toolbar-api.ts
Labels: type/feature, area/frontend, release/15.4.0

#18660 Content Picker: Filter out invalid entity types
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/core/picker-input/picker-input.context.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/components/input-content/input-content.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/property-editor-ui-content-picker.element.ts
Labels: type/bug, area/frontend

#18689 Tiptap RTE: Added `data-mark` attributes
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/tiptap-toolbar.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/components/property-editor-ui-tiptap-toolbar-configuration.element.ts
Labels: area/frontend, ignore-for-release

#18727 build(deps-dev): bump storybook from 8.5.7 to 8.6.7
  src/Umbraco.Web.UI.Client/.storybook/main.ts
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
Labels: dependencies, ignore-for-release

#18708 Tiptap RTE: Table column/row bubble menu
  src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-umb-bubble-menu.extension.ts
  src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-umb-table.extension.ts
  src/Umbraco.Web.UI.Client/src/external/tiptap/index.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/cascading-menu-popover/cascading-menu-popover.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/base.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/components/table-column-menu.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/components/table-row-menu.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/table.tiptap-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/table.tiptap-toolbar-api.ts
Labels: type/feature, area/frontend, release/15.4.0

#18724 Tiptap RTE: Refactored Table toolbar button
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/cascading-menu-popover/cascading-menu-popover.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/toolbar/tiptap-toolbar-menu.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/components/table-toolbar-menu.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/table.tiptap-toolbar-api.ts
Labels: area/frontend, ignore-for-release

#18715 V15: Adds accepted image types for image cropper
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/config/config.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/temporary-file-manager.class.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/input-image-cropper.element.ts
Labels: category/ux, type/bug, area/frontend, release/15.4.0

#18677 build(deps): bump @umbraco-ui/uui from 1.13.0-rc.1 to 1.13.0-rc.2
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
Labels: dependencies, ignore-for-release

#18651 Bugfix: Document granular user permission preset
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/user-permissions/input-document-granular-user-permission/input-document-granular-user-permission.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user-group/workspace/user-group/components/user-group-granular-permission-list.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user-permission/modals/settings/entity-user-permission-settings-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user-permission/modals/settings/entity-user-permission-settings-modal.token.ts
Labels: category/ux, release/15.4.0

#18519 V15: Change drag and drop icon
  src/Umbraco.Web.UI.Client/src/packages/core/components/multiple-color-picker-input/multiple-color-picker-item-input.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/multiple-text-string-input/input-multiple-text-string-item.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/views/design/content-type-design-editor-group.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/views/design/content-type-design-editor-property.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/views/design/content-type-design-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icon-dictionary.json
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-drag.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/entity-actions/sort-children-of/modal/sort-children-of-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/image-crops/property-editor-ui-image-crops.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/collection/config/column/column-configuration.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/collection/config/layout/layout-configuration.element.ts
Labels: category/ui, area/frontend, release/15.4.0

#18665 Bugfix: block culture permissions
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/clipboard/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/clipboard/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/components/block-list-entry/block-list-entry.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block/workspace/block-element-property-dataset.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content/property-dataset-context/element-property-dataset.context.ts
Labels: status/regression, type/bug, area/frontend

#18521 Feature: Language Item Ref
  src/Umbraco.Web.UI.Client/src/packages/language/components/input-language/input-language.element.ts
  src/Umbraco.Web.UI.Client/src/packages/language/item/langauge-item-ref.element.ts
  src/Umbraco.Web.UI.Client/src/packages/language/item/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/language/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/language/repository/item/language-item.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/language/repository/item/types.ts
Labels: category/dx, area/frontend, release/15.4.0

#18592 Remove the showOpenButton configuration
  src/Umbraco.Web.UI.Client/src/mocks/data/data-type/data-type.data.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/property-editors/document-type-picker/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/property-editors/document-type-picker/property-editor-ui-document-type-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/components/input-document/input-document.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/property-editors/document-picker/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/property-editors/document-picker/property-editor-ui-document-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/property-editors/media-type-picker/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-media/input-media.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-group/components/input-member-group/input-member-group.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-group/property-editor/member-group-picker/property-editor-ui-member-group-picker.element.ts
  src/Umbraco.Web.UI.Client/src/packages/multi-url-picker/link-picker-modal/link-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/components/input-content/input-content.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/property-editor-ui-content-picker.element.ts
Labels: category/ux, area/frontend, release/15.4.0

#18736 Updates dashboard to use uui-box headline property/attribute & place
  src/Umbraco.Web.UI.Client/src/packages/models-builder/models-builder-dashboard.element.ts
Labels: community/pr, category/ui, type/improvement, release/15.4.0

#18751 Tiptap RTE: Table Properties toolbar menu + modal
  src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-umb-table.extension.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/document/document.data.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/index.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/components/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/components/table-insert.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/components/table-properties-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/components/table-properties-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/index.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/table.tiptap-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/table.tiptap-toolbar-api.ts
Labels: type/feature, area/frontend, release/15.4.0

#18754 wups wrong icon name correction
  src/Umbraco.Web.UI.Client/src/packages/core/components/multiple-color-picker-input/multiple-color-picker-item-input.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/multiple-text-string-input/input-multiple-text-string-item.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/views/design/content-type-design-editor-group.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/views/design/content-type-design-editor-property.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/views/design/content-type-design-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icon-dictionary.json
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-grip.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/entity-actions/sort-children-of/modal/sort-children-of-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/property-editors/image-crops/property-editor-ui-image-crops.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/collection/config/column/column-configuration.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/collection/config/layout/layout-configuration.element.ts
Labels: ignore-for-release

#18682 Removed obsoleted group alias keys from being publicly available
  src/Umbraco.Cms.Api.Management/Security/ExternalSignInAutoLinkOptions.cs
  src/Umbraco.Core/Constants-Security.cs
  src/Umbraco.Core/Models/UserExtensions.cs
  src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/UserServiceCrudTests.Filter.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Persistence/Repositories/UserRepositoryTest.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Services/UserGroupServiceTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Infrastructure/Editors/UserEditorAuthorizationHelperTests.cs
Labels: category/breaking, release/16.0.0

#18662 V16: Removed deprecated client-side code
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/libs/formatting-api/formatting.controller.ts
  src/Umbraco.Web.UI.Client/src/libs/formatting-api/index.ts
  src/Umbraco.Web.UI.Client/src/libs/formatting-api/localizeAndTransform.function.ts
  src/Umbraco.Web.UI.Client/src/packages/code-editor/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property-editor/ui-picker-modal/property-editor-ui-picker-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/core/section/components/input-section/input-section.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/conditions/const.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/components/data-type-input/data-type-input.context.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/modals/data-type-picker-flow/data-type-picker-flow-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/dictionary/components/input-dictionary/input-dictionary.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/components/input-document-type/input-document-type.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/components/input-document/input-document.context.ts
  src/Umbraco.Web.UI.Client/src/packages/language/components/input-language/input-language.context.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/components/input-media-type/input-media-type.context.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-group/components/input-member-group/input-member-group.context.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/components/input-member-type/input-member-type.context.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/components/input-member/input-member.context.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/content-picker/components/input-content/input-content.element.ts
  src/Umbraco.Web.UI.Client/src/packages/static-file/components/input-static-file/input-static-file.context.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/partial-views/global-components/input-partial-view/input-partial-view.context.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/scripts/global-components/input-script/input-script.context.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/stylesheets/global-components/stylesheet-input/stylesheet-input.context.ts
  src/Umbraco.Web.UI.Client/src/packages/templating/templates/global-components/input-template/input-template.context.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user-group/components/input-user-group/user-group-input.context.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/components/user-input/user-input.context.ts
  src/Umbraco.Web.UI.Client/tsconfig.json
  src/Umbraco.Web.UI.Client/utils/all-umb-consts/imports.ts
Labels: area/frontend, release/16.0.0

#18747 Only validate for duplicate member email address when configured to do so
  src/Umbraco.Infrastructure/Services/MemberEditingService.cs
Labels: area/backend

#18753 V15: New dropzone component available for the Backoffice
  .vscode/lit.code-snippets
  src/Umbraco.Web.UI.Client/.vscode/lit.code-snippets
  src/Umbraco.Web.UI.Client/devops/generate-check-const-test/index.js
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/packages/core/resources/resource.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/temporary-file-manager.class.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/types.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/entity-actions/import/modal/document-type-import-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/components/dropzone.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/components/index.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/components/input-dropzone/input-dropzone.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/components/input-dropzone/input-dropzone.stories.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/dropzone-change.event.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/dropzone-manager.class.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/dropzone-submitted.event.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/index.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/modals/dropzone-media-type-picker/dropzone-media-type-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/modals/dropzone-media-type-picker/dropzone-media-type-picker-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/modals/dropzone-media-type-picker/index.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/modals/index.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/modals/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/types.ts
  src/Umbraco.Web.UI.Client/src/packages/media/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/entity-actions/import/modal/media-type-import-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/collection/media-collection.context.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/collection/media-collection.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/collection/types.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/collection/views/grid/media-grid-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/input-upload-field.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/index.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/index.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/types.ts
  src/Umbraco.Web.UI.Client/src/packages/media/vite.config.ts
  src/Umbraco.Web.UI.Client/tsconfig.json
  src/Umbraco.Web.UI.Client/utils/all-umb-consts/imports.ts
Labels: category/dx, type/feature, area/frontend, release/15.4.0

#18775 Worspace: fix workspace circular
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-editor/workspace-editor.element.ts
Labels: ignore-for-release

#18773 User: Fix circular for user kind util
  src/Umbraco.Web.UI.Client/src/packages/user/user/repository/detail/user-detail.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/utils/index.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/utils/user-kind.ts
Labels: ignore-for-release

#18227 Feature: Tree expansion state
  src/Umbraco.Web.UI.Client/src/packages/core/tree/default/default-tree.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/default/default-tree.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/entity-actions/duplicate-to/modal/duplicate-to-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/entity-actions/move/move-to.action.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/expansion-manager/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/expansion-manager/tree-expansion-manager.test.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/expansion-manager/tree-expansion-manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/expansion-manager/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-base/tree-item-context-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-base/tree-item-element-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-context.interface.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-picker-modal/tree-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-picker-modal/tree-picker-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/duplicate/modal/duplicate-document-modal.element.ts
Labels: type/feature, area/frontend, release/15.4.0

#18513 Update 01_bug_report.yml
  .github/ISSUE_TEMPLATE/01_bug_report.yml
Labels: ignore-for-release

#18772 Media: Fix circular
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
Labels: ignore-for-release

#18782 Block Grid: Fix circular dependencies
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/block-grid-manager/block-grid-manager.context-token.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/block-grid-manager/block-grid-manager.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/block-grid-manager/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/block-grid-manager/index.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/clipboard/grid-block/copy/block-grid-to-grid-block-copy-translator.test.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-area-config-entry/block-grid-area-config-entry.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-area-config-entry/index.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-area/block-grid-area.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-area/index.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-areas-container/block-grid-areas-container.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-areas-container/index.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-block-inline/block-grid-block-inline.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-block-inline/index.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-block-unsupported/block-grid-block-unsupported.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-block-unsupported/index.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-block/block-grid-block.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-block/index.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entries/block-grid-entries.context-token.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entries/block-grid-entries.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entries/block-grid-entries.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entries/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entries/index.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.context-token.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entry/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entry/index.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-scale-handler/index.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/ref-grid-block/index.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/context/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/context/index.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/index.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/local-components.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-areas-config/property-editor-ui-block-grid-areas-config.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-column-span/property-editor-ui-block-grid-column-span.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-editor/property-editor-ui-block-grid.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
Labels: ignore-for-release

#18783 Dropzone: fix dropzone circular dependency
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/components/input-dropzone/input-dropzone.element.ts
Labels: ignore-for-release

#18767 UX: Make discard changes button red
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/he-il.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/ja-jp.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/ko-kr.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/pt-br.ts
  src/Umbraco.Web.UI.Client/src/packages/core/modal/common/discard-changes/discard-changes-modal.element.ts
Labels: category/ux, release/16.0.0

#18787 Dictionary cleanup: Remove duplicate keys for discard changes
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/he-il.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/ja-jp.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/ko-kr.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/pt-br.ts
Labels: type/improvement, release/16.0.0

#18789 Tiptap RTE: Statusbar extension type
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/external/tiptap/index.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/data-type/data-type.data.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/character-map/character-map-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/tiptap-statusbar.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/tiptap-toolbar.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/types.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/word-count.tiptap-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/statusbar/element-path.tiptap-statusbar-element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/statusbar/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/statusbar/word-count.tiptap-statusbar-element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/tiptap-statusbar.extension.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/types.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/components/property-editor-ui-tiptap-statusbar-configuration.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/components/property-editor-ui-tiptap-toolbar-configuration.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/contexts/tiptap-statusbar-configuration.context.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/contexts/tiptap-toolbar-configuration.context.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/property-editor-ui-tiptap.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/types.ts
Labels: type/feature, area/frontend, release/15.4.0

#18798 Feature: validation synchronization as opt in
  .vscode/settings.json
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-editor/property-editor-ui-block-grid.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block/workspace/block-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content/workspace/content-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/context/validation-messages.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/validation.controller.test.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/validation.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/submittable/submittable-workspace-context-base.ts
  src/Umbraco.Web.UI.Client/src/packages/rte/components/rte-base.element.ts
Labels: category/ux, area/frontend, release/15.4.0

#18793 Move public access files to member-public-access module
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/index.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/public-access/index.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/public-access/modal/index.ts
  src/Umbraco.Web.UI.Client/src/packages/members/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-public-access/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-public-access/index.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-public-access/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-public-access/modal/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-public-access/modal/public-access-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-public-access/modal/public-access-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-public-access/modal/types.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-public-access/public-access.action.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-public-access/repository/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-public-access/repository/index.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-public-access/repository/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-public-access/repository/public-access.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-public-access/repository/public-access.server.data.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-public-access/types.ts
  src/Umbraco.Web.UI.Client/src/packages/members/vite.config.ts
  src/Umbraco.Web.UI.Client/tsconfig.json
Labels: category/breaking, area/frontend, release/16.0.0

#18808 Feature: property type workspace validation context
  src/Umbraco.Web.UI.Client/src/packages/core/property-type/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property-type/utils/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property-type/workspace/property-type-workspace.context.ts
Labels: category/ux, area/frontend, release/15.4.0

#18815 Fix entity user permission modal preset logic
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/user-permissions/input-document-granular-user-permission/input-document-granular-user-permission.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user-permission/modals/settings/entity-user-permission-settings-modal.element.ts
Labels: ignore-for-release

#18830 build(deps): bump @umbraco-ui/uui from 1.12.2 to 1.13.0
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Login/package-lock.json
  src/Umbraco.Web.UI.Login/package.json
Labels: dependencies, area/frontend, release/13.8.0

#18667 Fix bug uploading an image via the Media Picker is no longer automatically selected
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/components/input-dropzone/input-dropzone.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/dropzone-manager.class.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/dropzone-media-manager.class.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/dropzone-media.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/dropzone/index.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
Labels: type/bug, area/frontend

#18243 Avoid a hash key generation and lookup when inserting in the LockingMechanism
  src/Umbraco.Core/Scoping/LockingMechanism.cs
  tests/Umbraco.Tests.Common/Builders/ContentBuilder.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Scoping/LockingMechanismTests.cs
Labels: community/pr, release/15.4.0

#18827 Remove syslib003 & syslib0051 obsoleted code dependencies
  src/Umbraco.Core/Exceptions/DataOperationException.cs
  src/Umbraco.Core/Exceptions/InvalidCompositionException.cs
  src/Umbraco.Core/Install/InstallException.cs
  src/Umbraco.Core/Semver/Semver.cs
Labels: category/breaking, release/16.0.0

#18838 V15: Improve the dropzone for Image Cropper
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/image-cropper-field.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/image-cropper-preview.element.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-image-cropper/input-image-cropper.element.ts
Labels: category/ux, type/feature, area/frontend, release/15.4.0

#18837 Populate parent key on move and copy notifications
  src/Umbraco.Core/Services/ContentService.cs
Labels: area/backend

#18845 Fixes Dropdown property-editor validation
  src/Umbraco.Web.UI.Client/src/packages/property-editors/dropdown/property-editor-ui-dropdown.element.ts
Labels: type/bug, area/frontend

#18847 V15: Dropzone single mode should only allow one file at a time
  src/Umbraco.Web.UI.Client/src/packages/media/dropzone/components/input-dropzone/input-dropzone.element.ts
Labels: category/ux, type/feature, area/frontend, release/15.4.0

#18849 15.3: Hotfix: Localization culture alias case-insensitive check
  src/Umbraco.Web.UI.Client/src/packages/core/localization/registry/localization.registry.ts
Labels: status/regression, area/frontend

#18813 Render Property "vary by segment"-toggle
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/workspace/views/design/content-type-design-editor-property.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property-type/workspace/views/settings/property-workspace-view-settings.element.ts
Labels: type/feature, release/15.4.0

#18810 Adds MemberTwoFactorLoginService
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Core/Services/IMemberTwoFactorLoginService.cs
  src/Umbraco.Core/Services/ITwoFactorLoginService.cs
  src/Umbraco.Core/Services/MemberTwoFactorLoginService.cs
  src/Umbraco.Core/Services/UserTwoFactorLoginService.cs
Labels: status/needs-docs, area/backend

#18821 Feature: make load more 100p wide
  src/Umbraco.Web.UI.Client/src/packages/core/tree/default/default-tree.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/tree/document-tree.element.ts
Labels: ignore-for-release

#18873 Fix select all checkbox in scheduled publishing
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/schedule-publish/modal/document-schedule-modal.element.ts
Labels: type/bug, area/frontend, release/15.4.0

#18860 Unpublish Document: Align UX of referenced items with trash and delete
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/unpublish/modal/document-unpublish-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/reference/components/document-reference-table.element.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/bulk-delete/modal/bulk-delete-with-relation-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/bulk-trash/modal/bulk-trash-with-relation-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/delete/modal/delete-with-relation-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/trash/modal/trash-with-relation-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/global-components/confirm-action-modal-entity-references.element.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/global-components/confirm-bulk-action-modal-entity-references.element.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/global-components/index.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/global-components/types.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/index.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/types.ts
Labels: category/ux, type/bug, release/15.4.0

#18865 Implement context base for a few last contexts
  src/Umbraco.Web.UI.Client/examples/workspace-context-counter/counter-workspace-context.ts
  src/Umbraco.Web.UI.Client/src/apps/backoffice/components/backoffice-main.element.ts
  src/Umbraco.Web.UI.Client/src/apps/installer/error/installer-error.stories.ts
  src/Umbraco.Web.UI.Client/src/apps/installer/installer.context.ts
  src/Umbraco.Web.UI.Client/src/apps/installer/installer.element.ts
  src/Umbraco.Web.UI.Client/src/apps/installer/shared/utils.story-helpers.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/backoffice-modal-container/backoffice-modal-container.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/menu/components/menu/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/menu/components/menu/menu.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/menu/components/menu/menu.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/menu/conditions/menu-alias.condition.ts
  src/Umbraco.Web.UI.Client/src/packages/core/section/section.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/global-contexts/document-configuration.context.ts
  src/Umbraco.Web.UI.Client/src/packages/health-check/dashboard-health-check.element.ts
  src/Umbraco.Web.UI.Client/src/packages/health-check/health-check-dashboard.context.ts
  src/Umbraco.Web.UI.Client/src/packages/log-viewer/workspace/logviewer-workspace.context.ts
Labels: area/frontend, affected/v15, release/15.4.0

#18876 V15: Removes flaky localization tests
  src/Umbraco.Web.UI.Client/src/libs/localization-api/localization.controller.test.ts
Labels: area/test

#18879 V15: Revert "Fix: RTE markup props not up to date issue"
  src/Umbraco.Web.UI.Client/src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiny-mce/property-editors/tiny-mce/property-editor-ui-tiny-mce.element.ts
Labels: type/bug, area/frontend

#18836 V15: bump @umbraco-ui/uui from 1.12.2 to 1.13.0
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
Labels: dependencies, area/frontend, release/15.4.0

#18786 Chore: set circular dependency limit
  src/Umbraco.Web.UI.Client/devops/circular/index.js
  src/Umbraco.Web.UI.Client/src/packages/core/tree/expansion-manager/tree-expansion-manager.test.ts
Labels: area/frontend, ignore-for-release

#18587 Fix issue text overflow when user name is too long
  src/Umbraco.Web.UI.Client/src/packages/user/user/collection/views/grid/user-grid-collection-view.element.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Settings/DocumentType/DocumentTypeDesignTab.spec.ts
Labels: category/ux, category/accessibility, type/bug, area/frontend
