Repository umbraco/Umbraco-CMS, pull requests merged in 2025-02, with the labels that each got.

#18205 Corrects filename label on the Upload File component
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/preview/input-upload-field-file.element.ts
Labels: area/frontend

#18171 V15/feature/toggle property editor UI
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/input-toggle/input-toggle.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/toggle/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/toggle/property-editor-ui-toggle.element.ts
Labels: area/frontend

#18188 V15: Add progress UI to the Upload Field property editor
  src/Umbraco.Web.UI.Client/src/packages/core/resources/apiTypeValidators.function.ts
  src/Umbraco.Web.UI.Client/src/packages/core/resources/resource.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/resources/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/temporary-file-manager.class.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/temporary-file.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/temporary-file.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/types.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-upload-field/input-upload-field.element.ts
Labels: category/ux, type/feature, area/frontend, release/15.3.0

#18201 Localize reference block labels and properties in the block editing experience
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block/context/block-entry.context.ts
Labels: area/frontend

#18194 Fixes #17206
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/controllers/validation.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/mixins/form-control.mixin.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/utils/replace-start-of-path.function.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/utils/replace-start-of-path.test.ts
Labels: area/frontend

#18203 Corrected rendering of member type icons on create button and picker
  src/Umbraco.Web.UI.Client/src/packages/members/member/collection/action/create-member-collection-action.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/collection/repository/member-collection.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/components/input-member/input-member.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/components/member-picker-modal/member-picker-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/repository/detail/member-detail.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/types.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/workspace/member/member-workspace.context.ts
Labels: area/frontend

#18182 Fixes #18000 - Unsupported Block
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/nb-no.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/media-type/media-type.db.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-custom-view/types.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-block-unsupported/block-grid-block-unsupported.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-block-unsupported/index.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entries/block-grid-entries.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/components/block-list-entry/block-list-entry.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/components/unsupported-list-block/index.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/components/unsupported-list-block/unsupported-list-block.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block/context/block-entry.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/sorter/sorter.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/temporary-file/temporary-file.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-split-view/workspace-split-view-variant-selector.element.ts
  src/Umbraco.Web.UI.Client/src/packages/health-check/views/health-check-overview.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/conditions/allow-change-password/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/entity-actions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/repository/config/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/repository/config/current-user-config.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/repository/config/current-user-config.store.token.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/repository/config/manifests.ts
Labels: area/frontend

#18206 V13: Fix members while using basic auth.
  src/Umbraco.Core/EmbeddedResources/Snippets/LoginStatus.cshtml
  src/Umbraco.Web.Common/Extensions/HttpContextExtensions.cs
  src/Umbraco.Web.Common/Extensions/MemberClaimsPrincipalExtensions.cs
  src/Umbraco.Web.Common/Security/MemberManager.cs
Labels: area/backend

#17966 V15 QA Added acceptance tests to verify the SVG thumbnail
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Content/ContentWithUploadVectorGraphics.spec.ts
  tests/Umbraco.Tests.AcceptanceTest/tests/DefaultConfig/Media/Media.spec.ts
Labels: area/test

#18198 Set Smidge cachebuster type
  src/Umbraco.Web.Common/RuntimeMinification/SmidgeOptionsSetup.cs
  src/Umbraco.Web.Common/RuntimeMinification/SmidgeRuntimeMinifier.cs
Labels: community/pr, release/13.7.0

#18216 Deprecate get unique param on UmbPickerInputContext and UmbRepositoryItemsManager
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-area-type-permission/block-grid-area-type-permission.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-type/components/block-type-card/block-type-card.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-type/workspace/block-type-workspace-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/picker-input/picker-input.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/repository/repository-items.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/components/input-document/input-document.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
  src/Umbraco.Web.UI.Client/src/packages/webhook/webhook/repository/detail/webhook-detail.repository.ts
Labels: category/dx, area/frontend, release/15.3.0

#15576 Cache null dictionary values by key
  src/Umbraco.Core/Cache/RepositoryCachePolicyOptions.cs
  src/Umbraco.Infrastructure/Cache/DefaultRepositoryCachePolicy.cs
  src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DictionaryRepository.cs
Labels: community/pr, area/backend, release/13.7.0

#18219 RTE TinyMCE: Compares previous value in `#onChange` event
  src/Umbraco.Web.UI.Client/src/packages/rte/components/rte-base.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiny-mce/property-editors/tiny-mce/property-editor-ui-tiny-mce.element.ts
Labels: area/frontend

#18228 Bugfix: Reload recycle bin on trashed entity
  src/Umbraco.Web.UI.Client/src/packages/core/recycle-bin/entity-action/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/recycle-bin/entity-action/trash/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/recycle-bin/entity-action/trash/trash.action.ts
  src/Umbraco.Web.UI.Client/src/packages/core/recycle-bin/entity-action/trash/trash.event.ts
  src/Umbraco.Web.UI.Client/src/packages/core/recycle-bin/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/core/recycle-bin/tree/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/core/recycle-bin/tree/tree-item/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/core/recycle-bin/tree/tree-item/recycle-bin-tree-item.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/recycle-bin/tree/tree-item/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/default/default-tree.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-base/tree-item-context-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-default/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-default/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-default/tree-item-default.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/recycle-bin/tree/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/recycle-bin/tree/data/document-recycle-bin-tree.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/recycle-bin/tree/data/document-recycle-bin-tree.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/recycle-bin/tree/data/document-recycle-bin-tree.store.context-token.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/recycle-bin/tree/data/document-recycle-bin-tree.store.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/recycle-bin/tree/data/index.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/recycle-bin/tree/data/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/recycle-bin/tree/index.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/recycle-bin/tree/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/recycle-bin/tree/tree-item/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/recycle-bin/tree/manifests.ts
Labels: category/ux, area/frontend, release/15.3.0

#16202 Review: Allow Duplicate Email for Members
  src/Umbraco.Core/Configuration/Models/SecuritySettings.cs
  src/Umbraco.Core/Services/IMemberService.cs
  src/Umbraco.Core/Services/MemberService.cs
  src/Umbraco.Web.BackOffice/Controllers/MemberController.cs
  src/Umbraco.Web.BackOffice/Filters/MemberSaveModelValidator.cs
  src/Umbraco.Web.BackOffice/Filters/MemberSaveValidationAttribute.cs
  src/Umbraco.Web.Common/Security/ConfigureMemberIdentityOptions.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Web.BackOffice/Controllers/MemberControllerUnitTests.cs
Labels: state/sprint-candidate, area/backend

#18237 Correct icon and label for media type create option
  src/Umbraco.Web.UI.Client/src/packages/media/media-types/entity-actions/create/default/manifests.ts
Labels: area/frontend

#18240 Management API authorization for requests to rollback.
  src/Umbraco.Cms.Api.Management/Controllers/DocumentVersion/RollbackDocumentVersionController.cs
Labels: area/backend

#18247 Fixes new "Document Type with Template" filename casing
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/workspace/document-type/document-type-workspace.context.ts
Labels: area/frontend

#18254 Fix issues in newly added buttongroup localization
  src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbbuttongroup.directive.js
Labels: area/frontend, affected/v13

#18257 Fix 11643
  src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.component.js
Labels: area/frontend, affected/v13

#18264 Property editor settings translation for DK&US
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
Labels: area/frontend

#18217 Adds name and description to webhooks
  src/Umbraco.Cms.Api.Management/Factories/WebhookPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Mapping/Item/ItemTypeMapDefinition.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/Webhook/WebhookModelBase.cs
  src/Umbraco.Core/Models/IWebhook.cs
  src/Umbraco.Core/Models/Webhook.cs
  src/Umbraco.Core/Services/WebhookService.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
  src/Umbraco.Infrastructure/Migrations/Upgrade/V_15_3_0/AddNameAndDescriptionToWebhooks.cs
  src/Umbraco.Infrastructure/Persistence/Dtos/WebhookDto.cs
  src/Umbraco.Infrastructure/Persistence/Factories/WebhookFactory.cs
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/external/backend-api/src/types.gen.ts
  src/Umbraco.Web.UI.Client/src/packages/webhook/webhook-root/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/webhook/webhook-root/paths.ts
  src/Umbraco.Web.UI.Client/src/packages/webhook/webhook/collection/repository/webhook-collection.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/webhook/webhook/collection/views/table/column-layouts/content-type/webhook-table-name-column-layout.element.ts
  src/Umbraco.Web.UI.Client/src/packages/webhook/webhook/collection/views/table/webhook-table-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/webhook/webhook/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/webhook/webhook/paths.ts
  src/Umbraco.Web.UI.Client/src/packages/webhook/webhook/repository/detail/webhook-detail.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/webhook/webhook/types.ts
  src/Umbraco.Web.UI.Client/src/packages/webhook/webhook/workspace/views/webhook-details-workspace-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/webhook/webhook/workspace/webhook-workspace-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/webhook/webhook/workspace/webhook-workspace.context.ts
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/WebhookServiceTests.cs
Labels: area/frontend, area/backend

#18261 Add validation to prevent update of a user or member to an invalid username (13)
  src/Umbraco.Web.BackOffice/Controllers/MemberController.cs
  src/Umbraco.Web.BackOffice/Controllers/UsersController.cs
  src/Umbraco.Web.UI.Client/src/views/users/views/user/details.html
Labels: area/backend

#18271 Feature: Fewer redirects
  src/Umbraco.Web.UI.Client/src/apps/backoffice/backoffice.context.ts
  src/Umbraco.Web.UI.Client/src/apps/backoffice/components/backoffice-main.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/section/section-main-views/section-main-views.element.ts
Labels: area/frontend

#18250 Picker search result item icons for Documents and Members
  src/Umbraco.Web.UI.Client/src/packages/core/picker/search/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/picker/search/result-item/default/default-picker-search-result-item.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/picker/search/result-item/default/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/picker/search/result-item/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/picker/search/result-item/picker-search-result-item-element-base.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/picker/document-picker-search-result-item.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/picker/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/picker/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/picker/member-picker-search-result-item.element.ts
Labels: area/frontend

#18274 V15: Bump minimum required Node.js to V22
  src/Umbraco.Web.UI.Client/.nvmrc
  src/Umbraco.Web.UI.Client/package-lock.json
  src/Umbraco.Web.UI.Client/package.json
  src/Umbraco.Web.UI.Login/.nvmrc
  src/Umbraco.Web.UI.Login/package-lock.json
  src/Umbraco.Web.UI.Login/package.json
  src/Umbraco.Web.UI.Login/public/mockServiceWorker.js
Labels: dependencies, category/dx, area/frontend, release/15.3.0

#18142 URL encodes member user names when passing information for public access setting such that those with user names as emails containing a plus will be included in the rule
  src/Umbraco.Web.UI.Client/src/common/resources/publicaccess.resource.js
Labels: area/frontend

#18295 V15/feature/history cleanup localization
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-types/workspace/document-type/views/settings/document-type-workspace-view-settings.element.ts
Labels: area/frontend

#18151 Backport use of thread delay over sleep and handle dispose in FileSystemMainDomLock
  src/Umbraco.Infrastructure/Runtime/FileSystemMainDomLock.cs
Labels: area/backend

#18299 Feature: workspace action additional options ellipsis
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action-menu-item/default/workspace-action-menu-item.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action-menu-item/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action-menu-item/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action/common/submit/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action/common/submit/submit.action.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action/common/submit/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action/default/default.action.kind.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action/default/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action/default/workspace-action-default-kind.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action/default/workspace-action-default-kind.interface.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/components/workspace-action/workspace-action.interface.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/extensions/workspace-action.model.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/types.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish/workspace-action/save-and-publish.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/actions/save.action.ts
Labels: category/ux, area/frontend, release/15.3.0

#18298 Fix: #17676
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content/workspace/views/edit/content-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/router/components/not-found/route-not-found.element.ts
Labels: area/frontend

#18270 Split force for publish descendants into separate options for publish unpublish and re-publish unedited (15)
  src/Umbraco.Cms.Api.Management/Controllers/Document/PublishDocumentWithDescendantsController.cs
  src/Umbraco.Cms.Api.Management/OpenApi.json
  src/Umbraco.Cms.Api.Management/ViewModels/Document/PublishDocumentWithDescendantsRequestModel.cs
  src/Umbraco.Core/Models/PublishBranchFilter.cs
  src/Umbraco.Core/Services/ContentPublishingService.cs
  src/Umbraco.Core/Services/ContentService.cs
  src/Umbraco.Core/Services/IContentPublishingService.cs
  src/Umbraco.Core/Services/IContentService.cs
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/external/backend-api/src/types.gen.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish-with-descendants/modal/document-publish-with-descendants-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish-with-descendants/modal/document-publish-with-descendants-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/repository/document-publishing.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/repository/document-publishing.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/workspace-context/document-publishing.workspace-context.ts
  tests/Umbraco.TestData/UmbracoTestDataController.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentUrlServiceTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentUrlServiceTest_hidetoplevel_false.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/PublishStatusServiceTest.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/PublishedUrlInfoProviderTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/PublishedUrlInfoProvider_hidetoplevel_false.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEventsTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentPublishingServiceTests.Publish.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServicePublishBranchTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServiceTagsTests.cs
Labels: status/needs-docs, area/frontend, area/backend

#18221 Feature: block type element not found
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-type/components/block-type-card/block-type-card.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/repository/repository-items.manager.ts
Labels: category/ux, area/frontend

#18249 Split force for publish descendants into separate options for publish unpublish and re-publish unedited (13)
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Core/Models/ContentEditing/ContentSaveAction.cs
  src/Umbraco.Core/Models/PublishBranchFilter.cs
  src/Umbraco.Core/Services/ContentService.cs
  src/Umbraco.Core/Services/IContentService.cs
  src/Umbraco.Web.BackOffice/Controllers/ContentController.cs
  src/Umbraco.Web.BackOffice/Filters/ContentSaveValidationAttribute.cs
  src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js
  src/Umbraco.Web.UI.Client/src/common/resources/content.resource.js
  src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.controller.js
  src/Umbraco.Web.UI.Client/src/views/content/overlays/publishdescendants.html
  tests/Umbraco.TestData/UmbracoTestDataController.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/ContentServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentEventsTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServicePublishBranchTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/Services/ContentServiceTagsTests.cs
Labels: status/needs-docs, area/frontend, area/backend

#18308 Chore: Fix circular dependency in picker module
  src/Umbraco.Web.UI.Client/src/packages/core/picker/search/result-item/picker-search-result-item-element-base.ts
Labels: internal, ignore-for-release

#17868 Resolves issues related to the setting of a schedule for content publishing
  src/Umbraco.Cms.Api.Management/Controllers/Document/ByKeyDocumentController.cs
  src/Umbraco.Cms.Api.Management/Controllers/Document/ByKeyPublishedDocumentController.cs
  src/Umbraco.Cms.Api.Management/Factories/DocumentPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Factories/IDocumentPresentationFactory.cs
  src/Umbraco.Cms.Api.Management/Mapping/Document/DocumentMapDefinition.cs
  src/Umbraco.Cms.Api.Management/ViewModels/Document/DocumentVariantResponseModel.cs
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/libs/observable-api/utils/append-to-frozen-array.function.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/conditions/const.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/conditions/workspace-entity-is-new.condition.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/pending-changes/document-published-pending-changes.manager.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish/entity-bulk-action/publish.bulk-action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/repository/document-publishing.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/schedule-publish/modal/document-schedule-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/schedule-publish/modal/document-schedule-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/schedule-publish/workspace-action/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/unpublish/entity-bulk-action/unpublish.bulk-action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/unpublish/workspace-action/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/workspace-context/document-publishing.workspace-context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/repository/detail/document-detail.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/types.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts
Labels: area/frontend, area/backend

#18212 Removes collection action state
  src/Umbraco.Web.UI.Client/src/libs/localization-api/localization.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/collection/action/collection-action-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/collection/action/collection-action-button.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/collection/action/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/core/collection/extensions/collection-action.extension.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/default/entity-action.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/action/create-document-collection-action.element.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user/invite/collection-action/manifests.ts
Labels: category/ux, type/bug, area/frontend

#18330 Chore: Remove the `propertyEditorSchemaAlias` for "Accepted Upload Types"
  src/Umbraco.Web.UI.Client/src/packages/property-editors/accepted-types/manifests.ts
Labels: area/frontend, ignore-for-release

#18329 Help Header App, popover placement + code tidy-up
  src/Umbraco.Web.UI.Client/src/packages/help/header-app/help-header-app.element.ts
Labels: category/ui, type/feature, area/frontend, release/15.3.0

#18327 Content dashboard, info box drop-shadow
  src/Umbraco.Web.UI.Client/src/packages/umbraco-news/umbraco-news-dashboard.element.ts
Labels: category/ui, type/feature, area/frontend, release/15.3.0

#18322 LinkedIn icon, adds `currentColor` fill
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-linkedin.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/svgs/icon-linkedin.svg
Labels: type/bug, area/frontend, affected/v15

#18323 Property actions: adds localization support
  src/Umbraco.Web.UI.Client/src/packages/core/property-action/kinds/default/property-action.element.ts
Labels: type/bug, area/frontend

#18338 Data Type create option description
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/data-type/entity-actions/create/default/manifests.ts
Labels: area/frontend

#18341 V15: Show duration on time displays
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/libs/localization-api/localization.controller.test.ts
  src/Umbraco.Web.UI.Client/src/libs/localization-api/localization.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/localization/localize-date.element.test.ts
  src/Umbraco.Web.UI.Client/src/packages/core/localization/localize-date.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/localization/localize-relative-time.element.ts
Labels: category/ux, type/feature, area/frontend

#18339 V15: Add a button to clear schedule
  src/Umbraco.Web.UI.Client/src/assets/lang/bs.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/cs-cz.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/cy-gb.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/de-de.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/es-es.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/fr-fr.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/hr-hr.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/it-it.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/nl-nl.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/ru-ru.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/tr-tr.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/uk-ua.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/document/document-publishing.manager.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/document/publishing.handlers.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/input-date/input-date.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/schedule-publish/modal/document-schedule-modal.element.ts
Labels: category/ux, type/feature, area/frontend, release/15.3.0

#18302 Allow for multiple backoffice hosts
  src/Umbraco.Cms.Api.Management/Middleware/BackOfficeAuthorizationInitializationMiddleware.cs
  src/Umbraco.Cms.Api.Management/Security/BackOfficeApplicationManager.cs
  src/Umbraco.Cms.Api.Management/Umbraco.Cms.Api.Management.csproj
  src/Umbraco.Infrastructure/Security/IBackOfficeApplicationManager.cs
  tests/Umbraco.Tests.Integration/ManagementApi/ManagementApiTest.cs
Labels: area/backend

#18287 Only filter post retrieval of entities for start nodes if working with entities that support start nodes
  src/Umbraco.Web.BackOffice/Controllers/EntityController.cs
Labels: area/backend

#18326 Markdown Editor: adds "Default value" support
  src/Umbraco.Web.UI.Client/src/packages/markdown-editor/property-editors/markdown-editor/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/markdown-editor/property-editors/markdown-editor/property-editor-ui-markdown-editor.element.ts
Labels: category/dx, type/bug, area/frontend, release/15.3.0

#18344 V15: Save the variant before scheduling
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/libs/localization-api/localization.controller.test.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/data-type/data-type.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/handlers/document/detail.handlers.ts
  src/Umbraco.Web.UI.Client/src/packages/core/utils/path/umbraco-path.function.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish/entity-action/publish.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/publish/entity-bulk-action/publish.bulk-action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/repository/document-publishing.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/workspace-context/document-publishing.workspace-context.ts
Labels: category/ux, type/feature, area/frontend, release/15.3.0

#18357 Chore: Tiptap mock data update
  src/Umbraco.Web.UI.Client/src/mocks/data/data-type/data-type.data.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/document/document.data.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/property-editor-ui-tiptap.stories.ts
Labels: area/frontend, ignore-for-release

#18358 Chore: Relocate Tiptap Block extension files
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/block/block.tipap-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/block/block.tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/block/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/manifests.ts
Labels: area/frontend, ignore-for-release

#18363 Fix #18215
  src/Umbraco.Web.UI.Client/src/packages/core/modal/component/modal.element.ts
Labels: area/frontend

#18364 Tiptap RTE: Cascading Style Select Menu
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/cascading-menu-popover/cascading-menu-popover.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/index.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/tiptap-toolbar.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/toolbar/default-tiptap-toolbar-element.api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/toolbar/tiptap-toolbar-button.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/toolbar/tiptap-toolbar-dropdown-base.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/style-select/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/style-select/style-select-tiptap-toolbar.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/style-select.tiptap-toolbar-api.ts
Labels: type/feature, area/frontend, release/15.3.0

#18311 Feature: Display current variant item name
  src/Umbraco.Web.UI.Client/src/packages/core/tree/tree-item/tree-item-base/tree-item-element-base.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/repository/document-collection.server.data-source.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/types.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/views/table/column-layouts/document-table-column-name.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/views/table/column-layouts/document-table-column-state.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/views/table/document-table-collection-view.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/item/document-item-data-resolver.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/item/document-item-ref.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/item/index.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/item/repository/types.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/tree/tree-item/document-tree-item.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/tree/tree-item/document-tree-item.element.ts
  src/Umbraco.Web.UI.Client/utils/all-umb-consts/index.ts
Labels: category/ux, type/feature, area/frontend, release/15.3.0

#18373 build(deps-dev): update npm dependencies for login screen
  src/Umbraco.Web.UI.Login/package-lock.json
  src/Umbraco.Web.UI.Login/package.json
Labels: dependencies, area/frontend, release/15.3.0

#18382 Tiptap RTE: Ensure core extension is loaded
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/rich-text-essentials.tiptap-api.ts
Labels: area/frontend, ignore-for-release

#18365 Tiptap RTE: Table extension enhancements
  src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-umb-table.extension.ts
  src/Umbraco.Web.UI.Client/src/external/tiptap/index.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/cascading-menu-popover/cascading-menu-popover.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/tiptap-hover-menu.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/base.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/table.tiptap-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/components/table-insert.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/table-tiptap-toolbar-button.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/table.tiptap-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/table.tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/table.tiptap-toolbar-api.ts
Labels: type/feature, area/frontend, release/15.3.0

#18321 Chore: Block Manager + Variant ID Polishing
  src/Umbraco.Web.UI.Client/src/packages/block/block/workspace/block-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/core/variant/variant-id.class.ts
  src/Umbraco.Web.UI.Client/src/packages/language/global-contexts/app-language.context.ts
Labels: area/frontend, ignore-for-release

#18224 Feature: block grid block type area/root validation
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entries/block-grid-entries.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/context/block-grid-entries.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/context/block-grid-entry.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block/context/block-entry.context.ts
Labels: area/frontend

#18303 Fix: #17500
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/property-editors/block-grid-editor/property-editor-ui-block-grid.element.ts
Labels: area/frontend

#18333 Toggle property Value labels and validation
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/input-toggle/input-toggle.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/const.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/toggle/property-editor-ui-toggle.element.ts
Labels: area/frontend

#18351 Feature: Delete/Trash referenced by
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/ref-item/ref-item.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/common/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/common/delete/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/common/delete/delete.action.kind.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/common/delete/delete.action.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/common/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/recycle-bin/entity-action/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/core/recycle-bin/entity-action/trash/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/core/recycle-bin/entity-action/trash/trash.action.kind.ts
  src/Umbraco.Web.UI.Client/src/packages/core/recycle-bin/entity-action/trash/trash.action.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/entity-actions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/recycle-bin/entity-action/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/reference/components/document-reference-table.element.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/reference/repository/document-reference.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/reference/repository/document-reference.server.data.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/entity-actions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/item/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/recycle-bin/entity-action/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/reference/repository/media-reference.repository.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/reference/repository/media-reference.server.data.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/delete/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/delete/delete-with-relation.action.kind.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/delete/delete-with-relation.action.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/delete/index.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/delete/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/delete/modal/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/delete/modal/delete-with-relation-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/delete/modal/delete-with-relation-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/delete/modal/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/delete/types.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/local-components/confirm-action-entity-references.element.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/trash/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/trash/index.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/trash/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/trash/modal/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/trash/modal/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/trash/modal/trash-with-relation-modal.element.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/trash/modal/trash-with-relation-modal.token.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/trash/trash-with-relation.action.kind.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/trash/trash-with-relation.action.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/entity-actions/trash/types.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/reference/types.ts
  src/Umbraco.Web.UI.Client/src/packages/relations/relations/types.ts
Labels: type/feature, area/frontend, release/15.3.0

#18414 V15: A user cannot switch back to the default language
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/core/localization/registry/localization.registry.test.ts
  src/Umbraco.Web.UI.Client/src/packages/core/localization/registry/localization.registry.ts
Labels: category/ux, area/frontend, release/15.3.0

#18404 Bugfix: can't remove items from a picker
  src/Umbraco.Web.UI.Client/src/packages/core/repository/repository-items.manager.ts
Labels: ignore-for-release

#18310 Implement create options for Member Types + Fix issue when single option is a link
  src/Umbraco.Web.UI.Client/src/packages/core/components/entity-actions-bundle/entity-actions-bundle.element.ts
  src/Umbraco.Web.UI.Client/src/packages/core/entity-action/common/create/create.action.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/constants.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/entity-actions/create.action.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/entity-actions/create/default/default-member-type-create-option-action.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/entity-actions/create/default/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/entity-actions/create/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/entity-actions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member-type/paths.ts
Labels: category/dx, area/frontend, release/15.3.0

#18438 Fix validation for blocks in variant block editors
  src/Umbraco.Infrastructure/PropertyEditors/BlockEditorValidatorBase.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/BlockListElementLevelVariationTests.Validation.cs
  tests/Umbraco.Tests.Integration/Umbraco.Infrastructure/PropertyEditors/BlockListElementLevelVariationTests.cs
Labels: release/15.3.0

#18445 Fix #18431
  src/Umbraco.Web.UI.Client/src/packages/core/content/manager/content-data-manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content/manager/element-data-manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/variant/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/variant/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/variant/variant-id.class.ts
  src/Umbraco.Web.UI.Client/src/packages/core/variant/variant-object-compare.function.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/entity/entity-workspace-data-manager.ts
Labels: area/frontend

#18396 Add Localization to Documentation Types - Structure - Collection
  src/Umbraco.Web.UI.Client/src/assets/lang/da-dk.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/core/components/input-collection-configuration/input-collection-configuration.element.ts
Labels: category/ux, type/bug, area/frontend, release/15.3.0

#18449 Restored minimal default permissions for the writer user group
  src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs
Labels: area/backend, release/15.3.0

#18437 V15: Adds validation on date from/to inputs in the schedule modal
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/schedule-publish/modal/document-schedule-modal.element.ts
Labels: category/ux, type/feature, area/frontend, release/15.3.0

#18281 Published status filtering
  src/Umbraco.Cms.Api.Delivery/Services/ApiMediaQueryService.cs
  src/Umbraco.Cms.Api.Management/Controllers/Template/Query/ExecuteTemplateQueryController.cs
  src/Umbraco.Core/DeliveryApi/ApiContentRouteBuilder.cs
  src/Umbraco.Core/DependencyInjection/UmbracoBuilder.cs
  src/Umbraco.Core/EmbeddedResources/Snippets/ListDescendantsFromCurrentPage.cshtml
  src/Umbraco.Core/EmbeddedResources/Snippets/SiteMap.cshtml
  src/Umbraco.Core/Events/AddUnroutableContentWarningsWhenPublishingNotificationHandler.cs
  src/Umbraco.Core/Extensions/PublishedContentExtensions.cs
  src/Umbraco.Core/Models/PublishedContent/PublishedContentBase.cs
  src/Umbraco.Core/Models/PublishedContent/PublishedValueFallback.cs
  src/Umbraco.Core/PublishedCache/Internal/InternalPublishedContent.cs
  src/Umbraco.Core/Routing/AliasUrlProvider.cs
  src/Umbraco.Core/Routing/ContentFinderByUrlAlias.cs
  src/Umbraco.Core/Routing/DefaultUrlProvider.cs
  src/Umbraco.Core/Routing/DomainUtilities.cs
  src/Umbraco.Core/Routing/NewDefaultUrlProvider.cs
  src/Umbraco.Core/Routing/UrlProvider.cs
  src/Umbraco.Core/Routing/UrlProviderExtensions.cs
  src/Umbraco.Core/Services/PublishStatus/IPublishedContentStatusFilteringService.cs
  src/Umbraco.Core/Services/PublishStatus/IPublishedMediaStatusFilteringService.cs
  src/Umbraco.Core/Services/PublishStatus/IPublishedStatusFilteringService.cs
  src/Umbraco.Core/Services/PublishStatus/PublishedContentStatusFilteringService.cs
  src/Umbraco.Core/Services/PublishStatus/PublishedMediaStatusFilteringService.cs
  src/Umbraco.Infrastructure/Routing/RedirectTracker.cs
  src/Umbraco.PublishedCache.HybridCache/PublishedContent.cs
  src/Umbraco.Web.Common/Extensions/FriendlyPublishedContentExtensions.cs
  src/Umbraco.Web.Common/Extensions/PublishedContentExtensions.cs
  src/Umbraco.Web.Website/Controllers/UmbLoginController.cs
  tests/Umbraco.Tests.Integration/Umbraco.Core/Services/DocumentNavigationServiceTests.cs
  tests/Umbraco.Tests.Integration/Umbraco.Web.BackOffice/UrlAndDomains/DomainAndUrlsTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ContentBuilderTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/ContentRouteBuilderTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/DeliveryApiTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/MultiNodeTreePickerValueConverterTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/DeliveryApi/PropertyValueConverterTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Routing/ContentFinderByUrlAliasTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Services/PublishStatus/PublishedContentStatusFilteringServiceTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Templates/HtmlImageSourceParserTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/Templates/HtmlLocalLinkParserTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Tests.UnitTests.csproj
Labels: release/15.3.0

#18429 V15: Serverside Media Picker Validation
  src/Umbraco.Core/EmbeddedResources/Lang/da.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en.xml
  src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml
  src/Umbraco.Core/PropertyEditors/Validation/ITypedJsonValidator.cs
  src/Umbraco.Core/PropertyEditors/Validation/TypedJsonValidatorRunner.cs
  src/Umbraco.Infrastructure/PropertyEditors/MediaPicker3PropertyEditor.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/DataValueReferenceFactoryCollectionTests.cs
  tests/Umbraco.Tests.UnitTests/Umbraco.Core/PropertyEditors/MediaPicker3ValueEditorValidationTests.cs
Labels: release/15.3.0

#18423 Feature: Property Value Preset
  src/Umbraco.Web.UI.Client/src/libs/extension-api/controller/base-extensions-initializer.controller.ts
  src/Umbraco.Web.UI.Client/src/libs/extension-api/functions/create-extension-api.function.ts
  src/Umbraco.Web.UI.Client/src/libs/extension-api/registry/extension.registry.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/context/block-grid-entries.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-grid/context/block-grid-manager.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/context/block-list-entries.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/context/block-list-manager.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-rte/context/block-rte-entries.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-rte/context/block-rte-manager.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block/context/block-entry.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block/context/block-manager.context.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block/workspace/block-element-manager.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/structure/content-type-structure-manager.class.ts
  src/Umbraco.Web.UI.Client/src/packages/core/content/workspace/content-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property-editor/config/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property-editor/config/property-editor-config-collection.class.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property-editor/config/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property-editor/extensions/property-editor.extension.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property-editor/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property-editor/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/property-value-cloner/property-value-clone.controller.test.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/property-value-cloner/property-value-clone.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/property-value-preset/index.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/property-value-preset/property-value-preset-builder.controller.test.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/property-value-preset/property-value-preset-builder.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/property-value-preset/property-value-preset-variant-builder.controller.test.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/property-value-preset/property-value-preset-variant-builder.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/property-value-preset/property-value-preset.extension.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/property-value-preset/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/property-value-resolver/property-value-resolver.extension.ts
  src/Umbraco.Web.UI.Client/src/packages/core/property/types.ts
  src/Umbraco.Web.UI.Client/src/packages/core/workspace/entity-detail/entity-detail-workspace-base.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/document-blueprints/workspace/document-blueprint-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/workspace/document-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/language/global-contexts/app-language.context.ts
  src/Umbraco.Web.UI.Client/src/packages/markdown-editor/components/input-markdown-editor/input-markdown.element.ts
  src/Umbraco.Web.UI.Client/src/packages/markdown-editor/property-editors/markdown-editor/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/markdown-editor/property-editors/markdown-editor/markdown-editor-property-value-preset.ts
  src/Umbraco.Web.UI.Client/src/packages/markdown-editor/property-editors/markdown-editor/property-editor-ui-markdown-editor.element.ts
  src/Umbraco.Web.UI.Client/src/packages/markdown-editor/property-editors/markdown-editor/types.ts
  src/Umbraco.Web.UI.Client/src/packages/media/media/workspace/media-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/members/member/workspace/member/member-workspace.context.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/index.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/slider/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/slider/property-editor-ui-slider.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/slider/slider-property-value-preset.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/slider/types.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/toggle/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/toggle/property-editor-ui-toggle.element.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/toggle/true-false-property-value-preset.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/toggle/types.ts
  src/Umbraco.Web.UI.Client/src/packages/property-editors/types.ts
  src/Umbraco.Web.UI.Client/src/packages/user/user-group/workspace/user-group/user-group-workspace-editor.element.ts
Labels: category/ux, type/feature, area/frontend, release/15.3.0

#18278 Feature: Simpler app language request
  src/Umbraco.Web.UI.Client/src/packages/language/global-contexts/app-language.context.ts
Labels: area/frontend

#18125 Tiptap RTE: configuration localizations
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
  src/Umbraco.Web.UI.Client/src/packages/rte/Umbraco.RichText.ts
  src/Umbraco.Web.UI.Client/src/packages/tiny-mce/property-editors/tiny-mce/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/source-editor.tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/manifests.ts
Labels: type/feature, area/frontend

#18280 Feature: enforce block variations to be present in all mandatory languages
  src/Umbraco.Web.UI.Client/src/packages/block/block/context/block-manager.context.ts
Labels: category/ux, area/frontend

#18447 Chore: Tiptap code sweep
  src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-umb-image.extension.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/tiptap-toolbar.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/block/block.tipap-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/block/block.tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/link.tiptap-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/media-upload.tiptap-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/rich-text-essentials.tiptap-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/redo.tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/undo.tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/unlink.tiptap-toolbar-api.ts
Labels: area/frontend, ignore-for-release

#18433 V15: Schedule only languages you have access to
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/publishing/schedule-publish/modal/document-schedule-modal.element.ts
Labels: category/ux, type/bug, area/frontend, release/15.3.0

#18459 Tiptap RTE: Text Direction extension
  src/Umbraco.Web.UI.Client/src/external/tiptap/extensions/tiptap-text-direction-extension.ts
  src/Umbraco.Web.UI.Client/src/external/tiptap/index.ts
  src/Umbraco.Web.UI.Client/src/mocks/data/data-type/data-type.data.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icon-dictionary.json
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-text-direction-ltr.ts
  src/Umbraco.Web.UI.Client/src/packages/core/icon-registry/icons/icon-text-direction-rtl.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/text-direction.tiptap-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/text-direction-ltr.tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/text-direction-rtl.tiptap-toolbar-api.ts
Labels: type/feature, area/frontend, release/15.3.0

#18462 Fix: Front-end/UX of #18402
  src/Umbraco.Web.UI.Client/src/packages/core/content-type/structure/content-type-structure-manager.class.ts
Labels: type/bug, area/frontend, release/15.3.0

#18453 Feature: RTE blocks validation
  src/Umbraco.Web.UI.Client/src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-rte/property-value-cloner/property-value-cloner-block-rte.cloner.test.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block-rte/property-value-cloner/property-value-cloner-block-rte.cloner.ts
  src/Umbraco.Web.UI.Client/src/packages/block/block/validation/block-element-data-validation-path-translator.controller.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/utils/extract-json-query-properties.function.ts
  src/Umbraco.Web.UI.Client/src/packages/core/validation/utils/extract-json-query-properties.test.ts
  src/Umbraco.Web.UI.Client/src/packages/rte/components/rte-base.element.ts
  src/Umbraco.Web.UI.Client/src/packages/rte/property-value-resolver/rte-block-value-resolver.api.ts
  src/Umbraco.Web.UI.Client/src/packages/rte/types.ts
  src/Umbraco.Web.UI.Client/src/packages/tiny-mce/property-editors/tiny-mce/property-editor-ui-tiny-mce.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/input-tiptap/tiptap-toolbar.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/property-editors/tiptap/property-editor-ui-tiptap.element.ts
Labels: area/frontend, release/15.3.0

#18470 V15: Fix draft being seeded
  src/Umbraco.PublishedCache.HybridCache/Services/DocumentCacheService.cs
Labels: type/bug, release/15.3.0

#18483 Tiptap RTE: Reusable toolbar menu component
  src/Umbraco.Web.UI.Client/src/mocks/data/document/document.data.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/cascading-menu-popover/cascading-menu-popover.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/toolbar/tiptap-toolbar-button-disabled.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/toolbar/tiptap-toolbar-button.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/components/toolbar/tiptap-toolbar-menu.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/style-select/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/style-select/style-select-tiptap-toolbar.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/style-select/style-select.tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/manifests.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/table-tiptap-toolbar-button.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/table/table.tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/tiptap-toolbar.extension.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/font-family-tiptap-toolbar.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/font-family.tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/font-size-tiptap-toolbar.element.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/font-size.tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/text-align-center.tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/text-align-justify.tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/text-align-left.tiptap-toolbar-api.ts
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/toolbar/text-align-right.tiptap-toolbar-api.ts
Labels: type/feature, area/frontend, release/15.4.0

#18488 Data Type: Add mandatory attribute for the property editor field
  src/Umbraco.Web.UI.Client/src/packages/data-type/workspace/views/details/data-type-details-workspace-view.element.ts
Labels: category/ux, area/frontend

#18487 Document collection: align status tag colors
  src/Umbraco.Web.UI.Client/src/packages/documents/documents/collection/views/table/column-layouts/document-table-column-state.element.ts
Labels: category/ux, area/frontend

#18486 Remove Tip tap placeholder text
  src/Umbraco.Web.UI.Client/src/packages/tiptap/extensions/core/rich-text-essentials.tiptap-api.ts
Labels: category/ux, area/frontend

#18500 Makes a few labels friendlier for screen readers
  src/Umbraco.Web.UI.Client/src/assets/lang/en-us.ts
  src/Umbraco.Web.UI.Client/src/assets/lang/en.ts
Labels: category/accessibility, type/feature, area/frontend, release/15.4.0
